### ISSUE TITLE
Default Store Cleanup

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/go-filecoin#1002]
### Description
This issue tracks improvements to the default store, introduced in #851 that remain as followons from that PR.

The default store json encodes data it stores in the datastore kv store.  From @dignifiedquire -- the encoding should instead be cbor for efficiency and consistency with our other data storage

From @dignifiedquire -- PutTipSetAndState should batch write to underlying stores for efficiency.

The method set of the chain.Store interface is a sprawling mess.  It should be cleaned up, and probably split into several interfaces.

**Comment by anorth** [comment]
@ZenGround0 I suggest closing this one. There's no longer any JSON and, while the interface is large, consumers define subsets of it.
