### ISSUE TITLE
Node Initialization and the chainStore.

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/go-filecoin#1008]
### Description
Follow on from PR #851.  Right now node initialization's interaction with the chain.Store is not quite right.  the node `Init` function contains lots of direct writes to the datastore and chain.Store that should probably be abstracted into the chain.Store or an associated interface.  

Also the fact that `Load` is called in `node.Start` means that built but uninitialized nodes do not have a Head.  Maybe this is ok, but it is worth re-evaluating putting `Load` in `node.Build`

**Comment by anorth** [comment]
@ZenGround0 is this something to address in conjunction with #3053? Or out of date enough to close?

**Comment by anorth** [comment]
@ZenGround0 can we close this?

**Comment by ZenGround0** [comment]
I still want to re-evaluate where `Load` goes, but I guess we'll address that if it becomes a problem.
