### ISSUE TITLE
Signature Validation in consensus.RunStateTransition

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/go-filecoin#1010]
### Description

We still don't validate the signature on the block using the miner's public key during block processing.

I think that because of the weirdness of our signature scheme we don't need to check message signatures, but this should be explicitly evaluated and stated in the code.  If this assumption is wrong we need to check those signatures too.

**Comment by mishmosh** [comment]
@shannonwells is this ready to be closed?
