### ISSUE TITLE
Fix unnecessary locking in the chain.DefaultSyncer

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/go-filecoin#1012]
### Description

PR #851 introduced the chain.DefaultSyncer.  One flaw in the current design is that the syncer's main entry point, `HandleNewBlocks` holds a lock while reading from the network.  We need to rethink the concurrency model of the syncer and potentially redesign to avoid this.  

My gut feeling at the moment is that this might actually be a 2 line change simply moving the lock call to a point after the syncer's network bound call has completed.  But this might lead to a subtle bug and should be evaluated more thoroughly.

**Comment by ZenGround0** [comment]
cc @acruikshank who has been making some changes in this direction.

**Comment by anorth** [comment]
@ZenGround0 could you comment on whether this is still relevant and, if so, an updated idea of the fix?

We should probably expand documentation around the fetcher to make it clear that it must be reentrant.

**Comment by ZenGround0** [comment]
The comment decorating this lock access (due to @acruikshank) makes the solid case that this locking is the better thing to do because parallelization can easily lead to fetching the same large dataset over the network multiple times.  AFAIK the fetcher does NOT need to be reentrant right now.

I think there is room for more sophisticated network fetch scheduling (say grabbing multiple forks at a time) but it seems that work is much more significant than this issue and shouldn't be tracked until we evaluate it as a bottleneck for some user facing concern.
