### ISSUE TITLE
use a signature for the ticket

### ISSUE THREAD

**Issue by phritz** [filecoin-project/go-filecoin#1054]
In https://github.com/filecoin-project/go-filecoin/pull/1048/ we introduced per-miner randomness into the ticket in order to fix a bug where all miners would win the challenge simultaneously because the ticket was the same for each. (The ticket at this point is not a signature, it's a hash of the input bytes, so not unique to each miner.)

Per the spec the ticket needs to be a signature: https://github.com/filecoin-project/specs/blob/master/expected-consensus.md#tickets

Make it so.

- [x] Part 1/3 Foundational work (#1795)
- [x] Part 2/3 Disable ticket checking, make tickets cryptographically signed (#2115)
- [ ] Part 3/3 Enable ticket checking (protocol breaking)

**Comment by phritz** [comment]
@shannonwells it looks like 3/3 (enable ticket checking) is done https://github.com/filecoin-project/go-filecoin/blob/675344fd36517ba6ee06990784afc30129378daf/consensus/expected.go#L285 and this issue can be closed. Am I wrong? 

I do see some TODO's in here, eg https://github.com/filecoin-project/go-filecoin/blob/675344fd36517ba6ee06990784afc30129378daf/consensus/expected.go#L278, perhaps that's a reason to keep this open, to ensure we do those TODOs?

**Comment by shannonwells** [comment]
No, it isn't done; the signer pubkey needs to be made part of the block, and checking whether it's a winning ticket currently doesn't include validating that it has been signed.  This is a protocol breaking change.

Once we put the pubkey into the block, we can implement signing blocks in the block mining worker and checking the block signature in consensus/expected,  but that should be a separate issue.
