### ISSUE TITLE
`go-filecoin mpool` is broken

### ISSUE THREAD

**Issue by whyrusleeping** [filecoin-project/go-filecoin#1071]
Misleading title, the command reliably works for the only thing we ever use it for, checking the number of messages in the mempool. But the hashes that it spits out are not actually the hashes of messages in the mempool (actually, they should be all the same hash).

The problem is that 'View' returns `[]SignedMessage`s, and the commands 'type' is an array of `Message` (not signed). This causes unmarshaling to not work right. We get the right number of items, but each of the items is empty because the data coming over the wire has no fields in common with the expected type.

This could probably be prevented by a check in the commands lib, cc @Stebalien

**Comment by anorth** [comment]
I think this is fixed now, mpool and commands were rewritten and we haven't seen any reports of this for ages.
