### ISSUE TITLE
node.SendMessage needs to be smarter

### ISSUE THREAD

**Issue by whyrusleeping** [filecoin-project/go-filecoin#1075]
Currently, this method selects a nonce, broadcasts the message, and moves on. However, if the message fails for any reason, particularly in the event of a nonce collision (as is the prompt of me writing this issue) then the message will never be sent, and the caller will have no idea it didnt happen, the (currently) common pattern of calling SendMessage and then WaitForMessage just hangs forever.

It seems that most callers of SendMessage/WaitForMessage really want to send their message, and care to stick around until it makes it, or get a useful error if it doesnt. We should either change SendMessage to do this, or add a new method to do this for us.

In the case that we encounter a nonce collision, we should re-create and re-broadcast our message until it succeeds.

**Comment by anorth** [comment]
We made a lot of this better with the outbound queue.
