### ISSUE TITLE
ReceiveStorageProposal is incomplete (TODOs etc)

### ISSUE THREAD

**Issue by phritz** [filecoin-project/go-filecoin#1130]

**Comment by anorth** [comment]
@acruikshank for epic #2481?

**Comment by acruikshank** [comment]
@anorth While it's true that that receiveStorageProposal is (and will probably always be in some sense) incomplete, the TODOs that remain are around scaling the miner protocol for large scale mining operations. This isn't in line with the goals of #2481. I'd be up closing this in favor of more pressing issues.

**Comment by anorth** [comment]
Great, let's do that. We'll open new and more specific issues as we approach that work.
