### ISSUE TITLE
Chain sync differentiates between initial 'syncing' vs incremental 'caught up' mode

### ISSUE THREAD

**Issue by whyrusleeping** [filecoin-project/go-filecoin#1160]
We currently don't distinguish between being in a 'caught up' state, where we know roughly the latest state of the network, and a 'syncing' state, where we are trying to catch up to what the current system consensus thinks is the latest state of the system. Certain operations (such as mining, and sending messages) shouldnt be done while syncing as they are almost guaranteed to not provide correct results (though message sending could probably be done).

**Comment by anorth** [comment]
I'm closing this in favour of #1105, which overlaps significantly.

An explicit requirement to distinguish synced and caught-up modes has been removed from the spec, as an implementation decision. #1105 will achieve most of our goals here. It doesn't answer all of @phritz 's questions, but we don't need to answer them all at once.

The need for secure bootstrapping is well noted and I'll factor that out into other issues. Right now, we workaround by starting with "trusted" bootstrap nodes, but that won't last.
