### ISSUE TITLE
the `miner create` command should be porcelain

### ISSUE THREAD

**Issue by laser** [filecoin-project/go-filecoin#1161]
### Description

The `miner create` command blocks until the `createMiner` message has been included in a block. This is different than `miner update-peerid` (and other commands), which return the cid of the created message (leaving the user to `message wait <cid>` as a second step).

This is because `miner create` implements a user flow rather than a single action. The user issues a create miner message on the network, the command waits for a block containing the create miner transaction, and then that result  is stored in config.

We will continue to need more and more commands like this that perform higher level actions on behalf of the user, but we should not design the system around these complex tasks. We will introduce the concept of porcelain, to distinguish higher level actions that depend on multiple api calls, from the lower level 'plumbing' commands that mirror the api.

### Acceptance criteria

- create a `porcelain` package subpackage of `commands`.
- miner create (and other porcelain commands) have no unique api calls. All functionality is implemented with api calls representing by existing plumbing commands.

### Where to begin

- message send
- message wait
- config

**Comment by phritz** [comment]
@rosalinekarr whats the status with this one?
