### ISSUE TITLE
Versioned Address Prefix

### ISSUE THREAD

**Issue by acruikshank** [filecoin-project/go-filecoin#1201]
### Description

Filecoin should support an arbitrary number of networks. Change the current 'fcX', 'tfX' address prefix to 'fMN' where M is the network number and 'N' is the protocol. Old 'fc' addresses will be network 0, and 'tf' addresses will be network 1. The protocol will be 0 until ID addresses are implemented. This story does NOT require of Var32encoded integers for the network or protocol.

### Acceptance criteria

1. All addresses in go-filecoin begin with 'f00' or 'f10'.
2. Address validation rejects addresses that do not begin with the new format.
3. All tests pass.

### Where to begin

Start in `address/address.go`

**Comment by ZenGround0** [comment]
@acruikshank is this closed out by new address spec?

**Comment by acruikshank** [comment]
New spec invalidates this work.
