### ISSUE TITLE
Multibase encoding for addresses

### ISSUE THREAD

**Issue by acruikshank** [filecoin-project/go-filecoin#1203]
### Description

Filecoin addresses consist of a prefix and a key. Currently the key is always base32 encoded. In keeping with PL philosophy, the key should be Multibase encoded. The default encoding should be `Base58BTC`.

### Acceptance criteria

1. All addresses within go-filecoin must be multibase encoded.
2. Address decoding validates keys have a valid encoding
3. Addresses are decoded in such a way that addresses with equivalent keys encoded in different bases are decoded to equivalent internal structs.
4. BCH error correction works with new encoding.

**Comment by ZenGround0** [comment]
@acruikshank is this closed out by new address spec?

**Comment by acruikshank** [comment]
Invalidated by new address spec.

**Comment by lidel** [comment]
Mind linking to the new address spec? :)

**Comment by frrist** [comment]
Address Spec here: https://github.com/filecoin-project/specs/blob/master/address.md
