### ISSUE TITLE
ID Addresses

### ISSUE THREAD

**Issue by acruikshank** [filecoin-project/go-filecoin#1205]
### Description

Not all Filecoin addresses represent AccountActors with public keys. Add a new address protocol, '1', that represents a simple id. ID addresses can be any byte string. As ID addresses are not expected to be communicated over unreliable channels, they do not need the BCH error detection that account addresses require. All addresses that are not associated with a wallet must be ID addresses.

### Acceptance criteria

1. Addresses with a `f01` prefix pass validation.
2. `f01` addresses do not contain BCH codes.
3. Every go-filecoin address that does not represent a public key is an ID address.

### Where to begin

`address/address.go`

**Comment by ZenGround0** [comment]
@acruikshank is this closed out by new address spec?

**Comment by acruikshank** [comment]
Invalidated by new address spec.
