### ISSUE TITLE
Var32encoded ints for addresses

### ISSUE THREAD

**Issue by acruikshank** [filecoin-project/go-filecoin#1206]
### Description

In order to future proof Filecoin addresses, the address network and address protocol should have a high upper bound. Implement the var32encoding specified here: https://github.com/filecoin-project/specs/pull/19, to permit numbers up to 2^70-1 for both numbers.

### Acceptance criteria

1. Address creation should permit any uint64 number for a network.
2. Addresses with any network < 2^70 must validate.
3. Address creation and validation for addresses with protocols > 1 should fail with a message that the protocol is unknown, not that the format is invalid.

### Where to begin

`address/address.go`

**Comment by ZenGround0** [comment]
@acruikshank is this closed out by new address spec?

**Comment by acruikshank** [comment]
Invalidated by new address spec
