### ISSUE TITLE
Secure Deal Protocol

### ISSUE THREAD

**Issue by rkowalick** [filecoin-project/go-filecoin#1211]
### Description

Currently, the the miner responding to a storage deal does not actually sign the response. The miner must sign the response to allow deal arbitration.

### Acceptance criteria

1. Miner signs deal response with a signature that validates against the miner's miner actor's owner.
2. Client validates the signature and rejects the deal if it's invalid (reject only does what storage deal errors currently do).
3. Signing and validation are tested.

**Comment by anorth** [comment]
FYI @acruikshank. This seems like something that should be in scope for the current storage protocol epics.
