### ISSUE TITLE
we are getting circleci notifications for all branches, not just master

### ISSUE THREAD

**Issue by phritz** [filecoin-project/go-filecoin#1242]
### Description

pretty sure we are using circle 1.0 syntax to specify  branch filtering but it is maybe flaky in 2.0 and there is no 2.0 specific syntax. see https://discuss.circleci.com/t/circleci-2-0-notifications-webhooks/19075/16. i think the right course of action is to file a bug with circle ci since we are a paid customer. include our config file (from .circleci at top of our repo). 

relevant config:

https://github.com/filecoin-project/go-filecoin/blob/7b145d5f024db3f3600315a9df71a615ca77c1e9/.circleci/config.yml#L167

**Comment by phritz** [comment]
@ognots is this something you can look into?

**Comment by ognots** [comment]
yes

**Comment by ognots** [comment]
still not supported in CircleCI

keeping this branch open to test https://github.com/filecoin-project/go-filecoin/compare/bug/circle-notifications
