### ISSUE TITLE
TestRetrievalProtocolHappyPath is flaky

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/go-filecoin#1257]
### Description

The commit sector message takes too long to make it to the chain while setting up a storage deal: https://circleci.com/gh/filecoin-project/go-filecoin/5429?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by phritz** [comment]
this test was deleted, yay https://github.com/filecoin-project/go-filecoin/blob/c8fae50f902f36635d2568a097917d6b8ce428a9/protocol/retrieval/retrieval_protocol_test.go#L18
