### ISSUE TITLE
Document how to operate a filecoin storage miner

### ISSUE THREAD

**Issue by whyrusleeping** [filecoin-project/go-filecoin#1312]
### Description
For the 'Filecoin Node Operation' spec, we need to document how running a storage miner works. Roughly, this is a description of how the system works and ties together whats discussed in the mining spec, the storage market spec, and the 'make deal' network protocols document. It does not need to go into detail into any of the processes.

### Where to begin
'operation.md' in the spec
Talk with @whyrusleeping before starting to get an idea of whats needed here.

**Comment by anorth** [comment]
The go-filecoin wiki contains the raw commands for getting a miner going. I think this issue is asking for higher level documentation, but I don't think go-filecoin is the right place for that. I'll close this issue shortly in the name of focussing issues here on development.
