### ISSUE TITLE
Merklize messages in block

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/go-filecoin#1324]
### Description
We currently store a slice of messages directly in the block.  From the [spec](https://github.com/filecoin-project/specs/blob/master/mining.md#block-creation) and a long living [TODO in the code](https://github.com/filecoin-project/go-filecoin/blob/master/types/block.go#L50) it is clear that this will need to change to look more like the storage of the block's state.  Messages and receipts need to be put in a merkle tree like structure and fetched from the node's ipld data store when the actual messages and receipts are needed.  

### Acceptance criteria
Update the messages and receipts fields in the block to a merkle root without breaking things.

### Risks + pitfalls
Deciding on serialization of messages will perhaps take thinking to get right in the same way we have put a lot of thinking into the VM actor storage format.  Maybe that thinking can be reused here cc @acruikshank.  Our choices here could have effects on how message formats are constrained as the system evolves.

If we stop sending messages around with blocks we need to handle message fetching so that nodes can perform the same operations that they do today, in particular applying messages during consensus checks.  Message fetching has the same potential for DOS as block fetching and should be treated with similar care.  Very likely the chain syncer should handle message fetching alongside block fetching.

### Where to begin
1. Decide how to serialize messages (and receipts) into a merkle tree.
2. Figure out how message fetching should work exactly.

Good idea to talk with at least @whyrusleeping and @acruikshank before starting on this.

**Comment by anorth** [comment]
Done
