### ISSUE TITLE
Signature code and tests should be in one, reasonable place.

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/go-filecoin#1326]
### Description
Right now signature code and tests is scattered among `types` and `wallet`.  This has led to a situation where to prevent import cycles the tests for `types.Signature` currently live in `wallet`.  This is not ideal.  This is also described in this [comment](https://github.com/filecoin-project/go-filecoin/blob/master/wallet/signature_test.go#L1)

### Acceptance criteria
Signature packages are rearranged so that all signature functions can be in the same package as their tests. 

### Where to begin
Probably the way forward is to separate out the ability to generate signatures from the wallet backend and group this alongside the function for verifying signatures.  Then `wallet` and `type/signed_message` can import this `signature` dependency.

**Comment by anorth** [comment]
Ancient history
