### ISSUE TITLE
designdocs need to be accessible by the world

### ISSUE THREAD

**Issue by phritz** [filecoin-project/go-filecoin#1360]
There are various designdocs floating around in google docs. Some of them are no longer relevant but some are (eg, integer encoding). We should move them to GH and have a policy and process for design collaboration that is both privacy-preserving and efficient.

**Comment by anorth** [comment]
Assigning to @mishmosh. We have already made some recent ones available, but some older ones are still private. @mishmosh could you propose a criteria for calling this issue "done".

**Comment by anorth** [comment]
Our design docs are not in this repo, but most since open-source are available at https://github.com/filecoin-project/designdocs
