### ISSUE TITLE
OSX build jobs on CI take 3x as long as Linux job

### ISSUE THREAD

**Issue by laser** [filecoin-project/go-filecoin#1422]
### Description

Our `build_macos` build jobs routinely take 3x as long as the related `build_linux` job. 

See [here](https://circleci.com/workflow-run/113c0e50-3f15-445a-bf8f-b5b321f505e6) for an example.

**Comment by anorth** [comment]
@ognots @travisperson WDYT about closing this one. Is it actionable?

**Comment by ognots** [comment]
the gap between mac and linux builds has narrowed. on average, the mac builds are now only 30% slower than linux builds, no where near what this issue was reporting. this speed difference would roughly be as expected in CircleCI.

closing this issue
