### ISSUE TITLE
iptb plugins should use a datastore for frequently accessed data

### ISSUE THREAD

**Issue by frrist** [filecoin-project/go-filecoin#1467]
### Description
When using the go-filecoin iptb plugins as packages it will be useful to have access to fields like minerAddress, minerOwnerAddress, and defaultAddress without having to run a command everytime. We can accomplish this by storing the information in a datastore on the plugin.

### Acceptance criteria
The following fields are stored in a datastore on the iptb filecoin plugin:
- minerAddress
- minerOwnerAddress
- defaultWalletAddress

### Tricky Bits
The docker plugin will be tricky as the containers may be remote to where IPTB is being called from, this may require a change/addition to the IPTB core interface.

### Where to begin
https://github.com/filecoin-project/go-filecoin/blob/master/tools/iptb-plugins/filecoin/local/localfilecoin.go#L35-L40

https://github.com/filecoin-project/go-filecoin/blob/master/tools/iptb-plugins/filecoin/docker/dockerfilecoin.go#L51-L62

**Comment by anorth** [comment]
@travisperson do you consider this something worth fixing? If not, please close.
