### ISSUE TITLE
Plumbing/Porcelain API Refactor

### ISSUE THREAD

**Issue by phritz** [filecoin-project/go-filecoin#1469]
This is a tracking issue for this refactor of the API into plumbing and porcelain, *none of which depends on node*

Why not depend on node: https://github.com/filecoin-project/go-filecoin/issues/1223#issuecomment-433764709. An additional reason to not have api depend on node is to make it easier to write a light client, or to integrate just some pieces of filecoin into another app (eg, just message sending and waiting). In these cases you might not want to instantiate a full node, just the pieces you need.

Why split into plumbing/porcelain split is articulated below. 

There are still some open questions eg
- mechanically how to do the refactor. Proposal: create a new api package `api2` and start moving stuff over. api/2 will have to co-exist for a while but an implementation should live in exactly one of them at any time.
- do we want to continue to have sub-interfaces eg message client etc or do we want one api? proposal: it's strictly more stuff to pass around with multiple interfaces and porcelain is going to consume random subsets of interfaces. Let's just leave it as one big api interface and let consumers define the subset of it they need in the consuming package consistent with https://github.com/golang/go/wiki/CodeReviewComments#interfaces. We can still define implementations in separate files for convenience, maybe even separate packages. If this gets unwieldy we can go back to the current strategy which is sub-interfaces.
- what to do about parts of the api that seem like they *must* depend on node? proposal: break them out into a separate, higher level api which is the control surface. 

Note that this work started with https://github.com/filecoin-project/go-filecoin/pull/1224.

**Comment by anorth** [comment]
@rosalinekarr would you do the honours of closing this if it's complete?
