### ISSUE TITLE
Complete Payment Broker transition to Porcelain

### ISSUE THREAD

**Issue by acruikshank** [filecoin-project/go-filecoin#1489]
### Description
Any interaction between API callers and builtin actors is accomplished by sending a message to or querying the actor. We have general purpose plumbing for sending and querying, so all actor communication should be plumbing. The one catch is that Payment Broker command that deal with vouchers need some additional logic to decode and sign vouchers.

This task is to find an appropriate place to put the voucher decode and signing logic, and then use this logic to convert the remaining `paych` commands to porcelain.

### Acceptance criteria
1. The signing and decode (multibase.Decode) logic must be implemented either as part of the plumbing API, or some other helper code specifically created to support plumbing API calls (not in the PaymentBroker actor). The task is to create a good design for this.
2. The `paych voucher`, `paych redeem` and `paych close` commands are implmented in porcelain.

### Risks + pitfalls
The precise definition of porcelain and location of porcelain code ~~is under desi~~ [updated Jan 23— @mishmosh] was under design when this issue was created, but design is now complete. See https://github.com/filecoin-project/go-filecoin/pull/1524, the first PR in the series, for reference.

**Comment by rosalinekarr** [comment]
Dup of #1942
