### ISSUE TITLE
output of config command is enclosed in double quotes, which makes it hard to export to a variable

### ISSUE THREAD

**Issue by pooja** [filecoin-project/go-filecoin#1525]
### Description

Running `export MINER_ADDR=`go-filecoin config mining.minerAddress`` doesn't work because the output of `go-filecoin config mining.minerAddress` is enclosed in quotes. There are other similar commands in go-filecoin that do not enclose their output in quotes, which makes it easy to export the output to a variable that can be used in other parts of the workflow.

We would like to change the output of `go-filecoin config mining.minerAddress` so that it is not enclosed in double quotes. This should be super easy, but is a minor UX improvement that will go a long way!

### Acceptance criteria

Running `export MINER_ADDR=`go-filecoin config mining.minerAddress`` properly exports a miner address to the var `MINER_ADDR` such that `MINER_ADDR` can be used in other commands where a miner address is required.

**Comment by anorth** [comment]
Note: we're standardising JSON everywhere. We could add a `--raw` flag which strips quotes from bare string outputs and similar things. Or `jq` can do the same .
