### ISSUE TITLE
Notes on initial user experience

### ISSUE THREAD

**Issue by haadcode** [filecoin-project/go-filecoin#1557]
I finally had the time to give go-filecoin a spin to try it out. I took these notes to describe the steps I took following the instructions in the repo(s). These notes are from the perspective of a user who's completely new to the project and tries to get a feel for Filecoin for the first time. Fresh eyes.

I hope these will help to catch some low-hanging fruits to improve initial user experience. Thank you for providing access to test it, here's to a great 2019 🎉 😃 

1) Install from binaries

- In https://github.com/filecoin-project/go-filecoin/wiki/2.-Getting-Started#installing-from-binary

3) Start
- https://github.com/filecoin-project/go-filecoin/wiki/2.-Getting-Started#name-your-filecoin-node
  - do I need to restart the daemon for the nickname to take effect?

- Open Dashboard, seems to be starting
  - I can see my nickname, so I guess no restart needed

- Open Block Explorer, doesn't seem to work :/
  - "Something went wrong", "Chain could not be loaded"
  - Close the dialog
  - "No Chain (something probably went wrong)"
  - "Chain" and "Best Block" give the error, can see some actors in "Actors" tab

- Back to Dashboard
  - In the wiki, it says "If your node is in consensus with all other nodes, you should see the tipset indicator colored green."
  - I see green, orange and red 🤔 There's a question mark icon, so I click the dots, but nothing happens
  - I click on the "tipset hash" of my node (its background is green, says "(2 blocks)" after it)
    - Get a 404 (url is http://nightly.kittyhawk.wtf:8000/blocks/zDPWYqFD1KJ28Qv6yvwLiyV2iVHgkKjZN8sG1Epgj4MHC75sUP5C)
  - Nothing else I can do or click it seems...

4) Get some FIL
- https://github.com/filecoin-project/go-filecoin/wiki/2.-Getting-Started#get-fil-from-the-filecoin-faucet

- I run the steps listed in Wiki up to "4. To verify that the FIL has landed in your wallet, check your wallet balance"
  - `0` 😢
  - I guess no FIL this time

- I run `go-filecoin swarm peers` and see 2 peers:
```
/ip4/3.81.214.21/tcp/9000/ipfs/Qmd6xrWYHsxivfakYRy6MszTpuAiEoFbgE1LWw4EvwBpp4
/ip4/3.81.214.21/tcp/9081/ipfs/QmVR3UFv588pSu8AxSw9C6DrMHiUFkWwdty8ajgPvtWaGU
```
- I run `go-filecoin swarm <peer ID>` and both connect

5) Start mining
- https://github.com/filecoin-project/go-filecoin/wiki/3.-Mining-Filecoin#start-mining

- Run step 2 `go-filecoin miner create 10 100 --from=${MINER_OWNER_ADDR}`
  - `Error: price option is required`
- Ok, run `go-filecoin miner create 10 100 --from=${MINER_OWNER_ADDR} --price=666`
  - `Error: invalid gas limit`
- Ok, run `go-filecoin miner create 10 100 --from=${MINER_OWNER_ADDR} --price=666 --limit=1`
  - Crunching.... got a CID!
- Run `go-filecoin mining start`
  - `Started mining` 🎉

- Block Explorer still erroring, so trying the command line

- Follow instructions in "Create an ask", up to step 3 (run `go-filecoin miner add-ask --from=$MINER_OWNER_ADDR $MINER_ADDR 2.5 5`)
  - `Error: price option is required`
  - run `go-filecoin miner add-ask --from=$MINER_OWNER_ADDR $MINER_ADDR 2.5 5 --price=1`
  - `Error: invalid gas limit`
  - run `go-filecoin miner add-ask --from=$MINER_OWNER_ADDR $MINER_ADDR 2.5 5 --price=1 --limit=1`
  - Got a CID!

- Reading "Accept a deal and get paid"
  - It talks about what things are, but I have no idea, after reading it, how to accept a deal or get paid :/

6) Stop mining

**Comment by mishmosh** [comment]
Closing, feel free to reopen with any further notes.
