### ISSUE TITLE
Model for change

### ISSUE THREAD

**Issue by mishmosh** [filecoin-project/go-filecoin#1576]
This is a placeholder issue, edit directly when ready. Some notes from Jan 8 below:

* this is a lot of work, ~2 eng weeks minimum
* maybe preceded by rationalizing data encoding
* lots of prior art in ipfs
* includes migrations, versioning data structures, forking

First step:
* Understand IPFS repo migrations and write down what we should/shouldn't borrow for filecoin.
* Write down ideas from @whyrusleeping for how data goes on-chain.
* Get 1 and 2 reviewed.
* Write down how things work today and point out what does & doesn't work. Thoroughly understand how messages are encoded. Eg: why are we using CBOR, are we supposed to be using CBOR, are there issues with the reformat library, incomplete areas of the reformat library.

**Comment by travisperson** [comment]
This doesn't have too much to do with model for change, in terms of implementation, but something I would like to get some ideas about from @whyrusleeping about is how upgrading miners might work with regard to the downtime they will incur, or how to deal with faulty migrations / rollbacks / etc. It's something we will have to deal with if we are running miners for the devnets, and something users will absolutely have to figure out how to deal with. Any insight we can provide I'm sure would be greatly appropriated.

**Comment by mishmosh** [comment]
@travisperson we talked briefly about miner downtime today. Initial ideas include separating the download&paramfetch&check&install (non-disruptive) from restart (disruptive) process and a set of "grace period" blocks after upgrades.

After walking through this problem in more detail, it is much much bigger than the "2 weeks" quoted in the original comment.

**Comment by whyrusleeping** [comment]
I think a good model here would be for us to have a `go-filecoin update` command that connects to the running daemon, asks it to safely shutdown, replaces the binary, does any migrations needed, and then starts the daemon back up again (if possible). See `ipfs update` for some inspiration, but i think we can be even smarter than that.

**Comment by anorth** [comment]
The repo-migration part of this placeholder is now captured in epic #2471

**Comment by anorth** [comment]
And the protocol upgrade part epic #2472.

**Comment by anorth** [comment]
I am closing this issue in favour of the two epics, both of which refer to this to capture the recent comments.
