### ISSUE TITLE
proof-of-spacetime faults should appear on-chain

### ISSUE THREAD

**Issue by laser** [filecoin-project/go-filecoin#1583]
### Description

Currently, the faults returned by the proof-of-spacetime generation routine are not posted to the blockchain. The [spec demonstrates that they should be](https://github.com/filecoin-project/specs/blob/14a7719d218ef616e40088bccd0b405b41f8b2eb/actors.md#submitpost). These faults are required by the proof-of-spacetime verification routine.

### Acceptance criteria

- Ensure that the faults returned by the proof-of-spacetime routine are included as "parameters" in the `submitPoSt` message.
- Ensure that faults produced by rust-fil-proofs `generate_post` make their way into `submitPoSt` message.
- Ensure that faults obtained from `submitPoSt` message make their way to rust-fil-proofs `verify_post`.

### Developer Notes

- After speaking with @dignifiedquire, I think that we can port his [bitsets](https://github.com/filecoin-project/bitsets) project to Go and use that abstraction to represent faults on-chain.

### Open Questions

~The spec says that `submitPoSt` message should include a slice of `FaultSet`. I've [asked elsewhere](https://github.com/filecoin-project/specs/issues/119) for someone explain this parameter to me. We should wait on implementing this feature until my questions are answered.~

**Comment by laser** [comment]
This issue is still blocked on Cryptolab designing and implementing faults.

**Comment by laser** [comment]
@ZenGround0 - I'm going to assign this issue to you since you are going to be the person who transmutes the array of uint64-indices into a Golang BitField. Feel free to reassign it if you're not the right person for this.

**Comment by anorth** [comment]
#2889 is the go-filecoin side of wiring for this. Let's leave this issue representing any work to get actual fault information from the prover, when implemented.

**Comment by anorth** [comment]
Made redundant by new spec.
