### ISSUE TITLE
car file reader tool

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/go-filecoin#1591]
### Description
There should be a simple way to open up a car file and see its structure.  Something like an online ASN1 parser.  We want to be able to manually inspect a given genesis.car for debugging purposes.

**Comment by anorth** [comment]
This would be great, but not in this repo. We expect to use CAR files more heavily for chain/VM validation tools too. cc @frrist

**Comment by frrist** [comment]
@ZenGround0 the go-car package has a cli that gets pretty close to this:
https://github.com/ipfs/go-car/blob/master/car/main.go
```
NAME:
   car - A new cli application

USAGE:
   car [global options] command [command options] [arguments...]

VERSION:
   0.0.0

COMMANDS:
     header   
     ls       
     verify   
     help, h  Shows a list of commands or help for one command
```
