### ISSUE TITLE
Actors store their public keys

### ISSUE THREAD

**Issue by frrist** [filecoin-project/go-filecoin#1607]
### Description
To accomplish this we will add a field to the account actor to store their public key. An Actor can be created by sending funds to the actors public key -- this is how the public key of an actor makes it on chain. This implies that changes will need to be made to message sending such that a message can be sent to the address of an actor or the public key of an actor. This removes the ambiguity around new actor creation (we don't have to do the weird 'upgrade' thing, as actors will have unambiguous addresses).

### Acceptance criteria
- Account Actor has a field to store its public key.
- When the message with the public key is process (mined) the public key gets placed into the actors internal state.
- Messages can be sent to the address of an actor or the public key of an actor.
  - The public key goes in the `To` field of the message.

### Design Doc
https://docs.google.com/document/d/1W6eKt5kuLF9zZmwIdiQl2-UAs2VJg-KqO3ti2fYVN_M/edit

**Comment by phritz** [comment]
deprioritized for now, moving back to backlog

**Comment by anorth** [comment]
Closing this issue in favour of a new one when we update actors to match the new spec.
