### ISSUE TITLE
Actors can be reference by their ID

### ISSUE THREAD

**Issue by frrist** [filecoin-project/go-filecoin#1608]
### Description
ID is a monotonically increasing value that is generated when an actor is created. An Actor may be referenced by its ID, its Address or its Public Key. A map of ID -> Actor and a map of PublicKey -> ID will need to be maintained.
- Said maps will allow for:
  - Key cycling, it is common practice to cycle out keys every so often for security reasons.
  - ID reuse, saves space
- Said maps should not be kept on chain, they should instead be built by a filecoin node during its sync process.

### Acceptance criteria
TODO

**Comment by anorth** [comment]
The new spec lays out a concrete mechanism for this with the InitActor. I'm closing this in favour of new issues when we come to implement the new actors.
