### ISSUE TITLE
Filecoin Automation & System Toolkit (FAST)

### ISSUE THREAD

**Issue by frrist** [filecoin-project/go-filecoin#1612]
### Goal
Our goal here is to develop a standardized method for initializing and running go-filecoin that remains agnostic to the environment go-filecoin runs in (e.g. system process with PID, docker container, or kubernetes pod).  We will develop a common library of go-filecoin code that can be used in daemon testing, cluster initialization, and other applications like network randomization that involve managing nodes, running commands against them, and observing their state. This common library will be written in go, will utilize functionality that already exists in IPTB, and will be referred herein as the "Filecoin Automation & System Toolkit" or FAST.

### Problem
The need for developing this library stems from having duplicate "wrapper" methods for orchestrating and testing go-filecoin. The go-filecoin testing and orchestration code is littered with  methods that perform near identical tasks. For example, the [go code for testing miner creation](https://github.com/filecoin-project/go-filecoin/blob/57a08f3f635a72a5381707cba4bc7767d4a360d2/commands/miner_daemon_test.go#L191-L231) and the [bash code for setting up miners in infrastructure clusters](https://github.com/filecoin-project/go-filecoin-infra/blob/2dd6e326ffa1340d4906bddf298c3b5306ff8b53/terraform/modules/aws/ec2/scripts/docker_user_data.sh#L180-L208) both create filecoin miners, update their peerID's, and configure them to use the generated miner address. The only difference between these pieces of code is that one is written in bash and the other go. Code written this way is fragile and has a high overhead of maintainership when api's/commands change. Furthermore, there is yet another [separate bash library](https://github.com/filecoin-project/go-filecoin/blob/57a08f3f635a72a5381707cba4bc7767d4a360d2/functional-tests/retrieval#L125-L163) used to test filecoin clusters that shares functionality with the aforementioned bash script used to deploy clusters. Maintaining 3 separate orchestration/test suites like this is infeasible. 

### Solution
The solution is to use **IPTB** as the core interface for process management. 
First, we will write **plugins** for IPTB that can be used to control a filecoin process in a specific environment (e.g. linux proc or docker container). All complexity of orchestrating a filecoin process in a specific environment is deferred to the IPTB plugin ([local proc plugin](https://github.com/filecoin-project/go-filecoin/tree/7abce71c75df84cd28fe49bd4060665ec89e09d9/tools/iptb-plugins/filecoin/local), [docker plugin](https://github.com/filecoin-project/go-filecoin/tree/7abce71c75df84cd28fe49bd4060665ec89e09d9/tools/iptb-plugins/filecoin/docker)). Next, we will create a set of **IPTB Command Wrappers** that can be used to control filecoin processes without having to account for the environment the process is running in, this means the wrapper methods can be used for both local process orchestration and docker container orchestration interchangeably. Some examples of these commands could be, CreateMiner, AddAsk, CreateGenesisNode, or MakeDeal -- basically any command or set of commands that could be issued to a filecoin process. Lastly, we will replace TestDaemon calls, Cluster initialization commands, and Cluster Functional Test methods with this shared set of command wrappers, this will create a common library of code that can be used to control filecoin in any environment we write a plugin for -- this is the Filecoin Automation Toolkit. 
A diagram showing the relations of these pieces is shown below:
![IPTB Diagram (2).png](https://images.zenhubusercontent.com/5ab13f7a4b5806bc2bcba4ae/54b763ee-c32c-4cbf-ae44-ab180411b4d5)

### Anti-Requirements
It should be easy to isolate the rolls of the development wg and the roles of the infrastructure wg. We will assume there is already deployed infrastructure in place. These things include/can be thought of as: VMs that filecoin nodes can be installed on, network between the VMs. Whatever infrastructure is in place will also be usable with things like IPFS and Libp2p. We do not intend to cover how these things will function. 

FAST will only orchestrate filecoin processes, while it is true that this concept could be used to manage things like the filecoin-aggregator we will not do attempt to do that here.

### Acceptance Criteria
- Docker and Local Process (Linux & OSX) IPTB plugins exist and have unit tests.
- A command library that:
  - Works in filecoin daemon tests
  - Works in filecoin functional tests
  - Works in Cluster initialization and automation
  - Can be used to control local filecoin process(s)
  - Works at the same level as filecoin commands.
  - Minimizes dependencies on go-filecoin internals.
  - Is easy to write commands for in addition to writing commands that themselves are composed of lower level commands (**TODO** this is a similar concept to plumbing vs porcelain, however WE WILL NOT BE USING THAT TERMINOLOGY HERE, the **TODO** is to figure out the terminology we will use to describe these relations among commands -- e.g. actions == command, story == set of commands) 
  - Makes it easy to process command outputs, e.g. json and ndjson output should automatically be decoded into a domain object, callers of these methods should **rarely* need to parse command outputs.

- TODO add more as they become apparent

**Comment by anorth** [comment]
@travisperson I don't think we need an epic for FAST any more. It's served its purpose and FAST is in use. We have a tag for identifying FAST-related issues. A future epic could focus on the use of FAST for a specific purpose, but should have a clear and achievable "done" state.

Please close this if you agree.
