### ISSUE TITLE
Expose block reward as a command

### ISSUE THREAD

**Issue by mslipper** [filecoin-project/go-filecoin#1614]
### Description

Speaking with Fritz yesterday, it looks like the block reward is constant right now. One of the stats we'd like to render on the dashboard is the current block reward. It's trivial for me to hardcode the block reward in the dashboard, but a potentially better solution would be to expose it as part of the go-filecoin API. Perhaps something like this:

`go-filecoin params block-reward <block-height>`

What does the team think? I can potentially take this as a good first ticket if there's interest.

**Comment by anorth** [comment]
@mslipper is this still something you need?

The specific issue should be made redundant by #3098, which should instead have this support.
