### ISSUE TITLE
Implement FAT Series around FAT Actions

### ISSUE THREAD

**Issue by frrist** [filecoin-project/go-filecoin#1631]
### Description
Once #1629 gets moving along we can begin to implement yet an even high level set of wrapper methods herein referred to as **Series**. Series will be made up of multiple Actions, and will allow for complex operations to be performed against filecoin process(s). Some examples of Series include:
- `EnsureCreateMiner`: the method will get filecoin, create a miner, and ensure the create miner message is successfully mined.
- `MakeDealWithMiner`: the method will create an ask with a miner, propose a deal to the miner with a client, and ensure the deal is successfully mined.

### Acceptance criteria
- Enough Series are written such that the functional retrieval test can be composed of calls to story commands.
- [x] Genesis Series
- [ ] Retrieval Series
- [ ] Storage Series

**Comment by anorth** [comment]
@travisperson is this about done now that FAST is usable? Could remaining work be broken out into a tighter scoped issue?

**Comment by travisperson** [comment]
Ya, I think the larger concern of this issue has been address. A lot of this work was defined prior to FAST being implemented and we didn't really know what we needed. These series could be written, but I don't think they are strictly needed except to showcase as an example.

If we want these we can open additional issues, for now I think we can close this out.
