### ISSUE TITLE
[Security] Separate 'global' and 'local' blockstores

### ISSUE THREAD

**Issue by whyrusleeping** [filecoin-project/go-filecoin#1658]
It could be that we are already doing this properly, but just in case, i'm filing this issue.

We need to very clearly separate 'public' data, and 'private' data to ensure that it doesnt leak between these bounds. 

Public data includes:
- All blockchain data
  - Blocks
  - Messages
  - State tree
  - etc
- Any other data we want other peers to be able to ask us for

Private data should be assumed to be everything else. Anything we put in the CborIpldStore (which really could use a rename, and relocation to a better package) should be intentionally put into one of these categories. Some of the 'private' data isnt necessarily bad to have leak (most of it nobody will really care about), but some things (like the payment vouchers in storage deal proposals) might produce inconvient outcomes if the data falls into the wrong hands.

Note: data placed into the public cboripldstore isnt discoverable by other parties (we don't advertise any content like ipfs does) so they would have to know its hash in order to request it (very improbable for some data).

**Comment by anorth** [comment]
-> #3481
