### ISSUE TITLE
Add feedback on user experience

### ISSUE THREAD

**Issue by mishmosh** [filecoin-project/go-filecoin#1689]
### Description
This is an organizing thread for feedback on the experience of running, storing, and mining on go-filecoin. 

#### Alternatives
* Direct PRs are also welcome. But if you'd like to discuss the idea first, or simply submit feedback without making the change yourself, this issue is a good place.
* Feedback on the experience of _contributing_ goes in #1690.

### Acceptance criteria
As actionable problems or patterns are identified, we will spin them out into separate issues.

### Where to begin
* Add observations and/or suggestions via comments below.
* As feedback comes in via other channels, we will also include here.

**Comment by waynewyang** [comment]
I suggest with [Getting-Started](https://github.com/filecoin-project/go-filecoin/wiki/Getting-Started)

-  original content
```
3. The faucet will provide you with a message CID. The message should be processed in about 30 seconds. You can run the following command to wait for confirmation:

go-filecoin message wait ${MESSAGE_CID}
```

- problem

```
Now everyone in devnet is Full Node, when users delete the ~/.filecoin or run daemon firstly, it will cost much time to sync filecoin blockchain.

so the wait message time will be longer longer, not 30 seconds
```

- I suggest that add some info 

    - check the lastest block throught [block explore](http://user.kittyhawk.wtf:8000/)
    - check your local blockchain data as below, if it's the same with  [block explore](http://user.kittyhawk.wtf:8000/), The message should be processed in about 30 seconds. 
```
waynewyang:go-filecoin waynewyang$ go-filecoin chain head
[{"/":"zDPWYqFCuUYDs5C5WtWrncFoLdmzT2ezfJBZ9fugeMiKb91M4P1r"}]
waynewyang:go-filecoin waynewyang$ go-filecoin show block zDPWYqFD49b3FhVDbrWRfkVuvDeM46CQX1A5BM7C8HFSGDkig62c
Block Details
Miner:  fcq4npmz3uq4f4guvs00l7j6pluat3rc678vfff94
Weight: 362709.466
Height: 15242
Nonce:  0
```
