### ISSUE TITLE
Decouple the `Address` and `Wallet` commands

### ISSUE THREAD

**Issue by frrist** [filecoin-project/go-filecoin#1693]
### Description
Currently the `address` and `wallet` commands have overlap, i.e.:
```
USAGE
  go-filecoin wallet - Manage your filecoin wallets

  go-filecoin wallet

SUBCOMMANDS
  go-filecoin wallet addrs                 - Interact with addresses
  go-filecoin wallet balance <address>     - 
  go-filecoin wallet export <addresses>... - 
  go-filecoin wallet import <walletFile>   -
```
```
USAGE
  go-filecoin address - Interact with addresses

  go-filecoin address

SUBCOMMANDS
  go-filecoin address lookup <address> - 
  go-filecoin address ls               - 
  go-filecoin address new              -
```

This is redundant as prefixing the `address` command with `wallet` doesn't give us an additional functionality, e.g. there is no difference between calling `go-filecoin wallet addrs ls` and `go-filecoin address ls` -- it's just confusing. 

### Acceptance criteria
- Remove `addrs` subcommand from the `wallet` command s.t. the `wallet` command and `address` command have zero overlap in functionality.
- Update any affected tests.

### Where to begin
https://github.com/filecoin-project/go-filecoin/blob/master/commands/address.go#L14
https://github.com/filecoin-project/go-filecoin/blob/master/commands/address.go#L26

**Comment by rosalinekarr** [comment]
Some of this work is likely going to conflict with some of my work on porcelain/plumbing. Just ping me if you start working on any of this and we can discuss specifics.

**Comment by rosalinekarr** [comment]
Ok, so after reading over this again. I don't think this should conflict since most of this work will be in the `commands` directory, and the porcelain/plumbing work will be in the `api` directory. What few if any conflicts do arise from this should be manageable.

**Comment by alanshaw** [comment]
I'm going to try this one!
