### ISSUE TITLE
feature or bug? how we encode data returned from the vm

### ISSUE THREAD

**Issue by phritz** [filecoin-project/go-filecoin#1714]
i'm working on some querymessage porcelain and finding myself confused by why the vm encodes it output like it does. @dignifiedquire i'm hoping you can answer this, or perhaps @whyrusleeping ; the answer here doesnt just help with enabling my progress, its also something we should document in spec. anyway:

values are passed into the vm as a slice of bytes which is a cbor-encoded slice of abi-serialized byte slices. that is, to get the slice of bytes to pass you take your slice of go types, convert them to a slice of abi.values, and then abi-serialize each abi value to a byte slice yielding a slice of abi-serialized byte slices. then cbor encode that slice of byte slices.

eg heres where message sending takes go types and converts them to these cbor bytes: https://github.com/filecoin-project/go-filecoin/blob/c4b642bea8f6b767a333c8c7dac8a673b163dc98/plumbing/msg/sender.go#L62
 
and when an actor wants to send a message the same thing happens manually in vmcontext.send for messages between actors: https://github.com/filecoin-project/go-filecoin/blob/c4b642bea8f6b767a333c8c7dac8a673b163dc98/vm/context.go#L135

so far so good. however notice that everywhere we get data **out** of the vm it comes out without the outer cbor encoding. it comes out as the slice of abi-serialized byte slices, an intermediate value in the encoding step above. the flow is interesting:

1. starting innermost first, when an actor returns go values from a method call they are fully encoded to cbor as i would expect; a single slice of cbor encoded bytes is returned from the exported method call: https://github.com/filecoin-project/go-filecoin/blob/c4b642bea8f6b767a333c8c7dac8a673b163dc98/actor/export.go#L110

2. this cbor encoded byte slice is returned to vm.send, which *undoes* the outer cbor encoding to yield the slice of abi serialized byte slices: https://github.com/filecoin-project/go-filecoin/blob/c4b642bea8f6b767a333c8c7dac8a673b163dc98/vm/vm.go#L58

3. this slice is returned, possibly through vmcontect.send which leaves it untouched, to applymessage which sets it on messagereceipt.return: https://github.com/filecoin-project/go-filecoin/blob/c4b642bea8f6b767a333c8c7dac8a673b163dc98/consensus/processor.go#L418

there are two other places besides the message receipt where this type of return value shows up. the first is in consensus.callquerymethod which is just a light wrapper around send: https://github.com/filecoin-project/go-filecoin/blob/c4b642bea8f6b767a333c8c7dac8a673b163dc98/consensus/processor.go#L332 The other is when an actor calls vmcontext.send to send a message to another actor; it receives the return value as a slice of abi serialzed byte slices. 

ok, so my questions:
- is it a feature that vm input is cbor encoded but that output is not? shouldn't it be symmetrical? note that all the interfaces for decoding assume the cbor encoding eg abi.decodevalues takes the cbor encoded slice. any place that we actually decode these values we are doing it manually instead of using a single call into the abi package. seems to me that *send should return the cbor encoded bytes and this is what should be found in the message receipt and returned from querymessage.*
- if for some reason it is a feature to return the return value not cbor encoded we should remove the cbor encoding from the exported actor method wrapper mentioned above. 
- why does vmcontext.send take go types but return the slice of abi serialized byte slices which the actor cannot use? why not just return go types that it can use? vmcontext.send is only called by actors, so it is a vm implementation detail. the go types would be en/decoded to the abi types under the hood. as it is the signature is weird; it takes go types but returns a useless array of abi bytes. note i am not suggesting that vm.send return go types. vm.send is the entrypoint to the vm and between actors. i'm saying the higher level vmcontext.send used by actors should return go types.
- speaking of not useful, i cannot find a single place where an actor uses the return value of a call to another actor. the exit code yes, but not the return value. interesting fact.

**Comment by mishmosh** [comment]
Discussed with @acruikshank and @phritz. The plan is to address this as part of a larger cleanup (either model for change, or VM v2). Moving to backlog for now.

**Comment by anorth** [comment]
I'm closing this issue, but FYI @icorderi when you're working here the discussion above may help set direction.
