### ISSUE TITLE
Bootstrap reports actionable errors

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/go-filecoin#1729]
### Description
We've hit the point where bootstrapping has the potential to end in errors that we should take action on, like maybe shut down the node if we see them.  Right now we just log these.  As we begin relying on bootstrapping for security this will become more important.

To allow for robust bootstrapping right now bootstrapping is a persistent process that checks that enough peers are connected every minute and connects to bootstrappers if connections are below a threshold.

There should be some way to listen on an error channel from this routine (and probably others) and use error information to do things like shut down the node.

### Acceptance criteria
- we identify good UX for current bootstrap errors (i.e. is logging fine, should we shut down the node?)
- implement this

### Risks + pitfalls
May or may not be a tricky node refactor (might be as simple as using a goroutine to connect an err channel from bootstrap to the node shutdown method).  Need to understand good node operation UX to id whether we should just log this error or do something else.

### Where to begin
filnet/bootstrap.go and node/node.go

**Comment by anorth** [comment]
What does bootstrapping refer to here? Is it just libp2p DHT bootstrapping, or the more general secure peer/chain bootstrapping that we need to implement (https://github.com/filecoin-project/specs/pull/196)?
