### ISSUE TITLE
Order Messages by Gas Price

### ISSUE THREAD

**Issue by acruikshank** [filecoin-project/go-filecoin#1751]
### Description

Filecoin block miners should be able to process messages in a way that generates the most profit. Choosing to process messages with a higher gas prices is the way to do this.

Miners must continue to take message nonce into consideration, so the next message to process must satisfy

1. The message has a lower nonce than any other message from the same actor.
2. The message's gas price is has price greater than or equal to any other message that meets the first condition.

### Acceptance criteria

1. When the messages in the message pool exceed the block's gas limit, only the messages prioritized by the above rules appear in the block.

### Risks + pitfalls

Sending a price of 0 is still valid (although now potentially has consequences), so tests should still probably pass.

### Where to begin

processor.go

**Comment by anorth** [comment]
I've picked this up. My approach is to build per-actor queues ordered by nonce, then a priority-queue of actor queues ordered by gas price of the next message from that actor, and merge these actor queues into a single list.

I believe this is optimal if ignoring the bin-packing aspect of the problem. More squeezing is possible by also considering the gas limit and solving a 0/1 knapsack problem.
