### ISSUE TITLE
return go types from messagequery

### ISSUE THREAD

**Issue by phritz** [filecoin-project/go-filecoin#1754]
### Description

background: #1469 in general and #1714 which indicates that the right interface for passing things into and out of the vm and within it is cbor encoded abi serialized byte array.

current messagequery takes go types but returns an abi encoded return value and a function signature that the caller can use to decode the return values. callers want go types and so do this decoding themselves. we should instead do this decoding within the message queryer and return a slice of interface{}s containing go types, and no function signature. 
 
this is relatively straightforward except for the fact that the abi en/decoding interfaces return/take cbor encoded abi-serialized byte slices. messagequery gets back abi serialized byte slices, without the outer cbor encoding. https://github.com/filecoin-project/go-filecoin/blob/b85dfe3bff17a3420b5c1f02f7951b701a176d54/abi/encode.go#L33. this is ugly, asymmetrical, and not wai. before working out to adjust messagequery there is some internal cleanup listed in https://github.com/filecoin-project/go-filecoin/issues/1714#issuecomment-459551933 that will make this easier. 

would be great to clean a few things up along the way eg
- function names in abi i find confusing, seems like they can be cleaned up, eg https://github.com/filecoin-project/go-filecoin/blob/b85dfe3bff17a3420b5c1f02f7951b701a176d54/abi/encode.go#L59 actually encodes to bytes, not values. we should call going from go types to cbor encoded abi serialized bytes encoding and the opposite decoding. intermediate steps should say what they do, eg de/serialize, to/from values. you'll see what i mean.
- why dont we have a function that goes from encoded values to a slice of go types? we should

the value created here is two fold. first, vm inputs and outputs become symmetrical which means we will have an easier time writing conformance tests for it. second, if messagequery returns go types instead of abi serialized bytes then that is one less thing callers have to do. they dont have to deserialized the bytes to values and then to go types. they do still need to cast from interface{} to the expected go type. so we remove some boilerplate and make converting things to messagequery easier. converting more things to messagequery comes next.

note this is a little more hairy than i first thought bc it involves adjusting some really key function signatures at the core of the code. its possible someone with more context should pick this up. @anorth unassign from yourself if this looks too hairy for a first issue or if you get into it and it is just too much to start with. 

### Acceptance criteria

- messagequery returns a slice of interfaces
- vm.send returns []byte of cbor encoded bytes and this is whats found in the receipt

### Where to begin

1. https://github.com/filecoin-project/go-filecoin/issues/1714#issuecomment-459551933
2. probably should decode here and return them https://github.com/filecoin-project/go-filecoin/blob/b85dfe3bff17a3420b5c1f02f7951b701a176d54/plumbing/msg/queryer.go#L87

**Comment by anorth** [comment]
@phritz is this ready?

**Comment by anorth** [comment]
FYI @icorderi in case you want to roll this into other VM work.

**Comment by anorth** [comment]
Deleted
