### ISSUE TITLE
[bug] go-filecoin developers shouldn't need Rust (take two – BLS)

### ISSUE THREAD

**Issue by anorth** [filecoin-project/go-filecoin#1759]
**Describe the bug**
Building go-filecoin fails without Rust installed because `scripts/install-bls-signatures.sh` builds the bls-signatures submodule. It's not pre-built.

**To Reproduce**
`go run ./build/*.go deps` without Rust (or with an old version)

See output at https://gist.github.com/Kubuxu/840bb5ef7ea27c810031459bd0a7c352

**Expected behavior**
`go-filecoin` should be easily buildable without a local Rust toolchain.

**Additional context**
We've solved this before in #1386. A prebuild for BLS might be the answer.

FYI @laser @sidke @frrist

**Comment by ognots** [comment]
One is now able to fetch groth parameters via `paramfetch`, included in [0.1.4 release](https://github.com/filecoin-project/go-filecoin/releases/tag/0.1.4).

See the [Getting Started Wiki "Install Filecoin and its Dependencies" section](https://github.com/filecoin-project/go-filecoin/wiki/Getting-Started#install-filecoin-and-its-dependencies) for detailed instructions

**Comment by anorth** [comment]
Go-filecoin developer still need Rust (in fact, with even more delicate requirements than when this issue was filed).

**Comment by laser** [comment]
@sidke - Would you mind responding to this comment with a link to the issue you're working on which produces a precompiled `bls-signatures` library?

**Comment by sidke** [comment]
this issue exists: https://github.com/filecoin-project/go-filecoin/issues/2361
this pr exists: https://github.com/filecoin-project/go-filecoin/pull/2368

release was happening and avoided trying to shoehorn stuff with moving parts in

**Comment by sidke** [comment]
resolved with this merge:
https://github.com/filecoin-project/go-filecoin/pull/2368
