### ISSUE TITLE
Repo Migrations

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/go-filecoin#1766]
### Description
When go-filecoin updates versions it needs the flexibility to change how things are stored on disk.  When operators update they need a painfree automatic way to upgrade their persistent data to match the form expected by the new version.

### Acceptance criteria
- There is a mechanism for detecting versions of filecoin repos. 
- There is a mechanism for upgrading any previous version of a filecoin repo to a filecoin binary's repo version

- It is not a goal to tie this back to the model for change for the protocol.  If possible let's try to keep the design of versioning protocol datastructures (blocks, messages, the state tree etc) abstracted away from this work.

### Risks + pitfalls
cc @phritz  call out things I missed or got wrong.

### Where to begin
IPFS has some great patterns: https://github.com/ipfs/fs-repo-migrations

**Comment by shannonwells** [comment]
I'm closing this since it's covered by the epic #2470 , even though this was first, and the epic issue is technically a duplicate, it has all the references now.
