### ISSUE TITLE
DHT explainer

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/go-filecoin#1769]
### Description
We should have a [codewalks](https://github.com/filecoin-project/go-filecoin/blob/master/CODEWALK.md) level description of how the DHT works in filecoin.  Probably merits 2 sections: 
1. setup: including starting the bootstrap service and explaining what is happening at the level of records to get a node bootstrapped
2. use: right now I think its only used to go from miner peer id (gotten from chain) to miner address to connect directly to miners during deals.  Should explain which call hits the DHT and high level explanation of what is happening with lookup to make things work.  

Might be further sections as our implementation becomes better.  For example when we do chain bootstrapping correctly we will probably do some DHT walking to find random peers for querying chain head.

@anacrolix if interested/if you need some filecoin work, this is something you would probably do well, I could steer you towards entrypoints for setup and use of DHT in go-filecoin.  No pressure though, I'm happy to take this on.

### Where to begin
A little bit of research into kademlia, and in particular libp2p's implementation.

**Comment by phritz** [comment]
@anacrolix would you mind responding as to whether you'll pick this one up? thanks!

**Comment by raulk** [comment]
@phritz – I'm taking this one for the team.

**Comment by anacrolix** [comment]
Thanks @raulk.
