### ISSUE TITLE
Manual DHT inspection

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/go-filecoin#1770]
### Description
For some reasons explained in comments of #1440 we don't have as much confidence as we would like that DHT nodes on the filecoin network are bootstrapping and operating as expected.  We 

### Acceptance criteria
- Understand what the DHT should look like after bootstrapping
- Manually inspect the DHT to ensure that what should be happening is happening (i.e. the records that we expect to see in the DHT are in the DHT)

### Where to begin
- Do a little research into libp2p kademlia implementation to understand what we should see after a successful bootstrap to ensure that DHT is setup right.  Dovetails with research for #1769.
- @anacrolix is working on a DHT CLI tool that will be very useful for examining DHT state

**Comment by phritz** [comment]
dup of https://github.com/filecoin-project/go-filecoin/issues/1997
