### ISSUE TITLE
create real PoST when mining

### ISSUE THREAD

**Issue by shannonwells** [filecoin-project/go-filecoin#1791]
### Description
mining workers are created with a fakeCreatePoST, which simply sleeps for `w.blockTime`.  The worker needs a function that creates a PoST according to [spec](https://github.com/filecoin-project/specs/blob/master/proofs.md#proof-of-space-time) 

### Acceptance criteria
Worker calls a real createPoST function that matches the [spec](https://github.com/filecoin-project/specs/blob/master/proofs.md#proof-of-space-time)

### Risks + pitfalls
Affects all actual and test mining
Related: #1586, #1582 

### Where to begin
mining/worker.go: `NewDefaultWorker`, `fakeCreatePoST`, `createProof`

**Comment by laser** [comment]
@ZenGround0 @shannonwells - 

I propose to close this story. 

I propose to replace this story with a new story, a stub, which is called something like "use a real delay function when generating and verifying blocks when mining." 

I think that new story should immediately be marked as BLOCKED pending The Research Team "acks to a particular delay function."

**Comment by shannonwells** [comment]
Agreed; I think leaving this issue here will just cause more confusion.
