### ISSUE TITLE
Remove use of `add-ask` command, and remove command

### ISSUE THREAD

**Issue by travisperson** [filecoin-project/go-filecoin#1794]
### Description

The `add-ask` command has been deprecated. Also the command does not properly configure the `miner.storagePrice`, so using it is not valid. We should remove all use of `add-ask` in our tests and deployments.

Related issue for infra: https://github.com/filecoin-project/go-filecoin-infra/issues/150

### Acceptance criteria

- `add-ask` is no longer used in functional retrieval test
- `add-ask` is removed from FAT lib.
- Remove `add-ask` from cli.

### Risks + pitfalls

Removing the use of `add-ask` is a bit of work. We could also update it to set the price as well.

### Where to begin

https://github.com/filecoin-project/go-filecoin/blob/master/functional-tests/retrieval
https://github.com/filecoin-project/go-filecoin/blob/master/functional-tests/devnet-retrieval
https://github.com/filecoin-project/go-filecoin/blob/master/tools/fat/action_miner.go
https://github.com/filecoin-project/go-filecoin/blob/master/commands/miner.go

**Comment by rkowalick** [comment]
I have updated the wiki documentation to better communicate that they will be "setting their price" vs. "adding an ask".
