### ISSUE TITLE
Reconcile storage protocol related porcelain and plumbing with old api

### ISSUE THREAD

**Issue by acruikshank** [filecoin-project/go-filecoin#1807]
### Description

Some new functions have been added porcelain and plumbing to support paying miners in the storage client. Namely:
plumbing/ChainLs
porcelain/ChainBlockHeight
porcelain/MinerGetAsk
porcelain/MinerGetOwnerAddress
porcelain/MinerGetPeerID

All of these have equivalents in the old API, but their might be slight discrepancies in behavior.

These function should be reconciled, code using the api should start using porcelain and we should remove the functions from the old api.

### Acceptance criteria
The functions listed above are removed from the api and everything still works.

**Comment by rosalinekarr** [comment]
This is done
