### ISSUE TITLE
[bug] `miner set-price`: storageprice is not per sector, but byte per block

### ISSUE THREAD

**Issue by travisperson** [filecoin-project/go-filecoin#1820]
**Describe the bug**

The `miner set-price` command currently describes the `storageprice` per sector. However, in the newly implemented payments, it's actually implemented as the price for each byte per block.

**Additional context**
Slack discussion
https://filecoinproject.slack.com/archives/CEHHJNJS3/p1549467815527800

How the ask (ask is created by set-price) value is used

https://github.com/filecoin-project/go-filecoin/blob/726e6705860ddfc8ca4e55bc3610ad2230a95c0c/protocol/storage/client.go#L105-L145

**Comment by anorth** [comment]
Just to confirm, I think the fix here is to update the documentation to use bytes per block.
