### ISSUE TITLE
[bug] Relay addresses not getting advertised

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/go-filecoin#1829]
**Describe the bug**
When connected to the nightly devnet nodes behind NATs should automatically connect to the relay and get relay addresses.

A little prelim debugging has shown that the bootstrappers are initialized with the right flags.  Also the autonat discover service appears to be working as the debug output of local nodes shows that NATed nodes correctly learn that they are NATed.

**To Reproduce**
Start a daemon booted off nightly devnet and wait.  You won't see relay addresses in the output of `go-filecoin id` as expected.

**Expected behavior**
Relay addresses should be advertised after 5 minutes.

**Screenshots**
If applicable, add logging output or screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: mac OS for local nodes.

**Additional context**
There are two places to debug: the bootstrap nodes in the devnet and the local node.  Start by debugging the local node and if no issue is found there move to debugging the devnet.  To debug bootstrappers get access to the logs.  It will likely also help if you have ssh access to the test devnet machines + access / knowledge to deploy the test devnet with debug docker containers.

**Comment by ZenGround0** [comment]
Ok I have verified that relay addresses get advertised in the test cluster when running the libp2p 6.0.35 patches introduced in #2036.

I have been burned before seeing sporadic successes but we have more long term and actionable stability and debugging work in the pipeline #1997 #1678 so I'm closing this out.

Thanks again to @vyzo @raulk for the sound and rapid fixes 🔥 🔥 🚒 
![image](https://user-images.githubusercontent.com/5515260/53448303-15f23680-39e5-11e9-9610-b45b8e55983a.png)

❤️ 💝 ❤️ 💓 ❤️ 

![image](https://user-images.githubusercontent.com/5515260/53448413-55b91e00-39e5-11e9-8ae0-9a0a30873fc6.png)

**Comment by raulk** [comment]
@zenground0 great to hear! 👏👏👏
