### ISSUE TITLE
Update the Wiki, Readme and flags to work with 'usernet' and new dashboard

### ISSUE THREAD

**Issue by frrist** [filecoin-project/go-filecoin#1838]
### Description
When the usernet and new dashboard go "live" we need to update documentation and flags for it.
### Acceptance criteria
- [x] update `init` bootstrapping flag: `--devnet-user`: https://github.com/filecoin-project/go-filecoin/pull/1852
- [x] update the heartbeat target flag to the new dashboard: https://github.com/filecoin-project/go-filecoin/pull/1840
- [x] update infra to use new hartbeat config https://github.com/filecoin-project/go-filecoin-infra/pull/154
- [ ] update README with new link to dashboard and description on flags
- [ ] update the wiki with the above ^

**Comment by phritz** [comment]
@frrist status?

**Comment by frrist** [comment]
The wiki contains a link to the dashboard and the flags required to connect to it:
https://github.com/filecoin-project/go-filecoin/wiki/Dashboards

The README points users to the Getting Started process:
https://github.com/filecoin-project/go-filecoin#usage
