### ISSUE TITLE
Improved testing in mining/worker_test.go

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/go-filecoin#1841]
### Description
DefaultWorker.Mine is the function that puts the logic for creating tickets, checking for winning conditions and generating new blocks on behalf of a mining node.  It currently has a single happy path test.  We should expand coverage to hit more edge cases.

TestApplyMessagesForSuccessTempAndPermFailures lives in the same file and appears to be a misplaced processor test that can move to the consensus/processor_test.go file.

**Comment by anorth** [comment]
Ancient history
