### ISSUE TITLE
Chain API improvements

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/go-filecoin#1847]
### Description
Discussing with @phritz `BlockHistory` seems a little off.  A better solution (that could be used to implement block history) is to have a `Head` and `GetNext` method allowing tipsets to traverse themselves.

### Acceptance criteria
BlockHistory is removed from the chain interface.  It is reimplemented elsewhere with more irreduceable and ergonomic api methods.  

### Risks + pitfalls
Depending on how we go about it this work has the potential to blow up in scope.  If we want tipsets to be able to traverse themselves maybe that means the `GetNext` method is defined on tipset which opens up a lot of complexity.  This work could also start bleeding into questions of whether state or state cids should be stored on tipsets.  This could start a chain reaction where we start untangling lots of technical debt in the chain store interface.

**Comment by phritz** [comment]
note this will enable things like https://github.com/filecoin-project/go-filecoin/pull/1755 to be implemented as porcelain. there are a million ways to filter the chain, we need to provide the building blocks that enable consumers to filter how they want

**Comment by mishmosh** [comment]
Really nice to have, but not strictly required to delete node API, so may fall out of this epic.

**Comment by rosalinekarr** [comment]
@phritz, regarding your earlier suggestion, changing

```
Head() consensus.TipSet
```

to

```
GetHead() types.SortedCidSet
```

is a problem, because we use `Head` in a number of places where we need the full block information of the head of the chain. For example, line 229 of `chain/default_syncer.go` uses it to fetch the parents of the block.

Should I skip this suggestion for now, or do you have any ideas about how to make it work?

**Comment by phritz** [comment]
Use GetHead() to get the sortedcidset then GetTipSetAndState() to get the block?
