### ISSUE TITLE
Proposed edits to wiki  (WIP)

### ISSUE THREAD

**Issue by terichadbourne** [filecoin-project/go-filecoin#1849]
As I review the wiki at https://github.com/filecoin-project/go-filecoin/wiki to collect concepts that might require further explanation (see https://github.com/filecoin-project/engine/issues/19), I'd also like to capture notes on spots where the wiki itself could be improved through linking, etc. I'm creating this issue as a placeholder to drop my notes in, and then I'll be happy to put in a PR to make the edits if folks agree with my suggestions.

**Comment by terichadbourne** [comment]
Thanks @anorth! I'll try to set aside some time on Friday to circle back to this, look at the changes you've made, and keep going with the sections I haven't gotten to yet.

**Comment by terichadbourne** [comment]
@anorth I'm just now circling back to the two sections you updated based on my suggestions. It's a lot clearer now, thanks!

**Getting Started** 

Found a typo in step 4 of [Start running Filecoin](https://github.com/filecoin-project/go-filecoin/wiki/Getting-Started#start-running-filecoin) on the [Getting Started](https://github.com/filecoin-project/go-filecoin/wiki/Getting-Started) page of the wiki: 
In "The last segment of a peer's address is it's peerID,"  `it's` should be `its`.

In step 2, is "user.kittyhawk.wtf" what everyone types, or an example where that's something you set yourself? Asking because "WTF" is slang-y enough for me to assume this is trying to be a funny example.

Warning: Grammar nitpicks ahead... 

In these various steps and those throughout the page, it would be great to consistently use colons before the code samples where it can be done both consistently and grammatically. Currently there are some with colons, some with periods, some with nothing. 

At the bottom of the page, 'd prefer changing: 

```
Next, choose your adventure:
- Mining Filecoin, or
- Storing Data.
```

to either: 
```
Next, choose your adventure:
- Mining Filecoin 
- Storing Data
``` 

or: 
```
Next, choose your adventure: mining filecoin or storing data. 
```
There's no way to do PRs on a Wiki, right? I'd have to make edits directly without anyone having a chance to give feedback? Just want to make sure I'm sharing suggestions in the way that's most helpful.


**Mining Filecoin**
This was very accessible until I hit this section: 

```
Create a miner that pledges 10 sectors (currently 256 MiB each) of storage and 100 FIL as collateral, with a message gas price of 0 FIL/unit and limit of 1000 gas units. When successful, it returns the miner address of the newly created miner.
```
- Is MiB a typo or a measurement I'm not familiar with? 
- Is "sectors" just a word you're using  as a storage unit? 
- I don't think you've introduced "FIL" yet. It's like saying "USD," right? 
- What does "message gas price"? What does gas have to do with anything? Do you just mean unit price? 
- What's a gas unit? 
- Do you have to pick these precise amounts to start mining or was this just an example of how to construct the code if those were the amounts you wanted to use?  (I have the same question in later sections of this page.

```
For now, you are mining blocks that contain activity on the network. 
```
 I thought I was mining filecoin but now you say I'm mining blocks. Are you comfortable making the assumption that everyone here already knows what blocks are?

Under "Stop mining" should we say that you'll also stop mining automatically if your computer goes offline (I'm guessing here). 

Overall, this page relies heavily on people already understanding mining and blocks. If it's possible filecoin will be the first cryptocurrency they've mined, I don't personally consider the explanations sufficient.


Alright, that's it for today! Will circle back next week for other sections of the wiki!

**Comment by terichadbourne** [comment]
The Mining Filecoin page lists 3 kinds of miners: 

```
The Filecoin network will have multiple types of miners:

Storage miners
Retrieval miners
Repair miners
```

But the architecture overview on the How Filecoin Works page has 4 roles of which only 2 are mining. 

```
The Filecoin decentralized storage network has 4 major roles:

Storage miners: like servers in the classical http web, they store data
Retrieval miners: like CDNs, they fetch data and serve it to clients
Storage clients: users that want to store data
Retrieval clients: users that want to get data
```

Why the discrepancy? 



**"More HowTos" Page** 
_Note that this feedback is purely from reading, not having tried to walk through this process._

Why only one how to on a page that is labelled like it will have many? I think it would be more user friendly to have a wiki page for each how to separately, and each could be labelled as "How To: Do a Thing" in the title and in the index. (I don't know if nesting exists in Wiki indexes, but that would also be an option.)

If you don't like that suggestion, note that I'm bothered by the use of smushed together HowTos. Could we use "Tutorials" or something else here? 

I'm also aesthetically bothered by the "HOW TO:" in caps at the top of the content.

`Let's first set the location of the filecoin source (substitute with where ever your source tree is cloned):`
Substitute what, exactly? Everything in caps? Just the part that says `GO_FILECOIN_PATH`? Just `$HOME`? Everything except `export`?

`Then for convenience, we'll export the node address to a bash variable.`

Soooo are you inserting one thing from what you got back in the `Addresses array` in the sample above after `export NODE1_ADDR=`?

Under the Node 2 instructions you include `export FIL_PATH=<repodir>` and I'm assuming that the <repodir> is what I'm supposed to replace because of the puntuation. You didn't use this format elsewhere. Making it consistent how you show what gets replaced and what stays as is in examples would be hugely helpful, particular to newer developers.

`Then specify non-default values for the api.address and swarm.address. NOTE ANY VALUE HAS TO BE SINGLE AND DOUBLE-QUOTED.`
Can we pick something other than caps to call this out? Bold? Underline? Can you give an example? I'm guessing you mean that I have to do `"'something'"` but I don't see anythign like that in the example below.

Here you've started using another format for how to show what to replace, so there's a consistency-of-formatting issue. I presume this practice of using carrots to point up to the thing you're pointing to isn't particularly accessibility friendly. I would expect anything that's not actual code and is instead messages to the reader to be commented out, eg `// a comment` on a new line if this were JavaScript, looks like Go might use `#` which you do in a later code sample.
![image](https://user-images.githubusercontent.com/19171465/54454522-089cb200-4730-11e9-908a-efba2d561f6e.png)

**Comment by terichadbourne** [comment]
**"Storing on Filecoin" page** https://github.com/filecoin-project/go-filecoin/wiki/Storing-on-Filecoin

Here's a key piece of context that I happen to already know that I wish were mentioned explicitly here: 
When you store data on IPFS, that data is only available as long as someone who's storing it is connected to the network. If only two people have the data and both turn off or disconnect their machines, no one will be able to access that data until someone comes back online. To make data persistent on the network, you need to either (a)ensure that there are so many people hosting that it's super unlikely they'll all go offline at the same time or (b)  never disconnect/unplug your machine. If (b) is impractical for you, you can pay someone to never turn their machine off. 

There are probably lots of nuances there I'm missing or things I'm misstating or other words that should be included (pinning?), but what I'm trying to get at is **_why_** you would bother paying someone for this service. For example, is it cheaper to pay a storage miner to keep their computer on than it would be to keep yours on? What's the risk if you don't hire a storage miner? 

I noticed that this page talks about “anyone who wants to store data on the **Filecoin network**.” My very beginner impression has been that you use Filecoin to pay people to store stuff on the IPFS network, so there’s a single IPFS network that contains both stuff people are self-hosting and stuff people are paying storage miners to store for them. Is that not true?  If there’s any actual difference between the networks, I'd love to see a clear explainer of the distinction. 

Something I'd be curious about when deciding whether to pay a storage miner and hand over my data is whether there's any expectation of privacy. Is there any sort of encryption before they get the data? Should nothing private ever be stored in IPFS regardless? Is there anything to prevent a storage miner from claiming they own that client's data? 

"make sure you have Filecoin installed and running" - As I've mentioned before since the word filecoin refers to at least 4 different things (currency, network, etc.), I wish you'd insert a clear noun that indicated which thing you mean. Maybe this means "a Filecoin node"? "Filecoin software"? 

Under "Import data" I'm surprised because I was expecting I'd be putting my data on the IPFS network. ¯\_(ツ)_/¯ If I already had data on IPFS, would there be a way for me to get it into this looks-to-be-a-separate-thing Filecoin network without uploading it again? (Yes, I know I'm not supposed to say "upload" in IPFS land but you know what I mean. 😂 ) 

You show the format of a JSON ask like so: 
```
{
  "Miner": "fcqxvnl37zdv8clc26j6r43zn8md7tc2mrfx77vru",
  "Price": "2.5",
  "Expiry": 588,
  "ID": 0,
  "Error": null
}
```
What's the unit for the price? FIL? 

What does that expiry mean? How long they're willing to store the data? How long the bid is good for? What's the unit here? Seconds? Minutes? Years? 

When explaining "duration" you say: "how long you want to store (in # of ~30sec blocks)" - is "block" here like the "block" in "blockchain" or do you really just mean "units"? If so, I'd replace with the less ambiguous term. 

Random idea - can we make a little calculator so people can enter an amount of time that actually makes sense and it will translate it to how many of these time blocks they should ask for? 
____ years + _____ days + _______ hours + ______ minutes + _____ seconds = x blocks

"deals will fail if the data exceeds what that miner has available" - was there something in the list of asks that would have alerted me they didn't have enough space(?) available?

"Deals will also fail if your node's wallet balance is insufficient" - how do I put money in my wallet? do i have to put in filecoin or can i put in standard currencies? If so, how would I acquire filecoin in order to put it in my wallet? This might just need a link out to another wiki page or document about how transactions work.

Under "Retrieve your data," the construction of this sentence is a mouthful and it took me a few reads to unravel the prepositions and figure out how to parse it: "you must wait for the sector in which your data is to be stored is sealed" Actually, I think it just doesn't parse into grammatical English, right? "you must wait for the-sector-in-which-your-data-is-to-be-stored is sealed" --> "you must wait **for** it is sealed" should be "you must wait **until** it is sealed"  or "you must wait for it **to be** sealed. Would  "you must wait until the sector your data is assigned to is sealed" be accurate? Anyone have less wordy ideas?

**Comment by terichadbourne** [comment]
In  *Troubleshooting & FAQs*

The solution you propose for this one: 

> Error: “go-filecoin” is damaged and can’t be opened. You should move it to the Trash." (MacOS) 
> This is due to Mac's default protection settings. Go to System Preferences > Security & Privacy > General. Select Allow apps downloaded from: Anywhere. (Allowing the individual application doesn't work.)
> 

isn't an option for me: 

![image](https://user-images.githubusercontent.com/19171465/55634849-533ca780-578d-11e9-9e46-3213b56292b2.png)

I'm on MacOS High Sierra 10.13.6.

It might be nice to add a table of contents at the top of this page that drops you down into each of the main sections.

_I actually made it to the last page of the wiki!_ 🎉

**Comment by anorth** [comment]
Thanks Teri! I have made edits to the wiki incorporating most of your feedback, although there are some questions I decided were not to be answered here.

To speak to one confusion in particular: Filecoin and IPFS are quite separate, at least at the moment. We don't assume any familiarity with IPFS from readers of this documentation at the moment. There will be options for integration in the future, particularly of the type you suggest about importing data from IPFS, but at the moment the networks are distinct.

Please close this issue whenever you consider this pass done. Thank you!
