### ISSUE TITLE
Bootstrapping chain randomness

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/go-filecoin#1872]
### Description
Randomness for leader election and post generation needs to be taken from "far enough back in the chain".  When the chain has fewer tipsets than the lookback parameter we use to sample randomness it is undefined how we get this randomness.  The protocol needs to handle this edge case.  Currently we use the genesis ticket (0 bytes) as the chain randomness for all blocks fewer than lookback tipsets away from genesis.

### Acceptance criteria
The spec has a well motivated way to handle this and the implementation is in sync with the spec.

**Comment by rosalinekarr** [comment]
@whyrusleeping, do you think this should this have a separate task for `specs` and `go-filecoin` or is the one task good enough?

**Comment by anorth** [comment]
See also #2251

**Comment by anorth** [comment]
I expect the new spec to resolve this issue, and we should wait for that.
