### ISSUE TITLE
[bug] Flaky test TestPaymentChannelReclaimSuccess and TestStorageDealsAfterRestart

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/go-filecoin#1873]
**Describe the bug**
Flaky test: TestPaymentChannelReclaimSuccess

**To Reproduce**
Run CI

**Expected behavior**
Test should never fail.

**Screenshots**
https://circleci.com/gh/filecoin-project/go-filecoin/10794?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Desktop (please complete the following information):**
 Travis CI

**Additional context**
Haven't seen this before and couldn't find another issue reporting

**Comment by shannonwells** [comment]
This one is back again; failed in my dev branch and at least once on master.

**Comment by anorth** [comment]
Another one: https://circleci.com/gh/filecoin-project/go-filecoin/12314

`TestStorageDealsAfterRestart` failed too.

**Comment by rkowalick** [comment]
I don't know if fixing the payment channel test failures make sense given that @travisperson is working on converting this stuff to FAST in https://github.com/filecoin-project/go-filecoin/pull/2319. I have a fix for TestStorageDealsAfterRestart, so I will say that "resolves" this issue.

We can open a new one or reopen this if the new FAST payment channels end up being flaky too.

**Comment by phritz** [comment]
still flaky i think: https://circleci.com/gh/filecoin-project/go-filecoin/13258?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link 

@travisperson can you tell us if we should ignore these flakes because this test is being replaced, and if so when you think it will be? probably worth an announcement to the team if we should be ignoring

**Comment by travisperson** [comment]
Yes, these can probably be ignored unless they are really consistent and causing a lot of pain. Payment channel FAST tests are currently WIP in PR #2319. I hope to have those merged later this week or early next week.

**Comment by travisperson** [comment]
Merged #2528, hopefully this resolves these issues.
