### ISSUE TITLE
Improve support for manual peer bootstrapping in case of no peers

### ISSUE THREAD

**Issue by arcalinea** [filecoin-project/go-filecoin#1877]
**Describe the bug**
`swarm peers` should return peers, and if it doesn't, there should be an alternative bootstrapping method.  

**Expected behavior**
If I cannot discover nodes locally with `swarm peers`, I expect there to be a "seeder" node I can connect to, or node addresses I can find online and manually connect to. http://nightly.kittyhawk.wtf:9082/nodes only returns multihashes, not complete node addresses I can connect to. 

Error I get trying to connect to a multihash: 

```
go-filecoin swarm connect /Qmd6xrWYHsxivfakYRy6MszTpuAiEoFbgE1LWw4EvwBpp4
Error: no protocol with name Qmd6xrWYHsxivfakYRy6MszTpuAiEoFbgE1LWw4EvwBpp4
```

I see a `bootstrap` property in the config file. You could add seed nodes here that can help with bootstrapping. The Zcash config file usually includes `addnode=mainnet.z.cash` (or testnet.z.cash), which automatically connects nodes joining the network to well-connected seed nodes run by the Zcash company, to aid in peer discovery. You could get `devnet.fileco.in` or something.

**Desktop (please complete the following information):**
 - Running on Debian

**Comment by rosalinekarr** [comment]
@anorth, can you make sure this issue has some acceptance criteria, etc?

**Comment by anorth** [comment]
On further thought I think we can close this. We already have "well-known" bootstrap addresses in config. It would be handy if the dashboard provided full addresses, but they are in `fixtures/constants.go` already. I think the only case not covered is attempting to join a network other than those bootstrapped by Protocol Labs.

@arcalinea I trust you connected ok once the docs stabilised?
