### ISSUE TITLE
Ensure all PaymentBroker methods only pay the target.

### ISSUE THREAD

**Issue by acruikshank** [filecoin-project/go-filecoin#1881]
### Description

A quick perusal of `PaymentBroker.Redeem` and `PaymentBroker.Close` does not give the impression that payment vouchers can only be redeemed by the channel target. It is extremely important that a voucher for a payment target only delivers funds to the channel's target (or its owner). There is some question whether another actor should be able to redeem a payment on the target's behalf. This issue is to:

* Establish whether this behavior is implemented correctly
* Fix the behavior if not implemented correctly
* Clarify the behavior even if it is correct (i.e. add a guard clause to the top of the methods to make it explicit).
* Start the discussion about whether vouchers can be redeemed by a 3rd party, and implement the result

**Comment by rkowalick** [comment]
This functionality does exist and is already pretty high up in the relevant function call. Closing.

Please feel free to add more context @acruikshank
