### ISSUE TITLE
[bug] balance changed to zero weirdly

### ISSUE THREAD

**Issue by whyrusleeping** [filecoin-project/go-filecoin#1883]
I got some funds from the faucet, then ran balance on my address. It showed 1000, and then ran it again and it showed zero. No idea what happened.

```
why@why-MS-7B46 ~/g/s/g/f/go-filecoin>
go-filecoin wallet balance fcq0egt5t0th7qc6yhh0aavlxz3u6vhflmn94efr
1000
why@why-MS-7B46 ~/g/s/g/f/go-filecoin>
go-filecoin wallet balance fcq0egt5t0th7qc6yhh0aavlxz3u6vhflmn94efr
0
```

**Comment by rosalinekarr** [comment]
Renaming to "Add logging for chain reorg and extending" and updating labels.

@phritz, can you add some acceptance criteria?

**Comment by phritz** [comment]
we got re org logging i think, either @rkowalick or @ZenGround0 implemented i think

**Comment by rkowalick** [comment]
I don't think this ever landed. Will sync up with @ZenGround0 about it today.

**Comment by ZenGround0** [comment]
We're logging which is something.  See #2127 for thoughts on how to make this better long term.
