### ISSUE TITLE
Stop reimplmenting big.Int

### ISSUE THREAD

**Issue by acruikshank** [filecoin-project/go-filecoin#1884]
### Description

`types.ChannelID`, `types.BlockHeight`, 'types.BytesAmmount` and `types.AttoFIL` are all wrappers around big.Int that implement some of big.Int's math functionality. Furthermore `types.GasUnits` is a simple alias of big.Int that fails to provide the same level of type safety as the other types. The partial reimplementation of big.Int math makes it frustrating to implement math, especially when types are mixed in a formula.

### Acceptance Criteria

* All the above types are implemented as types safe wrappers around big.Int.
* All the above types take a big int as a constructor (some already do).
* All the above types get a 'BigInt()' method to convert them to big.Int. To save confusion, this should be a copy of the struct's internal big.Int().
* All math functions are removed from these types, and math implemented with these types starts by converting to big.Int and ends by converting back to type.

**Comment by anorth** [comment]
As noted in #2245, these wrappers would probably be best modelled as a value type, and ensuring consistent usage as such is part of the work.

**Comment by anorth** [comment]
Done
