### ISSUE TITLE
protocol/storage/miner getPaymentChannel should be porcelain.

### ISSUE THREAD

**Issue by acruikshank** [filecoin-project/go-filecoin#1897]
### Description

Right now getPaymentChannel waits for the channel creation message cid, then fires off a query message to get the payment channels for the payer. It returns the one that matches the channel id. 

Waiting for the message cid is probably specific to the miner, but fetching a payment channel should be easier.

**Comment by mishmosh** [comment]
@rosalinekarr tagging you since you were the last to edit pipeline state. is this fixed by #1862 or is there a separate PR in review? (or sth else altogether)

**Comment by rosalinekarr** [comment]
@mishmosh, nope, it's not fixed yet.
