### ISSUE TITLE
[bug] chain loading (not sync) takes a long time

### ISSUE THREAD

**Issue by whyrusleeping** [filecoin-project/go-filecoin#1902]
When starting up your node, loading the chain from disk takes a really long time (45 seconds for 10k blocks). This has to be done (for some reason) before we start the node api. this is really inconvenient. We should make chain loading faster, and also look into maybe making the api accessible before that finishes (though maybe thats not a good idea).

In any case, we should print more info about node startup, like "Loading chain from disk..." "Finished loading chain!"

**Comment by phritz** [comment]
lets add a message along the lines of the chain syncing messages that was recently added

**Comment by dignifiedquire** [comment]
it would be great to have a progressbar for chain sync, given that we can easily measure it using the blockheight.

**Comment by frrist** [comment]
This has been address here: https://github.com/filecoin-project/go-filecoin/pull/1952
