### ISSUE TITLE
[bug] paramcache missing from binary install

### ISSUE THREAD

**Issue by porcuquine** [filecoin-project/go-filecoin#1913]
**Describe the bug**

When installing `go-filecoin` as a binary, there is no way to get the groth parameters before running for the first time.

**To Reproduce**
1. Use the links in installation instructions to download a binary installation of `go-filecoin`.
2. Notice that there are no groth parameter files: (like `v9-zigzag-proof-of-replication-123456`).
3. Notice that there is no executable named `paramcache`.

**Expected behavior**
Either the groth parameter files themselves should be included, or the `paramcache` utility should be present. The user needs to be able to generate parameters before running. Otherwise, `go-filecoin` will stall the first time it is run (for what could be up to 40 minutes). If the program is terminated during parameter generation, the process will have to be repeated the next time. We should at least document that this is expected behavior so users know to wait it out.

**Screenshots**
If applicable, add logging output or screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: At least linux, as experienced by @mslipper and verified by @phritz and @porcuquine last night.
 - Browser [if applicable, e.g. chrome, safari]

**Additional context**
This was discovered by @mslipper, whose node got stuck at a certain node last night, with this log output:
```
^[[0;37m05:48:28.141  INFO ^[[0;34mchain.sync: ^[[0msyncing the chain, currently at block height 52 ^[[0;37mdefault_syncer.go:153^[[0m
^[[0;37m05:48:28.187  INFO ^[[0;34mchain.sync: ^[[0mchain synced ^[[0;37mdefault_syncer.go:158^[[0m
Feb 13 05:48:28.319 INFO parameter set identifier for cache: layered_drgporep::PublicParams{ drg_porep_identifier: drgporep::PublicParams{graph: zigzag_graph::ZigZagGraph{expansion_degree: 8 base_graph: drgraph::BucketGraph{size: 8388608; degree: 5} }; sloth_iter: 0}, challenges: Tapered { layers: 4, count: 2, taper: 0.3333333333333333, taper_layers: 2 } }, target: params, place: storage-proofs/src/parameter_cache.rs:54 storage_proofs::parameter_cache, root: storage-proofs
Feb 13 05:48:28.321 INFO checking cache_path: "/tmp/filecoin-proof-parameters/v9-zigzag-proof-of-replication-52431242c129794fe51d373ae29953f2ff52abd94c78756e318ce45f3e4946d8", target: params, place: storage-proofs/src/parameter_cache.rs:83 storage_proofs::parameter_cache, root: storage-proofs
Feb 13 05:48:28.323 INFO reading groth params from cache: "/tmp/filecoin-proof-parameters/v9-zigzag-proof-of-replication-52431242c129794fe51d373ae29953f2ff52abd94c78756e318ce45f3e4946d8", target: params, place: storage-proofs/src/parameter_cache.rs:126 storage_proofs::parameter_cache, root: storage-proofs
Feb 13 05:48:28.324 INFO groth_parameter_bytes: 0, target: stats, place: storage-proofs/src/parameter_cache.rs:131 storage_proofs::parameter_cache, root: storage-proofs
Feb 13 05:48:28.324 INFO Actually generating groth params., target: params, place: storage-proofs/src/parameter_cache.rs:70 storage_proofs::parameter_cache, root: storage-proofs
```
Note in particular the last three lines. These show an attempted read, that this read took only 1ms, and that a lengthy parameter generation process was immediately triggered.

**Comment by rosalinekarr** [comment]
@porcuquine Is this issue still valid after the paramfetch changes or should I close it?

**Comment by porcuquine** [comment]
@rosalinekarr I just checked with @sidke, and the root issue is still present. He's going to work on a fix (which might just be documentation — not sure).

**Comment by mishmosh** [comment]
@sidke This looks stale, closing for now but please reopen if that's incorrect.
