### ISSUE TITLE
Groth Parameters and Performance Issues

### ISSUE THREAD

**Issue by ognots** [filecoin-project/go-filecoin#1929]
### Description

Performance issues during bootstrapping were being caused by regenerating and/or reading groth parameters from file.

The fix currently implemented is to copy or symlink `v9-zigzag-proof-of-replication-52431242c129794fe51d373ae29953f2ff52abd94c78756e318ce45f3e4946d8` to `/tmp/filecoin-proof-parameters/params.out`

This issue is intended to discuss if this is the canonical solution to the problem or if it's temporary

### Acceptance criteria

Bootstrapping nodes should not create any substantial delays during bootstrapping go-filecoin

### Risks + pitfalls

The current delay  made it very difficult to process blocks for 30-40 minutes after a go-filecoin daemon starts

### Where to begin
 
Gather stakeholders to discuss and plan moving forward

**Comment by anorth** [comment]
@porcuquine please close this issue if you believe it to be done.
