### ISSUE TITLE
Command for sector size

### ISSUE THREAD

**Issue by mishmosh** [filecoin-project/go-filecoin#1932]
### Description
Add a CLI command in the porcelain that returns the sector size of the network you're connected on.
Whoever picks this up is welcome and encouraged to propose a better command name in this issue.

Backstory is in #1921.

### Acceptance criteria
- Running `go filecoin (or similar) returns a message like this:
  - `Sector size on $NETWORKNAME is 256GiB.`
- (After PR merges) Update the Commands page on wiki

### Risks + pitfalls
?

### Where to begin
`/commands`

**Comment by phritz** [comment]
we really need this, moving it to ready

**Comment by laser** [comment]
@phritz - Sector size obtained from `rust-fil-proofs` through the FFI. go-filecoin creates a sector configuration-value using the `FIL_USE_SMALL_SECTORS` environment variable which it trades for a number-of-bytes-in-a-sector value through the FFI. I think that It makes sense to write a command which reports the sector size for the currently-running daemon. 

Do you instead propose a command which produces a sector size for ... the cluster which is associated with the `genesis.car` file that the the running go-filecoin node was initialized with? This implies that go-filecoin would need to maintain a mapping of cluster identifier (`genesis.car` file URL or something) to sector configuration ("small" or not-"small"). That seems odd to me.

**Comment by phritz** [comment]
Sorry, yes, the first thing you said, not the second. A command that reports sector size for the currently running daemon.

Separately, we can/should talk about sticking protocol parameters into hello or similar to prevent nodes with incompatible settings from talking to each other.

**Comment by rkowalick** [comment]
If the currently running daemon is not mining and has no interest in mining, it is not possible to get the correct sector size.  This is because

1. Accurate sector size can only be obtained from the initialized sector builder.
2. Creation of a sector builder requires a mining address.
3. A mining address can only be created with a createMiner message on chain. This requires a pledge, collateral, and gas

**Comment by laser** [comment]
@rkowalick 

> Accurate sector size can only be obtained from the initialized sector builder.

This is the case today, I agree. 

That said, we can add a new FFI-exposed function to rust-fil-proofs which:

1. Does not require a pointer to a Rust sector builder and
2. Will trade a `C.ConfiguredStore` for a number-of-bytes-in-a-sector value

We can use the aforementioned environment variable to determine which member of the Go [`SectorStoreType`](https://github.com/filecoin-project/go-filecoin/blob/3059e9a8e8e305505fa29bec966693677a2be1c1/proofs/rustverifier.go#L168) enum-values to trade for the `C.ConfiguredStore`.

I'm happy to take this story if someone (@rkowalick) is willing to specify how the command should work (from a CLI consumer standpoint).

**Comment by rkowalick** [comment]
The current use cases for an easy way to determine sector size would be:

1. Allowing a user to determine the sector size on their network with a CLI command. The behavior @mishmosh has outlined above seems reasonable to me.
1. Allowing a storage client to avoid sending over a piece larger than the sector size on the network.

**Comment by laser** [comment]
I'm not sure that this command makes much sense given that we're about to support multiple sector sizes. Perhaps the command could return an enumeration of supported sector sizes (as configured in the genesis block)?

**Comment by rkowalick** [comment]
As per the recommendation of @rosalinekarr in #2575, it makes sense to add this to the quite new `protocol` command

**Comment by laser** [comment]
As per the spec, the protocol supports multiple sector sizes. What should this command produce? An enumeration of sizes? Also, will this command show the number of user bytes which can be written to a staged sector or will it show the number of bytes that the miner will get power for?
