### ISSUE TITLE
rethink the message pool

### ISSUE THREAD

**Issue by phritz** [filecoin-project/go-filecoin#1936]
TODO to fill this out properly, just capturing short notes to refer to later
- stop using message pool if we're not mining
- stop consulting message pool for the nonce after actor state; instead, keep track of messages that have been sent but have not appeared on chain and warn the user if we cannot select a nonce with high confidence
- provide a message status command or similar to surface sent message state
- have a set nonce on actor that sets it to an higher level. move nonce into state of account actor. use case is you send a message with n which fails unbeknownst to you, you send a few more that sit in the mpool and then you realize you want cancel them so you send a new message with n that sets it past the messages sent. security implications. obv.

**Comment by woshihanhaoniao** [comment]
@phritz Dear Contributor, I want to join the IPFs as a miner, but neither I nor my friends know how to use Filecoin. So sincerely ask the Contributor to tell me what kind of commands I should type in to do the four things you said.
I look forward to receiving your reply.

**Comment by anorth** [comment]
@woshihanhaoniao please ask usage questions in the [forum](https://discuss.filecoin.io/) or project Slack. We reserve GitHub issues for discussion of code contributions.

**Comment by woshihanhaoniao** [comment]
@anorth Sorry, I see.

**Comment by mishmosh** [comment]
As part of this design, please scan #1965 and consider making informational logging / progress changes to improve user comprehension of what's happening.
