### ISSUE TITLE
More robust DHT bootstrapping

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/go-filecoin#1947]
### Description
From @anacrolix on moving to bootstrapWithConfig:
"I’d recommend setting NumQueries to 2, and Timeout to 1 minute at the moment. You might also set the Period lower. you might see a message like “bootstrapping query (0/1)” or 0/2 and then “context deadline exceeded”, and no other attempts, if you do, that will be really useful i think there’s a serious bug in there that i’ve already fixed but haven’t pushed"

And also
"I would recommend 4.4.23, and the latest kbucket too"

**Comment by anacrolix** [comment]
Is there any update and feedback on this? I can make those values the defaults, and confirm the error behaviour it's working out.

**Comment by anorth** [comment]
@ZenGround0 fixed?
