### ISSUE TITLE
Move Client Propose and Query Storage Deal from Node API into Plumbing

### ISSUE THREAD

**Issue by rosalinekarr** [filecoin-project/go-filecoin#1957]
### Description

These methods are just pass throughs to the StorageMiner, so we can easily remove these methods from the Node by just adding the StorageMiner itself to plumbing, like wallet or chain reader.

**Comment by rosalinekarr** [comment]
@shannonwells I think this issue may be a dup of your current work. I'm assigning it to you to mark as done or delete once the protocol stuff gets in.

**Comment by shannonwells** [comment]
Fixed in #2325
