### ISSUE TITLE
[bug] download params, instead of generating them in deps

### ISSUE THREAD

**Issue by jbenet** [filecoin-project/go-filecoin#1975]
### issue:

- building deps
- proofs fail to build (i think it's generating the parameters)
- machine OOMs (`paramcache` tries to allocate ~500MB, but somehow not paging to disk) -- see https://github.com/filecoin-project/rust-proofs/issues/480 for the details.
- Filing this in `go-filecoin` because i think `go-filecoin` shouldn't rely on having to run `paramcache` in deps.
- This makes me unable to build go-filecoin in those machines, and it is not clear how i might build the params elsewhere and move them into place.

### discussion:

**current dependency on rust-proofs is error prone**. Requiring having to (a) build proofs from source, and (b) generate proof parameters from scratch as part of go-filecoin deps installation are both expensive, error prone, and avoidable, in different ways. I think go-filecoin should not depend on rust-proofs this way. It's highly likely to fail, because it couples two complex build processes together. 

**Decoupling through static artifacts.** 
- Instead, decoupling the build processes and having simple static outputs between them will make it much easier (and in some cases, possible at all) for people to install and use go-filecoin.
- I believe (but not sure) that the intention is for (a) to go away -- to be able to download prebuilt rust-proofs for the majority of cases, and only having to build from scratch when necessary. (ideally, for a small % of users, "off the beaten path" issue).
- I think go-filecoin shouldn't have to do (b) either -- namely it should be possible to pre-generate and just download the proof parameters.

**proof parameter artifacts.** 
- of course, static parameter artifacts are a requirement for production
- I think there should be standard param outputs as static artifacts for development, that tools like go-filecoin download (either during install/deps or at run time).
- can be served, pinned, and downloaded from ipfs (and over http from the ipfs gateway)

**proof parameter use documentation**
- go-filecoin should document how it uses the parameters and feeds them into proofs, so that users can download things and put them into the right place themselves if they need to.
- these parameters should likely live in `~/.filecoin` (and allow symlinking from there when running many instances), as the current location (i think `/tmp/filecoin-proof-parameters`) is ephemeral and not likely to work in many cases. (posting here because it should be up to `go-filecoin` to decide "where this stuff goes")

**Comment by mishmosh** [comment]
Precompiled proofs are already available, but the default instructions don't tell you so. Here's the PR to change that: https://github.com/filecoin-project/go-filecoin/pull/1983

**Comment by rosalinekarr** [comment]
Marking as closed since #1983 addresses issue.
