### ISSUE TITLE
Skip very-slow proofs tests by default, run occasionally on CI

### ISSUE THREAD

**Issue by anorth** [filecoin-project/go-filecoin#1976]
### Description
Recently-added tests under `proofs/sectorbuilder/testing` are very slow, taking some minutes to complete. Running these as part of standard developer workflows with `go test` is a drag on getting PRs ready for review. Running these on every CI build adds latency to CI results which block merging of PRs, and can clog up the backlog.

A vast majority of code changes are very unlikely to affect these tests. Let's exclude by default from developer workflows and CI, with a flag to opt-in. We should run them on CI occasionally.

### Acceptance criteria
- Very slow proofs tests are excluded from `go ... best` and default invocations of `go test ./...`, and these invocations take <120s on a representative dev laptop
- The same tests are excluded from default CI builds
- There's a mechanism to opt-in to the excluded tests
- A new CI workflow exercises these tests once every few hours

### Risks + pitfalls
- The CI workflow to test these adds a little operational complexity
- Developers working on code that may break these tests must be aware of the need to opt-in to them.
- Don't use the existing `-short` flag to `go test`; we'll reserve this for opt-in skipping of only moderately slow tests

### Where to begin
See https://github.com/filecoin-project/go-filecoin/blob/master/functional-tests/faucet_test.go for another place we've flagged some tests out by default (but that flag is set for CI every time).

**Comment by phritz** [comment]
note this issue is already in progress, rkowalick is just out sick
