### ISSUE TITLE
Allow precompiled rust proofs without a github access token

### ISSUE THREAD

**Issue by rkowalick** [filecoin-project/go-filecoin#1981]
### Description

We no longer need a github token to access the rust-proofs repository. We can remove that step from the `install-rust-proofs` script to allow users to more easily use the precompiled version of rust-proofs.

### Acceptance criteria

`FILECOIN_USE_PRECOMPILED_RUST_PROOFS=true` will successfully install precompiled rust proofs without needing a github token.

### Risks + pitfalls

None

### Protocol Changes

None

### Where to begin

`scripts/install-rust-proofs.sh`

**Comment by mishmosh** [comment]
On a Macbook, using precompiled proofs drops the time to run `deps` from 31mins to 8.5mins.
