### ISSUE TITLE
Remove Version from Node API

### ISSUE THREAD

**Issue by rosalinekarr** [filecoin-project/go-filecoin#1982]
### Description

Remove the Version method from the node api and extract its functionality to commands, since it's so small.

**Comment by songjiayang** [comment]
Right, I test with same problem

<img width="845" alt="screen shot 2019-02-15 at 10 42 24 am" src="https://user-images.githubusercontent.com/1459834/52831486-cc196e80-310f-11e9-8cff-f4ac5d1eda9c.png">
