### ISSUE TITLE
Move Swarm Find Peers from Node API into Porcelain

### ISSUE THREAD

**Issue by rosalinekarr** [filecoin-project/go-filecoin#1986]
### Description

Move the swarm find peers method from the Node API into Porcelain. This will require moving several other aspect of libp2p into network plumbing.

**Comment by ZenGround0** [comment]
This one should move to a subcommand of the new `dht` command and should add the call `FindPeer` to filnet:Router.  This should be trivial because the interface that the Router struct wraps already implements this call.
