### ISSUE TITLE
Dockerfiles use Go version below what Readme suggest to be required

### ISSUE THREAD

**Issue by imrehg** [filecoin-project/go-filecoin#1989]
The readme says that `Go >= 1.11.2` is required ([link to section](https://github.com/filecoin-project/go-filecoin/tree/271a6812e23e3ccd80642d251e1c1f449459a8b7#install-go-and-rust))

On the other hand, the `Dockerfile`s in the repo are using 1.11.1, for example https://github.com/filecoin-project/go-filecoin/blob/271a6812e23e3ccd80642d251e1c1f449459a8b7/Dockerfile#L1

**Comment by rosalinekarr** [comment]
@gmasgras, can you take a look at this?

**Comment by mishmosh** [comment]
Closing, fixed in #2045.
