### ISSUE TITLE
Error: go run ./build/*.go deps

### ISSUE THREAD

**Issue by pkrasam** [filecoin-project/go-filecoin#1994]
Getting error when running this command...

```
FILECOIN_USE_PRECOMPILED_RUST_PROOFS=true go run ./build/*.go deps
build/main.go:15:2: cannot find package "github.com/filecoin-project/go-filecoin/util/version" in any of:
	/usr/lib/go-1.10/src/github.com/filecoin-project/go-filecoin/util/version (from $GOROOT)
	/root/go/src/github.com/filecoin-project/go-filecoin/util/version (from $GOPATH)
root@mn00_FIL:/src/github.com/filecoin-project/go-filecoin# 
```

**Comment by travisperson** [comment]
It looks like you do not have the source code checked out into your `$GOPATH`.

You can probably solve this by setting `GOPATH` to `$HOME` (give the information above).

**Comment by pkrasam** [comment]
Thank you @travisperson I am going to start from a clean build.

**Comment by anorth** [comment]
@pkrasam did this resolve your issue?

**Comment by rosalinekarr** [comment]
@pkrasam I'm going to assume this issue was resolved. If not, just let me know and I'll reopen.
