### ISSUE TITLE
PoSt Randomness outside the State Machine 

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/go-filecoin#1996]
### Description
The work in #1617 is done and so the state machine can sample chain randomness.  A simpler task that remains is to get randomness from back in the chain from outside the state machine (in particular from within the storage miner protocol).  It should be simple to get the correct number of blocks by adding the chain accessor methods to the storage miner plumbing interface and taking `lookback` ancestor tipsets.

Ideally the function that samples the bytes value from a tipset should be abstracted away from the current `vmcontext.Rand` method and reused in the storage miner.

### Acceptance criteria
Storage miners can access randomness from the chain.

### Where to begin
vmcontext.Rand and storage/miner.go

**Comment by laser** [comment]
This is blocked on rust-fil-proofs issue [505](https://github.com/filecoin-project/rust-fil-proofs/issues/505).

**Comment by laser** [comment]
@ZenGround0 - How does this break the protocol?
