### ISSUE TITLE
[bug]parameter_cache

### ISSUE THREAD

**Issue by Pacius** [filecoin-project/go-filecoin#1998]
**Describe the bug**
place: storage-proofs/src/parameter_cache.rs:54 storage_proofs::parameter_cache, root: storage-proofs

**To Reproduce**

`FILECOIN_USE_PRECOMPILED_RUST_PROOFS=true go run ./build/*.go deps`

See error:
Pretty sure it's not a problem of insufficient memory.

**OS**
New ubuntu 16.04

```
_identifier: drgporep::PublicParams{graph: zigzag_graph::ZigZagGraph{expansion_degree: 8 base_graph: drgraph::BucketGraph{size: 32; degree: 5} }; sloth_iter: 0}, challenges: Tapered { layers: 4, count: 2, taper: 0.3333333333333333, taper_layers: 2 } }, target: params, place: storage-proofs/src/parameter_cache.rs:54 storage_proofs::parameter_cache, root: storage-proofs
Feb 16 02:32:33.474 INFO checking cache_path: "/tmp/filecoin-proof-parameters/v9-zigzag-proof-of-replication-f8b6b5b4f1015da3984944b4aef229b63ce950f65c7f41055a995718a452204d", target: params, place: storage-proofs/src/parameter_cache.rs:83 storage_proofs::parameter_cache, root: storage-proofs
Feb 16 02:32:33.475 INFO reading groth params from cache: "/tmp/filecoin-proof-parameters/v9-zigzag-proof-of-replication-f8b6b5b4f1015da3984944b4aef229b63ce950f65c7f41055a995718a452204d", target: params, place: storage-proofs/src/parameter_cache.rs:126 storage_proofs::parameter_cache, root: storage-proofs
Feb 16 02:32:42.989 INFO groth_parameter_bytes: 770902584, target: stats, place: storage-proofs/src/parameter_cache.rs:131 storage_proofs::parameter_cache, root: storage-proofs
Feb 16 02:32:43.030 INFO parameter set identifier for cache: layered_drgporep::PublicParams{ drg_porep_identifier: drgporep::PublicParams{graph: zigzag_graph::ZigZagGraph{expansion_degree: 8 base_graph: drgraph::BucketGraph{size: 8388608; degree: 5} }; sloth_iter: 0}, challenges: Tapered { layers: 4, count: 2, taper: 0.3333333333333333, taper_layers: 2 } }, target: params, place: storage-proofs/src/parameter_cache.rs:54 storage_proofs::parameter_cache, root: storage-proofs
Feb 16 02:32:43.031 INFO checking cache_path: "/tmp/filecoin-proof-parameters/v9-zigzag-proof-of-replication-52431242c129794fe51d373ae29953f2ff52abd94c78756e318ce45f3e4946d8", target: params, place: storage-proofs/src/parameter_cache.rs:83 storage_proofs::parameter_cache, root: storage-proofs
Feb 16 02:32:43.031 INFO reading groth params from cache: "/tmp/filecoin-proof-parameters/v9-zigzag-proof-of-replication-52431242c129794fe51d373ae29953f2ff52abd94c78756e318ce45f3e4946d8", target: params, place: storage-proofs/src/parameter_cache.rs:126 storage_proofs::parameter_cache, root: storage-proofs
Feb 16 02:32:43.032 INFO groth_parameter_bytes: 0, target: stats, place: storage-proofs/src/parameter_cache.rs:131 storage_proofs::parameter_cache, root: storage-proofs
Feb 16 02:32:43.032 INFO Actually generating groth params., target: params, place: storage-proofs/src/parameter_cache.rs:70 storage_proofs::parameter_cache, root: storage-proofs
memory allocation of 1088489088 bytes failedCommand './proofs/bin/paramcache' failed: signal: aborted (core dumped)
exit status 1
```

**Comment by joshgarde** [comment]
I noticed that using the `0.0.2` release caused a memory leak in param_cache while `0.0.1` didn't have the same problem.

**Comment by schomatis** [comment]
I don't think it's a memory leak, the computation needed for the mathematical model behind the proofs system (the Rust part of the code base, what is called here the "groth params") is quite expensive, both in terms of memory and computation. However, I think there's a command available to download most of that information instead of needing to produce it locally, let me check that.

**Comment by joshgarde** [comment]
I was running `0.0.1`'s param_cache and not even swapping to disk. With `0.0.2` I had to close out of everything on my desktop while it was generating the groth params and it was maxing out my 8G of RAM and swapping. I can try doing a clean build again to see if I get the same results.

**Comment by schomatis** [comment]
Yes, that is expected, since the amount of computation depends on internal security parameters that are probably being changed across versions.

**Comment by schomatis** [comment]
**Do this under your own risk**: it's highly experimental and insecure.

```
curl http://ipfs.io/ipfs/QmY8UR7sPGgfeoVB381mrvcdVK4QF28qV5cdoyZFfPuUfM -o /tmp/filecoin-proof-parameters/v9-zigzag-proof-of-replication-f8b6b5b4f1015da3984944b4aef229b63ce950f65c7f41055a995718a452204d

curl http://ipfs.io/ipfs/QmP7yBN63YRmnQt7p7ZTQWgahwniNgSoJL5KD1b8eKmGWr -o /tmp/filecoin-proof-parameters/v9-zigzag-proof-of-replication-52431242c129794fe51d373ae29953f2ff52abd94c78756e318ce45f3e4946d8
```

Well, we have a command for doing this but the JSON file it needs it's not in the usual place and it is complaining so I'm issuing the internal `curl` command manually. This downloads what the log announces it's `Actually generating`. There are two different parameters, I'm downloading the first one since that was what *my* log told me it was generating, in the log of this issue that parameter seemed to have been found and it was actually generating the second one.

I'm downloading this at the moment so I'm not sure if it works, I'll report back later.

**Comment by joshgarde** [comment]
So I'm guessing that using preshared params is a security problem? Really puts a dent on my plans to spin up a few Pi based nodes

**Comment by schomatis** [comment]
No, the way *I* am doing things in this post is the insecure part :)

The proofs use shared parameters but they are not *secret*.

**Comment by schomatis** [comment]
Downloading the parameters worked, although they have a considerable size (adding up to roughly 2.3 GB), so it's basically a trade-off between connection bandwidth and local cpu/memory resources.

Closing in favor of https://github.com/filecoin-project/go-filecoin/issues/2008.
