### ISSUE TITLE
Unable to find libclang

### ISSUE THREAD

**Issue by zhangkuicheng** [filecoin-project/go-filecoin#2000]
hello:
my environment is "CentOS Linux release 7.5.1804 (Core)", when I run as deps , it would stop ,just like that:

# FILECOIN_USE_PRECOMPILED_RUST_PROOFS=true go run ./build/*.go deps

`go get -u github.com/pmezard/go-difflib/difflib
./scripts/install-rust-proofs.sh
using precompiled rust-proofs
fatal: Invalid object name '@'.

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   129  100   129    0     0    139      0 --:--:-- --:--:-- --:--:--   139

release @:./proofs/rust- does not exist, GitHub said {
  "message": "Not Found",
  "documentation_url": "https://developer.github.com/v3/repos/releases/#get-a-release-by-tag-name"
}

ensure your access token has full repo scope
failed to find or obtain precompiled rust-proofs, falling back to local
/home/go/src/github.com/filecoin-project/go-filecoin/proofs/rust-proofs /home/go/src/github.com/filecoin-project/go-filecoin
cargo 1.32.0-nightly (5e85ba14a 2018-12-02)
    Updating crates.io index
    Updating git repository `https://github.com/zcash-hackworks/sapling-crypto`
    Updating git repository `https://github.com/dignifiedquire/rust-gperftools`
    Updating git repository `https://github.com/filecoin-project/merkle_light`
    Updating git repository `https://github.com/gtank/blake2-rfc`
   Compiling filecoin-proofs v0.1.0 (/home/go/src/github.com/filecoin-project/go-filecoin/proofs/rust-proofs/filecoin-proofs)
error: failed to run custom build command for `filecoin-proofs v0.1.0 (/home/go/src/github.com/filecoin-project/go-filecoin/proofs/rust
-proofs/filecoin-proofs)`process didn't exit successfully: `/home/go/src/github.com/filecoin-project/go-filecoin/proofs/rust-proofs/target/release/build/filecoi
n-proofs-260b9406bc363c6a/build-script-build` (exit code: 101)--- stderr
thread 'main' panicked at 'Unable to find libclang: "the `libclang` shared library at /usr/lib64/clang-private/libclang.so.5.0 could no
t be opened: libclangAST.so.5: cannot open shared object file: No such file or directory"', src/libcore/result.rs:1009:5note: Run with `RUST_BACKTRACE=1` for a backtrace.

/home/go/src/github.com/filecoin-project/go-filecoin
cp: cannot stat ‘proofs/rust-proofs/target/release/paramcache’: No such file or directory
cp: cannot stat ‘proofs/rust-proofs/target/release/libfilecoin_proofs.a’: No such file or directory
cp: cannot stat ‘proofs/rust-proofs/target/release/libfilecoin_proofs.pc’: No such file or directory
Command './scripts/install-rust-proofs.sh' failed: exit status 1
exit status 1
`
what matter with me ,what should i do?

**Comment by zhangkuicheng** [comment]
my evironment just like that:
`
# go version
go version go1.11.2 linux/amd64

# rustc -V
rustc 1.34.0-nightly (a9410cd1a 2019-02-15)

# cargo -V
cargo 1.34.0-nightly (865cb7010 2019-02-10)

# gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/local/gcc/libexec/gcc/x86_64-pc-linux-gnu/8.2.0/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: ../configure --prefix=/usr/local/gcc --enable-bootstrap --enable-checking=release --enable-languages=c,c++ --disable-m
ultilibThread model: posix
gcc version 8.2.0 (GCC)

 # gx --version
gx version 0.14.0
`

**Comment by NatoBoram** [comment]
```yaml
nato@hp-server
--------------
OS: Ubuntu 18.04.2 LTS x86_64
Host: HP G62 Notebook PC 0598120000202710010020100
Kernel: 4.15.0-46-generic
Uptime: 1 hour, 45 mins
Packages: 649
Shell: bash 4.4.19
Terminal: /dev/pts/3
CPU: Intel i3 M 370 (4) @ 2.399GHz
GPU: Intel Core Processor
Memory: 795MiB / 3744MiB
```

```bash
./scripts/install-rust-proofs.sh
using local rust-proofs
~/go/src/github.com/filecoin-project/go-filecoin/proofs/rust-proofs ~/go/src/github.com/filecoin-project/go-filecoin
cargo 1.32.0-nightly (5e85ba14a 2018-12-02)
    Updating crates.io index
    Updating git repository `https://github.com/zcash-hackworks/sapling-crypto`
    Updating git repository `https://github.com/dignifiedquire/rust-gperftools`
    Updating git repository `https://github.com/filecoin-project/merkle_light`
    Updating git repository `https://github.com/gtank/blake2-rfc`
   Compiling filecoin-proofs v0.1.0 (/home/nato/go/src/github.com/filecoin-project/go-filecoin/proofs/rust-proofs/filecoin-proofs)
error: failed to run custom build command for `filecoin-proofs v0.1.0 (/home/nato/go/src/github.com/filecoin-project/go-filecoin/proofs/rust-proofs/filecoin-proofs)`
process didn't exit successfully: `/home/nato/go/src/github.com/filecoin-project/go-filecoin/proofs/rust-proofs/target/release/build/filecoin-proofs-5c0848e970cff4bd/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'Unable to find libclang: "couldn\'t find any valid shared libraries matching: [\'libclang.so\', \'libclang-*.so\', \'libclang.so.*\'], set the `LIBCLANG_PATH` environment variable to a path where one of these files can be found (invalid: [])"', src/libcore/result.rs:1009:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.

~/go/src/github.com/filecoin-project/go-filecoin
cp: cannot stat 'proofs/rust-proofs/target/release/paramcache': No such file or directory
cp: cannot stat 'proofs/rust-proofs/target/release/libfilecoin_proofs.a': No such file or directory
cp: cannot stat 'proofs/rust-proofs/target/release/libfilecoin_proofs.pc': No such file or directory
Command './scripts/install-rust-proofs.sh' failed: exit status 1
exit status 1
```

**Comment by schomatis** [comment]
Yes, similar to #2003, check that `jq` is installed.

**Comment by NatoBoram** [comment]
Hello @schomatis! Installing `jq` solved #2003 but not #2000 for me. I'm trying to run `FILECOIN_USE_PRECOMPILED_RUST_PROOFS=false go run ./build/*.go deps`. Is there a specific package I should install?

**Comment by schomatis** [comment]
Did you install `libclang`?

**Comment by NatoBoram** [comment]
```
E: Unable to locate package libclang
```

There are multiple version of that available.

```
libclang1                libclang1-4.0-dbg        libclang1-6.0-dbg        libclang-5.0-dev         libclang-common-4.0-dev  libclang-dev
libclang1-3.9            libclang1-5.0            libclang1-7              libclang-6.0-dev         libclang-common-5.0-dev  libclang-perl
libclang1-3.9-dbg        libclang1-5.0-dbg        libclang-3.9-dev         libclang-7-dev           libclang-common-6.0-dev
libclang1-4.0            libclang1-6.0            libclang-4.0-dev         libclang-common-3.9-dev  libclang-common-7-dev
```

I ended up installing `clang`, which depends on `clang-6.0` and `libclang1-6.0`. The error is gone, and it's working!

Perhaps `clang` could be added as a dependency in the [README.md](https://github.com/filecoin-project/go-filecoin/#install-dependencies)?

**Comment by schomatis** [comment]
It's already there, but yes, we should give it more visibility, and we should centralize all the dependencies in a single, clear list.

**Comment by NatoBoram** [comment]
```
./scripts/copy-groth-params.sh
/tmp/filecoin-proof-parameters ~/go/src/github.com/filecoin-project/go-filecoin
ln: failed to create symbolic link 'params.out': File exists
~/go/src/github.com/filecoin-project/go-filecoin
```

Perhaps it would be a good idea to add `-f` in `ln -s ${params_file} params.out`?

**Comment by schomatis** [comment]
Probably, I think we'll always want the latest version in `params.out`. Good catch, would you mind opening a separate issue about it?

**Comment by NatoBoram** [comment]
Done!  #2013
