### ISSUE TITLE
Make the user aware of the parameters generation

### ISSUE THREAD

**Issue by schomatis** [filecoin-project/go-filecoin#2008]
Both in terms of computer resources and user's time. A note should be added in the [Getting Started](https://github.com/filecoin-project/go-filecoin/wiki/Getting-Started) guide. And if possible, provide instructions for the user to download them instead, through `paramfetch` (if that tool is meant for the normal user).

This can be *very* frustrating for a new user excited to try Filecoin for the very first time and stumbling upon a very expensive computation for which it wasn't notified of nor it understands its motivation.

See https://github.com/filecoin-project/go-filecoin/issues/1998 as an example.

**Comment by anorth** [comment]
We don't intend users to need to generate the parameters, this is a (hopefully brief) interim. See #1975.

**Comment by schomatis** [comment]
I see, but this interim exists as of today (even if it will hopefully be solved soon), so maybe it's still worth adding a note to the user testing Filecoin now.

**Comment by rosalinekarr** [comment]
Thanks to PR #1975, we now download params instead of generating them, so I'm closing this.
