### ISSUE TITLE
[bug] Building the supplied Dockerfile fails at one of the COPY steps

### ISSUE THREAD

**Issue by imrehg** [filecoin-project/go-filecoin#2009]
**Describe the bug**
Cannot successfully build the docker image based on the supplied `Dockerfile`, as one of the libraries referenced don't seem to be built anymore / don't exists.

**To Reproduce**
1. Check out the repository
2. Run the docker build with `docker build .`
3. Wait for a while until the image builds.... (can be 1+ hour)
4. Observe this error:

**Expected behavior**
Docker image successfully building.

**Screenshots**
```
...
Step 32/40 : COPY --from=builder $SRC_DIR/proofs/rust-proofs/target/release/libsector_base.so /lib/libsector_base.so
COPY failed: stat /var/lib/docker/overlay2/a0907c1c1f89571dda229a8e4648fffae08329445e702392e99cacf5b600c452/merged/go/src/github.com/filecoin-project/go-filecoin/proofs/rust-proofs/target/release/libsector_base.so: no such file or directory
```

**Comment by rosalinekarr** [comment]
@gmasgras, can you look into this?
