### ISSUE TITLE
[bug] Wallet address listing is not in stable order

### ISSUE THREAD

**Issue by imrehg** [filecoin-project/go-filecoin#2012]
**Describe the bug**
When listing addresses inside the node, the order is not stable, thus might cause difficulties, people working with a different address than they mean to, if they use scripting to get addresses for their task.

**To Reproduce**
1. Create some new addresses with `go-filecoin address new`
2. Run listing the addresses a few times: `go-filecoin wallet addrs ls`
3. Se the order changing at some attempts

**Expected behavior**
The order being stable, and repeatable with both `go-filecoin wallet addrs ls` and `go-filecoin wallet addrs ls --enc=json`

**Screenshots**
Some example tries:
```
...
~> go-filecoin wallet addrs ls
fcq0mhjypzl368jk30kh8qc2534kymhum4729wk8l
fcq6kl2v8acz9m69h8u43scuu02ckdwjju63pyfh9
~> go-filecoin wallet addrs ls
fcq6kl2v8acz9m69h8u43scuu02ckdwjju63pyfh9
fcq0mhjypzl368jk30kh8qc2534kymhum4729wk8l
~> go-filecoin wallet addrs ls
fcq0mhjypzl368jk30kh8qc2534kymhum4729wk8l
fcq6kl2v8acz9m69h8u43scuu02ckdwjju63pyfh9
~> go-filecoin wallet addrs ls
fcq0mhjypzl368jk30kh8qc2534kymhum4729wk8l
fcq6kl2v8acz9m69h8u43scuu02ckdwjju63pyfh9
```
The second one is in a different order than the rest.

**Comment by schomatis** [comment]
https://github.com/filecoin-project/go-filecoin/blob/7a875edf5eb423bf8011a0437f26ceac5f1511be/wallet/wallet.go#L67-L73

Yes please :)

**Comment by imrehg** [comment]
@schomatis great catch! :D

> `// Always sorted in the same order.`

vs

> `// TODO: Should we make this ordering deterministic?`

Something's gotta give :P
