### ISSUE TITLE
[bug] Invalid go version

### ISSUE THREAD

**Issue by Luca8991** [filecoin-project/go-filecoin#2016]
**Describe the bug**
Cannot install filecoin due to **go version error**, following the guide at [README.md](https://github.com/filecoin-project/go-filecoin/#install-dependencies)

**To Reproduce**
1. I'm in the `${GOPATH}/src/github.com/filecoin-project/go-filecoin` folder
2. Run this command `FILECOIN_USE_PRECOMPILED_RUST_PROOFS=true go run ./build/*.go deps`
3. See error: 
```bash
Invalid go version: go1.10.4                                                                                                                                                                                       
exit status 1
```

**Expected behavior**
Clear installation

**Desktop (please complete the following information):**
 - OS: Ubuntu
- Version: 18.04.2 LTS

**Comment by schomatis** [comment]
Hey @Luca8991, the README has a tutorial to help you download the latest version of `go`, additionally you could try [`snap`](https://snapcraft.io/go) which works very well for Ubuntu.
