### ISSUE TITLE
[bug] error unknown option "devnet-user"

### ISSUE THREAD

**Issue by pengxiankaikai** [filecoin-project/go-filecoin#2020]
**Describe the bug**
run go-filecoin init --devnet-user --genesisfile=http://user.kittyhawk.wtf:8020/genesis.car
go-filecoin init fail

**Comment by travisperson** [comment]
Can you provide any additional details? If you downloaded a binary can you try to build from the `devnet-user` git tag?

**Comment by pengxiankaikai** [comment]
I am using the mac os system, the downloaded binary file is compiled, and the above command is executed after decompression. Thank you.

**Comment by rosalinekarr** [comment]
@pengxiankaikai where are you finding this compiled binary file? we don't currently have a binary for download and are encouraging contributors to build from source in the meantime.

**Comment by pengxiankaikai** [comment]
@rosalinekarr I downloaded the package under the release of the node, I am now also solved by the self-compiled file startup, thank you!

**Comment by shannonwells** [comment]
@pengxiankaikai if you are satisfied with a self-compiled file startup, we'd like to close this issue.
