### ISSUE TITLE
[bug] wallet export / import use the different format

### ISSUE THREAD

**Issue by thomas92911** [filecoin-project/go-filecoin#2024]
when I export my wallet addr:
```sh
go-filecoin wallet export fcqhn.....
```
got
```
Address:	fcqhn.....
PrivateKey:	ceaf5e302....
Curve:		secp256k1
```

or use `--enc=json` get a json output, but
```sh
go-filecoin wallet import <walletFile> 
```
got
```
Error: invalid length, need 256 bits
```

why not wallet export / import use the same format

**Comment by rosalinekarr** [comment]
@thomas92911, can you give us a little more detail regarding the issue? What OS are you using and how exactly did you call these commands?

`go-filecoin wallet import` should take a file exported by `go-filecoin wallet export` just fine.

**Comment by thomas92911** [comment]
my problem command:
```sh
go-filecoin wallet export fcqnvgwnmnzlnx305uxr8pnja64vujrams3lqg9sj>a.txt
go-filecoin wallet import ./a.txt
```
got
```
Error: invalid character 'A' looking for beginning of value
```


I hope the `go-filecoin wallet import` command can support the different format from export
```sh
go-filecoin wallet export --enc=text
go-filecoin wallet export --enc=json
```

or
```sh
go-filecoin wallet import <PrivateKey> <Curve>
```

**Comment by rosalinekarr** [comment]
Hmm, you shouldn't need to specify any encoding to get this to work. Something is definitely broken. @frrist, I think you were the last one to touch this code. Can you look into this issue?

**Comment by frrist** [comment]
Yes I can take a look at this week, or early next week once I land some stuff that's inflight.
