### ISSUE TITLE
Unable to get FIL Mock[bug]

### ISSUE THREAD

**Issue by yph152** [filecoin-project/go-filecoin#2025]
**Describe the bug**
I executed FIL at ```http://user.kittyhawk.wtf:9797/tap```, and returned ```Success! Message CID: zDPWYqFCsxAcpDyZrSFeHr78KzkWMztfM15mprNQr14aFTM65JRB```, but the account is still 0.

**Comment by travisperson** [comment]
Receiving funds is not instantaneous. The returned Message CID is the message which contains the information about the transfer.

You can wait for the message to show up by issuing a `message wait` on the provided CID.

```
go-filecoin message wait zDPWYqFCsxAcpDyZrSFeHr78KzkWMztfM15mprNQr14aFTM65JRB
```

If you just started a node, you will need to sync the entire chain first, as your message is going to need to be mined into a block first. Chain syncing can take some time at the moment, and times can vary between users.

If your chain is already synced when you submit for funds, it might take up to 2-3 minutes for a block to pick up the message.

I was able to confirm that your message with funds was in block `10926`, in block `zDPWYqFCx1oGcY9Fo6QkdWJhx26B95dqecnM8E62aCqvaVBmjL1a`.

If you still have your node around, let it sync the entire chain, and you should see your funds show up in your wallet.

**Comment by rosalinekarr** [comment]
Marking as closed.
