### ISSUE TITLE
fatal error : stdlib.h

### ISSUE THREAD

**Issue by zjoooooo** [filecoin-project/go-filecoin#2026]
### Description
root@vultr:~/code/go/src/github.com/filecoin-project/go-filecoin# FILECOIN_USE_PRECOMPILED_RUST_PROOFS=true go run ./build/*.go deps
pkg-config --version
0.29.1
Installing dependencies...
go get -u github.com/whyrusleeping/gx
runtime/cgo
_cgo_export.c:3:10: fatal error: stdlib.h: No such file or directory
 include <stdlib.h>
          ^~~~~~~~~~
compilation terminated.
Command 'go get -u github.com/whyrusleeping/gx' failed: exit status 2
exit status 1

### Go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/root/code/go"
GOPROXY=""
GORACE=""
GOROOT="/snap/go/3129"
GOTMPDIR=""
GOTOOLDIR="/snap/go/3129/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmess                                                                      age-length=0 -fdebug-prefix-map=/tmp/go-build084141052=/tmp/go-build -gno-record                                                                      -gcc-switches"

### Code path
root@vultr:~# ls
code  go  go1.11.4.linux-amd64.tar.gz  snap

Anybody know how to fix it fatal error: stdlib.h ?

**Comment by rosalinekarr** [comment]
@travisperson, do you mind taking this one?

**Comment by whyrusleeping** [comment]
@zjoooooo thats a weird one... do you have gcc or clang installed?

**Comment by zjoooooo** [comment]
Yes, I already install gcc.

**Comment by anorth** [comment]
This issue may be stale from the previous release. @zjoooooo did you resolve your problem?

**Comment by btcioner** [comment]
OS X Mojave moved the location of stdlib.h out of /usr/include. This issue exists for other packages and there are several possible solutions suggested in this thread for neovim issue #9050. Thanks to Filecoin community member A_jinbin_filecoin.cn for the link.

**Comment by btcioner** [comment]
https://github.com/neovim/neovim/issues/9050

**Comment by anorth** [comment]
I think this issue has gone stale, particularly since we have moved to go modules from gx so the original case is not longer reproducible. Please re-open with a new reproduction if this is incorrect.

**Comment by vhosakot** [comment]
I saw the error in Ubuntu `18.04`:

```
_cgo_export.c:3:10: fatal error: stdlib.h: No such file or directory
```

and doing `sudo apt install --reinstall build-essential` resolved the error for me.

**Comment by KwokGH** [comment]
> I saw the same error in Ubuntu `18.04`:
> 
> ```
> _cgo_export.c:3:10: fatal error: stdlib.h: No such file or directory
> ```
> 
> and doing `sudo apt install --reinstall build-essential` resolved the error for me.

good

**Comment by dokdred** [comment]
> I saw the same error in Ubuntu `18.04`:
> 
> ```
> _cgo_export.c:3:10: fatal error: stdlib.h: No such file or directory
> ```
> 
> and doing `sudo apt install --reinstall build-essential` resolved the error for me.

this resolved my the same problem on Linux mint 19

**Comment by WindClam** [comment]
> I saw the same error in Ubuntu `18.04`:
> 
> ```
> _cgo_export.c:3:10: fatal error: stdlib.h: No such file or directory
> ```
> 
> and doing `sudo apt install --reinstall build-essential` resolved the error for me.

good , this resolved my the same problem on linux mint 20.

**Comment by rost5000** [comment]
I had the same issue. When I installed `musl-dev`, the problem was solved

**Comment by MinsonLee** [comment]
> I had the same issue. When I installed `musl-dev`, the problem was solved in alpine

@rost5000 wow, thanks a lot~

**Comment by LaptevPavelA** [comment]
BusyBox:
apk add git
apk add gcc
apk --no-cache --update add build-base

**Comment by LaptevPavelA** [comment]
Alpine Linux 10.2.1_pre1:
apk add git
apk add gcc
apk --no-cache --update add build-base

**Comment by oGabrielArruda** [comment]
@LaptevPavelA that worked for alpine images, thanks man!

**Comment by mansakelabs** [comment]
I'm getting this when running `yay -S yay` in SteamOS 3.4.6


`# runtime/cgo
_cgo_export.c:3:10: fatal error: stdlib.h: No such file or directory
    3 | #include <stdlib.h>
      |          ^~~~~~~~~~
compilation terminated.
make: *** [Makefile:117: yay] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
 -> error making: yay`


I'm attempting to upgrade yay from v11.0.3 to v12.0.5-1.
I have used pacman to install go, clang, musl, and any other missing packages declared by yay.
Still no dice.

**Comment by lexmirnov** [comment]
> I'm getting this when running `yay -S yay` in SteamOS 3.4.6

@mansakelabs i managed to get it working with this: https://www.reddit.com/r/SteamDeck/comments/xgs27m/installing_snap_on_steamdeck/

**Comment by josevitormorais** [comment]
> sudo apt install --reinstall build-essential

this works for me, thanks.
linux mint: 21

**Comment by zhucan** [comment]
if under centos7，is there a way to fix it?
