### ISSUE TITLE
High priority fixes and improvements

### ISSUE THREAD

**Issue by mishmosh** [filecoin-project/go-filecoin#2027]
A set of highest-priority bugs and productivity improvements discovered after opening repos. We will start with the problems that will require more time to diagnose/support than to simply fix: things that are incorrect, cause crashes, etc.

**Comment by phritz** [comment]
to be clear what we are looking for here:
- things that are relatively small in scope, <= 3 points
- anything that is incorrect wrt protocol (eg, wrong units)
- anything that is going to eat more helpdesk/slack time to explain/accommodate than it would take to fix
- things that are very confusing/annoying to users or devs
- any crashes, unexpected errors, etc.

**Comment by anorth** [comment]
This epic was created in the wake of the open sourcing and initial release of go-filecoin, and has now served its purpose. We still have outstanding issues, but many are less well defined than this epic calls for, and we are no longer devoting explicit time to these issues, outside consideration of all the other things we could build or fix.

I'll close this issue now.
