### ISSUE TITLE
move protocol calls from node api into protocol apis

### ISSUE THREAD

**Issue by phritz** [filecoin-project/go-filecoin#2030]
We should have protocol apis of some sort that sit on top of protocols on which commands can depend.  Mining start/stop is the canonical example of this  -- it should move out of the node api, and not into plumbing/porcelain,  but into its own;  a new api that is higher level. Anything that interacts with storage miner / cilent and retrieval miner / client, things which themselves rely on plumbing/porcelain, should move out of node api into this / these new apis.

See [Architecture Overview](https://github.com/filecoin-project/go-filecoin/blob/master/CODEWALK.md#architecture-overview) 

cc @rosalinekarr who is working on a plan to move the non protocol stuff out of node api in #1858

**Comment by shannonwells** [comment]
All the actual protocol stuff is moved now as of #2325
