### ISSUE TITLE
High memory usage (possible leak) on user devnet [bug]

### ISSUE THREAD

**Issue by gmasgras** [filecoin-project/go-filecoin#2031]
**Describe the bug**
The memory usage of some go-filecoin nodes running on the `user-devnet` is very high. 
One of the nodes went all the way up to 10GB and resulted in the process (running inside a docker container) to be killed (and then restarted by the docker daemon)

**To Reproduce**
1. Have `go-filecoin` run on the `usernet` for a few days (height 12605)

**Expected behavior**
Some of the memory should be reclaimed. 

**Screenshots**
[Grafana graphs](https://protocollabs.grafana.net/d/oesf9T1iz/kittyhawk?refresh=30s&orgId=1&var-instance_name=user&from=now-24h&to=now)
<img width="713" alt="screen shot 2019-02-19 at 1 47 37 pm" src="https://user-images.githubusercontent.com/42549113/53054707-16755500-345a-11e9-8694-3d686538fef4.png">

**Desktop (please complete the following information):**
 - OS: Linux 4.15.0-1021-aws
 - Version `devnet-user` tag

**pprof dumps:**
goroutine dump:
https://gateway.ipfs.io/ipfs/QmYhcVFQDsNDAiq9miGaSeN8rrq3CiBvAsqtn3X5XymFDC

30 second cpu profile
https://gateway.ipfs.io/ipfs/QmcEJFugAVaHUXQjyeSZexzzbSvKV8PdPPMzWNn53UCg2M

heap trace dump
https://gateway.ipfs.io/ipfs/QmZciR9C56BTcgu843sNeJZhhZnjrgq7mghP7vHTU6bkba

go-filecoin binary
https://gateway.ipfs.io/ipfs/QmbvQ5KriHLmxbUCGUW5JJFjeKzdQxRb1Y4yu9anQisy7k

**Comment by whyrusleeping** [comment]
@gmasgras could you also upload the exact binary being used? the debug symbols for interpreting a lot of this is in there

**Comment by anorth** [comment]
Is there anything environmental that distinguishes the node that crashed from the others? Was it running longer? Was it storing more pieces? Any protocol-level factors?

**Comment by phritz** [comment]
moving this to ready in case anyone has time to pick it up

**Comment by gmasgras** [comment]
> Is there anything environmental that distinguishes the node that crashed from the others? Was it running longer? Was it storing more pieces? Any protocol-level factors?

All of the nodes on that instance are running the same version of the code. 
It seems that they're all suffering from the same leak, 3/5 have already restarted due to OOM, the other 2 will probably restart soon, based on the [graphs](https://protocollabs.grafana.net/d/oesf9T1iz/kittyhawk?refresh=30s&orgId=1&from=now-7d&to=now&var-instance_name=user)

**Comment by gmasgras** [comment]
> @gmasgras could you also upload the exact binary being used? the debug symbols for interpreting a lot of this is in there

added link to description

**Comment by mslipper** [comment]
Hi there,

I'm experiencing the following error on the dashboard's backend as well. I've attached the output of `/debug/pprof/heap` to this message. It's become particularly bad over the past day; `go-filecoin` runs out of memory roughly hourly. This happens whether the dashboard is running or not.

[out.txt](https://github.com/filecoin-project/go-filecoin/files/3045273/out.txt)
[out2.txt](https://github.com/filecoin-project/go-filecoin/files/3045275/out2.txt)

**Comment by mslipper** [comment]
Possibly related: https://github.com/filecoin-project/go-filecoin/issues/2500. This is a fairly new occurrence on the user devnet.

**Comment by gmasgras** [comment]
The leaks seem to have gotten worse with the `0.1.4` release. Nodes last about 2 days before getting OOM'd. 

Here are 6 pprof samples (taken every 10 mins over an hour) of a node running on the user devnet:
https://gateway.ipfs.io/ipfs/QmNW9q8usyFZryBtCyK3FQCHEHK56X6Qqa6st7dhxjs3G9/filecoin-4_pprof.tar.gz
