### ISSUE TITLE
[bug] `pubKey` field in `createMiner` messages is null

### ISSUE THREAD

**Issue by mslipper** [filecoin-project/go-filecoin#2032]
**Describe the bug**
Take a look at block height 12925, transaction index 5, on the user devnet. You'll see that it's a `createMiner` message with the message params `g0EK9lgiEiCQIEGVW4dOtQy6yuSsBbCCBvtM2Hjrv7z7SqJNAoJsWw==`. When these params are ABI-decoded, the following result pops out:

```
> cbor.decode(Buffer.from('g0EK9lgiEiCQIEGVW4dOtQy6yuSsBbCCBvtM2Hjrv7z7SqJNAoJsWw==', 'base64'))
[ <Buffer 0a>,
  null,
  <Buffer 12 20 90 20 41 95 5b 87 4e b5 0c ba ca e4 ac 05 b0 82 06 fb 4c d8 78 eb bf bc fb 4a a2 4d 02 82 6c 5b> ]
```

The second item of the array is supposed to be the `pubKey` field, but it's null. Is this expected?

**To Reproduce**
1. Run `chain.Ls()` via HTTP to get full JSON responses.
2. Look at the block and transaction index listed above.

**Expected behavior**
The miner's pubkey should never be null - or should it? I'm not sure.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04

**Additional context**
This brought down the stats dashboard. The dashboard now tolerates null pubkeys, but I'd like to get to the bottom of what's happening here.

**Comment by mslipper** [comment]
Any updates all? I'm seeing a _lot_ of null miner addresses in the logs now.

**Comment by shannonwells** [comment]
@mslipper I'm looking at it now - PR #2115  may fix it; I'm currently writing a test to repro the issue.

**Comment by phritz** [comment]
i think this was not reproducible, @mslipper please re open if you are still seeing this
