### ISSUE TITLE
Check connection to miner before proposing storage deal

### ISSUE THREAD

**Issue by anorth** [filecoin-project/go-filecoin#2035]
### Description
Clients require a direct connection to a miner in order to propose a deal. Many asks may be on chain from miners that are no longer active, or just temporarily inaccessible. At present, clients go to all the work of setting up payment channels (on-chain) before discovering that the target miner is inaccessible. `propose-storage-deal` fails with `error sending proposal: context deadline exceeded`.

Clients should test connection to the miner, with a relatively short timeout, before making on-chain operations. Maybe this can be done in parallel with ingesting the file and other sanity checks like it's size.

### Acceptance criteria
- Attempting to propose a deal to an offline miner fails in only a few seconds, with a clear error message
- If a miner goes offline subsequent to the ping, the error message when failing to propose the deal clearly articulates the problem

### Risks + pitfalls
None

### Where to begin
protocol/client/miner.go

**Comment by magik6k** [comment]
https://github.com/filecoin-project/go-filecoin/pull/2216 should address part of this

**Comment by anorth** [comment]
@rkowalick could you evaluate whether this is sufficiently fixed, or maybe needs some error message improvements to bring it home?

**Comment by rkowalick** [comment]
Looking now

**Comment by rkowalick** [comment]
For both Acceptance Criteria cases, I get the following error message:

```
Error: error sending proposal: failed to establish connection with the peer: dial attempt failed:
<peer.ID Qm*osca5L> --> <peer.ID Qm*5jwVEW> dial attempt failed: dial tcp4
127.0.0.1:50593: connect: connection refused
```

I'm not sure if this error message is satisfactory or not. Let me know if want me to change it @anorth

**Comment by anorth** [comment]
Looks good enough to me, thanks!
