### ISSUE TITLE
 cross-compile the arm/arm64 binary

### ISSUE THREAD

**Issue by wyblyf** [filecoin-project/go-filecoin#2037]
### Description
We tried to cross-compile the arm/arm64 environment executable, but encountered a lot of dependencies, can you give me some advice? Do you have an arm/arm64 version development plan?
### Acceptance criteria
arm/arm64 binary
### Risks + pitfalls
none
### Where to begin
Always

**Comment by whyrusleeping** [comment]
@wyblyf could you paste the failures you encountered?

**Comment by wyblyf** [comment]
@[whyrusleeping](/whyrusleeping) The following problems were encountered when compiling file-coin:
![image](https://user-images.githubusercontent.com/6084318/53137298-22c5f300-35bd-11e9-83c1-ac19322c871d.png)
Exported coredump tips: “/usr/bin/qemu-aarch64-static /tmp/go-build825887773/b001/exe/main build”
![image](https://user-images.githubusercontent.com/6084318/53137513-fe1e4b00-35bd-11e9-91c9-c57508ea81d1.png)
But the /tmp/go-build825887773/b001/exe/main file does not exist, I can't execute crash to view more stack information.

And I have the following questions about cross compilation:
1.Does the CC and GCCGO tools need to specify the corresponding platform?
![image](https://user-images.githubusercontent.com/6084318/53137923-923ce200-35bf-11e9-8da4-cdf75eb3bffe.png)
2. Do tools such as rust, rust-proofs, and bls-signatures need to be mapped to the platform?
![image](https://user-images.githubusercontent.com/6084318/53138124-29099e80-35c0-11e9-82b8-4b3c30a493fe.png)

Thanks.

**Comment by whyrusleeping** [comment]
You cannot build go-filecoin without CGO, so setting `CGO_ENABLED=0` will definitely not work.

Are you able to do the build on the arm platform itself? (not cross compiling?)

@phritz is there a way we can build without having to generate all the groth parameters? That seems like an annoying extra step to force in all situations.

**Comment by wyblyf** [comment]
@whyrusleeping I compile with "GOOS=linux GOARCH=arm64 go run ./build/*.go build" and the final result is also a failure.
![image](https://user-images.githubusercontent.com/6084318/53148370-6d5b6580-35e5-11e9-8df2-7835a0e59887.png)


Native compilation is able to success generate executable files normally
![image](https://user-images.githubusercontent.com/6084318/53148424-954ac900-35e5-11e9-903a-fb18364eae9a.png)


Now I am trying to build a build environment on the arm64 platform, I hope I can have a good luck, and I will have feedback in time.

**Comment by dignifiedquire** [comment]
you will need to compile rust-proofs and bls-signatures manually using the appropriate targets. the default commands used build it for the platform you are on.
https://github.com/japaric/rust-cross is a tool I used in the past for doing that

**Comment by wyblyf** [comment]
@dignifiedquire  I put the file-coin project on the arm64 platform to compile. When I executed the "make deps" command to install the dependency package, I encountered a problem:
![image](https://user-images.githubusercontent.com/6084318/53161280-ace57a00-3604-11e9-9af2-8ae3ece75d1b.png)

I think it is caused by the wrong package( x86-64 ) downloaded by scripts/install-rust-proofs.sh
![image](https://user-images.githubusercontent.com/6084318/53161443-f8982380-3604-11e9-9e7d-0ae60c44eafb.png)


So I downloaded the rust-proofs source code and tried to compile, but I can't get target files such as paramcache.
![image](https://user-images.githubusercontent.com/6084318/53162617-5af22380-3607-11e9-84f3-091d379b8d4c.png)

![image](https://user-images.githubusercontent.com/6084318/53162887-ebc8ff00-3607-11e9-8975-2394b0bf8439.png)

How can I compile to get release files?
![image](https://user-images.githubusercontent.com/6084318/53163272-af49d300-3608-11e9-94b9-8ba95bcc572f.png)

**Comment by rosalinekarr** [comment]
@laser, can you help with this?

**Comment by rosalinekarr** [comment]
Hey @wyblyf, we currently do not officially support ARM architectures. Support is in the plan down the road, but I'm afraid we won't be getting to it any time soon.

**Comment by wyblyf** [comment]
@rosalinekarr Already compile the binary, but can't initialize --devnet-user！！
![image](https://user-images.githubusercontent.com/6084318/53219964-229d2480-369d-11e9-8542-becd7322c6d4.png)
![image](https://user-images.githubusercontent.com/6084318/53220095-b3740000-369d-11e9-9470-e72ba6878d05.png)

![image](https://user-images.githubusercontent.com/6084318/53219958-1ca74380-369d-11e9-8655-d49759526992.png)

**Comment by whyrusleeping** [comment]
@wyblyf ah yeah, thats badger not working on arm. We can get around that by using leveldb (or some other datastore) probably. Datastore types are technically configurable: https://github.com/filecoin-project/go-filecoin/blob/master/repo/fsrepo.go#L320 But theres only one type... we would need to add in leveldb or something there.

In addition, it also looks like someone added code to open up two different badger datastores here: https://github.com/filecoin-project/go-filecoin/blob/master/repo/fsrepo.go#L347 This is a bug IMO, and we should just be using one datastore (so its configurable in just one place).

You could probably get things working hackily by modifying the code and changing all the badger references to use leveldb (via this package: https://github.com/ipfs/go-ds-leveldb)

In the meantime, i'll open an issue to make the datastores configurable.

**Comment by wyblyf** [comment]
@whyrusleeping Yes, I agree with you, the badger not working on arm. The following is the comparison test result：
1. In x86-64 environment， test is successful
![image](https://user-images.githubusercontent.com/6084318/53282132-7f1c4480-376e-11e9-8afe-da3eb165f553.png)
2. In arm64 environment， test is failure
![image](https://user-images.githubusercontent.com/6084318/53282216-a58eaf80-376f-11e9-8906-f5c05db059f1.png)
![image](https://user-images.githubusercontent.com/6084318/53282225-762c7280-3770-11e9-9094-86eaab6f15c2.png)

I will follow your suggestion, hackily by modifying the code and changing all the badger references to use leveldb. Thanks for your suggestion.

**Comment by loulancn** [comment]
When is the ARM/ARM64 architecture expected to be supported?

**Comment by wyblyf** [comment]
@whyrusleeping This arm/arm64 version can be run normally using the leveldb storage method. Thank you for your support.
![image](https://user-images.githubusercontent.com/6084318/53319851-bcb7d380-390e-11e9-8c6e-4804c4e6e747.png)

![image](https://user-images.githubusercontent.com/6084318/53319705-3dc29b00-390e-11e9-8fc3-173ae372f9d3.png)
![image](https://user-images.githubusercontent.com/6084318/53319712-47e49980-390e-11e9-9124-f2ed1fd7ff24.png)

**Comment by whyrusleeping** [comment]
@loulancn once issue #2070 is fixed, we should have slightly better arm support. right now, you have to manually patch the code like @wyblyf did.

**Comment by pinkethan** [comment]
@ rosalinekarr where can I get bls-signatures source ? once I compiled rust-proofs and bls-signatures for my target, what should I do fro here to file-coin project?


> you will need to compile rust-proofs and bls-signatures manually using the appropriate targets. the default commands used build it for the platform you are on. https://github.com/japaric/rust-cross is a tool I used in the past for doing that
