### ISSUE TITLE
Question: How do I get Proven Storage?

### ISSUE THREAD

**Issue by Nanofortress** [filecoin-project/go-filecoin#2043]
### Description
I have read the Mining Filecoin and Storing on Filecoin post on the Wiki (Also many other posts) but I could not find anything about "Proven Storage". I saw this term on https://stats.kittyhawk.wtf/storage/mining and it seems like only half of the running nodes has this setup.

I have already created a miner on my node with 10 sectors pledged, and I have created an ask on the storage market. But on the website (https://stats.kittyhawk.wtf/storage/mining) my node still has 0 Proven Storage.
  
My question is how can I get the Proof of Storages (Proof of SpaceTime and Proof of Replications) to prove my storage exist.

**Comment by whyrusleeping** [comment]
You have to actually store data in those pledged sectors, seal it, and then commit it to the chain. This all happens automatically if people contact your miner to store data.

For more details, please take a read through this spec doc: https://github.com/filecoin-project/specs/blob/master/mining.md (and if something seems wrong there, let me know)

**Comment by Nanofortress** [comment]
Got it, thanks!
