### ISSUE TITLE
Provide porcelain and cli command to retrieve default wallet address

### ISSUE THREAD

**Issue by travisperson** [filecoin-project/go-filecoin#2049]
### Description

Currently the only way to retrieve the default wallet address is by using the config. However, this may not be set when it is needed.

https://github.com/filecoin-project/go-filecoin/pull/1864#discussion_r258696860

### Acceptance criteria

- Users should be able to retrieve their default wallet address from the CLI.

**Comment by jaybatra26** [comment]
Is this taken. If not I would like to contribute.

**Comment by GeetikaBatra** [comment]
Can I take this one?

**Comment by waynewyang** [comment]
@travisperson I think I can add  "DefaultWalletAddress" method in [go-filecoin/porcelain/wallet.go](https://github.com/filecoin-project/go-filecoin/blob/master/porcelain/wallet.go), references to  "GetAndMaybeSetDefaultSenderAddress" in [go-filecoin/porcelain/message.go](https://github.com/filecoin-project/go-filecoin/blob/master/porcelain/message.go),
and add the CLI "go-filecoin wallet addrs default", is it feasible?

**Comment by travisperson** [comment]
That seems like a reasonable approach.

**Comment by waynewyang** [comment]
@travisperson ok, thanks,I'll make a PR later.
