### ISSUE TITLE
Add 'dag get' command for messages (or viewable somehow by hash)

### ISSUE THREAD

**Issue by whyrusleeping** [filecoin-project/go-filecoin#2053]
I expect to be able to run `go-filecoin dag get <Message CID>` and have it print me out the message. In addition, a nicely formatted version could be made available via `go-filecoin show message <Message CID>`

**Comment by anorth** [comment]
This sounds the same as https://github.com/filecoin-project/go-filecoin/issues/1933. If not, could you please expand on the difference?

**Comment by whyrusleeping** [comment]
@anorth ah, i guess this issue proposes a solution to that issue. otherwise, yes. addressing the same problem.

**Comment by anorth** [comment]
Great, closing in favour of that since I'm already on it.
