### ISSUE TITLE
CI should run lint before tests

### ISSUE THREAD

**Issue by anorth** [filecoin-project/go-filecoin#2054]
### Description
A full CI run takes 11-12 minutes. Linting takes ~30s but is the last step. It should be the first step so that simple merge-blocking failures can be detected quickly.

This is an especially painful problem given the serial nature of merging PRs enforced by our branch protections. See [issue I will file later about a merge queue].

### Acceptance criteria
- Failing lint fails a CI build within a minute of starting

**Comment by rosalinekarr** [comment]
+10000000000000000000 for this

**Comment by phritz** [comment]
i put this in ready, anyone who is available feel free to pick it up

**Comment by phritz** [comment]
@ognots this would be an easy one for you

**Comment by ognots** [comment]
Closed by https://github.com/filecoin-project/go-filecoin/pull/2094
