### ISSUE TITLE
Automate import ordering and spacing 

### ISSUE THREAD

**Issue by anorth** [filecoin-project/go-filecoin#2056]
### Description
The current [import ordering conventions](https://github.com/filecoin-project/go-filecoin/blob/master/CONTRIBUTING.md#conventions-and-style) cannot be achieved automatically with some tool, although there are tools that can automate other orderings. When engineers use IDEs or other tools with automatic import resolution (a valuable productivity boost), the imports end up out of line with the convention. Some IDEs (GoLand) collapse imports on screen by default because they expect to be automatically managed, so the problem is not even visible to the developer without changing config to require more scrolling around. This leads to additional noise in pull requests for the reviewer, and work for the contributor.

For similar reasons to relying on `gofmt` to define acceptable typographic layout, it would be a nontrivial boost to rely on a tool to arrange imports. A tightly defined conventional layout reduces unnecessary import diffs.

This could be achieved by:
- changing or relaxing our import convention such that existing tools can automate it
- writing a tool that can automate our desired ordering, available as a lint check and IDE file watcher

### Acceptance criteria
- A tool supports import ordering such that authors never need to rearrange imports
    - Ideally, this tool is usable inside widely-used IDEs
- Reviewers never comment on bad import ordering if the contributor uses available tools

### Risks + pitfalls
- Relaxing conventions may lead to aesthetically displeasing import statements.

### Where to begin
`gofmt -s` and `goimports` define some constraints on import ordering, but not nearly as tight as our conventions. 

Discussion.

**Comment by rosalinekarr** [comment]
I think @rkowalick might tell you to use GoLand for this, but I agree we should have something more universal to help with this. I refuse to give up my dumb editor.

**Comment by anorth** [comment]
I do use GoLand. It can't enforce the conventions we have chosen. Relaxing the conventions to match what GoLand can do (possibly via `gofmt` or `goimports` file watches) is a possible resolution.

**Comment by rkowalick** [comment]
Yeah, goland gets kind of close to what we do, but not quite. I would be in favor of either of

> * changing or relaxing our import convention such that existing tools can automate it
> * writing a tool that can automate our desired ordering, available as a lint check and IDE file watcher

**Comment by anorth** [comment]
This got better with the removal of `gx` since now there are fewer categories and we're using canonical Go patterns. I'm going to close this for now.
