### ISSUE TITLE
can't build master with USE_PRECOMPILED_RUST_PROOFS after filecoin-proofs repo rename [bug]

### ISSUE THREAD

**Issue by gmasgras** [filecoin-project/go-filecoin#2062]
**Describe the bug**
Master builds are currently broken. It looks like the script `/scripts/install-rust-proofs.sh` exits with 1 due not being able to find a release when `USE_PRECOMPILED_RUST_PROOFS` is set to TRUE

**To Reproduce**
1. Merge something to `master`

**Expected behavior**
Should build

**Screenshots**
If applicable, add logging output or screenshots to help explain your problem.

**Additional context**
Error:
```
release 12bc40ba164a66cc does not exist, GitHub said {
  "message": "Moved Permanently",
  "url": "https://api.github.com/repositories/135468185/releases/tags/12bc40ba164a66cc",
  "documentation_url": "https://developer.github.com/v3/#http-redirects"
}
ensure your access token has full repo scope
```

failed build: https://circleci.com/gh/filecoin-project/go-filecoin/11329

**Comment by mishmosh** [comment]
IIUC this is fixed now. @gmasgras please re-open if false.
