### ISSUE TITLE
Datastore type should be configurable

### ISSUE THREAD

**Issue by whyrusleeping** [filecoin-project/go-filecoin#2070]
The type of datastore we use should be configurable, we started out making this somewhat possible (we check the datastore type when opening the datastore), so technically all we should have to do is add another option there for something like leveldb (since badger doesnt work everywhere).

The complicating factor is these dealdatastore and chaindatastore things that are separate for some reason, and are hardcoded to be badger. Those should be removed as separate datastores, and instead just use a namespace into the main one.

Fixing this should unblock: https://github.com/filecoin-project/go-filecoin/issues/2037

**Comment by rosalinekarr** [comment]
@whyrusleeping Are you sure this is a bug? This seems like a feature request.

**Comment by whyrusleeping** [comment]
Given that it was partially configurable (there is a config option) that
would normally work, I would call the existence of the other incorrect
datastore loading code a bug.

**Comment by rosalinekarr** [comment]
@whyrusleeping This is still something that isn't broken at the moment. I agree that it's something we need to do, but bugs are issues which specifically break existing functionality and take priority over other tasks.

At @mishmosh and @phritz's suggestion, I'm relabelling as technical debt.

**Comment by anorth** [comment]
cc @shannonwells this may be relevant for repo migration work #2470

**Comment by ZenGround0** [comment]
@anorth @whyrusleeping I think we need to align on whether this is a product requirement for testnet.  It looks like there are different assumptions around this at the moment and this feature has the potential to spin up a bunch of unaccounted for work.

**Comment by anorth** [comment]
This seems to me like something we could work on during testnet. We will be spending some efforts on scalable miner architecture then and this could fit in well. I don't think we have enough information right now (from users/miners) to motivate work that we are sure is in the right direction.

I don't immediately agree with the assertion that all the datastores should be rolled into one; flexibility for using domain-appropriate stores for different data types may be required. But resolving that requires more miner/architecture research.

We should work to ensure that our repo migration implementation does not get in the way of this later.
