### ISSUE TITLE
CircleCI Testing Concurrency

### ISSUE THREAD

**Issue by ognots** [filecoin-project/go-filecoin#2077]
### Description

The overall goal of this story is to reduce build time for jobs `build_linux` and `build_macos`, with `build_linux` being the priority as it runs as the primary test - part of `test_all` workflow

In `build_linux`, split out `Test` and `Functional Test` in to separate jobs and run them concurrently using workflows. They currently run serially in the same job stanza.

In `build_macos`, search for any additional efficiencies to reduce build time

Relates to https://github.com/filecoin-project/go-filecoin/issues/2057

### Acceptance criteria

`build_linux` and `build_macos` completes faster while providing same level of test quality

### Risks + pitfalls

The time required to load assets from workspace and cache may negate time savings by parallel Test job runs

### Where to begin

`.circleci/config`

**Comment by dignifiedquire** [comment]
I tried to make this happen before: https://github.com/filecoin-project/go-filecoin/blob/chore/circle-pipeline/.circleci/config.yml but failed, even talked a bunch to their customer support, though they stopped responding eventually :( The issue was that the installations and caches where never properly shared between builds and pipeline steps

**Comment by anorth** [comment]
Note that we would require all the checks to be part of the branch protections that guard merging PRs. If it's difficult to gate on multiple CI workflows, that could make splitting them too hard.

I believe the `build_linux` workflow should be exactly what we want to run on prospective PRs – there are already other workflows run less frequently for very slow-running jobs (and see #1976).

**Comment by ognots** [comment]
This is the workflow I'm envisioning:

```
+--------------------+   +--------------+    +---------------------+
|                    |   |              |    |                     |
|install dependencies+-->+run unit tests| +> |run integration tests|
|                    |   |              | |  |                     |
+--------------------+   +--------------+ |  +---------------------+
                                |---------+
                         +--------------+ |  +---------------------+
                         |              | |  |                     |
                         |   run build  | +> | run functional tests|
                         |              |    |                     |
                         +--------------+    +---------------------+

```

**Comment by mishmosh** [comment]
moving to backlog for now
