### ISSUE TITLE
install-rust-fil-proofs.sh fallback-to-local-build behavior is broken

### ISSUE THREAD

**Issue by laser** [filecoin-project/go-filecoin#2083]
### Description

A [recently merged PR](https://github.com/filecoin-project/go-filecoin/pull/2006) added a `set -e` to the top of the `install-rust-fil-proofs.sh` script, which breaks the status code-checking fallback behavior at the end of the script.

If a user has set the `FILECOIN_USE_PRECOMPILED_RUST_PROOFS` to `true` but there does not exist a GitHub release for the submodule SHA, the build will fail instead of falling back to a local build.

An example of such a failure [can be seen here](https://circleci.com/gh/filecoin-project/go-filecoin/11393).

**Comment by schomatis** [comment]
:sweat_smile:
