### ISSUE TITLE
Auto trading instead of manual one

### ISSUE THREAD

**Issue by Byte-Doctor** [filecoin-project/go-filecoin#2087]
### Description
FileCoin is designed for one by one trading between storage customer and miner. If there are millions miners, it is impossible for a customer to compare and make deal with all of them. Automatically trading is the best solution.

### Acceptance criteria
System is able to find best miner for a specific customer, and makes deal automatically. The result is same or better than manual trading.

### Risks + pitfalls
Customer may complain that the system choose a wrong miner.

### Where to begin
Redesign the whole storage trading market

**Comment by ZenGround0** [comment]
As long as asks remain on chain (question, is this the case long term?) then this seems like a straightforward addition to the storage client.  There could be a `go-filecoin client best-ask` command that looks through the ask table and outputs the best ask for a user's price, size and duration criteria.  There could also be a `go-filecoin client propose-best` that does a `propose-deal` on the output of `best-ask`.

@Byte-Doctor is this along the lines of what you have in mind?
