### ISSUE TITLE
devnet deploys failed due to missing genesis files and bootstrap keyFiles

### ISSUE THREAD

**Issue by gmasgras** [filecoin-project/go-filecoin#2101]
### Description
The files `genesis.car`,  `gen.json`, `setup.json`, `keyFile0..4` are required by the devnet startup script, however they have not been included in the `latest` docker images.
### Acceptance criteria
A devnet comes up correctly

**Comment by anorth** [comment]
@ognots is this now redundant?

**Comment by ognots** [comment]
Fixed
