### ISSUE TITLE
Migrate CircleCI config to 2.1

### ISSUE THREAD

**Issue by ognots** [filecoin-project/go-filecoin#2107]
### Description

Migrate CircleCI config to 2.1 configuration, in order to take advantage of new reusable configuration features leading to DRYer, more flexible configuration.

Also allows use of parameters in job definitions, which will help unblock https://github.com/filecoin-project/go-filecoin/pull/2096

### Acceptance criteria

All CircleCI workflows should pass and behave exactly the same as current configuration

### Risks + pitfalls

None

**Comment by anorth** [comment]
@ognots please close if done or let us know what remains.

**Comment by ognots** [comment]
Done
