### ISSUE TITLE
should we move nightly to use large sectors?

### ISSUE THREAD

**Issue by phritz** [filecoin-project/go-filecoin#2110]
currently nightly uses small sectors so sealing happens in a minute or so as opposed to tens of minutes with large sectors. small sector is roughly 1kb whereas large is roughly 256 megs. the reason we use small sectors for the nightly is to make it quick to use by developers. the downside is that its behavior is not identical to the user devnet which uses large sectors. there is the possibility that a problem could be introduced eg wrt proofs performance and using small sectors would hide it in the nightly. we'd then be faced with a nasty surprise when we went to roll out the user devnet weeks later. 

this issue is to discuss whether we judge that risk to be sufficient enough that we should use large sectors in the nightly to mitigate it. we could have two nightlies one with each setting, but that seems complicated. or we could keep small sectors in nightly and put it on devs to ensure risky changes like updates to the proofs submodule are properly integrated. we are going to require devs do this anyway, and make self-service devnets easy for everyone to use, but i was thinking that having large sectors in the nightly would be a further backstop. 

and yes, we should have some kind of performance regression suite, both at the proofs level and at the gfc level to catch performance regressions. infra is talking about this soon.

we can still use small sectors locally when testing

**Comment by acruikshank** [comment]
My only argument against using large sectors is that we might need to make a quick turnaround change that needs to be tested against a real cluster. With the recent work to FAST, these type of changes can be tested against an ad hoc network. I don't have any good reason we shouldn't switch to large sectors.

**Comment by mishmosh** [comment]
We'll want this in the future, and I'm personally inclined to rip the band-aid off now.

This will also make nightly harder to debug and slower to deploy. @filecoin-project/infra can someone weigh in on if anything can/should be done to mitigate that, and whether this is the right time to make the switch?

**Comment by laser** [comment]
Given how hard it is to transfer a large sector-sized piece from retrieval miner to retrieval client (existing retrieval protocol doesn't handle network connectivity issues very well - @travisperson and I experienced a few issues when testing in the usernet during the last release), making not-small sectors the default will result in some pain.

That said, that pain may result in us rewriting the existing retrieval protocol - which would be a good thing for people wishing to serve and retrieve files using Filecoin.

**Comment by travisperson** [comment]
> there is the possibility that a problem could be introduced eg wrt proofs performance and using small sectors would hide it in the nightly. we'd then be faced with a nasty surprise when we went to roll out the user devnet weeks later.

Has this happened yet, or are we just speculating? I know @frrist was looking into something last week with regard to block processing that might be related.

I think moving to large sectors would work right now, but I'd be worried that it won't be realistic as we move to more real world parameters. I've heard numbers thrown around on the order of hours for proving times that may come along. Maybe @laser and @porcuquine can provide some insight on the targeted numbers we are looking to move towards in the coming months.

**Comment by porcuquine** [comment]
Yes — there will eventually be sectors that probably do not fit the characteristics you want for nightly. That said, there will also be multiple sector sizes, and that mechanism could be used to provide a smaller sector. How much proofs themselves would need to be hobbled would depend on timing requirements.

**Comment by phritz** [comment]
There is sufficient risk in having nightly not look like test that we should do this. That is, we should not use small sectors in the nightly and once we change nightly to large sectors we should remove instructions in the wiki that say to set small sectors for the nightly.

**Comment by anorth** [comment]
Who will own this issue. @gmasgras?

**Comment by gmasgras** [comment]
👍 assigned myself
