### ISSUE TITLE
Unable to get test TOKEN

### ISSUE THREAD

**Issue by pengxiankaikai** [filecoin-project/go-filecoin#2111]
**Describe the bug**
Unable to get test TOKEN，The address I submitted is : fcq6t2s706mjsp5lwpf6pzq4sjhgn6n6qv2nr3rjk
http://user.kittyhawk.wtf:9797/tap return result:
Success! Message CID: zDPWYqFD7zqaPvnfmYy2Zr6xnwXrF4QLusdbmCnBTbyFjKJFBtrz

I have been waiting for more than 24 hours
thanks!

**Comment by windstore** [comment]
I had the same problem，how to get token?
