### ISSUE TITLE
when mining, use a real delay function when generating and verifying blocks

### ISSUE THREAD

**Issue by laser** [filecoin-project/go-filecoin#2119]
### Description

For background, see the comments in [this story](https://github.com/filecoin-project/go-filecoin/issues/1791). 

Today, generating a block calls in to some fake PoSt-creation code (emphasis on _fake_) to prevent miners from mining blocks too fast. It is not our intent to use the current PoSt construction to prevent miners from mining blocks too fast. Instead, we need some other delay function (blocked on Research).

### Acceptance criteria

- learn from Research which delay function we should be using
- figure out where to write the delay function (rust-fil-proofs? go-filecoin?)
- integrate block generation with the to-be-developed proof-generator
- integrate block verification with the to-be-developed proof-verifier

### Risks + pitfalls

- Research hasn't figured out which delay function to use

**Comment by laser** [comment]
As per @ZenGround0, this work is [blocked](https://github.com/filecoin-project/go-filecoin/issues/1791#issuecomment-460399480) until the research team specifically acks to a particular delay function.

**Comment by laser** [comment]
FYI, @shannonwells

**Comment by ZenGround0** [comment]
@nicola @sternhenri @bvo @whyrusleeping 

can we haz VDF?

**Comment by sternhenri** [comment]
There are two strong opinions I know of on this topic. It may be time to have that conversation again.

**Comment by anorth** [comment]
The October 2019 spec dispenses with VDF.
