### ISSUE TITLE
Remove all mention of PoSt in the consensus block mining code

### ISSUE THREAD

**Issue by laser** [filecoin-project/go-filecoin#2122]
### Description

There are a few places where we refer to PoSt in the mining code:

1. The `types.Block` struct has a `Proof` field whose type is very PoSt-specific ([here](https://github.com/filecoin-project/go-filecoin/blob/414464d5f086d35fcdcdfb1a7a46e50fbe0e28c6/types/block.go#L54)].
1. The `Expected#validateMining` method attempts to use PoSt tooling to verify a block's proof ([here](https://github.com/filecoin-project/go-filecoin/blob/414464d5f086d35fcdcdfb1a7a46e50fbe0e28c6/consensus/expected.go#L286))
1. The `DefaultWorker` has a `createPoSTFunc` field ([here](https://github.com/filecoin-project/go-filecoin/blob/fb4130d7115ccffaad2a8597eec75031b3e8c71b/mining/worker.go#L78))

There are a few more examples of this.

**Comment by mishmosh** [comment]
PoST will still be in storage mining. PoST will not be in block mining.

**Comment by anorth** [comment]
@ZenGround0 is this relevant to your current consensus implementation work?

**Comment by ZenGround0** [comment]
It's taken care of by other issues and I'll close it when its no longer an issue.

**Comment by anorth** [comment]
Done
