### ISSUE TITLE
messages with invalid sigs should never go on chain

### ISSUE THREAD

**Issue by phritz** [filecoin-project/go-filecoin#2124]
https://github.com/filecoin-project/go-filecoin/blob/f5918bda9e76f61200763c44cdb1dadb19bb4a61/consensus/processor.go#L447

seems like if there is an invalid sig we should consider the message unapplyable. it should never even attempt application. this should be caught earlier it seems like and the message should definitely not go on chain.

**Comment by rkowalick** [comment]
So the `Validate` call that performs signature verification is called in two places:

1. `sender.Send`
2. `attemptApplyMessage`

`sender.Send` is called when a miner sends a message out to the block chain, so it currently prevent any filecoin node (with our code) from sending out a message with an invalid signature.

`attemptApplyMessage` is called by `ApplyMessagesAndPayRewards`, which is called in three places:

1. in `DefaultWorker.Generate` when collating messages into a block during mining, so a message with an invalid signature will not be included in a block by a miner running our code.


`attemptApplyMessage` is also called when validating the messages in a block that is received over the network, so any filecoin node running our code will mark a block as invalid if it contains a message with an invalid signature.

**Comment by phritz** [comment]
i was looking at generate. it seems like although errinvalidsignature is a revert error, it is mapped to a permanent failure: https://github.com/filecoin-project/go-filecoin/blob/f5918bda9e76f61200763c44cdb1dadb19bb4a61/consensus/processor.go#L664, which i think does the right thing. so maybe this is wai and the line i included above is just scary looking. maybe worth a test that an invalid signature ends up in the permanent failures if there isn't one. 

man i would love to clean this code up, eg to have a set of return types permanent failure, temp failure, fault, success, and success but revert state and make this simpler.

**Comment by rkowalick** [comment]
I feel like even a permanent failures test won't necessary elucidate the situation. A recent PR of @anorth's added an extra check for negative value transfer and gas limit for a message above block limit: https://github.com/filecoin-project/go-filecoin/pull/2233. Both of those conditions were already producing permanent errors, he just added them into `sender.Send` so a miner wouldn't even attempt to broadcast them to the network.

I would agree that a clear list of rules in code that need to be applied during the situations I have outlined above and a very obvious application of those rules in all of those cases would make understanding this stuff much simpler.

**Comment by rkowalick** [comment]
I think the take aways that make sense to me are:
1. Ensure all errors that can be thrown by `validate` are permanent errors.
1. When one creates a message-level consensus rule that should be run in all of the 4 cases above, it should go in `validate`, since that is in the code path of all of the above cases
1. Communicate the idea that validate is "the place" for rules that are important.

**Comment by anorth** [comment]
I don't think 1. is possible directly: current callers of validate need it to check for temporary errors. It may be if validation is split into permanent and temporary streams, or a composite validation result is returned. @acruikshank has related work in #2256 - please sync up.

**Comment by rkowalick** [comment]
Conversations with @acruikshank have led us to believe this card is not really actionable. Improvements are being made to make it more clear how validation occurs in various parts of the filecoin node, as referenced by @anorth above.

@acruikshank, you are welcome to add more context to this.
