### ISSUE TITLE
Design Outgoing Message Queue

### ISSUE THREAD

**Issue by acruikshank** [filecoin-project/go-filecoin#2132]
### Description

As part of rethinking the message queue (#1936) and messages V2, we've decided we need a new queue to track outgoing messages.

This will fit within a broader set of messaging improvements described in https://docs.google.com/document/d/1n224bJItvu44hd-WVd69gfNbzC-5XUu-HpOfUCcpgEc.

This queue should allow us to:

1. Set message nonces without querying the message pool.
1. Inspect message status.
1. Manage send failures.

### Acceptance criteria

1. A design doc is written that describes the problem, the design goals, an implementation of an outgoing message queue, and alternatives.
2. That document is shared with the community and feedback is explicitly solicited from Filecoin team members with messaging experience.
3. Issues are written based on the document and its feedback to implement the queue. Those issues will be listed in the Messages v2 epic.

**Comment by anorth** [comment]
Design doc ready for review: https://docs.google.com/document/d/1MO6MloDs1plJsBb8pLKYILJQPbmO9Hy8hdrGCCno6UI/edit#

**Comment by anorth** [comment]
Moving on to implementation now.
