### ISSUE TITLE
获取fil币之后，查看余额，一直为0

### ISSUE THREAD

**Issue by muronglaowang** [filecoin-project/go-filecoin#2137]

**Comment by pengxiankaikai** [comment]
@muronglaowang Confirm if your node data is synchronized!

**Comment by muronglaowang** [comment]
> @muronglaowang确认您的节点数据是否已同步！

@pengxiankaikai 怎么确认呢？求指导

**Comment by sandjj** [comment]
go-filecoin show block `go-filecoin chain head |jq -r ' .[0]. "/"'`

**Comment by sandjj** [comment]
go-filecoin show block `go-filecoin chain head |jq -r ' .[0]. "/"'`
查看获取的 Height 与 https://stats.kittyhawk.wtf/storage/mining 中的已经一致，否则一致等到一致才能获取余额

**Comment by moyid** [comment]
以上的回答满意吗？余额还是0吗？

**Comment by muronglaowang** [comment]
@sandjj 否则一直等到一致才能获获取余额，是得到Height值，然后等待https://stats.kittyhawk.wtf/storage/mining这个图表上面出现这样的Height值？

**Comment by muronglaowang** [comment]
> 以上的回答满意吗？余额还是0吗？

还未解决

**Comment by muronglaowang** [comment]
@moyid 还未解决，
还在解决

**Comment by moyid** [comment]
你运行sandjj的命令后得到什么？

**Comment by diwufeiwen** [comment]
我也一样,之前的出问题重新生成.filecoin后就不行了,swarm peers很多节点,但是https://stats.kittyhawk.wtf/storage/mining查不到.

**Comment by muronglaowang** [comment]
@moyid 
有得到一个height值

**Comment by moyid** [comment]
在构建之前请运行：`git checkout 6914061`， 从user net代码构建

**Comment by diwufeiwen** [comment]
@moyid 按你说的编译错误为啥?
error: could not find `Cargo.toml` in `/root/go/src/github.com/filecoin-project/go-filecoin/proofs/rust-proofs` or any parent directory
error: could not find `Cargo.toml` in `/root/go/src/github.com/filecoin-project/go-filecoin/proofs/rust-proofs` or any parent directory

**Comment by muronglaowang** [comment]
@diwufeiwen 在构建之前请运行：git checkout 6914061，从用户net代码构建    这个怎么执行呢？
