### ISSUE TITLE
定存储协议中的data的那一串字符是怎么得到的？

### ISSUE THREAD

**Issue by muronglaowang** [filecoin-project/go-filecoin#2141]
### Description
How do you get the string of characters in the Protocol?

**Comment by Nanofortress** [comment]
You need to import the data first before you propose a storage deal, it can be done as follows.
First import the data, and export it to a variable:
```export CID=`go-filecoin client import ./hello.txt` ```
Then run the command to propose the deal put the $CID into <data>:
```# go-filecoin client propose-storage-deal <miner> <data> <ask> <duration>```
```go-filecoin client propose-storage-deal <miner> $CID <ask> <duration>```

**Comment by shannonwells** [comment]
对于这些类型的问题，我们还有一个[Filecoin论坛](https://discuss.filecoin.io)。
For these types of questions, we also have the [Filecoin forum](https://discuss.filecoin.io).
