### ISSUE TITLE
set-ask does not properly authorize sender?

### ISSUE THREAD

**Issue by phritz** [filecoin-project/go-filecoin#2142]
report from @contrun in slack:
---
Hi, team. While playing with filecoin, I find I can set bogus miner address in the go-filecoin miner set-price command.

A malicious part can spam ask-list (albeit with some gas) with bogus miner list and harass innocent miners. Is this an intended behavior or a potential bug?

**Comment by rkowalick** [comment]
It seems like it is no longer the case that one can send unauthorized set-price commands

1. In the case that I try to make an ask for a miner whose owner is not the `message.From`, I get the error

    ```
        Error: not authorized to call the method
    ```

1. In the case where I use a nonsense address, I get

    ```
        Error: miner must be an address: invalid address checksum
    ```

If there are other cases I missed, please reopen, but I'm going to close this for now.
