### ISSUE TITLE
create script to automatically dump pprof state when CPU is pegged on devnet

### ISSUE THREAD

**Issue by gmasgras** [filecoin-project/go-filecoin#2144]
### Description
We're seeing CPU spikes and possible MEM leaks on usernet. It would be very helpful to get pprof snapshots generated when spikes happen. 
### Acceptance criteria
heap, stack and cpu profiles are saved to disk.

**Comment by anorth** [comment]
I'm closing this, and trust that it or something like it will be re-opened when the need is again present.
