### ISSUE TITLE
Rearrange packages under a few top-level directories

### ISSUE THREAD

**Issue by anorth** [filecoin-project/go-filecoin#2148]
### Description
We have a lot of top-level packages, which obscures relationships and desired dependencies between them. With a few exceptions, the top-level is usually the only place where a new package makes sense.

@phritz suggested re-arranging code under a smaller set of top-level directories in https://github.com/filecoin-project/go-filecoin/pull/2092#issuecomment-467308115. His off-the-cuff suggestion was:
```core/
plumbing/
porcelain/
protocols/
tools/
```

This will also be an opportunity to establish clearer design around package dependencies. Some undesirable relationships will be made clear by the re-org. E.g. we may wish to declare that packages under `core` cannot depend on `plumbing`, `porcelain` or `protocols`, and nothing else should depend on `tools`. (Fixing any violations is outside the scope of this issue)

It's likely that unexpected relationships will emerge while attempting this reorganisation. Work should start with a rough proposal so we can align on the goals, but implementation is likely to be iterative and end up with something slightly different than we expected at the outset.

### Acceptance criteria
- Most Go packages are nested under a top-level directory, of which there are substantially fewer than there are packages
- Desired dependency relationships between the top-level directories are clear and documented

### Risks + pitfalls
- Package relationships are probably pretty messy at the moment
- Moving code that people are editing will cause merge conflict pain
- Risk of trying to achieve too good a result will suck a lot of time

### Where to begin
Identifying `core` components  and more `protocols` is probably a good place to start.

**Comment by phritz** [comment]
note aiui now cmd/ is more idiomatic than tools/

**Comment by anorth** [comment]
@icorderi did great work here, moving us towards a more standard Go package layout. There's more to do, but we don't need an issue to motivate it.
