### ISSUE TITLE
运行go-filecoin swarm peers  Error: unable to convert API endpoint address /  to a multiaddr: no protocol with name 

### ISSUE THREAD

**Issue by muronglaowang** [filecoin-project/go-filecoin#2150]

**Comment by shannonwells** [comment]
能否请您提供以下信息：
* 你是如何初始化go-filecoin的？
* 您使用的go-filecoin的“SHA”（git commit）是什么？
* 最后50行左右的输出
* 你的操作系统是什么？

Can you please provide the following information:
* How did you initialize go-filecoin?
* What is the "SHA" (git commit) of go-filecoin you are using?
* The last 50 lines of output or so
* What is your OS?
