### ISSUE TITLE
Checking for reorgs is inefficient

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/go-filecoin#2151]
### Description
In the upcoming log-reorgs PR #2131 we introduce a check for chain reorgs that naively gathers all ancestors of a new chain.  This is done at the suggestion of Review comments to improve the clarity of the design.  However this does not scale and should be rethought in a way that doesn't degrade the design too much.

### Acceptance criteria
We still log reorganization events that users would care about
We do this in a way that scales better than linearly with chain length
Design does not degrade

Probably the way to do this is to define a constant number of tipsets, if we see a new chain with more than this number of tipsets extended off the current head we count this chain as a reorg.  Choosing this parameter may have something to do with determining the finality parameter of the chain.

**Comment by frrist** [comment]
@ZenGround0 does https://github.com/filecoin-project/go-filecoin/pull/2833 resolve this? If so feel free to close.
