### ISSUE TITLE
How to connect to go-filecoin network

### ISSUE THREAD

**Issue by woshihanhaoniao** [filecoin-project/go-filecoin#2153]
I want to show multiple machines in a blue circle. What should I do?

So the blue circle looks big and cool.

It's like this there are many boots in the list of boot circles.

**Comment by rkowalick** [comment]
@woshihanhaoniao ,

Thanks for the interest in your project. I'm not quite sure what you are asking. Could you try rephrasing your question so we can help?

**Comment by moyid** [comment]
如果更方便的话，可以直接说中文 ^_^

**Comment by anorth** [comment]
If the circle size is proportional to number of nodes, you'll need to create many mining nodes with different heartbeat names. @mslipper but perhaps we should size the circles with storage capacity instead?

**Comment by mslipper** [comment]
Yes, I can size the circles using storage capacity. They're sized proportionally to the number of nodes right now between a hardcoded min and max radius.

**Comment by anorth** [comment]
Thanks @mslipper I'll leave that to your discretion on the dashboard repo.

**Comment by ElecRoastChicken** [comment]
i guess this issue refers to the size of node shows on the globle map
exp, a circle shows there are several nodes with same name running in one certain location, lets say "X" opened 5 nodes in same location (display on map only 1 circle), so the size for that particular circle should be bigger than others
which indicates "X" has stronger strength than others.......
 
if i m not wrong~~ should be like this, am i right? @woshihanhaoniao
