### ISSUE TITLE
[bug] Create a miner faild but also deducted the balance

### ISSUE THREAD

**Issue by yangjian102621** [filecoin-project/go-filecoin#2154]
**Describe the bug**
I try to create a miner for dev-net by the command: 

`go-filecoin miner create 10 100 --price=0 --limit=1000 --peerid `go-filecoin id | jq -r '.ID'``

Since i have not finish synchronizing all the blocks, so it created faild. 
However it deducted my balance.

After i having complete the sync, i did it again, and it blocked for about 2 minute, so i kill the process by pressing [ctrl + C]. when i get the balance, It has been reduced again.

It was not until the third time I created the miner that it was successful.

![image](https://user-images.githubusercontent.com/4746061/53676277-f2780600-3cda-11e9-8a0c-ab6be10c85c0.png)

But now my balance is only 700.

So, is it necessary to deduct the balance every time i run the creating miner command, whether it is created successfully?

**Comment by yangjian102621** [comment]
My wallet address: fcqh2znmcdn3mprny3kz8v0tytkvxccyt9m7c3dfe
Minner address: fcqdzp28x8vnph7aedzw3pwlpwrnxjh77zayx75c5

**Comment by rkowalick** [comment]
@yangjian102621 ,

Deducting the balance for a miner create that fails because you're chain hasn't synced completely definitely seems like a bug. We will look into this when we get a chance.

**Comment by yangjian102621** [comment]
@rkowalick ，

Thanks for your reply.

It seems that it is not because my chain hasn't synced completely . In fact, my Filecoin daemon is always 
 runing and syncing, and i can get the latest block through the client commond.

But it  did not refunds so far,  it's been three days, and my chain data has grown from 1.1GB to 1.7 GB

![image](https://user-images.githubusercontent.com/4746061/53775877-087e0480-3f2f-11e9-99a3-2ee9bbea4c12.png)

**Comment by rkowalick** [comment]
I think the most likely thing that happened was that you ended up making three different miners.

If you search output of `chain ls --enc=json` for your wallet address, you may find 3 different `createMiner` messages, each of which would have created a different miner, each with 100FIL in collateral transferred from your wallet address.

**Comment by yangjian102621** [comment]
@rkowalick  

Oh, thanks i got it. and is there any convenient api to find all miners that i had created?

**Comment by rkowalick** [comment]
I'm looking into an easy way to do this right now.

**Comment by rkowalick** [comment]
It's not ergonomic in any way, but here is _a_ way to do it.

Each line of output of `chain ls --enc=json` is an array of blocks, representing a tipset. Typically, there will only be one block in the array. This block contains two fields that we care about: `messages` and `messageReceipts`.

Using your address in the user devnet, we find one of your `createMiner` message in the `messages` part of the block:

```
{
   "meteredMessage" : {
      "gasLimit" : "6Ac=",
      "gasPrice" : "0",
      "message" : {
         "params" : "g0EKWEEEvVfEq4LuyBWUg5peecr2BVERgX02dAyxXU87jt7WA1P9VC0mZuR7cRWIilM5gkeDR1cdw7N3rZX3JT8ipfw4VlgiEiAXIDs9wdKejKxbzuLaXmj+jaMwhS1w7OpNagwKHAZwGA==",
         "value" : "100",
         "to" : "fcqafmqgvzkzpvc6wjxecm7gsweuawjv8t6falk6r",
         "nonce" : "Ag==",
         "method" : "createMiner",
         "from" : "fcqh2znmcdn3mprny3kz8v0tytkvxccyt9m7c3dfe" < --- Your Wallet Address
      }
   },
   "signature" : "R3qkJHyqC+J6s3g5tPrskKK7LUM6chwCrllw1fqK+pRGeB8Xa2eDpbP6OxI+xxLQcE/KiNiloSG5qAA+kSG5xQA="
}
```

In my `chain ls` output, it is the 6th entry in the `messages` array (note that this ordering is not consistent across different executions of `chain ls`). We go to the `messageReceipts` array in the block and look for the 6th entry:

```
{
   "gasAttoFIL" : "0",
   "return" : [
      "AABogqOY7Jhv7uWidELvhcOZpX94XQ=="
   ],
   "exitCode" : 0
}
```

That `return` entry is the address of the miner created from the message. In order to decode it to a base32 encoded address, you need to run the go code

```go
package main

import (
	encoding/base64"
	"fmt"
	"gx/ipfs/QmR8BauakNcBa3RbE4nbQu76PDiJgoQgz8AJdhJuiU4TAw/go-cid"
	"github.com/filecoin-project/go-filecoin/address"
)

func main() {
	aBytes, _ := base64.StdEncoding.DecodeString("AACbDn0JxxLKuBJ1v6iq6qX+b0iOkw==")

	addr, _ := address.NewFromBytes(aBytes)

	fmt.Println(addr.String())
}
```

Doing this for all of your miner create messages will give you the addresses of all of the miners you've created.

Sorry this is kind of involved. Feel free to make an issue asking for a feature that makes this easier to do!

**Comment by yangjian102621** [comment]
@rkowalick 
Thanks so much. i also find a quick method to find all miners that i had created.

First, run the script below

```bash
go-filecoin chain ls --enc=json |grep '"from":"fcqh2znmcdn3mprny3kz8v0tytkvxccyt9m7c3dfe","nonce":"[A-Z]\{2\}==","value":"100","method":"createMiner"'
```
Then you can get the blocks that contain messages for creating your miner. In fact i got two records.

![image](https://user-images.githubusercontent.com/4746061/54006194-3cf3f980-4197-11e9-9a51-0e30d785b338.png)

I parsed the JSON data and found the `message` and `messageReceipts` fields.

```javascript
{
    "messages":[
        {
            "meteredMessage":{
                "message":{
                    "to":"fcqafmqgvzkzpvc6wjxecm7gsweuawjv8t6falk6r",
                    "from":"fcqh2znmcdn3mprny3kz8v0tytkvxccyt9m7c3dfe",
                    "nonce":"AA==",
                    "value":"100",
                    "method":"createMiner",
                    "params":"g0EKWEEEvVfEq4LuyBWUg5peecr2BVERgX02dAyxXU87jt7WA1P9VC0mZuR7cRWIilM5gkeDR1cdw7N3rZX3JT8ipfw4VlgiEiAXIDs9wdKejKxbzuLaXmj+jaMwhS1w7OpNagwKHAZwGA=="
                },
                "gasPrice":"0",
                "gasLimit":"6Ac="
            },
            "signature":"0lbMOt9zCbpqrQvxLbihXeLmEq6eD3e8P21M+r22LapXH+3enTfqY1S334Y18IWyvTyBBbiPxqK9EzpXbnYStgE="
        },
        {
            "meteredMessage":{
                "message":{
                    "to":"fcqp606qfk5gwmq6ac24g4mhv3cr8zzf67vqkpulh",
                    "from":"fcqacdn2pyprjrj4z5vtudny26whal8v40x57ec9q",
                    "nonce":"zgE=",
                    "value":"0",
                    "method":"createChannel",
                    "params":"glYAACSEHT7ZE6RnrkFSkunU04G4e0I+Q9OCAg=="
                },
                "gasPrice":"0",
                "gasLimit":"rAI="
            },
            "signature":"g449eqvNG0HcXs5ej4WvrkzapFfTZ8AIGbZ5RpCNo7w0zEZbwaDjMJeqC9LoHDzmVd+I5DimF020pkFlks8HdgE="
        },
        {
            "meteredMessage":{
                "message":{
                    "to":"fcql6lhlunr085efumzfczpcqr9uj0t4t3msr2y4x",
                    "from":"fcqtv3f7s9xunxjxm7mmvpdeau8a8v70mwez4zs7t",
                    "nonce":"Ag==",
                    "value":null,
                    "method":"commitSector",
                    "params":"hUEBWCCdsAKUeIn6zJRTTSYqTNCnrUPAd4rzbHdJlNzH39ntPlggUFfpfFR1R6wwUjbap129VrRlPS9lDe0WLunESetbqD1YII/JYlxQ6j23OqTec9sks+75DZTl6AgrGG9AeFeW0HcVWQGAtoe2E+f9Ivt5q2Lo8LOiwDU63vdKT+L+uODSacuhV1W/B2DZbgGaVRFqj7wdGZaCkYbjhzsTlMoQUHTxZONNJPtTDUL86Rhb5Ps/io1sDZulGxZV4RZV0tM0JX0zNjDNFM6G+Ij8p7o6/RhMUsejFEdvF3uuMli0uAH1yi8ocTCCEwjuyLQVALA8VTpW9GGAieuRHCmvn+4LB7ae3lO8bFRoX1ugv/+nVl07Q4prf/IbSl3D2TKPohOtVBLFM/bzr+gv4kYg//giAvSZ+HvmsvfO8yRwM7vXLPvtkQzHnTTdP0N99jXVb28OZXeniZwbuanXGiZ+Pk3vVoQWkSeRZd1i4A6ynGCRx7WBXbO5rhl3ClmQAep+iE7Rn9Y0RUcXBIqD7+J7Htz914bqYX/BBtSpYdgn7MdMlKix4wCUv5U4YtKbB+ptnl2OLmCLV9QJiyrs+vXOUZa7e32+jLfr7PdQwZmqpIqgD+xSocZMjGW7Jk0OmT6BB9EPOo4TheqH"
                },
                "gasPrice":"0",
                "gasLimit":"rAI="
            },
            "signature":"e6r9o0KU0dxILWLCLuaFgBPSrhONMjvPKETbIgqB2gsYw7jDL62J24pJ5bj7LwgBauKTvUm0cQ6DwDfHTBYFKwE="
        }
    ]
}
```

And the parallelism `messageReceipts` ：

```javascript
{
    "messageReceipts":[
        {
            "exitCode":0,
            "return":[
                "AACbDn0JxxLKuBJ1v6iq6qX+b0iOkw=="
            ],
            "gasAttoFIL":"0"
        },
        {
            "exitCode":0,
            "return":[
                "zgE="
            ],
            "gasAttoFIL":"0"
        },
        {
            "exitCode":0,
            "return":null,
            "gasAttoFIL":"0"
        }
    ]
}
```
Finally run your go code for decoding the content of `return` (AACbDn0JxxLKuBJ1v6iq6qX+b0iOkw==) field, i got the miner address successfully, and i had did created three miners, there are:

* fcqnv886zw8zt9tsyn4h7524649leh53r5n0sg2p0
* fcqrfu4am29qjaf68gpxgg84cajuuks5udcyx2e2c
* fcqdzp28x8vnph7aedzw3pwlpwrnxjh77zayx75c5

Thank you again for helping me solve the problem.
