### ISSUE TITLE
[bug]Install Dependencies fail

### ISSUE THREAD

**Issue by AndyChen1984** [filecoin-project/go-filecoin#2156]
**Describe the bug**
command FILECOIN_USE_PRECOMPILED_RUST_PROOFS=true go run ./build/*.go deps
exit fail!

**To Reproduce**
1. Go to '/go-filecoin'
2. Run this command 'FILECOIN_USE_PRECOMPILED_RUST_PROOFS=true go run ./build/*.go deps'
3. See error

**Expected behavior**
success

**Screenshots**
./scripts/install-bls-signatures.sh
using local bls-signatures
/mnt/sata/go/src/github.com/filecoin-project/go-filecoin/bls-signatures/bls-signatures /mnt/sata/go/src/github.com/filecoin-project/go-filecoin
cargo 1.32.0-nightly (5e85ba14a 2018-12-02)
    Updating crates.io index
    Updating git repository `https://github.com/dignifiedquire/pairing`
    Finished release [optimized] target(s) in 0.77s
/mnt/sata/go/src/github.com/filecoin-project/go-filecoin
./proofs/bin/paramfetch fetch --all --json=./proofs/misc/parameters.json
panic: read |0: file already closed

goroutine 50 [running]:
main.runCmd.func2(0x4000017dd0, 0x1c9180, 0x400000e470, 0x4000044d90)
        /mnt/sata/go/src/github.com/filecoin-project/go-filecoin/build/main.go:78 +0x11c
created by main.runCmd
        /mnt/sata/go/src/github.com/filecoin-project/go-filecoin/build/main.go:75 +0x290
exit status 2

**Desktop (please complete the following information):**
 - OS: ubuntu 16.04 64bit
 - Browser [if applicable, e.g. chrome, safari]

**Additional context**
CPU:ARM A53
aarch64-linux-gnu-gcc (Ubuntu/Linaro 7.3.0-16ubuntu3) 7.3.0

**Comment by anorth** [comment]
It looks like the problem is in paramfetch. cc @sidke @laser

**Comment by AndyChen1984** [comment]
> It looks like the problem is in paramfetch. cc @sidke @laser

How can I get the paramfetch for Arm cortex A53?
I find "./proofs/bin/paramfetch " is x86-64 elf format in my server after download,but my CPU is Arm cortexA53.

**Comment by anorth** [comment]
Ah, I am very sorry but at this stage of development we are not supporting platforms/architectures other than Linux/x86. We certainly intend to in the future, but the team is focussed on core protocol development at present.

**Comment by anorth** [comment]
Tracking architecture support in https://github.com/filecoin-project/go-filecoin/issues/2258
