### ISSUE TITLE
Add >4GB system requirement in README

### ISSUE THREAD

**Issue by jaybutera** [filecoin-project/go-filecoin#2161]
### Description
My 4GB aws ec2 instance ran out of memory while installing dependencies (```FILECOIN_USE_PRECOMPILED_RUST_PROOFS=true go run ./build/*.go deps```). I upgraded to an 8GB and it worked fine. This could be worthwhile information for anyone running a client on a VM.

**Comment by rkowalick** [comment]
I added a note to the README. Thanks for finding this!
