### ISSUE TITLE
Error: failed to open datastore: Value log truncate required to run DB. This might result in data loss.

### ISSUE THREAD

**Issue by sandjj** [filecoin-project/go-filecoin#2162]
### Description
OS is centos7.6.1810.  The root partition is full and go-filecoin is crashed. So I decreased home partition and extended root partition.  When I run go-filecoin , I got  error:
# go-filecoin daemon
Error: failed to open datastore: Value log truncate required to run DB. This might result in data loss.

How to solve this problem

**Comment by schomatis** [comment]
Related to https://github.com/ipfs/go-ipfs/issues/5275.

**Comment by rkowalick** [comment]
@sandjj

Thanks for finding an interesting issue. The linked issue seems to contain a possible solution.

@schomatis , would there be harm in adding a `Truncate: true` to our initializations of badger datastores in go-filecoin? Here is a "starter" PR:

**Comment by schomatis** [comment]
> would there be harm in adding a `Truncate: true` to our initializations of badger datastores in go-filecoin?

Yes, in the sense that if for any reason the datastore gets corrupted Badger will just automatically remove all the data from that point in the log onward (i.e., truncate it).

The solution in IPFS was to force the user to explicitly enable that option so it would be aware of its implications, the use case being: I've stored important information that I don't have anywhere else, the datastore gets corrupted, and this might just be a minor bit flip (provided you had the bad luck that it landed in the wrong place), but most of your data is still on the log, so you may want to first backup the raw log (not through Badger but at a lower level like `dd`) where you might be able to recover a big portion of your data (provided you know its format) before actually truncating it and starting again.

This may not be an issue in gfc, I'm not sure what you're storing there, and it may be harmless to truncate the corrupted portion and replicate later.

**Comment by sandjj** [comment]
The data I store is not very useful, but I want to restore it as much as possible.  In addition, I want to keep information about nodes, such as wallet addresses. And how do I start the go-filecoin command correctly?

**Comment by sandjj** [comment]
The data I stored is not very useful, but I want to restore it as much as possible. In addition, I want to keep information about nodes, such as wallet addresses. And how do I start the go-filecoin command correctly?

**Comment by rkowalick** [comment]
@schomatis and I feel that the best solution to this problem is to

1. Keep truncation disabled by default, as it can cause data loss
1. Check for corruption of any of the badger dbs when they are read from disk.
1. If a db is corrupt, give the user the option to (A) re-read the db from disk with the truncate option, or (B) manually try to resolve the problem to hopefully prevent dataloss.

**Comment by schomatis** [comment]
@rkowalick Agreed, I think that adding the `truncate` config option might still be desirable (for someone who, say, wants to leave a node mining continuously in an non-interactive automated process, even at the risk of losing data) and hopefully, with a convenient interactive truncate option in place, the normal user won't bother to turn it on (and most probably leave it on and forget about it, causing future inadvertent loss of data).

**Comment by rkowalick** [comment]
I have merged the PR above. If we would like the more advanced interactive functionality later, we can implement it.
