### ISSUE TITLE
In CI, trigger User Devnet deploy as part of binary release process

### ISSUE THREAD

**Issue by ognots** [filecoin-project/go-filecoin#2172]
### Description

Rather than having the User Devnet deploy have it's own trigger, make the CircleCI job `trigger_user_devnet_deploy` part of the `build_and_publish_release` workflow. 

### Acceptance criteria

* As a fil developer or tester, I can be confident the "latest" `go-filecoin` Github release is compatible with the User Devnet
* As a product owner, I want to be able to trigger a User Devnet deploy as part of the binary release process

### Risks + pitfalls

* inadvertent devnet deploys on git tags matching regex `/^\d+\.\d+\.\d+$/`

### Where to begin

Use and modify existing CircleCI configuration when possible

**Comment by ognots** [comment]
Currently rethinking if this is a good approach

**Comment by anorth** [comment]
Devnet deploy will be quite infrequent (~monthly?) so process/documentation may be a better trade-off.

**Comment by ognots** [comment]
this has been implemented and tested successfully during 0.1.4 launch
bonus: test-devnet is also deployable via CI
