### ISSUE TITLE
[bug] processBlock() errors in user devnet

### ISSUE THREAD

**Issue by travisperson** [filecoin-project/go-filecoin#2176]
**Describe the bug**

We are seeing quite a few errors on the user devnet today, starting around 4AM PST.

https://search-filecoin-logs-feyxjodkwak6pulqamqtqwgddi.us-east-1.es.amazonaws.com/_plugin/kibana/goto/88c30971546be52af89da2669791c178

There is a mixture of two errors, seen across all nodes

- `processBlock(): processing block from network: blocks state root does not match computed result` ~220
- `processBlock(): processing block from network: context deadline exceeded` ~50

These are observed over 3 hours, and are continuing

**Comment by rkowalick** [comment]
@travisperson Is this still happening? Hopefully nodes with old code aren't connecting as much anymore.

**Comment by travisperson** [comment]
It doesn't appear to be happening anymore. Appears to have had stopped a little after 11AM PST. We can either close this, or we can use it as a reference issue if we want to find a better way to handle the errors.

**Comment by travisperson** [comment]
I think your issue #2182 will mitigate this. If we see the errors again we can reevaluate if we want to treat them as errors or warnings. I'm going to close this issue for now.
