### ISSUE TITLE
Add DHT query subcommand (Copy from IPFS)

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/go-filecoin#2177]
### Description
It will be useful for debugging purposes (for example to make sure that DHT bootstrapping is wai) to include this subcommand.  Copy over [this](https://github.com/ipfs/go-ipfs/blob/master/core/commands/dht.go#L50) ipfs command to filecoin.  For reference on how to do this see PR #2158.  This should be even simpler because the porcelain api is already set up with a router and all the command helpers are already in place.
 
Good first issue for a go-ipfs contributor.  Not a bad first issue for an experienced dev looking at filecoin for the first time.

### Where to begin
1. copy code from IPFS
2. modify code to call into router from go-filecoin porcelain API instead of ipfs node
3. add a `GetClosestPeers` call to filnet/router, inside that method cast the wrapped interface and error if routing isn't a kad dht.  Then pipe the call through
4. add a `NetworkGetCLosesPeers` call to plumbing/api.go calling `GetClosestPeers` on the ntwk struct.

**Comment by firmianavan** [comment]
#2158 has not been merged yet
