### ISSUE TITLE
[bug] Failed to deploy nightly devnet

### ISSUE THREAD

**Issue by travisperson** [filecoin-project/go-filecoin#2184]
**Describe the bug**

The command which exited to fail the deployment was
```
++ docker exec filecoin-1 go-filecoin --repodir=/var/local/filecoin miner create --price 0.000000001 --limit 300 10 10
Error: Could not create miner. Please consult the documentation to setup your wallet and genesis block correctly: invalid message: message from non-account actor
```

The only suspicious thing I've been able to find so far is a warning from badger

```
+ docker run -v /home/ubuntu/car:/var/filecoin/car -v /mnt/storage/filecoins:/var/local/filecoins --entrypoint=/usr/local/bin/go-filecoin 657871693752.dkr.ecr.us-east-1.amazonaws.com/filecoin:latest init --genesisfile=/var/filecoin/car/genesis.car --repodir=/var/local/filecoins/1 --peerkeyfile=/var/filecoin/car/keyFile1 --auto-seal-interval-seconds 0
initializing filecoin node at /var/local/filecoins/1
badger 2019/03/06 06:21:11 INFO: All 0 tables opened in 0s
badger 2019/03/06 06:21:11 INFO: All 0 tables opened in 0s
badger 2019/03/06 06:21:11 INFO: All 0 tables opened in 0s
badger 2019/03/06 06:21:11 INFO: All 0 tables opened in 0s
badger 2019/03/06 06:21:11 INFO: Storing value log head: {Fid:0 Len:43 Offset:3815}
badger 2019/03/06 06:21:11 INFO: Force compaction on level 0 done
badger 2019/03/06 06:21:11 INFO: Storing value log head: {Fid:0 Len:42 Offset:134}
badger 2019/03/06 06:21:11 INFO: Force compaction on level 0 done
badger 2019/03/06 06:21:11 INFO: Storing value log head: {Fid:0 Len:42 Offset:803}
badger 2019/03/06 06:21:11 INFO: Force compaction on level 0 done
badger 2019/03/06 06:21:11 WARNING: While forcing compaction on level 0: Unable to fill tables
```

@rkowalick also saw these same warnings when he upgrade to golang 1.12. We build the docker container images using [`circleci/golang:latest`](https://github.com/filecoin-project/go-filecoin/blob/master/.circleci/config.yml#L322), so I'm wondering if this is the same issue.

https://gist.github.com/travisperson/a77d38cb7958b610beeef9544b65bd51

**Comment by rkowalick** [comment]
@travisperson ,

Those warnings are shown on go 1.11.x as well, so they don't necessarily mean something is wrong. The big question is whether or not the `init` command exited successfully or not. On go 1.12, one would see
```
 Error: sync /dev/stderr: bad file descriptor
``
at the end of the init command and its exit status would be 1 instead of 0.

**Comment by gmasgras** [comment]
> at the end of the init command and its exit status would be 1 instead of 0.  

the exit code of `go-filecoin init` was 0 for each of the 5 filecoin nodes.

This is the command that exited with non-zero:
```
+ docker exec filecoin-1 go-filecoin --repodir=/var/local/filecoin message wait zDPWYqFCtSi2KRJEaUpMoR5fAtnFDhY6MptnDifhUJsytUy9DqPa
{
        "meteredMessage": {
                "message": {
                        "to": "fcqdzcsfwqvh9m97alv8qftt6j4cq7wehslfxkamg",
                        "from": "fcq9dmarma5atgf9adrr5y5gjdh7ldgunyketrp35",
                        "nonce": "Aw==",
                        "value": "100",
                        "method": "",
                        "params": null
                },
                "gasPrice": "0.000000001",
                "gasLimit": "rAI="
        },
        "signature": "HnWE0xSnzCBFPCHPMox8wIf5bs6+gXk2YI4JyOY8M99yPyM3mB0qUHsKGKcZgaRDoT0AGSLmX3CGdQKQzSbyCwA="
}
{
        "exitCode": 0,
        "return": null,
        "gasAttoFIL": "0"
}
++ docker exec filecoin-1 go-filecoin --repodir=/var/local/filecoin miner create --price 0.000000001 --limit 300 10 10
Error: Could not create miner. Please consult the documentation to setup your wallet and genesis block correctly: invalid message: message from non-account actor
```

**Comment by travisperson** [comment]
We deployed correctly the previous night, and @gmasgras just ran another deployment and ran into the same error.

- 19bdff5dc806926bb50f6918b3d478ac43ee64d8 - Last successful deployment
- 83a8ea7d31152fcbf1f289f889eb997c607d653d - Deployment that failed last night
```
➜  go-filecoin git:(feat/fast-updates) ✗ git log --name-only 19bdff5dc806926bb50f6918b3d478ac43ee64d8...83a8ea7d31152fcbf1f289f889eb997c607d653d
commit 83a8ea7d31152fcbf1f289f889eb997c607d653d
Author: Phritz <157153+phritz@users.noreply.github.com>
Date:   Tue Mar 5 15:12:24 2019 -1000

    add integration to contrib (#2140)

CONTRIBUTING.md

commit 255ee7d1a2fce21bbafdccdd6c08bb1a93958e46
Author: Sidney Keese <sidke.z@gmail.com>
Date:   Tue Mar 5 15:36:49 2019 -0800

    paramfetch: parameter validation (#2143)
    
    * update paramfetch
    
    * bump ci timeout for parameter downloading

.circleci/config.yml
build/main.go
proofs/rust-fil-proofs

commit b2ecbd0cab01eb38861d264412b9d2dc022dfce5
Author: Alex North <anorth@users.noreply.github.com>
Date:   Thu Feb 28 15:18:26 2019 +1100

    Plumb message validator to sender and validate outgoing messages before adding them to mpool.
    
    This is most of the work for #1934 (there are some cases the validator doesn't yet check).

commands/message_daemon_test.go
consensus/validation.go
node/message_propagate_test.go
node/node.go
node/node_test.go
plumbing/msg/sender.go
plumbing/msg/sender_test.go
plumbing/msg/testing.go
plumbing/msg/waiter_test.go

commit e00ef78c9ec03da6a7bd473fbdacaa44b770bcb5
Author: Ryan Kowalick <690440+rkowalick@users.noreply.github.com>
Date:   Tue Mar 5 12:04:44 2019 -0500

    Update required go version for filecoin (#2169)
    
    Filecoin doesn't work with go 1.12 right now: #2167, so we update the
    README and version checking code to require the go version to be < 1.12

README.md
util/version/version.go
util/version/version_test.go
```

Wild guess is that b2ecbd0cab01eb38861d264412b9d2dc022dfce5 failed (https://github.com/filecoin-project/go-filecoin/pull/2139)

**Comment by travisperson** [comment]
Another PR I thought may have had something to do with it would be #2114 (Pay miner owner instead of miner). That was merged 8 days ago though, so it still is an issue in the above 4 commits. However, the context of #2114 might be helpful when digging into RC.

**Comment by travisperson** [comment]
This is the failure condition

https://github.com/filecoin-project/go-filecoin/blob/447923fdf4ff9b1aa2fd81fdf07d2cfb9cd0bfb9/consensus/validation.go#L48-L50

**Comment by travisperson** [comment]
So the validation check is new, so I'm wondering if this just means we are doing something incorrect in our devnet setup that was invalid, and we are now catching it.

https://github.com/filecoin-project/go-filecoin/pull/2139/files#diff-45355871e26f118ffda505d75e0c6bf0R80

**Comment by anorth** [comment]
I made that change. I had to wrangle some integration tests to work appropriately afterwards so it's indeed possible that the devnet setup is doing something that's (now) invalid. In summary, nodes now validate messages before sending them. Validation includes requiring that there is an actor installed at the sending address, that it has FIL, message signature is valid etc. It is essential to have actors installed in the genesis block: these are the only addresses that can send messages.

Invalid messages are likely to fail to be mined, but the validation is necessarily imperfect and it's possible that a message initially deemed invalid would have eventually been mined after some *other* message change the state so as to make the invalid one now valid.

**Comment by travisperson** [comment]
I rebase my FAST PR onto the latest master and I am now able to reproduce this locally.

https://github.com/filecoin-project/go-filecoin/pull/2168

This should make it much easier to track down the issue, as it fails in about 7 seconds.

**Comment by travisperson** [comment]
> In summary, nodes now validate messages before sending them. Validation includes requiring that there is an actor installed at the sending address, that it has FIL, message signature is valid etc. It is essential to have actors installed in the genesis block: these are the only addresses that can send messages.

I think we are meeting these requirements. The only built in genesis actors we use are for the genesis node, and it's miner. The failure here (from reading into the above) is that `filecoin-1` default wallet address is the actor which can't be found. Normally this would tell me that no filecoin was sent to the address. However, we do send to the first wallet address for the node, [which should be the default](https://github.com/filecoin-project/go-filecoin/blob/master/porcelain/message.go#L61-L80). We also issue the `message wait` from `filecoin-1`, so we know that it has the message that would construct the wallet actor.

The only thing left that I can think of is that the actor code is wrong.

I did a bit of debugging and found that the wallet addr has no `Code` set, it appears we have some follow up work to fix this in the following places:

https://github.com/filecoin-project/go-filecoin/blob/6914061e22bb8725182e5496b1286c914b5b9c26/vm/context.go#L158-L160
https://github.com/filecoin-project/go-filecoin/blob/6914061e22bb8725182e5496b1286c914b5b9c26/vm/context.go#L213-L215
https://github.com/filecoin-project/go-filecoin/blob/6c6f511bf60cad8adc76f2e09c49add10bf97310/consensus/processor.go#L458-L463
https://github.com/filecoin-project/go-filecoin/blob/6c6f511bf60cad8adc76f2e09c49add10bf97310/consensus/processor.go#L594-L596

**Comment by travisperson** [comment]
I'm going to escalate this to a p0 as I think we should be working on this over some other work.

The lack of properly build actors with the new validation code essentially breaks go-filecoin.

**Comment by travisperson** [comment]
I don't know if we need to change the above `GetOrCreateActor`, but we need to at least find the correct place to call `account.UpgradeActor`. It looks like the first instance of `GetOrCreateActor` in _consensus/processor.go_ is the origin of wallet actors.

**Comment by anorth** [comment]
I think the appropriate fix is to allow an undefined actor code in the send validation. When the message is processed, the actor will silently be upgraded to an account actor.

There are obviously no tests for this at the moment, so I'll try to craft one.
