### ISSUE TITLE
Test Categorization 

### ISSUE THREAD

**Issue by ognots** [filecoin-project/go-filecoin#2185]
### Description

Create the means to categorize tests. Candidate categories would be  `unit`, `integration`, or `functional` tests.

Currently there is no canonical way to distinguish between the various types of tests. Running `go run ./build/*.go test` results in both `unit` and `integration` tests being run.

Being able to run tests with greater granularity will allow test parallelization in CI and allow developers to target specific tests suites, improving productivity.

### Acceptance criteria

* As a developer I should be able to classify my test as a `unit`, `integration` or `functional` test
* As a developer or build engineer, I should be able to run only a specific category of test, and not all tests

### Risks + pitfalls

minimal

### Where to begin

Functional test use a flag https://github.com/filecoin-project/go-filecoin/blob/master/functional-tests/faucet_test.go#L23 as a controller to whether the tests should run.

When using flags, all tests must instantiate the same flags via `flag.TYPE()` otherwise tests will exit with an error due to unknown flags. A common testing library would be recommended as a way to satisfy this requirement. 

For example (using current code):
```
$ go test -timeout 30m -parallel 8 ./... -v -sector-builder-tests=true
?   	github.com/filecoin-project/go-filecoin	[no test files]
flag provided but not defined: -sector-builder-tests
```

**Comment by anorth** [comment]
Go has a built-in method for identifying small unit tests, the `-short` flag. I have intention to identify all the daemon tests as not `short` and see where that gets us. I propose that as a first step.

A very small set of flags identifying other suites may be appropriate. Note that particular test classes can already be targeted by the `-run` argument, so the flags would likely identify larger classes like `--very-slow`.

**Comment by ognots** [comment]
that would be a great first step @anorth 

my primary motivation for this is primarily to run the build and unit tests concurrently in CI
