### ISSUE TITLE
进行p2p连接，执行go-filecoin swarm findpeer $peerID出现报错：Error: routing: not found

### ISSUE THREAD

**Issue by muronglaowang** [filecoin-project/go-filecoin#2199]

**Comment by rkowalick** [comment]
Could you provide more context for when you are seeing this error?

**Comment by muronglaowang** [comment]
@rkowalick 
执行：go-filecoin address  lookup fcq5flr7ckx8kat74pfe0y88tx57p4ajww57s3gk2
得到：QmZeuoZi3Gvq7UWftCaZDFHC33ECg925sZ13PBsrkgKYdG
继续执行：go-filecoin swarm findpeer QmZeuoZi3Gvq7UWftCaZDFHC33ECg925sZ13PBsrkgKYdG
得到：Error: routing: not found

**Comment by rkowalick** [comment]
There are a couple reasons this could be happening:

1. The node running that address is no longer running on the network
1. The node is behind a different NAT router than your computer. This functionality is currently not working on user net, so if you are using that, you will need to wait until a new release of user net.

Do either of these apply?

**Comment by ZenGround0** [comment]
@muronglaowang also could be related to you dialing yourself if `QmZeuoZi3Gvq7UWftCaZDFHC33ECg925sZ13PBsrkgKYdG` is your own peerID.

**Comment by muronglaowang** [comment]
@rkowalick  yes ,the first is ture
