### ISSUE TITLE
  How do I query the tokens that the miner has acquired?

### ISSUE THREAD

**Issue by sandjj** [filecoin-project/go-filecoin#2201]
I have some filecoin nodes. I stored and retrieved a lot of files. But I didn't see an increase in wallet of the node.  How do I query the tokens that the miner has acquired?

**Comment by rkowalick** [comment]
@sandjj,

The code currently deployed on usernet allocates the mining reward to the miner actor, so the reward will not show up in your wallet balance on usernet. This is not the intended behavior and a recent [change](#2114) has been made to allocate the reward to the miner actor's owner, so after that change has been deployed to the usernet, you will see the reward in your wallet.

**Comment by rkowalick** [comment]
If you'd like to confirm that you mined correctly, you can run

```
go-filecoin actor ls | grep "your-miner-address"
```

This will contain a `balance` field which is the balance of your miner and will increment by the block reward (currently 1000FIL) for each successfully mined block.

Please reopen if you are still having problems.
