### ISSUE TITLE
Use Go modules

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/go-filecoin#2208]
### Description
So long gx 👋 we are migrating dependency management to go modules

* See the [go modules wiki](https://github.com/ipfs/go-ipfs/issues/5848)

* See the [historical issue](https://github.com/ipfs/go-ipfs/issues/5850) beginning the discussion in go-ipfs

* See some [prior art](https://github.com/ipfs/go-ipfs/pull/5849) [in go-ipfs](https://github.com/ipfs/go-ipfs/issues/5848)

* A [script](https://gist.github.com/raulk/708debe71b9abd395fc7935ee1215ddd) from @raulk for moving to go-mod 

### Acceptance criteria
Given the above resources, figure out how to move from gx to go-mod and do this.

### Where to begin
A close reading of the above resources, or talk to @Kubuxu.  Seems like @anacrolix and @raulk are also good people to consult on this.

**Comment by mishmosh** [comment]
A really useful Step 0: investigate all the resources pointed out above, and then draft a plan.

**Comment by hsanjuan** [comment]
I think I can do this

**Comment by hsanjuan** [comment]
See comments in #2221 about all the trouble I found..

**Comment by anorth** [comment]
A quick bit of context: we really want a good plan for this, but would like to land the actual, possibly-disruptive changes after our next release (so from 1 April).

**Comment by phritz** [comment]
agree with @anorth lets not land this this week

**Comment by hsanjuan** [comment]
I will continue at fil-fridays pace. I don't think there is a way to have a "good plan" without actually trying to do it like I did and surface the issues. Other than that, the actual go-modding is a very simple process. All the issues steam from the tooling around go-filecoin but there are no issues with go-filecoin itself.

**Comment by mishmosh** [comment]
> I don't think there is a way to have a "good plan" without actually trying to do it like I did and surface the issues

@hsanjuan This makes sense. Continuing at fil-fridays pace sounds good 🙌 

I believe @anorth's comment on "good plan" was to clarify that this doesn't need to be completed for the upcoming release next week — not "plan only, don't try it in code". Is that right @anorth?

**Comment by ZenGround0** [comment]
@hsanjuan you got scooped by @Stebalien: https://github.com/filecoin-project/go-filecoin/pull/2307

If there is more work to be done it should be added as a commit on 2307.

**Comment by anacrolix** [comment]
Should this be closed? It's not yet fixed.

**Comment by hsanjuan** [comment]
oh, sorry, I somehow thought #2307 had been merged
