### ISSUE TITLE
Propose-storage-deal can fail with "context deadline exceeded"

### ISSUE THREAD

**Issue by pengxiankaikai** [filecoin-project/go-filecoin#2210]
**Describe the bug**
execute:
go-filecoin client propose-storage-deal --allow-duplicates fcqdzp28x8vnph7aedzw3pwlpwrnxjh77zayx75c5 $CID 3 200
Error: error creating payment: context deadline exceeded

return Error, but balance change:
go-filecoin wallet balance fcq2j4j2hu7mc0fm0xyxk7euucezhzwg9mfpkp7fq
801

go-filecoin wallet balance fcq2j4j2hu7mc0fm0xyxk7euucezhzwg9mfpkp7fq
735

go-filecoin wallet balance fcq2j4j2hu7mc0fm0xyxk7euucezhzwg9mfpkp7fq
668.6124205

The miner I specified also did not store changes in file space.

minerAddress:
fcqdzp28x8vnph7aedzw3pwlpwrnxjh77zayx75c5   
Proven Storage： 0MB

thinks!

**Comment by pengxiankaikai** [comment]
supplement：
Transaction charge record found in the block：
{
                "meteredMessage":{
                    "message":{
                        "to":"fcqp606qfk5gwmq6ac24g4mhv3cr8zzf67vqkpulh",
                        "from":"fcq2j4j2hu7mc0fm0xyxk7euucezhzwg9mfpkp7fq",
                        "nonce":"Bg==",
                        "value":"66",
                        "method":"createChannel",
                        "params":"glYAALqFPeGzjsI5kjYR2PWRdmGxgiy7Q/3CAg=="
                    },
                    "gasPrice":"0",
                    "gasLimit":"rAI="
                },
                "signature":"cz5ndFgRlNh4v+Bl1a13cWfEADms/vvBCwjAHMLazV97zKjo9OMb8cYUMXHEQxFv2dGPLAYzwafXYryykvD5AAA="
            }

**Comment by rkowalick** [comment]
@pengxiankaikai Seeing `context deadline exceeded` when running `client propose-storage-deal` is definitely a bug.

The fact that your payment channel was created and your balanced was deducted is a known problem, as we have not yet implemented verification of storage before the client pays the miner.



Currently, the payment vouchers are sent out without any confirmation that the data was stored by the storage miner, so I think this might be related.

**Comment by pengxiankaikai** [comment]
@rkowalick But sometimes it is possible to successfully return the dealID when it is stored by the `client propose-storage-deal` . It is only in the staged state. Is it impossible to store files to the miner node?

**Comment by shannonwells** [comment]
There is some test code I left in the issue #2123 in case this helps

**Comment by acruikshank** [comment]
@pengxiankaikai The problem appears to be that the storage deal is timing out while waiting for the payment channel to be created. The timeout is established on this line: 

https://github.com/filecoin-project/go-filecoin/blob/3212773e1dbb49d620b974d48ce8befccd0f1e21/protocol/storage/client.go#L89

4 * BlockTime is 2 minutes, and it includes some work that happens before creating the channel. This is really low for such an important transaction. I recommend this timeout be greatly increased or possibly even eliminated.

**Comment by pengxiankaikai** [comment]
@acruikshank thanks! It should be that the storage node times out during the process of receiving the file submission copy certificate. At this time, the miner node consumes system resources and cannot be completed or the node is killed by the system.
