### ISSUE TITLE
 balance is zero always

### ISSUE THREAD

**Issue by dayou5168** [filecoin-project/go-filecoin#2212]
i started go-filecoin daemon and it runs well and i got ${MESSAGE_CID}
but when i execute 
go-filecoin message wait ${MESSAGE_CID} it has no response
and i execute
go-filecoin wallet balance ${WALLET_ADDR}
i got zero for many times

**Comment by sywyn219** [comment]
Need to synchronize the blocks

**Comment by dayou5168** [comment]
> Need to synchronize the blocks

how to synchronize.  thx!

**Comment by dayou5168** [comment]
@sywyn219 
how to synchronize. thx!

**Comment by travisperson** [comment]
As long as your daemon is running, you will be synchronizing with other peers. However, this process can take quite a bit of time, particularly now that the current user devnet is at almost 40,000 blocks. This is something we are looking into over in #2050 and #2067.

The actually process of downloading all the block is fairly quick. When you start a new node, you will see a count down from a number close to the current block height, down to zero.

```
...
09:07:14.649  INFO chain.sync: syncing the chain, currently at block height 38623 default_syncer.go:153
09:07:14.842  INFO chain.sync: syncing the chain, currently at block height 37537 default_syncer.go:153
...
09:07:17.847  INFO chain.sync: syncing the chain, currently at block height 7187 default_syncer.go:153
09:07:17.906  INFO chain.sync: syncing the chain, currently at block height 6345 default_syncer.go:153
...
```

Once that process is complete, the node will start to verify each block as it walks back up the chain. This is what takes most of the time, and this process occur for each block.

Your balance will stay at zero until the block containing the message which transfers the value from the faucet wallet to your own has been processes, which is near the end of the chain.

You can monitor how far your node is into this process by printing out information about the current chain head. This will provide you a block height for the latest block your node has processes.

```sh
go-filecoin show block $(go-filecoin chain head --enc=json | jq -r '.[0]."/"')
```

**Comment by dayou5168** [comment]
> ```shell
> go-filecoin show block $(go-filecoin chain head --enc=json | jq -r '.[0]."/"')
> ```

thx for you response which helps me lot.
 it seems like some of my test can get FIL 
it takes about one or two days ,quite a long time!

**Comment by anorth** [comment]
It is slow, yes. We'll be working to speed it up at some point in the intermediate future, although of course contributions before then are welcome!

Note that we'll be rebooting the user devnet in a few weeks, at which point the chain will restart from genesis.

It seems that your problem is now resolved, so I'll close this issue. Thanks!
