### ISSUE TITLE
compile bug 

### ISSUE THREAD

**Issue by dayou5168** [filecoin-project/go-filecoin#2213]
my locate is china
when i compile filecoin i get this err
fetching: v9-zigzag-proof-of-replication-52431242c129794fe51d373ae29953f2ff52abd94c78756e318ce45f3e4946d8.vk
downloading parameter... error:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:20 --:--:--     0curl: (7) Failed connect to ipfs.io:443; Connection refused

fetching: v9-zigzag-proof-of-replication-f8b6b5b4f1015da3984944b4aef229b63ce950f65c7f41055a995718a452204d.vk
downloading parameter... error:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:20 --:--:--     0curl: (7) Failed connect to ipfs.io:443; Connection refused

even with ipfs running. and  i get vpn link for ipfs ,i can access https://ipfs.io
just cant get compile through!
what should i do?

**Comment by travisperson** [comment]
We use a tool called `paramfetch` that is maintained over in the `rust-fil-proof` repo. It currently only supports downloading from `https://ipfs.io`. I'm a little confused why under a vpn you would be having issue though, unless it's a http proxy.

If the download fails, we should be building the proofs locally though. I just tested this and found that it doesn't actually work. You can manually run the parameter generation though.

```
go-filecoin $ ./proofs/bin/paramcache
```

**Comment by dayou5168** [comment]
@travisperson 
i follow you steps 
go-filecoin $ ./proofs/bin/paramcache
go-filecoin $ ./scripts/copy-groth-params.sh
the complie get through ,but when i run
# go-filecoin damon
i get this err info
 ERROR       node: processBlock(): processing block from network: input chain contains a cached bad tipset node.go:1128
and i search the issues. i find #2211
i follow the steps 
git fetch origin devnet-user -f
git checkout devnet-user
the I compile agine 
it failed
sorry, man ,my english is bad,hope i said correctly!

**Comment by dayou5168** [comment]
@travisperson 
now i am confused 
show i execute these command before the compile:
git fetch origin devnet-user -f
git checkout devnet-user

**Comment by travisperson** [comment]
It depends what you are trying to build. If you want to join the user devnet you will want to be on the `devnet-user` tag. The `devnet-user` code does not have `paramfetch`, so you won't run into that issue with it.

```
$ git fetch origin devnet-user -f
$ git checkout devnet-user
$ go run build/*.go deps
$ go run build/*go build
$ go run build/*go install
$ rm -rf ~/.filecoin
$ go-filecoin init --devnet-user --genesisfile=http://user.kittyhawk.wtf:8020/genesis.car
$ go-filecoin daemon
```

**Comment by anorth** [comment]
Note that there are difficulties building the `devnet-user` tag right now. Please follow #2211 for a resolution.

I'll then close this issue in favour of #2219
