### ISSUE TITLE
error: Could not compile `storage-backend` -- Can't build devnet-user, errors during build

### ISSUE THREAD

**Issue by aaronhenshaw** [filecoin-project/go-filecoin#2215]
**Describe the bug**
When running -- `FILECOIN_USE_PRECOMPILED_RUST_PROOFS=true go run ./build deps` I get an erorr during the `./scripts/install-rust-proofs.sh` part.

```
...
   Compiling human-size v0.4.0
   Compiling permutate v0.3.2
   Compiling storage-backend v0.1.0 (/home/ubuntu/go/src/github.com/filecoin-project/go-filecoin/proofs/rust-proofs/storage-backend)
error: Edition 2018 is unstable and only available for nightly builds of rustc.

   Compiling proc-macro2 v0.3.8
error: Could not compile `storage-backend`.
warning: build failed, waiting for other jobs to finish...
error: build failed
~/go/src/github.com/filecoin-project/go-filecoin
cp: cannot stat 'proofs/rust-proofs/target/release/paramcache': No such file or directory
cp: cannot stat 'proofs/rust-proofs/target/release/libfilecoin_proofs.h': No such file or directory
cp: cannot stat 'proofs/rust-proofs/target/release/libfilecoin_proofs.a': No such file or directory
cp: cannot stat 'proofs/rust-proofs/target/release/libfilecoin_proofs.pc': No such file or directory
Command './scripts/install-rust-proofs.sh' failed: exit status 1
exit status 1
```

**To Reproduce**
1. Using this walkthrough -- https://github.com/filecoin-project/go-filecoin/wiki/Getting-Started
2. Ubuntu 18.04 on aws instance
3. `git checkout devnet-user`
4. Walked through installing quite a few dependencies that aren't mentioned and managing other errors.
5. run `FILECOIN_USE_PRECOMPILED_RUST_PROOFS=true go run ./build deps` in `go-filecoin` directory
6. Got to the error above and figured it's worth raising an issue, as I am not sure how to fix it.

**Comment by travisperson** [comment]
What version of rust do you have installed?

The actually dependency requirement are listed in the [README](https://github.com/filecoin-project/go-filecoin#install), the wiki page linked to is just about getting connect to the user devnet (I think this is a bit confusing though).

**Comment by aaronhenshaw** [comment]
I didn't have rust installed and I don't have the correct version of go, I had 1.12 not 1.11. So I will try again, this is probably not an issue.

Thanks for the help!

**Comment by phritz** [comment]
likely dup of #2167 , please reopen if not!
