### ISSUE TITLE
[bug] Installing deps doesn't work if ipfs.io is unreachable.

### ISSUE THREAD

**Issue by travisperson** [filecoin-project/go-filecoin#2219]
**Describe the bug**

This is in relation to #2213, where ipfs.io is not reachable for the user. This issue is for tracking the failure here in go-filecoin. However, the fix is a change to `paramfetch`, which is filed in rust-fil-proof https://github.com/filecoin-project/rust-fil-proofs/issues/535

**To Reproduce**
1. Add `127.0.0.1 ipfs.io` to our host file
2. Run `go run build/*.go deps`

**Expected behavior**
paramfetch fails, but deps continues and parameters are generated with `paramcache`.

**Comment by anorth** [comment]
https://github.com/filecoin-project/rust-fil-proofs/issues/535 has been closed. @travisperson  could you please attempt to repro and/or close?
