### ISSUE TITLE
EC Upgrade 1: ticket arrays

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/go-filecoin#2222]
### Description
Perhaps the biggest of several [recent changes](https://github.com/filecoin-project/specs/pull/138) to the EC spec is that blocks now must hold onto an array of tickets, one for each null block.  This issue tracks work to make this change.

### Acceptance criteria
* block format includes space for multiple tickets
* during mining new blocks are created with an array of tickets in the case of null block mining
* during validation the number of tickets is checked to make sure that it corresponds with the height field.

Don't worry about what we put in the ticket array so much.  Generating something that will actually be validated is tracked in part 4.  Because we don't have VDF bindings we need to mock some of this out anyway.

**Comment by anorth** [comment]
Note that block timestamp validation must be changed to use ticket height.

**Comment by ZenGround0** [comment]
This is tracking the syntactic change to the block header.
- [ ] use the spec compliant ticket type with the correct VDF and VRF subtypes
- [ ] use an array instead of a single ticket
- [ ] don't make any semantic changes to ticket generation, just put the same data we currently use in a subfield of a single ticket in the array.
