### ISSUE TITLE
EC Upgrade 2: randomness sampling from ticket chain

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/go-filecoin#2223]
### Description
In a world with ticket arrays, randomness is sampled along the *ticket chain*.  We need to change randomness sampling fundamentally.

### Acceptance criteria
(1) Small design doc for moving randomness sampling from blockchain to ticket chain.

(2) Sync with the spec.  If things are underspecified [in the spec](https://github.com/filecoin-project/specs/blob/master/expected-consensus.md) then we need to get these details in the spec.  It should be pretty good though.

(3) Implement
* ancestor extraction now extracts tickets instead of blocks
* randomness sampling from the ticket chain conforms to the all the edge cases that by now should be in the spec.
* during block mining miners can correctly sample randomness from the tickets they have created as part of mining null blocks.  This edge case is essential for guaranteeing progress.
* please extensively test edge cases

### Risks + pitfalls
Lots of tricky details, many of which might exist as bits in the heads of others.

### Where to begin
Read the spec!

**Comment by ZenGround0** [comment]
This is now tracking semantic changes to the ticket array
- [ ] mining null blocks adds ticket to ticket array
- [ ] create leader election lookback (can set to 1 for now)
- [ ] sampling randomness is now greatly simplified to iterating over max(N, M) tickets.  N is proving period height + post look back.  M is leader election look back
- [ ] use ticket iterator abstraction to help with the above
- [ ] mining updates sampling array to use null tickets to ensure liveness
- [ ] reason about / spec cross reference / spec update edge cases concerning iteration over ticket chain in the case of multiple winners with null blocks

**Comment by anorth** [comment]
@ZenGround0 is ticket sampling complete, or if not could you jot down what we still need?

**Comment by ZenGround0** [comment]
Not yet complete.  We need to introduce lookback into leader election and election validation.  I'm on this.
