### ISSUE TITLE
EC Upgrade 4: integrate randomness sampling into the leader election rules

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/go-filecoin#2225]
### Description
Right now the EC leader election proof and block validation only refers to data in the block and its parent.  [The new spec](https://github.com/filecoin-project/specs/blob/master/expected-consensus.md#secret-leader-election) includes upgrades to the protocol which entail sampling tickets from further back in the chain to prove and validate a block's status as a leader.

This issue tracks all the work needed to get the implementation of leader election in line with the spec.

### Acceptance criteria
* Block mining now actually uses randomness sampling to get tickets from the past.  Block mining includes "scratching off" a past ticket (using VRF) and including the scratched ticket ( i.e. VRF proof ) as an election proof (see the spec)
* ~Block mining now updates the ticket array of the new block properly by sampling a past ticket and running a mock VDF on that ticket before including it in the new ticket array.~
* Block validation checks election proofs with respect to the ticket a lookback parameter away and whatever notion of mock VRF validity we are using.
* ~Block validation checks tickets with respect to the previous ticket in the chain and whatever mock VRF and VDF validity we are using.~

If any of that doesn't make sense go read the spec!  If it still doesn't make sense open a spec issue and don't stop until it makes sense or the spec has been updated with any corrections!

### Where to begin
Read the spec!

**Comment by anorth** [comment]
Closed by #3810
