### ISSUE TITLE
Bad loop on interactive prompt from paramfetch when building deps

### ISSUE THREAD

**Issue by chenminjian** [filecoin-project/go-filecoin#2248]
**To Reproduce**
1. Execute 'FILECOIN_USE_PRECOMPILED_RUST_PROOFS=true go run ./build/*.go deps'

**Screenshots**
![try](https://user-images.githubusercontent.com/13758621/54181319-23291e00-44d9-11e9-94a3-4bccfb3e4a13.png)

**Desktop**
 - OS: MacOS High Sierra

**Comment by dayou5168** [comment]
i got this err befor no long time ago 
you can try run ipfs damon first 
then begain the compile

**Comment by anorth** [comment]
Fix for this is coming in https://github.com/filecoin-project/rust-fil-proofs/issues/535

**Comment by chenminjian** [comment]
> i got this err befor no long time ago
> you can try run ipfs damon first
> then begain the compile

I tried it, but the result is the same

**Comment by laser** [comment]
This fix has been merged into go-filecoin master.
