### ISSUE TITLE
Recover from failure sampling chain for randomness from within state machine

### ISSUE THREAD

**Issue by laser** [filecoin-project/go-filecoin#2251]
### Description

When the PoSt verifying Filecoin node has different view of blockchain than PoSt generating Filecoin node (because the verifier's chain lags behind the generator's by some number of blocks), the `submitPoSt` message can fail to verify. This failure results from an error encountered sampling randomness from the block chain at a block height which doesn't yet exist in the verifier's chain (but does exist in the generator's chain).

After talking to @ZenGround0 about this, we wonder if perhaps this error scenario should be handled with a VM "temporary error" instead of the current "revert error." We aren't sure, though. Any ideas, @acruikshank or @anorth?

### Open Questions

1. How many times should we retry `submitPoSt` processing?
1. Under what circumstances should we fault (instead of retrying) when processing a `submitPoSt` message?

**Comment by anorth** [comment]
That sounds reasonable to me, at least for now.

Does the submitPost message include any information about the chain state
from which randomness was sampled? What happens in the opposite scenario,
where the submitter's chain lags?

**Comment by ZenGround0** [comment]
AFAIK the submitPost message contains no info about the height at which the challenge was sampled.  That info is stored in the state machine on the miner actor.

If the submitter (i.e. prover)'s chain lags then the message processor will have the section of the chain needed for sampling randomness and validating correctness of the proof.  In fact the design of the system is such that if everything is working correctly we expect a lag of about one proving period (this parameter is still not known).

If the post submission is delayed *too* much then the state machine will deduct a fee for late submission, but randomness sampling won't be a problem or cause any errors.
