### ISSUE TITLE
Use a helper function instead of overwriting FakeChildParams in default_syncer_test.go

### ISSUE THREAD

**Issue by shannonwells** [filecoin-project/go-filecoin#2253]
### Description
There could be unwanted side effects (false positives or false negatives, I presume) by setting a FakeChildParams struct and overwriting its values.  Instead, make a helper function that sets defaults and returns a new struct with new values... or something like this.

### Acceptance criteria
Each block created in default_syncer_test.go, default_store_test.go tests uses its own new FakeChildParams.

### Risks + pitfalls
None

### Where to begin
default_syncer_test.go, probably also default_store_test.go

- [ ]  also fix `fakeChildParams.Nonce = uint64(2)` on line 123
- [ ] in node_tests.go import node as `.`

**Comment by anorth** [comment]
@ZenGround0 and I rewrote these tests to not use shared params.
