### ISSUE TITLE
Replace []byte in submitPoSt with PoStProof and []byte in commitSector with SealProof

### ISSUE THREAD

**Issue by laser** [filecoin-project/go-filecoin#2254]
### Description

PoSt generation produces a proof of a known, fixed length, but is currently represented on chain as a `[]byte`.

PoRep generation produces a proof of a known, fixed length - but is currently represented on chain as a `[]byte`.

### Acceptance criteria

Add a new type called `PoStProof` and update the spec's _Data Structures_ section to include this type. [Modify the `submitPoSt` message](https://github.com/filecoin-project/specs/blob/c60b2a88b7f3c24848f4011c2d7b18dbd3f38cd2/actors.md#submitpost) to include this proof.

Add a new type called `SealProof` and update the spec's _Data Structures_ section to include this type. [Modify the `commitSector` message](https://github.com/filecoin-project/specs/blob/c60b2a88b7f3c24848f4011c2d7b18dbd3f38cd2/actors.md#commitsector) to include this proof.

**Comment by laser** [comment]
@whyrusleeping  - FYI, I'm tracking this work. I should get to it soon.

**Comment by laser** [comment]
This work is blocked on [this spec PR](https://github.com/filecoin-project/specs/pull/192).

**Comment by mishmosh** [comment]
The blocking spec PR https://github.com/filecoin-project/specs/pull/192 is now merged, so moving back to Ready.

**Comment by laser** [comment]
This issue was completed in [this PR](https://github.com/filecoin-project/go-filecoin/pull/2607), which modified the `SubmitPoSt` and `CommitSector` signatures to use the more specific types.
