### ISSUE TITLE
Frequent error creating payment: context deadline exceeded

### ISSUE THREAD

**Issue by muronglaowang** [filecoin-project/go-filecoin#2259]
I set up the p2p connection ,and clear up the message pool
 when I run the go-filecoin client propose-storage-deal < miner >  < data >  < ask >  < duration >
sometimes,Error: error creating payment: context deadline exceeded.
a very few time it store success.  the miner is others.

**Comment by anorth** [comment]
Can you confirm that you've built at the `devnet-user` tag? We have little expectation that things will work otherwise.

**Comment by rosalinekarr** [comment]
Dup of #2210. Closing in favor of that issue.
