### ISSUE TITLE
the new release filecoin-0.0.2-Linux.tar.gz cant run in centos7

### ISSUE THREAD

**Issue by dayou5168** [filecoin-project/go-filecoin#2260]
### Description
when i see new release 
i run it on my server soon 
i fund two problems 

1: mkdir -p /tmp/filecoin-proof-parameters
./paramfetch fetch 
this will get two error. its helpless to run go-filecoin

2:filecoin-0.0.2-Linux.tar.gz cant run in centos7
i got this error
go-filecoin: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by go-filecoin)
maybe this not a bug ,but i think go-filecoin should support more platform!

**Comment by yaohcn** [comment]
i have the same problem in ubuntu16.04

**Comment by chenminjian** [comment]
> 2:filecoin-0.0.2-Linux.tar.gz cant run in centos7
> i got this error
> go-filecoin: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by go-filecoin)
> maybe this not a bug ,but i think go-filecoin should support more platform!

The [article](https://www.jianshu.com/p/d69167a2720e) may help.

**Comment by dayou5168** [comment]
> > 2:filecoin-0.0.2-Linux.tar.gz cant run in centos7
> > i got this error
> > go-filecoin: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by go-filecoin)
> > maybe this not a bug ,but i think go-filecoin should support more platform!
> 
> The [article](https://www.jianshu.com/p/d69167a2720e) may help.

我试试，兄弟，你是中国人吗，加个微信1368615390

**Comment by anorth** [comment]
@gmasgras @ognots can you shed any light here?

**Comment by chenminjian** [comment]
> 我试试，兄弟，你是中国人吗，加个微信1368615390

github is enough. 😊

**Comment by gmasgras** [comment]
The `0.0.2` Linux binary is dynamically linked to `libc6` version `2.27`. 
I recommend either upgrading to `18.04` or compiling `go-filecoin` using these instructions: https://github.com/filecoin-project/go-filecoin/wiki/Getting-Started#installing-from-source

**Comment by sandjj** [comment]
When I run "./paramfetch fetch" command in UBUNTU 18.04,  I have the same problem and there have no more error information. I don't known how can I do next.

**Comment by dayou5168** [comment]
> When I run "./paramfetch fetch" command in UBUNTU 18.04, I have the same problem and there have no more error information. I don't known how can I do next.

i think the document is something wrong

**Comment by anorth** [comment]
At the moment the team is focussed on protocol completeness before broad platform support. It looks like compiling from source is a reasonable workaround to this problem so I'll close the issue now. We're tracking broader architecture support in #2258.
