### ISSUE TITLE
Support non-integer values for message send

### ISSUE THREAD

**Issue by rkowalick** [filecoin-project/go-filecoin#2265]
### Description

Currently, the `--value` option for `message send` only accepts integers. People will likely want to transfer non-integer amounts of FIL, so we should changes this to accept a float-as-string amount of filecoin.

### Acceptance criteria

The ability to send 0.5 filecoin to another address

### Risks + pitfalls

none known

### Where to begin

The `cmdkit.IntOption("value"...)` inside the message send command.

**Comment by ZenGround0** [comment]
Alternatively value could be specified in attofil.
