### ISSUE TITLE
gengen should create real sealed sectors for the miners it creates with non-zero power

### ISSUE THREAD

**Issue by laser** [filecoin-project/go-filecoin#2270]
### Description

The gengen program allows us to create a genesis block containing miners with non-zero power. It does this by:

- Creating a special variant of miner ("bootstrap miner") which does not verify the seal proofs sent to it. The owner of a bootstrap miner will not generate PoSt proofs for sectors it has committed.
- Creating several `commitSector` messages containing bogus proofs and sending them to the newly-created bootstrap miners (to increase their power).

If we created miners using the output of the seal operation and provided those miners with the sealed sector-files, they'd be able to behave just like normally-created miners. This would allow us to delete a bunch of test-only code from the normal code path (`Actor#SubmitPoSt`, `Actor#CommitSector`, et cetera).

### Acceptance criteria

- delete the notion of a bootstrap miner
- no more conditional verification of `CommitSector` message
- no more condition generation of PoSt
- no more conditional verification of `SubmitPoSt` message

### Risks + pitfalls

Sealed sector files must be distributed to miners, and their rust-fil-proofs SectorBuilder metadata must be updated to include the piece-to-sealed-sector-file mappings.

**Comment by laser** [comment]
cc @travisperson and @whyrusleeping

**Comment by phritz** [comment]
this seems like something we need, but why the sudden priority? we have talked at prioritization about this being something we get to just before or even during testnet

**Comment by laser** [comment]
My intent was not to assign it any priority. If I did, it was a mistake. Agree with you about testnet.

**Comment by laser** [comment]
Ah, @anorth placed this ticket in _Candidates_. I will defer to him (but I did just tag it with the `testnet` release).

**Comment by anorth** [comment]
I did. I'm helpdesk this week and instructions are to leave nothing in inbox. I understand that candidates is the priority triage place, and expect it to be moved to backlog during story prioritisation.
