### ISSUE TITLE
CircleCI config is broken

### ISSUE THREAD

**Issue by frrist** [filecoin-project/go-filecoin#2275]
**Describe the bug**
Out circleCI file is invalid, this will prevent all code rebased on master from being tested in CI

**To Reproduce**
From the root of go-filecoin repo run: `circleci config validate`, or just make a branch and push it to for a CI run.

**Failure**:
```
circleci config validate
Error: ERROR IN CONFIG FILE:
[#/parameters/sector_builder_tests_param] 3 schema violations found
1. [#/parameters/sector_builder_tests_param] required key [default] not found
2. [#/parameters/sector_builder_tests_param] required key [type] not found
3. [#/parameters/sector_builder_tests_param] extraneous key [sector_builder_tests] is not permitted
|   Permitted keys:
|     - type
|     - default
|     - description
|     - enum
|   Passed keys:
|     - sector_builder_tests
```

**Expected behavior**
The command passes

**Comment by gmasgras** [comment]
It looks like the `circle/config.yaml` file hasn't changed since Mar 5th. This might be an error on Circle's side.  @ognots

**Comment by rkowalick** [comment]
It looks like a YAML indentation based error. I was mucking around in that part of the config, so I might be able to help

**Comment by ognots** [comment]
closed by https://github.com/filecoin-project/go-filecoin/pull/2279
