### ISSUE TITLE
Extract tipset canonical block ordering and use in all tipset traversals

### ISSUE THREAD

**Issue by anorth** [filecoin-project/go-filecoin#2310]
### Description
The canonical ordering of blocks in a tipset is apparently by ticket bytes. Many places in the code iterate blocks in a tipset either in map range order, or by iterating keys of a  `SortedCidSet`.

Blocks could be considered to lose their identify for many purposes when combined in a tipset: the tipset is more primary. Some block-inspection functionality (e.g. iterating messages) should work with a tipset instead. Tipsets should only permit iteration of blocks in canonical (ticket) order.

See discussions [here](https://github.com/filecoin-project/go-filecoin/pull/2269#discussion_r265564100) and [here](https://github.com/filecoin-project/go-filecoin/pull/2272)

### Acceptance criteria
- [x] TipSet hides its internals and exposes blocks only in canonical order
- [x] Remove use of SortedCidSet for stable ordering of blocks in a tipset
- [ ] Iterate messages in canonical order in callers of `chains.CollectBlocksToCommonAncestor`
- [x] Spec is updated to match: https://github.com/filecoin-project/specs/issues/285
- [x] [bonus] Tipset is immutable

### Risks + pitfalls
- There are probably more than a few places that iterate blocks and/or sorted CIDs.

### Where to begin
- chain/traversal.go (iterators) and core/chains.go (traversal/collection)

**Comment by anorth** [comment]
There could be a time-bomb buried here. The outbound message queue now checks that messages from an address are discovered in nonce order, and will error out of block handling if not. So messages from multiple blocks at the same height that happened to be mined in the right order from the vm's point of view also need to be discovered in the right order by the queue.

So we shouldn't let this one lie: either @ZenGround0 or myself should pick it up soon.

(If you're here because the time bomb went off, the quick fix is probably to remove the nonce sequence assertions in the outbound message queue).

**Comment by shannonwells** [comment]
Looks like some of this may be addressed with Issue #1847, PR #2422

**Comment by anorth** [comment]
@ZenGround0 I'm stealing this, I trust you haven't started on it.

**Comment by anorth** [comment]
`runMessages` in `consensus/expected.go` iterates in CID order, with a TODO to process in ticket order. It calls `ProcessTipSet` in `processor.go`, which does a similar iteration (but the comments lie about it).

So iteration is in fact consistently in CID order at present. We should still fix it.
