### ISSUE TITLE
[bug]it takes too long time for running "go-filecoin miner create"

### ISSUE THREAD

**Issue by dayou5168** [filecoin-project/go-filecoin#2314]
**Describe the bug**
release 0.02 
when i run  go-filecoin miner create 10 100 --price=0 --limit=1000 --peerid `go-filecoin id | jq -r '.ID'` 
it takes too long time even i wait for two hours 
it has no response !
just cant create the miner or the miner id
.

**Comment by rosalinekarr** [comment]
It sounds like you may not have any FIL in your wallet. Can you run the following to let us know what your wallet balance is?

```
export WALLET_ADDR=`go-filecoin wallet addrs ls`
go-filecoin wallet balance ${WALLET_ADDR}
```

**Comment by dayou5168** [comment]
> It sounds like you may not have any FIL in your wallet. Can you run the following to let us know what your wallet balance is?
> 
> ```
> export WALLET_ADDR=`go-filecoin wallet addrs ls`
> go-filecoin wallet balance ${WALLET_ADDR}
> ```
balance is 1000
i do this so many times

**Comment by rosalinekarr** [comment]
Ok, this is definitely a bug then. @dayou5168, can you please least all the steps you took to get this error so we can reproduce it?

Also, @rkowalick, would you mind digging into this problem?

**Comment by dayou5168** [comment]
> Ok, this is definitely a bug then. @dayou5168, can you please least all the steps you took to get this error so we can reproduce it?
> 
> Also, @rkowalick, would you mind digging into this problem?

i create miner successfully yesterday, i think its not a bug ,
but i found i must wait for so long time when i want mining
i wait two days for FIL
wait one day for create minner
thats what hapen to me 
hope this infomation is userfull

**Comment by rkowalick** [comment]
@dayou5168 It should take like 9+ hours to sync the current user dev net chain, so it makes sense that it seems like nothing would be happening. It's best to make sure you are synced before doing anything. The easiest way to do that right now is to run

```
go-filecoin show block $(go-filecoin chain head | jq .[0]['"/"'] | tr -d \")
```

and looking at the "Height". A synced chain should have the same height as what is displayed on https://stats.kittyhawk.wtf/storage/mining

**Comment by dayou5168** [comment]
> @dayou5168 It should take like 9+ hours to sync the current user dev net chain (_NOTE_ optimizing this is actively being work on), so it makes sense that it seems like nothing would be happening.
> 
> It's best to make sure you are synced before doing anything. The easiest way to do that right now is to run
> 
> ```
> go-filecoin show block $(go-filecoin chain head | jq .[0]['"/"'] | tr -d \")
> ```
> and look at the "Height". A synced chain should have the same height as what is displayed on https://stats.kittyhawk.wtf/storage/mining

@rkowalick 
i follow you steps and got this
" 
Block Details
Miner:  fcquv2uu892jyd6eglvrek7mpd6gnm8au38hz6g2n
Weight: 954880.647
Height: 60904
Nonce:  0 "
and i see https://stats.kittyhawk.wtf/storage/mining
find there height is 60887
whats that means?

**Comment by rkowalick** [comment]
The most likely explanation for that is the ~5 minute delay for updates to storage mining dashboard. I would definitely consider that `synced`

**Comment by rkowalick** [comment]
@dayou5168 I'm closing this. If you have any more questions, feel free to comment or reopen the issue.
