### ISSUE TITLE
Update Dockerfiles to use go 1.12.1

### ISSUE THREAD

**Issue by rkowalick** [filecoin-project/go-filecoin#2322]
### Description

#2308 has been merged and go-filecoin no longer supports go 1.11.X. We need to update our docker files to use go 1.12.1. 

### Acceptance criteria

All of the Dockerfiles in go-filecoin can build go-filecoin

### Risks + pitfalls

None known

### Protocol Changes

None

### Where to begin

The Dockerfiles (not containing `.ci`)

**Comment by cgwyx** [comment]
Install and run docker of filecoin https://hub.docker.com/r/cgwyx/go-filecoin
