### ISSUE TITLE
run high-level functional test (submitPoSt, commitSector, verification) against nightly devnet each morning

### ISSUE THREAD

**Issue by laser** [filecoin-project/go-filecoin#2329]
### Description

This story is a stub.

### Acceptance criteria

We need some test which:

1. creates a miner
1. stores a piece or two with that miner, causing it to seal the piece into a sector
1. retrieves a piece from that miner
1. verifies that the `commitSector` message appeared on chain
1. verifies that the `submitPoSt` message appeared on chain

### Where to begin

The existing `functional-tests/retrieval` is nearly what we want. This new test should be able to share a lot of code with the existing retrieval test, with some exceptions:

1. We'll need to create a new address instead of importing a keypair produced by gengen
1. We'll need to hit the faucet for FIL
1. We probably won't need to create a bootstrap miner (as the devnet should already have one running... right?)

**Comment by phritz** [comment]
if it is an easier first step we can run this test as part of cluster deployment. there is huge value in verifying the cluster is wai once it comes up. it is also valuable to ensure that it stays running, but that first verification has the most value.

**Comment by gmasgras** [comment]
PR here: https://github.com/filecoin-project/go-filecoin-infra/pull/227

**Comment by anorth** [comment]
@travisperson this ancient issue and PR look like they'll be made redundant by your FAST work, which is a more robust foundation. Please close both if you agree.
