### ISSUE TITLE
provide a command which removes a piece of content from the node's block store by cid

### ISSUE THREAD

**Issue by laser** [filecoin-project/go-filecoin#2345]
### Description

The `client import` command, required in order to consummate a storage deal with a miner, imports a piece into the node's block store for purposes of transferring the piece to the miner (see also: block _service_ and bitswap exchange).

After the storage deal is completed and the piece has been transferred, the client needs a command which it can use to evict from its block store.

I propose the following command be added to the go-filecoin CLI:

```
14:18 $ ./go-filecoin storage rm --help
USAGE
  ./go-filecoin storage rm <cid> - Remove content from local storage.

SYNOPSIS
  ./go-filecoin storage rm [--] <cid>

ARGUMENTS

  <cid> - CID of data to remove from local storage.

DESCRIPTION

  Removes a piece of content with a given CID from the node's block store.
```

### Acceptance criteria

- initialize a new go-filecoin repository in `~/.filecoin`
- run `du -h ~/.filecoin/` and record the directory size
- `dd if=/dev/urandom of=/tmp/somefile  bs=1024 count=70000`
- start the daemon
- run `IMPORTED_CID=$(client import < /tmp/somefile)`
- run `du -h ~/.filecoin/` and verify that directory size increased
- run `./go-filecoin storage rm ${IMPORTED_CID}`
- run `du -h ~/.filecoin/` and verify that directory size decreased

**Comment by acruikshank** [comment]
Clarification: This command might have lots of general purpose uses, but the main problem it solves is that a storage client might use their blockstore to send a piece of content to a storage miner and (once retrieval is modified to use bitswap) use the same blockstore to retrieve that content. If the user has not evicted the content in between, no content will be transmitted during retrieval and a lot of storage miner functionality will go untested (sealing, decoding, etc).

So this command is needed in the near term for correctness in testing. Specifically it blocks converting the retrieval protocol to bitswap.

**Comment by anorth** [comment]
After extraction of the storage market/miner modules, there will be no piece data in the node's blockstore.
