### ISSUE TITLE
retrieval flow should use a bitswap-backed block service to move user piece-bytes from retrieval miner to retrieval client

### ISSUE THREAD

**Issue by laser** [filecoin-project/go-filecoin#2346]
### Description

Today, a retrieval client initiates the retrieve-piece-for-free flow by sending a `RetrievePieceRequest` CBOR-encoded Go struct to the retrieval miner. This request contains the CID of the piece to be unsealed and sent back to the retrieval client.

If the retrieval miner does have this CID in a sealed sector which it manages, the sealed sector will be unsealed. The the piece's bytes will be buffered into memory, the buffer will be chunked, and each chunk will be sent from miner to client over a libp2p stream. The client will concatenate the chunks (in memory) and stream the complete file to stdout.

The existing file transfer mechanism requires unnecessary buffering on the client and is not particularly resilient to network partitions. We should instead use a bitswap exchange-backed block service to facilitate piece bytes-transfer between retrieval client in miner - much like we do between storage client and miner.

### Acceptance criteria

User piece-bytes flow from retrieval miner to retrieval client using bitswap instead of the `/fil/retrieval/free/0.0.0` protocol.

### Protocol Changes

None required.

### Where to begin

I suggest the following:

- client sends miner a `RetrievePieceRequest` request on `/fil/retrieval/free/0.0.0` libp2p stream
- `RetrievePieceRequest` contains CID of content to be unsealed and retrieved
- miner unseals piece and writes piece-bytes to local block store (wrapped by block service, presumably)
- miner sends OK message to client
- client attempts to get piece with CID from local bitswap-backed block service (using `dag.FetchGraph(ctx, PIECE_CID, dag.NewDAGService(BLOCKSERVICE_OF_NODE))`, which broadcasts ask to peers
- miner is a peer, so it sends client the requested content
- client closes libp2p stream and emits `GetPorcelainAPI(env).DAGCat(req.Context, CID)`

**Comment by jnthnvctr** [comment]
Just a flag - this is something the Subvisual folks, @frrist  and I were discussing as a potential issue.

We're working through a web app where users can upload files to a service that will store them on Filecoin. Users can upload a number of files, those files get zipped, stored on Filecoin and can be retrieved at a later stage. 

Given that the data is stored in memory on retrieval (i.e. in memory), the Subvisual guys flagged that this might cause OOM errors on a miner if a sufficient number of users were requesting data simultaneously from a single miner.

**Comment by anorth** [comment]
Retrieval responsibility will move to the storage miner/market modules.
