### ISSUE TITLE
[bug] nightly devnet failed to boot due to param name change

### ISSUE THREAD

**Issue by gmasgras** [filecoin-project/go-filecoin#2349]
**Describe the bug**
Running `go-filecoin wallet addrs ls` seems to be no longer supported.
```
++ docker exec filecoin-1 go-filecoin --repodir=/var/local/filecoin wallet addrs ls
Error: Unknown Command "addrs"
```

**Expected behavior**
Able to list addresses

**Comment by travisperson** [comment]
Ah ya I remember seeing the PR (#2295) that removed that but it totally escaped me to check the setup script. Should be an easy fix, `go-filecoin wallet addr` and `go-filecoin address` are aliases of each other so we should be able to easily swap it over.

**Comment by gmasgras** [comment]
infra fix here: https://github.com/filecoin-project/go-filecoin-infra/pull/192
