### ISSUE TITLE
next steps for application architecture & technical debt

### ISSUE THREAD

**Issue by phritz** [filecoin-project/go-filecoin#2352]
Background: in https://github.com/filecoin-project/go-filecoin/issues/1223#issuecomment-433764709 we realized that we needed to bust up our god object, the node. The epic 
https://app.zenhub.com/workspaces/filecoin-5ab0036a12f8e82ae4ed60f0/issues/filecoin-project/go-filecoin/1469 tracked the work required to eliminate the node api in favor of an api that does not depend on the node but on the narrower set of actual dependencies that implementations need. The end result is an architecture more or less like https://github.com/filecoin-project/go-filecoin/blob/a603886379fe17de50f26297bc5790d352c87e26/CODEWALK.md#architecture-overview, but with protocol apis sitting between commands and protocols. 

This issue is to capture work that further improves the application architecture, as well as generalized state dump on technical debt. Here is what I see at this moment, which could be wrong now and will definitely be wrong in the future given changing circumstances, in rough order of priority:

- consensus block mining needs to be centralized. the implementation is smeared between node/ and mining worker (https://github.com/filecoin-project/go-filecoin/blob/c88b3ef57892d6c8ea16108052b328dcecd30928/node/node.go#L752). a majority of the remaining complexity on node has to do with consensus block mining bookkeeping, eg https://github.com/filecoin-project/go-filecoin/blob/c88b3ef57892d6c8ea16108052b328dcecd30928/node/node.go#L752. we should move the consensus block mining protocol from node/ and mining/ into protocol/mining/block (or blockmining is probably better). in doing so i think we can likely greatly simplify the implementation and book keeping. once this happens the only things that node does is construction of all the dependencies and hooking up of inputs and outputs like the output of consensus block mining to the chain syncer and new blocks from the network to the syncer. this is fine, tho at some point we should clean up construction (see a few below).
- retrieval is the simplest thing and needs to be updated: it doesn't take payments, it always unseals, there is no caching, there is no content locating/market, etc. 
- i think https://github.com/filecoin-project/go-filecoin/issues/1847 i think is worth doing. it is really natural for people to want to filter the chain in different ways, eg https://github.com/filecoin-project/go-filecoin/pull/1755 which tries to add an interface to the chain reader to iterate all blocks since a given height. we should move blockhistory out of the chian reader interface https://github.com/filecoin-project/go-filecoin/blob/c88b3ef57892d6c8ea16108052b328dcecd30928/chain/default_store.go#L393 and have a traversal thingy that knows how to use the more fundamental interfaces in 1847 to iterate the chain. then consumers can create their own iterators that filter according to their own needs. i think we have the building blocks in https://github.com/filecoin-project/go-filecoin/blob/c88b3ef57892d6c8ea16108052b328dcecd30928/chain/default_store.go#L393. 
- speaking of which, the chain syncer is known to be a mess and needs to be overhauled, i believe https://github.com/filecoin-project/go-filecoin/issues/2128 references this. i think there is a new implementation in spec we could replace it with?
- vm implementation i think could be greatly simplified. we dont need fancy reflective sugar like this to pretend like we are an actual vm: https://github.com/filecoin-project/go-filecoin/blob/288345b503a54ed0be1ad982e19d02d38bd4de9b/actor/export.go#L23. we could just have a map of method names to implementations and it would be far easier to understand. error handling in the vm should be simplified too, eg maybe returning success, rollback, fault, perm failure, temp failure instead of various revert errors that have to mapped to various conditions. zero actors use return values btw, and there are very few exit codes in use. i have to think this could/should be slimmed down for testnet if for no other reason than to make it easier for other implementations to implement. 
   - related https://github.com/filecoin-project/go-filecoin/issues/1714  and https://github.com/filecoin-project/go-filecoin/issues/1754
- there are roughly 200 TODOs in the code, who knows what they hide
- the https://github.com/filecoin-project/go-filecoin/issues?q=is%3Aissue+is%3Aopen+label%3AC-technical-debt, https://github.com/filecoin-project/go-filecoin/issues?q=is%3Aopen+is%3Aissue+label%3A%22I-security+%3Awarning%3A%22 and https://github.com/filecoin-project/go-filecoin/issues?q=is%3Aopen+is%3Aissue+label%3AI-scaling labels should reveal a decent amount of work, and i think we should be more rigorous with labeling security and scaling issues this way
- the way all our dependencies and apis are constructed isn't very principled. we have config https://github.com/filecoin-project/go-filecoin/blob/c88b3ef57892d6c8ea16108052b328dcecd30928/node/node.go#L173, and init https://github.com/filecoin-project/go-filecoin/blob/c88b3ef57892d6c8ea16108052b328dcecd30928/node/init.go#L23, and test opts https://github.com/filecoin-project/go-filecoin/blob/c88b3ef57892d6c8ea16108052b328dcecd30928/node/testing.go#L38 that do similar things. given the way the constructor works https://github.com/filecoin-project/go-filecoin/blob/c88b3ef57892d6c8ea16108052b328dcecd30928/node/node.go#L323 there is no way to selectively swap out dependencies in a principled way, eg if you want to replace say the message pool or the block/message fetcher in a node or in core apis for some reason for testing or running locally. a builder that managed dependencies in a more principled fashion could help make this easier, though i guess we would have to convince ourselves the cost is worth the benefit. 
- we could have directories more closely map to our application architecture: https://github.com/filecoin-project/go-filecoin/issues/2148

i will add more to this as it run into it

cc @anorth

**Comment by phritz** [comment]
- i have heard lots of grumble grumble about badger as our underlying key/value store. dig, why, or someone on ipfs will have more state

**Comment by phritz** [comment]
- we should consider moving to structured output for all our commands

**Comment by ZenGround0** [comment]
* TODO taken from node_test.go `TestNodeStartMining`: we need a principled way to construct an API that can be used both by node and by tests. It should enable selective replacement of dependencies.
