### ISSUE TITLE
[bug] query-storage-deal always return Status: staged

### ISSUE THREAD

**Issue by yangjian102621** [filecoin-project/go-filecoin#2355]
Well i run the command :

```bash
go-filecoin client query-storage-deal {dealId}
```
it always return the following message 

```
Status: staged
Message:
```
I can not retrieve it.  i check the wiki document [Storing-on-Filecoin](https://github.com/filecoin-project/go-filecoin/wiki/Storing-on-Filecoin)

> Your data is automatically transferred to a staging area via the underlying bitswap mechanism (implementation from IPFS) of Filecoin. Miners will now be required to store your files on their machines and begin the sealing/proving process. Under the hood, filecoin miners automatically fire off a sealing process at some configured interval (default 120 seconds) to take all data in the miner's staging area and seal it into the miner's pledged storage sectors. Your deal status will move to "staged" at this point. After sealing is complete and the miner posts its commitment to the chain your deal status will move to "posted". 

My question is whether the seal process is done automatically? If it is not, what should i do to make the state of deal to `posted`.

Note: both the miner node and client node are my nodes.

@travisperson 

Thanks.

**Comment by rosalinekarr** [comment]
@yangjian102621, can you provide a list of steps to reproduce this error including how you setup your node, which devnet you're connecting to, and your operating system?

@travisperson, would you mind shepherding this issue until it's resolved?

**Comment by travisperson** [comment]
> My question is whether the seal process is done automatically?

There is a default configuration of 120 seconds, so your miner should start the sealing process 120 seconds after you proposed the deal. The sealing process itself can take a while depending on your system. On a stock i7-9700K (3.6GHz) I average 7 minutes, on an i7-8550U (1.8GHz), I average 20 minutes (these are for the 256MiB sectors, the 1KiB sectors should only take a few minutes on most average hardware).

**Comment by yangjian102621** [comment]
## My system configuration
CPU: Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz
RAM: 8GB
OS: Ubuntu 18.04.1 LTS

## Here are my steps on node1
1. Initialize node: `go-filecoin init --devnet-user --genesisfile=http://user.kittyhawk.wtf:8020/genesis.car`
2. Run the daemon: `go-filecoin daemon`
3. Creating the miner : `go-filecoin miner create 10 100 --price=0 --limit=1000 --peerid `go-filecoin id | jq -r '.ID'`
4. Start mining `go-filecoin mining start`
5. Create ask order: 
```bash
export MINER_ADDR=`go-filecoin config mining.minerAddress | tr -d \"`
export MINER_OWNER_ADDR=`go-filecoin miner owner $MINER_ADDR`
go-filecoin miner set-price --from=$MINER_OWNER_ADDR --miner=$MINER_ADDR --gas-price=0 --gas-limit=1000 0.000000001 2880
```
**Then i run `propose-storage-deal` on the other node(node2). here is my steps:** 
1 - 4 steps is the same as node1 
Note: node1's miner address is : fcqdzp28x8vnph7aedzw3pwlpwrnxjh77zayx75c5

step 5, search the ask orders for miner address `fcqdzp28x8vnph7aedzw3pwlpwrnxjh77zayx75c5`

```bash
go-filecoin client list-asks --enc=json |grep "fcqdzp28x8vnph7aedzw3pwlpwrnxjh77zayx75c5" |jq
``` 
and it return 2 records 

```
{
  "Miner": "fcqdzp28x8vnph7aedzw3pwlpwrnxjh77zayx75c5",
  "Price": "0.01",
  "Expiry": 66271,
  "ID": 3,
  "Error": null
}
{
  "Miner": "fcqdzp28x8vnph7aedzw3pwlpwrnxjh77zayx75c5",
  "Price": "0.001",
  "Expiry": 53372,
  "ID": 8,
  "Error": null
}
```
step 6: storing file to network

```bash
export CID=`go-filecoin client import ~/hello.txt`
go-filecoin client propose-storage-deal fcqdzp28x8vnph7aedzw3pwlpwrnxjh77zayx75c5 $CID 3 100
```
Note: `hello.txt` is less than 4KB in size, and i `replication-name` to make `proof.json` with the `hello.txt` just taken a few seconds.

But a few days have passed, the state of my deal is still `staged`.

One more thing @travisperson , i build a custom net according to the steps of issue #2294,  excute the above steps, **i got the same result.**

1. Run the master node according your steps.

> $ ./go-filecoin init --genesisfile=./fixtures/genesis.car
$ ./go-filecoin daemon
$ mineraddr=$(jq -r '.Miners[0].Address' ./fixtures/gen.json)
$ peerid=$(./go-filecoin --enc=json id | jq -r '.ID')
$ ./go-filecoin config mining.minerAddress $mineraddr
$ walletaddr=$(./go-filecoin --enc=json wallet import ./fixtures/0.key | jq -r '.Addresses[0]')
$ ./go-filecoin config wallet.defaultAddress $walletaddr
$ ./go-filecoin miner update-peerid --from $walletaddr --gas-price 0 --gas-limit=300 $mineraddr $peerid
$ ./go-filecoin mining start
$ ./go-filecoin wallet balance $walletaddr

 2. setup 2 nodes use the same genesisfile(on the another machine, and i copied the same `go-filecoin`)

```
go-filecoin init --genesisfile=./fixtures/genesis.car
go-filecoin daemon
go-filecoin swarm connect {master_node_id}
```
Next, create a miner, create an order... are the same as above.

Is there any step go wrong? I hope you can help analyze it. Thank you.

**Comment by deltazxm** [comment]
兄弟试试这个，go-filecoin client propose-storage-deal fcqdzp28x8vnph7aedzw3pwlpwrnxjh77zayx75c5 $CID 8 100

**Comment by yangjian102621** [comment]
@deltazxm 
存不上去，报错： 
Error: error creating payment: context deadline exceeded

**Comment by travisperson** [comment]
Did the mining machine also have 8GB of ram? I can say that the size of the file has little to do with how much memory might be consumed though. Sectors are always padded out to the full size, so a 4KB file will still use the full 256MiB sector size.

> So What is the minimum amount of memory needed to get the machine to complete the seal process properly

We don't really have any good numbers for system requirements. The 8GB number in the README is a best guess. We do currently have some sort of memory issue which you might be running into, and the process of sealing might be pushing the system resources over the edge.

You may try running all of the nodes with the environment value `FIL_USE_SMALL_SECTORS=true` (when running a private chain) just to verify that you can move through the workflows you want.
