### ISSUE TITLE
create a precompiled binary-release flow for bls-signatures

### ISSUE THREAD

**Issue by laser** [filecoin-project/go-filecoin#2361]
### Description

For background, see [this thread](https://github.com/filecoin-project/go-filecoin/issues/2292#issuecomment-474476863).

It is currently the case that a developer must have Rust (and rustup) installed in order to build go-filecoin. This is the case because the `bls-signatures` dependency does not provide a precompiled binary, and the `bls-signatures` project requires rustup.

We should build a precompiled binary release flow for the `bls-signatures` project so that go-filecoin developers don't need the Rust (and rustup) toolchain installed to build go-filecoin.

### Acceptance criteria

Build a release flow for `bls-signatures` using the template provided by `rust-fil-proofs`.

1. Each successful CI build of `bls-signatures` should produce a new GitHub release containing precompiled `bls-signatures` assets
1. go-filecoin's `install-bls-signatures.sh` script should support a `FILECOIN_USE_PRECOMPILED_BLS_SIGNATURES` environment variable

**Comment by sidke** [comment]
resolved with this merge:
https://github.com/filecoin-project/go-filecoin/pull/2368
