### ISSUE TITLE
Serious performance issues when storing a file of 4KB

### ISSUE THREAD

**Issue by pengxiankaikai** [filecoin-project/go-filecoin#2375]
**Describe the bug**

Test the storage between the two nodes. After the storage is successful, the storage node receives the dealid, and the load of the miner node suddenly rises to CPU: 400%, RAM: 40%, and the node stops after running for a while.

error info:
Mar 21 11:18:32.492 INFO Actually generating groth params., id: zigzag-proof-of-replication-733b035c440d8b0e4a03ab5e4c58553b6c674cc64bd6a130e8764f7abeb38f69, target: params, place: storage-proofs/src/parameter_cache.rs:127 storage_proofs::parameter_cache, root: storage-proofs
memory allocation of 100663296 bytes failedAborted (core dumped)

CPU ：
4  Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz
RAM：
8G

storage file size:
4K

**Comment by dayou5168** [comment]
i got this error yesterday, sometimes go-filecoin will cost all 8GB RAM then quit the daemon。
i think you shoud  increase you RAM and test again.

**Comment by pengxiankaikai** [comment]
@dayou5168 Yes, I am also ready to increase memory and test again.

**Comment by dayou5168** [comment]
> @dayou5168 Yes, I am also ready to increase memory and test again.

do you have wechat

**Comment by rosalinekarr** [comment]
This is absolutely a problem, but since it doesn't technically break behavior, I'm going to mark it as a technical debt and scaling issue rather than a bug. We'll be sure to look into this problem as soon as we can.

**Comment by mishmosh** [comment]
@pengxiankaikai at what commit did you clone & build go-filecoin?

https://github.com/filecoin-project/go-filecoin/pull/2285 was recently integrated which might affect storage performance.

**Comment by travisperson** [comment]
> Actually generating groth params

I believe this means you do not have the filecoin proof params on your system. You will need to have them installed to avoid this lengthy generation step.

Additional details (one asked by mishmosh) will help determine how to get the right parameters for you. If by chance you are running the latest code from master, you can run the install script.

```
go-filecoin $ ./scripts/install-filecoin-parameters.sh
```

These should have been installed by running `deps`, but if your `/tmp` is backed by a tmpfs, you will lose the download / generated parameters after a restart.

**Comment by pengxiankaikai** [comment]
@dayou5168 wechat: pengxiankaikai

**Comment by pengxiankaikai** [comment]
@mishmosh Thanks! I am using releases 0.0.2 .

**Comment by travisperson** [comment]
@pengxiankaikai that release includes a `paramfetch` binary. You can run it to download the required proof params for the release.

```
$ ./paramfetch fetch -a
```

The `paramfetch` binary consumes the `parameters.json` file, and downloads the key-value pairs listed in the file. The `value` represents the IPFS hash of the parameter and the `key` is the filename. The parameters need to be installed under `/tmp/filecoin-proof-parameters/`.

The `paramfetch` binary should handle this for you. If it does not work (failure to resolve from the gateway) you can manually download them through IPFS and placing them in the correct location as describe above.

**Comment by pengxiankaikai** [comment]
Thank you for your answer, I updated the new binary package and completed the file upload operation.

```
root@xjxh-hongkong-pro:~# go-filecoin client query-storage-deal $DEALID
Status: posted
Message:
```
