### ISSUE TITLE
new wallet address  is wrong

### ISSUE THREAD

**Issue by muronglaowang** [filecoin-project/go-filecoin#2387]
I used the new release, 
i ran  go-filecoin address ls
t1wudlbbs4lilmrj6bmdlht2cnkg4xvrmb62g3fsq

used the address on http://user.kittyhawk.wtf:9797/
Error: Failed to parse target address t1wudlbbs4lilmrj6bmdlht2cnkg4xvrmb62g3fsq invalid character

**Comment by rosalinekarr** [comment]
Which version of the project are you running? There are some differences in address format between versions, and this problem can occur if you're running a different version than the devnet you're connecting to.
