### ISSUE TITLE
Daemon from different commit can join devnet

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/go-filecoin#2393]
**Describe the bug**
The release checklist asserts that it should be the case that "you cannot connect a binary built at a different commit to this devnet".  I connected a binary with version `6c1fbaf5eb0e6d12987611ae72bf576f7dfd1654` to a devnet running version `b87348b354d8ffea5309cb6e395fdc82d0a9eef1`

**To Reproduce**
start a node at version `6c1fbaf5eb0e6d12987611ae72bf576f7dfd1654`, this was just what my latest build was.  (could it be it didn't have the needed patches to prevent it from joining a different network?)

**Expected behavior**
I thought joining this network would have failed

**Screenshots**
If applicable, add logging output or screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser 
 - Version: 6c1fbaf5eb0e6d12987611ae72bf576f7dfd1654

**Additional context**
This commit was from last week so maybe it was too old to have the gatekeeping changes.  I looked in the log history quickly and couldn't find changes between it and the devnet commit that would have introduced the change however.

**Comment by ZenGround0** [comment]
cc @phritz

**Comment by phritz** [comment]
i'm on it
