### ISSUE TITLE
surface auto seal interval in plumbing and with a command

### ISSUE THREAD

**Issue by phritz** [filecoin-project/go-filecoin#2394]
we should surface auto seal setting in plumbing, eg in a protocolparams plumbing call like https://github.com/filecoin-project/go-filecoin/issues/1932. all params can just be returned in one struct for now

**Comment by rosalinekarr** [comment]
@anorth @phritz Isn't this already surfaced with `ConfigGet`/`ConfigSet` in plumbing and `go-filecoin config` in commands?

The following lines can get and set auto seal interval in the CLI:

```
# To Get:
go-filecoin config mining.autoSealIntervalSeconds

# To Set:
go-filecoin config mining.autoSealIntervalSeconds 120
```

And the following lines in plumbing:

```
// To Get:
plumbing.ConfigGet("mining.autoSealIntervalSeconds")

// To Set:
plumbing.ConfigSet("mining.autoSealIntervalSeconds", 120)
```

**Comment by phritz** [comment]
yeah, but that seems like an implementation detail and there are going to be quite a number of protocol and other parameters that might live eg in code and the thinking was we should have a principled way to surface them...

**Comment by anorth** [comment]
See discussion in #884. We will probably move most protocol parameters to configuration, but still need an accessor for them as a group, distinct from other configuration.
