### ISSUE TITLE
the chain head command is lack test coverage

### ISSUE THREAD

**Issue by frrist** [filecoin-project/go-filecoin#2398]
### Description
During the implementation of https://github.com/filecoin-project/go-filecoin/pull/2396 we noticed that there is basically no test coverage for the `chain head` command, we need to have coverage around this. 

### Acceptance criteria
- test for json encoding
  - 1 block in tipset
  - many blocks in tipset
  - null block tipset
- test for text encoding
  - 1 block in tipset
  - many blocks in tipset
  - null block tipset
- test for json round trip
  - can encode the result of `chain head --enc=json` into a json object representing a slice of CID's 

### Where to begin
https://github.com/filecoin-project/go-filecoin/blob/master/commands/chain.go#L27

**Comment by phritz** [comment]
added to high priority fixes epic

**Comment by rkowalick** [comment]
Working on this, pending a discussion with @ZenGround0 (or anyone else) who can help me to set up a test daemon whose chain head has a tipset with multiple blocks.

**Comment by ZenGround0** [comment]
Reposting this here:

> Right now to do this you would need to muck around in the internals of the leader election mechanism in the test daemon's consensus component such that you were sure that both daemons would win an election
And after ensure this have both daemons mine one block on top of the same base
Doing this should get the chain in the right state on all daemons by default
the trickiest thing is getting the consensus to elect them both.
However it might be the case that test daemons always win elections
I am not sure the level of mocking going on in mining atm

**Comment by rkowalick** [comment]
In response to the above difficulties, I have simply made a round trip test for both `text` and `json` encodings. I'm pretty sure there is also no such thing as a "null" chain head, so that was also skipped.
