### ISSUE TITLE
Make wording of error message for code version mismatch clearer

### ISSUE THREAD

**Issue by rkowalick** [filecoin-project/go-filecoin#2403]
### Description

The current error message for a code version mismatch is

```
code not at same version: <SHA_FROM_PEER> does not match <SHA_OF_LOCAL_NODE>, disconnecting from peer: ...
```

It is not clear from the error message which SHA is which.

### Acceptance criteria

Rewording the error message to something like

```
code not at same version: peer has version <SHA_FROM_PEER>, daemon has version <SHA_OF_LOCAL_NODE>, disconnecting from peer: ...
```

### Risks + pitfalls

None

### Protocol Changes

None

### Where to begin

hello.go error message.

**Comment by Daniel-Wang** [comment]
Hey @rkowalick, I would like to fix this issue!

**Comment by rkowalick** [comment]
@Daniel-Wang Thank you so much! Merged and closed!

**Comment by cgwyx** [comment]
My testing  also is error message for a code version mismatch.

**Comment by rkowalick** [comment]
@cgwyx You should not see that error message if you are using the correct version of filecoin. Please follow the instructions in the wiki here https://github.com/filecoin-project/go-filecoin/wiki/Getting-Started#installing-from-binary . If you are still having problems, feel free to open a separate issue.
