### ISSUE TITLE
we have no deployment tests for the block explorer 

### ISSUE THREAD

**Issue by phritz** [filecoin-project/go-filecoin#2404]
While vetting the 0.1 release we discovered that chain head was returning blocks and not cids https://github.com/filecoin-project/go-filecoin/issues/2392. This silently broke the block explorer https://github.com/filecoin-project/filecoin-explorer/issues/8. We discovered this by manual testing. We should have test that catches breakages, eg if the block explorer returns a non-200. This "test" could run at the end of deployment and emit an ERROR log or it could run like a regular CI test earlier, whatever works.

**Comment by anorth** [comment]
cc @mslipper @mishmosh @ognots 

The explorer is an important part of the user devnet so we should consider it as a primary item in our periodic releases. I would like us to be able to keep it in sync with go-filecoin but with minimal drag on gfc development, which implies some kind of regular, automated testing.

**Comment by travisperson** [comment]
I've written up an issue for this in the filecoin-explorer repo: https://github.com/filecoin-project/filecoin-explorer/issues/11

**Comment by anorth** [comment]
This is still an issue, but work is in progress and this isn't the right place to track it.
