### ISSUE TITLE
[bug] flaky OSX tests (FAST)

### ISSUE THREAD

**Issue by gmasgras** [filecoin-project/go-filecoin#2413]
**Describe the bug**
The latest MacOS build failed:
```
Test:       	TestRetrieval
FAIL
FAIL	github.com/filecoin-project/go-filecoin/tools/fast/tests	160.246s
```
https://circleci.com/gh/filecoin-project/go-filecoin/13283

**Comment by travisperson** [comment]
I'm going to close as I haven't heard of any frequency as a few things have changed that may of mitigated this. I think #2469 may help here.

If we see it again let reopen and I'll try to investigate further.
