### ISSUE TITLE
Change timeout of commitSector/SubmitPoSt in retrieval script when using normal-sized sectors

### ISSUE THREAD

**Issue by rkowalick** [filecoin-project/go-filecoin#2415]
### Description

The retrieval test functional script currently times out if one sets the nodes to use normal-sized sectors (as opposed to the default small-sized sectors). This is due to a timeout of only 120 seconds when waiting for the commitSector and SubmitPoSt messages to appear on chain. According to @laser, these timeouts should be 3600 seconds when using normal-sized sectors.

### Acceptance criteria

The retrieval script works reliably when using normal-sized sectors.

### Risks + pitfalls

None

### Protocol Changes

None

### Where to begin

The calls to `wait_for_message_in_chain_by_method_and_sender` in `functional-tests/retrieval`

**Comment by laser** [comment]
@rkowalick - Nice find. 3600 seconds should be appropriate for large-sized sectors on a developer's laptop. 120 has been working for small-sized sectors.

**Comment by phritz** [comment]
we should surface sector size in plumbing and via a command https://github.com/filecoin-project/go-filecoin/issues/1932, and we should use this in the script instead of hardcoding so that when things like #2110 change it does the right thing

**Comment by rkowalick** [comment]
@phritz I definitely closed this and did not acknowledge your comment. I do feel like there are some problems with a command that exposes sector size, as commented in #1932 . I would definitely love #2110 though.
