### ISSUE TITLE
follow up on multiple submitpost message issue during 0.1 launch

### ISSUE THREAD

**Issue by phritz** [filecoin-project/go-filecoin#2418]
During release vetting we found https://github.com/filecoin-project/go-filecoin/issues/2406, an instance where multiple submitpost messages caused mining to stop in the devnet. The issue is that the second submitpost caused the proving period to advance far into the future and we faulted when we were unable to sample randomness from those non-existent blocks. We did not root cause but we did paper this over with 
- https://github.com/filecoin-project/go-filecoin/pull/2408 which properly stops mining when any error is received on the output channel 
- https://github.com/filecoin-project/go-filecoin/pull/2409 which treats errors from chain randomness sampling as reverts instead of faults, meaning that all state changes will be reverted and the message will go on chain and the node will not stop mining or infinitely loop when they are hit. 

2408 isn't quite right because not all errors are surfaced to the caller. 2409 is not quite right because it treats all faults like reverts, even things that really should be faults. I think to clean this up we need to:
- ensure that all errors are surfaced to the caller via the output channel
- in miner.submitpost validate the incoming submitpost message so that we dont attempt to process submitpost messages that don't make sense. at minimum before verifying the post we should check that the proving period is not too far in the past and is not for a block of height greater than what we have (right @ZenGround0 ?). If we apply this validation logic early in the submitpost implementation we can then change chain randomness errors as faults again. That is, if the submitpost does not look valid because proving period is too far in the past or future return a revert error, and if chain randomness sampling returns an error treat that as a fault. We should never get the fault from chain randomness sampling because validation should prevent us from getting there.
- the above logic has to be sensitive to re orgs and lookback
- we should check that generation does not have this same problem
- (maybe?) send to the output channel via go routine, right now it blocks on the receiver

**Comment by anorth** [comment]
Ancient history.
