### ISSUE TITLE
prevent filecoin nodes with incompatible protocol parameters from interoperating

### ISSUE THREAD

**Issue by phritz** [filecoin-project/go-filecoin#2421]
we currently prevent binaries built at a different commit from interoperating with the test and user devnets via the hello protocol https://github.com/filecoin-project/go-filecoin/blob/8158fdfb572e7fdcbd98b42a2e83912b1b4f097e/protocol/hello/hello.go#L116. this is a specific case of a more general problem: filecoin binaries with incompatible protocol parameters are going to experience undefined behavior when interoperating, eg if one has large sectors configured and another has small. 

we should have a mechanism that prevents filecoin nodes with different protocol parameters from interoperating

**Comment by phritz** [comment]
related, we're adding plumbing/commands to get protocol params, maybe this is the same struct:
#1932  #2394

**Comment by acruikshank** [comment]
We should probably sync these in a similar manner to the way we sync genesis blocks. This means that the parameters would be bundled in some data structure that would be retrieved on init. The data structure could be content addressed, and this Cid could be compared in the hello protocol.

**Comment by phritz** [comment]
related: https://github.com/filecoin-project/go-filecoin/issues/2426

**Comment by anorth** [comment]
@acruikshank this seems sorta related to network names and protocol upgrades, but I'm not sure there's anything to do here. I think we've backed off from ideas about exchanging parameter sets etc. As we approach more "real" networks, we'll rely on consensus mechanisms detecting incompatible implementations, and need to be robust to bad data.

I propose we close this in favour of #2509
