### ISSUE TITLE
prevent old binaries from polluting the DHT

### ISSUE THREAD

**Issue by phritz** [filecoin-project/go-filecoin#2426]
We noticed during the release a bunch of WARNING logs like this:

`genesis cid: zDPWYqFCutuHwRZhGXzji9L4eHeoFxxNCxCruGjWje36aAvbK2XV does not match: zDPWYqFCu9VdMN9pUSSttbjJsxd2sTJGZjXv8AGZvquxnsMRFh9e, disconnecting from peer: <peer.ID Qm*hRehNU>`

There is only one dht for all filecoin nodes https://github.com/filecoin-project/go-filecoin/blob/f66f42cd08bda2710a03f771a1c6d645b1b04801/node/node.go#L349 so if two filecoin nodes connect to each other they will exchange dht information, even if they are part of different devnets. Since gfc randomly walks the dht and attempts to connect to random peers, gfc will often attempt to connect to nodes that happen to be in the dht even if they are part of different devnets and/or built at different commits. We suspect that the reason we see so many of these warning messages is not because of bridged devnets but because of old nodes connecting into the new usernet. Old nodes don't have the client disconnect logic: https://github.com/filecoin-project/go-filecoin/blob/675344fd36517ba6ee06990784afc30129378daf/protocol/hello/hello.go#L116 and the server side does disconnect (by design, though we should revisit that).

We should strive to have a dht that is not polluted by incompatible binaries or binaries from other environments. First priority is to prevent old binaries from connecting to and polluting the dht of the test or user devnet. Second priority is to prevent new binaries from polluting across environments (test to user, eg), though we can't currently think of a mechanism by which this would be possible. Potential mechanisms:
- generate a new set of peerids for bootstrap nodes for each release. Challenge is how to include them in the config. 
- rotate ips each release
- disconnect on the server side if a client connects with the wrong commit. This has dev ux tradeoff, eg devs would need a way to override this behavior so they can connect arbitrary code to a devnet.

Related:
- we probably should not be using the same peerids across each environment (nightly, test, user). At the very least this is confusing because if you connect to a certain peerid you can't tell what devnet it belongs to. But also if dhts do become bridged then we could get whacky behavior where multiple nodes with the same peerid try to manage the same dht entry.

**Comment by phritz** [comment]
related: https://github.com/filecoin-project/go-filecoin/issues/2421

**Comment by gmasgras** [comment]
(phritz typing) we should probably set a different dhtopts.Protocols for each of nightly, user, test devnets (and eventually testnet)

**Comment by gmasgras** [comment]
@scout see link to source above where we are setting dht protocol

**Comment by anorth** [comment]
In the same vein, we probably also want to separate the pubsubs with fresh topic names. Separate DHTs may not suffice to segregate the pubsub channels. For example, if network bootstrap nodes are preserved between old/new networks, messages from different logical networks may be propagated.

**Comment by anorth** [comment]
I'm closing this in favour of #2509. I think the mechanism will be to embed the network name in the protocol ID.
