### ISSUE TITLE
dump message along with failure message

### ISSUE THREAD

**Issue by phritz** [filecoin-project/go-filecoin#2427]
as of the 0.1 release we see tons of messages like this on our bootstrap nodes

`processMessage(): failed to add message zDPWYqFD1gRDd1WhM5PBYS8GwZLRUdmkkKy3vYAeVfueJL171DTH to pool: sig invalid`

it's hard to know whether this is a problem or not without the message. we should dump the message along with this log line so we can easily see where this message is coming from and whether there might be a problem

also, this should not be an error, this should be a WARNING

**Comment by anorth** [comment]
This is old and we've changed both the code and logging in these areas.
