### ISSUE TITLE
the speed of running 0.1.4 released seal proof is much slower than the old one

### ISSUE THREAD

**Issue by deltazxm** [filecoin-project/go-filecoin#2429]
with the same equipment,running proof is slower than the old released version.For example ,sealed a sector need 15 minutes while it just needs 7 minutes before.I want to know the reason.Is this about POST code?

**Comment by laser** [comment]
Hi @deltazxm,

Would you please tell me how you measure seal performance? For instance:

"I start my timer when the `./go-filecoin client propose-storage-deal` command returns. I stop my timer when I see a `commitSector` message in the client's chain. This once took 7 minutes and now takes 15 minutes."

or perhaps:

"I start my timer when I call the [`seal`](https://github.com/filecoin-project/rust-fil-proofs/blob/master/filecoin-proofs/src/api/internal.rs#L479) function. I stop my timer when `seal` returns. This once took 7 minutes and now takes 15 minutes."

I will be able to compare seal performance across devnet/user releases once I know how are measuring in your environment.

Take care,

Erin

**Comment by deltazxm** [comment]
I look stat of the file in sealed,new release is slower than before.

**Comment by deltazxm** [comment]
I calculate the time  from accepted to posted  with one deal

**Comment by laser** [comment]
> I calculate the time from accepted to posted with one deal

Thanks. I will investigate this issue.

**Comment by travisperson** [comment]
I ran a miner for a good while on the last user devnet and was averaging 7 minute sealing times as well. I just setup a miner on v0.1.4 and am still seeing 7 minute sealing.

@laser my repos are on a disk array with ~82 MB/s writes, ~450 MB/s reads, and my system has 64GB of ram.

**Comment by deltazxm** [comment]
thanks,I will do more test
