### ISSUE TITLE
go-filecoin init error with --genesisfile=https://genesis.user.kittyhawk.wtf/genesis.car

### ISSUE THREAD

**Issue by irocnX** [filecoin-project/go-filecoin#2435]
### Description
I run into this error when I run the below command 
$>go-filecoin init --devnet-user --genesisfile=https://genesis.user.kittyhawk.wtf/genesis.car

the error information is:
initializing filecoin node at ~/.filecoin
Error: Could not Init Node: unmarshal error: cannot assign <x:[]> to fixed length=22 byte array

but I use the previous genesis.car it work well.
$go-filecoin init --devnet-user --genesisfile=genesis.car (this genesis.car downloaded before)

**Comment by irocnX** [comment]
version issue

**Comment by deaswang** [comment]
same issue. without the previous genesis.car, how to init? @irocnX
