### ISSUE TITLE
When mining, create challenge seed using Lookback parameter

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/go-filecoin#2437]
### Where to begin
Modify CreateChallengeSeed to take in either the lookback tipset or the ancestor slice.  Use the DefaultWorker's `getAncestors` function to pass the correct data into worker.Mine's call of CreateChallengeSeed

**Comment by jscode017** [comment]
May I ask that what you said is that the function should not only use one tipset(its parent)'s minTicket to generate the challengeSeed, but should lookback more than one tipset and use their all lookback tipsets' minTickets to generate challengeSeed?
If so how should the lookback parameter be?
