### ISSUE TITLE
Filecoin metrics must be tagged with a version label

### ISSUE THREAD

**Issue by frrist** [filecoin-project/go-filecoin#2440]
### Description
Currently filecoin exposes 2 metrics, ApplyMessage and ProcessBlock durations, these metrics and all metrics added hereafter must be labeled with the filecoin version.

**Comment by anorth** [comment]
I hope we can do this in a way that is transparent to developers, specifying this and other automatic tags at boot and having them automatically added to all metrics.

**Comment by frrist** [comment]
Closing in favor of https://github.com/filecoin-project/go-filecoin-infra/issues/214
