### ISSUE TITLE
Move clusterduck rotation into helpdesk

### ISSUE THREAD

**Issue by gmasgras** [filecoin-project/go-filecoin#2442]
### Description
move clusterduck rotation into helpdesk as described here: https://github.com/filecoin-project/pm/issues/125

### Acceptance criteria
infra has documented how to log in, tail logs, search logs, find dashboards, etc for each devnet and that there is a link to the infra page from the helpdesk description in roles.md

**Comment by anorth** [comment]
@gmasgras @ognots this epic has no open issues, but we have not shared cluster monitoring work with the implementation team yet. Are there issues that should be added? What remains before we can merge our community helpdesk with this role?

**Comment by anorth** [comment]
Closing this go-filecoin issue, it's an infra issue.
