### ISSUE TITLE
Log commands issued to a node to keep track of piece→miner mappings

### ISSUE THREAD

**Issue by phritz** [filecoin-project/go-filecoin#2443]
## Motivation
In the near term, we don't intend to implement any discovery mechanism for retrieval. A client must keep track of which miner has stored their files.

The relevant information is embedded in the commands issued to a node by a client accepting a deal. As a cheap way of doing something here, we wish to log all the commands issued to a node to disk, where they can be inspected later by a client who has otherwise failed to keep track.

We probably don't want this log to be subject to log level suppression, so it's probably a distinct path from the usual application logs. We should log to a file somewhere, perhaps in `.filecoin`.

Plain text logs should suffice, but a little structure wouldn't hurt. CSV? JSON?

The first part of this story is proposing a specific mechanism in this issue.

**Comment by deaswang** [comment]
## designdoc

### Problem Statement

For inspecte relevant information of piece→miner mappings, need to store log commands issued to a node to local file.

### Design Goals

1. Format information of piece→miner mappings.
2. Manage one array of loggers for different command log information.
3. Store the log information to local file system.

### Proposed Implementation

Add one map of loggers in repo struct, key match filename which store log information file, value match logger object. logger use file as output. all log files store in REPODIR/logs folder.

```go
	loggers map[string]*log.Logger
```

Repo use Logger func to get logger to log command information.

```go
	Logger(string) (*log.Logger, error)
```

After command execute success,  use InspectorAPI to get Logger and Printf the formated information to the output file of logger.

### Alternatives

define and use logger at the place of command. will not affect Repo struct, and remove them after implement discovery mechanism for retrieval.

**Comment by anorth** [comment]
This sounds broadly reasonable to me. I'm not sure that we want to use the `log.Logger` interface specifically (with all of the levels, format etc that that implies) or something more direct, e.g. with a `func log(o interface{})` that records calls as JSONL (one JSON obj per line).

@travisperson you recently mentioned the idea of logging messages sent by a node, which might want to use the same framework. Your thoughts here?

**Comment by anorth** [comment]
See #3230

**Comment by anorth** [comment]
FYI @frrist

**Comment by acruikshank** [comment]
The motivation for this issue and its proposed solution seem a bit at odds. We already storing piece CID -> miner mappings in client deals. Deals must be stored this way for potential arbitration. This command log might have many additional uses, but I recommend that piece->miner discovery use the deal data store instead.

**Comment by anorth** [comment]
Great - that storage might post-date this request, so lets close it.
