### ISSUE TITLE
SubmitPoSt

### ISSUE THREAD

**Issue by SmartMeshFoundation** [filecoin-project/go-filecoin#2445]
How to Ensure Miners to Execute SubmitPoSt According to Current Rules？Who will verify that the miners submitted PoSt  on time?

**Comment by shannonwells** [comment]
For questions like this, please do not file an issue; please check for an answer [in the specs](https://github.com/filecoin-project/specs/), if this does not answer your question, please direct questions either to our Riot [fil_dev](https://riot.im/app/#/room/#fil-dev:matrix.org) channel or[discuss.filecoin.io](https://discuss.filecoin.io/)
