### ISSUE TITLE
Error: couldn't establish connection to miner: context deadline exceeded

### ISSUE THREAD

**Issue by woshihanhaoniao** [filecoin-project/go-filecoin#2446]
I am a miner and have submitted orders. But I want to store the data for me.
log is  couldn't establish connection to miner: context deadline exceeded
this is my： 
t2pwqfepvcq7qk2ptdhvhxxsodml3c6vowqre5cey 001 6.6666666 10255

**Comment by sywyn219** [comment]
go-filecoin mpool ls | xargs -L1 go-filecoin mpool rm

Or check if your balance is enough

Or Whether two nodes establish a connection

**Comment by woshihanhaoniao** [comment]
> go-filecoin mpool ls | xargs -L1 go-filecoin mpool rm
> 
> Or check if your balance is enough
> 
> Or Whether two nodes establish a connection

thanks ,Can you tell me the enrollment test?

**Comment by sywyn219** [comment]
Give me your Q ^_^ , Email

**Comment by woshihanhaoniao** [comment]
> Give me your Q ^_^ , Email

my email : :
18054418886@163.com
and do you use Wechat or qq？....n(*≧▽≦*)n

**Comment by shannonwells** [comment]
Hello @woshihanhaoniao it is probably not a good idea to post personal emails in a GitHub Issue since it is public.

**Comment by woshihanhaoniao** [comment]
> Hello @woshihanhaoniao it is probably not a good idea to post personal emails in a GitHub Issue since it is public.

Thank you for reminding me，I think it will help me more quickly.O(∩_∩)O

**Comment by rkowalick** [comment]
@woshihanhaoniao This issues seems like it is being resolved elsewhere. Please feel to reopen if you are still having problems.
