### ISSUE TITLE
Running deps failing on fetching gx

### ISSUE THREAD

**Issue by block2020** [filecoin-project/go-filecoin#2447]

**Comment by block2020** [comment]
FILECOIN_USE_PRECOMPILED_RUST_PROOFS=true go run ./build deps
pkg-config --version
0.27.1
Installing dependencies...
go get -u github.com/whyrusleeping/gx
package golang.org/x/crypto/ed25519: golang.org/x/crypto is a custom import path for https://go.googlesource.com/crypto, but /usr/local/go/gopath/src/golang.org/x/crypto is checked out from https://github.com/golang/crypto.git
package golang.org/x/crypto/blake2s: golang.org/x/crypto is a custom import path for https://go.googlesource.com/crypto, but /usr/local/go/gopath/src/golang.org/x/crypto is checked out from https://github.com/golang/crypto.git
package golang.org/x/crypto/sha3: golang.org/x/crypto is a custom import path for https://go.googlesource.com/crypto, but /usr/local/go/gopath/src/golang.org/x/crypto is checked out from https://github.com/golang/crypto.git
Command 'go get -u github.com/whyrusleeping/gx' failed: exit status 1
exit status 1

**Comment by shannonwells** [comment]
This appears to be the same type of error as here in golant/lint: https://github.com/golang/lint/issues/118 can you please try the recommended steps there and close this issue if it solves your problem.

**Comment by rkowalick** [comment]
As this issue seems identical to the one referenced above, I'm going to close this. @block2020 please reopen if you are still having issues.
