### ISSUE TITLE
MarketView.Total, MarketView.Miner limited by uint64

### ISSUE THREAD

**Issue by shannonwells** [filecoin-project/go-filecoin#2453]
### Description
MarketView.Total and MarketView.Miner return `uint64`,  which is enough bits to express about 1 exabyte of total storage. This should be increased for v1.

### Acceptance criteria
Use a big.Int?

### Risks + pitfalls
Can't think of any

### Where to begin
consensus/power_table_view.go

**Comment by anorth** [comment]
Fixed to be bigints.
