### ISSUE TITLE
Q: Should power in PTV be sectors or bytes?

### ISSUE THREAD

**Issue by shannonwells** [filecoin-project/go-filecoin#2454]
### Description
Power in a power table view is in sectors, figure out if & how it should be converted to bytes.
(from a TODO)

### Acceptance criteria
Answer the question and make changes (or not) accordingly

### Risks + pitfalls
Lots of dependencies on the units of PTV, including in tests

### Where to begin
https://github.com/filecoin-project/go-filecoin/blob/master/consensus/power_table_view.go

**Comment by anorth** [comment]
It's in bytes.
