### ISSUE TITLE
FAST environment for connecting to devnets

### ISSUE THREAD

**Issue by travisperson** [filecoin-project/go-filecoin#2457]
### Description

To help with automation around using the devnets (nightly, test, user) FAST should provide a environment to help users manage nodes which will connect to the devnets.

Due to the lengthy time required to download and process the chain, the environment  should support a new feat `AddProcess` which differs from `CreateProcess`, in that it should allow the user to attach anything from an already running process, to an existing repo that a process can be started with.

The new `AddProcess` will allow us to maintain a set of pooled nodes which which will have the chain already sync and ready to perform functional testing without the every increasing chain syncing delay.

**Other Thoughts**

First, it would also be really neat if this devnet environment could some how supported localnet.

Secondly, at some-point we may be able to reuse these nodes, but at the moment I'd be worried about issues dealing with state (maybe we can get around this). If we wish to always be working with a fresh node, after tests run with a given node we would want to remove it from the pool, reset, and have it start the chain sync / processing again so that it can be available for use later.

This work is also something that can achieved using FAST. I would be curious to hear peoples thoughts on this. Something that may help with this is to make sure that each test always create a new wallet (account), which would allow us to reuse the chain information from a single node, but act like we are something new.

### Acceptance criteria

- New FAST environment exists allowing users to connect to devnets
- A way to retrieve funds should be provided by the environment (faucet)
- bonus: Update the EnvironmentMemeyGenesis to allow it to reuse the same retrieve funds API above

### Where to begin

https://github.com/filecoin-project/go-filecoin/blob/master/tools/fast/environment.go#L33-L69

See #2444 

Would appropriate input from @anorth @ognots @frrist

**Comment by sywyn219** [comment]
Will it bring any new problems ?

**Comment by travisperson** [comment]
This change should have zero impact on the go-filecoin binary itself and should not impact any of the devnets in the immediate future. It should hopefully help reduce the number of problems by allowing us to perform automated functional tests to ensure the stability of go-filecoin.

The additional of this environment for FAST will also help move us towards our efforts in reducing the amount of duplicate code we have in automation, particularly around how we setup the devnets.

Let me know if you have any specific questions though.

**Comment by anorth** [comment]
The use case is a bit unclear to me. Could you provide a concrete motivating example?

**Comment by travisperson** [comment]
Running the retrieval test against the devnets (nightly, test, or user): https://github.com/filecoin-project/go-filecoin/pull/2444/files

**Comment by anorth** [comment]
@travisperson is this done? If not, could you outline the remaining work?
