### ISSUE TITLE
[bug] Can't connect to the network using tag 0.1.4

### ISSUE THREAD

**Issue by NatoBoram** [filecoin-project/go-filecoin#2458]
**Describe the bug**

I can't join the Filecoin swarm and the `devnet-user` because my Filecoin node doesn't know what's its version.

**To Reproduce**

1. Checkout `0.1.4`
2. Build `go-filecoin`
3. Initialize `go-filecoin` according to [Getting-Started#start-running-filecoin](https://github.com/filecoin-project/go-filecoin/wiki/Getting-Started#start-running-filecoin)

**Expected behavior**

I should be able to join the network.

**Screenshots**

```log
My peer ID is QmdrPHuzaQjg8RKkZMoU6dRvEpx1QFfoniBJ2TML3jMuMX
Swarm listening on: /ip4/127.0.0.1/tcp/6000
Swarm listening on: /ip4/192.168.1.3/tcp/6000
Swarm listening on: /ip4/192.168.1.139/tcp/6000
00:39:32.966  INFO chain.stor: start loading chain at tipset: { zDPWYqFCu9VdMN9pUSSttbjJsxd2sTJGZjXv8AGZvquxnsMRFh9e }, height: 0 default_store.go:114
00:39:32.971  INFO chain.stor: finished loading 0 tipsets from { zDPWYqFCu9VdMN9pUSSttbjJsxd2sTJGZjXv8AGZvquxnsMRFh9e } default_store.go:156
00:39:43.391 WARNI /fil/hello: bad hello message from peer <peer.ID Qm*vwBpp4>: stream reset hello.go:87
00:39:44.661 ERROR /fil/hello: code not at same version: 966fe75919755074c7c2724f2c9634c2b61d4212 does not match , disconnecting from peer: <peer.ID Qm*vwBpp4> hello.go:97
00:39:53.368 ERROR /fil/hello: code not at same version: 966fe75919755074c7c2724f2c9634c2b61d4212 does not match , disconnecting from peer: <peer.ID Qm*2DX9XY> hello.go:97
00:39:58.242  INFO    autonat: Discovered AutoNAT peer QmXhxqTKzBKHA5FcMuiKZv8YaMPwpbKGXHRVZcFB2DX9XY notify.go:33
00:40:03.239 ERROR /fil/hello: code not at same version: 966fe75919755074c7c2724f2c9634c2b61d4212 does not match , disconnecting from peer: <peer.ID Qm*2DX9XY> hello.go:97
00:40:03.239 WARNI /fil/hello: failed to send hello handshake to peer <peer.ID Qm*2DX9XY>: stream reset hello.go:167
00:40:13.412 ERROR /fil/hello: code not at same version: 966fe75919755074c7c2724f2c9634c2b61d4212 does not match , disconnecting from peer: <peer.ID Qm*2DX9XY> hello.go:97
00:40:18.279  INFO    autonat: Discovered AutoNAT peer QmXhxqTKzBKHA5FcMuiKZv8YaMPwpbKGXHRVZcFB2DX9XY notify.go:33
00:40:23.382 ERROR /fil/hello: code not at same version: 966fe75919755074c7c2724f2c9634c2b61d4212 does not match , disconnecting from peer: <peer.ID Qm*crmVbg> hello.go:97
00:40:23.382 WARNI net/identi: error reading identify message:  stream reset id.go:135
00:40:33.392 ERROR /fil/hello: code not at same version: 966fe75919755074c7c2724f2c9634c2b61d4212 does not match , disconnecting from peer: <peer.ID Qm*QvwuiV> hello.go:97
```

**Desktop (please complete the following information):**

```yaml
OS: Ubuntu 18.04.2 LTS x86_64 
Host: HP G62 Notebook PC 0598120000202710010020100 
Kernel: 4.15.0-47-generic 
Uptime: 1 day, 23 hours, 10 mins 
Packages: 853 
Shell: bash 4.4.19 
Terminal: /dev/pts/3 
CPU: Intel i3 M 370 (4) @ 2.399GHz 
GPU: Intel Integrated Graphics 
Memory: 841MiB / 3744MiB 
```

```bash
go-filecoin version
commit: 
```

**Additional context**

```git
HEAD detached at 0.1.4
nothing to commit, working tree clean
```

**Comment by rkowalick** [comment]
@NatoBoram Looking into this right now.

**Comment by rkowalick** [comment]
It seems like you might have accidentally run a command that doesn't include the code version during build time.

It is important to run `go run ./build build` to build the project instead of `go build .`, as the latter does not include the code version into the build.

We also have an instruction `cp go-filecoin $GOPATH/bin` to preserve the code version, since `go install` has the same issue as `go build` above.

Let me know if this fixes your issue.

**Comment by NatoBoram** [comment]
:thinking: 

Here's my exact script to install / update Filecoin : 

```sh
#!/bin/sh

# Remember working directory
HERE=`pwd`

echo Updating Rust...
rustup update

echo Go Get...
go get -u -v -fix github.com/filecoin-project/go-filecoin

echo Git Pull...
cd ~/go/src/github.com/filecoin-project/go-filecoin
git pull

echo Stopping Filecoin...
systemctl --user stop filecoin.service

echo Dependencies...
FILECOIN_USE_PRECOMPILED_RUST_PROOFS=false go run ./build deps

echo Building...
go run ./build build

echo Installing...
go run ./build install

# Returns to the working directory
cd $HERE

echo Starting Filecoin...
systemctl --user start filecoin.service

echo Starting the mining process...
go-filecoin mining start
```

I was already using `go run ./build build`.

**Comment by rkowalick** [comment]
Ahh, I see the issue. The `go run ./build install` command currently doesn't set the code version correctly. You need to copy the binary created in `build` directly to `$GOPATH/bin`. I have made a PR to address this issue: #2465

Let me know if replacing the `go run ./build install` line with `cp go-filecoin $GOPATH/bin` fixes the issue.

**Comment by NatoBoram** [comment]
I tried both commands on branch https://github.com/filecoin-project/go-filecoin/pull/2465 and reported [here](https://github.com/filecoin-project/go-filecoin/pull/2465#issuecomment-478770451).

**Comment by rkowalick** [comment]
The command on branch #2465 won't work, as that code will be at a different version. You need to use the source code with the git tag 0.1.4 to use user/test-devnet.

So, speaking solely about the steps in https://github.com/filecoin-project/go-filecoin/wiki/Getting-Started#installing-from-source:

1. First off, we need to make sure `$GOPATH/bin` is in your execution path. To check your `$GOPATH`, run `echo $GOPATH`. Then run `echo $PATH`. You should see `<output-of-echo-gopath>/bin`. If it is not there, you must run `export PATH="$GOPATH/bin:$PATH"`

2. Next, we need to check which go-filecoin executable you are running by executing the command below
```
which go-filecoin
```

If it says `/usr/local/bin/go-filecoin`, run `rm  /usr/local/bin/go-filecoin`.

If it is `$GOPATH/bin/go-filecoin`  (for whatever your $GOPATH is), please carefully run the steps in https://github.com/filecoin-project/go-filecoin/wiki/Getting-Started#installing-from-source.

Let me know if you are still having problems.

**Comment by rkowalick** [comment]
I'm going to close this. If you are still having problems, feel free to reopen.
