### ISSUE TITLE
storage client deal ID tracking improvements

### ISSUE THREAD

**Issue by whyrusleeping** [filecoin-project/go-filecoin#247]
The storage client code (in node/storage_client) needs to be upgraded in a couple ways.

- It needs to persist to disk
- It needs to store ID's per miner, so that miners can't override negotiations from other miners by returning the same ID

**Comment by anorth** [comment]
@ingar this issue is old, could you investigate whether we still need to do things here? Since we're otherwise nearly done with deal protocol, it would be a good time to polish the rough edges.
