### ISSUE TITLE
Tech design for repo schema migrations

### ISSUE THREAD

**Issue by anorth** [filecoin-project/go-filecoin#2471]

**Comment by anorth** [comment]
See some comments in #1576, but we may be able to do something simpler.

**Comment by anorth** [comment]
The design doc draft is https://docs.google.com/document/d/1THzh1mrNCKYbdk1zP72xV8pfr1yQBe2n3ptrSAYyVI8/edit#. This doc is in the filecoin.org domain and publicly accessible.

This is not yet final, but at a point where feedback from the wider team would be most helpful, especially @acruikshank @whyrusleeping. We'll discuss a little in the dev weekly call.

**Comment by shannonwells** [comment]
- [ ] Unit tests (how-to and coding)
- [ ] Migration validation (how-to and coding)
- [ ] Build functionality
- [ ] Repo migration functionality
- [ ] Logging and output
- [ ] Version detection and upgrade decisioning
- [ ] Importing/using old code where needed
- [ ] CLI
