### ISSUE TITLE
panic: exec: "pkg-config": executable file not found in $PATH

### ISSUE THREAD

**Issue by woshihanhaoniao** [filecoin-project/go-filecoin#2474]
log

root@aliyun:/home/lisheng/go/src/github.com/filecoin-project/go-filecoin/build# FILECOIN_USE_PRECOMPILED_RUST_PROOFS=true go run ./build deps
package github.com/filecoin-project/go-filecoin/build/build: cannot find package "github.com/filecoin-project/go-filecoin/build/build" in any of:
	/usr/local/go/src/github.com/filecoin-project/go-filecoin/build/build (from $GOROOT)
	/home/lisheng/go/src/github.com/filecoin-project/go-filecoin/build/build (from $GOPATH)

**Comment by rkowalick** [comment]
@woshihanhaoniao In order to run that command, you need to be in the `go-filecoin` repository root. You are in the `/build` directory. If you run
```
cd /home/lisheng/go/src/github.com/filecoin-project/go-filecoin
```
before running that command, it should work.

**Comment by woshihanhaoniao** [comment]
> @woshihanhaoniao In order to run that command, you need to be in the `go-filecoin` repository root. You are in the `/build` directory. If you run
> 
> ```
> cd /home/lisheng/go/src/github.com/filecoin-project/go-filecoin
> ```
> before running that command, it should work.

root@aliyun:/home/lisheng/go/src/github.com/filecoin-project/go-filecoin# FILECOIN_USE_PRECOMPILED_RUST_PROOFS=true go run ./build deps

pkg-config --version
panic: exec: "pkg-config": executable file not found in $PATH

goroutine 1 [running]:
main.runCmd(0x58ec1f, 0x2, 0xc00001e370, 0x1, 0x1)
	/home/lisheng/go/src/github.com/filecoin-project/go-filecoin/build/main.go:83 +0x50b
main.deps()
	/home/lisheng/go/src/github.com/filecoin-project/go-filecoin/build/main.go:107 +0xed
main.main()
	/home/lisheng/go/src/github.com/filecoin-project/go-filecoin/build/main.go:321 +0x18d
exit status 2




Friends, I'm sure there's no problem with the path. But mistakes still exist. What should I do?

**Comment by rkowalick** [comment]
Sorry you are still having issues.

The system requirements for building filecoin are listed in https://github.com/filecoin-project/go-filecoin/wiki/Getting-Started#installing-from-source. Please follow those instructions carefully. If you are still having issues, feel free to comment.
