### ISSUE TITLE
[bug] Invalid argument passed to param fetch in insall-filecoin-parameters.sh

### ISSUE THREAD

**Issue by dignifiedquire** [filecoin-project/go-filecoin#2476]
**Describe the bug**

When running `go run ./build deps` I encountered the following

```
~/.go/src/github.com/filecoin-project/go-filecoin
./scripts/install-filecoin-parameters.sh
error: Found argument '--all' which wasn't expected, or isn't valid in this context
	Did you mean to put '--all' after the subcommand 'fetch'?

USAGE:
    paramfetch [OPTIONS] [SUBCOMMAND]

For more information try --help
```

**To Reproduce**
Run the script

**Expected behavior**
No error

**Desktop (please complete the following information):**
 - OS: macOS

**Additional context**

**Comment by rkowalick** [comment]
I'm not sure if my version is out of date or yours is, but, after pulling `go-filecoin` master and running `deps`, my `proofs/bin/paramfetch` is okay with the `--all` option.

**Comment by rkowalick** [comment]
Closing. Please reopen if the problem persists.
