### ISSUE TITLE
[bug] Go Modules CircleCI Cache

### ISSUE THREAD

**Issue by ognots** [filecoin-project/go-filecoin#2477]
**Describe the bug**
Dependencies saved using go modules are not cache properly in CircleCI. Add the appropriate directory to cache and increment cache version number

**To Reproduce**
https://circleci.com/gh/filecoin-project/go-filecoin/13511

**Comment by Kubuxu** [comment]
I don't think it is a cache problem. I think it is a problem with `GO111MODULE=on` not being set thus go modules not being enabled.

A solution is to set `GO111MODEULE=on` or build out of `GOPATH` (https://github.com/filecoin-project/go-filecoin/pull/2478)
