### ISSUE TITLE
Storing on Filecoin wiki example wrong file extension image.png[bug]

### ISSUE THREAD

**Issue by zebul** [filecoin-project/go-filecoin#2480]
**Describe the bug**
The [Storing on Filecoin: Import Data](https://github.com/filecoin-project/go-filecoin/wiki/Storing-on-Filecoin) tutorial switches file extension from .jpg to .png resulting in open failure.

**To Reproduce**
1. Go to [Storing on Filecoin: Import Data](https://github.com/filecoin-project/go-filecoin/wiki/Storing-on-Filecoin#import-data)

2. See section demonstrating how to import camel.jpg
![image](https://user-images.githubusercontent.com/1380654/55425085-82a5a700-5536-11e9-94b3-7d502d254e39.png)

3. Error occurs when running command to open file image.png
![image](https://user-images.githubusercontent.com/1380654/55425173-a23ccf80-5536-11e9-8a7f-c6c9506f5518.png)

**Expected behavior**
Command to open image.png should open original camel.jpg image.  File extension should remain .jpg in example. 

**Screenshots**
![image](https://user-images.githubusercontent.com/1380654/55425085-82a5a700-5536-11e9-94b3-7d502d254e39.png)
![image](https://user-images.githubusercontent.com/1380654/55425173-a23ccf80-5536-11e9-8a7f-c6c9506f5518.png)

**Desktop (please complete the following information):**
 - OS: [Ubuntu 18.04.2 LTS]
 - Browser [Firefox 65.0]

**Comment by rkowalick** [comment]
Fixed! Thanks for pointing this out.
