### ISSUE TITLE
Storage Protocol Deals & Dispute Resolution

### ISSUE THREAD

**Issue by acruikshank** [filecoin-project/go-filecoin#2481]
This epic tracks work towards establishing a power balance between storage clients and storage miners. It includes work on:

1. Clients promptly retrieving funds for declined or otherwise broken deals.
2. Miners providing sufficient information for clients to track storage proofs on chain (piece inclusion proofs).
3. Requiring miners to prove storage before collecting payment.
4. Slashing miners for breaking storage deals.

Work will mostly focus on:

1. The PaymentBroker actor
2. The storage protocol.
3. The Miner actor.

**Comment by anorth** [comment]
I'm closing this epic now. We have been blocked from making the final bits of progress by upstream uncertainty. Along with Rational PoSt we expect more changes here to settle around October, after which we can work through remaining implementation.
