### ISSUE TITLE
Datastore Config should use the advanced datastore configuration from ipfs

### ISSUE THREAD

**Issue by shannonwells** [filecoin-project/go-filecoin#2490]
### Description
Is this still relevant? From a todo in config/config.go, DatastoreConfig has only `Type`, `Path` strings but the comment says it should use the advanced datastore configuration from ipfs.

### Acceptance criteria
If we need the configuration from ipfs then it should be imported and used, if not leave as is.

### Risks + pitfalls
related to #2470 

### Where to begin
config/config.go, repo directory

**Comment by anorth** [comment]
@whyrusleeping is this something we should be looking into now, or lower priority/later?
