### ISSUE TITLE
@anorth -> maintainer proposal

### ISSUE THREAD

**Issue by mishmosh** [filecoin-project/go-filecoin#2493]
I nominate @anorth as a maintainer for go-filecoin. I believe he already effectively carries out the responsibilities outlined in [CONTRIBUTING](https://github.com/filecoin-project/go-filecoin/blob/master/CONTRIBUTING.md#maintainers).

1. @anorth is invested in the project as a full-time contributor, familiar with its mission, goals, and constraints. Recent contribution highlights include the message queue [design](https://docs.google.com/document/d/1Ns5_ushX9exsKr0xbc2Kt0ZHzAA0WnVvl42hyGRR5l0/edit) and [implementation](https://github.com/filecoin-project/go-filecoin/issues/2146), chain[iterators](https://github.com/filecoin-project/go-filecoin/pull/2269), and setting and [documenting our policy](https://github.com/filecoin-project/go-filecoin/pull/2090) on merge commits. In the past three months @anorth has left a mark on the [commit count leaderboard](https://github.com/filecoin-project/go-filecoin/graphs/contributors?from=2019-01-07&to=2019-03-24&type=c).

2. @anorth understands the Filecoin system and this implementation as a whole, having authored the [CODEWALK](https://github.com/filecoin-project/go-filecoin/blob/master/CODEWALK.md) document, and parts in depth through design and implementation work. He also knows when to pull in others.

3. @anorth enables others through direct involvement in planning, feedback, and review.

4. @anorth has consistently modeled good judgement, trustworthiness, civility and helpfulness.

Acceptance of this nomination requires unanimous approval of @whyrusleeping, @phritz, @acruikshank and @mishmosh. Please add your comments to this issue.

**Comment by anorth** [comment]
Thank you @mishmosh. I look forward to continuing and growing my impact on the project in all these ways.

**Comment by phritz** [comment]
full support from this corner!

**Comment by phritz** [comment]
my guess is that alex will be less clumsy than i am when it comes to clicking buttons...

**Comment by acruikshank** [comment]
I hholeheartedly approve.

**Comment by dignifiedquire** [comment]
I approve, even though nobody asked me :) go forth @anorth

**Comment by whyrusleeping** [comment]
Oh hey, sounds good to me.

**Comment by travisperson** [comment]
@mishmosh anything else we need?

**Comment by anorth** [comment]
Thank you all. Would someone please bless me with repo admin permissions?

**Comment by mishmosh** [comment]
@anorth has been added to the `@go-filecoin-maintainers` team on Github, which includes admin access to this repo.
