### ISSUE TITLE
Scripts for contributors usernames

### ISSUE THREAD

**Issue by mishmosh** [filecoin-project/go-filecoin#2504]
### Description
For the [changelog's contributors section](https://github.com/filecoin-project/go-filecoin/blob/master/CHANGELOG.md#contributors) we tried to use these scripts but ran into GitHub API timeouts:
https://gist.github.com/alanshaw/5a2d9465c5a05b201d949551bdb1fcc3

Why reports that he has run into the timeouts before. Do these scripts work out of the box for you @alanshaw @olizilla? If so can you help us verify or debug?

- We mostly want contributors who create issues, comments, and commits.
- Usernames are okay/preferred over firstlast names. Counts (eg 15 comments, etc.) are nice to have, but not necessary
- The repos we want to count for now are the 3 direct dependencies of `go-filecoin`:
  - go-filecoin
  - rust-fil-proofs
  - specs

### Acceptance criteria
A script that works for @mishmosh or other filecoin team member to run and fetch these stats, given a time period.

**Comment by alanshaw** [comment]
The scripts work for me - I just used them the other day. It takes ages (because there's so many repos to examine for JS IPFS) but it creates a cache file so if it bugs out you've not lost your progress, just start it again.

Note: you _have_ to get and use a [github personal access token](https://github.com/settings/tokens) (see first line of https://gist.github.com/alanshaw/5a2d9465c5a05b201d949551bdb1fcc3#file-exec-sh for usage) because otherwise you'll hit API limits.

**Comment by alanshaw** [comment]
I'll edit the script for you next friday to output what you need (as defined above).

**Comment by alanshaw** [comment]
@mishmosh any chance you can give the tool a go? Instructions are here https://github.com/filecoin-project/filecoin-contributors/blob/master/README.md

When I run it from 01/01/2019 I get the following output - is that what you're looking for:

* [@814556001](https://github.com/814556001) (1 comment)
* [@a8159236](https://github.com/a8159236) (3 issues, 10 comments)
* [@aaronhenshaw](https://github.com/aaronhenshaw) (1 issue, 1 comment)
* [@AbelLaker](https://github.com/AbelLaker) (2 issues, 2 comments)
* [@acruikshank](https://github.com/acruikshank) (46 commits, 22 PRs, 38 issues, 72 comments)
* [@aioloszcy](https://github.com/aioloszcy) (2 issues)
* [@alanshaw](https://github.com/alanshaw) (1 commit, 1 PR, 3 comments)
* [@anacrolix](https://github.com/anacrolix) (2 commits, 2 PRs, 17 comments)
* [@andrewxhill](https://github.com/andrewxhill) (1 issue)
* [@AndyChen1984](https://github.com/AndyChen1984) (4 issues, 5 comments)
* [@anorth](https://github.com/anorth) (61 commits, 61 PRs, 42 issues, 294 comments)
* [@arcalinea](https://github.com/arcalinea) (1 issue, 4 comments)
* [@arsstone](https://github.com/arsstone) (1 PR, 1 issue, 2 comments)
* [@aschmahmann](https://github.com/aschmahmann) (4 comments)
* [@bigs](https://github.com/bigs) (1 comment)
* [@block2020](https://github.com/block2020) (5 issues, 1 comment)
* [@btcioner](https://github.com/btcioner) (2 comments)
* [@bvohaska](https://github.com/bvohaska) (1 commit, 1 PR, 6 issues, 26 comments)
* [@Byte-Doctor](https://github.com/Byte-Doctor) (1 issue)
* [@cgwyx](https://github.com/cgwyx) (2 comments)
* [@chenminjian](https://github.com/chenminjian) (1 issue, 3 comments)
* [@comradekingu](https://github.com/comradekingu) (1 commit, 1 PR)
* [@contrun](https://github.com/contrun) (4 commits, 5 PRs, 1 issue, 7 comments)
* [@craigbranscom](https://github.com/craigbranscom) (1 issue)
* [@creationix](https://github.com/creationix) (1 comment)
* [@Cyanglacier](https://github.com/Cyanglacier) (1 issue)
* [@Daniel-Wang](https://github.com/Daniel-Wang) (1 commit, 1 PR, 1 comment)
* [@danigrant](https://github.com/danigrant) (2 commits, 2 PRs)
* [@dayou5168](https://github.com/dayou5168) (6 issues, 17 comments)
* [@dayu26](https://github.com/dayu26) (1 comment)
* [@deaswang](https://github.com/deaswang) (1 comment)
* [@decentralion](https://github.com/decentralion) (1 issue, 12 comments)
* [@deltazxm](https://github.com/deltazxm) (1 issue, 5 comments)
* [@dignifiedquire](https://github.com/dignifiedquire) (48 commits, 29 PRs, 15 issues, 146 comments)
* [@diwufeiwen](https://github.com/diwufeiwen) (3 issues, 3 comments)
* [@djdv](https://github.com/djdv) (2 comments)
* [@DonaldTsang](https://github.com/DonaldTsang) (1 issue)
* [@EbonyBelle](https://github.com/EbonyBelle) (1 comment)
* [@ebuchman](https://github.com/ebuchman) (1 issue)
* [@eefahy](https://github.com/eefahy) (1 comment)
* [@ElecRoastChicken](https://github.com/ElecRoastChicken) (2 comments)
* [@fengchenggang1](https://github.com/fengchenggang1) (1 issue)
* [@firmianavan](https://github.com/firmianavan) (1 commit, 2 PRs, 3 comments)
* [@fjl](https://github.com/fjl) (4 comments)
* [@frrist](https://github.com/frrist) (93 commits, 46 PRs, 43 issues, 93 comments)
* [@gfc-test](https://github.com/gfc-test) (1 PR)
* [@gmas](https://github.com/gmas) (12 commits)
* [@gmasgras](https://github.com/gmasgras) (22 commits, 19 PRs, 14 issues, 35 comments)
* [@gnunicorn](https://github.com/gnunicorn) (1 comment)
* [@haadcode](https://github.com/haadcode) (1 issue)
* [@haoglehaogle](https://github.com/haoglehaogle) (1 issue)
* [@hsanjuan](https://github.com/hsanjuan) (3 commits, 2 PRs, 7 comments)
* [@ianjdarrow](https://github.com/ianjdarrow) (5 comments)
* [@imrehg](https://github.com/imrehg) (7 issues, 4 comments)
* [@irocnX](https://github.com/irocnX) (1 issue, 1 comment)
* [@jamiew](https://github.com/jamiew) (1 comment)
* [@jaybutera](https://github.com/jaybutera) (1 issue)
* [@jbenet](https://github.com/jbenet) (1 commit, 4 issues, 8 comments)
* [@jcchua](https://github.com/jcchua) (1 issue, 1 comment)
* [@jesseclay](https://github.com/jesseclay) (1 issue, 1 comment)
* [@jhiesey](https://github.com/jhiesey) (1 issue)
* [@jimpick](https://github.com/jimpick) (1 issue, 3 comments)
* [@joshgarde](https://github.com/joshgarde) (4 comments)
* [@jscode017](https://github.com/jscode017) (1 commit, 1 PR, 2 issues, 9 comments)
* [@karalabe](https://github.com/karalabe) (1 issue, 4 comments)
* [@kishansagathiya](https://github.com/kishansagathiya) (1 issue, 4 comments)
* [@Kostadin](https://github.com/Kostadin) (1 commit, 1 PR)
* [@Kubuxu](https://github.com/Kubuxu) (13 commits, 9 PRs, 8 comments)
* [@lanzafame](https://github.com/lanzafame) (2 commits, 1 PR, 1 issue, 4 comments)
* [@laser](https://github.com/laser) (62 commits, 53 PRs, 73 issues, 164 comments)
* [@leinue](https://github.com/leinue) (1 issue, 1 comment)
* [@lidel](https://github.com/lidel) (3 comments)
* [@life-i](https://github.com/life-i) (1 issue, 3 comments)
* [@lin6461](https://github.com/lin6461) (2 issues, 5 comments)
* [@linsheng9731](https://github.com/linsheng9731) (1 issue)
* [@loulancn](https://github.com/loulancn) (1 issue, 1 comment)
* [@Luca8991](https://github.com/Luca8991) (1 issue)
* [@madper](https://github.com/madper) (1 commit, 1 PR)
* [@magik6k](https://github.com/magik6k) (4 commits, 4 PRs, 9 comments)
* [@MariusVanDerWijden](https://github.com/MariusVanDerWijden) (2 comments)
* [@markwylde](https://github.com/markwylde) (2 issues, 5 comments)
* [@mburns](https://github.com/mburns) (1 PR)
* [@mgoelzer](https://github.com/mgoelzer) (2 issues, 7 comments)
* [@mhammersley](https://github.com/mhammersley) (3 issues, 15 comments)
* [@mikeal](https://github.com/mikeal) (1 PR, 1 issue, 2 comments)
* [@mishmosh](https://github.com/mishmosh) (21 commits, 8 PRs, 34 issues, 150 comments)
* [@mkky-lisheng](https://github.com/mkky-lisheng) (1 issue, 1 comment)
* [@moyid](https://github.com/moyid) (4 comments)
* [@mslipper](https://github.com/mslipper) (9 commits, 8 PRs, 7 issues, 46 comments)
* [@muronglaowang](https://github.com/muronglaowang) (8 issues, 7 comments)
* [@Nanofortress](https://github.com/Nanofortress) (1 issue, 4 comments)
* [@NatoBoram](https://github.com/NatoBoram) (3 issues, 9 comments)
* [@nicola](https://github.com/nicola) (17 commits, 5 PRs, 7 issues, 25 comments)
* [@ognots](https://github.com/ognots) (53 commits, 36 PRs, 18 issues, 84 comments)
* [@olizilla](https://github.com/olizilla) (1 commit, 1 PR)
* [@Pacius](https://github.com/Pacius) (1 issue)
* [@ParadiseTaboo](https://github.com/ParadiseTaboo) (1 comment)
* [@pengxiankaikai](https://github.com/pengxiankaikai) (7 issues, 15 comments)
* [@phritz](https://github.com/phritz) (13 commits, 11 PRs, 50 issues, 366 comments)
* [@pkrasam](https://github.com/pkrasam) (1 issue, 1 comment)
* [@pooja](https://github.com/pooja) (5 commits, 1 PR, 11 issues, 84 comments)
* [@porcuquine](https://github.com/porcuquine) (60 commits, 23 PRs, 31 issues, 239 comments)
* [@protocolin](https://github.com/protocolin) (1 issue)
* [@pxrxingrui520](https://github.com/pxrxingrui520) (1 issue)
* [@rafael81](https://github.com/rafael81) (2 commits, 2 PRs, 1 issue, 3 comments)
* [@raulk](https://github.com/raulk) (4 commits, 5 PRs, 21 comments)
* [@redransil](https://github.com/redransil) (1 issue)
* [@RichardLitt](https://github.com/RichardLitt) (1 commit, 1 PR)
* [@ridewindx](https://github.com/ridewindx) (1 commit, 2 PRs)
* [@rjan90](https://github.com/rjan90) (1 comment)
* [@rkowalick](https://github.com/rkowalick) (51 commits, 46 PRs, 17 issues, 106 comments)
* [@RobQuistNL](https://github.com/RobQuistNL) (1 issue, 7 comments)
* [@rosalinekarr](https://github.com/rosalinekarr) (33 commits, 32 PRs, 44 issues, 144 comments)
* [@sanchopansa](https://github.com/sanchopansa) (2 comments)
* [@sandjj](https://github.com/sandjj) (5 issues, 8 comments)
* [@SaveTheAles](https://github.com/SaveTheAles) (1 issue, 3 comments)
* [@schomatis](https://github.com/schomatis) (47 commits, 21 PRs, 12 issues, 171 comments)
* [@scout](https://github.com/scout) (3 comments)
* [@SCUTVincent](https://github.com/SCUTVincent) (1 issue, 2 comments)
* [@shannonwells](https://github.com/shannonwells) (22 commits, 22 PRs, 40 issues, 63 comments)
* [@sidke](https://github.com/sidke) (79 commits, 22 PRs, 18 issues, 12 comments)
* [@SmartMeshFoundation](https://github.com/SmartMeshFoundation) (1 issue)
* [@songjiayang](https://github.com/songjiayang) (1 comment)
* [@Stebalien](https://github.com/Stebalien) (4 commits, 6 PRs, 18 comments)
* [@sternhenri](https://github.com/sternhenri) (38 commits, 10 PRs, 4 issues, 50 comments)
* [@steven004](https://github.com/steven004) (3 commits, 6 PRs, 4 issues, 9 comments)
* [@sywyn219](https://github.com/sywyn219) (3 issues, 13 comments)
* [@Tbaut](https://github.com/Tbaut) (1 issue)
* [@terichadbourne](https://github.com/terichadbourne) (1 issue, 12 comments)
* [@thomas92911](https://github.com/thomas92911) (1 issue, 1 comment)
* [@travisperson](https://github.com/travisperson) (93 commits, 51 PRs, 39 issues, 179 comments)
* [@tycholiu](https://github.com/tycholiu) (1 comment)
* [@vmx](https://github.com/vmx) (5 commits, 5 PRs, 1 issue, 8 comments)
* [@vyzo](https://github.com/vyzo) (8 comments)
* [@warpfork](https://github.com/warpfork) (6 comments)
* [@waynewyang](https://github.com/waynewyang) (3 commits, 5 PRs, 1 issue, 8 comments)
* [@whyrusleeping](https://github.com/whyrusleeping) (153 commits, 40 PRs, 54 issues, 291 comments)
* [@windstore](https://github.com/windstore) (1 issue, 2 comments)
* [@woshihanhaoniao](https://github.com/woshihanhaoniao) (5 issues, 6 comments)
* [@wyblyf](https://github.com/wyblyf) (1 issue, 6 comments)
* [@xcshuan](https://github.com/xcshuan) (1 issue, 1 comment)
* [@yangjian102621](https://github.com/yangjian102621) (1 PR, 3 issues, 16 comments)
* [@yaohcn](https://github.com/yaohcn) (1 PR, 1 issue, 3 comments)
* [@yph152](https://github.com/yph152) (1 issue)
* [@ytQiao](https://github.com/ytQiao) (1 issue, 2 comments)
* [@yusefnapora](https://github.com/yusefnapora) (1 comment)
* [@yyh1102](https://github.com/yyh1102) (1 comment)
* [@zebul](https://github.com/zebul) (1 issue)
* [@ZenGround0](https://github.com/ZenGround0) (31 commits, 22 PRs, 82 issues, 118 comments)
* [@zhangkuicheng](https://github.com/zhangkuicheng) (2 issues, 4 comments)
* [@zixuanzh](https://github.com/zixuanzh) (4 comments)
* [@zjoooooo](https://github.com/zjoooooo) (1 issue, 1 comment)

**Comment by mishmosh** [comment]
Moving here from chat -- the output looks great!

I haven't run this successfully yet. I've run this 3-4 times on multiple dates. First few times, it spun at the "getting contributors" step. Now, I am getting 502 errors after ~5 mins:

```
:heavy_multiplication_x: Bad Gateway
{
 statusCode: 502,
 statusMessage: ‘Bad Gateway’,
 headers: {
   server: ‘GitHub.com’,
   date: ‘Mon, 06 May 2019 17:26:07 GMT’,
   ‘content-type’: ‘application/json’,
   ‘transfer-encoding’: ‘chunked’,
   connection: ‘close’,
   ‘x-github-request-id’: ‘C1A8:2319:1427E15:29DFDF5:5CD06E2F’
 },
 responseBody: ‘{\n   “data”:“null”,\n   “errors”:[\n      {\n         ’ +
   ‘“message”:“Something went wrong while executing your query. This may ’ +
   ‘be the result of a timeout, or it could be a GitHub bug. Please ’ +
   ‘include `C1A8:2319:1427E15:29DFDF5:5CD06E2F` when reporting this ’ +
   ‘issue.“\n      }\n   ]\n}\n’
}
```

**Comment by mishmosh** [comment]
@alanshaw said via chat that he also experienced those same errors. Went away for me later in the day, so it seems like a problem on Github's end.

The good news is, @rosalinekarr was able to run this successfully in one try, so we were able to use this in our latest release announcement: https://github.com/filecoin-project/go-filecoin/blob/master/CHANGELOG.md#contributors

We think my repeated attempts have exceeded an unknown Github API rate limit.

@alanshaw does that smell right? If so, we have a workaround (ask someone new to run it) and this issue could be closed.

Thank you @alanshaw!

**Comment by alanshaw** [comment]
I think it might be combination of github being a bit flakey, the rate limit, and the library we're using smothering errors. If you just keep running it when it errors it should eventually succeed (as each query is cached locally) but the hangs are a bit of a mystery until I get the time to look into what the library is going and why it's hanging.

**Comment by mishmosh** [comment]
The fact that @rosalinekarr could run this successfully, but not me, leads me to think each time I run it is consuming my Github API ration. I will try a long rest (maybe it is allocated monthly?) and retry.

Closing as done, since someone on the team is able to use this successfully. Thank you!
