### ISSUE TITLE
error: failed to run custom build command for `filecoin-proofs v0.1.0 (/home/lisheng/go/src/github.com/filecoin-project/go-filecoin/proofs/rust-fil-proofs/filecoin-proofs)`

### ISSUE THREAD

**Issue by woshihanhaoniao** [filecoin-project/go-filecoin#2507]
###Describe the bug

When I compiled the source code, there was an error.

###To Reproduce

root@aliyun:/home/lisheng/go/src/github.com/filecoin-project/go-filecoin# cd ${GOPATH}/src/github.com/filecoin-project/go-filecoin
root@aliyun:/home/lisheng/go/src/github.com/filecoin-project/go-filecoin# FILECOIN_USE_PRECOMPILED_RUST_PROOFS=true go run ./build deps

###Expected behavior
I want to turn the source code into a release

### Risks + pitfalls
pkg-config --version
0.29.1
Installing dependencies...
go mod download
./scripts/install-rust-fil-proofs.sh
using precompiled rust-fil-proofs
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5739  100  5739    0     0   4557      0  0:00:01  0:00:01 --:--:--  4554
./scripts/install-rust-fil-proofs.sh: line 14: jq: command not found
curl: (3) <url> malformed
basename: missing operand
Try 'basename --help' for more information.
curl: (3) <url> malformed
asset failed to be downloaded
failed to find or obtain precompiled rust-fil-proofs, falling back to local
/home/lisheng/go/src/github.com/filecoin-project/go-filecoin/proofs/rust-fil-proofs /home/lisheng/go/src/github.com/filecoin-project/go-filecoin
cargo 1.32.0-nightly (5e85ba14a 2018-12-02)
    Updating git repository `https://github.com/filecoin-project/bellman`
    Updating crates.io index
    Updating git repository `https://github.com/filecoin-project/pairing`
    Updating git repository `https://github.com/filecoin-project/phase2`
    Updating git repository `https://github.com/filecoin-project/sapling-crypto`
    Updating git repository `https://github.com/oconnor663/blake2s_simd`
    Updating git repository `https://github.com/filecoin-project/merkle_light`
    Updating git repository `https://github.com/gtank/blake2-rfc`
   Compiling filecoin-proofs v0.1.0 (/home/lisheng/go/src/github.com/filecoin-project/go-filecoin/proofs/rust-fil-proofs/filecoin-proofs)
error: failed to run custom build command for `filecoin-proofs v0.1.0 (/home/lisheng/go/src/github.com/filecoin-project/go-filecoin/proofs/rust-fil-proofs/filecoin-proofs)`
process didn't exit successfully: `/home/lisheng/go/src/github.com/filecoin-project/go-filecoin/proofs/rust-fil-proofs/target/release/build/filecoin-proofs-2285b3328168c47e/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'Unable to find libclang: "couldn\'t find any valid shared libraries matching: [\'libclang.so\', \'libclang-*.so\', \'libclang.so.*\'], set the `LIBCLANG_PATH` environment variable to a path where one of these files can be found (invalid: [])"', src/libcore/result.rs:1009:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.

/home/lisheng/go/src/github.com/filecoin-project/go-filecoin
cp: cannot stat 'proofs/rust-fil-proofs/target/release/paramcache': No such file or directory
cp: cannot stat 'proofs/rust-fil-proofs/target/release/paramfetch': No such file or directory
cp: cannot stat 'proofs/rust-fil-proofs/target/release/libfilecoin_proofs.a': No such file or directory
cp: cannot stat 'proofs/rust-fil-proofs/target/release/libfilecoin_proofs.pc': No such file or directory
Command './scripts/install-rust-fil-proofs.sh' failed: exit status 1
exit status 1
### Where to begin
os:ubuntu 16.04 64

**Comment by travisperson** [comment]
Do you have a c compiler installed? It looks like you don't.

**Comment by rosalinekarr** [comment]
I'm closing this issue to due to no response. @woshihanhaoniao, if you're still having this problem after installing gcc, let us know, and we'll reopen the issue.
