### ISSUE TITLE
Separate devnet DHTs

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/go-filecoin#2509]
### Description
Currently different devnets have the same peer ids which could cause problems.  One such problem is that DHT records could mistakenly cross networks and cause problems.  One solution for this and other such problems is to namespace filecoin DHTs to reference a specific network.

### Acceptance criteria
We separate DHT namespaces.

### Where to begin
The code change should be a small modification to the protocol id string used for the DHT.  This should be set depending on the network being joined.

**Comment by anorth** [comment]
There are lots of issues about related proposals. Whoever does some work on this, please gather these together and propose a set of changes to resolve them as a group: #1700, #2357, #2421, #2426 

One of these existing issues is probably the right tracking issue. #1700 proposes extracting the network protocol string to a configuration parameter, which could make some of these easy to resolve. But don't get in the way of upcoming protocol versioning and upgrading, which will require more nuance than strictly segregating networks of nodes running different code.

**Comment by anorth** [comment]
Another concern is to ensure that developers can connect their node to any network they want to if explicitly opting in.

**Comment by anorth** [comment]
@acruikshank I think this is ready to implement with the network name.
