### ISSUE TITLE
ERROR /fil/hello: code not at same version: peer has version 966fe75919755074c7c2724f2c9634c2b61d4212

### ISSUE THREAD

**Issue by aioloszcy** [filecoin-project/go-filecoin#2511]
Please first see README for how to get help before filing a new bug report. 
I dowload and Installing from binary  from https://github.com/filecoin-project/go-filecoin/releases，and each time when I run "go-filecoin daemon",it report an error "ERROR /fil/hello: code not at same version: peer has version 966fe75919755074c7c2724f2c9634c2b61d4212, daemon has version xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx, disconnecting from peer: <peer.ID Qm*2DX9XY> hello.go:97"

**Expected behavior**

**Screenshots**
Swarm listening on: /ip4/127.0.0.1/tcp/6000
Swarm listening on: /ip4/192.168.1.18/tcp/6000
22:23:31.847  INFO chain.stor: start loading chain at tipset: { zDPWYqFCu9VdMN9pUSSttbjJsxd2sTJGZjXv8AGZvquxnsMRFh9e }, height: 0 default_store.go:114
22:23:31.855  INFO chain.stor: finished loading 0 tipsets from { zDPWYqFCu9VdMN9pUSSttbjJsxd2sTJGZjXv8AGZvquxnsMRFh9e } default_store.go:156
22:23:49.097 ERROR /fil/hello: code not at same version: peer has version 966fe75919755074c7c2724f2c9634c2b61d4212, daemon has version 8ea5ae16527d7ff95976292f450d27eff8b96c94, disconnecting from peer: <peer.ID Qm*2DX9XY> hello.go:97
22:23:50.557  INFO    autonat: Discovered AutoNAT peer QmXhxqTKzBKHA5FcMuiKZv8YaMPwpbKGXHRVZcFB2DX9XY notify.go:33
22:23:58.941 WARNI /fil/hello: bad hello message from peer <peer.ID Qm*crmVbg>: stream reset hello.go:87
22:24:01.970  INFO    autonat: Discovered AutoNAT peer QmZRnwmCjyNHgeNDiyT8mXRtGhP6uSzgHtrozc42crmVbg notify.go:33
22:24:06.480 ERROR /fil/hello: code not at same version: peer has version 966fe75919755074c7c2724f2c9634c2b61d4212, daemon has version 8ea5ae16527d7ff95976292f450d27eff8b96c94, disconnecting from peer: <peer.ID Qm*2DX9XY> hello.go:97
22:24:10.067  INFO    autonat: Discovered AutoNAT peer QmXhxqTKzBKHA5FcMuiKZv8YaMPwpbKGXHRVZcFB2DX9XY notify.go:33
22:24:15.702 ERROR /fil/hello: code not at same version: peer has version 966fe75919755074c7c2724f2c9634c2b61d4212, daemon has version 8ea5ae16527d7ff95976292f450d27eff8b96c94, disconnecting from peer: <peer.ID Qm*crmVbg> hello.go:97
22:24:26.081 ERROR /fil/hello: code not at same version: peer has version 966fe75919755074c7c2724f2c9634c2b61d4212, daemon has version 8ea5ae16527d7ff95976292f450d27eff8b96c94, disconnecting from peer: <peer.ID Qm*QvwuiV> hello.go:97

**Desktop (please complete the following information):**
CentOS Linux release 7.5.1804 (Core) 

**Additional context**

**Comment by travisperson** [comment]
It looks like you are trying to connect to the user devnet, you will need to use a release targeted at it to connect. You can find the latest release by reading the README and clicking on the `User Devnet Release` badge.

https://github.com/filecoin-project/go-filecoin/releases/tag/0.1.4
