### ISSUE TITLE
Separate staging and sealed sectors from node repo

### ISSUE THREAD

**Issue by anorth** [filecoin-project/go-filecoin#2524]
### Description
At present, all on-disk storage for a filecoin node is under the "repo" directory, `~/.filecoin`. This directory contains config, structured stores of block data, and subdirectories `staging` and `sealed` for client data. The staging/sealed data is quite different to the protocol store data and the internals are managed by code in `rust-fil-proofs` which is simply given directory paths to use.

We are currently designing a migration scheme for node's repo data and will likely implement revertible migrations by operating on a copy of the repo. Migrating the sector storage is something we'd like to call out of scope for the immediate efforts since:
- its schema is unlikely to change as frequently
- it's largely orthogonal to the data core to the protocol
- it has potential to be large enough to prohibit copying as a rollback strategy
- we expect large-scale miners to customise sector storage to their architecture, but more likely use our protocol implementation

If we imagine a future separation between a library responsible for the protocol, and a sector builder responsible for storage and proofs, this separation would also be reflected in independent data storage schemes.

Thus, I propose we move the staging and sector directories out of the repo directory, so the repo directory is specialised to storage related directly to the protocol and node operation. 

Concretely, this could be a `~/.filecoin-sectors` directory, or we could nest all the protocol data at `~/.filecoin/protocol` and call that the "repo", but other suggestions welcome.

@whyrusleeping @laser we'd appreciate any thoughts you have here.

### Acceptance criteria
- Staging and sealed sectors are stored outside the directory tree containing protocol-related node storage
- Sector storage is split from the Repo interface
- The location of the repo and the sector store are configurable (the sector paths may be configured by the config contained inside the repo)

### Risks + pitfalls
Implementing this change will require some manual intervention by any node that wishes to retain sectors across the update. These actions can be performed in a shell (which is a property we value for the storage migration processes in general).

### Where to begin
Discuss here to determine any unwanted side-effects of this split. Implementation begins in https://github.com/filecoin-project/go-filecoin/tree/master/repo

**Comment by laser** [comment]
The rust-fil-proofs `SectorBuilder` is created with two paths. One of the paths corresponds to the sealed sector directory and the other to the staged sector directory. I don't see any problems with moving those directories out of the "repo" directory. We'll need to augment some tests with additional teardown code; many tests clean up by deleting their "repo" directory.

> The location of the repo and the sector store are configurable (the sector paths may be configured by the config contained inside the repo)

This will be a little tricky. What do you suppose should happen if someone operating a go-filecoin node changes the staging or sealed sector directories when the node is running? Should the rust-fil-proofs `SectorBuilder` need to respect these changes immediately?

The existing rust-fil-proofs `SectorBuilder` implementation assumes that, after initialization, the staged and sealed directories remain fixed. It will require some programming to ensure that sealed and staged sector file-paths are _relative_ to the sealed and staged sector directories passed to the rust-fil-proofs `SectorBuilder` constructor. This would give us the flexibility to, for example, shut down the node, move staged and sealed sector-directories, update configuration and start the node.

**Comment by travisperson** [comment]
I'd be in favor of keeping all data in a single directory and using configuration with defaults to sub-directories. It makes things much easier to reason about when we only have to worry about a single directory path for basic setups.

**Comment by anorth** [comment]
Yes, I agree that simplicity is valuable. That suggests a layout something like:

```
~/.filecoin
  /sectors
    /staging
    /sealed
  /repo
    config.json
    /chain
    /...
  /repo-20190101120000-v3 # a pre-migration copy
```

**Comment by whyrusleeping** [comment]
That sounds like a good default. But make sure this location is
configurable. An absolute requirement is that I can have my sectors stored
at a location of my choice.

**Comment by anorth** [comment]
This landed with a bit of turbulence, triggered by the sector path not being correctly nested in the home directory for daemon tests (#2680).

The implication of my directory layout proposal was that the "repo" is nested one level deeper than `~/.filecoin`, the "home" dir, with the sector data and space for archived pre-migration repos next to it. This name change caused some confusion, as CLI flags and env vars now target this inner directory.

We might switch back default args and FIL_DIR to refer to `~/.filecoin`. we could take back the term `repo` for `.filecoin`, and then need a new name for the directory containing all the configuration and data a (non-mining) node stores, and understand that migrations only target that inner directory. I am not advocating for that change, tho.

I just want to note the confusion and call our our failure to communicate this well. I do think the distinction between the node data and sectors is an important one that we must face up to eventually in distributed/scalable miner architectures.
