### ISSUE TITLE
Payment Vouchers should be a first class type

### ISSUE THREAD

**Issue by travisperson** [filecoin-project/go-filecoin#2527]
### Description

The payment broker actor defines a `PaymentVoucher` type. This type should exist in the `go-filecoin/types` package, and not in the actor itself.

### Acceptance criteria

- `PaymentVoucher`, and accompanied functions are provide in the `go-filecoin/types` package.

### Where to begin

https://github.com/filecoin-project/go-filecoin/blob/master/actor/builtin/paymentbroker/payment_voucher.go

**Comment by jscode017** [comment]
If I want to try out this as my first issue, should I write a new paymentVoucher_test.go for paymentVoucher in/types and delete some overlap in /actor/builtin/paymentbroker/paymentbroker_test.go?

**Comment by travisperson** [comment]
Ya, I don't know if there are any actual tests of payment vouchers yet, so we'd probably need to write some. Easiest would be a simple round trip test to ensure we can encode/decode.

**Comment by jscode017** [comment]
I do not know why failed dht_daemon_test.go? Changing payment Vouchers to ./types do not seems to related with dht_daemon?
And at my machine(macos), I passed all tests for go run ./build best.
Can anyone provide some help please.
