### ISSUE TITLE
Identify filesystem access throughout go-filecoin

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/go-filecoin#2529]
### Description
Capture information in a document (perhaps linked from the "other" section of the design docs repo) describing all of the instances the go-filecoin writes to disk and through which abstractions.  In particular we want to know about direct disk access not channeled through strong abstractions as part of scoping model for change work.

### Acceptance criteria
The document mentioned above is created and correct

**Comment by ZenGround0** [comment]
cc @shannonwells @anorth please take a look at [this quick report](https://gist.github.com/ZenGround0/82fc8fd946f848051af92dba06f5965e).  The high level is that 
(1) we are doing pretty well 
(2) the CLI client breaks abstractions in a way which we might want to fix but I consider it fairly low priority and 
(3) the proofs directories are super leaky but it shouldn't matter because we want to move them out of the repo anyway

Let me know if you want more info, have any questions, or would like me to file any followup issues or PRs.

**Comment by anorth** [comment]
Thanks.

Too many globals, but we can address them as we write tests for migration work.

For the CLI client we could reconsider whether we even need that functionality, or whether there's a simpler way to have a default port. I agree it's low priority.
