### ISSUE TITLE
Resolve long low-CPU delays during tests

### ISSUE THREAD

**Issue by anorth** [filecoin-project/go-filecoin#2535]
### Description
When running tests, I observe periods of intense CPU work and periods where my CPU is near idle (maybe 1 core working). This suggests that the total duration required to run tests is longer than necessary, not constrained by resources. My guess is that there are some lengthy tests that are not but should be marked as parallel.

### Acceptance criteria
- Tests consume all resources available on a typical developer machine in the name of finishing as quickly as possible.

### Risks + pitfalls
If the tests to be parallelised are very memory intensive they may put more pressure on CI builds, see #2516.

### Where to begin
Evaluate which test functions are not marked parallel.

**Comment by frrist** [comment]
I observe that the CPU is not being fully utilized only when running functional tests, specifically the FAST test `TestRetrieval`. I believe this is due to the initial setup required for the test, specifically message wait calls:

Configure a genesis node and update its peer-id:
```
15:55:28.760  INFO /tmp/TestR: RunCmd: /tmp/TestRetrieval389232326/0 [go-filecoin id --enc=json] process.go:190
15:55:28.787  INFO /tmp/TestR: RunCmd: /tmp/TestRetrieval389232326/0 [go-filecoin config mining.minerAddress "t2udhmwzokf4hq7oe4zj4g3faah7oz4dnbxtxaqoy"] process.go:190
15:55:28.813  INFO /tmp/TestR: RunCmd: /tmp/TestRetrieval389232326/0 [go-filecoin wallet import --enc=json] process.go:190
15:55:28.838  INFO /tmp/TestR: RunCmd: /tmp/TestRetrieval389232326/0 [go-filecoin config wallet.defaultAddress "t1nhudgskmseowv7rp4e6scxsmlt3qoysvpn73tuy"] process.go:190
15:55:28.863  INFO /tmp/TestR: RunCmd: /tmp/TestRetrieval389232326/0 [go-filecoin miner update-peerid --from t1nhudgskmseowv7rp4e6scxsmlt3qoysvpn73tuy --gas-price 300 --gas-limit 300 t2udhmwzokf4hq7oe4zj4g3faah7oz4dnbxtxaqoy QmRNJdPL3XCN9PvkwxTMoGcqHgEa7Gua85CSPnZnNmbUtW --enc=json] process.go:190
15:55:28.890  INFO /tmp/TestR: RunCmd: /tmp/TestRetrieval389232326/0 [go-filecoin mining start] process.go:190
```

Start 2 more daemons and connect them:
```15:55:29.213  INFO localfilec: Node: /tmp/TestRetrieval389232326/1 Started daemon: /tmp/TestRetrieval389232326/1, pid: 21188 localfilecoin.go:425
15:55:29.214 WARNI       util: open /tmp/TestRetrieval389232326/1/api: no such file or directory util.go:27
15:55:29.651  INFO /tmp/TestR: RunCmd: /tmp/TestRetrieval389232326/1 [go-filecoin id --enc=json] process.go:190
15:55:29.781  INFO localfilec: Node: /tmp/TestRetrieval389232326/2 Started daemon: /tmp/TestRetrieval389232326/2, pid: 21237 localfilecoin.go:425
15:55:29.781 WARNI       util: open /tmp/TestRetrieval389232326/2/api: no such file or directory util.go:27
15:55:30.241  INFO /tmp/TestR: RunCmd: /tmp/TestRetrieval389232326/2 [go-filecoin id --enc=json] process.go:190
15:55:30.267  INFO /tmp/TestR: RunCmd: /tmp/TestRetrieval389232326/1 [go-filecoin id --enc=json] process.go:190
15:55:30.292  INFO /tmp/TestR: RunCmd: /tmp/TestRetrieval389232326/0 [go-filecoin swarm connect /ip4/127.0.0.1/tcp/36497/ipfs/QmNzR5ix13hhj6f6ZsTtwkSeLPF1ZcpARJT7vgUtuhsqZD --enc=json] process.go:190
15:55:30.330  INFO /tmp/TestR: RunCmd: /tmp/TestRetrieval389232326/2 [go-filecoin id --enc=json] process.go:190
15:55:30.354  INFO /tmp/TestR: RunCmd: /tmp/TestRetrieval389232326/0 [go-filecoin swarm connect /ip4/127.0.0.1/tcp/40835/ipfs/QmYQiztgQT5SdeviN7JUMi7JwDnAejqunxT2zjh9PkghoX --enc=json] process.go:190
```

Genesis node sends filecoin to the new nodes:
```
15:55:30.391  INFO /tmp/TestR: RunCmd: /tmp/TestRetrieval389232326/1 [go-filecoin config wallet.defaultAddress --enc=json] process.go:190
15:55:30.415  INFO /tmp/TestR: RunCmd: /tmp/TestRetrieval389232326/0 [go-filecoin config wallet.defaultAddress --enc=json] process.go:190
15:55:30.440  INFO /tmp/TestR: RunCmd: /tmp/TestRetrieval389232326/0 [go-filecoin message send --value 100000 --from t1nhudgskmseowv7rp4e6scxsmlt3qoysvpn73tuy --gas-price 1 --gas-limit 300 t1yuwgqqlorv7du7ypzupcbobayywmkyjzsy2fybi --enc=json] process.go:190
15:55:30.469  INFO /tmp/TestR: RunCmd: /tmp/TestRetrieval389232326/0 [go-filecoin message wait zDPWYqFCuXUh7mUspgSK6BU1HWGdGUYH5u33ifMzdJVHGPDSxmUF --enc=json] process.go:190
15:55:34.097  INFO /tmp/TestR: RunCmd: /tmp/TestRetrieval389232326/2 [go-filecoin config wallet.defaultAddress --enc=json] process.go:190
15:55:34.129  INFO /tmp/TestR: RunCmd: /tmp/TestRetrieval389232326/0 [go-filecoin config wallet.defaultAddress --enc=json] process.go:190
15:55:34.157  INFO /tmp/TestR: RunCmd: /tmp/TestRetrieval389232326/0 [go-filecoin message send --value 100000 --from t1nhudgskmseowv7rp4e6scxsmlt3qoysvpn73tuy --gas-price 1 --gas-limit 300 t1lerrgcxgzowkzy2skug6sermlqxbyxsq75qhbjy --enc=json] process.go:190
15:55:34.187  INFO /tmp/TestR: RunCmd: /tmp/TestRetrieval389232326/0 [go-filecoin message wait zDPWYqFD5Lhf6LJZox8kMC6LcjecXjsviP5SZttoJMWCwNcdmajy --enc=json] process.go:190
```

One of the new nodes creates a miner and sets price:
```
15:55:39.270  INFO /tmp/TestR: RunCmd: /tmp/TestRetrieval389232326/1 [go-filecoin miner create --gas-price 1 --gas-limit 300 10 500 --enc=json] process.go:190
15:55:44.485  INFO /tmp/TestR: RunCmd: /tmp/TestRetrieval389232326/1 [go-filecoin mining start] process.go:190
15:55:44.523  INFO /tmp/TestR: RunCmd: /tmp/TestRetrieval389232326/1 [go-filecoin miner set-price --gas-price 1 --gas-limit 300 0.000000001 2880 --enc=json] process.go:190
15:55:49.647  INFO /tmp/TestR: RunCmd: /tmp/TestRetrieval389232326/1 [go-filecoin message wait zDPWYqFD3NGDb3BsQSXeoeTpBTw2JMebjFhiCqa6Vo995yQLvk5K --enc=json] process.go:190
```

The other new nodes imports a file and proposes a deal:
```
15:55:49.759  INFO /tmp/TestR: RunCmd: /tmp/TestRetrieval389232326/2 [go-filecoin client import --enc=json] process.go:190
15:55:49.785  INFO /tmp/TestR: RunCmd: /tmp/TestRetrieval389232326/2 [go-filecoin client propose-storage-deal t2rzk3c5ok2kwg6z6v4v26qetxft2wg7apifpaq2i QmUUAdFuqxA857pWtgyUxmvHCs7T1mLoeNqUAWWwocP98i 0 10 --enc=json] process.go:190
```

At this point the CPU usage increases as the client node queries for the deal:
```
15:55:54.815  INFO /tmp/TestR: RunCmd: /tmp/TestRetrieval389232326/2 [go-filecoin client query-storage-deal zDPWYqFCvqPwwhk2rQ73PkbvTWCzw9upEoiKxFp3FxJ6Qa36bauH --enc=json] process.go:190
```

The initial setup spends a lot of time waiting for messages to appear on chain, this is not a CPU intensive task. Looking at the timestamps: `15:55:28` to `15:55:49.647` this takes about 20 seconds, which seems inline with what you are experiencing. Given this can we close this issue?

**Comment by anorth** [comment]
Is this a test that will only be run with `-functional`? If so, yes. I expect that a default `go test` will then have no such delays.

But if we're attempting to replace all daemon tests with FAST, and that will cause integration tests to have these delays, then I think we need to do something else. At the very least run them in more parallel, though this will challenge memory pressure (#2516). @travisperson noted somewhere that he had success reducing the block time below 5s.

**Comment by frrist** [comment]
> Is this a test that will only be run with -functional? If so, yes. I expect that a default go test will then have no such delays.

Correct, issuing the command `go test` will only run unit tests, which do not suffer from any delays.

> But if we're attempting to replace all daemon tests with FAST, and that will cause integration tests to have these delays, then I think we need to do something else. At the very least run them in more parallel, though this will challenge memory pressure (#2516).

The plan is to run FAST tests in parallel, which as you have stated will increase our memory usage. However as I understand #2515 this will only cause issues for external contributors. I believe (@ognots please correct me if I am wrong) we can detect the instance size/class we are running on and set `-parallel=1` when running functional and integration tests. This means that tests will run slower, but will no OOM the CI box. I believe this is a reasonable tradeoff.

**Comment by travisperson** [comment]
There are two ways to write FAST tests

1) Using synchronous mining
2) Using asynchronous mining

Functional tests are expected to be able to run against any deployed network (under the assumption that we have a FAST environment define for it). These tests are forced to use the parameters of the network. If the block time is 30s, and we send a message, we must wait for the message to be mined into a block. This will result in low cpu usage as the go-filecoin daemon runs ideal for this time.

The delay you are seeing is from a functional tests, for which there is currently **1** of. The low cpu usage is rather up front in this scenario as there is literately nothing else that can be run at the moment.

What we currently are calling Daemon Tests (gated by the integration flag), are run in a sudo network with synchronous mining. This means we explicitly call `mining once` when we need a block mined. No such delays should exist in this scenario for the most part. Blocktime should be set to an extremely fast time (currently set to 1ms in the payment channel tests). To reduce any delay during the call to `mining once`.
https://github.com/filecoin-project/go-filecoin/blob/a45c0f1a70c2e8a61d6d5b4e01e641bedb344a06/mining/worker.go#L260-L264
https://github.com/filecoin-project/go-filecoin/blob/a45c0f1a70c2e8a61d6d5b4e01e641bedb344a06/mining/worker.go#L128-L130

**Comment by ognots** [comment]
@frrist that's almost correct. there's no way to detect resource class, however. the new testing strategy limits `go test --parallel 2` (in CI only) and then uses CircleCI parallel containers to increase testing concurrency (splits tests up between different containers). For community contributors, they might not have any additional privileges in CircleCI such as parallelism or larger resource classes, but since we've limited go concurrency the tests will still run through at 2x go test concurrency, but just take longer.

**Comment by anorth** [comment]
Ok, thanks all. I think you can close this @frrist.
