### ISSUE TITLE
Miner actor SectorCommitments map should be a lookup

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/go-filecoin#2536]
### Description
All other map datastructures within actor state are implemented as [hamt-based lookups](https://github.com/filecoin-project/go-filecoin/blob/master/actor/storage.go#L159).  From conversation with @acruikshank it looks like the `SectorCommitments` implementation was meant to be moved to a lookup but it slipped through the cracks.

### Acceptance criteria
We have evaluated whether this is the right thing to do.

We have changed the implementation of the `SectorCommitments` map to use a lookup.

### Risks + pitfalls
cc @laser in case this issue is missing key context suggesting we not use a lookup to implement this map.

This change can't be introduced live into a new network without a model for change protocol upgrade (protocol breaking)

### Where to begin
Understand actor lookups and modify miner.go

**Comment by anorth** [comment]
@ZenGround0 FYI this issue might be either redundant or repurposed into your SectorSet(/Map) work

**Comment by anorth** [comment]
I think this is the same as #2888
