### ISSUE TITLE
Remove unnecessary contexts from chain store

### ISSUE THREAD

**Issue by rosalinekarr** [filecoin-project/go-filecoin#2551]
### Description

The following methods in the chain store interface require contexts as an argument but never actually use it:

```
type ReadStore interface {
  ...
  PutTipSetAndState(ctx context.Context, tsas *TipSetAndState) error
  GetBlock(ctx context.Context, id cid.Cid) (*types.Block, error)
  ...
}

type Store interface {
  ...
  HasTipSetAndState(ctx context.Context, tsKey string) bool
  GetBlocks(ctx context.Context, cids types.SortedCidSet) ([]*types.Block, error)
  HasAllBlocks(ctx context.Context, cs []cid.Cid) bool
  HasBlock(ctx context.Context, c cid.Cid) bool
  SetHead(ctx context.Context, s types.TipSet) error
  ...
}
```

As a result, we pass contexts at every invocation of these methods that, in most cases, we never actually use for anything else. We shouldn't be passing around contexts that are never used.

### Acceptance criteria

The `ctx context.Context` in each of the above methods is removed, and all call sites are updated accordingly.

### Where to begin

`chain/store.go`

**Comment by travisperson** [comment]
We probably want to keep the context for metrics / tracing. Also, even if we don't use the context in an implementation, we should strongly considering keeping it as part of the interface. Changing interfaces will become much more difficult later.

/cc @frrist

**Comment by rosalinekarr** [comment]
How does passing an unused argument help with metrics/tracing?

Also, if need the contexts in the future, I'd argue to just re-adding them then. If our code becomes so rigid we can't make changes like that down the road, we'll have much bigger problems to deal with.

**Comment by travisperson** [comment]
> How does passing an unused argument help with metrics/tracing?

Metrics and tracing requires a context to be implemented. 

> Also, if we need the contexts in the future, I'd argue to just re-adding them then.

We may want these contexts in the immediate future and doing the work to remove them may be counter productive to near tear work. I think that is a valid reason not to do this work. I will defer to @frrist though as he has more knowledge around if we would want to gather metrics / tracing information from this interface.

> If our code becomes so rigid we can't make changes like that down the road, we'll have much bigger problems to deal with.

I didn't say we can't make changes, I said it will be much more difficult later. Change to an interface will have to land in a major release (for the package), and the changes we make will have to be discussed and determines to have significant enough impact to warrant the change. The interfaces we design will be used by others outside of go-filecoin itself.

This project is more than just an implementation of a full node, we are also building libraries that will be used by the community at large. The chain store is not part of the Filecoin protocol itself, but breaking interfaces can induce large amounts of code churn for third party developers outside of the go-filecoin project that may be implementing custom solutions.

**Comment by rosalinekarr** [comment]
*IMPORTANT*

After speaking with @frrist async about it, this issue seems to be a matter of debate, so we should *NOT* start any work on it until we make a decision.

**Comment by frrist** [comment]
Here are three reasons I think we should keep them, @travisperson has already touched on most of them.

#### Metric & Tracing:
Both [OpenTracing](https://github.com/opentracing/opentracing-go/blob/master/gocontext.go#L21) and [Opencensus](https://github.com/census-instrumentation/opencensus-go/blob/master/trace/trace.go#L169) use a `ctx` to store tracing data and metric data (they are using `context.WithValue` under the hood). If we want to trace these methods, or produce metrics from them we will need to use a `context` here -- it's what stitches everything together.

#### Syscalls - Network and Disk IO:
If at some point we use the aforementioned interfaces for storing blocks on disk or retrieving them from the network we will want to use a context to allow for graceful cancelation. As Travis pointed out, this depends on the implementation.

#### Breaking Interfaces:
If we remove the context's and later decide we want them (for one of the above reasons) adding them back will change the interface and that can be painful. Travis has summed this up well in his previous comments.

**Comment by rosalinekarr** [comment]
With regard to metrics and tracing, OpenTracing actually offers a singleton implementation which doesn't rely on contexts at all to work, and it actually seems to be the preferred usage of the tool: https://github.com/opentracing/opentracing-go#singleton-initialization

As for retrieving blocks from disk or the network, that's actually done entirely within the `Load` method on the chain store which *does* accept a context and from which I am *not* recommending removing the context argument. Considering that `Load` is part of this interface, I assume that any future implementations would similarly use the `Load` method for interacting with the disk or network.

When it comes to leaving in contexts because re-adding them at a future time would be painful, I think this is actually a code smell for a much larger problem in our project: our function calls are way too deep. Updating a single method signature shouldn't require updating dozens of parent methods above it. We shouldn't be making decisions about the implementation of code on the basis of what requires more or fewer line changes.

I also think leaving these contexts in is harmful because they create a false promise that said contexts will be respected in implementations of the store interface, which the current implementation does not. For example, prior to #2422, the default store's own `Load` method was written with the assumption that the context passed to `GetBlock`, `PutTipSetAndState` and `SetHead` would cause these methods to return an error if the cancelled. They do not, and as a result, the `Load` method itself also could not be cancelled.

**Comment by anorth** [comment]
I am going to close this issue because, as a high level judgement, stores are the kind of component that might do expensive operations (requiring cancellation) and that we will want to instrument with metrics and traces. It's appropriate for contexts to be passed here, even if they are currently unused. It is not worth doing work to remove these right now.

To give my 2c on some of the other justifications presented here:
- Less code is better, and if the contexts were not already in place I would not support adding them prospectively.
- I am not concerned about interface churn at the moment. We have no obligation to support existing internal interfaces in any way and should do whatever supports our implementation velocity. 
 We are not yet producing a library for 3rd party consumption, and will be very explicit about changing that because it has carries an ongoing cost. We will do so in the future, though.
- We won't be using a global/singleton anything if I can help it, although I haven't investigated the Go implementation of opentracing.
