### ISSUE TITLE
Push proofs access to vm.Context

### ISSUE THREAD

**Issue by acruikshank** [filecoin-project/go-filecoin#2555]
### Description

In the current state, the `miner.Actor` has hard dependencies on `proofs` and `proofs/sectorbuilder`. These (and probably some of its other dependencies) are inappropriate for an actor in the VM. Access to proofs may soon be needed by other actors. The interface to proofs should reside in the `vm.Context` and hide as many details about proving as possible from the actor.

This first of all decouples the actor code from the go-filecoin implementation of proving (the dependency on sectorbuilder is particularly problematic here) and furthers our long term goals for the the VM.

As an architectural principal, actors should only act directly on message data and their own state. Any interaction 'outside' the VM should be mediated through the context. The context can be thought of as a set of 'system calls' that allow the actor to interact with the world outside its 'process'.

### Acceptance criteria

1. `miner.Actor` does not depend on the `proofs` or `proofs/sectorbuilder` package.
2. Any proof related actions the miner makes will be accessible through the `vm.Context` to all actors.

**Comment by laser** [comment]
@acruikshank 

> This first of all decouples the actor code from the go-filecoin implementation of proving (the dependency on sectorbuilder is particularly problematic here)

The actor code doesn't depend on the sector builder. The actor code indirectly relies on libfilecoin_proofs (by way of `RustVerifier`). Does that distinction impact your recommendation to move the seal verification call into VM context?

**Comment by acruikshank** [comment]
@laser it wouldn't affect my feelings on this, but the miner actor currently depends on some conversion tools in the sectorbuilder package https://github.com/filecoin-project/go-filecoin/blob/9ce92def3e43314e455ffba3d03161106b89480f/actor/builtin/miner/miner.go#L476.

It would be easy to work around that if it were the only issue. The point is that we should minimize the actor's surface contact with any code that isn't implemented within the VM.

**Comment by whyrusleeping** [comment]
We should have a set of 'builtins' that we can call to from the VM. proof verification can be one of those

**Comment by acruikshank** [comment]
@whyrusleeping I don't have a problem making the functions statically available. My big concern is how do we track what's in and what out at a point where there aren't any limits. Creating a separate package `vm/proofs` or some such would have the same effect. Adding methods to VMContext sends a strong signal though that this code is tied to the VM.

**Comment by anorth** [comment]
@acruikshank I believe you may have completed this recently.

**Comment by acruikshank** [comment]
I did.
