### ISSUE TITLE
Questions about Filecoin daemon

### ISSUE THREAD

**Issue by lin6461** [filecoin-project/go-filecoin#2559]
Soon after running the go - filecoin daemon automatically quit, could you tell me who can tell how to keep it stable running. Thank you very much!
Tip the following information:
`rax    0x0
rbx    0x39ab8b
rcx    0x7f31f83c5428
rdx    0x6
rdi    0x523b
rsi    0x52e8
rbp    0x7f2fe67f5270
rsp    0x7f2fe67f4b88
r8     0x0
r9     0xa
r10    0x8
r11    0x202
r12    0x0
r13    0x7f2fe67f6b70
r14    0x40e0fc60
r15    0x7f2fe67f4d10
rip    0x7f31f83c5428
rflags 0x202
cs     0x33
fs     0x0
gs     0x0
`

**Comment by travisperson** [comment]
How much memory does the machine you are running the node on have?

I'm not sure what the output you provided it, it looks like a sample of a core dump though as I see some register names in there.

**Comment by rosalinekarr** [comment]
@lin6461, can you provide the complete error output including the last few normal logs from the daemon?

**Comment by rosalinekarr** [comment]
I'm closing this issue to due lack of response. @lin6461, if you're still experiencing this issue, let me know, and I'll reopen.
