### ISSUE TITLE
Upgrade libp2p for autorelay fixes

### ISSUE THREAD

**Issue by anorth** [filecoin-project/go-filecoin#2561]
### Description
Libp2p recently landed a bunch of improvements to relay functionality, addressing heavy resource usage observed in some production relay node. We should upgrade to enjoy the same fixes in the filecoin network relay nodes.

### Acceptance criteria
- Filecoin depends on go-libp2p [0.0.13](https://github.com/libp2p/go-libp2p/releases/tag/v0.0.13)
- @raulk acks that this is the right target

### Risks + pitfalls
This should be much easier than the previous upgrade thanks to gomod!

**Comment by vyzo** [comment]
We have a few more fixes in the pipeline, might make sense to wait a few days for v0.0.14.

**Comment by vyzo** [comment]
I think v0.0.16, which has just been tagged, is a good target
