### ISSUE TITLE
A[build] build go-filecoin 0.1.4 fail。Which version of rust-fil-proofs is need for 0.1.4 go-filecoin?

### ISSUE THREAD

**Issue by AndyChen1984** [filecoin-project/go-filecoin#2562]
Describe the bug
go run ./build build fail

/root/go/src/github.com/filecoin-project/go-filecoin/proofs/sectorbuilder/rustsectorbuilder.go:187:3: cannot use _Ctype_ulong(len(pieceBytes)) (type _Ctype_ulong) as type *_Ctype_char in assignment
/root/go/src/github.com/filecoin-project/go-filecoin/proofs/sectorbuilder/rustsectorbuilder.go:186:18: cannot use (*_Ctype_uchar)(cPieceBytes) (type *_Ctype_uchar) as type _Ctype_ulong in assignment

To Reproduce
1、I build rust-fil-proofs on master branch of commit 
      b429279195e08ecf3abd9879a3ef6f3b6fb2e21f.
2、I build filecoin on master branch success，but run report error:
      "code not at same version" at hello session.
3、I find devnet-user need 0.1.4 version，so I checkout code to 0.1.4，and run go run ./build/*.go deps again。

4、go run ./build build report this error.

Screenshots
root@localhost:~/go_path/src/github.com/filecoin-project/go-filecoin# go run ./build build
Building go-filecoin...
git log -n 1 --format=%H
go build -ldflags -X github.com/filecoin-project/go-filecoin/flags.Commit=8158fdfb572e7fdcbd98b42a2e83912b1b4f097e -v -o go-filecoin .
github.com/filecoin-project/go-filecoin/proofs/sectorbuilder
# github.com/filecoin-project/go-filecoin/proofs/sectorbuilder
/root/go/src/github.com/filecoin-project/go-filecoin/proofs/sectorbuilder/rustsectorbuilder.go:187:3: cannot use _Ctype_ulong(len(pieceBytes)) (type _Ctype_ulong) as type *_Ctype_char in assignment
/root/go/src/github.com/filecoin-project/go-filecoin/proofs/sectorbuilder/rustsectorbuilder.go:186:18: cannot use (*_Ctype_uchar)(cPieceBytes) (type *_Ctype_uchar) as type _Ctype_ulong in assignment
Command 'go build -ldflags -X github.com/filecoin-project/go-filecoin/flags.Commit=8158fdfb572e7fdcbd98b42a2e83912b1b4f097e -v -o go-filecoin .' failed: exit status 2
exit status 1

OS: ubuntu 18.04 64bit
Browser [if applicable, e.g. chrome, safari]
Additional context
CPU:ARM A53
aarch64-linux-gnu-gcc (Ubuntu/Linaro 7.3.0-16ubuntu3) 7.3.0

**Comment by travisperson** [comment]
Can you provide the output of the following

```
go version
rustc --version
cargo --version
git rev-parse HEAD
go env
$(go env | grep -E "^CC" |  sed -e 's/.*\=//' | sed -e 's/^"//' -e 's/"$//') --version
```

**Comment by AndyChen1984** [comment]
root@localhost:~# go version
go version go1.12.2 linux/arm64

root@localhost:~# rustc --version
rustc 1.35.0-nightly (53f2165c5 2019-04-04)

root@localhost:~# cargo --version

root@localhost:~# go env
GOARCH="arm64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/root/go"
GOPROXY=""
GORACE=""
GOROOT="/root/go"
GOTMPDIR=""
GOTOOLDIR="/root/go/pkg/tool/linux_arm64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build374557562=/tmp/go-build -gno-record-gcc-switches"

root@localhost:~# $(go env | grep -E "^CC" |  sed -e 's/.*\=//' | sed -e 's/^"//' -e 's/"$//') --version
gcc (Ubuntu/Linaro 7.3.0-27ubuntu1~18.04) 7.3.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

root@localhost:~/go_path/src/github.com/filecoin-project/go-filecoin# git rev-parse HEAD
8158fdfb572e7fdcbd98b42a2e83912b1b4f097e

root@localhost:~/go_path/src/github.com/filecoin-project/go-filecoin# git status
HEAD detached at 8158fdfb
nothing to commit, working tree clean

**Comment by travisperson** [comment]
For gcc we require v7.4.0 or later. You can resolve this issue by installing clang or upgrade to gcc v7.4.0

**Comment by AndyChen1984** [comment]
> For gcc we require v7.4.0 or later. You can resolve this issue by installing clang or upgrade to gcc v7.4.0

Sorry to interrupt.The error still report after I installed clang.   
 I can build master branch successfully,and I check the code. I dont't understand why report this error.

root/go/src/github.com/filecoin-project/go-filecoin/proofs/sectorbuilder/rustsectorbuilder.go:187:3: cannot use _Ctype_ulong(len(pieceBytes)) (type _Ctype_ulong) as type _Ctype_char in assignment
/root/go/src/github.com/filecoin-project/go-filecoin/proofs/sectorbuilder/rustsectorbuilder.go:186:18: cannot use (_Ctype_uchar)(cPieceBytes) (type *_Ctype_uchar) as type _Ctype_ulong in assignment

On my machine，I find the type is matched in code:
\github.com\filecoin-project\go-filecoin\proofs\rust-fil-proofs\target\release\libfilecoin_proofs.h
AddPieceResponse *add_piece(SectorBuilder *ptr,
                            const char *piece_key,
                            const uint8_t *piece_ptr,
                            size_t piece_len);

\github.com\filecoin-project\go-filecoin\proofs\sectorbuilder\rustsectorbuilder.go
resPtr := (*C.AddPieceResponse)(unsafe.Pointer(C.add_piece(
		(*C.SectorBuilder)(sb.ptr),
		cPieceKey,
		(*C.uint8_t)(cPieceBytes),
		C.size_t(len(pieceBytes)),
	)))
github.com\filecoin-project\go-filecoin\proofs\rust-fil-proofs\filecoin-proofs\src\api\mod.rs

pub unsafe extern "C" fn add_piece(
    ptr: *mut SectorBuilder,
    piece_key: *const libc::c_char,
    piece_ptr: *const u8,
    piece_len: libc::size_t,

**Comment by travisperson** [comment]
If go is not picking up clang by default you will need to get `CC=clang` you can do that by running `export CC=clang` or `env CC=clang` before running deps & build.

If you still run into issues, please include the output of
```
go env
$(go env | grep -E "^CC" |  sed -e 's/.*\=//' | sed -e 's/^"//' -e 's/"$//') --version
```

**Comment by AndyChen1984** [comment]
> If go is not picking up clang by default you will need to get `CC=clang` you can do that by running `export CC=clang` or `env CC=clang` before running deps & build.
> 
> If you still run into issues, please include the output of
> 
> ```
> go env
> $(go env | grep -E "^CC" |  sed -e 's/.*\=//' | sed -e 's/^"//' -e 's/"$//') --version
> ```

I have compiled 0.1.4 tag successfully.
Thank you very much!
