### ISSUE TITLE
[bug] cant build go-filecoin

### ISSUE THREAD

**Issue by whyrusleeping** [filecoin-project/go-filecoin#2566]
```
why@WhyNet ~/g/s/g/f/go-filecoin> make deps
go run ./build/*.go smartdeps
pkg-config --version
0.29.2
Installing dependencies...
go mod download
verifying github.com/libp2p/go-libp2p-secio@v0.0.1: unexpected ziphash: ""
Command 'go mod download' failed: exit status 1
exit status 1
make: *** [deps] Error 1
```

**Comment by rosalinekarr** [comment]
@whyrusleeping, can you please update to use the bug report template?

**Comment by whyrusleeping** [comment]
Still happening on latest master at this point: 48868f99d02dcca362d5600258e29d77dd06b7c1

**Comment by rosalinekarr** [comment]
@Why, did @frrist's suggestion of running `go clean -n -modcache` resolve your issue?

**Comment by rosalinekarr** [comment]
Closing due to no response. @whyrusleeping, if you're still having this problem, let me know and I'll reopen.

**Comment by whyrusleeping** [comment]
Nope, running `go clean -n -modcache` did not resolve the issue. I also did not see that suggestion. And waiting less than a day before closing an issue is not okay.

**Comment by shannonwells** [comment]
What happens if you run dumb deps?  Maybe try manually deleting it from `pkg/mod` ?  https://github.com/imdario/mergo/issues/93

I'd also make sure that clearing the cache actually deleted the cache, just in case there is some weird permissions problem.  $GOPATH/src/v/cache

**Comment by whyrusleeping** [comment]
@shannonwells ah, yeah. Looks like deleting my pkg/mod cache did the trick, thanks!

**Comment by shannonwells** [comment]
awesome, I'll go ahead & close if no objections.
