### ISSUE TITLE
Miner confirms client's Data Commitment

### ISSUE THREAD

**Issue by acruikshank** [filecoin-project/go-filecoin#2572]
### Description

The client will be including a data commitment within each of the payments they make to a miner. If this data commitment isn't correct, the miner may not get paid for storage. The miner must validate the data commitment before staging the piece.

After the miner receives all the data from the client, they will generate the data commitment using the same rust proofs function used by the client to generate the data commitment in the first place. If the commitment doesn't match the commitment in all the vouchers, the deal is off.

### Acceptance criteria

Miner rejects deal if data commitment in any of the payment vouchers does not match the data commitment the miner generates from the received data, the miner will terminate the deal.

**Comment by anorth** [comment]
Is this story blocked on proofs, or can we do most of the work anyway?

**Comment by acruikshank** [comment]
@anorth There is likely a fair bit of go-filecoin work:

1. Adding the call to fetch the data commitment
2. Wrangling the data in preparation for the rust-proofs call
3. Handling errors on either the go side or the rust side
4. Creating a place for the commitment in the voucher and storing it there.

A fake implementation might be worthwhile to keep the epic moving. We'd still need to coordinate closely with proofs to decide what kind of data wrangling we need to do and where the fake boundary should live.

**Comment by acruikshank** [comment]
This story needs the data commitment to be in the deal (#2568) before the miner can verify it.
