### ISSUE TITLE
Cannot generate replication certificate

### ISSUE THREAD

**Issue by ytQiao** [filecoin-project/go-filecoin#2577]
I created a number of miners, one of whom transmitted more than 400 M files to another miner, but after a considerable period of time, the miner still had no storage space and generated a copy certificate.

Machine configuration: CPU: AMD 200GE, 8G memory, 4T hard disk.

Is this configuration too weak to complete the replication certification, or is there a BUG in go-filecoin?

**Comment by rosalinekarr** [comment]
@ytQiao, your setup sounds fine, so this may be a bug. Can you please update the issue to use our bug report template and include steps to reproduce the problem?

**Comment by rosalinekarr** [comment]
Closing due to lack of response. @ytQiao, if you're still having this problem, let me know and I'll reopen.

**Comment by ytQiao** [comment]
@ZenGround0 Thank you for your reply. I have solved this problem.
There may be several reasons for this problem.
1. Miner M go-filecoin mining stop under unknown conditions.
2. My configuration is a little low.
After I improved my configuration, I basically did not have the problem of exceeding the context time limit, and could already display the sealed space on the network statistics dashboard.
