### ISSUE TITLE
[bug] Mining Once and Mining Start don't work as expected when used together

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/go-filecoin#2579]
**Describe the bug**
Mining Once and Mining Start aren't safe to use together.  This is a placeholder issue that needs more work to describe the underlying race and exactly the conditions that cause this to work poorly.

**To Reproduce**
Try to include a message using mining once while running mining start and watch as it is sometimes not included.  FAST is an example of a place where this shows up because that framework uses once as part of some builtins.  I recently ran into behavior where running start on the FAST genesis miner and allocating funds using the builtin functions that wrap once ends up in lost data where the transfer of funds does not show up in the blockchain.  This is an unintuitive and tough to debug issue we should address sooner rather than later.

**Expected behavior**

once and the main loop triggered by start should never cause races on which blocks are included.  There should be a clear mental framework for understanding how to use these two commands together.

**Screenshots**

**Version information**
- Version: 8ea4ff036100e6960a91a19e01c9bfb72114d100

**Additional context**

@laser and I ran into this bug a while ago during post integration.  I promised I'd write it up but did not 👎 .  IIRC there is a race between including blocks with once and the main mining loop triggered by start that is not too hard to see if you go into the node code looking for it.

**Comment by anorth** [comment]
I would not have expected the two mining modes to be compatible. Could you outline the use case for mixing them?

Without a strong reason, I think we could just document them as incompatible and move on.

**Comment by frrist** [comment]
Could we disallow them being used together? -- e.g. if `mining start` has been called all calls to `mining once` return an error.

**Comment by anorth** [comment]
SGTM
