### ISSUE TITLE
Create repo migration validation strategy with sample tests

### ISSUE THREAD

**Issue by shannonwells** [filecoin-project/go-filecoin#2583]
### Description
Repo migration validation strategy isn't entirely figured out yet.  Decide on good tests for working out that the migration succeeded.  

Definitely: 
Run daemon tests that do some queries on all parts of the newly migrated datastore, such as chain, deals, keystore, and wallet.

Possibly:
Generate toy repos that need to be migrated, migrate them and run daemon tests that write to the repo: mining, propose deals, create miner, etc.  These would be included as fixtures for each migration in the migration directory.

### Acceptance criteria
Migration tests exercise reads on all areas of an existing repo, and even better, exercise write tests on all areas of a fixture repo.

### Risks + pitfalls
It may not be realistic to ship even a small repo around with a release, even if it's limited to just the last migration.

**Comment by anorth** [comment]
For repo validation (the automated checks that are executed along with a migration) I think daemon tests are excessive. I think simple but thorough inspection of the parts of the repo that have been changed would suffice.

For unit testing the go-filecoin node in the post-migration state, daemon tests are appropriate (but we should mostly already have them).

**Comment by shannonwells** [comment]
See PR #2880, first migration for where to start with migration validation.  It's validated against a repo fixture that is unpacked for test.
