### ISSUE TITLE
Provide configuration which allows a miner to select PoSt and PoRep proof partitions

### ISSUE THREAD

**Issue by laser** [filecoin-project/go-filecoin#2592]
### Description

A miner can impact the number of PoSt and PoRep proof-bytes in the `submitPoSt` and `commitSector` messages that they generate by adjusting the number of `PoStProofPartitions` and `PoRepProofPartitions` used when generating proofs. 

A miner who has a lot of RAM may elect for a small number of proof partitions which means larger circuits and smaller proofs. This costs them less gas (in the `submitPoSt` and `commitSector` messages) than if they decide to prove with a large number of proof partitions (which would require less RAM but would produce larger proofs).

### Acceptance Criteria

- A miner operator should be able to configure their go-filecoin node to use a particular number of PoRep and PoSt proof partitions.
- The choice of PoRep and PoStProof partitions should be constrained to some set of values (see `types.PoRepProofPartitions`).

### Open Questions

- When should configuration changes be reflected in the behavior of rust-fil-proofs? After a go-filecoin node restart?

**Comment by laser** [comment]
It is not clear to me if this configuration should be a part of go-filecoin or the `rust-fil-proofs.config.toml` configuration file.

**Comment by anorth** [comment]
Such configuration will move to the storage mining module (if it remains relevant).
