### ISSUE TITLE
[bug] Message pool panics due to concurrent map access under load

### ISSUE THREAD

**Issue by steven004** [filecoin-project/go-filecoin#2630]
**Describe the bug**
The filecoin daemon will crash while facing non-stop deal-proposals from a client. 

**To Reproduce**
1. Run a filecoin daemon and start mining with predefined asks
2. From another node, using a scripts for send deal-proposal requests, one per 3 minutes. Some requests fail, some succeed. 
3. Keep the system running, you will see the system crash. 

**Expected behavior**
The system could keep running; 
While the sealing could not catch up the speed as the request; it could respond an appropriate error to the client. 

**What we see from the output**
When it happens, we see
1) consensus Info with *Nonce too low*, keep the same message with different signatures for some time;
2) then, mining Info with *permanent ApllyMessage failure* come out, and keep going with the same message ...... 
3) Finally, it hit fatal error, and print out >25000-line backtrace info. 

**Version information**
go-filecoin dev-testnet-0.1.4
on my ubuntu 18.4-LTS

**Log file**
[2019-04-19_11-42-17_short.log](https://github.com/filecoin-project/go-filecoin/files/3102404/2019-04-19_11-42-17_short.log)

**Comment by frrist** [comment]
Hi @steven004, thanks for filing this. 

In the interest of reproducing this panic would you mind sharing the script you use for the deal making process?

----------------------------

The panic provided in the log file is indeed quite long. It seems to indicate that we have a concurrency bug around message pool:
```
fatal error: concurrent map iteration and map write

goroutine 19381 [running]:
runtime.throw(0x15761c5, 0x26)
	/usr/local/go/src/runtime/panic.go:617 +0x72 fp=0xc0f69e1c68 sp=0xc0f69e1c38 pc=0x4e01f2
runtime.mapiternext(0xc0f69e1d48)
	/usr/local/go/src/runtime/map.go:860 +0x597 fp=0xc0f69e1cf0 sp=0xc0f69e1c68 pc=0x4c19e7
github.com/filecoin-project/go-filecoin/core.(*MessagePool).timeoutMessages(0xc0131f8030, 0x17c8220, 0xc063c7b600, 0x7ef8a0723680, 0xc0004bf180, 0xc0af7db3e0, 0x40, 0x80)
	/root/go/src/github.com/filecoin-project/go-filecoin/core/message_pool.go:185 +0x203 fp=0xc0f69e1db8 sp=0xc0f69e1cf0 pc=0xbb83f3
github.com/filecoin-project/go-filecoin/core.(*MessagePool).UpdateMessagePool(0xc0131f8030, 0x17c8220, 0xc063c7b600, 0x7ef8a0723680, 0xc0004bf180, 0xc10180c450, 0xc0af7db3e0, 0x0, 0x0)
	/root/go/src/github.com/filecoin-project/go-filecoin/core/message_pool.go:155 +0x465 fp=0xc0f69e1ec8 sp=0xc0f69e1db8 pc=0xbb8195
github.com/filecoin-project/go-filecoin/node.(*Node).handleNewHeaviestTipSet(0xc00000c1e0, 0x17c8220, 0xc063c7b600, 0xc10180c450, 0xc069bd18c0)
	/root/go/src/github.com/filecoin-project/go-filecoin/node/node.go:660 +0x346 fp=0xc0f69e1fb8 sp=0xc0f69e1ec8 pc=0xcc84f6
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc0f69e1fc0 sp=0xc0f69e1fb8 pc=0x50f791
created by github.com/filecoin-project/go-filecoin/node.(*Node).Start
	/root/go/src/github.com/filecoin-project/go-filecoin/node/node.go:543 +0x7f1
```

**Comment by steven004** [comment]
> In the interest of reproducing this panic would you mind sharing the script you use for the deal making process?

@frrist , the script is pretty simple, I import a bunch of contents (files) into the client node, and name them with the corresponding cid, then, run the following script: 
``` bash
for i in {1..180}
do 
	for cid in `ls temp | cut -d '.' -f 1`;
	do
		echo "go-filecoin client propose-storage-deal t2x5nkatu5ozgbyhsye56lyxjd2aspzsrbbquohoi $cid 1 2880 --allow-duplicates"
		go-filecoin client propose-storage-deal t2x5nkatu5ozgbyhsye56lyxjd2aspzsrbbquohoi $cid 1 2880 --allow-duplicates
		sleep 200
	done
done
```

From the log, the message-pool handling has some problems when dealing some time-out messages.

**Comment by steven004** [comment]
The possible cause: 
The panic happens on filecoin-project/go-filecoin/core/message_pool.go:185, which is: 
`for cid, msg := range pool.pending {`

That means the code is reading the map, however, the map could be being written simultenuously, then, it happened. 
If it makes sense, I would suggest use RLock for read, and Lock for write separately in this module.

**Comment by ZenGround0** [comment]
Hey @steven004 I am suspicious that this is the same bug originally patched [here](https://github.com/filecoin-project/go-filecoin/pull/2486) and actually [here](https://github.com/filecoin-project/go-filecoin/pull/2522/files).  I believe this problem is fixed on master and will stop showing up after the next release.

I'm going to close this for now.  If you want to test this out on master against the nightly cluster and report back that would be useful.  Feel free to reopen if you have reason to think master hasn't fixed the problem.
