### ISSUE TITLE
Investigate optimizing HAMT width

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/go-filecoin#2635]
### Description
The filecoin node's disk usage is dominated by storing state.  Part of the reason this is so disk heavy is that we currently write an entire HAMT node for every new state.  Flip a bit in any actor's storage and you write ~2kb.  This means that every new tipset writes a new HAMT node.  This is actually worse because we need to process blocks on their own for verification so a tipset with `n` non-identical blocks results in `n+1` HAMT node writes.  See [this writeup](https://docs.google.com/document/d/1-EUt0Oj5O5Simb8OWW_hVGDC3_W7iyJnnF4HgW6gsbA/edit?usp=sharing) for evidence and repro steps.

[@whyrusleeping has suggested](https://github.com/filecoin-project/go-filecoin/issues/2533#issuecomment-484234857) that investigating and modifying HAMT parameters (specifically making the HAMT less wide) could help with deduplication.  We should do this to reduce state storage's disk footprint.

### Acceptance criteria
An analysis of HAMT parameter effect on storage footprint.  Ideally a sketch of theory with experimental results.  This should include impact on time.

Changes to go-filecoin that optimize the code in the way suggested by the analysis. 

### Risks + pitfalls
We don't have a lot of well established metrics for analyzing performance of go-filecoin.  A good place to start is disk usage and time to sync some standard chain.  Measuring on nightly/user net is probably ok for now.

This could tradeoff space and time to process a chain, we don't have a well defined set of requirements for what we want to make an optimal decision in the face of tradeoffs.

### Where to begin
Define metrics, measure existing implementation.  Sync with @whyrusleeping on HAMT width, read the [HAMT source](https://github.com/ipfs/go-hamt-ipld).  Look at go-filecoin state/tree.go.

**Comment by whyrusleeping** [comment]
One great way to investigate this would be to write a test in the hamt repo that writes a value of some set size (maybe 32 byte key, 100 byte value), flushes the hamt, then repeats N times. At the end of the test, check what the total size of all objects written to the blockstore is.

We can then tweak the width and see how it affects those numbers.

**Comment by anorth** [comment]
@hannahhoward I believe you're looking into this now, so pulling up and assigning to to you.

**Comment by anorth** [comment]
Done!
