### ISSUE TITLE
Can go-filecoin work on a assigned path,not  "~/.filecoin"?Just like IPFS can export IPFS_PATH.

### ISSUE THREAD

**Issue by AndyChen1984** [filecoin-project/go-filecoin#2647]
### Description
Please first see README for how to get help before filing a new issue.

**Comment by ZenGround0** [comment]
Hey @AndyChen1984 in the future could you direct questions that are about go-filecoin usage and not about bugs, development or feature requests to our discussion board: https://discuss.filecoin.io/ ?

The answer is yes, you can run all commands with the `--repodir` flag (see help text for more details) or by setting the `FIL_API` env var.

We used to document the environment variables read by go-filecoin but that seems to have vanished 😕.  I'll open an issue to surface that documentation better.

**Comment by ZenGround0** [comment]
Woops meant `FIL_PATH` env var.

**Comment by AndyChen1984** [comment]
OK.I got it.Thanks for reply.
