### ISSUE TITLE
filecoin command that prints diagnostic information

### ISSUE THREAD

**Issue by frrist** [filecoin-project/go-filecoin#2652]
### Description
We should make it as simple as possible for users to provide developers with the relevant information they need to debug a problem. Our issue template asks for a lot of this  already, go version, filecoin version, OS, etc. but collecting all that information can sometimes be challenging. I propose that we add a command go-filecoin to automate that work.

Feedback on acceptance criteria would be appreciated -- what information have you found helpful when debugging a problem?

### Acceptance criteria
go-filecoin has a command (`go-filecoin diag`) that provides the following information:
 - system
   - cpu
   - memory
   - disk s
- runtime
  - arch (amd64, arm, etc)
  - compiler (gc)
  - os (linux, windows, osx)
  - version (go1.11.4)
  - relevant env vars (`GO_PATH`)
- config
  - wallet addresses
  - miner address
  - autoseal
  - dashboard endpoint
- network
  - number of connected peers
  - interface addresses
  - online/offline status
  - bootstrap addresses
- filecoin
  - chain head
  - mpool size
  - files stored (`go-filecoin client import`) and their sizes
  - list of all commands ran
  - mining status
  - related env vars (e.g. `FIL_PATH`)

### Risks + pitfalls
Some of the information in env vars could be sensitive

### Where to begin
Prior Art: https://github.com/ipfs/go-ipfs/blob/master/core/commands/sysdiag.go#L17

**Comment by anorth** [comment]
This proposal has great potential to ease our remote debugging efforts. Some of these diagnostics may be harder to obtain than others, but we should not block landing something useful on waiting for those. I suggest that the acceptance criteria for this issue be reduced to a minimum set of easily-obtainable diagnostics to start.

**Comment by anorth** [comment]
See #2443 for a listing of commands executed.

**Comment by dayou5168** [comment]
great!
