### ISSUE TITLE
Replace go-log with a backend that provides structured logging

### ISSUE THREAD

**Issue by frrist** [filecoin-project/go-filecoin#2653]
### Description
The design doc proposing a refactor of go-log is on ice until someone with the bandwidth can pick it up. In the meantime I propose that go-filecoin drops go-log and replaces it with a logging framework capable of supporting structured logging, my preference is [logrus](https://github.com/sirupsen/logrus). Logrus's logger is compatible with the API used by go-log, meaning the change to go-filecoin will be fairly mechanical. 

Taking this change will mean logs produced by libp2p will be of a different format than go-filecoin. I believe this is a non-issue as we [rely on those for surfacing errors](https://github.com/filecoin-project/go-filecoin/blob/master/main.go#L31-L41) and not for inspecting go-filecoin process execution.

### Acceptance criteria
- go-log is replaced as a dependency by logrus 
- log messages containing fields: CIDs and Multi-Addresses are modified to use logrus's [FieldLogger](https://github.com/sirupsen/logrus/blob/master/logrus.go#L139) interface.

**Comment by anorth** [comment]
@ognots @gmas @travisperson, please voice any concerns.
@whyrusleeping @raulk FYI.
@rosalinekarr wrt https://github.com/ipfs/go-log/issues/60 - this may give us the desired configurability.

@frrist informs me that if the go-log facade proposal is later accepted and we wish to switch back, that will also be a low-risk change.

I support this proposal in the absence of any major technical concerns.

**Comment by whyrusleeping** [comment]
I don't think this is the best use of the dev teams time right now (to make the changes, review them well enough, and to adapt everyone to a different logging interface). Compared to the huge number of other things needing to be done, this should rank pretty low.

**Comment by raulk** [comment]
looping in @bigs - pertinent to the discussion we just have about normalising logging across libp2p.

**Comment by rosalinekarr** [comment]
Fwiw, imo, the work here will be well worth it when we need to debug issue on the DevNet during releases, and it could also unblock some seriously beneficial improvements to FAST's error reporting.

**Comment by anorth** [comment]
I agree with @whyrusleeping in the sense that we should have a concrete and fairly immediate need to motivate actually doing the work for this. Testing and/or debugging may be that need, but I think we should actually experience some great difficulty that this would resolve rather than just a hypothetical.

I'm putting this in the backlog for now.
