### ISSUE TITLE
[bug]Error: error creating payment: failed to add message 

### ISSUE THREAD

**Issue by dayou5168** [filecoin-project/go-filecoin#2655]
when i try to store data in my other filecoin node 
i got this err:
Error: error creating payment: failed to add message to outbound queue: Invalid nonce 457, expected 456

and i notice that : when the block height is low , i store so many times ,no err happen, when the block height increase,i got this err  frequently
does this hapen related with the block height?

**Comment by shannonwells** [comment]
Hello @dayou5168, please fill out the missing information from the Bug report template so we can diagnose this issue.  Otherwise we will have to close.

**Comment by dayou5168** [comment]
@shannonwells 
ok ,i will get the detail information later and report again,
you can close this issue now

**Comment by shannonwells** [comment]
Thank you, @dayou5168, we'll look at it as soon as possible once you have posted the new report.
