### ISSUE TITLE
Add FAQ for getting funds from faucet

### ISSUE THREAD

**Issue by travisperson** [filecoin-project/go-filecoin#2659]
### Description
User reported issues with recieving funds from the faucet:

- https://filecoinproject.slack.com/archives/CEGN061C5/p1555503741037200
- https://filecoinproject.slack.com/archives/CEGN061C5/p1554801231009900
- https://filecoinproject.slack.com/archives/CEGN061C5/p1551915373022800
- https://filecoinproject.slack.com/archives/CEGN061C5/p1549146594135200
- https://github.com/filecoin-project/go-filecoin/issues/2560
- https://github.com/filecoin-project/go-filecoin/issues/2212
- https://github.com/filecoin-project/go-filecoin/issues/2166
- https://github.com/filecoin-project/go-filecoin/issues/2137

The chain currently can take quite a while and we don't call this out in the wiki when we tell the user how to get funds. We actually tell them it should only take 30 seconds. While this is true for a synced chain, it's misleading to most user which will have probably just have setup a node. Depending on the age of the network, syncing can take hours if not days.

> 1. The faucet will provide you with a message CID. The message should be processed in about 30 seconds. You can run the following command to wait for confirmation:
>
>    ```Shell
>    go-filecoin message wait ${MESSAGE_CID}
>    ```
>
> 1. To verify that the FIL has landed in your wallet, check your wallet balance:
>    ```Shell
>    go-filecoin wallet balance ${WALLET_ADDR}
>    ```
_[Get FIL from the filecoin faucet](https://github.com/filecoin-project/go-filecoin/wiki/Getting-Started#get-fil-from-the-Filecoin-faucet)_

### Acceptance criteria

- Add messaging in the "Get FIL from the Filecoin faucet" wiki article telling the user that the `message wait` step may take a while if they just recently setup their node, tell the user they should check `https://stats.kittyhawk.wtf` for current block height before, and used `go-filecoin show block $(go-filecoin chain head | head -n1)` to see where their node is.
- Add a FAQ explaining this process a bit more in depth (Issue #2560 might be a good place to start

### Where to begin

https://github.com/filecoin-project/go-filecoin/wiki/Getting-Started#get-fil-from-the-filecoin-faucet

**Comment by shannonwells** [comment]
I made some updates to [Get FIL from the Filecoin Faucet](https://github.com/filecoin-project/go-filecoin/wiki/Getting-Started#get-fil-from-the-filecoin-faucet) and I added an FAQ section with a little more detail using a modified version of your copy here and in the linked issue(s): [Problems caused by incomplete chain sync](https://github.com/filecoin-project/go-filecoin/wiki/Troubleshooting-&-FAQ#problems-caused-by-incomplete-chain-sync)

If they search on "faucet" or "message wait" people will find the info.
