### ISSUE TITLE
CircleCI should not use golang:latest

### ISSUE THREAD

**Issue by travisperson** [filecoin-project/go-filecoin#2662]
### Description

Currently we use `circleci/golang:latest` in a few places in CI. We should be using the version we recommend in our README everywhere in CI.

### Acceptance criteria

- All uses of `circileci/golang:latest` are switched to `circileci/golang:1.12.1`

### Risks + pitfalls

- We do not discover issues around using new version of golang.
  **note** if we want this we should setup a nightly job to run against latest, or a set of other versions that we can use as an indicator.

### Where to begin

- https://github.com/filecoin-project/go-filecoin/blob/master/.circleci/config.yml

**Comment by travisperson** [comment]
I want thoughts / feedback from @ognots before we move this forward anywhere.

**Comment by ognots** [comment]
yup let's do this. using the `latest` Docker tag is problematic in many ways.
