### ISSUE TITLE
Chain sync status messages

### ISSUE THREAD

**Issue by mishmosh** [filecoin-project/go-filecoin#2669]
### Description
When we fetch the chain we periodically print out the height of the most recent block we've fetched from the network: 20,000, 15,000, 10,000. This makes users feel like something is going wrong. We say we are "syncing" blocks up to this height, we should say "fetching". Also we should count forwards, not backwards.

### Acceptance criteria
- Status messages that say "syncing" should say "fetching" instead.
- Count forwards, not backwards.

### Risks + pitfalls
none

### Protocol Changes
none

### Where to begin
- Here's the output line: https://github.com/filecoin-project/go-filecoin/blob/master/chain/default_syncer.go#L144
- Counting should happen in `collectChain: https://github.com/filecoin-project/go-filecoin/blob/master/chain/default_syncer.go#L102
- If you are picking this up, please tag @ZenGround0 to review the PR.

**Comment by anorth** [comment]
There is currently a log message "chain synced" after the chain has been *downloaded* but not *verified*, the latter of which takes much longer. This is very misleading. We should at least not say "synced" at this point.

https://filecoinproject.slack.com/archives/CEHTVSEG6/p1556552276044700

**Comment by tianfangk** [comment]
> There is currently a log message "chain synced" after the chain has been _downloaded_ but not _verified_, the latter of which takes much longer. This is very misleading. We should at least not say "synced" at this point.
> 
> https://filecoinproject.slack.com/archives/CEHTVSEG6/p1556552276044700

Yes, I'm so confused with this "chain synced". Once I think that I have completed the synchronization.

**Comment by mishmosh** [comment]
@anorth are you referring to a separate message from the ones outlined in the original description? Perhaps https://github.com/filecoin-project/go-filecoin/blob/66089103c636ac52bf0ef3bdaca18bafdc210b6b/chain/default_syncer.go#L113?

**Comment by anorth** [comment]
Yes, I am
