### ISSUE TITLE
Client Validates piece inclusion proof in deal

### ISSUE THREAD

**Issue by acruikshank** [filecoin-project/go-filecoin#2676]
Blocked on #2571

### Description

Once a deal is in the POSTED state, it should include a sector id and a piece inclusion proof (#2571). The proof proves that the client's piece is included within the sector represented by the sector id.

Upon making a deal state request and seeing the deal is in the posted state, the client should check for the existence of the pip and check it's validity. This can be done using `verifyPieceInclusion` on the storage miner's miner actor (#2625).

If the piece is not valid, the client should immediately cancel payment by calling cancel on the payment channel (#2621). If the miner cannot respond to the cancel by posting a voucher with a valid proof on chain, the client will be able to retrieve their funds.

### Acceptance criteria

1. Upon receiving a POSTED deal state, the client waits for the commitSector message and then runs a `verifyPieceInclusion` query. If the query succeeds, halt.
2. If the query fails, the client immediately calls `cancel` on their payment channel.
3. This flow with both a success and failure case is integration tested.

**Comment by laser** [comment]
@ingar - Code pointer for the `cancel` thing: https://github.com/filecoin-project/go-filecoin/blob/8de8451d1ac6be4c3b1f850460269a0294bb3d3f/actor/builtin/paymentbroker/paymentbroker.go#L404
