### ISSUE TITLE
go-filecoin init symlinks to ~/.filecoin/repo to a version-named repo directory sibling

### ISSUE THREAD

**Issue by shannonwells** [filecoin-project/go-filecoin#2684]
### Description
Repo migrations will be taking a similar approach to traditional database migrations, where the location of the database dir is actually a symlink pointing to a version-named directory.  Because of this we want to make `go-filecoin init` set up the repo as a version-named directory and then symlink the canonical name to it.
```
~/.filecoin   -> .filecoin-201903012000-v2 # canonical repo path symlinks to repo dir
~/.filecoin-201903012000-v2 # the actual repo
~/.filecoin-201901122000-v1 # pre-migration, now unlinked
~/.filecoin-sectors
```

Then `go-filecoin-migrate` can:
- assume the repo to be migrated exists as a symlink at the canonical path `$FIL_PATH` and follow it to find the directory to clone, or
- have an optional `--old-repo` CLI arg point to a repo directory (not symlink) to copy instead

### Acceptance criteria
`go-filecoin init`, creates ~/.filecoin-v201901122000-v1 (or something like it) and symlinks to `~/.filecoin` 

The directory name should be in the same format expected to be used for migrated repos.

### Risks + pitfalls
This change is backwards incompatible, so devs will need to either re-init or manually rename and symlink the repo directory *in order to run any migration*. Note that at the next release, all user devnet nodes will need to re-init in any case.

**Comment by anorth** [comment]
See also #2524 and beware of any follow-on changes to the env var, what the "repo" refers to, etc.

It would be really great to land this before release so that we can use it for migrations.

**Comment by anorth** [comment]
@shannonwells I have updated the description here to better reflect the directory layout after #2524. I also clarified my understanding of the migration's expectations. I think that the --old-repo arg may be omitted in the usual case, but if specified should point to a directory.

**Comment by anorth** [comment]
I have updated the description again to reflect the decision in #2687
