### ISSUE TITLE
What to do about the default repo layout?

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/go-filecoin#2687]
# What is the problem?
PR #2658 introduced the model explicitly outlined in #2524.  This new model caused issues for @laser addressed here: #2683, and during the discussion @travisperson raised a bunch of [issues with the new model](https://github.com/filecoin-project/go-filecoin/pull/2682#issuecomment-487989338).

# What is this issue for?
Outlining the two main courses of action and the different branches within each, including pros and cons, and a rough set of work that will need to be done to get any path finished.

# Acceptance Criteria?
A decision is made and I know 1) what we want long term and 2) what I am going to do to safely close out this workstream for the release

# Paths forward
## Keep Latest Changes
By default there is a single directory for persistent storage (home).  One subdirectory for sector storage (sectors), one subdirectory for all data that can be subject to migrations (repo).
* Pros 
	* default separation of go-filecoin and rust-fil proofs data. (See #2524 for exhaustive list of pros)
	* particularly migrations can copy the migrate-able data easily without having to handle large amounts of out of scope sector data by default

* Cons: 
	* directory structure grows in complexity.  Right now users (tests) need to think about two directories (home and repo)
	* just specifying the repo dir with the unchanged —repodir flag isn’t enough to separate sector storage into a separate directories which means lots of different users write to the same sector storage

* TODO: 
	* All paths forward require the homedir expansion fix in PR 2682

### Path forward 1a
Allow daemon to specify homedir with a —homedir flag and change tests to use this to specify a segregated testing path for both sector storage and repo storage.  Also FIL_PATH would reference the homedir and FIL_REPO_PATH would now reference the repo dir.  No tests would need to specify the repo dir or sectors dir, we could even remove those flags.
* Pros:
	* only one flag makes it easier on users
        * config path is determined by homedir flag unless user is doing something weird
* Cons: 
	* interaction between —homedir and —repodir might confuse users
	* config file path is a little harder to infer from a —homedir flag passed in 

* TODO:
	* Fix environment variables and flags to work as described
	* Update all callers (tests) to use homedir instead of repodir.  This includes messing with paths iptb uses that assume config is directly under the passed in directory
	* Update documentation

### Path forward 1b
Maintain default separation of migrate able data and sectors but the node only references a single directory ever unless a power user messes with the config.  The repo would again by the top level directory and could be specified by the —repodir  or FIL_PATH.  By default the repo would contain two directories migrateable and sectors.
* Pros: 
	* only one directory in the mental model by default
* Cons: 
	* the repo abstraction would not map to the “repodir” which is confusing and keeps us from cleanly abstracting sector storage out of the Repo struct in go-filecoin
	* config file path is still not at the —repodir path

* TODO:
	* basically undo last commit I made in PR 2658
	* This would include messing with some iptb assumptions and either adding in “migrateable” to the home path specified when reading/writing the config not through the daemon abstraction.

### Path forward 1c
Simply use @laser’s sectordir flag and make no other changes.  Users are maximally committed to the homedir-default, repodir/sectordir-config model which is self consistent
* Pros:
	* repodir still means what it used to mean and it is the path which contains config, api, lockfile etc
* Cons: 
	* two flags needed for users (tests) to work correctly, lots of test rewriting
	* lots of opportunity for mistakenly writing into the same home dir if you don’t pass two flags / env vars in
	* users now need to think about at least 2 and sometimes 3 directories :(
	* doesn’t seem to scale for when users specify lots of different paths, implicitly assumes sector storage is special

## Revert Latest Changes
By default there is a single directory for persistent storage which includes all files migratable and non-migrateable files at the top level (version, lockfile, sectors directory, config.json, datastore directories). 
* Pros: 
         *  —repodir just works, no testing changes needed, existing assumptions in iptb are not violated, no documentation changes needed
	*  really simple mental model that requires thinking about only a single directory 
* Cons: 
	* no default separation of go-filecoin and rust-fil proofs data (See 2524 for exhaustive list of why this is important)
	* migrations now take place over data not in scope for a migration by default

* TODO: 
	* All paths forward revert PR 2658, and the recent followons 2682 and 2683
	
### Path forward 2a
Sectors stay in the repo, sector storage is kept on the repo interface.  The migration copy is unchanged and  sector storage is copied over during migration.
* Pros:
	* KISS
* Cons:
	* lots of wasted disk space by default
	* putting off separation of sector and node storage

### Path forward 2b
Sectors stay in the repo, sector storage is kept on the repo interface.  The migration copy gets smarter and ignores sector storage during copy.
* Pros:
	* we don’t copy sector storage by default
* Cons: 
	* migration copy needs rethinking.  We now need to exclude some subdirs from our copy. And now we have to do separate copies of sector storage after repo migration is complete.

* TODO: 
	* migration copy needs a rewrite
		
### Path forward 2c
Sectors are out of the repo by default, the config puts them somewhere else, say as a sibling of the repo dir folder folder in <repodir>_sectors.  This path is managed with a sectorbase config as in 2658.  We maintain separation of sector storage from the repo abstraction as in 2658.
* Pros: 
	* no disk waste by default
	* we don’t need to handle sector data as a special default subdir in migration copy which means we can keep the same migration
	* one repodir flag covers everything still
* Cons:
	* This might get us back in trouble with default directory complexity by forcing users to think about multiple directories by default

* TODO:
	* Management of sectorbase config needs a little bit of work.

**Comment by whyrusleeping** [comment]
It seems to me that setting the sector base when the initializing the filecoin node itself feels a bit weird. The sector base is where a *miner* stores their sectors. When you initialize a filecoin node, there isnt a miner, so creating a sector base at that time is odd.

Other proposal: Configure sector base location per miner. Set it when creating a miner. 

I think this approach would satisfy @travisperson, as now iptb can easily programmatically put the sector base wherever it wants, *when* it needs to.

**Comment by shannonwells** [comment]
Here's my ranking of the options, with storage space and stated needs by @travisperson being the primary concerns, and simplicity being secondary.
1a
1b
2c

For 1a, I think that knowing the difference between a repodir and a homedir isn't too hard to understand if somebody needs to.

I consider these last 3 unacceptable because of wasted disk space and/or too much potential for error w.r.t. to copying in migration, in part because I think that the organization is likely to change, resulting in even more need for changing migration code, and it will be tedious and complicated to code for and test, and therefore at great risk of errors.
2a
1c
2b

@whyrusleeping 's comment about sector base makes tons of sense.

**Comment by ZenGround0** [comment]
I think @whyrusleeping's idea above should definitely happen orthogonal to this decision.  For 1a and 1b the default would look like
```
~/.filecoin 
   repo
      config.json 
      version
      ...
   miners(or maybe still "sectors")
      t2pqolz2fl4owvllhgggit32bnu5c3fpv4kstejly
         staging
         sealed
       ...
```

For 2c the default would look like
```
~/.filecoin 
   repo
      config.json 
      version
      ...
~/.filecoin_miners
      t2pqolz2fl4owvllhgggit32bnu5c3fpv4kstejly
         staging
         sealed
       ...
```

In either case the `t2pqolz2fl4owvllhgggit32bnu5c3fpv4kstejly` dir could be set to a non-default by a config entry mapping from miner address to on disk path.  And this directory would be created during `mining start` as is done today.

**Comment by ZenGround0** [comment]
Clarifying the above you actually *can* do something like the above (just per daemon, not per miner) today by running `go-filecoin config sectorbase.rootdir <per-daemon-sector-path>` before running `mining start`.  cc @travisperson

**Comment by ZenGround0** [comment]
Going with 2c

**Comment by anorth** [comment]
Thanks for this detailed write-up @ZenGround0 and 💯 for making a decision. I think this option 2c is pretty much the original proposal in #2524 anyway, before a misunderstanding sent us in a rokcy direction.

I would have liked to see a brief justification along with your decision comment above, though – I expect that you had some discussions outside this issue, and we should put the summary back here.
