### ISSUE TITLE
Move sector storage as sibling to repo, reverting "home" directory concept

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/go-filecoin#2689]
### Description
Remove the homedir concept introduced in #2658.  Replace it with [proposal 2c](https://github.com/filecoin-project/go-filecoin/issues/2687) outline in the link. The sector directory defaults to a sibling of the repo directory `<repodir>/../.filecoin_sectors` without being wrapped in any go-filecoin specific wrapper.  Put another way, go-filecoin doesn't need to know anything about repo migrations.

This is an alternative resolution to https://github.com/filecoin-project/go-filecoin/issues/2524

### Acceptance criteria
Homedir is gone, sectors are properly put in a sibling.

**Comment by anorth** [comment]
I think this is now resolved.
