### ISSUE TITLE
Nonce too low messages spam daemon logs

### ISSUE THREAD

**Issue by rosalinekarr** [filecoin-project/go-filecoin#2721]
### Description

Log messages like this one are spamming daemon logs:

```
11:07:25.994  INFO consensus.: Nonce too low:  %!s(types.Uint64=0) %!s(types.Uint64=1) <AccountActor (0xc0094bc630); balance: 899.9; nonce: 1> SignedMessage cid=[zDPWYqFCvXdigamFk2krkvfwTCbKPheENCyQTWZfU9Z84nLBrvQb]: {                     
  "meteredMessage": {
    "message": {
      "to": "t25j3aimcwcbmy2osgzy36iqoz45osmhl2eesybcy",
      "from": "t1v4erjnu27o45y6pkqgeo7dnrayhonbgikz5lvqy",
      "nonce": "0",
      "value": "100",
      "method": "createMiner",
      "params": "g0EKWEEEvlSPMMrKDDc/gcqgF1dKRYtfRiKp+19Y2pe8Zr0d1JF/71smzsWf96098e7ppfTM7QKyKl/4qWYz9LeLH82N2FgiEiABQnjzunSq9N19ATg/eLcwB3TxVOhoV0iqBbg3PE+n1w=="
    },
    "gasPrice": "0.001",
    "gasLimit": "300"
  },
  "signature": "3AgRpkvxGNWI9j1feBX2oyNzd0p6S2/6THwFO/WrhJ0SvyXH1wbaNBYXajkH/0yec9144oAfLJTqNFeSKQtF1wE="              
} validation.go:79
```

We should either fix the format of this message to use less space or reduce the frequency of the log.

### Acceptance criteria

Daemon logs are reasonably readable.

### Risks + pitfalls

We're not sure how we want to handle this yet.

### Where to begin

Figure out what to do.

**Comment by mishmosh** [comment]
We've added validation for nonces. Now this info message is triggered for almost every message to the message pool. Hypothesis is that this is due to the same message coming in more than once, via normal gossip protocol behavior. 

- [ ] confirm our understanding of root cause with libp2p team

Then, if true:
- [ ] drop this log to debug level only
- [ ] add metrics to track cc @travisperson 

cc @ZenGround0 @acruikshank @anorth

**Comment by mishmosh** [comment]
via @acruikshank:
> Our best hypothesis about why this is happening is because the first message is landing in some node (the node that ends up mining the block) and then the second version of it lands on, say, my node after I've already received the block. If there was a 100ms discrepancy in when the messages land, It would be extremely rare to get a duplicate nonce. If the discrepancy was on the order of 30s it would be pretty common.

**Comment by mishmosh** [comment]
via @raulk:

> Could you check if the signature field on these spammy logs is the same? That would clearly indicate a dupe and give us a good data point. You are using floodsub, right? It has a timecache configured for 120 seconds by default.

**Comment by travisperson** [comment]
I took a look at our logs and we are seeing the same message show quite a few times. 

When we setup the devnet we issue an `updatePeerID` from the first node with which we import the miner in the genesis. No other nodes do this.

```
docker exec filecoin-0 go-filecoin --repodir=/var/local/filecoin miner update-peerid --from=t1xnkokmwipwmsas3oe5x7mo2cutannwlm33xm3ii --gas-price 0.000000001 --gas-limit 300 t22u6wbndmualmcjc6hxwbytwwi3dhcdwswi3mdfy Qmd6xrWYHsxivfakYRy6MszTpuAiEoFbgE1LWw4EvwBpp4
zDPWYqFD4P65v9Gw2LQZgn81hrNk8onXenqohBjgt3kUXZDc7D8v
```

I did a search for this mcid, and from our logs I've seen the same message hit this error 221 between 6AM PSD and 2:40 PM.

![2019-05-06-144111_1049x316_scrot](https://user-images.githubusercontent.com/165274/57257107-52f22f00-700d-11e9-88df-a16b7d59d551.png)


```
Nonce too low:  %!s(types.Uint64=2) %!s(types.Uint64=20) <AccountActor (0xc0133fddd0); balance: 1000000012553.5821384000000013; nonce: 20> SignedMessage cid=[zDPWYqFD4P65v9Gw2LQZgn81hrNk8onXenqohBjgt3kUXZDc7D8v]: {
  "meteredMessage": {
    "message": {
      "to": "t22u6wbndmualmcjc6hxwbytwwi3dhcdwswi3mdfy",
      "from": "t1xnkokmwipwmsas3oe5x7mo2cutannwlm33xm3ii",
      "nonce": "2",
      "value": null,
      "method": "updatePeerID",
      "params": "gVgiEiDbXbBmGs1XgNWvOhNU42yekJfMBSr7U4fZYPsDbHxqFQ=="
    },
    "gasPrice": "0.000000001",
    "gasLimit": "300"
  },
  "signature": "/exlJikay/8cvR7pJBvdcxLDttyS9b2VzOjBXL+v9iFTbAB+xA/hcO+gocBwU5RgXtI5U1yOx0knG7J6WjTWjwE="
}
```

I looked at the original message in this issue and it shows up about the same number of times with a similar distribution (though this is probably due to the small number of nodes).

![2019-05-06-145110_1053x320_scrot](https://user-images.githubusercontent.com/165274/57257496-736eb900-700e-11e9-8c7d-dfbf2fe64c91.png)

**Comment by travisperson** [comment]
> Could you check if the signature field on these spammy logs is the same?

I did the same searches with the signature field and also saw the same results.

**Comment by anorth** [comment]
> You are using floodsub, right? It has a timecache configured for 120 seconds by default.

@raulk Does that mean that it's expected that a node might receive a message up to 120s after it was first broadcast? 120s is four blocktimes for us. If it would be typical behaviour for a message to be bouncing around 10s of seconds after its origin, that could well explain this message.

It doesn't line up well with the charts @travisperson created though - they suggest that a message is being received many minutes after its origin. That could happen if FC nodes are re-sending it for some reason.

**Comment by raulk** [comment]
It’s difficult to estimate how long a message may take to reach full propagation across the network, as that depends on many factors, but it certainly shouldn’t take more than a few seconds if the network is well-connected and healthy. Are you using the default time cache setting (120”) for floodsub? Note that the caches are local, meaning that if for whatever reason the message moves really slowly and takes over 120”, there’s a chance a cycle will form. You should add your logic as a pubsub validator to make sure that an error like this (suggesting you had already processed the message, and it moved out of the cache window) will stop the gossip for that message.

That said, 120” is remarkably high for a propagation time. Is there a chance that some node in the network is republishing this message under some circumstance?

The charts show the message appearing over the course of hours, and unless the planets aligned and a series of highly improbable conditions became true over hours, I am inclined to think the floodsub system is not the one cycling the message over and over again for over 11 hours.

**Comment by anorth** [comment]
I can't see anywhere that our code explicitly sends a message over pubsub except for its original broadcast, but I'll keep looking. For `CreateMiner` (in the OP), the only entry path is a manual action by the user.

We don't have any validators. From a quick skim of the code, are you referring to something like `RegisterTopicValidator`? I see brief docs at https://github.com/libp2p/specs/tree/master/pubsub#topic-validation. Will that also prevent "invalid" messages being received by the local node, as well as prevent propagation?

**Comment by anorth** [comment]
The ingestion validator certainly seems like the most likely candidate path into this message. There are two others though: message sending and applying messages for block mining. 

I have replicated the log spam on a new node that had never sent a message (and hence was not mining). The node (at `test-devnet-0.2.0`) synced the short chain, quietly kept up with empty blocks for 8 minutes, and then was met with a wall of "nonce too low" messages. I believe this excludes the two other direct callers of this validation.

In the process, think I found the culprit: UpdateMessagePool handling a re-org. The spam was immediately preceded by a reorg message:

```
17:08:17.043  INFO       node: Received new block from network cid: zDPWYqFCqsriuKoSzcUbZbEVeqHfCqCLHMXqWpcxzeKMErmys37U block.go:56
17:08:17.263  INFO chain.sync: chain fetch from network complete { zDPWYqFCqsriuKoSzcUbZbEVeqHfCqCLHMXqWpcxzeKMErmys37U } default_syncer.go:130
17:08:17.332  INFO chain.sync: reorg occurring while switching from { zDPWYqFCrbfUYWcurZG6wKtwHD9KYFTWJh96G1VjjexFhQ9zQjc5 } to { zDPWYqFCqsriuKoSzcUbZbEVeqHfCqCLHMXqWpcxzeKMErmys37U } default_syncer.go:273
17:08:17.332  INFO chain.sync: processing block 0 of 1 for chain with head at { zDPWYqFCqsriuKoSzcUbZbEVeqHfCqCLHMXqWpcxzeKMErmys37U } default_syncer.go:399
17:08:17.461  INFO consensus.: Nonce too low:  %!s(types.Uint64=7) %!s(types.Uint64=8) <AccountActor (0xc000c05560); balance: 16899.8000579999999997; nonce: 8> SignedMessage cid=[zDPWYqFCzKRuaCGhKHb3SNUfV7XZdBULieVQjX4unnbK4E4LL73b]: ...} validation.go:79
17:08:17.461  INFO     mqueue: validation error adding message to pool: nonce too low message_pool.go:166
17:08:17.462  INFO consensus.: Nonce too low:  %!s(types.Uint64=19) %!s(types.Uint64=20) <AccountActor (0xc00139db60); balance: 1000000063553.5821384000000013; nonce: 20> SignedMessage cid=[zDPWYqFD2N4ajGaeroznHS7H8XmVmLh54dNrHFfKaT4qeigQiTYM]:...} validation.go:79
17:08:17.462  INFO     mqueue: validation error adding message to pool: nonce too low message_pool.go:166
```

Then two minute later...
```
17:10:19.618  INFO       node: Received new block from network cid: zDPWYqFCwjWFftqRg7MDMxmFjHRbDySsTCtVVEc1ksXDYoifaPuJ block.go:56
17:10:19.897  INFO chain.sync: chain fetch from network complete { zDPWYqFCwjWFftqRg7MDMxmFjHRbDySsTCtVVEc1ksXDYoifaPuJ } default_syncer.go:130
17:10:19.966  INFO chain.sync: reorg occurring while switching from { zDPWYqFCyYoGGMxYqFYTJHyxyHKMKCUtLZTA7aRQso7NTVCq7jX1 } to { zDPWYqFCwjWFftqRg7MDMxmFjHRbDySsTCtVVEc1ksXDYoifaPuJ } default_syncer.go:273
17:10:19.966  INFO chain.sync: processing block 0 of 1 for chain with head at { zDPWYqFCwjWFftqRg7MDMxmFjHRbDySsTCtVVEc1ksXDYoifaPuJ } default_syncer.go:399
17:10:20.087  INFO consensus.: Nonce too low:  %!s(types.Uint64=7) %!s(types.Uint64=8) <AccountActor (0xc027972060); balance: 16899.8000579999999997; nonce: 8> SignedMessage cid=[zDPWYqFCzKRuaCGhKHb3SNUfV7XZdBULieVQjX4unnbK4E4LL73b]: { ...
```

It then settled down for a while.

In a reorg, all the messages on the rejected segment of the blockchain are re-added to the message pool. If the other branch of the chain has also processed a messages, and the associated state updated, then the message will fail the nonce check just as we see: it *should* be rejected from the mpool.

I think we want to be very sure that the message is being checked against the appropriate state. It would be a horrible error if the message was being validated against the *old* actor state, which I can imagine happening if the sequencing is wrong. I couldn't quickly convince myself one way or the other.

**Comment by anorth** [comment]
Aside, the message `processing block 0 of 1 for chain with head at { zDPWYqFCqsriuKoSzcUbZbEVeqHfCqCLHMXqWpcxzeKMErmys37U } default_syncer.go:399` is a bit scary, suggesting the algorithm has chosen a chain of length 1! I hope it just means that the difference between the chains is of length 1.

**Comment by mishmosh** [comment]
- When we switch the head to something that isn't a direct child of the head, that is a "reorg". 
- During reorgs, the message pool check for overlap between old and new chains.
- If the new chain is missing some messages, the message pool re-validates all old messages -- against the current chain state (latest tipset).
  - This will (correctly) cause many "nonce too low" errors since these messages have already been processed.
  - This will also (intentionally) discard any messages from the old/junk chain that are already on the new chain. We rely on gossip for those messages to be mined elsewhere.

TODOS:
Small concern on timing here which @acruikshank and @ZenGround0 are pairing to investigate. They will also confirm the chain reorg behavior.

via @ZenGround0: https://github.com/filecoin-project/go-filecoin/blob/master/core/message_pool.go#L155

**Comment by acruikshank** [comment]
@ZenGround0 and I have confirmed that reorgs are applied to the new state (the ChainStore sets its head synchronously before publishing the event that triggers the message pool update). 

We haven't ruled out that some of the nonce too low errors are an artifact of the gossip flood, but it does appear that the primary source is chain re-orgs.

It's an open issue why we're seeing reorgs containing so many messages (presumably from many blocks). We are adding logging to establish how big the re-orgs are. cc @anorth
