### ISSUE TITLE
go-filecoin-migrate logfile is always empty and --verbose does not print to stdout/err

### ISSUE THREAD

**Issue by shannonwells** [filecoin-project/go-filecoin#2731]
### Description
```
$ ./tools/migration/go-filecoin-migrate describe --old-repo=~/.filecoin-symlink --verbose --log-file=here.txt
$ ls -s here.txt
0 here.txt
```
Occurs in master branch. 

### Acceptance criteria
Expected output to go to stdout/err as well as logfile.
Also on wishlist: I keep typing `logfile` instead of `log-file` -- can we change the option to `logfile`?

**Comment by anorth** [comment]
@ZenGround0 I suggest handing this issue over to @shannonwells to bring home

**Comment by ZenGround0** [comment]
@anorth I didn't close this but patched this bug last release.
