### ISSUE TITLE
Nonce too high should be a warning, not an error

### ISSUE THREAD

**Issue by rosalinekarr** [filecoin-project/go-filecoin#2748]
### Description

This log message should be a warning, not an error:

```
16:07:51.315 ERROR       node: processMessage(): validation error adding message to pool: message nonce (60271) is too much greater than actor nonce (0) node.go:1040
```

This log can occur under normal operation with members on a devnet running out of date code. Error logs should be reserved for events that require the attention of the miner operator.

**Comment by anorth** [comment]
We've observed that the network seems to have stopped progressing around block height 390, and we see a lot of these messages. Not yet sure if they're related.

The message is observed in non-mining nodes (as well as miners?).

The only code path to this message is validation of a message being added to the message pool:
- `MessagePool.Add` from `Node.processMessage`
- `MessagePool.UpdateMessagePool` in response to a re-org

As far as I know, we did not observe this message at all on the `test` devnet, before releasing to the user devnet. One difference between them is the existence of many nodes on the previous version of the devnet. The `hello` protocol should not allow them to connect to each other, though. I'm not sure if it's possible for messages broadcast on a gossipsub to still cross the networks, but I'm guessing it is.

**Comment by travisperson** [comment]
I just glanced through some of this code, and the hello protocol does not serve this purpose per-say. It's true that it will force a disconnect, but the hello protocol doesn't appear gate other protocols from being opened. My hypothesis is that we connect to a new peer and during the process we change a few messages over pubsub or through the dht, and then disconnect. I'm going to add some logs and see if I can show this occurring.

**Comment by anorth** [comment]
We have multiple issues about how we want to separate the DHTs of different
networks. I'm not sure if they would also separate pubsub, but we probably
want to.

**Comment by travisperson** [comment]
Should we require that the hello handshake succeeded for a peer before we accept other protocol connections from them?

**Comment by travisperson** [comment]
Actually I don't like the above really. While it works, it's basically an extension of the commit check in the hello protocol which is already the wrong approach, and extending it isn't ideal.

**Comment by anorth** [comment]
This issue as originally stated remains valid so let's leave it's focus there. Ideas about separating networks are captured in other issues. Thanks @rosalinekarr and @travisperson
