### ISSUE TITLE
Remove build_docker_image from test_all CircleCI workflow

### ISSUE THREAD

**Issue by anorth** [filecoin-project/go-filecoin#2750]
### Description
The `test_all` workflow on CircleCI builds a docker image after running tests. AFAIK no-one uses that image, and other workflows build one for subsequent deployment. The `test_all` workflow is triggered by every branch and commit, but the outcome of the docker image build is ignored. If we don't care about the output, we shouldn't build it, for simplicity and reducing resource contention.

### Acceptance criteria
The CI workflow that runs branch checks on all PRs does not build a docker image we don't need.

**Comment by anorth** [comment]
@ognots @travisperson WDYT?

**Comment by ognots** [comment]
Agreed
