### ISSUE TITLE
Is this feasible that a go-filecoin node can specify multiple directories?

### ISSUE THREAD

**Issue by waynewyang** [filecoin-project/go-filecoin#2751]
- Go-filecoin can only specify one directory, I think it will result that it's hard to manage multiple hard disks, IPFS has the same question I think.
    - one hand, it is wasting space if using RAID , it does't match filecoin's vision, because we need lower costs.
    - on the other hand, LVM is not safe, All disks can't work if one disk does't work.

So I think about that if IPFS and go-filecoin can specify multiple directorys? or everyone else has good idea?

**Comment by waynewyang** [comment]
I think I found  the solution. so I close this issue.

**Comment by deltazxm** [comment]
What solution did you find?
