### ISSUE TITLE
Some Proposed Wiki recommendations

### ISSUE THREAD

**Issue by eshon** [filecoin-project/go-filecoin#2759]
(Some of these are nice-to-have's :dango:)

#### _On the Getting Started_ Wiki Page:

1. In the section [Installing from source](https://github.com/filecoin-project/go-filecoin/wiki/Getting-Started#installing-from-source):

   A. Under **Build Dependencies** :

      For "rust/rustup" add note that it must be Rust >= v1.36.0 (use nightly, because the rustup or the curl command on Ubuntu may install 1.34.x and a later pkg-config step will not work.)
   
   B. Under **Ensure you have the correct code for joining the user devnet**:

    Brackets could be added to `git checkout <LATEST_USER_DEVNET_TAG>` to make clear they need to add the actual latest release number themselves (for copy-pasters in a hurry :see_no_evil:)

2. In the section [Start Running Filecoin](https://github.com/filecoin-project/go-filecoin/wiki/Getting-Started#start-running-filecoin):

    A. The command `rm -rf ~/.filecoin` will delete their current wallet.
  
   Might want to suggest: 
    
    *This will delete all previous filecoin data, so export your wallet if you'd like to save it. (If the entire testnet is being upgraded there's no need to save it.)*

    B. Also in this section, the diagram of the **miner** could say "you can create a miner after your node is fully synced" (so they don't run that command right away).

3. In the section [Get FIL from the Filecoin faucet](https://github.com/filecoin-project/go-filecoin/wiki/Getting-Started#get-fil-from-the-filecoin-fauce)t:

    In the final step _4. check your wallet balance_, this could be added:
    
    **NOTE: Your wallet balance may not be visible locally until your node has synced with the chain.**

4. In the section [Wait for Chain Sync](https://github.com/filecoin-project/go-filecoin/wiki/Getting-Started#wait-for-chain-sync):

   An animated screenshot of what syncing looks like might be helpful here, in case their node is hung:
    
    ![node syncing](https://raw.githubusercontent.com/eshon/random_images/master/syncing_node.gif)

#### _On the Mining Filecoin_ Wiki Page:

6. In the section [Start Mining](https://github.com/filecoin-project/go-filecoin/wiki/Mining-Filecoin#start-mining) that reads:

   > Note: This step may take about a minute to process, but if it hangs for longer, double-check that gas-price is less than $YOUR_WALLET_BALANCE / LIMIT.

   Is LIMIT an available variable? Is that a division symbol?

   Also it says in step _1. Create a miner ... with a message gas price of 0 FIL/unit and limit of **1000 gas units**._

    The command below it uses `--gas-limit=300`. Is that a mismatch with 1000 gas units?

7. In the section [Stop Mining](https://github.com/filecoin-project/go-filecoin/wiki/Mining-Filecoin#stop-mining):

   `rm -rf ~/.filecoin`

   Might be good practice to add:

   *NOTE: This will also delete your wallet. Export your wallet file first if you'd like to re-import it later. (If the entire testnet is being upgraded there's no need to save it.)*
   
8. In the section [Set your price for storage](https://github.com/filecoin-project/go-filecoin/wiki/Mining-Filecoin#set-your-price-for-storage):

   A step 3 could be added to filter the long list of asks:
    
     3. Or filter for just your miner address:
    
    `go-filecoin client list-asks --enc=json | grep <your miner address> | jq`

9. In the section [Advanced Options](https://github.com/filecoin-project/go-filecoin/wiki/Mining-Filecoin#advanced-options):

   Might be helpful to add where the config.json is located:
    
    "the `sectorbase.rootdir` config entry in your `~/.filecoin/config.json` file"

#### _On the [Commands](https://github.com/filecoin-project/go-filecoin/wiki/Commands#mining) Wiki Page:, in the **Mining** section:_

   10.  `go-filecoin miner create 10 10 --gas-price 0 --gas-limit 300` 
    
   Note that the gas price above it set to 0. This might be confusing, how about `<your gasprice>` or something similar?
    
   
#### _On the Storing on Filecoin_ Wiki Page:

11. In the section [Send data and pay miner](https://github.com/filecoin-project/go-filecoin/wiki/Storing-on-Filecoin#send-data-and-pay-miner):
   
    Here's an attempt at a diagram, but it's fine to say no or table for later:

```
+--------+                                        +-------+
| client | ---$$---> propose+storage+deal ------> | miner |
+--------+                  |                     +-------+
                         Accepted
                  (payment channel opened)
                            |
                         Staging --------+         sealing
                            |            |         interval
                         Posted  <-------+
                            |
                            |
  retrieval                 |
  requests                  |    -------$------->  periodic
  possible                  |                      payments
                            | 
                            v
                       Expiration
                (payment channel closed)
```

**Comment by mishmosh** [comment]
Thanks! Replying to the first section (**_Getting Started page_**), first:

> 1. In the section [Installing from source](https://github.com/filecoin-project/go-filecoin/wiki/Getting-Started#installing-from-source):

> Brackets can be added to `git checkout <LATEST_USER_DEVNET_TAG>` to make clear they need to add the actual latest release number themselves (for copy-pasters in a hurry :see_no_evil:)

SGTM, can you add? This is already standard in in-CLI help, and we should use this standard in all docs as well.

> 2. In the section [Start Running Filecoin](https://github.com/filecoin-project/go-filecoin/wiki/Getting-Started#start-running-filecoin):

> A. The command `rm -rf ~/.filecoin` will delete their current wallet. Might want to suggest:  **(This will delete all previous filecoin data, so export your wallet if you'd like to save it.)**

I think at this early stage it's OK to leave this out, in favor of keeping the tutorial simple.

> B. Also in this section, the diagram of the **miner** could say "you can create a miner after your node is fully synced" (so they don't run that command right away).

Sounds good. @akrych would you mind sharing the source file for that image?

> 3. In the section [Get FIL from the Filecoin faucet](https://github.com/filecoin-project/go-filecoin/wiki/Getting-Started#get-fil-from-the-filecoin-fauce)t:

> In the final step _4. check your wallet balance_, this could be added:
    
>    **NOTE: Your wallet balance may not be visible locally until your node has synced with the chain.**

SGTM. Can you add?

> 4. In the section [Wait for Chain Sync](https://github.com/filecoin-project/go-filecoin/wiki/Getting-Started#wait-for-chain-sync):

> An animated screenshot of what syncing looks like might be helpful here, in case their node is hung:

SGTM. Can you add?

**Comment by rosalinekarr** [comment]
@mishmosh, if you don't mind, i'm going to assign this one to you and mark it as in progress. let me know if you don't think that's correct.

**Comment by eshon** [comment]
Adding a possible nice-to-have suggestion... 

> jq can be used to sort Miner asks by Price and Expiry:

`go-filecoin client list-asks --enc=json | jq -s -c 'sort_by(.Price, .Expiry) | .[]'`

**Comment by eshon** [comment]
_akyrch provided the design file so here's the diagram with the small instruction update (I don't have Edit permissions to the Wiki):

![getting-started-node-diagram](https://user-images.githubusercontent.com/1017762/58015871-9e700700-7afc-11e9-81fa-b8cc6f7c6bed.png)

**Comment by anorth** [comment]
@mishmosh could you please make any remaining updates and close this issue?
