### ISSUE TITLE
Resolve & implement how to close migration logger

### ISSUE THREAD

**Issue by shannonwells** [filecoin-project/go-filecoin#2760]
### Description
Migration logger needs to have Close() called before we exit, and defer apparently won't be sufficient.  The Close function returns error so if we need to exit because of a different error, and then Close errors, this presents a sort of design problem.

### Acceptance criteria
The migration logger (internal.Logger) always has Close called before exiting migration.

### Risks + pitfalls
Leaving an open file somewhere if Close fails
Failing to call Close at all because an exit  was missed.

### Where to begin
/tools/migration/main.go

**Comment by ZenGround0** [comment]
Forgot to close this down when merging #2771 but it is fixed
