### ISSUE TITLE
Resolve context.TODOs in storage protocol client and miner

### ISSUE THREAD

**Issue by rosalinekarr** [filecoin-project/go-filecoin#2764]
### Description

There are several `context.TODO()`s in `protocol/storage/client.go` and `protocol/storage/miner.go` that were introduced with #2749. We need to decide what context should be used in these cases and update them.

### Acceptance criteria

TBD

### Risks + pitfalls

This needs to be discussed first so we can make a decision.

### Where to begin

Discuss

**Comment by anorth** [comment]
An easy first answer is to make context a parameter of each method. In some cases we'll be able to resolve that to a context further up the call stack.

**Comment by rosalinekarr** [comment]
This has been resolved in #2749
