### ISSUE TITLE
Releases should come preconfigured with genesis, bootstrappers, and heartbeat

### ISSUE THREAD

**Issue by frrist** [filecoin-project/go-filecoin#2766]
### Description
When a filecoin binary is released users should be able to setup and join the network without passing a bunch of flags. 

A user should simply be able to run:
`go-filecoin init` then `go-filecoin daemon`. 
All flags that are usually passed to these commands will not longer be required.

The motivation here is to reduce confusion when connecting to a devnet, by making the default "just work" we will hopefully see less support requests from users.

### Acceptance criteria
- Released filecoin binarys come preconfigured with: 
  - genesis file, this will allow a user to init a filecoin node without passing the `--genesisfile` flag.
  - bootstrap peers, this will allow a user to init a filecoin node without passing the `--devnet-user` flag
  - stats dashboard heartbeat target address, this will auto connect users to the stats dashboard without running the `go-filecoin config heartbeat.beatTarget` command.
  - All information is passed at build time (like we do with version)

**Comment by mishmosh** [comment]
This all sounds delightful. I would like to know if this would cause problems with infra, proofs params, etc.

**Comment by mishmosh** [comment]
The stats dashboard heartbeat - during devnet/testnet, I think it would be OK to opt-out.

**Comment by anorth** [comment]
This issue lacks a stated motivation. Is it to reduce confusion and support requests from users who have inadvertently connected to the wrong network?

If that's the case, I think we would be better to make it explicit, but remove the defaults. Collapsing the geneisis and bootstrap flags into a single `--network=user` would be good though.

I don't think it's ok for us to opt users in to broadcasting their stats by default, but we should make it easier. We could simplify it to a `--heartbeat` boolean flag (which behaves according to `--network`), and demonstrate passing it always in all our documentation.

**Comment by frrist** [comment]
@anorth what are your thoughts on making the network and genesis file a build option instead of an init flag? An advantage to passing the genesis file at build time would be failing to build in the case that block structure has changed instead of allowing a user to init their node with a genesis file that will never work?

**Comment by anorth** [comment]
Is that a problem we have had? Build-time configuration sounds a bit brittle to me. For example, the pre-built binaries could not be used for a localnet or private network. Do any similar projects take this approach?

**Comment by ognots** [comment]
@frrist I feel like we'd potentially be building ourselves in to a corner (sorry for the pun) having parameters like that hard coded in to the binaries. 

having network and genesis file as build options adds a good amount of complexity to testing, distribution (github releases, docker builds) and deployment.

what do you envision our "default" network being set to? once we've reached mainnet for example, could there be potential financial or negative consequences to having daemons connect to it unintentionally if it's set to default?

often the default run-time mode of applications is to run in "dev" mode to prevent accidentally connecting to a production service when testing or experimenting, while production mode often requires more flags and configuration. (I'm not necessarily arguing in favour of this, just providing some colour to the topic)

**Comment by eshon** [comment]
Would a bash install script setting some environment variables or running those commands be easier? It can be based on the Docker scripts, users can scan and modify the script easily and they might require less time to compile and test before releases. The motivation is that binary users just want to try something out as quickly as possible.

**Comment by anorth** [comment]
A wrapper script sounds like a reasonable solution to me, so long as the dev team actively use it (I think we would).

**Comment by frrist** [comment]
After reflecting on this a bit, I agree that making these values build options sounds a bit fragile. I am going to close this as I cannot make a strong enough argument in favor of it.
