### ISSUE TITLE
[bug]

### ISSUE THREAD

**Issue by a8159236** [filecoin-project/go-filecoin#2776]
Hi, I found an interesting question:
I have three miners, A with 'Ubuntu' and B and C with 'Centos7'. I used A ping C and found that it could ping, but I used B ping C and found that the ping was different sometimes.Display: 'Error: context deadline 'or 'Error: Error: dial backoff'. I think this is the reason of the operating system. For this reason, I tested several machines and found that the Ununtu system could ping, but centos could not.
![{18492827-9D73-46E3-8454-C010ABE0F24C}_20190511103747](https://user-images.githubusercontent.com/32159630/57564120-602a6780-73d9-11e9-8ba5-075f61bd2b9d.jpg)
![{AE2375EF-87D2-41B0-A02D-AE68C11C9261}_20190511103731](https://user-images.githubusercontent.com/32159630/57564121-602a6780-73d9-11e9-91af-721be250b632.jpg)
![{F5A61599-9D1A-4E91-A4E1-56546FE68805}_20190511103810](https://user-images.githubusercontent.com/32159630/57564122-60c2fe00-73d9-11e9-8fac-2aff3b10523f.jpg)

**Comment by a8159236** [comment]
All three machines are on the same LAN, and two machines with 'centos7' are often not ping, but 'Ubuntu' can ping any one.
On the other hand, Ubuntu is easier to install Filecoin than Centos because Ubuntu comes with GLIBC>2.18, but centos7 requires an additional installation. Perhaps Ubuntu is better suited for Filecoin.

**Comment by rosalinekarr** [comment]
@a8159236, thanks for this bug report! If you could, please update the description of your issue to use our [bug report template](https://raw.githubusercontent.com/filecoin-project/go-filecoin/master/.github/ISSUE_TEMPLATE/bug_report.md). It helps us categorize and prioritize issues.

As for CentOS support, we do plan to support all major linux system eventually, but I'm afraid compatibility across various distros is not a very high priority at the moment, so it may take us a while to figure this one out. In the meantime, I would recommend sticking with your Ubuntu installation for now.

@travisperson, when you have some spare time, would you mind looking into this?
