### ISSUE TITLE
Chain sync rejects new heads farther than [finality] ahead of consensus head

### ISSUE THREAD

**Issue by anorth** [filecoin-project/go-filecoin#2782]
### Description
As reported in #2755, the 0.2.x user devnets experienced a long mining delay when peers and blocks from the previous devnet leaked into the DHT/pubsub of the new one. This simulated an attack by a node proposing a long and heavy alternate chain to the consensus one. Filecoin nodes spent a long time fetching this alternate chain, only to eventually reject it when it didn't meet with the new network's genesis.

Unlike POW blockchains, filecoin nodes can't easily validate blocks without linking them back to their existing chain. This attack is mitigated by a caught-up (#1160) node limiting the distance ahead of its current head that it will accept a new block. A block that doesn't converge with the chain within [finality] blocks should be dropped, marked as bad, and not propagated (see #2783, although it may not be feasible to prevent pubsub validation).

https://github.com/filecoin-project/consensus/issues/67 gives us a working number of 600 rounds (~5 hours) for this finality.

Note: #2755 also identifies that nodes are blocked from mining while following the fake chain due to synchronous/blocking code fetching the chain. Changing that is not in scope for this story; adding asynchrony here will only make things harder to trace and understand at the moment.

### Acceptance criteria
- Nodes which are caught up and following a consensus chain ignore blocks claiming to be more than 600 rounds past their current head
- The [sync spec](https://github.com/filecoin-project/specs/blob/master/sync.md) clearly identifies this behaviour

### Risks + pitfalls
- This resolution depends on differentiating a caught-up mode #1160

**Comment by whyrusleeping** [comment]
solution here sounds about right

**Comment by rosalinekarr** [comment]
Unless there's any objections, I'm going to go ahead and implement this with a stubbed out concept of `syncing` and `caught up` status. I'll add the actual status check as my next task.

**Comment by anorth** [comment]
Please hold off for a little, @rosalinekarr. There's a bunch of investigation into chain sync correctness and performance at the moment, and I'd prefer we have a clear scope and have prioritised against storage protocol work before diving in, lest we leave something in a (even more) half-way state.

**Comment by rosalinekarr** [comment]
Sounds good. I've pushed up [my WIP](https://github.com/filecoin-project/go-filecoin/pull/2799) for now so it can be resumed at a later time.

**Comment by anorth** [comment]
This isn't closed until we actually implement chain sync caught-up mode #1160.

**Comment by rosalinekarr** [comment]
Oops, ZenHub auto-closed bc of the linked PR.

**Comment by frrist** [comment]
Closing as the verbage -- caught-up/syncing/finality is changing, the spec this references has been deleted and #3268 will do the thing we want here once addressed.
