### ISSUE TITLE
Nightly Release Cleanup

### ISSUE THREAD

**Issue by ognots** [filecoin-project/go-filecoin#2784]
### Description
A Github release is created on every successful nightly build. This leads to polluting the release page with too many night releases.

Create a script or binary that can be run as part of nightly builds to remove any nightly releases older than a week

### Acceptance criteria
* After nightly build runs, only 7 nightly releases remain

### Risks + pitfalls
useful nightly releases may be removed

### Where to begin
consider adding a new golang tool to accomplish this

**Comment by anorth** [comment]
Done
