### ISSUE TITLE
Copying over chain data from a synced node to a new node speeds up syncing

### ISSUE THREAD

**Issue by eshon** [filecoin-project/go-filecoin#2789]
### Description

Being able to copy the chain from the ~/.filecoin/chain folder from a trusted and already-synced node to a new node might be a nice feature to speed up syncing, especially for miners who manage multiple nodes and want to spin up more quickly.

### Acceptance criteria

Copying all or part of the ~/.filecoin/chain folder from a synced node to a new node results in the new node being successfully synced in much less time and working properly.

### Risks + pitfalls

Whether or not to explicitly support this should be discussed - it could also just remain a known hacky way to sync.

A fast-sync feature would be an alternative way to sync quickly - although not if the goal is to create more full nodes quickly and if fast-sync is just using block headers.

### Where to begin

This was originally asked in the Filecoin Slack and @rosalinekarr suggested making it a possible feature request: https://filecoinproject.slack.com/archives/CEGN061C5/p1557955561126900

**Comment by rosalinekarr** [comment]
@eshon, thanks for writing this!

**Comment by ZenGround0** [comment]
IIRC just copying chain has led to errors.  I'm guessing that copying `chain` and `badger` ( which stores the persisted state tree bytes ) is needed to make this work.

**Comment by taylorshuang** [comment]
This is good idea! I try this method that copying over chain data from other synced node, but i find the state of the new node has the same status with the old. What should I do?

**Comment by anorth** [comment]
I'm closing this as a non-goal for now.

We do intend to implement a chain export functionality that, when it includes state too, will satisfy this need. #3554
