### ISSUE TITLE
[bug] git commit hash injection fails with `go run ./build/ install`

### ISSUE THREAD

**Issue by windemut** [filecoin-project/go-filecoin#2797]
**Describe the bug**
Only one peer is found, and "go-filecoin version" produces an empty output: "commit: " 

**To Reproduce**
1. Follow the instructions at https://github.com/filecoin-project/go-filecoin/wiki/Getting-Started under "Installing from source"
2. Run this command: "go-filecoin version"
3. Run this command: "go-filecoin daemon"
4. Run this command: "go-filecoin swarm peers"

**Expected behavior**
1. Command 2 should show a git commit hash
2. Command 4 should produce a long list of peers
3. If for some reason there is no git commit hash, or if the commit is not the correct one, ```go-filecoin daemon``` should fail with an informative error message
4. The correct git commit hash for the given network should be included in the error message

**Observed behavior**
1. Command 2 does not show a git commit hash. It shows only ```commit: ```
2. Command 4 produces only a single peers, even if running for more than a week
3. Daemon runs happily but mysteriously fails to connect with peers
4. It is not clear what the correct version is for any given network

**Screenshots**

None

**Diagnostic information**

- Filecoin Inspect Ouput: 
```
{"Config":{"api":{"accessControlAllowCredentials":false,"accessControlAllowMethods":["GET","POST","PUT"],"accessControlAllowOrigin":["http://localhost:8080","https://localhost:8080","http://127.0.0.1:8080","https://127.0.0.1:8080"],"address":"/ip4/127.0.0.1/tcp/3453"},"bootstrap":{"addresses":["/dns4/user.kittyhawk.wtf/tcp/9000/ipfs/Qmd6xrWYHsxivfakYRy6MszTpuAiEoFbgE1LWw4EvwBpp4","/dns4/user.kittyhawk.wtf/tcp/9001/ipfs/QmXq6XEYeEmUzBFuuKbVEGgxEpVD4xbSkG2Rhek6zkFMp4","/dns4/user.kittyhawk.wtf/tcp/9002/ipfs/QmXhxqTKzBKHA5FcMuiKZv8YaMPwpbKGXHRVZcFB2DX9XY","/dns4/user.kittyhawk.wtf/tcp/9003/ipfs/QmZGDLdQLUTi7uYTNavKwCd7SBc5KMfxzWxAyvqRQvwuiV","/dns4/user.kittyhawk.wtf/tcp/9004/ipfs/QmZRnwmCjyNHgeNDiyT8mXRtGhP6uSzgHtrozc42crmVbg"],"minPeerThreshold":1,"period":"10s"},"datastore":{"path":"badger","type":"badgerds"},"heartbeat":{"beatPeriod":"3s","beatTarget":"/dns4/stats-infra.kittyhawk.wtf/tcp/8080/ipfs/QmUWmZnpZb6xFryNDeNU7KcJ1Af5oHy7fB9npU67sseEjR","nickname":"Eniac","reconnectPeriod":"10s"},"mining":{"autoSealIntervalSeconds":120,"minerAddress":"empty","storagePrice":"0"},"mpool":{"maxNonceGap":"100","maxPoolSize":10000},"net":"devnet-user","observability":{"metrics":{"prometheusEnabled":false,"prometheusEndpoint":"/ip4/0.0.0.0/tcp/9400","reportInterval":"5s"},"tracing":{"jaegerEndpoint":"http://localhost:14268/api/traces","jaegerTracingEnabled":false,"probabilitySampler":1}},"sectorbase":{"rootdir":""},"swarm":{"address":"/ip4/0.0.0.0/tcp/6000"},"wallet":{"defaultAddress":"t167yceuk6fhp5vljdskvjqtfsszjbkt7h4pvyd3i"}},"Disk":{"FSType":"61267","Free":24835399680,"Total":17623924736},"Environment":{"FIL_API":"","FIL_PATH":"","GOPATH":"/home/andreas/go"},"FilecoinVersion":"","Memory":{"Swap":0,"Virtual":9972748000},"Runtime":{"Arch":"amd64","Compiler":"gc","GoMaxProcs":4,"NumCGoCalls":9,"NumGoRoutines":88,"NumProc":4,"OS":"linux","Version":"go1.12.5"}}
```
- Current Head: 
```zDPWYqFD6sE4HBMtXghMsEsm3SwJ4u8bmt3f5VJ4vzVc1j4LgL62```
- Connected Peers: 
```
/ip4/18.188.90.151/tcp/8080/ipfs/QmUWmZnpZb6xFryNDeNU7KcJ1Af5oHy7fB9npU67sseEjR
```
[Only one!]
**Version information**

- Go:  go version go1.12.5 linux/amd64
- Rust:  rustc 1.34.1 (fc50f328b 2019-04-24)
- Cargo:  cargo 1.34.0 (6789d8a0a 2019-04-01)
- Commit:  fcf56acdc98a2ea4fc4d0b62878a9302f51af869
- Go Env: 
```
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/andreas/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/andreas/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build086640603=/tmp/go-build -gno-record-gcc-switches"
```
- CC: 
```
gcc (Ubuntu 7.3.0-16ubuntu3) 7.3.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Additional context**

1. The install command has the proper -ldflags, it seems:
```go install -ldflags "-X github.com/filecoin-project/go-filecoin/flags.Commit=fcf56acdc98a2ea4fc4d0b62878a9302f51af869"```
2. Explicitly setting ```flags.Commit``` in ```flags.go``` does seem to fix the problem.

**Comment by anorth** [comment]
Interesting. I see also `"FilecoinVersion":""` in the inspect output.

Could you verify that you're really running the expected binary? After a build, invoke with `./go-filecoin version`.

**Comment by windemut** [comment]
I know it’s the right binary, because when I recompile with the hardcoded commit hash it works. Nevertheless, I’ll try your suggestion tomorrow.

**Comment by windemut** [comment]
Wait, since the -ldflags are in the install, would the pre-installation binary not be missing the version for sure?

**Comment by anorth** [comment]
It's worth highlighting that this is not just an informational problem. Without the right git hash, the node fails to connect to any peers. This is observed in the original issue, but I missed it.

The ldflags are also in the `build` command.

**Comment by frrist** [comment]
I observe that the command `go run ./build/main.go install` fails to inject the commit hash, i.e.:

```
frrist@pine ~/s/g/f/go-filecoin (master)> go run ./build/ install
Installing...
git log -n 1 --format=%H
go install -ldflags "-X github.com/filecoin-project/go-filecoin/flags.Commit=dcb0be33ca4b3baa4ed4eda7b54a88624cd08ec4"
go-filecoin version⏎                                                                                                                                                         frrist@pine ~/s/g/f/go-filecoin (master)> go-filecoin version
commit:
```
```
frrist@pine ~/s/g/f/go-filecoin (master)> go run ./build/ build
Building go-filecoin...
frrist@pine ~/s/g/f/go-filecoin (master)> ./go-filecoin version
commit: dcb0be33ca4b3baa4ed4eda7b54a88624cd08ec4
```

Manually running the install command **does** seem to work however.
```
frrist@pine ~/s/g/f/go-filecoin (master)> go install -ldflags "-X github.com/filecoin-project/go-filecoin/flags.Commit=dcb0be33ca4b3baa4ed4eda7b54a88624cd08ec4"
frrist@pine ~/s/g/f/go-filecoin (master)> go-filecoin version
commit: dcb0be33ca4b3baa4ed4eda7b54a88624cd08ec4
```

My gut says this indicates an issue with `./build/main.go`, but nothing seems out of place at first glance.

**Comment by frrist** [comment]
@windemut  do you use the command `go run ./build/ install` to install from source, or do you run `go run ./build/ build && cp go-filecoin $GOPATH/bin`?

**Comment by windemut** [comment]
I use install. And I just tried, it seems to work correctly with the local executable without the install. Weird.

**Comment by windemut** [comment]
So, I guess using the copy command instead if "install" seems to solve the problem. And the bug is located in the "install" command, somehow.

**Comment by windemut** [comment]
What @frrist shows is exactly what I see as well.
