### ISSUE TITLE
Is it necessary to synchronize multiple block data for one server to run multiple miner services?

### ISSUE THREAD

**Issue by chenzhi201901** [filecoin-project/go-filecoin#2803]
Is it necessary to synchronize multiple block data for one server to run multiple miner services?

**Comment by anorth** [comment]
Thanks for this question. Could you please ask it again in the [Filecoin forum](https://discuss.filecoin.io/) instead? A response there will be more visible to others in the community. Issues in this repository are reserved for development tasks and bug reports.

I am closing this issue now in favour of responding in the forum.

**Comment by chenzhi201901** [comment]
Thanks
