### ISSUE TITLE
Fix StorageMarketActor.UpdatePower to accept negative values.

### ISSUE THREAD

**Issue by acruikshank** [filecoin-project/go-filecoin#2808]
### Acceptance Criteria

1. Rename `actorStorageMarket.UpdatePower` to `UpdateStorage`
2. Ensure that it can both add and subtract power (i.e. it can't take a uint for a parameter)

**Comment by shannonwells** [comment]
@acruikshank I was just looking around for stories to pick up --  `StorageMarketActor.UpdateStorage` doesn't exist (UpdateStorage isn't a function of storagemarket.Actor).  Can you please update the description?

**Comment by acruikshank** [comment]
@shannonwells It should have been UpdatePower.

**Comment by anorth** [comment]
The spec calls it UpdateStorage, so rename it to the right name while doing this.
