### ISSUE TITLE
Mechanism for a miner to recover excess collateral (de-pledge)

### ISSUE THREAD

**Issue by acruikshank** [filecoin-project/go-filecoin#2809]

**Comment by anorth** [comment]
I think the spec might need some work here first. Increasing pledge specifies both space and FIL, but DePledge only FIL. In anticipation of a collateral function that is dependent on time, we should probably allow maximum flexibility for either value to be increased or decreased, limited by the collateral function so as not to reduce collateral (further) below that required for the pledged space.

**Comment by anorth** [comment]
This is waiting on clarification of pledge and storage collateral representation in https://github.com/filecoin-project/specs/issues/60

**Comment by anorth** [comment]
Closing until we come to implementing the new spec's actors.
