### ISSUE TITLE
Add `SerializationMode` to deal proposal

### ISSUE THREAD

**Issue by acruikshank** [filecoin-project/go-filecoin#2811]
A client sets the serialization mode (e.g. "bit-padded-fully-aligned") so that the miner knows how CommP was created by the client.

**Comment by anorth** [comment]
@whyrusleeping indicated that this was not necessary at the moment, so moving to icebox for now.

**Comment by whyrusleeping** [comment]
Oh, no. This is not what I thought we were talking about.  This is, how do I turn whatever is referenced by the pieceRef (likely the Cid of a unixfs graph, could also be a https URL) into a flat buffer of data that CommP is generated from. It's basically: how do you go from transfer encoding to filecoin encoding.

By default, I assume this will be "read out the leaves of the unixfs graph"

**Comment by anorth** [comment]
Thanks, I may well have misunderstood. AC could you clarify?

**Comment by acruikshank** [comment]
@anorth @whyrusleeping "how do I turn whatever is referenced..." is in line with my understanding of the meaning of this field. It would have only one value (the default). So this issue is pure protocol compliance and wouldn't affect the implementation.

**Comment by whyrusleeping** [comment]
@acruikshank yep, this should be a few lines that changes nothing important, but allows us to change things up later easily if needed.
