### ISSUE TITLE
Storage protocol – multiple sector sizes

### ISSUE THREAD

**Issue by anorth** [filecoin-project/go-filecoin#2815]
This epic covers work related to multiple sector sizes required to complete storage protocol.

**Comment by anorth** [comment]
@laser this epic has no remaining issues. Do you consider it "done" from the go-filecoin point of view, with remaining known work all being on the proofs side? Please close it if so.

(It's ok if some related stories crop up later, but we don't know what they are yet)

**Comment by laser** [comment]
@anorth - I have been waiting to close this epic until [this feature](https://github.com/filecoin-project/rust-fil-proofs/issues/625) is being used by go-filecoin.

**Comment by anorth** [comment]
@laser with recent changes, I don't expect this to all land in the immediate future, so closing this epic. We can re-open when the PoSt construction, sector construction etc are all more final.
