### ISSUE TITLE
Integration Test Storage Miner Payments

### ISSUE THREAD

**Issue by acruikshank** [filecoin-project/go-filecoin#2822]
### Description

We need a round trip test that a client creates miner payments with conditions correctly and that a miner can redeem these payments with a valid piece inclusion proof. We don't currently have a category of testing that this type of test would fit into. 

### Acceptance Criteria

1. Determine an appropriate style of testing (daemon, FAST, some sort of whitebox integration test).
2. Implement a test where the storage client code generates a deal proposal with payments containing piece inclusion conditions, and use storage miner code to generate a piece inclusion proof (real or fake) and redeem the payments.
3. Confirm some of payment channel balance has been transferred to client.

**Comment by anorth** [comment]
Piece inclusion proofs are removed by the new spec.
