### ISSUE TITLE
Design doc for PoST revamp

### ISSUE THREAD

**Issue by anorth** [filecoin-project/go-filecoin#2823]
### Description
Write a design document explaining the changes required to synchronize the SubmitPoSt method with the specification
- miner state should include proving period end instead of proving period start
- miner state should differentiate sector set from proving set
- miner needs notion of "next done set"

A storage miner stops generating PoSts for sectors whose pieces are referenced by deals which have expired (at miner’s option, maybe an explicit command?)
- introduce notion of active vs. inactive collateral
- introduce notion of sector set vs. proving sector set

See also #2824 and #2824 

### Acceptance criteria
- A design doc, published on appropriate channels, with feedback and revisions.
- Stories for work items from the design doc, in epic #2813

**Comment by acruikshank** [comment]
Design Doc with links to relevant stories:

https://docs.google.com/document/d/1c177XRpKCGkUzY1hMNZAs2pWz-XMEAovqKZU3O3VMNA

**Comment by anorth** [comment]
Done?

**Comment by acruikshank** [comment]
Yes
