### ISSUE TITLE
Design doc for PoST fault data structures

### ISSUE THREAD

**Issue by anorth** [filecoin-project/go-filecoin#2824]
### Description
Write a design doc for FaultSet, BitField, and SectorSet
- we need to understand why these data structures exist in the spec
- we need to be convinced that we actually need these data structures in our software
- NOTE: The SPEC states that a BitField "is a set of bits."
- NOTE: The miner's committed sector metadata (CommR, CommD, sector ID) are currently stored in a map, keyed by sector ID. @laser believes that the SPEC expects these things to live in an array and the BitField contains indices into the array. We should reconcile this discrepancy as part of this story.

See also #2823 and #2817 

### Acceptance criteria
- A design doc, published and appropriately revised
- Stories for work items arising from the design in epic #2813

**Comment by ZenGround0** [comment]
Check it out here: https://docs.google.com/document/d/1aE5a-QZojprMkig6IyYkwV1SrMDDLOnNBqNdnwpu9tk/edit?ts=5cfa8cf6
