### ISSUE TITLE
Storage location change[bug]

### ISSUE THREAD

**Issue by a8159236** [filecoin-project/go-filecoin#2826]
Hi,I installed FIlecoin0.2.2, and the default storage path is ~/. Filecoin, during which files were stored. Later, I tried to move it to a new path, as follows:
1. Stop the daemon
2. Move '. Filecoin 'and '. Filecoin_sectors' in the current sector to new sectors ' /storage'                           3. export FIL_PATH=/storage/.filecoin
4.go-filecoin daemon  --repodir=/storage/.filecoin
After the change, the program can start normally, but when I run "go-filecoin mining start ", the 'daemon' will stop running, is the method I changed incorrect?

**Comment by anorth** [comment]
Could you please most more information about what happens when you run the
daemon? The logs would be very helpful.

**Comment by frrist** [comment]
This issue has been static for the past week, when ready to resume feel free to reopen.
