### ISSUE TITLE
could not find payment channel

### ISSUE THREAD

**Issue by grandhelmsman** [filecoin-project/go-filecoin#2828]
**Describe the bug**
Error: response check failed: deal rejected: could not find payment channel for payer t1xnehcdnb5kwt33rotzgdsoe5qm5ty6itf7kzo5q and id 9

**could not find payment channel and paid the storage fee, which should not be reasonable.**

**To Reproduce**
1.
```
go-filecoin wallet balance  t1xnehcdnb5kwt33rotzgdsoe5qm5ty6itf7kzo5q
2299.8599999999999994
```
2.
```
go-filecoin wallet balance  t1xnehcdnb5kwt33rotzgdsoe5qm5ty6itf7kzo5q
2299.8599999999999994
```
3.
``` 
go-filecoin client propose-storage-deal t25n5cxbphqoukk43fg5t3fqd6rrobxs7pnlht2zi QmeieP7gvbxnrTkBDW8ra9PnDmG5hVr3EG5kzxduf7nKg7  0  100
Error: response check failed: deal rejected: could not find payment channel for payer t1xnehcdnb5kwt33rotzgdsoe5qm5ty6itf7kzo5q and id 9
```
4. 
```
go-filecoin client propose-storage-deal t25n5cxbphqoukk43fg5t3fqd6rrobxs7pnlht2zi QmeieP7gvbxnrTkBDW8ra9PnDmG5hVr3EG5kzxduf7nKg7  0  100
State:   accepted
Message: 
DealID:  zDPWYqFCs5CN4Vd2aRn4zbQ6X9BAmmvJDCWVU5JYVLJPxbozkurH
```
5. 
```
go-filecoin wallet balance  t1xnehcdnb5kwt33rotzgdsoe5qm5ty6itf7kzo5q
2259.8599999999999992
```

miner ask:
```
[root@localhost ~]# go-filecoin client list-asks |grep t25n5cxbphqoukk43fg5t3fqd6rrobxs7pnlht2zi
t25n5cxbphqoukk43fg5t3fqd6rrobxs7pnlht2zi 000 0.02 94089
```

**Comment by travisperson** [comment]
@grandhelmsman can you provide us with the output of `go-filecoin inspect all`? This will provide us with some basic information that will help us figure out what may of went wrong.

**Comment by grandhelmsman** [comment]
[root@localhost ~]# go-filecoin inspect all
{"Config":{"api":{"accessControlAllowCredentials":false,"accessControlAllowMethods":["GET","POST","PUT"],"accessControlAllowOrigin":["http://localhost:8080","https://localhost:8080","http://127.0.0.1:8080","https://127.0.0.1:8080"],"address":"/ip4/127.0.0.1/tcp/13453"},"bootstrap":{"addresses":["/dns4/user.kittyhawk.wtf/tcp/9000/ipfs/Qmd6xrWYHsxivfakYRy6MszTpuAiEoFbgE1LWw4EvwBpp4","/dns4/user.kittyhawk.wtf/tcp/9001/ipfs/QmXq6XEYeEmUzBFuuKbVEGgxEpVD4xbSkG2Rhek6zkFMp4","/dns4/user.kittyhawk.wtf/tcp/9002/ipfs/QmXhxqTKzBKHA5FcMuiKZv8YaMPwpbKGXHRVZcFB2DX9XY","/dns4/user.kittyhawk.wtf/tcp/9003/ipfs/QmZGDLdQLUTi7uYTNavKwCd7SBc5KMfxzWxAyvqRQvwuiV","/dns4/user.kittyhawk.wtf/tcp/9004/ipfs/QmZRnwmCjyNHgeNDiyT8mXRtGhP6uSzgHtrozc42crmVbg"],"minPeerThreshold":1,"period":"10s"},"datastore":{"path":"badger","type":"badgerds"},"heartbeat":{"beatPeriod":"3s","beatTarget":"/dns4/stats-infra.kittyhawk.wtf/tcp/8080/ipfs/QmcSFeiARE6DpFwsySFEVLw334HSBsqPFB3nTwkwEH2gED","nickname":"","reconnectPeriod":"10s"},"mining":{"autoSealIntervalSeconds":120,"minerAddress":"t25n5cxbphqoukk43fg5t3fqd6rrobxs7pnlht2zi","storagePrice":"0.02"},"mpool":{"maxNonceGap":"100","maxPoolSize":10000},"net":"devnet-user","observability":{"metrics":{"prometheusEnabled":false,"prometheusEndpoint":"/ip4/0.0.0.0/tcp/9400","reportInterval":"5s"},"tracing":{"jaegerEndpoint":"http://localhost:14268/api/traces","jaegerTracingEnabled":false,"probabilitySampler":1}},"sectorbase":{"rootdir":""},"swarm":{"address":"/ip4/0.0.0.0/tcp/26000"},"wallet":{"defaultAddress":"t1usjvldn6hlbhoeph6fzdhojioykzuh6rio3bxga"}},"Disk":{"FSType":"1481003842","Free":31771840512,"Total":31771840512},"Environment":{"FIL_API":"","FIL_PATH":"","GOPATH":"/opt/gopath"},"FilecoinVersion":"fcf56acdc98a2ea4fc4d0b62878a9302f51af869","Memory":{"Swap":0,"Virtual":29515828000},"Runtime":{"Arch":"amd64","Compiler":"gc","GoMaxProcs":32,"NumCGoCalls":838,"NumGoRoutines":884,"NumProc":32,"OS":"linux","Version":"go1.12.1"}}

**Comment by frrist** [comment]
Here is where the error is created:
https://github.com/filecoin-project/go-filecoin/blob/fcf56acdc98a2ea4fc4d0b62878a9302f51af869/protocol/storage/miner.go#L317-L320

cc @acruikshank or @rosalinekarr do you know what conditions can lead to a payment channel not existing for an address?

**Comment by acruikshank** [comment]
@grandhelmsman Thanks for reporting this. Each call to `client propose-storage-deal`  creates a new payment channel and sends it's id to the storage miner. The fact that the first one passed and the second one failed suggests there's a timing issue when checking the payment channels in the first command.

Could you run:
```
go-filecoin paych ls
```
?

I'm curious if you have one or two payment channels.

**Comment by anorth** [comment]
@grandhelmsman can you reproduce this issue?

**Comment by anorth** [comment]
Since this issue is old and silent, I'll close shortly unless someone objects.
