### ISSUE TITLE
[bug]Can't show the nickname

### ISSUE THREAD

**Issue by Peachooo** [filecoin-project/go-filecoin#2829]
**Describe the bug**
When we change the node nickname, it cannot be displayed on the network-->"stats.kittyhawk.wtf". Among them, some change the nickname can not display the new nickname, Others can not display the node

**To Reproduce**

**Expected behavior**

**Screenshots**

**Diagnostic information**

- Filecoin Inspect Ouput: 
- Current Head: 
- Connected Peers: 

**Version information**

- Go: 
- Rust: 
- Cargo: 
- Commit: 
- Go Env: 
- CC: 

**Additional context**

**Comment by frrist** [comment]
@Peachooo could you please share the output of `go-filecoin inspect all`, this will help us debug this issue.

**Comment by Peachooo** [comment]
@frrist The problem has been solved. Thank you for your kind help =w=
