### ISSUE TITLE
[bug]Filecoin Devnet is under controlled by one single miner

### ISSUE THREAD

**Issue by Aboatlai** [filecoin-project/go-filecoin#2831]
The miner node “t2hzrt4gppoehzb35ilsget5oqofnqbtsyuapka2a” only has 7.7% storage power ,but it is the onlyone who is packing blocks at present, and other miners cannot pack blocks. In addition, this miner  filtered signed messages from all other miners, it just pack blocks for miner node “t2uzjen2amlr4fmelga7iqqyshwi7lc35l74jobsy”. It is unfair for other miners.

These two particular miner nodes have packed more than 93% storage power，block height from 47000 to 49000. It really shocked me, and i think it is not in line with the spirit of decentralization.

Filecoin has bugs in this consensus part ? These two miner nodes had made the filecoin devnet been forked?

**Comment by anorth** [comment]
The consensus is definitely not fully implemented, yet. This behaviour won't be possible when the implementation is complete. Thanks for highlighting this behaviour is apparent on our devnet, but I don't think it's a simple "bug" to be fixed, but rather somewhat expected while our implementation is incomplete.

**Comment by taoshengshi** [comment]
@anorth @ZenGround0 @shannonwells -
I propose to close this story.
I propose to replace this story with existing story: [1791](https://github.com/filecoin-project/go-filecoin/issues/1791) / [2119](https://github.com/filecoin-project/go-filecoin/issues/2119) for discussion and research, as we know this known issue is blocked by "Research hasn't figured out which delay function to use" and "use a real delay function when generating and verifying blocks when mining." also with this [spec](https://github.com/filecoin-project/specs/blob/master/proofs.md#proof-of-space-time) are more concrete and easy for understanding.

**Comment by callmez** [comment]
@anorth Can we do anything to make it right now. 
 If it is not a "bug", now we can do nothing in the devnet until master-net up online.

**Comment by anorth** [comment]
I'm going to close this issue in favour of #2834, which outlines a short-term fix.

Discussion about whether or not to launch a new devnet can happen there. Doing so is a significant diversion for the development team.
