### ISSUE TITLE
[bug] implement block delay validation (quick fix against the attack on 0.2.2)

### ISSUE THREAD

**Issue by steven004** [filecoin-project/go-filecoin#2834]
**Describe the bug**
Attack on version 0.2.2 devnet is happening, after some investigation, this attack is using the current consensus implementation, which is not fully functional. After discussed with @whyrusleeping and @ZenGround0. 
I would suggest we have a short-term solution before we fully implement VDF for consensus part,  since the current attack could be used to mislead investors. As @whyrusleeping suggested, this can be easily addressed, then, let's do it to make the devnet work.

See more discussion in [this thread](https://filecoinproject.slack.com/?redir=%2Fmessages%2FCEHHJNJS3%2Fconvo%2FCEHHJNJS3-1558602296.079500%2F). 

**To Reproduce**
This attack is most likely doing as: 
1) Shorten the block time to a few seconds or no wait;
2) Select messages to create a block, most times only pick the messages related to this miner, and discard all others;
3) When creating a block, to calculate the ticket to see if the miner could be the next winner, if yes, send it out, if not, just produce blank block, and repeat until the new ticket could make sure it will be the next winner.

**Expected behavior**
This kind of blocks could not pass in other honest miners validation process, so that the malicous node could get any benefit from this. 

**Version information**
go-filecoin-0.2.2

**Some of the email-exchange information**
```
Hi ZenGround and Why, 

This is a follow-up of the discussion in the filecoin discussion thread. The reason I'd like to discuss more here is: it's about attacking, not very sure if it should be exposed to all audiences. 

The attacking is happening right now, and after some investigation, I would think the attacker is doing like this: 
1) Shorten the block time to about 10s or less;
2) Select messages to create a block, most times only pick the messages related to this miner, and discard all others;
3) When creating a block, to calculate the ticket to see if the miner could be the next winner, if yes, send it out, if not, just produce blank block, and repeat until the new ticket could make sure it will be the next winner.

Since the height number could be changed due to current blank block mechanism, this is a way to pass the validation of winner, and the miner once get a chance to mine a block, it will guarantee it could get the right to mine next ones. 

From current implementation of view, please confirm if it is a possible way or most likely the thing happening right now in the devnet? 

If this is true, is there a short-term way to avoid this, instead of fully implementation of VDF? e.g. in the validation of mining winner process, let the validator check the height and compare with previous height number to see the difference, and check the time difference of the two? 

Best Regards,
Steven

```

Replied by @whyrusleeping : 
```
Hey Steven,
Thanks for the email, and also thank you for the intuition to keep this private. Generally, I would be treating attacks like this with the utmost care. Given that this is just a developer network, and not even an official testnet, we prioritize transparency and speed to fix problems.

The issue can be easily addressed by adding the ’soft block delay’ to go-filecoin’s block creation and validation routines, see the ‘Verify Timestamp’ portion of ‘VerifyBlock’ here: https://github.com/filecoin-project/specs/blob/master/mining.md#block-validation and the part about choosing a timestamp in block creation: https://github.com/filecoin-project/specs/blob/master/mining.md#block-creation

Thanks,
Why
```

**Comment by steven004** [comment]
After published the reproducing steps, we see another malicious node is doing the same thing, attacking the network the same way. The miner ID is: t2upssipkmd5pbevilu43f4dujo5aphgs3mhcehqy. 

Anyone can check its owner and peerID, I would like to suggest everyone to stop this kind of attack, and let the network back to normal until the new version is ready, since the issue is found and clear, it would be more valuable to find other issues. And hope a new version with fix could be ready soon.

**Comment by anorth** [comment]
Just a note on our priorities: we will have a fix for this landed in `master` soon. 

At present, we are not planning to cherry-pick this and re-deploy the 0.2 devnet. Our SLA for the user devnet is "best effort". While the protocol implementation is still incomplete, we will generally prioritise that implementation above high devnet availability.

We can expect this (and other protocol correctness issues) to be resolved in the 0.3 release and devnet, estimated for early July 2019.

Thank you both for your active involvement and for your patience as we work towards a robust implementation.

**Comment by anorth** [comment]
An update: after more consideration and in light of continued un-usability, we are now hoping to patch the 0.2 devnet with block timestamp validation and restart it. We'll announce when that restart is imminent.

This doesn't change our plan to also release 0.3 (with much more) in July.

**Comment by steven004** [comment]
I assume this is a new version which will re-initiate the network from
scratch, right?

**Comment by anorth** [comment]
Correct!

**Comment by frrist** [comment]
Closed in https://github.com/filecoin-project/go-filecoin/pull/2899
