### ISSUE TITLE
[bug] No wait to generate block

### ISSUE THREAD

**Issue by ipfsmainofficial** [filecoin-project/go-filecoin#2836]
**Describe the bug**
In recent testing, we found a problem in the consensus mechanism. During the process of ticket computing, the node is able to choose not to wait for block time. 

**To Reproduce & Expected behavior**
If the node does not wait the block time, the consequences would be: 
1. As long as the CPU is bearable, the node is able to compute ticket without any restrictions; 
2. After the node has successfully computed the ticket, a large number of blocks would probably destroy the network. By using the large unexpected amount of blocks, it would be really difficult for other nodes to synchronize to the latest block; 
3. When a node with high storage power starts to do this, other nodes would be busy on verifying new blocks generated, resulting in no way to mine blocks, which makes thing worse;  
4. There are multiple nodes in the devnet with the highest power rankings performing similar tests. In the short term, the problem is likely to continue to exist, which affects network usage.

**Screenshots**
![image](https://user-images.githubusercontent.com/50067893/58396553-c07b0380-807f-11e9-9c80-c383bd1e985c.png)

**Version information**
go-filecoin-0.2.2

**Additional context**
All nodes would be able to choose not to wait. Therefore, it is better to solve this issue ASAP. We will do some further testings and update it here.

**Comment by anorth** [comment]
Thanks for the report. I think this is the same issue as #2834. If you agree, please close this one and we can discuss the fix there.
