### ISSUE TITLE
where is the FIL as collateral for miners when launching the filecoin mainnet ?

### ISSUE THREAD

**Issue by Peachooo** [filecoin-project/go-filecoin#2838]
### Description
I want to be a miner,But I have some question.
When launching the filecoin mainnet,Where can I catch the FIL as collateral?
If I catch the FIL as collateral by testing with sets of large scale miners or project leader distributing some FIL？Or maybe have other ways？
Waiting for your reply，thanks

**Comment by anorth** [comment]
Thanks for this question. Could you please ask it again in the [Filecoin forum](https://discuss.filecoin.io/) instead? A discussion there will be more visible to others in the community. Issues in this repository are reserved for development tasks and bug reports.

I am closing this issue now in favour of the forum.
