### ISSUE TITLE
Make `show deal` output include deals payment vouchers

### ISSUE THREAD

**Issue by shannonwells** [filecoin-project/go-filecoin#2844]
### Description
request from @acruikshank via @rosalinekarr : include a deals payment vouchers in the output from  show deals.

### Acceptance criteria
Add deals payment vouchers info to the show deal output

### Where to begin
commands/show.go

**Comment by shannonwells** [comment]
Need to know how this should be output and what to do if there isn't anything to show.

**Comment by rosalinekarr** [comment]
@acruikshank, any ideas?

**Comment by acruikshank** [comment]
Vouchers should display their index (when sorted by validAt), validAt, amount, and whether or not they have a condition (displaying the condition is unnecessary). Further work should allow the user to retrieve the encoded string of a single voucher that could be used as an argument to redeem.
