### ISSUE TITLE
[bug] .filecoin_sectors directory is unmovable 

### ISSUE THREAD

**Issue by steven004** [filecoin-project/go-filecoin#2848]
**Describe the bug**
Once I have some proven storage existing in my system already, it's impossible to change the sector root path while keeping existing power. In addition, the system keeping consuming CPU very high. 

**To Reproduce**
1. Successfully run go-filecoin-0.2.2 and complete some deals, gather some proven power, i.e. created some staging and sealed sectors;
2. Stop go-filecoin-0.2.2 daemon;
3. Move .filecoin_sectors folder to another place
4. Edit .filecoin/config.json, change sectorbase.rootdir item to reflect the change
5. Rerun go-filecoin-0.2.2 daemon, start mining
6. The daemon could catch up the chain, but will never accept deals, and CPU is very busy for long time. 

**Expected behavior**
The go-filecoin daemon could work as usual, and start accept new deals, if no replication provr running, CPU consuming should be low. 

**Version information**
go-filecoin 0.2.2

**Additional context**
After checked the .filecoin_sectors/staging/db file, which should be the table to save relationships between pieces, staging sectors and sealed sectors. It is found that absolute sector paths are saved in the db file, that might the root cause since the files are not there any more. 

We already have the sectorbase.rootdir defined,  shouldn't we only save relative path of sectors in the db?

**Comment by frrist** [comment]
Hi @steven004, thanks for filing this.

Firstly, could you provide the output of `go-filecoin inspect all`, this will make debugging a little bit easier on our end.

Secondly, can you clarify what you mean by "but will never accept deals"? What happens when you try to make a deal with the miner? Can you share the specific logs/output that indicate the miner is not accepting deals? -- Both on the client making the deal and the miner accepting the deal.

Lastly, in the interest of finding what's eating your CPU, would you mind sharing a profile of your daemon while this is occurring? This can be done using `pprof` and is covered in the profiling section of the [contributing guide](https://github.com/filecoin-project/go-filecoin/blob/master/CONTRIBUTING.md#profiling). If you share the `profile.dump` here we can take a look at it together.

**Comment by laser** [comment]
@frrist 

The Rust sector builder, when provisioning files into which user piece-bytes are written, simply [appends a forward slash (`/`) and 32 random alphanumeric](https://github.com/filecoin-project/rust-fil-proofs/blob/master/sector-base/src/api/disk_backed_storage.rs#L118) characters to the `staged_sectors_dir` path [provided to the `init_sector_builder` CGO call](https://github.com/filecoin-project/rust-fil-proofs/blob/master/filecoin-proofs/src/api/mod.rs#L202) [by go-filecoin](https://github.com/filecoin-project/go-filecoin/blob/master/proofs/sectorbuilder/rustsectorbuilder.go#L108). This value [comes from the go-filecoin Node configuration](https://github.com/filecoin-project/go-filecoin/blob/master/node/node.go#L912), and can be specified when the node is initialized.

For instance:

```
$ mkdir -p /tmp/12UFrP/

$ mkdir -p ./most/excellent/dir

$ ./go-filecoin init --auto-seal-interval-seconds=0 --repodir=/tmp/12UFrP/Ryd2lY --sectordir=./most/excellent/dir --cmdapiaddr=/ip4/127.0.0.1/tcp/53210 --genesisfile=./fixtures/test/genesis.car
```

Given the preceding commands, the sector builder snapshot (after adding a few pieces) will look like this:

```
StateSnapshot {
    prover_id: [ /* a bunch of bytes */ ],
    staged: StagedState {
        sector_id_nonce: 2,
        sectors: {
            2: StagedSectorMetadata {
                sector_id: 2,
                sector_access: "most/excellent/dir/staging/QEUEMGIDTNIEHXSMSLLCXQKRGNJUNGUN",
                pieces: [
                    PieceMetadata {
                        piece_key: "QmakAYc31gSDvDC5RQj8ffhwVqrKyhrcYD5hFpquohJ22t",
                        num_bytes: UnpaddedBytesAmount(
                            700,
                        ),
                    },
                ],
                seal_status: Sealing,
            },
            1: StagedSectorMetadata {
                sector_id: 1,
                sector_access: "most/excellent/dir/staging/MSRXUBUWKFREOLHOPTOUAHKEVDPSJCKW",
                pieces: [
                    PieceMetadata {
                        piece_key: "QmYcq7hFsd3tusZx9jjYERRPhyPfcity2EUEnN9rSvBxHu",
                        num_bytes: UnpaddedBytesAmount(
                            500,
                        ),
                    },
                ],
                seal_status: Pending,
            },
        },
    },
    sealed: SealedState {
        sectors: {},
    },
}
``` 

To support moving the sector dir, we need to drop the staging and sealed sector dir-prefixes from the sector builder snapshot (i.e. the `most/excellent/dir/staging/` above).

I [just created](https://github.com/filecoin-project/rust-fil-proofs/issues/672) an issue to track this work. Completion is TBD - but the implementation should be somewhat trivial (PRs gladly accepted).

Does that clear things up? Please let me know if we did not address your questions.

**Comment by frrist** [comment]
Thanks @laser, yup that clears this up. @steven004 changing the location of `.filecoin_sectors` will not be supported until https://github.com/filecoin-project/rust-fil-proofs/issues/672 is in -- closing this infavor of it.
