### ISSUE TITLE
[bug]There is a problem with the mining data displayed on the Devnet website.

### ISSUE THREAD

**Issue by zhengboowen** [filecoin-project/go-filecoin#2849]
The mining data on Filecoin devnet seems to have a problem. These data are displayed two days ago. Did the network not update the blockchain data in time? Or is there a problem with the blockchain data ?

![20190529 web data](https://user-images.githubusercontent.com/51158073/58550629-c1a75e80-8240-11e9-88c0-3c422bf3c309.jpeg)

**Comment by frrist** [comment]
Issue moved to [filecoin-project/filecoin-network-stats #30](https://github.com/filecoin-project/filecoin-network-stats/issues/30) via [**ZenHub**](https://www.zenhub.com/)
