### ISSUE TITLE
The seal and verify_seal operations need to be provided a ticket

### ISSUE THREAD

**Issue by laser** [filecoin-project/go-filecoin#2852]
### Description

For more information, see [this thread](https://github.com/filecoin-project/specs/issues/56#issuecomment-496675849) and [the spec](https://github.com/filecoin-project/specs/blob/master/proofs.md#seal).

As per the [ZigZag spec](https://github.com/filecoin-project/specs/blob/master/zigzag-porep.md#replication), the ticket is concatenated to the prover ID and sector ID and then hashed to produce a replica ID, which is used to compute CommRStar.

**Comment by anorth** [comment]
This responsibility will move to the storage miner module.
