### ISSUE TITLE
[bug]go-filecoin get crashed at the mining start

### ISSUE THREAD

**Issue by taoshengshi** [filecoin-project/go-filecoin#2856]
**Describe the bug**
When i am playing [localnet](https://github.com/filecoin-project/go-filecoin/wiki/Running-a-network-locally) on my computer, the go-filecoin(0.2.2) always get crashed on some nodes while other nodes works well. and if the  go-filecoin already get crashed ,it will not be able to start normally as a daemon on the same node. 

**To Reproduce**
```
go-filecoin $ ./go-filecoin init --genesisfile=./fixtures/genesis.car
go-filecoin $ ./go-filecoin daemon
```
```
go-filecoin $ mineraddr=$(jq -r '.Miners[0].Address' ./fixtures/gen.json)
go-filecoin $ peerid=$(./go-filecoin --enc=json id | jq -r '.ID')
go-filecoin $ ./go-filecoin config mining.minerAddress $mineraddr
go-filecoin $ walletaddr=$(./go-filecoin --enc=json wallet import ./fixtures/0.key | jq -r '.Addresses[0]')
go-filecoin $ ./go-filecoin config wallet.defaultAddress $walletaddr
go-filecoin $ ./go-filecoin miner update-peerid --from $walletaddr --gas-price 0.001 --gas-limit=300 $mineraddr $peerid
go-filecoin $ ./go-filecoin mining start
go-filecoin $ ./go-filecoin wallet balance $walletaddr
```
The go-filecoin always get crashed at ` ./go-filecoin mining start`.

**Expected behavior**
All above commands should work successfully.

**Screenshots**

```
thread '<unnamed>' panicked at 'Error reading the file: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/libcore/result.rs:999:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
fatal runtime error: failed to initiate panic, error 5
SIGABRT: abort
PC=0x7f5b027912a7 m=5 sigcode=18446744073709551610

goroutine 0 [idle]:
runtime: unknown pc 0x7f5b027912a7
stack: frame={sp:0x7f5afea44438, fp:0x0} stack=[0x7f5afe2450a8,0x7f5afea44ca8)
00007f5afea44338:  0000000000000000  0000000000000000
00007f5afea44348:  0000000000000000  00007f5afea444b8
00007f5afea44358:  000000000248d5d0  00007f5afea445e8
00007f5afea44368:  00007f5b02d2d269  0000000000000000
00007f5afea44378:  00000000012258b5  0000002000000000
00007f5afea44388:  00007f5afea44c03  0000000000000000
00007f5afea44398:  0000000000000001  000000000248dc18
00007f5afea443a8:  00007f5afea444b8  000000000248dc18
00007f5afea443b8:  00007f5afea44410  00007f5afea44588
00007f5afea443c8:  0000000000000001  0000000000000000
00007f5afea443d8:  00000000012264ab  0000000000000000
00007f5afea443e8:  000000000248deb8  00007f5afea44503
00007f5afea443f8:  0000000000000001  0000000000000010
00007f5afea44408:  0000000000000000  00000000019edf50
00007f5afea44418:  000000000248deb8  00007f5afea44728
00007f5afea44428:  0000000000000005  0000000000000001
00007f5afea44438: <00007f5b02792688  0000000000000020
00007f5afea44448:  0000000000000000  0000000000000000
00007f5afea44458:  0000000000000000  0000000000000000
00007f5afea44468:  0000000000000000  0000000000000000
```

**Diagnostic information**

- Filecoin Inspect Ouput: NA 
- Current Head: NA
- Connected Peers: NA

**Comment by frrist** [comment]
@taoshengshi please share the output of `go-filecoin inspect all` after the daemon panics (once it panics, restart it and run the command). 

The paths referenced in the above commands `./fixtures/gen.json`, `./fixtures/0.key` do not exist after building. Both `gen.json` and `*.key` exists under `fixtures/live/` or `fixtures/test/`. Your node will be in a misconfigured state if the above commands are run as shown. I have followed the above steps using correct paths and am unable to repo the panic.

Lastly, before you cause the panic, can you run `export RUST_BACKTRACE=1` before starting the daemon? This will give us more information about the panic.

**Comment by travisperson** [comment]
I've updated the wiki to reflect the new locations. You may try with the fix paths. If you run into this issue again you can reopen this issue. I'm going to close for it for now though.
