### ISSUE TITLE
Automatically cancel payment channel when a deal fails

### ISSUE THREAD

**Issue by acruikshank** [filecoin-project/go-filecoin#2857]
### Description

There a many failure scenarios for creating storage deals that are detectable before the propose-storage-deal completes. In this case, it would be nice if the command could automatically cancel the payment channel so the client doesn't have to do it manually.

Cancelling the payment channel will allow the client to reclaim funds from the channel after some timeout.

### Acceptance criteria

1. All detectable conditions that occur during propose-storage-deal after the creation of the payment channel that guarantee the files will not be stored trigger a cancel.

**Comment by anorth** [comment]
@acruikshank I'm going to remove this from the epic #2481 for now so we can focus on other required functionality. The CLI provides the required commands for a user to recover funds manually.

**Comment by anorth** [comment]
Obsolete
