### ISSUE TITLE
[bug] Unable to build 0.2.2 from source

### ISSUE THREAD

**Issue by frrist** [filecoin-project/go-filecoin#2859]
**Describe the bug**
The command `go run ./build/*go build` panics when building tag `0.2.2`.
```
frrist@pine ~/s/g/f/go-filecoin ((0.2.2))> go run ./build/*go build
Building go-filecoin...
git log -n 1 --format=%H
go build -ldflags -X github.com/filecoin-project/go-filecoin/flags.Commit=fcf56acdc98a2ea4fc4d0b62878a9302f51af869 -v -o go-filecoin .
Building gengen utils...
go build -o ./gengen/gengen ./gengen
Building faucet...
go build -o ./tools/faucet/faucet ./tools/faucet/
Building genesis file server...
go build -o ./tools/genesis-file-server/genesis-file-server ./tools/genesis-file-server/
Generating genesis...
./gengen/gengen --keypath fixtures/live --out-car fixtures/live/genesis.car --out-json fixtures/live/gen.json --config ./fixtures/setup.json
panic: json: cannot unmarshal string into Go struct field .Power of type uint64

goroutine 1 [running]:
github.com/filecoin-project/go-filecoin/fixtures.init.0()
        /home/frrist/src/github.com/filecoin-project/go-filecoin/fixtures/constants.go:68 +0x760
Command './gengen/gengen --keypath fixtures/live --out-car fixtures/live/genesis.car --out-json fixtures/live/gen.json --config ./fixtures/setup.json' failed: exit status 2
exit status 1
```

**To Reproduce**
`$ git checkout 0.2.2`
`$ go run ./build/ deps`
`$ go run ./build/ build`

**Expected behavior**
Filecoin builds without panicking.

**Diagnostic information**

- Filecoin Inspect Output: N/A
- Current Head: fcf56acdc98a2ea4fc4d0b62878a9302f51af869
- Connected Peers:  N/A

**Version information**

- Go: `go version go1.12.1 linux/amd64`
- Rust: `rustc 1.35.0 (3c235d560 2019-05-20)`
- Cargo: `cargo 1.35.0 (6f3e9c367 2019-04-04)`
- Commit: fcf56acdc98a2ea4fc4d0b62878a9302f51af869
- Go Env: 
```
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/frrist/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/frrist"
GOPROXY=""
GORACE=""
GOROOT="/home/frrist/.apps/go"
GOTMPDIR=""
GOTOOLDIR="/home/frrist/.apps/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build066941056=/tmp/go-build -gno-record-gcc-switches"
```
- CC: `gcc (GCC) 8.3.0`

**Comment by travisperson** [comment]
Looks like we are loading some data from disk in an `init` func. The issue here is that we recently changed the type of the `Power` field of miners in this `gen.json` file (#2768). Because it's parsed during `init`, gengen fails immediately to parse the file due to the change in types (as it depends on fixtures somewhere).

The work around would be to remove the contents of `./fixtures/tests/` (or at minimum the `gen.json` file).

I've created #2861 to track some work so we can avoid this failure in the future as the structure changes.
