### ISSUE TITLE
[bug] Error: response check failed: deal rejected: 

### ISSUE THREAD

**Issue by yangjian102621** [filecoin-project/go-filecoin#2863]
The miner is mining for 10 days, it has sealed 300GB data every thing is run well.
But i got the problem when post a deal to the specified miner today. The connection of client and miner is normal(i did by ran `go-filecoin ping {MinerNodeID}`).

Here is the log information:
```
Error: response check failed: deal rejected: Timeout waiting for payment channel: context deadline exceeded
```
All of my three nodes has occurred the same error at today. so who can tell me what's wrong? Thanks.

**Comment by frrist** [comment]
Hi @yangjian102621, thanks for the issue report. Could you include details below so we can investigate? In its current form this issue does not provide enough details to debug the problem, please provide the following:
1. Your go-filecoin version
2. Output from command `go-filecoin inspect all`
3. Current Head: `go-filecoin chain head`
4. Connected Peers: `go-filecoin swarm peers`
5. Payment Channels: `go-filecoin paych ls`

**Comment by yangjian102621** [comment]
@frrist which node should i provide information about it? The miner node or the client node?

**Comment by frrist** [comment]
Information on all nodes participating in the deal would be ideal -- both your client and miner node.

**Comment by yangjian102621** [comment]
@frrist I restart the nodes, and it works normal. i will provide you information when it appear again next time. thanks.

**Comment by frrist** [comment]
Going to close this then, please reopen if the issue occurs again.
