### ISSUE TITLE
sector collateral should be computed using baseline/pro-rata construction

### ISSUE THREAD

**Issue by laser** [filecoin-project/go-filecoin#2866]
### Description

The _Pledge Collateral Design Doc (Baseline Pro-rata Construction)_ demonstrates a mechanism for computing the collateral required of a miner who wants to commit to a sector. After chatting with @ZenGround0 and @whyrusleeping, we learned that we should use this construction to compute sector collateral. The existing software calls a stubbed `CollateralForSector(miner.SectorSize)` that produces a constant value `0.001FIL`.

### Acceptance criteria

- baseline pro-rata construction takes the place of `CollateralForSector(miner.SectorSize)`

**Comment by anorth** [comment]
Thanks for the issue. I don't think the collateral function is sufficiently final that we should put too much time into it, but it would be good to ensure we can provide the appropriate parameters at call site.

**Comment by yaohcn** [comment]
@laser   Where can I find the document (Pledge Collateral Design Doc) ?

**Comment by anorth** [comment]
We now have a spec for pledge collateral function: https://github.com/filecoin-project/specs/blob/master/pledge-collateral.md

Implementation depends on a model for FIL emissions, but until that is defined we could stub it out with a linear function for now, thus exercising the feature that collateral requirements grow with time.

**Comment by anorth** [comment]
Obsolete, this is now in actors.
