### ISSUE TITLE
Design and implement IntSet a bitfield based integer set

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/go-filecoin#2867]
### Description

Implement design of the go IntSet datastructure finalized here: https://docs.google.com/document/d/1aE5a-QZojprMkig6IyYkwV1SrMDDLOnNBqNdnwpu9tk/edit

We should check if go already has something like this builtin, or if there are good OSS solutions already out there.  If not we should write this and put it in types/intset.  

### Acceptance criteria
Implemented using bit operators, unit tested
Operations:
* Union
* Intersection
* Set difference
* Contains
* List positions of all flipped bits

### Where to begin
Look for existing implementations in standard libs / open source
If can't find anything look up standard methods (they definitely exist)

**Comment by ingar** [comment]
Resolved with #2913.
