### ISSUE TITLE
Pipe Bitfield params through submitPoSt interface 

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/go-filecoin#2869]
### Description
After #2868 you will have a working method to transfer a set of sectorIDs to a spec compliant Bitfield (rle+ encoded integer set).  

Add the done and recovered sets to the submitPoSt state machine function signature.  

Do dummy Bitfield construction of these parameters within the storage miner's submitPoSt logic (for now just encode all 0s).

### Acceptance criteria
submitPoSt has a recovered and done set and the network works as normal (miners generate correct submitPoSts)

### Where to begin
ABI files, miner actor, either node.go or protocol/storage/miner.go (can't remember which) has a goroutine that generates PoSts and needs to be updated to include these arguments.

**Comment by anorth** [comment]
I think this is the same as #2889 (and that one has a bit more info and ZenHub dependency links). @ZenGround0 please close in favour of that, or clarify what this one needs. cc @ingar
