### ISSUE TITLE
SectorSet: AMT design spike

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/go-filecoin#2887]
### Description
We need to solidify the design of the A[rray]M[apped]T[rie] structure proposed as the implementation for sector sets

We should write this as a subpackage of actor.  This issue is done when we have a plan for all of the software changes needed to make this AMT in software and spec it out in prose.

### Acceptance criteria
Build a prototype AMT to implement SectorSets.  Likely file several issues after this spike for writing/factoring into something more robust.  Don't forget to track work for writing up the spec for this.

### Risks + pitfalls
Don't rush in without understanding what's going on BUT
Don't spend too much time reading about it before trying to build it

### Where to begin
Read through [the design doc](https://docs.google.com/document/d/1aE5a-QZojprMkig6IyYkwV1SrMDDLOnNBqNdnwpu9tk/edit) to get the background and relevant links.

go-hamt-ipld spec and code, the Bagwell HAMT paper and the sectorset spec issue (links in doc) are all going to be useful.

**Comment by ZenGround0** [comment]
This currently exists [in this spec PR](https://github.com/filecoin-project/specs/pull/333).  It is low priority for me to get this spec PR through to completion but I'd like to get to it within a few weeks.  Word on the street is that @whyrusleeping plus some others might be leading the implementation charge on this one.

**Comment by anorth** [comment]
@ZenGround0 I think we can close this now. The AMT still needs to be implemented, but that's a different issue, and the work may happen outside go-filecoin.
