### ISSUE TITLE
Update state machine to use a SectorSet AMT

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/go-filecoin#2888]
### Description
After the work begun in #2887 has provided go-filecoin with an AMT-based SectorSet we need to update the miner actor to track its sector storage in this datastructure.

This will make #3007 obsolete.

### Acceptance criteria
Use SectorSet instead of golang map in miner actor storage

### Where to begin
Look at how HAMT based storage works.  The AMT should be designed similarly enough that hooking up vm blockstorage to the AMT should be straightforward.

**Comment by anorth** [comment]
This issue is blocked by implementation of the AMT IPLD structure.

A spec for this is happening here: https://github.com/ipld/specs/pull/137

**Comment by anorth** [comment]
@whyrusleeping has the initial implementation of AMT here: https://github.com/filecoin-project/go-amt-ipld

cc @hannahhoward while you are investigating HAMT storage layer improvements #3223 #3078. My first glance at the AMT code looks like it has the interface we need to swap in our own storage layer.

**Comment by anorth** [comment]
Done (@acruikshank)
