### ISSUE TITLE
Add fault and recovered sets to SubmitPost

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/go-filecoin#2889]
### Description
FaultSets are a simple data structure wrapping a Bitfield and a BlockHeight.  

### Acceptance criteria
Implement this wrapper.  
Add it as a parameter to the submitPoSt state machine function signature. 
Pass in dummy value of no faults from the storage miner protocol code.

### Risks + pitfalls
Representing the 0 value might be a bit weird.
This depends on on Bitfield encodings being implemented: #2868 

### Where to begin
See [this relevant design doc](https://docs.google.com/document/d/1aE5a-QZojprMkig6IyYkwV1SrMDDLOnNBqNdnwpu9tk/edit)

**Comment by ZenGround0** [comment]
Note, there are some todos introduced in #2999 referencing this issue as the place to change IntSets to be serialized as RLE+.  That might be better split into a preceding PR.

**Comment by ingar** [comment]
Question about implementing the [`FaultSet`](https://github.com/filecoin-project/specs/blob/master/data-structures.md#faultset) as described in the spec:
```
type FaultSet struct {

        // offset from start of proving period
	index UInt

        // sector ids that had faults
	bitField BitField
}
```
Currently, the rust sector builder [doesn't return any notion of a block height](https://github.com/filecoin-project/go-filecoin/blob/707e7c31406ca1127ee380fee2598221cfbdb063/proofs/sectorbuilder/rustsectorbuilder.go#L390-L393).  Is having the block height needed? Will we at some point be getting a slice of faults back from rust-fil-proofs?  Should we ignore it for now?

@laser @ZenGround0 @dignifiedquire

**Comment by laser** [comment]
Now that I look at it, FaultSet is an interesting type. What does the “index” field indicate? The block height at which a storage fault is detected? Is it expected that a single Rational PoSt generate call produce more than one FaultSet? What about Beacon? or Surprise?

Of all the PoSt constructions I know about, Beacon seems like the only one which would be able to produce more than one FaultSet (and, at maximum, one FaultSet per “step”). The other constructions either learn of the chain height once, when PoSt generation begins or, as is the case with Surprise, at some single point during the proving period.

**Comment by ZenGround0** [comment]
As @laser makes clear in the comment above this is likely to swirl as the PoSt construction develops.  We should feel free to choose something for now and expect it to change later.
