### ISSUE TITLE
Functional test to assert deal vouchers with conditions can be redeemed

### ISSUE THREAD

**Issue by acruikshank** [filecoin-project/go-filecoin#2918]
### Description

We need a way to round trip test the creation of deal vouchers with conditions and their redemption. #2891 made progress towards this by testing the new `deal redeem` command, but its integration test only tests whether the last voucher of the deal can be redeemed, and the last voucher does not contain a condition.

### Acceptance criteria

1. Create an integration test that creates a deal with more than one voucher and then redeems the first voucher (with a condtion).

### Risks + pitfalls

Deal vouchers are created on a schedule. Currently the interval between vouchers is 1000 blocks. This means 1000 blocks will need to elapse before the first voucher can be redeemed. To write a test that does this we will need to:

* Decrease the block time and wait a long time.
* Figure out how to fast forward block heights in tests
* Make the payment interval configurable so that it can be greatly decreased in tests.

**Comment by anorth** [comment]
Do you strictly mean *functional* test? An in-process integration test could achieve this with full control over those things – we just need to establish patterns of doing so. Ref #2194

**Comment by acruikshank** [comment]
An in process test would be fine so long as it can effectively simulate both the client and miner sides of the deal.

**Comment by anorth** [comment]
Deal payment will be automated by the chain with the new spec, no vouchers.
