### ISSUE TITLE
Change proving period to 1000 blocks

### ISSUE THREAD

**Issue by anorth** [filecoin-project/go-filecoin#2920]
### Description
Our Proving Period is 20x Too Long.  We should change it this release cycle. This will allow us to test PoST submission and slashing. We may want to allow this to be changed in config

Change from 20,000 to 1,000 blocks.

This will still be an interim value, a final value to be determined later.

Note that period depends on sector size, so this is probably for the 1GB sectors.

**Comment by frrist** [comment]
Closed in #2930
