### ISSUE TITLE
Remove config package from plumbing

### ISSUE THREAD

**Issue by rosalinekarr** [filecoin-project/go-filecoin#2928]
### Description

Plumbing is intended to be a thin wrapper around core services, so the logic present in `plumbing/cfg` disagrees with our stated goals around architecture in the project. We need to extract logic from this package into `config` and `repo` and remove it from `plumbing`.

**Comment by frrist** [comment]
Decided not to go this route: https://github.com/filecoin-project/go-filecoin/pull/2929#pullrequestreview-249668902
