### ISSUE TITLE
Placeholder: implement ArbitrateDeal actor method

### ISSUE THREAD

**Issue by anorth** [filecoin-project/go-filecoin#2943]
### Description
As part of storage protocol dispute resolution, the storage miner must have an `ArbitrateDeal` method, which transfers some part of the miner actor's storage collateral (distinct from pledge collateral) to the client of a failed deal.

See [faults and slashing design doc](https://docs.google.com/document/d/1U3b9GVNVOLoS_-q9kXU3a9dqHGvcrHprwDFzNYgLI0M/edit?pli=1#heading=h.anj0qf3angix) and [actor spec](https://github.com/filecoin-project/specs/blob/master/actors.md#arbitratedeal)

Work includes:
- actor method implementation
- CLI commands for invoking deal arbitration on behalf of a client

This should probably be broken out into more stories for implementation.

**Comment by anorth** [comment]
Implementation is blocked on piece inclusion proofs from the prover. This is also waiting on https://github.com/filecoin-project/specs/issues/60, https://github.com/filecoin-project/specs/issues/159, https://github.com/filecoin-project/specs/issues/306

**Comment by acruikshank** [comment]
When this feature is implemented, it will need to temproarily store a set of arbitrated deals in the miner actor `ArbitratedDealSet` to prevent a client from arbitrating the same deal twice. This set will need to be cleared in `SubmitPoSt` which is where this work intersects with the SubmitPoSt revamp #2813.

**Comment by acruikshank** [comment]
This is no longer blocked on piece inclusion proofs, but it is blocked on #1211

**Comment by anorth** [comment]
The October 2019 spec dispenses with this arbitration, in favour of automatic arbitration via a cron system actor.
