### ISSUE TITLE
Remove LastPoSt from miner actor

### ISSUE THREAD

**Issue by acruikshank** [filecoin-project/go-filecoin#2947]
### Description

In `VerifyPieceInclusion`, we currently establish whether a miner is currently storing a sector by checking that the sector exists in the miner's committedSectors and checking `LastPoSt` to ensure they have sent a proof with the proving period window. This does not account for sectors with faults or sectors that miners have chosen to remove (done sectors). 

We still need to ensure that that the miner is still active. We have two block heights related to the block at which the last post was submitted: `LastPoSt` and `ProvingPeriodEnd`. Only the later is in the spec, so we should use it for these types of calculations.

### Acceptance criteria

1.  Change `VerifyPieceInclusion` to use `ProvingPeriodEnd` rather than `LastPoSt` to determine whether the miner has run out of time. The time out should be the same timeout (currently `ProvingPeriodEnd + GenerationAttackTime`) used to determine a miner is past the point of paying late fees and slashable.
2. Remove LastPoSt as it should now be unused.

**Comment by ZenGround0** [comment]
-- edit --
The above description has a small error.  `LastPoSt` should be replaced with `SectorCommitments` above.  `LastPoSt` is a blocktime tracking when the previous submitPoSt occurred.  `SectorCommitments` is the full map of sectorIDs and commitments and the `ProvingSet` can in general be a subset of it.  Concretely this story should filter `SectorCommitments` by inclusion in the `ProvingSet` while iterating over the commitments in `submitPoSt`

This story should not remove `LastPoSt`

This story should also make improvements to the iteration interface on the `SectorSet` type I am introducing in #2948 which just uses regular map iteration right now and will eventually need to change.

**Comment by acruikshank** [comment]
@ZenGround0 I think the intent of this issue was unclear. We currently use LastPoSt only in VerifyPieceInclusion to establish whether the miner has been keeping up with their proofs. We have now have a better way to establish whether sector is still good by checking whether it exists in the proving set. You are correct that we still need to check the block time to ensure that the PoSts are up to date. LastPoSt is redundant with ProvingPeriodEnd, though. It's also not in the spec, so we should remove it.

I'll rewrite this story to be more clear.

**Comment by ZenGround0** [comment]
@acruikshank Thanks, I was mistaking this for what is now Issue #3003

**Comment by acruikshank** [comment]
I was wrong about this. We should just be checking whether the sector is in the sector commitments and that the miner is within the generation attack time of the proving period end.

A sector will be in the sector commitments if it has been committed and is not yet faulted, done, or the miner has been slashed. A sector will be in the proving set if it needs to be proven on in the current proving period and not yet faulted, done or the miner slashed. `verifyPieceInclusion` should not consider a piece invalid if it is in a sector that has been committed but not yet included in a proving period.

**Comment by acruikshank** [comment]
Most of this work has been done in #3195. The only remaining work is to remove `LastPoSt`.
