### ISSUE TITLE
Add `ProvingSet` and `NextDoneSet` ` to miner actor

### ISSUE THREAD

**Issue by acruikshank** [filecoin-project/go-filecoin#2948]
### Description

We need to track which sectors a miner is currently proving on at any moment. `ProvingSet` is a `SectorSet` (#2887) that contains sector commitments for all sectors that have at least one proof of spacetime (PoSt) and have not been marked done or permanently faulted.

The `NextDoneSet` stores the `done` BitField parameter from the previous `SubmitPoSt`. This gives clients one proving period of warning that sectors are about to be removed. The removal of active collateral based on this parameter is not included within this story

This story needs spec clarification about which of these is a SectorSet and which is a bitfield.

### Acceptance criteria

1. Add NextDoneSet
2. Store `done` in `NextDoneSet`
3. Add `ProvingSet`
4. Compute `ProvingSet` from sector set - NextDoneSet

**Comment by ZenGround0** [comment]
FYI from my reading of the spec's intention I'm confident these should be IntSets (i.e. Bitfields) and not SectorSets (there should only be one of those).  I am raising this assumption in a [spec issue](https://github.com/filecoin-project/specs/issues/346) and will follow up in the specs repo to keep it up to date with the output of this story.

**Comment by acruikshank** [comment]
I agree completely with NextDoneSet. If SectorSets were a data structure that supports structural sharing, the difference between making ProvingSet a SectorSet vs. an IntSet would be small and a ProvingSet would be slightly simpler. Given that we are going to implement ProvenSet before we have that data structure, we should make it an IntSet.
