### ISSUE TITLE
SubmitPoSt validates faults, recovered and done

### ISSUE THREAD

**Issue by acruikshank** [filecoin-project/go-filecoin#2949]
### Description

Providing faults, recovered and done parameters to SubmitPoSt allows the miner to deal with the realities of storage failure and to bring storage offline gracefully. This work is to validate these three fields as parameters to the SubmitPoSt Code that calls SubmitPoSt may provide these parameters as empty structures.

* `FaultSet` is a block height plus an `IntSet` #2913
* `faults` is a slice of `FaultSets`
* `recovered` is an `IntSet`
* `done` is an `IntSet`

### Acceptance criteria

1. SubmitPoSt validates that recovered is a subset of faults
2. SubmitPoSt validates that faults and done are disjoint
3. SubmitPoSt validates that every sector referenced by faults and done is in the miner's sector set (or committedSectors)
4. Validation is fully tested.

**Comment by anorth** [comment]
Moving back to backlog - this isn't stable enough in the spec to implement yet.

**Comment by anorth** [comment]
Closing until we re-implement the actors from the new spec.
