### ISSUE TITLE
Recompute storage power each SubmitPoSt

### ISSUE THREAD

**Issue by acruikshank** [filecoin-project/go-filecoin#2950]
### Description

After all new sectors are added and all permanent faults and completed sectors are removed from the proving set, a miner's storage power must be updated. The new power should be computed from the size of the proving set and the total network storage power must be updated in the storage market actor.

### Acceptance criteria

1. Compute storage power from the size of the new proving set
2. Update `miner.Power`
3. Send delta to `storagemarket.UpdatePower`

**Comment by merced** [comment]
Would you clarify the definition of "completed sectors"? Does that mean those with pieces out of storage deal duration?
Thank you!

**Comment by acruikshank** [comment]
@merced In this case "completed sectors" means sectors that the miner has marked as done by flagging them in the done BitField and will not be proving in future PoSt submissions. SubmitPoSt has no visibility into the pieces that are in deals.
