### ISSUE TITLE
[bug]test-devnet-0.2.4 introduce a new bug ？Devnet is in a crash state

### ISSUE THREAD

**Issue by zhengboowen** [filecoin-project/go-filecoin#2979]
test-devnet-0.2.4 introduce a new bug when incorporating new code (block  timestamp check) ? 

Or, is it because of a bug that is not isolated from the old version of the blocks ?

![filecoindevnet旧版本区块没有隔离](https://user-images.githubusercontent.com/51158073/59894593-cb714b80-9413-11e9-8cfc-5087a6a0b8bb.png)

![devnet20190621](https://user-images.githubusercontent.com/51158073/59894601-d0ce9600-9413-11e9-8a9c-f7516e089228.jpg)

**Comment by travisperson** [comment]
This is a known issue. We did not address this participial issue in the 0.2.4 update.

Previous issue on this was https://github.com/filecoin-project/go-filecoin/issues/2755

Work to address this issue in captured in https://github.com/filecoin-project/go-filecoin/issues/2782 and https://github.com/filecoin-project/go-filecoin/issues/2783
