### ISSUE TITLE
[bug]go-filecoin 0.2.4 miner create error. Error: Could not create miner.  actor not found

### ISSUE THREAD

**Issue by titilami** [filecoin-project/go-filecoin#2981]
**Describe**
i read the document in https://github.com/filecoin-project/go-filecoin/wiki/Mining-Filecoin
https://github.com/filecoin-project/go-filecoin/wiki/Getting-Started

while i run  
>go-filecoin miner create 10 100 --gas-price=0.001 --gas-limit=300 --peerid `go-filecoin id | jq -r '.ID'`

 it returns:
> Error: Could not create miner. Please consult the documentation to setup your wallet and genesis block correctly: no actor at address t1ltbiun6f6f2ah6y7cdsmfdqbs2wb5c5fs4u5y7i: actor not found

**Version information**
os: ubuntu 18.04.2 LTS
go-filecoin 0.2.4
> go-filecoin version
returns:
commit: 5c9b751f3a126c75057dd273f9bdb86e3e474fdd

> go-filecoin address ls
returns:
t1ltbiun6f6f2ah6y7cdsmfdqbs2wb5c5fs4u5y7i

when i get FIL from the Filecoin faucet: http://user.kittyhawk.wtf:9797/
it also returns: failed to send funds.

> go-filecoin wallet balance t1ltbiun6f6f2ah6y7cdsmfdqbs2wb5c5fs4u5y7i
returns:
 0

i initialized go-filecoin by
>go-filecoin init --devnet-user --genesisfile=https://genesis.user.kittyhawk.wtf/genesis.car

i can see my node in https://stats.kittyhawk.wtf/storage/mining

how to start mining?

**Comment by titilami** [comment]
it works now.  i get FIL from the Filecoin faucet and run ```go-filecoin mining start``` success

**Comment by barnettshao** [comment]
how do you resolve this question?
