### ISSUE TITLE
Error: Could not Init Node[bug]

### ISSUE THREAD

**Issue by chenxiaolin0105** [filecoin-project/go-filecoin#2985]
I run into this error when I run the below command
rm -rf ~/.filecoin
go-filecoin init --devnet-user --genesisfile=https://genesis.user.kittyhawk.wtf/genesis.car

the error information is:
initializing filecoin node at 
22:08:16.370  INFO     badger: All 0 tables opened in 0s
 logger.go:46
22:08:16.377  INFO     badger: All 0 tables opened in 0s
 logger.go:46
22:08:16.380  INFO     badger: All 0 tables opened in 0s
 logger.go:46
22:08:16.384  INFO     badger: All 0 tables opened in 0s
 logger.go:46
22:08:18.792  INFO     badger: Got compaction priority: {level:0 score:1.73 dropPrefix:[]} logger.go:46
22:08:18.792  INFO     badger: Running for level: 0
 logger.go:46
22:08:18.794  INFO     badger: LOG Compact 0->1, del 1 tables, add 1 tables, took 1.926039ms
 logger.go:46
22:08:18.795  INFO     badger: Compaction for level: 0 DONE logger.go:46
22:08:18.795  INFO     badger: Force compaction on level 0 done logger.go:46
22:08:18.795  INFO     badger: Got compaction priority: {level:0 score:1.73 dropPrefix:[]} logger.go:46
22:08:18.796  INFO     badger: Got compaction priority: {level:0 score:1.73 dropPrefix:[]} logger.go:46
22:08:18.796  INFO     badger: Got compaction priority: {level:0 score:1.73 dropPrefix:[]} logger.go:46
Error: Could not Init Node: unmarshal error: stream contains key "timestamp", but there's no such field in structs of type types.Block

How to solve this problem

**Comment by frrist** [comment]
@chenxiaolin0105 please provide the version of the go-filecoin binary you are using. In the latest release a timestamp field was added to the block structure. You may read more about that [here](https://github.com/filecoin-project/go-filecoin/blob/master/CHANGELOG.md#go-filecoin-024)


----------
The error message:
> Error: Could not Init Node: unmarshal error: stream contains key "timestamp", but there's no such field in structs of type types.Block

likely means you are using an older version of the filecoin binary that does not support the new field. You can checkout the correct version of code by running: `git checkout test-devnet-0.2.4`.
