### ISSUE TITLE
Remove Duplicate Content in "Troubleshooting & FAQs", Subsection "Mining and deals"

### ISSUE THREAD

**Issue by Kentix** [filecoin-project/go-filecoin#2986]
### Description

Under the documentation titled, "Troubleshooting & FAQs", in the "Mining and deals" subsection, the bullet point titled "Proposing deal fails: error sending proposal: context deadline exceeded" is duplicated.

### Acceptance criteria

All bullet points in documentation should contain unique content.

### Risks + pitfalls

N/A

### Protocol Changes

N/A

### Where to begin

N/A

**Comment by Kentix** [comment]
**Adding Screenshot for clarity, seen below:**

![image](https://user-images.githubusercontent.com/31446072/59980288-ad494e00-95c1-11e9-83bf-775991eb67d2.png)

**Comment by Kentix** [comment]
Additionally, I just noticed that the bullet in that same vicinity is also a duplicate. The tile of the bullet point is "Proposing deal fails: error creating payment: context deadline exceeded".

**Comment by anorth** [comment]
This documentation has moved to https://github.com/filecoin-project/docs, but the great thing about that is that you can now make a PR!

I'm closing this issue, but we welcome improvements to the docs in their new home.
