### ISSUE TITLE
how to improve the speed of data storage

### ISSUE THREAD

**Issue by chengzhigen** [filecoin-project/go-filecoin#2988]
### Description
Excuse me, how to improve the speed of data storage, I now use commands to save data very slowly, about 20 minutes before there is 0.2G data, see other miners save data very quickly. Another question is how to increase the% of Blocks Mined value. Is this automatic? Or is there any command execution like storing data that would have this value?

Please first see README for how to get help before filing a new issue.

**Comment by frrist** [comment]
Hey @chengzhigen, I do not understand the question. Per the [README.md](https://github.com/filecoin-project/go-filecoin#community) GitHub issues are for reporting bugs and contributing to ongoing development. Please ask questions of this nature in the [Filecoin Community Forum](https://discuss.filecoin.io/).
