### ISSUE TITLE
change pledge after creating miner

### ISSUE THREAD

**Issue by titilami** [filecoin-project/go-filecoin#2989]
### Description
i create miner by 

> go-filecoin miner create 10 100 --gas-price=0.001 --gas-limit=300 --peerid `go-filecoin id | jq -r '.ID'`

how to change the pledge for my node? e.g 10 to 1000.  i don't want to delete node and create miner again.
thx

**Comment by frrist** [comment]
Hi @titilami, great question. In later releases a `DePledge()` method will be added to the miner actor that will allow you to retrieve filecoin your miner has pledged to the network. This is currently not supported. For more information on this refer to the spec: https://github.com/filecoin-project/specs/blob/master/actors.md#depledge
