### ISSUE TITLE
Clients can get estimates of miner storage

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/go-filecoin#2991]
### Description
The CLI should expose a miner reported estimate of available storage so that clients can decide who to make deals with.  We removed pledge for spec compliance, maybe we should consider adding it back.  We could also use the miner actor's collateral balance as a proxy for expected storage to bring online.  We could also have a simple query protocol to do all of this offchain.

**Comment by anorth** [comment]
Medium term, the whole storage deal protocol will move off chain, so we
shouldn't add anything that relies chain data. However, querying collateral
and committed sector size makes sense.

**Comment by laser** [comment]
I'd like to understand better which pieces of information a storage client would like to see from a target storage miner. 

I believe that the storage client will want to see the target miner's sector size (this information is available on-chain). What else do they want to see?

**Comment by ZenGround0** [comment]
@laser the top complaint I hear is that clients want to know the answer to the yes/no question: "Does this storage miner have enough room left for me to make a deal with this data".  That is the basic bit of information current users struggle with that motivated filing this issue.  

Querying "inactive collateral" might good for this depending on how the protocol dictates miners can manage their funds.

**Comment by laser** [comment]
> Does this storage miner have enough room left for me to make a deal with this data

If querying the storage miner to determine inactive collateral and using that to determine how many additional sectors the miner can commit (and therefore if the storage client's piece will "fit"), then we don't have much software to write (and no rust-fil-proofs code modifications to make).
