### ISSUE TITLE
Rename core and cleanup

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/go-filecoin#2992]
### Description
The name `core` has long outlived its usefulness.  It has become a home for the outbound message queue and the message pool and should be split into a messaging package, or better yet a message-queue and message-pool package.

The functions that remain in testing.go all need a new home.  The `Must` methods should likely be changed to `Require` methods too because we don't typically panic during test failure.

### Acceptance criteria
core is no more
### Risks + pitfalls
Users of testing.go are a bit spread across the codebase.  Likely they can all be moved to either a messaging specific testing.go or to testhelpers/core.go, consensus.go

### Where to begin
Trace down all users of core testing.

**Comment by anorth** [comment]
The `core` package is gone (most of it lives now in the `message` package). As part of that, I split up its `testing.go` and sent the pieces somewhere sensible (or deleted duplicates).
