### ISSUE TITLE
How to check if synchronization is complete?

### ISSUE THREAD

**Issue by yangjian102621** [filecoin-project/go-filecoin#2993]
Well, Is there any API or command to help me to knows if my node is I have completed the synchronization?

**Comment by frrist** [comment]
This is covered in the wiki, see section: [Wait for Chain Sync](https://github.com/filecoin-project/go-filecoin/wiki/Getting-Started#wait-for-chain-sync). You will need to compare your nodes current head height the with height shown on https://stats.kittyhawk.wtf/

**Comment by yangjian102621** [comment]
@frrist I know that way, but this must be judged manually.
I want to know if there is a command or chain api to do this, such as the Ethereum `eth.syncing` command, return false if the synchronization is complete.

**Comment by frrist** [comment]
There does not exist a command like the one you have described. A command like that may be added as a follow on to: https://github.com/filecoin-project/go-filecoin/issues/1160

**Comment by yangjian102621** [comment]
@frrist 
Ok, i get it.  
thanks.
