### ISSUE TITLE
Flaky Test "TestDealsShowPaymentVouchers"

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/go-filecoin#2996]
**Describe the bug**

`TestDealsShowPaymentVouchers` keeps flaking on CI and working on my machine
**To Reproduce**

**Expected behavior**

No flakes
**Screenshots**

https://circleci.com/gh/filecoin-project/go-filecoin/21415#tests/containers/2

**Version information**

PR #2990 branch commit: 399761c4153e9a1e08527646731fb0312dc2d26a

**Additional context**

**Comment by ZenGround0** [comment]
ok this is a weird one.  After looking into it more the issue is that within the fast series `CreateStorageMinerWithAsk`, action `MiningStart` cannot see the new miner actor in the chain when trying to set up its sector builder, leading to this error.
```
Error: failed to initialize sector builder: failed to get sector size for miner w/address t2piset336owfhmysdqssqgab4ifxtnjyymtcwyji: query and deserialize failed: 'getSectorSize' query message failed: querymethod returned an error: failed to get To actor: actor not found
```

This should never be the case because the previous serial action is `MinerCreate` which is a blocking go-filecoin command that only returns when the miner actor is visible in the node's chain.  There is something happening that causes the second action to see a different head.  A reorg should not happen within fast as it should be a controlled environment but a reorg would explain this.

**Comment by ZenGround0** [comment]
Just observed same behavior locally on `TestDealsShow`
<details><summary>click for log</summary>
<p>

```
--- FAIL: TestDealsShow (8.50s)
    require.go:794: 
        	Error Trace:	deals_daemon_test.go:200
        	Error:      	Received unexpected error:
        	            	filecoin command: [go-filecoin mining start], exited with non-zero exitcode: 1
        	Test:       	TestDealsShow
    log_writer.go:44: >>>> start-dump
    log_writer.go:44: ---- command     go-filecoin mining stop
    log_writer.go:44: ---- exit-code   0
    log_writer.go:44: ---- error       nil
    log_writer.go:44: ---- stdout
    log_writer.go:44: Stopped mining
    log_writer.go:44: ---- stderr
    log_writer.go:44: <<<< end-dump
    log_writer.go:44: >>>> start-dump
    log_writer.go:44: ---- command     go-filecoin mining start
    log_writer.go:44: ---- exit-code   1
    log_writer.go:44: ---- error       nil
    log_writer.go:44: ---- stdout
    log_writer.go:44: ---- stderr
    log_writer.go:44: Error: failed to initialize sector builder: failed to get sector size for miner w/address t2nuaj2clngk5kxksxlqfvjnryonahgiabtbp74pq: query and deserialize failed: 'getSectorSize' query message failed: querymethod returned an error: failed to get To actor: actor not found
    log_writer.go:44: <<<< end-dump

```

</p>
</details>

**Comment by anorth** [comment]
See also #2822, #2194. We need a better integration testing approach.

**Comment by ZenGround0** [comment]
Documenting more failures
 [here](https://circleci.com/gh/filecoin-project/go-filecoin/24187#tests/containers/2).
[here](https://circleci.com/gh/filecoin-project/go-filecoin/24106#tests/containers/2)
[here](https://circleci.com/gh/filecoin-project/go-filecoin/24033#tests/containers/2)
[here](https://circleci.com/gh/filecoin-project/go-filecoin/23192#tests/containers/2)
[here](https://circleci.com/gh/filecoin-project/go-filecoin/23343)
[and here](https://circleci.com/gh/filecoin-project/go-filecoin/23192#tests/containers/2)

Most fail with
```
Error: couldn't send message: failed to add message to message pool: validation error adding message to pool: message pool contains message with same actor and nonce but different cid
```
One fails with something closer to the error seen above
```
Error: failed to get mining owner address for miner t2djzc4f4cicofmm5ssm7bm3an7wjmthun3ucezoy: querymethod returned an error: failed to get To actor: actor not found
```

**Comment by ZenGround0** [comment]
A related failure of `TestDealsShow` due to failure to add to the message pool can be found here: https://circleci.com/gh/filecoin-project/go-filecoin/24057

**Comment by anorth** [comment]
The "message pool contains message with same actor and nonce but different cid" is #3052 , thanks for linking those up. I didn't yet realise it was a source of test flakiness.
