### ISSUE TITLE
Splitting up big files

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/go-filecoin#2997]
### Description
**This is an opinion that others may not share.**

I think our convention of defining all of a type's methods in one file is not important and should be abandoned for the sake of clarity.  We should split up big ~1000 line files like actor/builtin/miner/miner.go into multiple files each dedicated to a specific subset of functionality.  We could have miner.go, commitSector.go and submitPoSt.go for example.  The later two files would include these two beast methods and all of their distinct helpers.

Thumbs up/down for agree/disagree.

**Comment by anorth** [comment]
In the specific case of actors, I think we should maintain a very clear boundary around the code that is in the actor call path. Keeping it all in one file is one way to make this boundary clear, though all files in a package could also do the trick.

At present, some code in the actors is not required for consensus, but present for worker convenience (#2973). If that were removed, the problem would be less severe. @acruikshank and I discussed potential ways of clearly separating that from the consensus-critical code, one of which could be a companion object in the same package.
