### ISSUE TITLE
Storage miners did not receive storage charges?

### ISSUE THREAD

**Issue by chenzhi201901** [filecoin-project/go-filecoin#3004]
The storage client has already sent the file to the storage miner, and the command of go-filecoin client query-storage-deal is displayed as "posted", but the storage miner has not received the storage fee in the whole life cycle of the file. Is it normal? What are some ways to track trading?

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Diagnostic information**

- Filecoin Inspect Output: 
- Current Head: 
- Connected Peers: 

**Version information**

- Go: 
- Rust: 
- Cargo: 
- Commit: 
- Go Env: 
- CC: 

**Additional context**

**Comment by ZenGround0** [comment]
The fee is claimable after the storage deal is completed but the miner needs to redeem the payment by posting a message to the blockchain.  The command `go-filecoin deals redeem <dealid>` is the best CLI endpoint for receiving all redeemable payments from a storage deal.

I'm leaving this issue open until we properly document this behavior in the wiki.  I think adding this command under [Accept a Deal and get paid](https://github.com/filecoin-project/go-filecoin/wiki/Mining-Filecoin#accept-a-deal-and-get-paid) is probably good enough.

**Comment by ZenGround0** [comment]
Added to [this section](https://github.com/filecoin-project/go-filecoin/wiki/Mining-Filecoin#accept-a-deal-and-get-paid) in the wiki.  It will be relevant after the next release, which is [coming soon](https://github.com/filecoin-project/go-filecoin/issues/3010).

@chenzhi201901 take a look and let me know if anything there is unclear.  If so I can reopen.
