### ISSUE TITLE
Fix SectorSet serialization

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/go-filecoin#3007]
### Description
[refmt can't handle maps with uint64 keys](https://github.com/polydawn/refmt/issues/35)
In order to have a map with sectorID keys in the miner actor we currently convert uint64s to strings first.  This is annoying because we open up the possibility of erroring when turning a map key back into a uint64.

### Acceptance criteria
Some options here
1. refmt implements this feature
2. we move to using a different type to represent sectorIDs.  Recent discussion on max sector id suggests we can fit them in uint16s.
3. This problem will likely go away on its own once we have use a tree based SectorSet data structure because we will no longer use go maps to represent the data structure in memory.

**Comment by anorth** [comment]
To be obsoleted by #2888
