### ISSUE TITLE
localnet build failed

### ISSUE THREAD

**Issue by R-Niagra** [filecoin-project/go-filecoin#3014]
After installing the go-filecoin dependency using:
FILECOIN_USE_PRECOMPILED_RUST_PROOFS=true go run ./build deps
And then successfully built and installed it using:
go run ./build build

go run ./build install

After this, I can run go-filecoin. However the moment I try to build localnet using:
go build -o localnet main.go 
package error pops up as shown below. Am I missing something?

../../../../metrics/export.go:7:2: cannot find package "contrib.go.opencensus.io/exporter/jaeger" in any of:
	/usr/local/go/src/contrib.go.opencensus.io/exporter/jaeger (from $GOROOT)
	/home/rz/goProj/src/contrib.go.opencensus.io/exporter/jaeger (from $GOPATH)
../../../../metrics/export.go:8:2: cannot find package "contrib.go.opencensus.io/exporter/prometheus" in any of:
	/usr/local/go/src/contrib.go.opencensus.io/exporter/prometheus (from $GOROOT)
	/home/rz/goProj/src/contrib.go.opencensus.io/exporter/prometheus (from $GOPATH)
../../../../types/intset.go:5:2: cannot find package "github.com/Workiva/go-datastructures/bitarray" in any of:
	/usr/local/go/src/github.com/Workiva/go-datastructures/bitarray (from $GOROOT)
	/home/rz/goProj/src/github.com/Workiva/go-datastructures/bitarray (from $GOPATH)
../../../../chain/store.go:8:2: cannot find package "github.com/cskr/pubsub" in any of:
	/usr/local/go/src/github.com/cskr/pubsub (from $GOROOT)
	/home/rz/goProj/src/github.com/cskr/pubsub (from $GOPATH)
../../../iptb-plugins/filecoin/docker/dockerfilecoin.go:21:2: cannot find package "github.com/docker/docker/api/types" in any of:
	/usr/local/go/src/github.com/docker/docker/api/types (from $GOROOT)
	/home/rz/goProj/src/github.com/docker/docker/api/types (from $GOPATH)
../../../iptb-plugins/filecoin/docker/dockerfilecoin.go:22:2: cannot find package "github.com/docker/docker/api/types/container" in any of:
	/usr/local/go/src/github.com/docker/docker/api/types/container (from $GOROOT)
	/home/rz/goProj/src/github.com/docker/docker/api/types/container (from $GOPATH)
../../../iptb-plugins/filecoin/docker/dockerfilecoin.go:23:2: cannot find package "github.com/docker/docker/api/types/network" in any of:
	/usr/local/go/src/github.com/docker/docker/api/types/network (from $GOROOT)
	/home/rz/goProj/src/github.com/docker/docker/api/types/network (from $GOPATH)
../../../iptb-plugins/filecoin/docker/dockerfilecoin.go:24:2: cannot find package "github.com/docker/docker/client" in any of:
	/usr/local/go/src/github.com/docker/docker/client (from $GOROOT)
	/home/rz/goProj/src/github.com/docker/docker/client (from $GOPATH)
../../../iptb-plugins/filecoin/docker/dockerfilecoin.go:25:2: cannot find package "github.com/docker/docker/pkg/stdcopy" in any of:
	/usr/local/go/src/github.com/docker/docker/pkg/stdcopy (from $GOROOT)
	/home/rz/goProj/src/github.com/docker/docker/pkg/stdcopy (from $GOPATH)
../../../../address/address.go:12:2: cannot find package "github.com/filecoin-project/go-leb128" in any of:
	/usr/local/go/src/github.com/filecoin-project/go-leb128 (from $GOROOT)
	/home/rz/goProj/src/github.com/filecoin-project/go-leb128 (from $GOPATH)
../../../../plumbing/api.go:8:2: cannot find package "github.com/ipfs/go-bitswap" in any of:
	/usr/local/go/src/github.com/ipfs/go-bitswap (from $GOROOT)
	/home/rz/goProj/src/github.com/ipfs/go-bitswap (from $GOPATH)
../../../../node/node.go:13:2: cannot find package "github.com/ipfs/go-bitswap/network" in any of:
	/usr/local/go/src/github.com/ipfs/go-bitswap/network (from $GOROOT)
	/home/rz/goProj/src/github.com/ipfs/go-bitswap/network (from $GOPATH)
../../../../actor/storage.go:7:2: cannot find package "github.com/ipfs/go-block-format" in any of:
	/usr/local/go/src/github.com/ipfs/go-block-format (from $GOROOT)
	/home/rz/goProj/src/github.com/ipfs/go-block-format (from $GOPATH)
../../../../proofs/sectorbuilder/rustsectorbuilder.go:12:2: cannot find package "github.com/ipfs/go-blockservice" in any of:
	/usr/local/go/src/github.com/ipfs/go-blockservice (from $GOROOT)
	/home/rz/goProj/src/github.com/ipfs/go-blockservice (from $GOPATH)
../../../../gengen/util/gengen.go:21:2: cannot find package "github.com/ipfs/go-car" in any of:
	/usr/local/go/src/github.com/ipfs/go-car (from $GOROOT)
	/home/rz/goProj/src/github.com/ipfs/go-car (from $GOPATH)
../../../../types/block.go:7:2: cannot find package "github.com/ipfs/go-cid" in any of:
	/usr/local/go/src/github.com/ipfs/go-cid (from $GOROOT)
	/home/rz/goProj/src/github.com/ipfs/go-cid (from $GOPATH)
../../../../repo/mem.go:6:2: cannot find package "github.com/ipfs/go-datastore" in any of:
	/usr/local/go/src/github.com/ipfs/go-datastore (from $GOROOT)
	/home/rz/goProj/src/github.com/ipfs/go-datastore (from $GOPATH)
../../../../wallet/dsbackend.go:9:2: cannot find package "github.com/ipfs/go-datastore/query" in any of:
	/usr/local/go/src/github.com/ipfs/go-datastore/query (from $GOROOT)
	/home/rz/goProj/src/github.com/ipfs/go-datastore/query (from $GOPATH)
../../../../repo/mem.go:7:2: cannot find package "github.com/ipfs/go-datastore/sync" in any of:
	/usr/local/go/src/github.com/ipfs/go-datastore/sync (from $GOROOT)
	/home/rz/goProj/src/github.com/ipfs/go-datastore/sync (from $GOPATH)
../../../../repo/fsrepo.go:14:2: cannot find package "github.com/ipfs/go-ds-badger" in any of:
	/usr/local/go/src/github.com/ipfs/go-ds-badger (from $GOROOT)
	/home/rz/goProj/src/github.com/ipfs/go-ds-badger (from $GOPATH)
../../../../repo/fsrepo.go:15:2: cannot find package "github.com/ipfs/go-fs-lock" in any of:
	/usr/local/go/src/github.com/ipfs/go-fs-lock (from $GOROOT)
	/home/rz/goProj/src/github.com/ipfs/go-fs-lock (from $GOPATH)
../../../../exec/exec.go:7:2: cannot find package "github.com/ipfs/go-hamt-ipld" in any of:
	/usr/local/go/src/github.com/ipfs/go-hamt-ipld (from $GOROOT)
	/home/rz/goProj/src/github.com/ipfs/go-hamt-ipld (from $GOPATH)
../../../../vm/storage.go:8:2: cannot find package "github.com/ipfs/go-ipfs-blockstore" in any of:
	/usr/local/go/src/github.com/ipfs/go-ipfs-blockstore (from $GOROOT)
	/home/rz/goProj/src/github.com/ipfs/go-ipfs-blockstore (from $GOPATH)
../../../../plumbing/dag/dag.go:9:2: cannot find package "github.com/ipfs/go-ipfs-chunker" in any of:
	/usr/local/go/src/github.com/ipfs/go-ipfs-chunker (from $GOROOT)
	/home/rz/goProj/src/github.com/ipfs/go-ipfs-chunker (from $GOPATH)
../../../../commands/actor.go:18:2: cannot find package "github.com/ipfs/go-ipfs-cmdkit" in any of:
	/usr/local/go/src/github.com/ipfs/go-ipfs-cmdkit (from $GOROOT)
	/home/rz/goProj/src/github.com/ipfs/go-ipfs-cmdkit (from $GOPATH)
../../../../commands/actor.go:19:2: cannot find package "github.com/ipfs/go-ipfs-cmds" in any of:
	/usr/local/go/src/github.com/ipfs/go-ipfs-cmds (from $GOROOT)
	/home/rz/goProj/src/github.com/ipfs/go-ipfs-cmds (from $GOPATH)
../../../../commands/main.go:13:2: cannot find package "github.com/ipfs/go-ipfs-cmds/cli" in any of:
	/usr/local/go/src/github.com/ipfs/go-ipfs-cmds/cli (from $GOROOT)
	/home/rz/goProj/src/github.com/ipfs/go-ipfs-cmds/cli (from $GOPATH)
../../../../commands/daemon.go:15:2: cannot find package "github.com/ipfs/go-ipfs-cmds/http" in any of:
	/usr/local/go/src/github.com/ipfs/go-ipfs-cmds/http (from $GOROOT)
	/home/rz/goProj/src/github.com/ipfs/go-ipfs-cmds/http (from $GOPATH)
../../../../plumbing/api.go:11:2: cannot find package "github.com/ipfs/go-ipfs-exchange-interface" in any of:
	/usr/local/go/src/github.com/ipfs/go-ipfs-exchange-interface (from $GOROOT)
	/home/rz/goProj/src/github.com/ipfs/go-ipfs-exchange-interface (from $GOPATH)
../../../../gengen/util/gengen.go:26:2: cannot find package "github.com/ipfs/go-ipfs-exchange-offline" in any of:
	/usr/local/go/src/github.com/ipfs/go-ipfs-exchange-offline (from $GOROOT)
	/home/rz/goProj/src/github.com/ipfs/go-ipfs-exchange-offline (from $GOPATH)
../../../../repo/fsrepo.go:16:2: cannot find package "github.com/ipfs/go-ipfs-keystore" in any of:
	/usr/local/go/src/github.com/ipfs/go-ipfs-keystore (from $GOROOT)
	/home/rz/goProj/src/github.com/ipfs/go-ipfs-keystore (from $GOPATH)
../../../../node/node.go:21:2: cannot find package "github.com/ipfs/go-ipfs-routing/offline" in any of:
	/usr/local/go/src/github.com/ipfs/go-ipfs-routing/offline (from $GOROOT)
	/home/rz/goProj/src/github.com/ipfs/go-ipfs-routing/offline (from $GOPATH)
../../../../address/address.go:13:2: cannot find package "github.com/ipfs/go-ipld-cbor" in any of:
	/usr/local/go/src/github.com/ipfs/go-ipld-cbor (from $GOROOT)
	/home/rz/goProj/src/github.com/ipfs/go-ipld-cbor (from $GOPATH)
../../../../types/block.go:9:2: cannot find package "github.com/ipfs/go-ipld-format" in any of:
	/usr/local/go/src/github.com/ipfs/go-ipld-format (from $GOROOT)
	/home/rz/goProj/src/github.com/ipfs/go-ipld-format (from $GOPATH)
../../../../types/signature.go:4:2: cannot find package "github.com/ipfs/go-log" in any of:
	/usr/local/go/src/github.com/ipfs/go-log (from $GOROOT)
	/home/rz/goProj/src/github.com/ipfs/go-log (from $GOPATH)
../../../../commands/daemon.go:16:2: cannot find package "github.com/ipfs/go-log/writer" in any of:
	/usr/local/go/src/github.com/ipfs/go-log/writer (from $GOROOT)
	/home/rz/goProj/src/github.com/ipfs/go-log/writer (from $GOPATH)
../../../../types/constants.go:6:2: cannot find package "github.com/ipfs/go-merkledag" in any of:
	/usr/local/go/src/github.com/ipfs/go-merkledag (from $GOROOT)
	/home/rz/goProj/src/github.com/ipfs/go-merkledag (from $GOPATH)
../../../../plumbing/dag/dag.go:12:2: cannot find package "github.com/ipfs/go-path" in any of:
	/usr/local/go/src/github.com/ipfs/go-path (from $GOROOT)
	/home/rz/goProj/src/github.com/ipfs/go-path (from $GOPATH)
../../../../plumbing/dag/dag.go:13:2: cannot find package "github.com/ipfs/go-path/resolver" in any of:
	/usr/local/go/src/github.com/ipfs/go-path/resolver (from $GOROOT)
	/home/rz/goProj/src/github.com/ipfs/go-path/resolver (from $GOPATH)
../../../../plumbing/dag/dag.go:14:2: cannot find package "github.com/ipfs/go-unixfs" in any of:
	/usr/local/go/src/github.com/ipfs/go-unixfs (from $GOROOT)
	/home/rz/goProj/src/github.com/ipfs/go-unixfs (from $GOPATH)
../../../../plumbing/dag/dag.go:15:2: cannot find package "github.com/ipfs/go-unixfs/importer" in any of:
	/usr/local/go/src/github.com/ipfs/go-unixfs/importer (from $GOROOT)
	/home/rz/goProj/src/github.com/ipfs/go-unixfs/importer (from $GOPATH)
../../../../plumbing/dag/dag.go:16:2: cannot find package "github.com/ipfs/go-unixfs/io" in any of:
	/usr/local/go/src/github.com/ipfs/go-unixfs/io (from $GOROOT)
	/home/rz/goProj/src/github.com/ipfs/go-unixfs/io (from $GOPATH)
../../process.go:11:2: cannot find package "github.com/ipfs/iptb/testbed" in any of:
	/usr/local/go/src/github.com/ipfs/iptb/testbed (from $GOROOT)
	/home/rz/goProj/src/github.com/ipfs/iptb/testbed (from $GOPATH)
../../fastutil/debug_utils.go:6:2: cannot find package "github.com/ipfs/iptb/testbed/interfaces" in any of:
	/usr/local/go/src/github.com/ipfs/iptb/testbed/interfaces (from $GOROOT)
	/home/rz/goProj/src/github.com/ipfs/iptb/testbed/interfaces (from $GOPATH)
../../../iptb-plugins/filecoin/docker/dockerfilecoin.go:28:2: cannot find package "github.com/ipfs/iptb/util" in any of:
	/usr/local/go/src/github.com/ipfs/iptb/util (from $GOROOT)
	/home/rz/goProj/src/github.com/ipfs/iptb/util (from $GOPATH)
../../../../crypto/crypto.go:10:2: cannot find package "github.com/ipsn/go-secp256k1" in any of:
	/usr/local/go/src/github.com/ipsn/go-secp256k1 (from $GOROOT)
	/home/rz/goProj/src/github.com/ipsn/go-secp256k1 (from $GOPATH)
../../../../node/libp2p.go:6:2: cannot find package "github.com/jbenet/goprocess" in any of:
	/usr/local/go/src/github.com/jbenet/goprocess (from $GOROOT)
	/home/rz/goProj/src/github.com/jbenet/goprocess (from $GOPATH)
../../../../node/config.go:4:2: cannot find package "github.com/libp2p/go-libp2p" in any of:
	/usr/local/go/src/github.com/libp2p/go-libp2p (from $GOROOT)
	/home/rz/goProj/src/github.com/libp2p/go-libp2p (from $GOPATH)
../../../../node/node.go:25:2: cannot find package "github.com/libp2p/go-libp2p-autonat-svc" in any of:
	/usr/local/go/src/github.com/libp2p/go-libp2p-autonat-svc (from $GOROOT)
	/home/rz/goProj/src/github.com/libp2p/go-libp2p-autonat-svc (from $GOPATH)
../../../../node/node.go:26:2: cannot find package "github.com/libp2p/go-libp2p-circuit" in any of:
	/usr/local/go/src/github.com/libp2p/go-libp2p-circuit (from $GOROOT)
	/home/rz/goProj/src/github.com/libp2p/go-libp2p-circuit (from $GOPATH)
../../../../node/config.go:5:2: cannot find package "github.com/libp2p/go-libp2p-crypto" in any of:
	/usr/local/go/src/github.com/libp2p/go-libp2p-crypto (from $GOROOT)
	/home/rz/goProj/src/github.com/libp2p/go-libp2p-crypto (from $GOPATH)
../../../../metrics/heartbeat.go:11:2: cannot find package "github.com/libp2p/go-libp2p-host" in any of:
	/usr/local/go/src/github.com/libp2p/go-libp2p-host (from $GOROOT)
	/home/rz/goProj/src/github.com/libp2p/go-libp2p-host (from $GOPATH)
../../../../testhelpers/net.go:11:2: cannot find package "github.com/libp2p/go-libp2p-interface-connmgr" in any of:
	/usr/local/go/src/github.com/libp2p/go-libp2p-interface-connmgr (from $GOROOT)
	/home/rz/goProj/src/github.com/libp2p/go-libp2p-interface-connmgr (from $GOPATH)
../../../../net/bootstrap.go:11:2: cannot find package "github.com/libp2p/go-libp2p-kad-dht" in any of:
	/usr/local/go/src/github.com/libp2p/go-libp2p-kad-dht (from $GOROOT)
	/home/rz/goProj/src/github.com/libp2p/go-libp2p-kad-dht (from $GOPATH)
../../../../node/node.go:29:2: cannot find package "github.com/libp2p/go-libp2p-kad-dht/opts" in any of:
	/usr/local/go/src/github.com/libp2p/go-libp2p-kad-dht/opts (from $GOROOT)
	/home/rz/goProj/src/github.com/libp2p/go-libp2p-kad-dht/opts (from $GOPATH)
../../../../metrics/heartbeat.go:12:2: cannot find package "github.com/libp2p/go-libp2p-net" in any of:
	/usr/local/go/src/github.com/libp2p/go-libp2p-net (from $GOROOT)
	/home/rz/goProj/src/github.com/libp2p/go-libp2p-net (from $GOPATH)
../../../../abi/abi.go:10:2: cannot find package "github.com/libp2p/go-libp2p-peer" in any of:
	/usr/local/go/src/github.com/libp2p/go-libp2p-peer (from $GOROOT)
	/home/rz/goProj/src/github.com/libp2p/go-libp2p-peer (from $GOPATH)
../../../../metrics/heartbeat.go:14:2: cannot find package "github.com/libp2p/go-libp2p-peerstore" in any of:
	/usr/local/go/src/github.com/libp2p/go-libp2p-peerstore (from $GOROOT)
	/home/rz/goProj/src/github.com/libp2p/go-libp2p-peerstore (from $GOPATH)
../../../../node/libp2p.go:11:2: cannot find package "github.com/libp2p/go-libp2p-peerstore/pstoremem" in any of:
	/usr/local/go/src/github.com/libp2p/go-libp2p-peerstore/pstoremem (from $GOROOT)
	/home/rz/goProj/src/github.com/libp2p/go-libp2p-peerstore/pstoremem (from $GOPATH)
../../../../testhelpers/net.go:15:2: cannot find package "github.com/libp2p/go-libp2p-protocol" in any of:
	/usr/local/go/src/github.com/libp2p/go-libp2p-protocol (from $GOROOT)
	/home/rz/goProj/src/github.com/libp2p/go-libp2p-protocol (from $GOPATH)
../../../../net/pubsub/publisher.go:3:8: cannot find package "github.com/libp2p/go-libp2p-pubsub" in any of:
	/usr/local/go/src/github.com/libp2p/go-libp2p-pubsub (from $GOROOT)
	/home/rz/goProj/src/github.com/libp2p/go-libp2p-pubsub (from $GOPATH)
../../../../net/bootstrap.go:15:2: cannot find package "github.com/libp2p/go-libp2p-routing" in any of:
	/usr/local/go/src/github.com/libp2p/go-libp2p-routing (from $GOROOT)
	/home/rz/goProj/src/github.com/libp2p/go-libp2p-routing (from $GOPATH)
../../../../commands/dht.go:14:2: cannot find package "github.com/libp2p/go-libp2p-routing/notifications" in any of:
	/usr/local/go/src/github.com/libp2p/go-libp2p-routing/notifications (from $GOROOT)
	/home/rz/goProj/src/github.com/libp2p/go-libp2p-routing/notifications (from $GOPATH)
../../../../net/network.go:13:2: cannot find package "github.com/libp2p/go-libp2p-swarm" in any of:
	/usr/local/go/src/github.com/libp2p/go-libp2p-swarm (from $GOROOT)
	/home/rz/goProj/src/github.com/libp2p/go-libp2p-swarm (from $GOPATH)
../../../../node/node.go:35:2: cannot find package "github.com/libp2p/go-libp2p/p2p/host/routed" in any of:
	/usr/local/go/src/github.com/libp2p/go-libp2p/p2p/host/routed (from $GOROOT)
	/home/rz/goProj/src/github.com/libp2p/go-libp2p/p2p/host/routed (from $GOPATH)
../../../../net/pinger.go:10:2: cannot find package "github.com/libp2p/go-libp2p/p2p/protocol/ping" in any of:
	/usr/local/go/src/github.com/libp2p/go-libp2p/p2p/protocol/ping (from $GOROOT)
	/home/rz/goProj/src/github.com/libp2p/go-libp2p/p2p/protocol/ping (from $GOPATH)
../../../../testhelpers/net.go:16:2: cannot find package "github.com/libp2p/go-stream-muxer" in any of:
	/usr/local/go/src/github.com/libp2p/go-stream-muxer (from $GOROOT)
	/home/rz/goProj/src/github.com/libp2p/go-stream-muxer (from $GOPATH)
../../../../paths/paths.go:7:2: cannot find package "github.com/mitchellh/go-homedir" in any of:
	/usr/local/go/src/github.com/mitchellh/go-homedir (from $GOROOT)
	/home/rz/goProj/src/github.com/mitchellh/go-homedir (from $GOPATH)
../../../../metrics/export.go:10:2: cannot find package "github.com/multiformats/go-multiaddr-net" in any of:
	/usr/local/go/src/github.com/multiformats/go-multiaddr-net (from $GOROOT)
	/home/rz/goProj/src/github.com/multiformats/go-multiaddr-net (from $GOPATH)
../../../../types/payment_voucher.go:5:2: cannot find package "github.com/multiformats/go-multibase" in any of:
	/usr/local/go/src/github.com/multiformats/go-multibase (from $GOROOT)
	/home/rz/goProj/src/github.com/multiformats/go-multibase (from $GOPATH)
../../../../testhelpers/net.go:19:2: cannot find package "github.com/multiformats/go-multistream" in any of:
	/usr/local/go/src/github.com/multiformats/go-multistream (from $GOROOT)
	/home/rz/goProj/src/github.com/multiformats/go-multistream (from $GOPATH)
../../../../actor/storage.go:11:2: cannot find package "github.com/polydawn/refmt/obj" in any of:
	/usr/local/go/src/github.com/polydawn/refmt/obj (from $GOROOT)
	/home/rz/goProj/src/github.com/polydawn/refmt/obj (from $GOPATH)
../../../../address/address.go:15:2: cannot find package "github.com/polydawn/refmt/obj/atlas" in any of:
	/usr/local/go/src/github.com/polydawn/refmt/obj/atlas (from $GOROOT)
	/home/rz/goProj/src/github.com/polydawn/refmt/obj/atlas (from $GOPATH)
../../../../actor/storage.go:12:2: cannot find package "github.com/polydawn/refmt/shared" in any of:
	/usr/local/go/src/github.com/polydawn/refmt/shared (from $GOROOT)
	/home/rz/goProj/src/github.com/polydawn/refmt/shared (from $GOPATH)
../../../../metrics/export.go:11:2: cannot find package "github.com/prometheus/client_golang/prometheus" in any of:
	/usr/local/go/src/github.com/prometheus/client_golang/prometheus (from $GOROOT)
	/home/rz/goProj/src/github.com/prometheus/client_golang/prometheus (from $GOPATH)
../../../../types/testing.go:9:2: cannot find package "github.com/stretchr/testify/assert" in any of:
	/usr/local/go/src/github.com/stretchr/testify/assert (from $GOROOT)
	/home/rz/goProj/src/github.com/stretchr/testify/assert (from $GOPATH)
../../../../state/testing.go:8:2: cannot find package "github.com/stretchr/testify/mock" in any of:
	/usr/local/go/src/github.com/stretchr/testify/mock (from $GOROOT)
	/home/rz/goProj/src/github.com/stretchr/testify/mock (from $GOPATH)
../../../../types/testing.go:10:2: cannot find package "github.com/stretchr/testify/require" in any of:
	/usr/local/go/src/github.com/stretchr/testify/require (from $GOROOT)
	/home/rz/goProj/src/github.com/stretchr/testify/require (from $GOPATH)
../../../../metrics/log_json_formatter.go:11:2: cannot find package "github.com/whyrusleeping/go-logging" in any of:
	/usr/local/go/src/github.com/whyrusleeping/go-logging (from $GOROOT)
	/home/rz/goProj/src/github.com/whyrusleeping/go-logging (from $GOPATH)
../../../../commands/inspector.go:11:2: cannot find package "github.com/whyrusleeping/go-sysinfo" in any of:
	/usr/local/go/src/github.com/whyrusleeping/go-sysinfo (from $GOROOT)
	/home/rz/goProj/src/github.com/whyrusleeping/go-sysinfo (from $GOPATH)
../../../../metrics/counter.go:6:2: cannot find package "go.opencensus.io/stats" in any of:
	/usr/local/go/src/go.opencensus.io/stats (from $GOROOT)
	/home/rz/goProj/src/go.opencensus.io/stats (from $GOPATH)
../../../../metrics/counter.go:7:2: cannot find package "go.opencensus.io/stats/view" in any of:
	/usr/local/go/src/go.opencensus.io/stats/view (from $GOROOT)
	/home/rz/goProj/src/go.opencensus.io/stats/view (from $GOPATH)
../../../../metrics/gauge.go:8:2: cannot find package "go.opencensus.io/tag" in any of:
	/usr/local/go/src/go.opencensus.io/tag (from $GOROOT)
	/home/rz/goProj/src/go.opencensus.io/tag (from $GOPATH)
../../../../metrics/export.go:13:2: cannot find package "go.opencensus.io/trace" in any of:
	/usr/local/go/src/go.opencensus.io/trace (from $GOROOT)
	/home/rz/goProj/src/go.opencensus.io/trace (from $GOPATH)
../../../iptb-plugins/filecoin/local/localfilecoin.go:24:2: cannot find package "golang.org/x/sync/errgroup" in any of:
	/usr/local/go/src/golang.org/x/sync/errgroup (from $GOROOT)
	/home/rz/goProj/src/golang.org/x/sync/errgroup (from $GOPATH)
/home/rz/goProj/src/golang.org/x/crypto/blake2s/blake2s_amd64.go:9:8: cannot find package "golang.org/x/sys/cpu" in any of:
	/usr/local/go/src/golang.org/x/sys/cpu (from $GOROOT)
	/home/rz/goProj/src/golang.org/x/sys/cpu (from $GOPATH)

**Comment by frrist** [comment]
I believe this means you do not have the `GO111MODULE` flag set. Try running this command to build localnet:
`env GO111MODULE=on go build -o localnet main.go`

**Comment by R-Niagra** [comment]
Thank-you, this solves the problem.
