### ISSUE TITLE
[bug] Failing to submit PoSt in proving period bricks miner

### ISSUE THREAD

**Issue by travisperson** [filecoin-project/go-filecoin#3018]
**Describe the bug**
In #3017 two miners failed while gathering requirements to start a PoSt. This put the miners in a state where `postInProcess` is set. This value is never unset, and the only way to move fast it being set is for the `provingPeriodEnd` to change, which only changes when a PoSt is submitted to the miner.

In this case, the only way to rescue the miner is to restart the node.

https://github.com/filecoin-project/go-filecoin/blob/81e75fd7f9722f9a100b8d03852e4e823a4b209d/protocol/storage/miner.go#L720-L723

https://github.com/filecoin-project/go-filecoin/blob/81e75fd7f9722f9a100b8d03852e4e823a4b209d/protocol/storage/miner.go#L733-L739

https://github.com/filecoin-project/go-filecoin/blob/81e75fd7f9722f9a100b8d03852e4e823a4b209d/actor/builtin/miner/miner.go#L842

**Comment by travisperson** [comment]
filecoin-4 hit this issue a while later `failed to calculate PoSt: failed to fetch PoSt challenge seed: error sampling chain for randomness: sample height out of range: 3142`

**Comment by anorth** [comment]
If restarted, the miner would have immediately hit the same error #3017 again, as the inputs to PoSt are deterministic given the chain.

If a miner can't generate a PoSt for some reason like this, I'm not sure there's much else we can do except fail permanently (the miner will eventually be penalised).

**Comment by anorth** [comment]
I don't think the code (nor spec) currently implements any recovery path from being too late to submit a PoSt.

**Comment by anorth** [comment]
This is an issue for specs-actors now.
