### ISSUE TITLE
[bug]Can not getting start.....

### ISSUE THREAD

**Issue by carsonfly** [filecoin-project/go-filecoin#3024]
I try to deploy filecoin in my ubuntu vps ,I meat a lot of problems.Please help me .
I deploy the filecoin by filecoin-test-devnet-0.3.0-Linux.tar.gz
when I execute "mkdir -p /tmp/filecoin-proof-parameters
./paramfetch -a"
"export PATH="$(pwd)":$PATH"
"rm -rf ~/.filecoin"
"go-filecoin init --devnet-user --genesisfile=https://genesis.user.kittyhawk.wtf/genesis.car"

Its ok
when I execute "go-filecoin daemon",it seems no sync chain,only connect.
**
My peer ID is QmPSo6h9nmdXuuKuQgBrDQf669bqmV3H3gTcZ26wmLqrCP
Swarm listening on: /ip4/127.0.0.1/tcp/6000
Swarm listening on: /ip4/23.92.78.109/tcp/6000
Swarm listening on: /ip4/10.255.67.20/tcp/6000
04:54:39.974  INFO chain.stor: start loading chain at tipset: { zDPWYqFD3SJXwpUGq5HUVUiKaSAtmdBBUmD9QnxchzGkyiBHYsUT }, height: 0 store.go:111
04:54:39.976  INFO chain.stor: finished loading 0 tipsets from { zDPWYqFD3SJXwpUGq5HUVUiKaSAtmdBBUmD9QnxchzGkyiBHYsUT } store.go:155
04:54:50.220 WARNI /fil/hello: failed to send hello handshake to peer QmZGDLdQLUTi7uYTNavKwCd7SBc5KMfxzWxAyvqRQvwuiV: stream reset hello.go:179
04:54:50.571 WARNI /fil/hello: failed to send hello handshake to peer QmUWmZnpZb6xFryNDeNU7KcJ1Af5oHy7fB9npU67sseEjR: protocol not supported hello.go:179

**
then I open anthor terminal execute "go-filecoin swarm peers ",no thing show
**
root@carsonflytw3:/home/user/filecoin# go-filecoin swarm peers
root@carsonflytw3:/home/user/filecoin#
**
I have to skip step "go-filecoin ping <peerID> "
then I execute
"go-filecoin config heartbeat.nickname "Carson""
"go-filecoin config heartbeat.nickname"
"go-filecoin config heartbeat.beatTarget "/dns4/stats-infra.kittyhawk.wtf/tcp/8080/ipfs/QmUWmZnpZb6xFryNDeNU7KcJ1Af5oHy7fB9npU67sseEjR""
Its ok
I restart go-filecoin daemon,and execute "watch -n 10 'go-filecoin show block $(go-filecoin chain head | head -n 1)'",the problem occur:
**
Every 10.0s: go-filecoin show block $(go-filecoin chain head | head -n 1)                                                Sat Jul  6 04:51:28 2019

Block Details
Miner:  empty
Weight: 0.000
Height: 0
Nonce:  0
Timestamp:  0
**
then I type 
"go-filecoin chain head"
it show:
**
zDPWYqFD3SJXwpUGq5HUVUiKaSAtmdBBUmD9QnxchzGkyiBHYsUT
**
no chain like that
when i type "go-filecoin inspect all", it show:
**
Version: 81e75fd

Runtime
OS: linux
Arch: amd64
Version: go1.12.1
Compiler: gc
NumProc: 4
GoMaxProcs: 4
NumGoRoutines: 98
NumCGoCalls: 4

Disk
Free: 8706824503296
Total: 8267494649856
FSType: 61267

Memory
Swap: 0
Virtual: 9520944000

Environment
FilAPI:
FilPath:
GoPath:

Config
{
"api": {
"address": "/ip4/127.0.0.1/tcp/3453",
"accessControlAllowOrigin": [
"http://localhost:8080",
"https://localhost:8080",
"http://127.0.0.1:8080",
"https://127.0.0.1:8080"
],
"accessControlAllowCredentials": false,
"accessControlAllowMethods": [
"GET",
"POST",
"PUT"
]
},
"bootstrap": {
"addresses": [
"/dns4/user.kittyhawk.wtf/tcp/9000/ipfs/Qmd6xrWYHsxivfakYRy6MszTpuAiEoFbgE1LWw4EvwBpp4",
"/dns4/user.kittyhawk.wtf/tcp/9001/ipfs/QmXq6XEYeEmUzBFuuKbVEGgxEpVD4xbSkG2Rhek6zkFMp4",
"/dns4/user.kittyhawk.wtf/tcp/9002/ipfs/QmXhxqTKzBKHA5FcMuiKZv8YaMPwpbKGXHRVZcFB2DX9XY",
"/dns4/user.kittyhawk.wtf/tcp/9003/ipfs/QmZGDLdQLUTi7uYTNavKwCd7SBc5KMfxzWxAyvqRQvwuiV",
"/dns4/user.kittyhawk.wtf/tcp/9004/ipfs/QmZRnwmCjyNHgeNDiyT8mXRtGhP6uSzgHtrozc42crmVbg"
],
"minPeerThreshold": 1,
"period": "10s"
},
"datastore": {
"type": "badgerds",
"path": "badger"
},
"heartbeat": {
"beatTarget": "/dns4/stats-infra.kittyhawk.wtf/tcp/8080/ipfs/QmUWmZnpZb6xFryNDeNU7KcJ1Af5oHy7fB9npU67sseEjR",
"beatPeriod": "3s",
"reconnectPeriod": "10s",
"nickname": "Carson"
},
"mining": {
"minerAddress": "empty",
"autoSealIntervalSeconds": 120,
"storagePrice": "0"
},
"mpool": {
"maxPoolSize": 10000,
"maxNonceGap": "100"
},
"net": "devnet-user",
"observability": {
"metrics": {
"prometheusEnabled": false,
"reportInterval": "5s",
"prometheusEndpoint": "/ip4/0.0.0.0/tcp/9400"
},
"tracing": {
"jaegerTracingEnabled": false,
"probabilitySampler": 1,
"jaegerEndpoint": "http://localhost:14268/api/traces"
}
},
"sectorbase": {
"rootdir": ""
},
"swarm": {
"address": "/ip4/0.0.0.0/tcp/6000"
},
"wallet": {
"defaultAddress": "t1zhfflggti7xaavdunzqe73dijhpukzd256tobvi"
}
}
**

**Comment by travisperson** [comment]
To connect to the user devnet you need to use the 0.2.4 release.

**Comment by carsonfly** [comment]
> To connect to the user devnet you need to use the 0.2.4 release.
