### ISSUE TITLE
Simplify access to chain history for sampling

### ISSUE THREAD

**Issue by anorth** [filecoin-project/go-filecoin#3025]
### Description
Chain sampling is used to generate a PoSt challenge seed, which is just the min ticket from a block a fixed number of rounds prior to the proving period.

The chain randomness sampling code traverses an ordered list of tipsets looking for one of a particular height. This list of tipsets is constructed with many complex parameters in `chain.GetAncestors`, called every block by `syncer.syncOne`, and passed through a deep call hierarchy. All the eventual caller wants is the ticket from a tipset at (or prior to) some height. Building this list every time only to sample a single tipset from it is wasteful and obscures the simplicity of what is actually needed.

Rather than compute and pass this big list around, some component (the tip index) should just index tipsets by height and provide a direct lookup (by binary search).

https://github.com/filecoin-project/go-filecoin/blob/0201cdfcc690c261b1b98d79b98474c54cec7ee8/chain/get_ancestors.go#L61

### Acceptance criteria
- Sampling the chain at a particular height is performed by an indexed lookup

### Risks + pitfalls
The tip index already has an index that includes height in the key (but also some CIDs). It may be reasonable to split this index up, or may require another one. The tip index is a major consumer of memory; consider holding pointers rather than tipset values (which are only slices anyway).

### Where to begin
Remove SampleChainRandomness and give callers a function to lookup a tipset with height less-or-equal to some sample height.

**Comment by ZenGround0** [comment]
Some complications to keep in mind when setting out to do this:

The ugly list exists to circumvent a dependency cycle: `chain ==> consensus ==> chain`.  Allowing vm code to directly access the tips index will require non-trivial design as it violates the existing dependency direction in a big way.

Once we reorganize our dependency tangle the tip index needs work to support the desired feature.  Looking up by height in the tip index will currently provide all valid tipsets seen by a daemon at the requested height, including tipsets on forks.  The tip index needs to offer a good interface for looking up blocks in a direct ancestral subtree for this refactor to land.

**Comment by ZenGround0** [comment]
Also please keep in mind another significant change already tracked that needs to land in the same area and will likely have a big impact on the design of this solution: https://github.com/filecoin-project/go-filecoin/issues/2223

**Comment by anorth** [comment]
Closed by #3810
