### ISSUE TITLE
UX: power table visualization

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/go-filecoin#3028]
### Description
Searching the output of `actor ls` and then running `miner power` is something but we should have an easier way for a node operator to easily look at the power table.

### Acceptance criteria
A CLI command that helps users visualize the power command

### Risks + pitfalls
Our CLI top level is getting messy.  This should not make the mess worse.

### Where to begin
Maybe a `go-filecoin storage-market` or `go-filecoin market` under `ACTOR COMMANDS` is the right place to put this?

**Comment by ZenGround0** [comment]
Here is a tool automating the `actor ls` approach that should hold us over for a long time: https://gist.github.com/ZenGround0/6e2cbd41dd2cfa1bcc6f5d264cf24ec1

**Comment by anorth** [comment]
I am sorry I have not been louder about this previously - I moved the issue to icebox and forgot about it.

In my opinion we should have a policy against implementing things like this in go-filecoin. Go-filecoin should provide basic access to the chain and related data, and leave slicing, dicing and aggregation to external tools. There is an unbounded set of possibly-useful arrangements of data that we could be called on to implement, and each carries a perpetual cost of maintenance and refactor-drag.

I had forgotten that @zen had already done something similar, and more-or-less replicated this with a single line outside of go-filecoin:
```
./go-filecoin actor ls | jq  'select(.actorType == "MinerActor") | .address' | xargs -n1 ./go-filecoin miner power
```
See also zen's gist linked above.

One line is a whole lot less code than it takes to build this inside go-filecoin, and is more flexible too. There possibly are a *very few* instances of something so useful that we opt in to paying the ongoing maintenance cost for it, but I'm not sure this is one.

There may be some arguments that the upcoming HTTP API would benefit from some higher level functionality than this, but assuming it's implementable in terms of other endpoints, as this would be, there'll still be no call for this logic to exist inside node implementations.
