### ISSUE TITLE
[bug]go-filecoin keep crashing with Corrupted snap/blob in staging folder

### ISSUE THREAD

**Issue by steven004** [filecoin-project/go-filecoin#3034]
**Describe the bug**
the go-filecoin daemon keeps crashing after load the chain data and deals info, when read staged sectors. It reports info like this: 
thread '<unnamed>' panicked at 'could not load snapshot: **_Corruption { at: Blob(36229536, 5245555104) }_**

This happened when I stress my node with lots of staged sectors waiting for sealing, and then the system crashed, after that, I tried to rerun the daemon, but always fail.

**To Reproduce**
I did not retry the steps (it really takes time) below, just believe it should work.  This is try to provide some clues for analysis. 

1. Start go-filecoin daemon, start mining
2. Create some staged sectors waiting for sealing, the more the better
3. Just kill -9 the go-filecoin process
4. Corrupt the last one or two files .filecoin_sectors/staging/blobs/ folder using any means
5. Restart go-filecoin daemon

**Expected behavior**
The corrupted data may impact staging sectors for sealing, but should not crash the whole process.

**log**
[snapReadError.log](https://github.com/filecoin-project/go-filecoin/files/3371869/snapReadError.log)

**Version information**
go-filecoin 0.2.4

**Additional context**
There is one way to let go-filecoin move on. That is delete all the data under .filecoin_sectors/staging, i.e. make it empty. 
With this deletion, go-filecoin will not crash, however, when we see try to add-piece, we see the error and we see almost all files in deals folder are open.
` http: Accept error: accept tcp4 127.0.0.1:3453: accept4: too many open files; retrying in 1s`

Not sure if this is relevant. 

**Suggestion**
1) We should move the meta-data information out from staging folder if meta-data is important and will be accessed often;
2) Are the staging sectors still needed to keep after sealed? if not, consider to delete;
3) Add some command for system check and clean up while go-filecoin is crashed, to take the best effort to keep miner's data and power, and make to mining keep moving on smoothly.

**Comment by anorth** [comment]
cc @laser @dignifiedquire

**Comment by laser** [comment]
This is an excellent bug report, thanks @steven004. I appreciate that you're using this thing and breaking it in ways we didn't think to break it.

**Comment by laser** [comment]
Moving this issue over to [rust-fil-sector-builder](https://github.com/filecoin-project/rust-fil-sector-builder/issues/13).
