### ISSUE TITLE
Support zero cost deals

### ISSUE THREAD

**Issue by acruikshank** [filecoin-project/go-filecoin#3037]
### Description

We have a need to support zero cost deals. Currently a deal based on an ask with zero price will still require the client to pay gas to create a payment channel with zero balance. It's possible to set the gas price low, but we'd still like to get the the cost down to zero.

To do this, we need to to skip the payment channel when the price is zero and also modify the storage miner to accept a deal proposal with no payment vouchers when the price is zero.

### Acceptance criteria

1. The storage client is modified to skip the payments step when the ask prices is zero.
2. The storage miner is modified to skip voucher validation when the price is zero.
3. The zero price case is tested.

**Comment by Lindensys** [comment]
Hi acruikshank , thanks very much for your update, i'm just confusing that the so called "cost down to zero" is about gas fee or the storage payment?

**Comment by acruikshank** [comment]
Hi @Lindensys. If the storage payment is zero, we would also like the gas fee to be zero. In this case, the gas fee is wasted on an empty payment channel.

**Comment by steven004** [comment]
If we consider gas fee for this case, should we consider gas fee to be zero for any message type. However, I doubt if we should do this. If I understand correctly, the gas fee is also for security of the chain, it is for miner's work. When gas fee could be down to zero, attacks is more likely happen with lower cost.

**Comment by acruikshank** [comment]
@steven004 You are correct. We have to charge some gas for every message that goes on chain for security reasons. We are currently validating this. The point of this story is to avoid sending the message in the first place.
