### ISSUE TITLE
Define an interface for fetching blocks from the network

### ISSUE THREAD

**Issue by frrist** [filecoin-project/go-filecoin#3048]
### Description
An interface that supports fetching contiguous sets of blocks (e.g. block `B` and 10 of `B`'s parents) must be added to the Fetcher in order for more robust forms of network syncing (blocksync or graphsync) to be added later. This new interface should work with the existing chain syncing code.

### Acceptance criteria
- Define and implement an interface on the Fetcher that supports fetching a block and `N` of its parents.

**Comment by anorth** [comment]
cc @hannahhoward for graphsync compatibility.

**Comment by frrist** [comment]
closed by #3047
