### ISSUE TITLE
[bug] panicked when submit post

### ISSUE THREAD

**Issue by ipfsmainofficial** [filecoin-project/go-filecoin#3055]
sometimes when i killed go-filecoin and  run go-filecoin daemon again ,it was panicked.
log:

thread '<unnamed>' panicked at 'Julfaults are not yet supported ', 11/home/ipfsmain/.cargo/git/checkouts/rust-fil-proofs-0521dfc2b7dd3149/07de4ef/filecoin-proofs/src/api.rs :14374::5717:
0note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
2.218 INFO generate_post: start, target: FFI, root: sector-builder-ffi, place: sector-builder-ffi/src/api.rs:269 sector_builder_ffi::api
thread '<unnamed>' panicked at '[run_blocking] could not recv: RecvError', src/libcore/result.rs:999:5
fatal runtime error: failed to initiate panic, error 5
Jul 11 14:57:02.218 ERRO expected Result to be Ok, backtrace: , error: RecvError, root: filecoin-proofs, place: /home/ipfsmain/.cargo/git/checkouts/rust-fil-proofs-0521dfc2b7dd3149/07de4ef/filecoin-proofs/src/error.rs:16 filecoin_proofs::error
SIGABRT: abort
PC=0x7f493396be97 m=41 sigcode=18446744073709551610

goroutine 0 [idle]:
runtime: unknown pc 0x7f493396be97
stack: frame={sp:0x7f464a7f9f90, fp:0x0} stack=[0x7f4649ffad48,0x7f464a7fa948)
00007f464a7f9e90:  00007f464a7fa1f8  00007f4933f472cc
00007f464a7f9ea0:  0000000000000000  0000000000000001
00007f464a7f9eb0:  0000000000000001  00007f4933f47270
00007f464a7f9ec0:  00007f4933f4a0e0  00000000016efed5
00007f464a7f9ed0:  0000000000000000  00007f4933f472cc
00007f464a7f9ee0:  0000000000000000  0000000000000001
00007f464a7f9ef0:  0000000000000001  00007f464a7fa128
00007f464a7f9f00:  0000000002e278b8  00007f464a7f9fa0
00007f464a7f9f10:  00007f464a7fa258  0000000000000001
00007f464a7f9f20:  0000000000000000  00000000016f0acb
00007f464a7f9f30:  0000000002e278b8  00007f464a7f9fa0
00007f464a7f9f40:  00007f464a7fa203  0000000000000001
00007f464a7f9f50:  0000000000000001  000000000173a311
00007f464a7f9f60:  0000000000000000  00000000016f0acb
00007f464a7f9f70:  0000000000000000  0000000000000000
00007f464a7f9f80:  00007f464a7fa103  35007f464a7fa200
00007f464a7f9f90: <0000000000000000  000000000172bfac
00007f464a7f9fa0:  0000000000000000  0000000000000000
00007f464a7f9fb0:  0000000000000000  00007f4933f472cc
00007f464a7f9fc0:  00007f464a7fa128  0000000000000001
00007f464a7f9fd0:  0000000000000001  00007f4933f47270
00007f464a7f9fe0:  00007f4933f4a0e0  00000000016efed5
00007f464a7f9ff0:  0000002000000000  00007f464a7fa803
00007f464a7fa000:  0000000000000000  0000000000000001
00007f464a7fa010:  fffffffe7fffffff  ffffffffffffffff
00007f464a7fa020:  ffffffffffffffff  ffffffffffffffff
00007f464a7fa020:  ffffffffffffffff  ffffffffffffffff
00007f464a7fa030:  ffffffffffffffff  ffffffffffffffff
00007f464a7fa040:  ffffffffffffffff  ffffffffffffffff
00007f464a7fa050:  ffffffffffffffff  ffffffffffffffff
00007f464a7fa060:  ffffffffffffffff  ffffffffffffffff
00007f464a7fa070:  ffffffffffffffff  ffffffffffffffff
00007f464a7fa080:  ffffffffffffffff  ffffffffffffffff
runtime: unknown pc 0x7f493396be97
stack: frame={sp:0x7f464a7f9f90, fp:0x0} stack=[0x7f4649ffad48,0x7f464a7fa948)
00007f464a7f9e90:  00007f464a7fa1f8  00007f4933f472cc
00007f464a7f9ea0:  0000000000000000  0000000000000001

**Comment by ZenGround0** [comment]
cc @laser who can tell you if this should be filed in rust-fil-proofs

**Comment by laser** [comment]
Hello!

Yes, please do file this issue in the [rust-fil-proofs](https://github.com/filecoin-project/rust-fil-proofs) repository. Thanks for your report, @ipfsmainofficial.

E

**Comment by anorth** [comment]
cc @ingar fyi
