### ISSUE TITLE
[bug]go-filecoin deals list --miner

### ISSUE THREAD

**Issue by carsonfly** [filecoin-project/go-filecoin#3058]
When I type "go-filecoin client list-asks --enc=json | jq ",It return a lots of miners,but then I type "go-filecoin deals list --miner",it return nothing.
I try it again 5 minute after,but it still return nothing.
How can I make a deal with others?

**Comment by sywyn219** [comment]
go-filecoin client propose-storage-deal

**Comment by travisperson** [comment]
You can find information on how to propose a storage deal on our wiki

https://github.com/filecoin-project/go-filecoin/wiki/Storing-on-Filecoin#propose-a-storage-deal

The command `go-filecoin deals list --miner` will list deals that have been made with your miner. This requires that you have a miner setup though, and someone has willingly made a deal with your miner.

You can find more information about how to setup a miner in our wiki as well

https://github.com/filecoin-project/go-filecoin/wiki/Mining-Filecoin#start-mining
