### ISSUE TITLE
Modify `deps` command in go-filecoin to allow developers to specify which sector sizes they'll download Groth parameters for

### ISSUE THREAD

**Issue by laser** [filecoin-project/go-filecoin#3072]
### Description

The `paramfetch` program [now accepts a list of sector sizes for which it will download Groth parameters](https://github.com/filecoin-project/rust-fil-proofs/blob/master/filecoin-proofs/src/bin/paramfetch.rs#L84). go-filecoin developers need to be able to specify these sizes when invoking `deps`, because `deps` in turn calls the `paramfetch` program.

This blocks the release of 1GiB sectors to go-filecoin.

**Comment by anorth** [comment]
Awesome. An acceptable state to me would be that `deps` only downloads verifying params and the 1KiB proof param, and no more. Miners must explicitly invoke paramfetch to fetch more. This is predicated on the go-filecoin daemon clearly alerting the user to a missing parameter as soon as they `mining start` (not waiting until a seal or PoSt is scheduled).

@mishmosh @travisperson?

**Comment by travisperson** [comment]
I agree with @anorth. The `deps` command is primarily a developer focused command. It should download at minimum all parameters required to run our tests. I think adding in the verifying params is a good idea as it allows a developer to also be able to join any network and run consensus.

**Comment by laser** [comment]
@anorth 

> An acceptable state to me would be that deps only downloads verifying params and the 1KiB proof param, and no more.

This is easy to do.

> Miners must explicitly invoke paramfetch to fetch more. 

Also easy to do.

> This is predicated on the go-filecoin daemon clearly alerting the user to a missing parameter as soon as they mining start (not waiting until a seal or PoSt is scheduled).

We'd need to write some software to do this. We could either:

1. Modify the `paramfetch` binary to accept a `--check` flag in addition to `--params-for-sector-sizes=$YOUR_SECTOR_SIZE_HERE`. The program would produce a non-success exit code if the Groth parameter cache did not include PoRep and PoSt Groth parameters for the specified sector size(s), and success if it did. Downside to this approach is that go-filecoin would need to `os.Exec` this other binary, and the binary would need to be on the operator's `$PATH` or in the current working directory (or some other known path). I'm not sure we can make that assumption for operators.
1. Create a new FFI-exposed function which, for a given sector size, PoRep proof partitions, and PoSt proof partitions, produces a boolean value indicating that the cache is populated with matching Groth parameters. go-filecoin could call this function and short-circuit the `mining start` flow if the function produced `false`.

The first option is cheaper (from a time perspective); it doesn't require much in the way of _design_. It would require that we tell miners that they need to keep `paramfetch` on their `$PATH` or put it in a place where `go-filecoin` can find it.

> I think adding in the verifying params is a good idea as it allows a developer to also be able to join any network and run consensus.

The existing behavior of the `paramfetch` program is that it always downloads all verifying keys listed in the `parameters.json` manifest - regardless of which sector sizes the operator passed (or didn't pass) to `paramfetch`. They're tiny - currently around 1.1KiB - so this doesn't take much time.

**Comment by anorth** [comment]
Of those two options, I certainly prefer the second. But maybe we can find something cheaper.

Can the sector builder check this at initialisation? There must be some existing first call that passes the sector size in that happens before PoRep, since that replication is not scheduled explicitly from the outside. Will that be sufficiently early for my needs?

Is there a reasonable way we could write go code instead of FFI? That's probably only a short term pattern, but maybe pragmatic atm.

**Comment by laser** [comment]
@anorth 

> Can the sector builder check this at initialisation?

Yes. That's a much better idea than what I proposed. We'll have to write a little Rust code to make the cache check, but not much. The initializer is the natural place for this.

**Comment by laser** [comment]
Splitting this issue into:

- _modify the `deps` command such that it downloads only Groth parameters and keys for 1KiB sectors #3152_
- _sector builder should fail to initialize if parameter cache is missing required Groth parameters and/or verifying keys #22_
