### ISSUE TITLE
[bug] Storage power stuck at 1 sector

### ISSUE THREAD

**Issue by yangjian102621** [filecoin-project/go-filecoin#3077]
Well, i had sealed 13 GB data on the miner node, but it always displayed 268.4 MB on the  https://stats.kittyhawk.wtf

```bash
miner@xjxh:~$ du -sh .filecoin*
0	.filecoin
6.5G	.filecoin-20190716-010345-v002
13G	.filecoin_sectors
```
And the miner power is no changed after i had finished the first sector, it is always `268435456 / 2229088026624`.

![image](https://user-images.githubusercontent.com/4746061/61346369-076cc480-a88b-11e9-9c60-db6a6cbe851b.png)

My miner node information 
* ID :  QmVoqEgQhLLSWMzLjaeofD4bAcpPNuakVaSw72YsK8Y7YZ
* minerAddress t2zmkmdccog3da2n5rnmkyrzvvuoklbcpymcapxay

I had post more than 60 deals to my miner with two client nodes, and my `.filecoin_sectors` dir is increasing 256 MB every 20 mins, but the data of https://stats.kittyhawk.wtf is never changed.

![image](https://user-images.githubusercontent.com/4746061/61346522-b01b2400-a88b-11e9-965b-861f343ef7af.png)

If someone could tell me what's problem?

**Comment by anorth** [comment]
268.4MB sounds suspiciously like exactly one sector. Despite sealing more sectors, I think that your PoSt is not being accepted. The PoSt is necessary to gain power.

This is very likely due to https://github.com/filecoin-project/rust-fil-proofs/issues/738. Let's use this as a tracking issue in go-filecoin for this problem.

**Comment by anorth** [comment]
There are reports from another miner about the same problem [in slack](https://filecoinproject.slack.com/archives/CEGN061C5/p1563027994194500).

**Comment by travisperson** [comment]
This actually has to do with the way the proving set is updated. We only update the proving set during a `submitPoSt`.

There is a special case for the first `commitSector` where we immediately add that sector to the proving set and start the proving period. This ensures miners get power quicker. This is the first `submitPoSt` that shows up on chain for any miner.

Due to how fast PoSt proof generation is at the moment you are unlikely to actually get another sector committed before the `submitPoSt`. This results in the next proving period to also only contain this first sector. This is why power does not change after the second `submitPost`. However, your proving set is probably much larger now, and on the third `submitPoSt` you should see your power increase.

Some details:

Your first `commitSector` was in block [13080](https://explorer.user.kittyhawk.wtf/blocks/zDPWYqFD8ZWiFLBhSTNXuK1nbDA8MyRF267tWQDhm1nzNpyVmpag), your first `submitPoSt` was in block [13093](https://explorer.user.kittyhawk.wtf/blocks/zDPWYqFD5tojAeydhYFuRGzttSAHPcQP2Gj35G5mn6t2WRT8W9Mi), and your second `submitPoSt` was in [14150](https://explorer.user.kittyhawk.wtf/blocks/zDPWYqFCzpVYfcrr8JtbtUwRZW1cbRKvY1St3kNZ1N2LaTqrCNZS)

The proving period for your miner at the moment is 15080 to 16080. So we should see your power increase pretty significantly in a little while. The PoSt generation will take a little longer though, as we currently only do a PoSt over 2 sectors at a time.

**Comment by steven004** [comment]
> Your first `commitSector` was in block [13080](https://explorer.user.kittyhawk.wtf/blocks/zDPWYqFD8ZWiFLBhSTNXuK1nbDA8MyRF267tWQDhm1nzNpyVmpag), your first `submitPoSt` was in block [13093](https://explorer.user.kittyhawk.wtf/blocks/zDPWYqFD5tojAeydhYFuRGzttSAHPcQP2Gj35G5mn6t2WRT8W9Mi), and your second `submitPoSt` was in [14150](https://explorer.user.kittyhawk.wtf/blocks/zDPWYqFCzpVYfcrr8JtbtUwRZW1cbRKvY1St3kNZ1N2LaTqrCNZS)

@travisperson , I am a little confused by this. I just checked the submitPost message ths particular miner sent in block 13093 and 14150 respectively, however, I saw the parameter length of the two messges are quite different: the first one is 268Bytes, while the second one is 2080. My understanding is that the length of params basically reflect the size of proving-set, so I would expect more proven storage will show up after the 2nd submitPost message successfully accepted by the chain. Is that correct?

**Comment by travisperson** [comment]
> My understanding is that the length of params basically reflect the size of proving-set

That is correct. This is a bug at the moment which is being fixed in #3067. Currently when we start PoSt generation we take all committed sectors and submit all the proofs. However, the the protocol is only going to award power for the proving set sectors.

**Comment by yangjian102621** [comment]
@steven004 

How to query the `submitPost` of specified miner?
Thanks.

**Comment by steven004** [comment]
@yangjian102621  just go to [filecoin explorer](http://user.kittyhawk.wtf:8000/).

**Comment by a8159236** [comment]
@yangjian102621 Hello, has your problem been solved? I had the same problem.I've already sent many data to the miners and shown "complete", but the size of "go-filecoin miner power" has not increased, and the "Storage Power" on the dashboard has not increased, for several days. What's the reason?Can you give me some guidance?

**Comment by yangjian102621** [comment]
@a8159236  
Yep, i found my second `submitPoSt` at block [14148](https://explorer.user.kittyhawk.wtf/blocks/zDPWYqFCzpVYfcrr8JtbtUwRZW1cbRKvY1St3kNZ1N2LaTqrCNZS)

![image](https://user-images.githubusercontent.com/4746061/61507543-a4109d00-aa18-11e9-9f2e-3cec670e66e6.png)

This `submitPoSt` parameter length is 2080 Bytes, much more longer than the first one(268 Bytes), 
my miner's storage power increase pretty significantly(increased to 16374562816 / 3143916060672).

`Proven Storage` is also increase to `16.4 GB` at https://stats.kittyhawk.wtf/storage/mining

So you just to wait you miner node's second `submitPoSt`, then you `"Storage Power"` will increase a lot.

**Comment by a8159236** [comment]
@yangjian102621 How to query the submitPost of specified miner on filecoin explorer?Do you use the browser's own search function ，Or is it a one-by-one information query?

**Comment by yangjian102621** [comment]
@a8159236 
> How to query the submitPost of specified miner on filecoin explorer?Do you use the browser's own search function ，Or is it a one-by-one information query?

Sorry, i also have no idea, This question you ask @travisperson  may be more appropriate.

**Comment by a8159236** [comment]
@yangjian102621 
Well, thank you very much.

**Comment by yangjian102621** [comment]
@a8159236 
Hi, If you have no obstacles to reading Chinese, here is a blog explaining how to check the `submitPost`.

**Comment by a8159236** [comment]
@yangjian102621 Thank you very much. Can you provide this blog?

**Comment by yangjian102621** [comment]
@a8159236 
Sorry, i forgot it. The blog url is http://www.r9it.com/20190720/filecoin-miner-test.html

**Comment by a8159236** [comment]
@yangjian102621 Thank you very much. But do you know what these two words mean respectively?createChannel and commitSector .

**Comment by a8159236** [comment]
The longer the length of the submitted parameters, the greater the additional storage power.But what factors determine the length of the parameters?

**Comment by a8159236** [comment]
@yangjian102621 The longer the length of the submitted parameters, the greater the additional storage power.But what factors determine the length of the parameters?
Are you Chinese? Is it convenient to leave the contact information of Wechat? I am also a fan of filecoin and hope to communicate more.

**Comment by a8159236** [comment]
Why did my parameter length reach 10KB?

**Comment by yangjian102621** [comment]
@a8159236 
Sorry, this issue is closed.
If you have other questions to discuss, just send an email to my box : yangjian102621@gmail.com

**Comment by yangjian102621** [comment]
@travisperson 
Hi, is it possible to use the same minerAddress for two different nodes?

**Comment by anorth** [comment]
No, that is not going to work if the nodes are storing different data.

**Comment by taylorshuang** [comment]
> No, that is not going to work if the nodes are storing different data.

@anorth what do you mean? I don't get it.

**Comment by taylorshuang** [comment]
This issue is very useful, thanks.

**Comment by yangjian102621** [comment]
@anorth 
Thanks , i got it.
Another reason is that it is not possible to determine which node to post the data to sealing.

**Comment by yangjian102621** [comment]
@travisperson 

Hi, I found there is an an API client for Filecoin implemented in javascript.
[js-filecoin-api-client](https://github.com/filecoin-project/js-filecoin-api-client)

Do you have plans to develop a filecoin api client for java implementation and PHP implementation?

If you do had a plan , i want to make a tittle contribute for it , i launched a project, [an API client for Filecoin implemented in Java](https://github.com/yangjian102621/java-filecoin-api-client),(The project has just started, there are not many functions, but I intend to constantly improve it.) 

we had a plan to develop a version implemented In PHP if you needed.

I want to add my project to `filecoin-project`, so that more people can use and participate in the contribution. 
What can I do to achieve this?

Thanks.

**Comment by anorth** [comment]
@yangjian102621 this isn't the right place for such a discussion - I suggest the #fil-dev channel in the project slack, or the discussion forum.

**Comment by yangjian102621** [comment]
@anorth 
I'm sorry,  in fact i had created a top in discussion forum. But i did not got a reply, 
and i had got a reply just now, we will discuss it on the forum.
Thanks for reply.
