### ISSUE TITLE
Better IPLD store abstractions

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/go-filecoin#3078]
### Description
Filing based off of suggestions [here](https://github.com/filecoin-project/go-filecoin/pull/3061#discussion_r304200759) and [here](https://github.com/filecoin-project/go-filecoin/pull/3061#discussion_r304201625).  

Problem 1: the hamt package begins the definition of the `CborIpldStore` with the comment "// THIS IS ALL TEMPORARY CODE".  We should not feel stuck using this incomplete general purpose abstraction in go-filecoin.  Specifically this store does not do the basic caching that go-filecoin type specific cbor (de)serializers do.  This is the biggest immediate drawback to using the store.  In general the lack of flexibility does not seem worth it for such a simple abstraction.  We should feel comfortable rolling our own.

Problem 2: We currently accept a concrete `CborIpldStore` type throughout go-filecoin's functions instead of using interfaces.  We should not be stuck with a single concrete instance and all of its methods entering every code path that needs a subset of those methods.  For example, the `chain.Store` needs to read from the cbor store but does not need to write to it and `state.Tree.Flush` needs to write to the cbor store but not read from it.

The root cause of both issues is that we use the `go-hamt-ipld` hamt and that package requires a concrete type, not an interface, for all of the hamt methods.

### Acceptance criteria
Step 1: the hamt package should be updated to accept an interface to ipld cbor storage instead of a concrete type.  This way go-filecoin can instantiate it's own concrete types for cbor storage that give us more flexibility (i.e. do our own caching).

Step 2: ideally different hamt functions should accept the minimal interface they need.  For example `hamt.LoadNode` should really only accept an interface with the `Get` method.  

### Risks + pitfalls
This seems like only good for the hamt package but it is shared code with the ipfs ecosystem so moving quick on the canonical implementation isn't likely.  Alternatively we could fork it, but that's probably not a good idea in the long run.

### Where to begin
This is largely @whyrusleeping's code, check in if he agrees that this change should make it to master in hamt repo.  See if someone in the ipfs ecosystem wants to take this up.

**Comment by whyrusleeping** [comment]
Sounds good to me. It's about time that code bothered someone enough to fix it

**Comment by whyrusleeping** [comment]
I think the interface should likely live in go-ipld-cbor, and a default implementation can live there. This way we don't have to import the hamt package everywhere for no real reason.

**Comment by anorth** [comment]
@frrist fixed this for us, and also aligned the AMT package to match!
