### ISSUE TITLE
expose commD and commRStar to storage client node operator through API

### ISSUE THREAD

**Issue by mishmosh** [filecoin-project/go-filecoin#3085]
### Description
This is a counterpart to #3074 which describes how miners inspect the state of their own stored data sectors. Storage clients will also want to inspect the state of the data they have stored with miners.

We can expect the client to be responsible for tracking `DealID` which is returned by successful `propose-storage-deal` and `minerID` with whom they proposed the deal. Once data is successfully stored (i.e. transferred, staged, and sealed), clients will want to get status of that data, especially details such as:
```
{ "sectorId": 1000, "commD": "AAA-some-encoding-of-comm-d", "commR": "AAA-some-encoding-of-comm-r", "commRStar": "AAA-some-encoding-of-comm-r-star", "proof": "AAA-some-encoding-of-proof", "pieces": [ { "commP": "YYY-some-encoding-of-comm-p", "pieceInclusionProof": "ZZZ-some-encoding-of-PIP" } ] }
{ "sectorId": 1001, "commD": "BBB-some-encoding-of-comm-d", "commR": "BBB-some-encoding-of-comm-r", "commRStar": "BBB-some-encoding-of-comm-r-star", "proof": "BBB-some-encoding-of-proof", "pieces": [ { "commP": "RRR-some-encoding-of-comm-p", "pieceInclusionProof": "SSS-some-encoding-of-PIP" } ] }
```

Some of this may already be available through `query-storage-deal`, which returns `ProofInfo` containing `commitmentMessage`.

### Acceptance criteria
- Given a `dealID` and `minerID`, a storage client (and any public node operator) can run a `query-storage-deal` to obtain the details above.
- If the data is not yet staged or sealed, return a useful status indicating that it is pending
- The bytes of commR, commRStar, commD, etc. are encoded in hex
- Once this is complete, create (or ping @mishmosh to create) an issue for each new command in https://github.com/filecoin-project/js-filecoin-api-client

### Where to begin
- https://github.com/filecoin-project/specs/blob/master/network-protocols.md#storage-deal-make 
- https://github.com/filecoin-project/go-filecoin/blob/a1771a863590be1432979fea9dc98d5bc99e4d0e/protocol/storage/miner.go#L540

cc @laser @sidke (plus @eingenito for long-term fyi)

**Comment by mishmosh** [comment]
via @laser in chat:

It has come to my attention that storage clients wish to obtain the CommD and CommR associated with the sector into which the piece referenced in their storage deal has been sealed. The client can already use the `query-deal` command to obtain the CID of the `commitSector` message corresponding to that sector - but `message wait` doesn't show individual `commitSector` arguments - it just shows some string encoding of the concatenated arguments' bytes.

I propose to augment the `ProofInfo` struct with `CommR` and `CommD` such that the storage client can query for their deal and, when available, see the replica and data commitments in the `query-storage-deal` command. Alternatively, the `query-storage-deal` code could get deal state from the miner and use the `CommitmentMessage` CID to look up CommR and CommD (on chain) - but this seems like more work than is really necessary. Any objections?

_Note: changing `ProofInfo` involves a spec change in https://github.com/filecoin-project/specs/blob/master/network-protocols.md#storage-deal-make _

**Comment by frrist** [comment]
To whomever picks this up, check out the porcelain added in https://github.com/filecoin-project/go-filecoin/pull/3169 that exposed miners proving periods and proving sets.

**Comment by ingar** [comment]
About this requirement:
>Given a dealID and minerID, a storage client (and any public node operator) can run a query-storage-deal to obtain the details above.

Currently, deals are stored off-chain in the storage miner and storage client's local stores, and the `query-storage-deal` assumes that it's the client itself that is issuing the command.  This means that the client has the deal -> miner association in the local store.  In order for this to work with an arbitrary deal/miner, this information would have to be communicated out-of-band somehow.

Is that mechanism assumed with this requirement?

**Comment by acruikshank** [comment]
@ingar you are correct that deal details are stored on disk by the client, the miner and no one else. We have no plans to expose this data through any sort of network protocol. The ability to query the deals for other clients or miners doesn't seem desirable or particularly useful to me.

I think the line in question should be:

> Given a dealID, a storage client or miner can run a query-storage-deal to obtain the details above on any of their deals.

@mishmosh do you disagree?
