### ISSUE TITLE
remove byte slice PIP literals from payment voucher redemption tests (use new FakeVerifier and FakeVMContext)

### ISSUE THREAD

**Issue by laser** [filecoin-project/go-filecoin#3086]
### Description

Our [recent PIP work](https://github.com/filecoin-project/go-filecoin/pull/3066/files#diff-802a189c834e8e991a719708407f60edR45) added some PIP, CommD, and CommP byte slice-literals to the payment voucher redemption tests. If rust-fil-proofs changes its hashing algorithm, this code will be invalid and PIPs will fail to verify.

We should rewrite `miner_redeem_test.go` to use the new `FakeVerifier` and `FakeVMContext`, much the same as the `miner_test.go` file does. This will prevent the FFI call and will allow us to remove the byte slice-literals.

### Acceptance criteria

- no more byte slice literals in `miner_redeem_test.go`
- no more FFI calls in `miner_redeem_test.go`

### Where to begin

- use `FakeVerifier` and `FakeVMContext`

**Comment by anorth** [comment]
Will you do this as a follow-up @sidke ?

**Comment by anorth** [comment]
The new spec makes this flow redundant, so improving the tests isn't worthwhile.
