### ISSUE TITLE
 file format not recognized

### ISSUE THREAD

**Issue by biyuegege** [filecoin-project/go-filecoin#3088]
file format not recognized 
hi :
        When i build go-filecoin in my arm-linux, it return file fomrat not recognized. I think the reson is  file libsector_builder_ffi.a is compile in amd64!   So what can i do ? Must i compile this file in armv8?

# go run ./build build
Building go-filecoin...
git log -n 1 --format=%H
go build -ldflags -X github.com/filecoin-project/go-filecoin/flags.Commit=1dee904cac85386e19fb4d036f1ec5f9fbec16db -v -o go-filecoin .
github.com/filecoin-project/go-filecoin/bls-signatures
github.com/filecoin-project/go-filecoin/proofs/libsectorbuilder
# github.com/filecoin-project/go-filecoin/bls-signatures
/usr/bin/ld: bls-signatures/lib/libbls_signatures.a: error adding symbols: file format not recognized
collect2: error: ld returned 1 exit status
# github.com/filecoin-project/go-filecoin/proofs/libsectorbuilder
/usr/bin/ld: proofs/libsectorbuilder/../lib/libsector_builder_ffi.a: error adding symbols: file format not recognized
collect2: error: ld returned 1 exit status
Command 'go build -ldflags -X github.com/filecoin-project/go-filecoin/flags.Commit=1dee904cac85386e19fb4d036f1ec5f9fbec16db -v -o go-filecoin .' failed: exit status 2
exit status 1

**Comment by travisperson** [comment]
Yes, you would need to compile the rust proofs yourself. Currently there is no official support for armv8 but you are more than welcome to give it a try!

**Comment by anorth** [comment]
Support for other architectures is tracked in #2258.
