### ISSUE TITLE
[bug]

### ISSUE THREAD

**Issue by embedSky** [filecoin-project/go-filecoin#3089]
**Describe the bug**

Some time for some reason submitPoSt message verified invalid. then my miner will never do PoSt . and then my power will never increase, even if I have still storage new deals.

**To Reproduce**

some time send submitPost message
**Expected behavior**

I think it`s necessary have some logic to judge wether the PoSt is success and let miner hava chace to do PoSt and Send submitPoSt again
**Screenshots**

**Diagnostic information**

**Version information**

I am runing go-filecoin in dev-user net,
version:0edc3e9c95f198cc5a20c3f94badb6d86160d7cc
release:0.3.2

**Additional context**

**Comment by waynewyang** [comment]
I think this PR:#3065 is alreay solved it.
