### ISSUE TITLE
I have tested two storage miners,When I store data to the storage miner, the miner node will drop, and then a miner process will stop, a miner process will not stop, but the block is not synchronized to the latest block, so the data cannot be stored

### ISSUE THREAD

**Issue by muronglaowang** [filecoin-project/go-filecoin#3092]
It appears when I run the storage command

State:   accepted
Message: 
DealID:  zDPWYqFCyr5GjJMsFngFWzyUhbfpEEkNnMJjk4fTWvqgUPLYJSht

It appears when I run the command go-filecoin client query-storage-deal <dealID>

Error: error querying deal: could not establish connection with peer. Peer does not support protocol

**Comment by taoshengshi** [comment]
Could you please share the detail steps of test scenario?

**Comment by shannonwells** [comment]
Hello, thank you for reporting this.  As well as the detailed test scenario steps that @taoshengshi mentioned, please also include a gist of your log output showing the problem.

**Comment by frrist** [comment]
Chiming in because I have a gut feeling on this:
> Peer does not support protocol

This error message _usually_ means the miner isn't mining i.e. the command `go-filecoin mining start` was never issued and the [protocol handlers havn't been registered on the node](https://github.com/filecoin-project/go-filecoin/blob/199c9241887366995ea8493fc5d9136be9f09f3c/protocol/storage/miner.go#L125-L126).

**Comment by muronglaowang** [comment]
> Could you please share the detail steps of test scenario?
I know the reason, 


> 因为我对此有一种直觉：
> 
> > Peer不支持协议
> 
> 此错误消息_通常_意味着矿工未进行挖掘，即命令`go-filecoin mining start`从未发出且[协议处理程序未在节点上注册](https://github.com/filecoin-project/go-filecoin/blob/199c9241887366995ea8493fc5d9136be9f09f3c/protocol/storage/miner.go#L125-L126)。

My miner is mining ,Because i run the  go-filecoin mining start 
 ,the  result is :Error: Node is already mining.  My node  process will not stop, but the block is not synchronized to the latest block, It`s always happen

**Comment by muronglaowang** [comment]
> 您好，感谢您报告此事。除了@taoshengshi提到的详细测试场景步骤，还请包含显示问题的日志输出的要点。

My node process will not stop, but the block is not synchronized to the latest block, It`s always happen ， I only have an error message when looking at the log ，23:21:55.863 ERROR       node: too late start=9335  end=10335 current=20581 node.go:680  ，
I can't quite understand its specific meaning。

**Comment by muronglaowang** [comment]
> 您好，感谢您报告此事。除了@taoshengshi提到的详细测试场景步骤，还请包含显示问题的日志输出的要点。

My node process will not stop, but the block is not synchronized to the latest block, It`s always happen ， I only have an error message when looking at the log ，
23:21:55.863 ERROR       node: too late start=9335  end=10335 current=20581 node.go:680
  Why this problem？

**Comment by taoshengshi** [comment]
> My node process will not stop, but the block is not synchronized to the latest block, It`s always happen ， I only have an error message when looking at the log ，
> 23:21:55.863 ERROR node: too late start=9335 end=10335 current=20581 node.go:680
> Why this problem？

I think this is the scenario of miner miss the proving period due to node not syncing with latest block.

@frrist or other PoSt stake holders:
once miner ming miss the proving period due to any reasons, it will never come into the logic of submit PoSt.
this is internal mechanism of filecocin PoSt,  should be this mechanism expose to end user by command line or document? should be go filecoin more robust to resist any conditions which leads to missing proving? or how to slashing the miner at the condition of block syncing late?
![appropriate proving period](https://user-images.githubusercontent.com/33315004/61603925-28aa2800-ac72-11e9-85ff-61829c6abe62.jpg)

**Comment by frrist** [comment]
@muronglaowang please run `go-filecoin inspect all` on your client and miner and share the output here.

**Comment by frrist** [comment]
@taoshengshi correct, if a miner is late on a proving period there is no recovery path for them. This is a known issue and is being tracked here:  https://github.com/filecoin-project/go-filecoin/issues/3018

**Comment by muronglaowang** [comment]
> 您能否分享一下测试场景的详细步骤？



> 您能否分享一下测试场景的详细步骤？



> @muronglaowang请`go-filecoin inspect all`在您的客户和矿工上运行并在此处分享输出。
This is my client output

Version:	0edc3e9c95f198cc5a20c3f94badb6d86160d7cc

Runtime
OS:           	linux
Arch:         	amd64
Version:      	go1.12.1
Compiler:     	gc
NumProc:      	4
GoMaxProcs:   	4
NumGoRoutines:	75718
NumCGoCalls:  	506203

Disk
Free:  	7903445516288
Total: 	7503767404544
FSType:	26985

Memory
Swap:   	0
Virtual:	33270208000

Environment
FilAPI: 	
FilPath:	/fil
GoPath: 	

Config
{
	"api": {
		"address": "/ip4/127.0.0.1/tcp/3453",
		"accessControlAllowOrigin": [
			"http://localhost:8080",
			"https://localhost:8080",
			"http://127.0.0.1:8080",
			"https://127.0.0.1:8080"
		],
		"accessControlAllowCredentials": false,
		"accessControlAllowMethods": [
			"GET",
			"POST",
			"PUT"
		]
	},
	"bootstrap": {
		"addresses": [
			"/dns4/user.kittyhawk.wtf/tcp/9000/ipfs/Qmd6xrWYHsxivfakYRy6MszTpuAiEoFbgE1LWw4EvwBpp4",
			"/dns4/user.kittyhawk.wtf/tcp/9001/ipfs/QmXq6XEYeEmUzBFuuKbVEGgxEpVD4xbSkG2Rhek6zkFMp4",
			"/dns4/user.kittyhawk.wtf/tcp/9002/ipfs/QmXhxqTKzBKHA5FcMuiKZv8YaMPwpbKGXHRVZcFB2DX9XY",
			"/dns4/user.kittyhawk.wtf/tcp/9003/ipfs/QmZGDLdQLUTi7uYTNavKwCd7SBc5KMfxzWxAyvqRQvwuiV",
			"/dns4/user.kittyhawk.wtf/tcp/9004/ipfs/QmZRnwmCjyNHgeNDiyT8mXRtGhP6uSzgHtrozc42crmVbg"
		],
		"minPeerThreshold": 1,
		"period": "10s"
	},
	"datastore": {
		"type": "badgerds",
		"path": "badger"
	},
	"heartbeat": {
		"beatTarget": "/dns4/stats-infra.kittyhawk.wtf/tcp/8080/ipfs/QmUWmZnpZb6xFryNDeNU7KcJ1Af5oHy7fB9npU67sseEjR",
		"beatPeriod": "3s",
		"reconnectPeriod": "10s",
		"nickname": "Lindentwtyone"
	},
	"mining": {
		"minerAddress": "t2wcubvddj7ilhc3noxpmpokp5bukxao6qm4qb6hi",
		"autoSealIntervalSeconds": 120,
		"storagePrice": "0"
	},
	"mpool": {
		"maxPoolSize": 10000,
		"maxNonceGap": "100"
	},
	"net": "devnet-user",
	"observability": {
		"metrics": {
			"prometheusEnabled": false,
			"reportInterval": "5s",
			"prometheusEndpoint": "/ip4/0.0.0.0/tcp/9400"
		},
		"tracing": {
			"jaegerTracingEnabled": false,
			"probabilitySampler": 1,
			"jaegerEndpoint": "http://localhost:14268/api/traces"
		}
	},
	"sectorbase": {
		"rootdir": "/fil/s"
	},
	"swarm": {
		"address": "/ip4/0.0.0.0/tcp/6000"
	},
	"wallet": {
		"defaultAddress": "t1fxz3yzvpfhxhu7c5eav2t3fpmsotgg63cvnd2ki"
	}
}



This is my miner info

OS:           	linux
Arch:         	amd64
Version:      	go1.12.1
Compiler:     	gc
NumProc:      	12
GoMaxProcs:   	12
NumGoRoutines:	199516
NumCGoCalls:  	27865454

Disk
Free:  	7885869350912
Total: 	7486191239168
FSType:	26985

Memory
Swap:   	0
Virtual:	45529444000

Environment
FilAPI: 	
FilPath:	/fil
GoPath: 	

Config
{
	"api": {
		"address": "/ip4/127.0.0.1/tcp/3453",
		"accessControlAllowOrigin": [
			"http://localhost:8080",
			"https://localhost:8080",
			"http://127.0.0.1:8080",
			"https://127.0.0.1:8080"
		],
		"accessControlAllowCredentials": false,
		"accessControlAllowMethods": [
			"GET",
			"POST",
			"PUT"
		]
	},
	"bootstrap": {
		"addresses": [
			"/dns4/user.kittyhawk.wtf/tcp/9000/ipfs/Qmd6xrWYHsxivfakYRy6MszTpuAiEoFbgE1LWw4EvwBpp4",
			"/dns4/user.kittyhawk.wtf/tcp/9001/ipfs/QmXq6XEYeEmUzBFuuKbVEGgxEpVD4xbSkG2Rhek6zkFMp4",
			"/dns4/user.kittyhawk.wtf/tcp/9002/ipfs/QmXhxqTKzBKHA5FcMuiKZv8YaMPwpbKGXHRVZcFB2DX9XY",
			"/dns4/user.kittyhawk.wtf/tcp/9003/ipfs/QmZGDLdQLUTi7uYTNavKwCd7SBc5KMfxzWxAyvqRQvwuiV",
			"/dns4/user.kittyhawk.wtf/tcp/9004/ipfs/QmZRnwmCjyNHgeNDiyT8mXRtGhP6uSzgHtrozc42crmVbg"
		],
		"minPeerThreshold": 1,
		"period": "10s"
	},
	"datastore": {
		"type": "badgerds",
		"path": "badger"
	},
	"heartbeat": {
		"beatTarget": "/dns4/stats-infra.kittyhawk.wtf/tcp/8080/ipfs/QmUWmZnpZb6xFryNDeNU7KcJ1Af5oHy7fB9npU67sseEjR",
		"beatPeriod": "3s",
		"reconnectPeriod": "10s",
		"nickname": "Lindeneightyfive"
	},
	"mining": {
		"minerAddress": "t2tqdtvvh2aaz6svecxx47puoiq7jly3ihmdwfzny",
		"autoSealIntervalSeconds": 120,
		"storagePrice": "0.000000001"
	},
	"mpool": {
		"maxPoolSize": 10000,
		"maxNonceGap": "100"
	},
	"net": "devnet-user",
	"observability": {
		"metrics": {
			"prometheusEnabled": false,
			"reportInterval": "5s",
			"prometheusEndpoint": "/ip4/0.0.0.0/tcp/9400"
		},
		"tracing": {
			"jaegerTracingEnabled": false,
			"probabilitySampler": 1,
			"jaegerEndpoint": "http://localhost:14268/api/traces"
		}
	},
	"sectorbase": {
		"rootdir": "/fil/s"
	},
	"swarm": {
		"address": "/ip4/0.0.0.0/tcp/6000"
	},
	"wallet": {
		"defaultAddress": "t1zm6i2o5zqnsiwrqujsd57wwa4nf56kneqv6zyfy"
	}
}

**Comment by anorth** [comment]
I'm closing this for now (but there's still no recovery path yet).
