### ISSUE TITLE
Fetcher interface accepts a predicate that it applies to fetched TipSets

### ISSUE THREAD

**Issue by frrist** [filecoin-project/go-filecoin#3101]
### Description
The [Fetcher](https://github.com/filecoin-project/go-filecoin/blob/5f9ba6cc91dcb81ab424f7a82f9ca60d2f8aad35/net/fetcher.go#L16-L19) interface should be modified to accept a predicate method that is applied to TipSets retrieved by the fetcher. The predicate method can then be used to determine when to stop fetching -- e.g. fetching is returning blocks we already have processed state for.

### Acceptance criteria
- Fetcher interface is modified to look similar to:
```
// Fetcher defines an interface that may be used to fetch data from the network.
type Fetcher interface {
	FetchTipSets(ctx context.Context, tsKey types.TipSetKey, until func(ts types.TipSet) bool) ([]types.TipSet, error)
}
```
- BitswapFetcher is updated to implement the interface.

**Comment by anorth** [comment]
Done
