### ISSUE TITLE
Expose chain syncing information

### ISSUE THREAD

**Issue by travisperson** [filecoin-project/go-filecoin#3107]
### Description

Currently the only way to understand what is happening during chain syncing is to read through log messages.

This is difficult and not ideal for users, it's also not convenient for testing as log messages may change frequently and makes testing for certain information fragile.

We should provide a cli command for users that will provide information to users so they can understand the current state of their chain.

There is already work being done to improve the chain syncing of the daemon at the moment. This work would tail off of the improvements being made.

There are two main pieces of information we want to know

1) Is chain syncing running?
2) What are we syncing?
3) Current progress?

To answer these questions a first proposal would to be expose the start / end time of the last / current call to `HandleNewTipset`, along with the tipset key.

```
{
   "mode": "",
   "start": "",
   "end": "",
   "tipset": [
      ""
   ],
   "delta": 0
}
```
_key names are completely up for change_

### Acceptance criteria

- CLI command to expose chain syncing status
- Result contains the `start` to the last call of `HandleNewTipset`
- Result contains the `end` to the last call of `HandleNewTipset` or null if it's running
- Result contains the `mode` of the chain syncer (`Syncing` or `CaughtUp`).
- Result contains the `tipset` passed to `HandleNewTipset`.
- Result contains the `delta`, which is the block difference between the last tipset fetched and our chain height.

--------------------

I defer strongly to suggests from @frrist who is currently leading the chain syncing rework.

**Comment by anorth** [comment]
Thanks for filing this. I think we can expose some great info about both downloading and validation, more than you've suggested, in a `chain status` command. @frrist can work out the details after we've finished the present refactors for graphsync and mode.

**Comment by anorth** [comment]
Moar status! 

- Since this structure is intended for external consumption, we should decouple it from the internal ChainInfo (also, please extract the trusted flag from that).
- For long fetches, include information about how much has been fetched so far (a tool could then indicate progress-%).

```
type SyncStatus struct {
  // The heaviest that has been fully validated
  ValidatedHead types.TipSetKey
  // The height of ValidatedHead
  ValidatedHeadHeight uint64

  // They key of the head of the chain currently being fetched/validator, or undef if none
  SyncingTip types.TipSetKey
  // The height of SyncingTIp
  SyncingHeight uint64
  // Whether SyncingTip is trusted as a head far away from the validated head
  SyncingTrusted boolean
  // The lowest height fetched for SyncingTip
  SyncingFetchedToHeight uint64
  // Whether fetching for SyncingTip has completed (reached ValidatedHead)
  SyncingFetchComplete boolean
  // The time at which SyncingTip began
  SyncStarted time.Time
}
```

**Comment by frrist** [comment]
Question about `SyncingFetchedToHeight`. I think this implies the fetcher will need to store or emit the most recent tipset it has fetched, would you expect:
- a polling method like `LastTipSetFetched() types.TipSet`
- a publishing channel, similar to `HeadEvent` on the chain store

**Comment by anorth** [comment]
I would expect a callback passed to the fetching method. It already has one, which I hope is sufficient!
