### ISSUE TITLE
Replace NewChainWithMessages for RequireChainWithMessages

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/go-filecoin#3110]
### Description
The `plumbing/msg` waiter tests use the `NewChainWithMessages` test setup function.  This function should be replaced with the cleaner `RequireChainWithMessages` introduced in #3076.  After doing this `NewChainWIthMessages` can be deleted from `core/testing.go`

### Acceptance criteria
No more `NewChainWithMessages`

--edit--
Also move this functionality directly onto the chain builder

### Where to begin
Look at how #3076 did this replacement in the inbox tests.  If you are not familiar with the new `chain.Builder` in `chain/testing.go` understand the basics of that type first.

**Comment by anorth** [comment]
As I commented, I think this functionality can be placed on the chain builder directly.

**Comment by ZenGround0** [comment]
Looking at this further this will be quite a bit of work to be done right.  Probably all the plumbing/msg tests should move from using a chain store to a `testChainReader` that wraps a builder and also keeps track of the head.  Also complicating this -- the state needs to be set.  This is our chance to try out the builder's `stateBuilder` dependency.

**Comment by anorth** [comment]
The exported `NewChainWithMessages` is gone. There's still some debt in the waiter tests, but closing this issue.
