### ISSUE TITLE
[bug] How to deal with this problem?

### ISSUE THREAD

**Issue by LYT1272478208** [filecoin-project/go-filecoin#3116]
ERROR    metrics: Heartbeat service failed to connect for 14h59m0.004938122s: dial to self attempted heartbeat.go:148

**Comment by ZenGround0** [comment]
This is interesting, I wouldn't expect the heartbeat service to dial its own address. cc @frrist @travisperson

**Comment by frrist** [comment]
@LYT1272478208 could you share two things here:
1. the output of `go-filecoin id`
2. the output of `go-filecoin inspect all`

The heartbeat attempting a self dial leads me to believe the filecoin node may be misconfigured. If we can confirm that is not the case we will investigate this issue further as this is unexpected behaviour.

**Comment by LYT1272478208** [comment]
> @LYT1272478208 could you share two things here:
> 
> 1. the output of `go-filecoin id`
> 2. the output of `go-filecoin inspect all`
> 
> The heartbeat attempting a self dial leads me to believe the filecoin node may be misconfigured. If we can confirm that is not the case we will investigate this issue further as this is unexpected behaviour.

./go-filecoin id
{
	"Addresses": [
		"/ip4/127.0.0.1/tcp/6000/ipfs/QmNQhEKr2vcw6UgwzmWfeajHBXBtCJNjT5TCLe5hH29Lp4",
		"/ip4/192.168.0.161/tcp/6000/ipfs/QmNQhEKr2vcw6UgwzmWfeajHBXBtCJNjT5TCLe5hH29Lp4",
		"/ip4/121.35.100.154/tcp/37260/ipfs/QmNQhEKr2vcw6UgwzmWfeajHBXBtCJNjT5TCLe5hH29Lp4"
	],
	"ID": "QmNQhEKr2vcw6UgwzmWfeajHBXBtCJNjT5TCLe5hH29Lp4"
}
zcr@zcr-desktop:~/go/bin$ ./go-filecoin inspect all
Version:	0edc3e9c95f198cc5a20c3f94badb6d86160d7cc

Runtime
OS:           	linux
Arch:         	amd64
Version:      	go1.12.1
Compiler:     	gc
NumProc:      	4
GoMaxProcs:   	4
NumGoRoutines:	796
NumCGoCalls:  	11511

Disk
Free:  	35544801280
Total: 	32326934528
FSType:	61267

Memory
Swap:   	0
Virtual:	23828636000

Environment
FilAPI: 	
FilPath:	
GoPath: 	

Config
{
	"api": {
		"address": "/ip4/127.0.0.1/tcp/3453",
		"accessControlAllowOrigin": [
			"http://localhost:8080",
			"https://localhost:8080",
			"http://127.0.0.1:8080",
			"https://127.0.0.1:8080"
		],
		"accessControlAllowCredentials": false,
		"accessControlAllowMethods": [
			"GET",
			"POST",
			"PUT"
		]
	},
	"bootstrap": {
		"addresses": [
			"/dns4/user.kittyhawk.wtf/tcp/9000/ipfs/Qmd6xrWYHsxivfakYRy6MszTpuAiEoFbgE1LWw4EvwBpp4",
			"/dns4/user.kittyhawk.wtf/tcp/9001/ipfs/QmXq6XEYeEmUzBFuuKbVEGgxEpVD4xbSkG2Rhek6zkFMp4",
			"/dns4/user.kittyhawk.wtf/tcp/9002/ipfs/QmXhxqTKzBKHA5FcMuiKZv8YaMPwpbKGXHRVZcFB2DX9XY",
			"/dns4/user.kittyhawk.wtf/tcp/9003/ipfs/QmZGDLdQLUTi7uYTNavKwCd7SBc5KMfxzWxAyvqRQvwuiV",
			"/dns4/user.kittyhawk.wtf/tcp/9004/ipfs/QmZRnwmCjyNHgeNDiyT8mXRtGhP6uSzgHtrozc42crmVbg"
		],
		"minPeerThreshold": 1,
		"period": "10s"
	},
	"datastore": {
		"type": "badgerds",
		"path": "badger"
	},
	"heartbeat": {
		"beatTarget": "/dns4/stats-infra.kittyhawk.wtf/tcp/8080/ipfs/QmNQhEKr2vcw6UgwzmWfeajHBXBtCJNjT5TCLe5hH29Lp4",
		"beatPeriod": "3s",
		"reconnectPeriod": "10s",
		"nickname": "zcrtest"
	},
	"mining": {
		"minerAddress": "empty",
		"autoSealIntervalSeconds": 120,
		"storagePrice": "0"
	},
	"mpool": {
		"maxPoolSize": 10000,
		"maxNonceGap": "100"
	},
	"net": "devnet-user",
	"observability": {
		"metrics": {
			"prometheusEnabled": false,
			"reportInterval": "5s",
			"prometheusEndpoint": "/ip4/0.0.0.0/tcp/9400"
		},
		"tracing": {
			"jaegerTracingEnabled": false,
			"probabilitySampler": 1,
			"jaegerEndpoint": "http://localhost:14268/api/traces"
		}
	},
	"sectorbase": {
		"rootdir": ""
	},
	"swarm": {
		"address": "/ip4/0.0.0.0/tcp/6000"
	},
	"wallet": {
		"defaultAddress": "t1dxodkibgngy3mzdvbgh6poxuhvrgm2oxao2pvly"
	}
}

**Comment by frrist** [comment]
@LYT1272478208 the heartbeat address your filecoin node is configured to use is incorrect -- your nodes PeerID is set as the heartbeat target, this causes the self dials.

You can correct this by running the command:
`go-filecoin config heartbeat.beatTarget "/dns4/stats-infra.kittyhawk.wtf/tcp/8080/ipfs/QmUWmZnpZb6xFryNDeNU7KcJ1Af5oHy7fB9npU67sseEjR"`
and then restarting your node.

For more information on how to connect to the Usernet dashboard refer to the [Network Dashboard](https://github.com/filecoin-project/go-filecoin/wiki/Explorer-and-Dashboard#network-dashboard) section of the wiki.

**Comment by LYT1272478208** [comment]
ERROR net.bootst: got error trying to connect to bootstrap node {Qmd6xrWYHsxivfakYRy6MszTpuAiEoFbgE1LWw4EvwBpp4: [/dns4/user.kittyhawk.wtf/tcp/9000]}: context deadline exceeded bootstrap.go:137
