### ISSUE TITLE
[bug]failed to verify PoSt due to State.SectorCommitments change

### ISSUE THREAD

**Issue by diwufeiwen** [filecoin-project/go-filecoin#3117]
Describe the bug
failed to verify PoSt: LEN(proofs) must == CEIL(LEN(comm_rs)/POST_SECTORS_COUNT);
I think it is because the threads "submitPoSt" and "commitSector" change the state of  miner actor at the same time. eg.When miner reads State.SectorCommitments and Construction inputs , CommitSector is writing to State.SectorCommitments.

Expected behavior
When the variable inputs is determined in the function Miner::OnNewHeaviestTipSet, State.SectorCommitments is not allowed to change.

Debug infomation
Err:failed to verify PoSt: LEN(proofs) must == CEIL(LEN(comm_rs)/POST_SECTORS_COUNT): len1, len2

**Comment by ZenGround0** [comment]
Thanks for filing, looks like a correct assessment.  The bad news is that this error will show up occasionally on the devnet until the next release.  The good news is that we have already fixed this on master in PR #3067 so this problem will go away without any more action after the next release.  Feel free to reopen if you have any questions or concerns not addressed by #3067.
