### ISSUE TITLE
Chain store takes tipset keys

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/go-filecoin#3119]
### Description
As pointed out [here](https://github.com/filecoin-project/go-filecoin/pull/3111#discussion_r306561887) the tipindex accessor methods on the chain store API take in strings in places where they should take in tipset keys.

### Acceptance criteria
Move to tipset keys in chain store.

### Risks + pitfalls
Should be very straightforward.

### Where to begin
`chain/store.go`: `HasTipSetAndState`, `GetTipSetAndStatesByParentsAndHeight`, `HasTipSetAndStatesWithParentsAndHeight`

**Comment by deaswang** [comment]
Need this issue also modify TipIndex.GetXxx and TipIndex.HasXxx. Even more to replace type tsasByTipSetID map[string]*TipSetAndState by type tsasByTipSetID map[types.TipSetKey]*TipSetAndState.
