### ISSUE TITLE
Enable message signing for pubsub

### ISSUE THREAD

**Issue by frrist** [filecoin-project/go-filecoin#3124]
### Description
Message signing is currently disabled in libp2p pubsub, this is something we may want moving forward. v0.1.0 of pubsub now requires that it be enabled in order for strict signature verification to work.

### Where to begin
https://github.com/filecoin-project/go-filecoin/blob/33ffd9ab8a9f13310990121b1c30ea165ffa0739/node/node.go#L416-L418

**Comment by anorth** [comment]
@ZenGround0 is this done?

**Comment by ZenGround0** [comment]
No and this might become an interop hurdle.  Thanks for flagging.
