### ISSUE TITLE
 Consume new go-sectorbuilder CGO bindings

### ISSUE THREAD

**Issue by laser** [filecoin-project/go-filecoin#3127]
### Description

@laser recently copied the CGO bindings for rust-fil-sector-builder [into a new project](https://github.com/filecoin-project/go-sectorbuilder) so that it could be shared between @Kubuxu and go-filecoin. We should update go-filecoin to consume the CGO bindings and build tooling in this project instead of using our own CGO bindings. This will prevent us from having to maintain two copies of the same CGO bindings.

### Notes

1. go-filecoin will have a submodule relationship with go-sectorbuilder
1. go-filecoin `deps` script will need to recursively update submodule upon initialization (because go-sectorbuilder has a submodule relationship with bls-signatures)
1. go-sectorbuilder already has a [Makefile](https://github.com/filecoin-project/go-sectorbuilder/blob/master/Makefile) which can be called by go-filecoin tooling in order to install go-sectorbuilder

### Acceptance Criteria

1. Remove rust-fil-sector-builder CGO bindings from go-filecoin codebase
1. Remove rust-fil-sector-builder submodule from go-filecoin and replace with go-sectorbuilder submodule
1. Ensure `deps` downloads appropriate rust-fil-sector-builder release, if one exists
1. Ensure `deps` builds from source as a fallback
1. Work with @travisperson to ensure migration to go-sectorbuilder doesn't regress the go-filecoin release flow

**Comment by anorth** [comment]
cc @icorderi. @laser would this make a good project for familiarisation with these bindings?

**Comment by laser** [comment]
Why, yes it would! I’ll reach out to @icorderi about this issue on Monday. Thanks, @anorth.
