### ISSUE TITLE
Correct inaccurate "finality" name

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/go-filecoin#3130]
### Description
Our syncer won't sync a chain that is too far ahead under certain circumstances.  Our code calls this concept finality which veers from the well known concept of finality.  We should give `finality` a snappy, accurate name.  

### Acceptance criteria
Goal: change the misleading name
Non-goal: evaluate if it is safe to do block chains that are too long or if we should actually be implementing finality checks.

### Where to begin
First think of a good name, then change [this function](https://github.com/filecoin-project/go-filecoin/blob/master/chain/syncer.go#L481) and all consumers.

**Comment by anorth** [comment]
FYI @frrist , and easy one for you
