### ISSUE TITLE
[bug] go run ./build/ lint warning messages after libp2p upgrade

### ISSUE THREAD

**Issue by frrist** [filecoin-project/go-filecoin#3143]
**Describe the bug**
We updated the version of `github.com/golangci/golangci-lint` (v1.17.0) we use when upgrading go-libp2p. This update results in the following warning logs being returned when the linter is ran:
```
$ go run ./build/ lint
Linting ./... ...
go run github.com/golangci/golangci-lint/cmd/golangci-lint run
level=warning msg="[runner/golint] Golint: can't lint 3 files: no file name for file &{Doc:<nil> Package:6844383 Name:bls Decls:[0xc008dc4780 0xc008dc47c0 0xc008dc4800 0xc008dc48c0 0xc008dc4900 0xc008dc4940 0xc008dc4980 0xc008dc49c0 0xc008dc4a40] Scope:scope 0xc003ec3000 {\n\tconst SignatureBytes\n\tconst PublicKeyBytes\n\ttype PublicKey\n\ttype PrivateKey\n\ttype Message\n\ttype Digest\n\tconst PrivateKeyBytes\n\tconst DigestBytes\n\ttype Signature\n}\n Imports:[] Unresolved:[byte byte byte byte byte] Comments:[0xc007b9e2e0 0xc007b9e360 0xc007b9e3e0 0xc007b9e4a0 0xc007b9e520 0xc007b9e5c0 0xc007b9e660 0xc007b9e720 0xc007b9e7a0]}"
```
This was introduced in a1771a863590be1432979fea9dc98d5bc99e4d0e

**To Reproduce**
run:
`go run ./build/ lint`

**Expected behavior**
No warning logs are returned when the command is ran.

**Version information**

- Go: go1.12.1
- Commit: a1771a863590be1432979fea9dc98d5bc99e4d0e

**Comment by frrist** [comment]
I believe these warning are relate to the contents of [bls.go](https://github.com/filecoin-project/go-filecoin/blob/e9dac13ead993416ca5b25d27e04b758def25507/bls-signatures/bls.go), since we are moving away from this in https://github.com/filecoin-project/go-filecoin/pull/3099 I would hold off on investigating this further.

**Comment by shannonwells** [comment]
I am pretty sure they are related to contents of bls.go too.  Also the error doesn't always occur, and I see it on my machine at home but not at work. May be related to parsing time, because if I run it a couple of times it eventually does pass.

**Comment by frrist** [comment]
This doesn't happen anymore (at least for a long while), closing.
