### ISSUE TITLE
Make `miner power` output JSON not a string

### ISSUE THREAD

**Issue by shannonwells** [filecoin-project/go-filecoin#3144]
## Description
As noted in [Pull 3136](https://github.com/filecoin-project/go-filecoin/pull/3136), the `miner power` command outputs "N / M", miner power / total power, which was implemented [as originally designed](https://github.com/filecoin-project/go-filecoin/issues/1128), however we would like to have the CLI output JSON results which can be more easily parsed.

## Acceptance criteria
`miner power <mineraddr>` outputs two big.Ints, one for miner power and one for total power (of the network).  This is serialized as:
{
  minerPower: N
  totalPower: N
}

**Comment by travisperson** [comment]
To add some details to this, there can be a text encoder to provide the `n / m` output, but the emitted value by the `Run` func should be a structure and not the formatted string.

**Comment by frrist** [comment]
closed via #3169
