### ISSUE TITLE
Flaky deals tests with non-zero exit code for `propose-storage-deal`

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/go-filecoin#3148]
`TestDealsRedeem`, `TestDealsShowPaymentVouchers`, and `TestDealsShow` frequently flake because the `go-filecoin client propose-storage-deal` does not complete successfully.

See:
* https://circleci.com/gh/filecoin-project/go-filecoin/23412
* https://circleci.com/gh/filecoin-project/go-filecoin/23343
* https://circleci.com/gh/filecoin-project/go-filecoin/23857
* https://circleci.com/gh/filecoin-project/go-filecoin/23410

**Comment by travisperson** [comment]
Here is another failure from something else https://circleci.com/gh/filecoin-project/go-filecoin/24530#tests/containers/2

I don't think I've ever seen an error about a miner actor not being found though.

**Comment by anorth** [comment]
I see the actor not found error very frequently - I'm sure there's a race there somewhere. I'm lucky enough to have a local environment that reproduces some of these failures *very* frequently 😬

**Comment by anorth** [comment]
Obsolete
