### ISSUE TITLE
modify the `deps` command such that it downloads only Groth parameters and keys for 1KiB sectors

### ISSUE THREAD

**Issue by laser** [filecoin-project/go-filecoin#3152]
### Description

Original issue [here](https://app.zenhub.com/workspaces/cryptolabfilecoin-integration-5d31e8d6a02eb00001aa3df7/issues/filecoin-project/go-filecoin/3072):

Quoting @anorth 

> An acceptable state to me would be that deps only downloads verifying params and the 1KiB proof param, and no more. Miners must explicitly invoke paramfetch to fetch more. This is predicated on the go-filecoin daemon clearly alerting the user to a missing parameter as soon as they mining start (not waiting until a seal or PoSt is scheduled).

### Acceptance criteria

- `deps` uses `paramfetch` to download parameters for 1KiB sectors
- `mining start` produces an error message informing user if they're missing Groth parameters for their configured sector size

### Risks + pitfalls

The second of the two criteria, above, is blocked on [this rust-fil-sector-builder](https://github.com/filecoin-project/rust-fil-sector-builder/issues/22) issue.

### Where to begin

- [`SectorBuilder#init_with_metadata`](https://github.com/filecoin-project/rust-fil-sector-builder/blob/master/sector-builder/src/builder.rs#L38) could be a place to put the cache-checking call
- [`paramcache`](https://github.com/filecoin-project/rust-fil-proofs/blob/master/filecoin-proofs/src/bin/paramcache.rs#L21) contains the enumeration of circuits which seal and PoSt-generation are currently configured to use

**Comment by laser** [comment]
@mishmosh 

> Once this is done, I believe we can remove this step from the Getting Started steps. (Please confirm or correct.)

Once this work is complete, a developer (whose environment is configured in "test proofs mode") will not need to do anything differently than they need to do today. The `deps` command will download verifying keys for all supported sector sizes. The `deps` command will download parameters for 1KiB sectors.

Once this work is complete, an end-user won't need to do anything differently than they do today, unless they wish to use a non-default sector size. The `paramfetch` program, by default, downloads all published Groth parameters and verifying keys. This ensures that the end-user will have their Groth parameter cache hydrated with parameters for all sector sizes that `miner create` allows for (and some which it won't!).

> Can someone confirm the miner create command will now support this option? And that the default is 1KiB if not specified?

The `miner create` command already supports the `--sectorsize` option. If not specified, the default will be used. In environments that use "live proofs mode" (devnet/user, for instance), 256MiB is the default (and only valid option, were the user to specify a value). In environments which use "test proofs mode" (developers' computers), 1KiB is the default (and the only valid option).

> What units are used to specify sector size in the code? Should we use the same units in the CLI or will that be prone to typos/errors?

The `--sectorsize` argument accepts a number, which is the quantity of bytes in the sealed sector. For 1KiB sectors, this is `--sectorsize=1024`. For 256MiB sectors, this is `--sectorsize=268435456`.

**Comment by anorth** [comment]
@laser this being assigned to you means I assume you are planning to do the work. If it's a reasonable thing to hand over, maybe @icorderi could take it over?

**Comment by laser** [comment]
@anorth - I have not assigned it to `@icorderi` yet because GitHub doesn't allow for it. `@icorderi` isn't yet a member of the `filecoin-project` organization.

I do think that this is a thing which he could do, and I would love to get it off my plate.

**Comment by laser** [comment]
@icorderi @mishmosh @anorth @dignifiedquire - The story _sector builder should fail to initialize if parameter cache is missing required Groth parameters and/or verifying keys_ which blocked this issue is now in `rust-fil-sector-builder` `master`. It won't be live in `go-filecoin` until we next release `go-sectorbuilder`.
