### ISSUE TITLE
Sector id upbound

### ISSUE THREAD

**Issue by merced** [filecoin-project/go-filecoin#3160]
In the Encode function in rleplus/rleplus.go, there is a restriction to the sector id range, which is less than 16384, Not sure if it's intentional and part of the design decision or subject to change in the coming releases?

**Comment by travisperson** [comment]
I believe the value comes from the max sectors that can be used in PoSt construction (`POST_SECTORS_COUNT`). The idea being that a miner using all available sectors will never exceed the 2<sup>14</sup> sectors so there is no need to encode an integer larger than that.

There is a draft PR to increase this value to 2<sup>18</sup> at the moment with a bit of this information (https://github.com/filecoin-project/go-filecoin/pull/3131).

@ingar might be able to provide some additional information.
