### ISSUE TITLE
[bug]failed to seal sector with unrecoverable error: Permission denied 

### ISSUE THREAD

**Issue by taoshengshi** [filecoin-project/go-filecoin#3166]
Describe the bug

Follow the normal process of propose-storage-deal, and got error in the log:
```
[0;37m15:53:16.214 ^[[31mERROR ^[[0;34m      node: ^[[0mfailed to seal sector with id 1: unrecoverable error: Permission denied (os error 13) ^[[0;37mnode.go:861
```

To Reproduce
node1:
- create miner and get miner id:
```
t2evdb4dvkdyjx23jyqew2tftumvz3umvbeqqudoq
```
- start mining

node2:

- list ask:

```
go-filecoin client list-asks --enc=json | jq
{
  "Miner": "t2evdb4dvkdyjx23jyqew2tftumvz3umvbeqqudoq",
  "Price": "0.000000001",
  "Expiry": 3001,
  "ID": 0,
  "Error": null
}
```
- propose-storage-deal

```
go-filecoin client propose-storage-deal t2evdb4dvkdyjx23jyqew2tftumvz3umvbeqqudoq  QmXmxHCK8v2GneGXMKS5pDgVc4S32QTWwWaodsni1oeU44  0 2880
State:   accepted
Message:
DealID:  bafy2bzaceatgqjciaegikwhuf4hlum64nm4spulnn272kuupwkdmyyhnbb3gy
```
Version information
```
Go: go version go1.12.7 linux/amd64
Rust: rustc 1.36.0 (a53f9df32 2019-07-03)
Cargo: argo 1.36.0 (c4fcfb725 2019-05-15)
Commit: ec25290
Go Env:
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/tshi/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/tshi/code/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build287286147=/tmp/go-build -gno-record-gcc-switches"
CC:
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-36)
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

Additional context
```
this is the master branch of go-filecoin
./go-filecoin version
commit: 3dbbf3a515ab9c9c48bb37da5dafc7bce77e17c0
```

**Comment by travisperson** [comment]
In #3075 we have changed the default location of the proof parameters.

To solve this issue you can either follow the steps in #3075, or set `FILECOIN_PARAMETER_CACHE` to the old default of `/tmp/filecoin-proof-parameters`.

I would suggest moving the parameters, but you can temporary fix the issue by setting the environment variable to verify.

**Comment by taoshengshi** [comment]
thanks! @travisperson ,it works well with FILECOIN_PARAMETER_CACHE settings.

I believe team has [fully discussed](https://github.com/filecoin-project/rust-fil-proofs/issues/629) on the topic you mentioned. but some minor comments:

1.  /var/tmp/ is independent of any linux user, that means some user have no permission to create directory in that folder or request to add extra permission to /var/ which would be bring security issue . Anyway we can use `FILECOIN_PARAMETER_CACHE`, but is `/var` a proper location？

2. go-filecoin/rust check the parameter files as mandatory preliminaries to run and exist gracefully with messages if these files are missing.

3.go-filecoin binary current use the `FILECOIN_PARAMETER_CACHE` env, and not sure the schedule of  `FIL_PROOFS_PARAMETER_CACHE` [will take effect](https://github.com/filecoin-project/rust-fil-proofs/issues/741), could team highlight the nightly build including this changes to nightly testers?

**Comment by travisperson** [comment]
1) I think the default location may be dropped, there is an issue open around this in rust proofs ( https://github.com/filecoin-project/rust-fil-proofs/issues/742).

2) This work is being tracked over in the sector builder: https://github.com/filecoin-project/rust-fil-sector-builder/issues/22

3) This is an interesting idea. I've been thinking about tracking major changes with a Github label on PRs. Something else we could start doing is requiring PRs that will result in CHANGELOG entries actually update the change log in the PR itself. This should at least provide a way to diff between two nightly change logs to see new entries.

**Comment by taoshengshi** [comment]
cool! good to see the coming of nightly change logs especially the user/tester interface changes.
