### ISSUE TITLE
[bug] install-rust-fil-sector-builder.sh should be reentrant

### ISSUE THREAD

**Issue by taoshengshi** [filecoin-project/go-filecoin#3174]
Describe the bug
The scripts works well for the first time:
```

Compiling storage-proofs v0.5.0
   Compiling sled v0.24.1
   Compiling hyper-tls v0.3.2
warning: couldn't execute `/usr/bin --prefix` (error: Permission denied (os error 13))
warning: set the LLVM_CONFIG_PATH environment variable to a valid `llvm-config` executable
   Compiling reqwest v0.9.19
   Compiling filecoin-proofs v0.5.0
   Compiling sector-builder v0.4.0 (/home/tshi/code/go/src/github.com/filecoin-project/go-filecoin/proofs/rust-fil-sector-builder/sector-builder)
note: Link against the following native artifacts when linking against this static library. The order and any duplication can be significant on some platforms.

note: native-static-libs: -lutil -lutil -ldl -lrt -lpthread -lgcc_s -lc -lm -lrt -lpthread -lutil -lutil

▽
#!/usr/bin/env bash

note: Link against the following native artifacts when linking against this static library. The order and any duplication can be significant on some platforms.

note: native-static-libs: -lutil -lutil -ldl -lrt -lpthread -lgcc_s -lc -lm -lrt -lpthread -lutil -lutil

    Finished release [optimized] target(s) in 7m 33s
```
If do a reentrant execution :` make deps`again,the scripts will break at:
```
linker_flags=$(cat ${build_output_tmp} \
    | grep native-static-libs\: \
    | head -n 1 \
    | cut -d ':' -f 3)
```
because cargo build did not generate `native-static-libs` related information in the ` ${build_output_tmp} ` file, so the `grep` failed cause the shell exit.

I assume here reentrant scenario require cargo rebuild and  generate `native-static-libs` info, but cargo did not rebuild due to no code changing.

And there is no force rebuild([link1](https://github.com/rust-lang/cargo/issues/1136),[link2](https://github.com/rust-lang/cargo/issues/1101)) flag for cargo, so I suggest use `cargo clean && cargo build ` as a workaround.

by the way,there is `llvm-config` missing warning:
```
warning: couldn't execute `llvm-config --prefix` (error: No such file or directory (os error 2))
warning: set the LLVM_CONFIG_PATH environment variable to a valid `llvm-config` executable
```
whereas, llvm-config  is exist without access the LLVM_CONFIG_PATH env:
```
llvm-config -h
usage: llvm-config <OPTION>... [<COMPONENT>...]
```

**Comment by anorth** [comment]
That script comes from https://github.com/filecoin-project/go-sectorbuilder, imported as a submodule. Could you please re-file this issue there?

Thanks for the good detail in the description.

FYI @laser @icorderi
