### ISSUE TITLE
[bug]Storage power is not increase!

### ISSUE THREAD

**Issue by Dengminer** [filecoin-project/go-filecoin#3186]
I had sealed 43 GB data on the miner node, but it always displayed 536.9 MB on the https://stats.kittyhawk.wtf

![1565077808(1)](https://user-images.githubusercontent.com/53812125/62521379-221ad380-b862-11e9-9f50-85c7b1194caf.jpg)

I checked have 2 submitPoSt on the filecoin network.The first submitPoSt was in block 54692, and the  second submitPoSt was in block 55913.

My miner node information

ID : QmPMe8ZeafeAkPLLjx8jWc6vEhmgoi8sQFFoq9rPqT3mDf
minerAddress : t2ltjlvgytjlsetyakjrhelhjsuhhg6ktxims5ofq

**Comment by taylorshuang** [comment]
This is a well-known problem and I don't know if the next version will change.

**Comment by anorth** [comment]
Could you confirm whether those submitPoSts were successful? If late, there is currently no recovery path #3018
