### ISSUE TITLE
[bug] panic: index out of range in chain/get_ancestors

### ISSUE THREAD

**Issue by Dengminer** [filecoin-project/go-filecoin#3188]
The log errors during the running of the program are as follows: My server is configured with 24 cores, 48 threads and 24G memory. I don't know what caused it. It's doing storage transactions.

![1565097456](https://user-images.githubusercontent.com/53812125/62543051-a3d52600-b88f-11e9-9271-9c8ddeb2f098.png)

**Comment by anorth** [comment]
This is quite possibly #3027 showing up in the wild

**Comment by anorth** [comment]
Code deleted
