### ISSUE TITLE
Remove Bitswap Fetcher once Graphsync Fetcher is battle tested

### ISSUE THREAD

**Issue by hannahhoward** [filecoin-project/go-filecoin#3191]
### Description

#3190 makes Graphsync the default fetcher for Blockchains in Filecoin. Once this goes in production in 0.4, and any issues are worked out, there no need to keep the Bitswap Fetcher around, and the code can be removed.

### Acceptance criteria

Bitswap Fetcher is not in Filecoin codebase

### Risks + pitfalls

Again, Graphsync Fetcher is not battle tested yet, so this shouldn't be done until we're sure we won't need the Bitswap Fetcher

### Where to begin

n/a

**Comment by anorth** [comment]
This is a good first issue after 9 September 2019.
