### ISSUE TITLE
Remove `SomeCid`

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/go-filecoin#3193]
### Description
@shannonwells recently made the good suggestion that we remove `SomeCid` from tests either by [hardcoding a default](https://github.com/filecoin-project/go-filecoin/pull/3185#discussion_r311310414) or [forcing the caller to use a string](https://github.com/filecoin-project/go-filecoin/pull/3185#discussion_r311316362)

### Acceptance criteria
`SomeCid` is replaced with one of the above suggestions.  I prefer forcing the caller to use a string but use your discretion.

### Where to begin
Choose a replacement strategy, grep SomeCid.

**Comment by shannonwells** [comment]
I too prefer forcing the caller to use a string :)
