### ISSUE TITLE
[bug] go-ipld-prime 369bb56ad071 is not fetchable

### ISSUE THREAD

**Issue by travisperson** [filecoin-project/go-filecoin#3199]
**Description**

```
$ go run ./build/*.go deps
go: finding github.com/ipld/go-ipld-prime v0.0.0-20190730002952-369bb56ad071
go: github.com/ipld/go-ipld-prime@v0.0.0-20190730002952-369bb56ad071: unknown revision 369bb56ad071
go: error loading module requirements
```

We currently have a direct and indirect dependency on `go-ipld-prime@369bb56ad071`. This revision of `go-ipld-prime` is from a branch was rebased yesterday resulting in the commit not being fetchable. (https://github.com/ipld/go-ipld-prime/pull/25)

We need to update our dependency as well as our dependency on `go-graphsync` after it's updated as it also has a direct dependency on `go-ipld-prime@369bb56ad071`.

https://github.com/ipfs/go-graphsync/blob/f506993bcc90f9273544f7c0096ff966e01dff63/go.mod#L16

--------------

**More Info**

On August 1st we merged PR #3153 which added a dependency on `go-ipld-prime@369bb56ad071`, as well as `go-graphsync`. This means that any branch which contains the commit `fe3d41143e81d461d8f049f0ac739b391b5aa342` may experience this bug if you have not ran `deps` since before yesterday on the branch due to the lack of the dependency in cache.

**Acceptance Criteria**
-  A tagged reference in `go-ipld-prime` is created for our dependency to ensure it's resolvable.

**Comment by hannahhoward** [comment]
@travisperson I pushed that ref for now in a seperate branch. BUT... this why as it turns out depending on a branch of go-ipld-prime was not a great idea :) My bad. I'm working on getting my commits in master and then tagging them. In the meantime, this should allow us to build.

**Comment by travisperson** [comment]
Thanks! That sounds like a good solution for this problem till we merge the branch.

**Comment by hannahhoward** [comment]
Looks like code is in master so I will be updating and submitting a more final PR today.
