### ISSUE TITLE
[Staging] Other unexpected behavior

### ISSUE THREAD

**Issue by mishmosh** [filecoin-project/go-filecoin#3207]
_This issue is for users who would like to help test the staging devnet. Please read #3157 for background._ 

Report any unexpected behavior changes here. For example: my power takes a day to be registered, I can only commit a certain number of sectors before my PoSts start failing.

**Comment by dayou5168** [comment]
i want to test the filecoin-staging-devnet-0.4.0,
when i follow the normal way to deploy this release ,init the node, i got this error:

initializing filecoin node at /fil/filecoin
02:40:41.896  INFO     badger: All 0 tables opened in 0s
 logger.go:46
02:40:42.095  INFO     badger: All 0 tables opened in 0s
 logger.go:46
02:40:42.296  INFO     badger: All 0 tables opened in 0s
 logger.go:46
02:40:42.495  INFO     badger: All 0 tables opened in 0s
 logger.go:46
Error: Could not Init Node: link value was empty

so how can i deploy the release and start test ,do we have some document?

**Comment by diwufeiwen** [comment]
> i want to test the filecoin-staging-devnet-0.4.0,
> when i follow the normal way to deploy this release ,init the node, i got this error:
> 
> initializing filecoin node at /fil/filecoin
> 02:40:41.896 INFO badger: All 0 tables opened in 0s
> logger.go:46
> 02:40:42.095 INFO badger: All 0 tables opened in 0s
> logger.go:46
> 02:40:42.296 INFO badger: All 0 tables opened in 0s
> logger.go:46
> 02:40:42.495 INFO badger: All 0 tables opened in 0s
> logger.go:46
> Error: Could not Init Node: link value was empty
> 
> so how can i deploy the release and start test ,do we have some document?

try this:go-filecoin init --devnet-staging --genesisfile=https://genesis.staging.kittyhawk.wtf/genesis.car

**Comment by coder-lb** [comment]
As @diwufeiwen  mentioned, with --devnet-staging option and the corresponding genesis file, it works.

**Comment by Dengminer** [comment]
i install the filecoin-staging-devnet-0.4.0,but error reporting during running 



> 20:01:30.449  INFO     badger: All 2 tables opened in 2ms
>  logger.go:46
> 20:01:30.451  INFO     badger: Replaying file id: 0 at offset: 1139555
>  logger.go:46
> 20:01:30.451  INFO     badger: Replay took: 20.98Âµs
>  logger.go:46
> 20:01:30.457  INFO     badger: All 1 tables opened in 0s
>  logger.go:46
> 20:01:30.459  INFO     badger: Replaying file id: 0 at offset: 176
>  logger.go:46
> 20:01:30.459  INFO     badger: Replay took: 20.293Âµs
>  logger.go:46
> 20:01:30.465  INFO     badger: All 2 tables opened in 0s
>  logger.go:46
> 20:01:30.469  INFO     badger: Replaying file id: 0 at offset: 20855
>  logger.go:46
> 20:01:30.469  INFO     badger: Replay took: 20.341Âµs
>  logger.go:46
> 20:01:30.473  INFO     badger: All 0 tables opened in 0s
>  logger.go:46
> 20:01:30.475  INFO     badger: Replaying file id: 0 at offset: 0
>  logger.go:46
> 20:01:30.475  INFO     badger: Replay took: 19.457Âµs
>  logger.go:46
> My peer ID is QmTnHtUii27HZzbKfgksLmRwmn9PyhJWvTrr3kXQZVaoLC
> Swarm listening on: /ip4/127.0.0.1/tcp/6000
> Swarm listening on: /ip4/172.16.86.153/tcp/6000
> 20:01:30.478  INFO chain.stor: start loading chain at tipset: { bafy2bzacea7w5jvlt3krbrgwzptuxzimxgbhbfydueo6zoruurlamdn5jv7xy }, height: 63 store.go:135
> 20:01:30.486  INFO chain.stor: load tipset: { bafy2bzacebf7ko7t7t76winmroj3m4xkfwqevbetoh33cxecykehobcisdkwu bafy2bzaced5duzvdmh2slvh5hs2halhzumsysduw6akkuyjzyn2csy7nlb6wo }, height: 60 store.go:153
> 20:01:30.503  INFO chain.stor: load tipset: { bafy2bzacec7fxf7xtejz2og6i24grxvxw2j4lh32h7nsmp6uxihm72bzgf4vw }, height: 54 store.go:153
> 20:01:30.526  INFO chain.stor: load tipset: { bafy2bzaceaxzkbjwnxkonnu7i3k3q37fmiwxiubsijsna7n5aor5oi2o7bfhw }, height: 48 store.go:153
> 20:01:30.549  INFO chain.stor: load tipset: { bafy2bzacece5dtjs266cm22fpsbu6ag4cyos6ai2z247dck6folqyldo3vrfe }, height: 42 store.go:153
> 20:01:30.571  INFO chain.stor: load tipset: { bafy2bzacedvt4r3uivpwwekcc6deutqngsyxi2yjio5njovyelsq7ohcys2rg }, height: 36 store.go:153
> 20:01:30.593  INFO chain.stor: load tipset: { bafy2bzacead366w4tifed7fazv3yf6eh4upvk72fwj4ahirndlpazr5h5mige }, height: 30 store.go:153
> 20:01:30.617  INFO chain.stor: load tipset: { bafy2bzaceadm6q4emzu6vucr24zmzuxup6qera7dvvmtxgkar533e7l5gboh6 }, height: 24 store.go:153
> 20:01:30.639  INFO chain.stor: load tipset: { bafy2bzacec4ympmdqi2c6bjnd2hekvlpsu5zkdnczhzbtrmyzumahudrqlya2 }, height: 18 store.go:153
> 20:01:30.662  INFO chain.stor: load tipset: { bafy2bzaceb33a52pdugrrs4d2npjdskispkh75zvjvxc4skcvp5hwyafvk5yq }, height: 12 store.go:153
> 20:01:30.685  INFO chain.stor: load tipset: { bafy2bzaceb7rkldpj5qaxsyvdj4n5k73a46fv25lntpm2od5xfhltp2fszx7g }, height: 6 store.go:153
> 20:01:30.708  INFO chain.stor: load tipset: { bafy2bzaceahqhwhhe6abnyqhqex462ac4gnzvqlx4gj4zjd3yzd45hbt5ukw6 }, height: 0 store.go:153
> 20:01:30.713  INFO chain.stor: finished loading 63 tipsets from { bafy2bzacea7w5jvlt3krbrgwzptuxzimxgbhbfydueo6zoruurlamdn5jv7xy } store.go:179
> 20:01:42.155  INFO       node: error handling blocks: { bafy2bzacebv4cptwhzdtjxr4h3zbhgf6gchfatozylqsz3znmb2hpmlogar2e bafy2bzaceb4phfofdcrl2eoz4xmbhdm52hrqefufl7opscjttuqout35hb53u } node.go:573
> 20:01:44.605  INFO       node: error handling blocks: { bafy2bzacebv4cptwhzdtjxr4h3zbhgf6gchfatozylqsz3znmb2hpmlogar2e bafy2bzaceb4phfofdcrl2eoz4xmbhdm52hrqefufl7opscjttuqout35hb53u } node.go:573
> 20:01:44.916  INFO       node: error handling blocks: { bafy2bzacebv4cptwhzdtjxr4h3zbhgf6gchfatozylqsz3znmb2hpmlogar2e bafy2bzaceb4phfofdcrl2eoz4xmbhdm52hrqefufl7opscjttuqout35hb53u } node.go:573
> 20:01:45.229  INFO       node: error handling blocks: { bafy2bzacebv4cptwhzdtjxr4h3zbhgf6gchfatozylqsz3znmb2hpmlogar2e bafy2bzaceb4phfofdcrl2eoz4xmbhdm52hrqefufl7opscjttuqout35hb53u } node.go:573
> 20:01:45.360 WARNI /fil/hello: failed to send hello handshake to peer QmUWmZnpZb6xFryNDeNU7KcJ1Af5oHy7fB9npU67sseEjR: protocol not supported hello.go:180
> 20:01:45.486  INFO       node: error handling blocks: { bafy2bzacebv4cptwhzdtjxr4h3zbhgf6gchfatozylqsz3znmb2hpmlogar2e bafy2bzaceb4phfofdcrl2eoz4xmbhdm52hrqefufl7opscjttuqout35hb53u } node.go:573
> 20:01:45.854  INFO    metrics: successfully to open stream, peerID: QmUWmZnpZb6xFryNDeNU7KcJ1Af5oHy7fB9npU67sseEjR, targetAddr: /dns4/stats-infra.kittyhawk.wtf/tcp/8080 heartbeat.go:252
> 20:01:46.858  INFO    autonat: Discovered AutoNAT peer QmXhxqTKzBKHA5FcMuiKZv8YaMPwpbKGXHRVZcFB2DX9XY notify.go:34
> 20:01:49.286  INFO    autonat: Discovered AutoNAT peer QmXq6XEYeEmUzBFuuKbVEGgxEpVD4xbSkG2Rhek6zkFMp4 notify.go:34
> 20:01:49.489  INFO    autonat: Discovered AutoNAT peer Qmd6xrWYHsxivfakYRy6MszTpuAiEoFbgE1LWw4EvwBpp4 notify.go:34
> 20:01:49.598  INFO    autonat: Discovered AutoNAT peer QmZRnwmCjyNHgeNDiyT8mXRtGhP6uSzgHtrozc42crmVbg notify.go:34
> 20:01:49.644  INFO    autonat: Discovered AutoNAT peer QmZGDLdQLUTi7uYTNavKwCd7SBc5KMfxzWxAyvqRQvwuiV notify.go:34
> 20:01:54.452  INFO  graphsync: Graphsync ReceiveError: stream reset graphsync.go:112
> 20:02:01.241  INFO  graphsync: Graphsync ReceiveError: stream reset graphsync.go:112
> 20:02:19.009  INFO       node: error handling blocks: { bafy2bzacedla7ps4snku22baktuvfsovx75nc5s4scdwjefwsdlc3ryhtn4g4 } node.go:573
> 20:02:19.084 WARNI peer-track: unexpected duplicate track on peer: QmPzxyirh1SEARocm5xYPo5yDge7MrPwwr3mW526yzEvNR peer_tracker.go:39
> 20:02:19.085 WARNI peer-track: unexpected duplicate track on peer: QmPzxyirh1SEARocm5xYPo5yDge7MrPwwr3mW526yzEvNR peer_tracker.go:39
> 20:02:19.730 WARNI peer-track: unexpected duplicate track on peer: QmbXCgosMGv1rp2STjWuT5XrxcV66ptGDFtXT9C35uajeY peer_tracker.go:39
> 20:02:23.773  INFO    autonat: Discovered AutoNAT peer QmaM5SdrZxUwxVjp9rrFCTQiMaupTADLV5Wbgh19dAoc2H notify.go:34
> 20:02:24.417  INFO  graphsync: Graphsync ReceiveError: stream reset graphsync.go:112
> 20:02:25.704  INFO       node: Received new block from network cid: bafy2bzacebty7vut243bibonb74wi26lohumlrfzwzvsbdmpz2djfqbvcdeue block.go:57
> 20:02:27.018  INFO       node: error handling blocks: { bafy2bzacealpz7glssivwmqsqvxbrgut2cs6d73r3dwkz4v6wujhymcrvvhoy bafy2bzacebu7j24cg5csb7wmv3zwbi7jil6xiumc5bbopfgruitozrirvjjt2 } node.go:573
> 20:02:27.262  INFO       node: error handling blocks: { bafy2bzacealpz7glssivwmqsqvxbrgut2cs6d73r3dwkz4v6wujhymcrvvhoy bafy2bzacebu7j24cg5csb7wmv3zwbi7jil6xiumc5bbopfgruitozrirvjjt2 } node.go:573
> 20:02:30.658  INFO    autonat: Discovered AutoNAT peer Qmd6xrWYHsxivfakYRy6MszTpuAiEoFbgE1LWw4EvwBpp4 notify.go:34
> 20:02:30.676  INFO    autonat: Discovered AutoNAT peer QmXq6XEYeEmUzBFuuKbVEGgxEpVD4xbSkG2Rhek6zkFMp4 notify.go:34
> 20:02:31.487  INFO    autonat: Discovered AutoNAT peer QmZGDLdQLUTi7uYTNavKwCd7SBc5KMfxzWxAyvqRQvwuiV notify.go:34
> 20:02:42.595  INFO  graphsync: Graphsync ReceiveError: stream reset graphsync.go:112
> 20:02:48.467  INFO    autonat: Discovered AutoNAT peer Qmd6xrWYHsxivfakYRy6MszTpuAiEoFbgE1LWw4EvwBpp4 notify.go:34
> 20:02:57.697 ERROR       node: error in handler github.com/filecoin-project/go-filecoin/node.(*Node).processBlock-fm for topic /fil/blocks/devnet-3: processing block from network: could not load message collection with cid: bafy2bzaceao5q2ozyk3v7kf2vbuggfljgrxk7paqifzjscnut24bdrk6m535y: blockservice: key not found node.go:1059
> 20:02:57.697  INFO       node: Received new block from network cid: bafy2bzacecnlajf7keeblpkxuvi4vyw3t2tx5e7jyls6yvimim7ypn2rs7tnm block.go:57
> 20:02:57.966  INFO       node: error handling blocks: { bafy2bzacebty7vut243bibonb74wi26lohumlrfzwzvsbdmpz2djfqbvcdeue } node.go:573
> 20:02:58.672 ERROR       node: error in handler github.com/filecoin-project/go-filecoin/node.(*Node).processBlock-fm for topic /fil/blocks/devnet-3: processing block from network: could not load message collection with cid: bafy2bzaceao5q2ozyk3v7kf2vbuggfljgrxk7paqifzjscnut24bdrk6m535y: blockservice: key not found node.go:1059
> 20:03:13.459  INFO  graphsync: Graphsync ReceiveError: stream reset graphsync.go:112
> 20:03:16.828 WARNI /fil/hello: failed to send hello handshake to peer QmRpGkNWDa8nSCsoTQP5PXNnKs3iGDCR5tf6Dbxnzd7pyN: protocol not supported hello.go:180
> 20:03:16.958 WARNI /fil/hello: failed to send hello handshake to peer QmZg56Q2F87KZxAf7ctCcrn7kNKssJG1TPCLk2FvBd4Mrv: stream reset hello.go:180
> 20:03:18.542 WARNI /fil/hello: failed to send hello handshake to peer Qme5rxkvDZqzqDLLwafJxepwjrDSRmEeQb81f8G8bzKdYU: protocol not supported hello.go:180
> 20:03:23.461  INFO  graphsync: Graphsync ReceiveError: stream reset graphsync.go:112
> 20:03:27.711  INFO       node: Received new block from network cid: bafy2bzaceaclbstenayyo5bqwiifuzrslk6url2bsilvqdkgzvvytb63rnoj4 block.go:57
> 20:03:35.028 ERROR       node: error in handler github.com/filecoin-project/go-filecoin/node.(*Node).processBlock-fm for topic /fil/blocks/devnet-3: processing block from network: could not load message collection with cid: bafy2bzaceao5q2ozyk3v7kf2vbuggfljgrxk7paqifzjscnut24bdrk6m535y: blockservice: key not found node.go:1059
> 20:03:58.718  INFO       node: Received new block from network cid: bafy2bzaceaf5dl2etmbi4rkydikjmqcl6qvigxw7wdnl2g4nlxajwx7aloz2w block.go:57
> 20:03:59.185 ERROR       node: error in handler github.com/filecoin-project/go-filecoin/node.(*Node).processBlock-fm for topic /fil/blocks/devnet-3: processing block from network: could not load message collection with cid: bafy2bzaceao5q2ozyk3v7kf2vbuggfljgrxk7paqifzjscnut24bdrk6m535y: blockservice: key not found node.go:1059
> 20:04:14.759  INFO  graphsync: Graphsync ReceiveError: stream reset graphsync.go:112
> 20:05:03.214  INFO       node: Received new block from network cid: bafy2bzacedbc7vrqn2ylkbhxcelz4ugsagkqt3e3nf7fpv2fwpnfz2i24ni5s block.go:57
> 20:05:03.696 ERROR       node: error in handler github.com/filecoin-project/go-filecoin/node.(*Node).processBlock-fm for topic /fil/blocks/devnet-3: processing block from network: could not load message collection with cid: bafy2bzaceao5q2ozyk3v7kf2vbuggfljgrxk7paqifzjscnut24bdrk6m535y: blockservice: key not found node.go:1059
> 20:05:31.601  INFO       node: Received new block from network cid: bafy2bzacedfe32h262pesw5xgzq33jdgf5wkkw2azzrubmjucgcueuaqt5h36 block.go:57
> 20:05:32.090 ERROR       node: error in handler github.com/filecoin-project/go-filecoin/node.(*Node).processBlock-fm for topic /fil/blocks/devnet-3: processing block from network: could not load message collection with cid: bafy2bzaceao5q2ozyk3v7kf2vbuggfljgrxk7paqifzjscnut24bdrk6m535y: blockservice: key not found node.go:1059
> 20:06:02.692  INFO       node: Received new block from network cid: bafy2bzaceanh4u57ppxovxorgswdaplhxnxm2vnsuzqblytoohmt6hkkqtz6y block.go:57
> 20:06:04.780 ERROR       node: error in handler github.com/filecoin-project/go-filecoin/node.(*Node).processBlock-fm for topic /fil/blocks/devnet-3: processing block from network: could not load message collection with cid: bafy2bzaceao5q2ozyk3v7kf2vbuggfljgrxk7paqifzjscnut24bdrk6m535y: blockservice: key not found node.go:1059
> 20:06:05.015  INFO       node: error handling blocks: { bafy2bzaceanh4u57ppxovxorgswdaplhxnxm2vnsuzqblytoohmt6hkkqtz6y } node.go:573
> 20:06:05.062  INFO       node: Received new block from network cid: bafy2bzacebbnjcbffvbn7hmxi35k75xtpj4dyy4q2inkp3mbt7ah5gm6l7j54 block.go:57
> 20:06:08.577  INFO    autonat: Discovered AutoNAT peer Qmd6xrWYHsxivfakYRy6MszTpuAiEoFbgE1LWw4EvwBpp4 notify.go:34
> 20:06:09.380 ERROR       node: error in handler github.com/filecoin-project/go-filecoin/node.(*Node).processBlock-fm for topic /fil/blocks/devnet-3: processing block from network: could not load message collection with cid: bafy2bzaceao5q2ozyk3v7kf2vbuggfljgrxk7paqifzjscnut24bdrk6m535y: blockservice: key not found node.go:1059
> 20:06:09.624  INFO       node: error handling blocks: { bafy2bzaceanh4u57ppxovxorgswdaplhxnxm2vnsuzqblytoohmt6hkkqtz6y bafy2bzacebbnjcbffvbn7hmxi35k75xtpj4dyy4q2inkp3mbt7ah5gm6l7j54 } node.go:573
>

**Comment by Dengminer** [comment]
I ran the program on version 0.4, and the block remained at 63 heights all the time. 

![1565356479(1)](https://user-images.githubusercontent.com/53812125/62781501-bac38480-baea-11e9-8128-f2231032e54f.png)

Now I can't get FIL in my wallet, so I can't create miners and mining properly.

**Comment by travisperson** [comment]
We have yet to officially stand up the staging network with the release we want . I will update issue https://github.com/filecoin-project/go-filecoin/issues/3157 when things are running.

**Comment by diwufeiwen** [comment]
the block  synchronization failed, remained at 55 heights all the time.

 ./go-filecoin version
commit: 248588e3875bbe73498ae2c60a508de8e7c86cf6

while : ; do ./go-filecoin show block `./go-filecoin chain head | head -n 1` ; sleep 70;done
Block Details
Miner:  t2ilv24boe3wjogeq35gvf3e6rjf6qmevecpxf6yy
Weight: 5650.000
Height: 55
Nonce:  0
Messages:  bafy2bzacebc3bt6cedhoyw34drrmjvazhu4oj25er2ebk4u445pzycvq4ta4a
Receipts:  bafy2bzacebc3bt6cedhoyw34drrmjvazhu4oj25er2ebk4u445pzycvq4ta4a
Timestamp:  1565399841

 ./go-filecoin swarm peers
/ip4/122.144.131.103/tcp/6000/ipfs/QmcKcf2cKCkU2f7EKH52joKbHm3CqVw772QKgHfAHyACmW
/ip4/3.89.132.42/tcp/9000/ipfs/Qmd6xrWYHsxivfakYRy6MszTpuAiEoFbgE1LWw4EvwBpp4
/ip4/3.89.132.42/tcp/9001/ipfs/QmXq6XEYeEmUzBFuuKbVEGgxEpVD4xbSkG2Rhek6zkFMp4
/ip4/3.89.132.42/tcp/9003/ipfs/QmZGDLdQLUTi7uYTNavKwCd7SBc5KMfxzWxAyvqRQvwuiV
/ip4/3.89.132.42/tcp/9004/ipfs/QmZRnwmCjyNHgeNDiyT8mXRtGhP6uSzgHtrozc42crmVbg
/ipfs/Qmd6xrWYHsxivfakYRy6MszTpuAiEoFbgE1LWw4EvwBpp4/p2p-circuit/ipfs/QmS5Vg6ZWwAAW13PtQmXdaGwUZy3fQMJCq4M65xfuRrZd5
/ipfs/Qmd6xrWYHsxivfakYRy6MszTpuAiEoFbgE1LWw4EvwBpp4/p2p-circuit/ipfs/QmXAzQ681JLiwqyoxqtM6kGaDaKzZNspDgNYAEx2W4PQwq
/ipfs/Qmd6xrWYHsxivfakYRy6MszTpuAiEoFbgE1LWw4EvwBpp4/p2p-circuit/ipfs/QmXhxqTKzBKHA5FcMuiKZv8YaMPwpbKGXHRVZcFB2DX9XY
/ipfs/Qmd6xrWYHsxivfakYRy6MszTpuAiEoFbgE1LWw4EvwBpp4/p2p-circuit/ipfs/QmfVSf1qPHdBaJ588VfpBwNkD6GUNyG7MtiCe26sfWXPod

error info:
12:11:31.760 ERROR       node: error in handler github.com/filecoin-project/go-filecoin/node.(*Node).processBlock-fm for topic /fil/blocks/devnet-3: processing block from network: no blocks for tipset node.go:1059
12:11:59.460  INFO       node: Received new block from network cid: bafy2bzacebsq2md2d3dthniralesshs65htphvpiwofjnsfkm7bwcemabrkco block.go:57
12:11:59.712 ERROR       node: error in handler github.com/filecoin-project/go-filecoin/node.(*Node).processBlock-fm for topic /fil/blocks/devnet-3: processing block from network: no blocks for tipset node.go:1059
12:12:02.516  INFO       node: Received new block from network cid: bafy2bzacebu5xto47qf6zcigkjoz6dgyl6mdtrhkcd67lmeuyvc3xdakba57i block.go:57
12:12:02.765 ERROR       node: error in handler github.com/filecoin-project/go-filecoin/node.(*Node).processBlock-fm for topic /fil/blocks/devnet-3: processing block from network: no blocks for tipset node.go:1059

**Comment by anorth** [comment]
I observe the same thing.

It appears that there's a chain of 3040 blocks, but it doesn't validate.

```13:44:29.027  INFO chain.sync: processing block 0 of 3040 for chain with head at { bafy2bzaceacrcn3ye7izsr7v26xwenzchjz5ocobtt3svpvmlm662b5p3ys7q bafy2bzaceazddktvonc3qijgiceri6tqnrzezi2n23yptucndojvugu3z52dc bafy2bzacecwnkysjfixkpuf5lvqyq3sho67vaksvu2l7yuzkow27633fbg4ay } syncer.go:396
```

Later...
```
13:44:29.580  INFO       node: error handling blocks: { bafy2bzaceacrcn3ye7izsr7v26xwenzchjz5ocobtt3svpvmlm662b5p3ys7q bafy2bzaceazddktvonc3qijgiceri6tqnrzezi2n23yptucndojvugu3z52dc bafy2bzacecwnkysjfixkpuf5lvqyq3sho67vaksvu2l7yuzkow27633fbg4ay } node.go:573
13:44:29.955  INFO       node: error handling blocks: { bafy2bzaceacrcn3ye7izsr7v26xwenzchjz5ocobtt3svpvmlm662b5p3ys7q bafy2bzaceazddktvonc3qijgiceri6tqnrzezi2n23yptucndojvugu3z52dc bafy2bzacecwnkysjfixkpuf5lvqyq3sho67vaksvu2l7yuzkow27633fbg4ay } node.go:573
13:44:30.428  INFO       node: error handling blocks: { bafy2bzaceacrcn3ye7izsr7v26xwenzchjz5ocobtt3svpvmlm662b5p3ys7q bafy2bzaceazddktvonc3qijgiceri6tqnrzezi2n23yptucndojvugu3z52dc bafy2bzacecwnkysjfixkpuf5lvqyq3sho67vaksvu2l7yuzkow27633fbg4ay } node.go:573
13:44:30.798  INFO       node: error handling blocks: { bafy2bzaceacrcn3ye7izsr7v26xwenzchjz5ocobtt3svpvmlm662b5p3ys7q bafy2bzaceazddktvonc3qijgiceri6tqnrzezi2n23yptucndojvugu3z52dc bafy2bzacecwnkysjfixkpuf5lvqyq3sho67vaksvu2l7yuzkow27633fbg4ay } node.go:573
13:44:31.167  INFO       node: error handling blocks: { bafy2bzaceacrcn3ye7izsr7v26xwenzchjz5ocobtt3svpvmlm662b5p3ys7q bafy2bzaceazddktvonc3qijgiceri6tqnrzezi2n23yptucndojvugu3z52dc bafy2bzacecwnkysjfixkpuf5lvqyq3sho67vaksvu2l7yuzkow27633fbg4ay } node.go:573
13:44:31.510  INFO       node: error handling blocks: { bafy2bzaceacrcn3ye7izsr7v26xwenzchjz5ocobtt3svpvmlm662b5p3ys7q bafy2bzaceazddktvonc3qijgiceri6tqnrzezi2n23yptucndojvugu3z52dc bafy2bzacecwnkysjfixkpuf5lvqyq3sho67vaksvu2l7yuzkow27633fbg4ay } node.go:573
13:44:31.931  INFO       node: error handling blocks: { bafy2bzaceacrcn3ye7izsr7v26xwenzchjz5ocobtt3svpvmlm662b5p3ys7q bafy2bzaceazddktvonc3qijgiceri6tqnrzezi2n23yptucndojvugu3z52dc bafy2bzacecwnkysjfixkpuf5lvqyq3sho67vaksvu2l7yuzkow27633fbg4ay } node.go:573
13:44:42.090  INFO       node: Received new block from network cid: bafy2bzacea2sscejbgyrnnosg7ngtgeuyqvoqqoy6lgkwxpjvxt6gstsdgzly block.go:57
13:44:43.036 ERROR       node: error in handler github.com/filecoin-project/go-filecoin/node.(*Node).processBlock-fm for topic /fil/blocks/devnet-3: processing block from network: could not load message collection with cid: bafy2bzacecapgrw3gypgdszigx6du3saedctf6ezzucjzbxl6xieo63zvzylw: blockservice: key not found node.go:1059
13:44:43.874  INFO       node: Received new block from network cid: bafy2bzacedzmu2aul5d2tuklonuybqz2tt5ulywudt66jeiaqp2md4y7sbkug block.go:57
13:44:46.126 ERROR       node: error in handler github.com/filecoin-project/go-filecoin/node.(*Node).processBlock-fm for topic /fil/blocks/devnet-3: processing block from network: could not load message collection with cid: bafy2bzacecapgrw3gypgdszigx6du3saedctf6ezzucjzbxl6xieo63zvzylw: blockservice: key not found node.go:1059
13:46:18.322  INFO       node: Received new block from network cid: bafy2bzaceav4wuw63ab7nyg5c5omabir2zmh6q7e6wrxtz4siqn742sd32wd2 block.go:57
13:46:18.922 ERROR       node: error in handler github.com/filecoin-project/go-filecoin/node.(*Node).processBlock-fm for topic /fil/blocks/devnet-3: processing block from network: could not load message collection with cid: bafy2bzacecapgrw3gypgdszigx6du3saedctf6ezzucjzbxl6xieo63zvzylw: blockservice: key not found node.go:1059
13:46:45.926  INFO       node: Received new block from network cid: bafy2bzacecbvmrhqcectv2mgdih3jkasepqaaqtxfy3zv4vh2o2wwsae3zkds block.go:57
13:46:46.499 ERROR       node: error in handler github.com/filecoin-project/go-filecoin/node.(*Node).processBlock-fm for topic /fil/blocks/devnet-3: processing block from network: could not load message collection with cid: bafy2bzacecapgrw3gypgdszigx6du3saedctf6ezzucjzbxl6xieo63zvzylw: blockservice: key not found node.go:1059
13:46:49.327  INFO       node: Received new block from network cid: bafy2bzacec33hf6kd3uwc3mtflayjouwciqiypjf6j7umjyz3agr7wwzq2dka block.go:57
13:46:49.898 ERROR       node: error in handler github.com/filecoin-project/go-filecoin/node.(*Node).processBlock-fm for topic /fil/blocks/devnet-3: processing block from network: could not load message collection with cid: bafy2bzacecapgrw3gypgdszigx6du3saedctf6ezzucjzbxl6xieo63zvzylw: blockservice: key not found node.go:1059
```

One thing to note is that this is using the same block pubsub topic as the 0.3 network, so nodes will be receiving a bunch of invalid blocks, possibly even trying to sync the wrong chain. We should change this topic for the same reasons we changed it for 0.3 - we're not learning anything from this unintended "spam" until we implement secure bootstrapping.

**Comment by anorth** [comment]
The [block explorer](https://explorer.staging.kittyhawk.wtf/) reports a height of ~5174 (~43 hrs) and is making progress, so the bootstrap node/s appear to be progressing, but others can't sync that chain.

**Comment by anorth** [comment]
According to my chain, the tip at height 55 has two blocks:
`{bafy2bzaceabftoi3xpfpfmkehpxn7fwdpc722wakorx42xzcs3cn2eubr3dzc, bafy2bzacecqsyt2tlsjgza4b77u4n4fc4ugplw2jgch3a6yrhb2mpij343ius
}`. This is the last one that validates locally.

Unfortunately `chain ls` doesn't show unvalidated blocks and the block explorer doesn't appear to have a way to jump to a height, so I haven't yet determined the CIDs of the next non-empty tip.

**Comment by anorth** [comment]
I have filed a new issue #3220 to track the syncing (which is halting due to database state missing the message collection for a block at height 56). Please move discussion of that problem to that issue, and bring up new problems here.

**Comment by dayou5168** [comment]
i cant get mock fil from https://faucet.staging.kittyhawk.wtf/ in china, we cant access this site sometimes.
so how to solve this problem!  thanks.

**Comment by travisperson** [comment]
Staging was probably down at the time you were trying to access it. We are currently resolving an issue as we move towards deploying the user devnet. You can find more information, and stay up with the current status of the deployment by join the #fil-release-04x channel on our slack.

**Comment by travisperson** [comment]
Github issue: https://github.com/filecoin-project/go-filecoin/issues/3274
