### ISSUE TITLE
[bug] panic: concurrent map iteration and map write in saveDealsAwaitingSeal

### ISSUE THREAD

**Issue by Dengminer** [filecoin-project/go-filecoin#3210]
my server hardware information
cpu:96 Cores
ram:192GB

It's crashed after i had run go-filecoin mining start command about 11 hours.
Is it because be proposed many storage deals?

Buy the miner's storage power is not increase. https://stats.kittyhawk.wtf/storage/mining

My peer ID: QmQ6ZFDQiXDhhqKKEs7HZdd1FX5fKhiiiPqK2WYAKVMaoA

devnet version number :0.3.2

![1565333362(1)](https://user-images.githubusercontent.com/53812125/62759805-f2afd500-bab4-11e9-907e-baf7910219b1.jpg)

**Comment by travisperson** [comment]
Looks like we are missing a lock:

https://github.com/filecoin-project/go-filecoin/blob/0edc3e9c95f198cc5a20c3f94badb6d86160d7cc/protocol/storage/miner.go#L488-L500

**Comment by Dengminer** [comment]
I'm not a professional developer. I'm very interested in filecoin.I would love to participate in version 0.4 testing.However, the staging-devnet-0.4.0 version currently deployed is not available for testing.
[https://github.com/filecoin-project/go-filecoin/issues/3207](url)
