### ISSUE TITLE
[bug]the minner node always stoped  by useing all the memory!

### ISSUE THREAD

**Issue by dayou5168** [filecoin-project/go-filecoin#3219]
**Describe the bug**
i keep propose deal to a minner node, one deal after another, about two days later ,the minner node stoped, i got this error

:08:08:06.028 WARNI net/identi: error reading identify message:  
short buffer id.go:146
memory allocation of 134217728 bytes failed

i got 64GB RAM, i found this error in recent release ,include 0.2.4, so ,is it a bug?
or maybe the way i test the program is not right?

**Comment by anorth** [comment]
Thanks for this report. The 0.2.4 release is relatively old - we expect to ship 0.4.x next week and would really appreciate your reproducing the issue on that release. We do not expect memory allocation failures on a machine of that capacity.

cc @icorderi @laser

**Comment by dayou5168** [comment]
> Thanks for this report. The 0.2.4 release is relatively old - we expect to ship 0.4.x next week and would really appreciate your reproducing the issue on that release. We do not expect memory allocation failures on a machine of that capacity.
> 
> cc @icorderi @laser

ok ,thanks i'll close this issue!
