### ISSUE TITLE
[bug] Failure to sync tipset received from hello, could not load message collection

### ISSUE THREAD

**Issue by anorth** [filecoin-project/go-filecoin#3220]
**Describe the bug**
On the 0.4.0 staging network, node are failing to sync the chain past height 55, because the message collection for a block at height 56 is not found in the store.

First reported in #3207, this issue is focussed on that specific problem.

It appears that there's a chain of ~3k blocks, but it doesn't validate.

```
13:44:29.027  INFO chain.sync: processing block 0 of 3040 for chain with head at { bafy2bzaceacrcn3ye7izsr7v26xwenzchjz5ocobtt3svpvmlm662b5p3ys7q bafy2bzaceazddktvonc3qijgiceri6tqnrzezi2n23yptucndojvugu3z52dc bafy2bzacecwnkysjfixkpuf5lvqyq3sho67vaksvu2l7yuzkow27633fbg4ay } syncer.go:396
```

Later...
```
13:44:29.580  INFO       node: error handling blocks: { bafy2bzaceacrcn3ye7izsr7v26xwenzchjz5ocobtt3svpvmlm662b5p3ys7q bafy2bzaceazddktvonc3qijgiceri6tqnrzezi2n23yptucndojvugu3z52dc bafy2bzacecwnkysjfixkpuf5lvqyq3sho67vaksvu2l7yuzkow27633fbg4ay } node.go:573
13:44:29.955  INFO       node: error handling blocks: { bafy2bzaceacrcn3ye7izsr7v26xwenzchjz5ocobtt3svpvmlm662b5p3ys7q bafy2bzaceazddktvonc3qijgiceri6tqnrzezi2n23yptucndojvugu3z52dc bafy2bzacecwnkysjfixkpuf5lvqyq3sho67vaksvu2l7yuzkow27633fbg4ay } node.go:573
13:44:30.428  INFO       node: error handling blocks: { bafy2bzaceacrcn3ye7izsr7v26xwenzchjz5ocobtt3svpvmlm662b5p3ys7q bafy2bzaceazddktvonc3qijgiceri6tqnrzezi2n23yptucndojvugu3z52dc bafy2bzacecwnkysjfixkpuf5lvqyq3sho67vaksvu2l7yuzkow27633fbg4ay } node.go:573
13:44:30.798  INFO       node: error handling blocks: { bafy2bzaceacrcn3ye7izsr7v26xwenzchjz5ocobtt3svpvmlm662b5p3ys7q bafy2bzaceazddktvonc3qijgiceri6tqnrzezi2n23yptucndojvugu3z52dc bafy2bzacecwnkysjfixkpuf5lvqyq3sho67vaksvu2l7yuzkow27633fbg4ay } node.go:573
13:44:31.167  INFO       node: error handling blocks: { bafy2bzaceacrcn3ye7izsr7v26xwenzchjz5ocobtt3svpvmlm662b5p3ys7q bafy2bzaceazddktvonc3qijgiceri6tqnrzezi2n23yptucndojvugu3z52dc bafy2bzacecwnkysjfixkpuf5lvqyq3sho67vaksvu2l7yuzkow27633fbg4ay } node.go:573
13:44:31.510  INFO       node: error handling blocks: { bafy2bzaceacrcn3ye7izsr7v26xwenzchjz5ocobtt3svpvmlm662b5p3ys7q bafy2bzaceazddktvonc3qijgiceri6tqnrzezi2n23yptucndojvugu3z52dc bafy2bzacecwnkysjfixkpuf5lvqyq3sho67vaksvu2l7yuzkow27633fbg4ay } node.go:573
13:44:31.931  INFO       node: error handling blocks: { bafy2bzaceacrcn3ye7izsr7v26xwenzchjz5ocobtt3svpvmlm662b5p3ys7q bafy2bzaceazddktvonc3qijgiceri6tqnrzezi2n23yptucndojvugu3z52dc bafy2bzacecwnkysjfixkpuf5lvqyq3sho67vaksvu2l7yuzkow27633fbg4ay } node.go:573
13:44:42.090  INFO       node: Received new block from network cid: bafy2bzacea2sscejbgyrnnosg7ngtgeuyqvoqqoy6lgkwxpjvxt6gstsdgzly block.go:57
13:44:43.036 ERROR       node: error in handler github.com/filecoin-project/go-filecoin/node.(*Node).processBlock-fm for topic /fil/blocks/devnet-3: processing block from network: could not load message collection with cid: bafy2bzacecapgrw3gypgdszigx6du3saedctf6ezzucjzbxl6xieo63zvzylw: blockservice: key not found node.go:1059
13:44:43.874  INFO       node: Received new block from network cid: bafy2bzacedzmu2aul5d2tuklonuybqz2tt5ulywudt66jeiaqp2md4y7sbkug block.go:57
13:44:46.126 ERROR       node: error in handler github.com/filecoin-project/go-filecoin/node.(*Node).processBlock-fm for topic /fil/blocks/devnet-3: processing block from network: could not load message collection with cid: bafy2bzacecapgrw3gypgdszigx6du3saedctf6ezzucjzbxl6xieo63zvzylw: blockservice: key not found node.go:1059
13:46:18.322  INFO       node: Received new block from network cid: bafy2bzaceav4wuw63ab7nyg5c5omabir2zmh6q7e6wrxtz4siqn742sd32wd2 block.go:57
13:46:18.922 ERROR       node: error in handler github.com/filecoin-project/go-filecoin/node.(*Node).processBlock-fm for topic /fil/blocks/devnet-3: processing block from network: could not load message collection with cid: bafy2bzacecapgrw3gypgdszigx6du3saedctf6ezzucjzbxl6xieo63zvzylw: blockservice: key not found node.go:1059
13:46:45.926  INFO       node: Received new block from network cid: bafy2bzacecbvmrhqcectv2mgdih3jkasepqaaqtxfy3zv4vh2o2wwsae3zkds block.go:57
13:46:46.499 ERROR       node: error in handler github.com/filecoin-project/go-filecoin/node.(*Node).processBlock-fm for topic /fil/blocks/devnet-3: processing block from network: could not load message collection with cid: bafy2bzacecapgrw3gypgdszigx6du3saedctf6ezzucjzbxl6xieo63zvzylw: blockservice: key not found node.go:1059
13:46:49.327  INFO       node: Received new block from network cid: bafy2bzacec33hf6kd3uwc3mtflayjouwciqiypjf6j7umjyz3agr7wwzq2dka block.go:57
13:46:49.898 ERROR       node: error in handler github.com/filecoin-project/go-filecoin/node.(*Node).processBlock-fm for topic /fil/blocks/devnet-3: processing block from network: could not load message collection with cid: bafy2bzacecapgrw3gypgdszigx6du3saedctf6ezzucjzbxl6xieo63zvzylw: blockservice: key not found node.go:1059
```
The [block explorer](https://explorer.staging.kittyhawk.wtf/) reports a height of ~5174 (~43 hrs) and is making progress, so the bootstrap node/s appear to be progressing, but others can't sync that chain.

According to my chain, the tip at height 55 has two blocks:
`{bafy2bzaceabftoi3xpfpfmkehpxn7fwdpc722wakorx42xzcs3cn2eubr3dzc, bafy2bzacecqsyt2tlsjgza4b77u4n4fc4ugplw2jgch3a6yrhb2mpij343ius
}`. This is the last one that validates locally.

By hacking in some better error messages, I can see the problem:
```
14:36:37.523  INFO       node: error handling tipset from hello {peer=QmXhxqTKzBKHA5FcMuiKZv8YaMPwpbKGXHRVZcFB2DX9XY height=5232 head={ bafy2bzacedimud2s74t3vdghaofdfhtnp6i7aacfoydg3djirewnfkst3tzyc }}: failed to sync { bafy2bzaceaxez2uzxtm6ffok76rtksr3lt3ta5hmu3ver6mlirk3knuibqrmq bafy2bzaceddo4xesg4rgojji3ecr55zamsucnupryasrthw5btst7wghwotoq }: failed loading messages for bafy2bzaceddo4xesg4rgojji3ecr55zamsucnupryasrthw5btst7wghwotoq: failed to load messages bafy2bzacecapgrw3gypgdszigx6du3saedctf6ezzucjzbxl6xieo63zvzylw: blockservice: key not found node.go:573
```

Tip height 56 is `{ bafy2bzaceaxez2uzxtm6ffok76rtksr3lt3ta5hmu3ver6mlirk3knuibqrmq bafy2bzaceddo4xesg4rgojji3ecr55zamsucnupryasrthw5btst7wghwotoq }` and [bafy2bzaceddo4xesg4rgojji3ecr55zamsucnupryasrthw5btst7wghwotoq](https://explorer.staging.kittyhawk.wtf/blocks/bafy2bzaceddo4xesg4rgojji3ecr55zamsucnupryasrthw5btst7wghwotoq) has a single message. It is *not* the first block with any messages.

One thing to note is that this is using the same block pubsub topic as the 0.3 network, so nodes will be receiving a bunch of invalid blocks, possibly even trying to sync the wrong chain. We should change this topic for the same reasons we changed it for 0.3 - we're not learning anything from this unintended "spam" until we implement secure bootstrapping.

**To Reproduce**
Join a new node to 0.4.0
```
./go-filecoin init --devnet-staging --genesisfile=https://genesis.staging.kittyhawk.wtf/genesis.car
./go-filecoin daemon
```

Others have reported their chain sync stopping at the same height.

**Expected behavior**
Chain sync continues!

**Comment by anorth** [comment]
According to the [dashboard](http://staging.kittyhawk.wtf:8010/), all five bootstrap nodes are in sync (but no others are). So the nodes that were online around the time this block was generated have been able to validate it.

The block in question has miner address `t2hya4wke6enpyxlsbm753x3fchdpcha3fk7kvlnq` (a miner actor with owner `t1qt2n6r4gt7avhq3inomzmujkap7f67qgmw6wt7i`). I'm pretty sure this is one of the bootstrap miners, because only 5 nodes have succeeded in getting asks on the chain:
```
[~/p/g/s/g/f/go-filecoin](248588e3+)$ ./go-filecoin client list-asks --enc=json
{"Miner":"t2hya4wke6enpyxlsbm753x3fchdpcha3fk7kvlnq","Price":"0.000000001","Expiry":86503,"ID":0,"Error":null}
{"Miner":"t2r6vwtdmqqif7bfg3nxhhwzxljuzm3wldx4w2o4y","Price":"0.000000001","Expiry":86523,"ID":0,"Error":null}
{"Miner":"t2krfc62s6ihea5lahidcbml5uurcsviu5xr7z6uy","Price":"0.000000001","Expiry":165,"ID":0,"Error":null}
{"Miner":"t2wlqaofpjisr2udkloybvchv2gp67djxa4c2uity","Price":"0.000000001","Expiry":86515,"ID":0,"Error":null}
{"Miner":"t2zdx64ocazk23vwgfevfh3s5xto5bklh4oqhx45q","Price":"0.000000001","Expiry":86508,"ID":0,"Error":null}
```

The block looks like:
```
{
  "height": "OA==",
  "messageReceipts": {
    "/": "bafy2bzacebqfwurdoz2k3s5rszdgrtb5zblhjtij2imc2ozpesz3qonwgm63a"
  },
  "messages": {
    "/": "bafy2bzacecapgrw3gypgdszigx6du3saedctf6ezzucjzbxl6xieo63zvzylw"
  },
  "miner": "Aj4ByyieI1+LrkFn+7vsojjeI4Nl",
  "nonce": "AA==",
  "parentWeight": "kJbgAg==",
  "parents": [
    {
      "/": "bafy2bzaceabftoi3xpfpfmkehpxn7fwdpc722wakorx42xzcs3cn2eubr3dzc"
    },
    {
      "/": "bafy2bzacecqsyt2tlsjgza4b77u4n4fc4ugplw2jgch3a6yrhb2mpij343ius"
    }
  ],
  "proof": null,
  "stateRoot": {
    "/": "bafyreigp7aosn54kq2ks2i7ta7c7ub3sfli2ylgaxcnb5p2vmo6lcnzmce"
  },
  "ticket": "RZFuo3F4dFRVNBpsRkJVS3uazO7CESrRZfUfz3kk/IA+w3tK3KFTbJGZlJxExQlri+ulH5XUPvCJ4NhjVrIPhgA=",
  "timestamp": "wLa46gU="
}
```

It as one message, a successful `submitPost` from account `t1umxdsgwldigckvilif4mulau4vrrmun235v47fq` (the worker/owner address for a miner) to `t2krfc62s6ihea5lahidcbml5uurcsviu5xr7z6uy` (a miner actor address). That miner actor is the odd-one-out above with the short ask expiry, and not the one that mined the block.

**Comment by anorth** [comment]
I was able to inspect the "missing" message list locally by:
```
[~/p/g/s/g/f/go-filecoin](248588e3+)$ ./go-filecoin dag get bafy2bzacecapgrw3gypgdszigx6du3saedctf6ezzucjzbxl6xieo63zvzylw
[{"from":"AaMuORrLGgwlVQtBeMosFOVjFlG6","gasLimit":"rAI=","gasPrice":"AQ==","method":"submitPoSt","nonce":"Aw==","params":"g1jDgVjAkr7tJN5Ki/SE0fmz/PuJo1MJrojDMAWQTyRz1aqjIA+tDpV5a6M87JdzQTKHcNzNuQLyAUKlo9ZhjzV1T3fRmz811Sv1aN3rAIKvhLlffI0kLiScJDI3JbLEfQG5Me+dDG+85eFVxSIQR+i8JkeDRASozIPkl7lkYPypWLA6El99Hvmk2Y4jBB6sg2pDaPdqhLjBlAQbBNeNC9wnZq/3gMvtGWp3+B/cyO1F/Fm8cxS64d/JZVkoNkGgeYnnTI0sTKJjaWRzQQBjaWR4AEJBAA==","signature":"AwwY/Zq/fZSRJ4VDzuIjgnV9K6OeaGgwGtJFCt3u79hzDBSGF4bLORDcCv3c82GucoEO7w13Yb63CZMFf//NlAE=","to":"AlRKL2peQcgOrAdAxBYvtKRFKqKd","value":"AA=="}]
```

This had the side-effect of fetching that IPLD node from the network (bitswap), thus making it locally available, and my chain advanced a few blocks until it ran into another missing message list, `bafy2bzacealtrvima3zl6s3he6x7c5hqb7qqpccuyh772hx56er7cw4ssmyse`.

I'm fairly confident that the problem here is that the fetcher is not correctly fetching all the message/receipt lists, and it does not directly detect this failure.

**Comment by anorth** [comment]
By adding some better logging and (unfortunately) missing checks in the fetcher that the messages/receipts are actually fetched, I've all but confirmed that they're failing to be returned in the graphsync query. This missing information only happens occasionally, but deterministically at the same block height regardless of peer.

Because the graphsync fetcher is not verifying that the message/receipt information is in fact received, the problem is not detected until validation time. I'm going to add those checks (and the missing tests for them), which will have the result of pulling the failure forward to fetch time, rather than validation time. I have yet to investigate the specific conditions where graphsync fails us.

**Comment by anorth** [comment]
Ok, I have a theory. I think the recursive selector does not include messages or receipts at the final iteration. Because graphsync queries must start with a single CID (but can then expand lists of references) and tipsets may have multiple blocks, our recursive query for a tipset at level N starts with a block at level N+1 (i.e. the target tip's child) and expands into its parent array in order to fetch all parents. But at the last level, only the headers for these parents are fetched, not the referenced fields.

The selector is:
```
gsf.ssb.ExploreRecursive(recursionDepth, gsf.ssb.ExploreFields(func(efsb selectorbuilder.ExploreFieldsSpecBuilder) {
		efsb.Insert("messages", gsf.ssb.Matcher())
		efsb.Insert("messageReceipts", gsf.ssb.Matcher())
		efsb.Insert("parents", gsf.ssb.ExploreUnion(
			gsf.ssb.ExploreAll(gsf.ssb.Matcher()),
			gsf.ssb.ExploreIndex(0, gsf.ssb.ExploreRecursiveEdge()),
		))
	}))
```

@warpfork with `recursionDepth := 1` would you expect this selector include the `messages` and `messageReceipts` content blocks of the blocks *reached via the recursive edge*, or would you expect it to only fetch the block that contains those refs but not the content of the refs?

**Comment by taylorshuang** [comment]
I wanted to join the staging network, but I found I couldn't synchronize.
![image](https://user-images.githubusercontent.com/1488931/62922120-35d3b600-bddd-11e9-9050-100488c9f0b8.png)
