### ISSUE TITLE
Change name of "show header" to "show block" and "show block" to "show fullblock"

### ISSUE THREAD

**Issue by anorth** [filecoin-project/go-filecoin#3224]
**Describe the bug**
As part of debugging #3220 I wanted to inspect a block header. Unfortunately it's impossible to inspect that block because the node doesn't have the messages stored locally. I specifically wanted to inspect the messagelist CID :-(

**To Reproduce**
On the 0.4.0 staging devnet:
```
[~/p/g/s/g/f/go-filecoin](248588e3+)$ ./go-filecoin show block bafy2bzaceddo4xesg4rgojji3ecr55zamsucnupryasrthw5btst7wghwotoq
Error: could not load message collection with cid: bafy2bzacecapgrw3gypgdszigx6du3saedctf6ezzucjzbxl6xieo63zvzylw: blockservice: key not found
```

**Expected behavior**
The CLI/API should be able to show the structures it has, and not fail because unwanted data is not present. IMO a raw block header should be inspectable, including the messagelist CID. Fetching a composite of a block header with messages receipts is a distinct operation.

@ZenGround0

**Comment by anorth** [comment]
I was able to find the information with `dag get`, but I consider this an unfortunate workaround and would prefer not to expose the state store so directly to the CLI/API.

**Comment by ZenGround0** [comment]
I made the thing you wanted and called it [`show header`](https://github.com/filecoin-project/go-filecoin/blob/master/commands/show.go#L99).  I think it's a good name for what we actually want but it is understandable there was confusion here because we've been abusing the block/header distinction in code forever.

Please reopen if you think we should change the naming.

**Comment by anorth** [comment]
It's a close call, but I've pretty much come around to @whyrusleeping's view that the things in the blockchain are called blocks, at least at the CLI/UI level. I think we should instead get used to the idea that the messages are not *in* the block, but referenced by it.

**Comment by ZenGround0** [comment]
@anorth ok, in that case I am going to modify this issue to track the feature work of swapping the name `header` with `block` and `block` with `fullblock` (or something better).
