### ISSUE TITLE
Protocol command should provide the max pieces size for a sector

### ISSUE THREAD

**Issue by travisperson** [filecoin-project/go-filecoin#3229]
### Description

The sector sizes listed from `go-filecoin protocol` can be used to find the sector sizes that can be used to create a miner. However, these values are not the actual size that a miner can store in a single sector. The actual max value is slightly smaller.

### Acceptance criteria

- A user can find the max piece size for a given sector size.

**Comment by laser** [comment]
Hey Travis,

 The output you seek is already included in the output here:

https://github.com/filecoin-project/go-filecoin/blob/master/commands/protocol.go

See line 39

Erin

**Comment by travisperson** [comment]
Okay thanks!

That should be easy enough to move into the JSON. I'll get a PR up for that.
