### ISSUE TITLE
Remove test skips after storage miner / block miner split

### ISSUE THREAD

**Issue by travisperson** [filecoin-project/go-filecoin#3236]
### Description
In PR https://github.com/filecoin-project/go-filecoin/pull/3235 we are disabling a new tests which require using async mining. These tests can be enabled once https://github.com/filecoin-project/go-filecoin/issues/2968 is resolved. 

This issue is to track the enabling of the tests.

**Comment by anorth** [comment]
@acruikshank did you remove all of these skips, or do some remain?
