### ISSUE TITLE
when I tested the filecoin-staging-devnet-0.4.1,Its height is uniformly zero

### ISSUE THREAD

**Issue by muronglaowang** [filecoin-project/go-filecoin#3240]
Block Details
Miner:  empty
Weight: 0.000
Height: 0
Nonce:  0
Messages:  bafy2bzacebc3bt6cedhoyw34drrmjvazhu4oj25er2ebk4u445pzycvq4ta4a
Receipts:  bafy2bzacebc3bt6cedhoyw34drrmjvazhu4oj25er2ebk4u445pzycvq4ta4a
Timestamp:  0

**Comment by travisperson** [comment]
We had an issue were be published builds that were off by one commit. This has been fixed, see https://github.com/filecoin-project/go-filecoin/issues/3157#issuecomment-521776932 for a bit more information.
