### ISSUE TITLE
[bug]The auto-seal was not triggered,filecoin version 0.3.2

### ISSUE THREAD

**Issue by Dengminer** [filecoin-project/go-filecoin#3243]
After the Filecoin runs for a period of time, it will not trigger auto-seal for a period of time. The Filecoin runs normally, and can receive deals. Then the deals is in the accepted state unchanged. At this time, the CPU has maintained a high utilization rate. Sectors will no longer be created and sealed.I didn't find the error information in the log. 

![1565878421(1)](https://user-images.githubusercontent.com/53812125/63100725-408f7600-bfaa-11e9-8481-7d000ffc5cd2.jpg)

![1565878583(1)](https://user-images.githubusercontent.com/53812125/63100779-5a30bd80-bfaa-11e9-8563-35af529cab95.jpg)

![1565878791(1)](https://user-images.githubusercontent.com/53812125/63101040-d9be8c80-bfaa-11e9-82b1-24df99d23fdb.jpg)

Can anyone tell me why? What was filecoin doing during that time? Or my filecoin is running out of order, thank you!

**Comment by deltazxm** [comment]
POST

**Comment by Dengminer** [comment]
Hi,deltazxm.The process took six hours. Is that normal?

**Comment by deltazxm** [comment]
yes,it's noraml for 0.3.2.next releases will be better

**Comment by Dengminer** [comment]
All right. Thank you very much for your patient explanation. @deltazxm

**Comment by frrist** [comment]
@Dengminer I don't understand the issue you are describing. What behaviour are you expecting?

When a deal is in the `Accepted` state it means that it has been accepted by the miner but the bytes have not yet been transferred from the client to the miner. You can find deal state definitions here: https://github.com/filecoin-project/specs/blob/6a220262ac71d1e744b22b32d98ba929e8335231/network-protocols.md

**Comment by frrist** [comment]
https://github.com/filecoin-project/go-filecoin/issues/3269 should help with this once implemented, closing.
