### ISSUE TITLE
 ./paramfetch -a -v can not connect

### ISSUE THREAD

**Issue by carsonfly** [filecoin-project/go-filecoin#3255]
After I type :' ./paramfetch -a -v'
downloading file... error: https://ipfs.io/ipfs/QmP1PkagfiC9cUEh3r7NEWaJfnBGEnqfABxXxh3PSoiMtX: error trying to connect: Connection refused (os error 111)
downloading file... os error 111error: https://ipfs.io/ipfs/QmbPHbry667qc7JEhYDWpvs6mj6rD9UQRi9ZpQb6q6pcoq: error trying to connect: Connection refused (os error 111)
....
But the network really work ,how can I solve it

**Comment by anorth** [comment]
Can you try to `curl` the same URL to confirm your connectivity to the IPFS gateway?

**Comment by dayou5168** [comment]
i got this problem in every release, we can't access https://ipfs.io in china , but the node can connect with the test-devnet though this error happens,
i really want to konw .how to solve this problem forever!

**Comment by frrist** [comment]
If you are unable to connect due to network issues you may generate the required files locally by running `paramcache`, this can be found in `go-filecoin/proofs/bin`.

**Comment by laser** [comment]
Note: `paramcache` is not a binary included in a `go-filecoin` release. It's something that only developers (PL and contributors) will have on their machine after running `deps`.

**Comment by frrist** [comment]
@carsonfly I am going to close this as there is not enough information to debug this problem, please reopen when you can share:
- geographic location `paramfetch` is being ran from.
- the output of `traceroute ipfs.io`
- the output of `curl -v https://ipfs.io/ipfs/QmP1PkagfiC9cUEh3r7NEWaJfnBGEnqfABxXxh3PSoiMtX`
