### ISSUE TITLE
[bug] memory allocation failed | core dump

### ISSUE THREAD

**Issue by hotlightline** [filecoin-project/go-filecoin#3259]
**Describe the bug**
collapse

**To Reproduce**

**Expected behavior**

**Screenshots**
![1](https://files.slack.com/files-pri/TEHTVS1L6-FML2LLZ1C/1.png)
![2](https://files.slack.com/files-tmb/TEHTVS1L6-FM6DCP5GS-7b87f16e18/2_720.png)

[image1](https://files.slack.com/files-pri/TEHTVS1L6-FML2LLZ1C/1.png)
[image2](https://files.slack.com/files-tmb/TEHTVS1L6-FM6DCP5GS-7b87f16e18/2_720.png)

**Diagnostic information**

- Filecoin Inspect Output: 
- Current Head: 
- Connected Peers: 

**Version information**

- Go:  go1.12.7 linux/amd64
- Rust: rustc 1.36.0 (a53f9df32 2019-07-03)
- Cargo: cargo 1.36.0 (c4fcfb725 2019-05-15)
- Commit: 
- Go Env: GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/gwork"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build861119219=/tmp/go-build -gno-record-gcc-switches"
- CC:

**Additional context**

**Comment by travisperson** [comment]
How much memory / free memory does your system have?

**Comment by hotlightline** [comment]
Tasks: 246 total,   1 running, 149 sleeping,   0 stopped,   0 zombie
%Cpu(s):  0.1 us,  0.0 sy,  0.0 ni, 99.9 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem : 32858380 total, 27180404 free,  3276360 used,  2401616 buff/cache
KiB Swap:  1048572 total,   988560 free,    60012 used. 29401260 avail Mem

**Comment by hotlightline** [comment]
> How much memory / free memory does your system have?
32g

**Comment by anorth** [comment]
Which version of the code are you running?

**Comment by travisperson** [comment]
@hotlightline this is probably related to the PoSt computational memory increase we are seeing right now.

I just filed an issue to track this on Github https://github.com/filecoin-project/go-filecoin/issues/3274

**Comment by anorth** [comment]
Closing this as we expect the next user devnet release to solve this. Please re-open if it doesn't
