### ISSUE TITLE
Failure to initialise sector builder, missing parameters file

### ISSUE THREAD

**Issue by muronglaowang** [filecoin-project/go-filecoin#3266]
go-filecoin mining start --repodir=/fil/f 

Error: failed to initialize sector builder: failed to initialize sector builder for miner t2ypjs25gd54qubavffobwndfwalmm53vupwcm2uy: missing verifying key for PoSt: ErrorMessage { msg: "Failed to stat: /var/tmp/filecoin-proof-parameters/v11-vdf-post-fcc91dc272c9e6dfc906ff56cf65c412340b02fdef60b8132610bbe1dce61b20.vk" }

**Comment by hotlightline** [comment]
> go-filecoin mining start --repodir=/fil/f
> 
> Error: failed to initialize sector builder: failed to initialize sector builder for miner t2ypjs25gd54qubavffobwndfwalmm53vupwcm2uy: missing verifying key for PoSt: ErrorMessage { msg: "Failed to stat: /var/tmp/filecoin-proof-parameters/v11-vdf-post-fcc91dc272c9e6dfc906ff56cf65c412340b02fdef60b8132610bbe1dce61b20.vk" }

me too

**Comment by AsherHuu** [comment]
Error: failed to initialize sector builder: failed to initialize sector builder for miner t2rcfyruzavhjxqks3fjetxk5psc7pfd3p73rcqta: missing verifying key for PoSt: ErrorMessage { msg: "Failed to stat: /var/tmp/filecoin-proof-parameters/v11-vdf-post-fcc91dc272c9e6dfc906ff56cf65c412340b02fdef60b8132610bbe1dce61b20.vk" }

**Comment by anorth** [comment]
@icorderi I think the documentation is missing following from https://github.com/filecoin-project/go-filecoin/pull/3252. I expect https://github.com/filecoin-project/go-filecoin/wiki/Mining-Filecoin to have instructions for fetching the proving parameter for the 256MiB sector. Could you please update it?

Try `proofs/bin/paramfetch -j proofs/misc/parameters.json -z 1024,268435456`. 

FYI @laser  @porcuquine

**Comment by icorderi** [comment]
The mining [documentation](https://github.com/filecoin-project/go-filecoin/wiki/Mining-Filecoin#start-mining) has been updated.

Please let us know if run into further issues.
