### ISSUE TITLE
[bug] PoSt construction memory requirements increased substantially

### ISSUE THREAD

**Issue by travisperson** [filecoin-project/go-filecoin#3274]
This is a tracking issue for the increased reosurce requirements for PoSt computation.

------------------------------
https://filecoinproject.slack.com/archives/CLYN768T1/p1566435768079700

We have discovered that PoSt computation requires memory proportional to sector size * `POST_SECTORS_COUNT`, which for this release was increased from 2 to 512 in order to reduce PoSt generation latency. The memory use is independent of the number of sectors actually being proven. This makes PoSt generation untenable on most hardware. laser is going to do some quick benchmarks to find the highest `POST_SECTORS_COUNT` that keeps memory requirements reasonable and also determine whether that delivers the latency improvements of a value of 2.

We expect to settle on a new number within 24 hours and then redeploy staging yet again. At this point, it makes release to the user devnet likely to take place at the beginning of next week.

**Comment by anorth** [comment]
Fixed upstream by setting POST_SECTORS_COUNT to a lower value (I think it was 4)
