### ISSUE TITLE
when I tested filecoin-staging-devnet-0.4.4,It appears when you initialize it,When I downloaded the source file, I reported 502 bad getway

### ISSUE THREAD

**Issue by muronglaowang** [filecoin-project/go-filecoin#3279]
Error: Get https://genesis.staging.kittyhawk.wtf/genesis.car: dial tcp 3.223.14.65:443: i/o timeout

**Comment by OdysLam** [comment]
I too get a `Error: Could not Init Node: link value was empty`, any idea?

**Comment by muronglaowang** [comment]
> I too get a `Error: Could not Init Node: link value was empty`, any idea?

You performed the initialization command incorrectly

**Comment by OdysLam** [comment]
@muronglaowang I performed the steps as instructed in the docs. 

Should I upgrade to 0.4.5?

**Comment by OdysLam** [comment]
I repeated the steps listed [here](https://github.com/filecoin-project/go-filecoin/wiki/Getting-Started) with filecoin 0.4.5 but I got the same error when initializing the client with `
go-filecoin init --devnet-user --genesisfile=https://genesis.user.kittyhawk.wtf/genesis.car
`

**Comment by muronglaowang** [comment]
> I repeated the steps listed [here](https://github.com/filecoin-project/go-filecoin/wiki/Getting-Started) with filecoin 0.4.5 but I got the same error when initializing the client with `go-filecoin init --devnet-user --genesisfile=https://genesis.user.kittyhawk.wtf/genesis.car`

You should use this command ：go-filecoin init --devnet-staging --genesisfile=https://genesis.staging.kittyhawk.wtf/genesis.car

**Comment by OdysLam** [comment]
I feel kinda ashamed, as soon as I posted the previous response, I tried what you suggested. 

Any idea on how long the staging phase will last? 

When we change to stable version, will the parameters remain the same or I will have to redownload using the `paramfetch`?

Thanks for your swift response and for your time :)

**Comment by muronglaowang** [comment]
> I feel kinda ashamed, as soon as I posted the previous response, I tried what you suggested.
> 
> Any idea on how long the staging phase will last?
> 
> When we change to stable version, will the parameters remain the same or I will have to redownload using the `paramfetch`?
> 
> Thanks for your swift response and for your time :)
According to my test, you don't need to modify this file。I'm glad to discuss these issues with you，Knowledge is meant to be Shared。

**Comment by anorth** [comment]
I don't expect you'll need to re-download parameters after you have fetched them for 0.4.5.
