### ISSUE TITLE
[bug] Error: failed to get key from keystore: no key by the given name was found

### ISSUE THREAD

**Issue by OdysLam** [filecoin-project/go-filecoin#3290]
**Describe the bug**

When starting the go-filecoin daemon, I get the following error:
I have downloaded the gen file and completed ./paramfetch.
Error: failed to get key from keystore: no key by the given name was found`

**Version information**
Filecoin staging 0.4.4, Ubuntu

I used to run the previous stable version but I kept getting a "short buffer" error when attempting to communicate with other peers, so I figured I needed to update my filecoin version. At what version can we participate in the network so as to develop on top of it?

Should I update to 0.4.5 (released only hours after I downloaded 0.4.4)

Thanks!

**Comment by anorth** [comment]
Neither of the 0.4 versions have been released to the user devnet yet. We welcome testing on the staging devnet, but if you'd rather just use some software that more-or-less works, wait for the 0.4 release to be completed.

**Comment by OdysLam** [comment]
Do we have any ETA for the 0.4? 

What I actually need is a semi stable network to test out commands and develop around the filecoin client. More specifically I want to create a simple RESTful client that can store & retrieve files from the network.

Currently I am trying to sync my nodes (client - miner) to the network so I can start testing.

Cheers and thank you for your time :)

**Comment by anorth** [comment]
0.4.6 has now been released to the user devnet, so it is very likely a safe target for the next month or so.

https://github.com/filecoin-project/go-filecoin/issues/3157

You may also be interested in following the new HTTP API currently in design: #3098
