### ISSUE TITLE
Sign blocks with miner worker key

### ISSUE THREAD

**Issue by frrist** [filecoin-project/go-filecoin#3293]
### Description
As defined in the [data-structures](https://github.com/filecoin-project/specs/blob/master/data-structures.md#block) portion of the spec, blocks should contain a signature calculated over the hash of the entire block using the miners worker key to ensure that the block is not tampered with after creation.

See https://github.com/filecoin-project/specs/issues/457

### Acceptance criteria
- blocks are signed using the miners worker key. The signature is calculated over the hash of the entire block.

### Where to begin
https://github.com/filecoin-project/go-filecoin/blob/master/types/block.go

**Comment by anorth** [comment]
FYI @ZenGround0 this is probably part of your upcoming work.

**Comment by anorth** [comment]
Done
