### ISSUE TITLE
[bug]can't fetching: v11-vdf-post-6142c5095dcab8adf8698aaea24eac78035e3fefe6503b3e2f80758e4c948639.params

### ISSUE THREAD

**Issue by hlb168** [filecoin-project/go-filecoin#3295]
fetching: v11-vdf-post-6142c5095dcab8adf8698aaea24eac78035e3fefe6503b3e2f80758e4c948639.params
downloading file... ok

fetching: v11-vdf-post-6142c5095dcab8adf8698aaea24eac78035e3fefe6503b3e2f80758e4c948639.vk
downloading file... 02:55:59.508 ERROR     flatfs: too many open files, retrying in 100ms flatfs.go:373
02:55:59.616 ERROR     flatfs: too many open files, retrying in 200ms flatfs.go:373
02:55:59.687 ERROR     flatfs: too many open files, retrying in 100ms flatfs.go:373
02:55:59.787 ERROR     flatfs: too many open files, retrying in 200ms flatfs.go:373
02:55:59.817 ERROR     flatfs: too many open files, retrying in 300ms flatfs.go:373
02:56:00.017 ERROR     flatfs: too many open files, retrying in 300ms flatfs.go:373
02:56:00.117 ERROR     flatfs: too many open files, retrying in 400ms flatfs.go:373
02:56:00.318 ERROR     flatfs: too many open files, retrying in 400ms flatfs.go:373
02:56:00.518 ERROR     flatfs: too many open files, retrying in 500ms flatfs.go:373
02:56:00.718 ERROR     flatfs: too many open files, retrying in 500ms flatfs.go:373
02:56:04.091 ERROR     flatfs: too many open files, retrying in 100ms flatfs.go:373
02:56:04.192 ERROR     flatfs: too many open files, retrying in 200ms flatfs.go:373
02:56:04.272 ERROR     flatfs: too many open files, retrying in 100ms flatfs.go:373
02:56:04.372 ERROR     flatfs: too many open files, retrying in 200ms flatfs.go:373
02:56:04.393 ERROR     flatfs: too many open files, retrying in 300ms flatfs.go:373
02:56:04.586 ERROR     flatfs: too many open files, retrying in 100ms flatfs.go:373
02:57:02.791 ERROR     flatfs: too many open files, retrying in 100ms flatfs.go:373
02:57:02.892 ERROR     flatfs: too many open files, retrying in 200ms flatfs.go:373
02:57:03.098 ERROR     flatfs: too many open files, retrying in 100ms flatfs.go:373
02:57:03.104 ERROR     flatfs: too many open files, retrying in 300ms flatfs.go:373
02:57:03.161 ERROR       mdns: mdns lookup error:  failed to bind to any unicast udp port mdns.go:139
02:57:03.198 ERROR     flatfs: too many open files, retrying in 200ms flatfs.go:373
02:57:03.262 ERROR     flatfs: too many open files, retrying in 100ms flatfs.go:373
02:57:03.362 ERROR     flatfs: too many open files, retrying in 200ms flatfs.go:373
02:57:03.444 ERROR     flatfs: too many open files, retrying in 100ms flatfs.go:373
02:57:03.545 ERROR     flatfs: too many open files, retrying in 200ms flatfs.go:373
02:57:03.563 ERROR     flatfs: too many open files, retrying in 300ms flatfs.go:373
02:57:03.745 ERROR     flatfs: too many open files, retrying in 300ms flatfs.go:373
02:57:03.864 ERROR     flatfs: too many open files, retrying in 400ms flatfs.go:373
02:57:04.057 ERROR     flatfs: too many open files, retrying in 400ms flatfs.go:373
02:57:04.266 ERROR     flatfs: too many open files, retrying in 500ms flatfs.go:373
02:57:04.465 ERROR     flatfs: too many open files, retrying in 500ms flatfs.go:373
02:57:04.766 ERROR     flatfs: too many open files, retrying in 600ms flatfs.go:373
02:57:04.965 ERROR     flatfs: too many open files, retrying in 600ms flatfs.go:373
02:57:05.040 ERROR     flatfs: too many open files, retrying in 100ms flatfs.go:373
02:57:05.452 ERROR     flatfs: too many open files, retrying in 100ms flatfs.go:373
02:57:05.624 ERROR     flatfs: too many open files, retrying in 100ms flatfs.go:373
02:57:05.724 ERROR     flatfs: too many open files, retrying in 200ms flatfs.go:373
02:57:05.924 ERROR     flatfs: too many open files, retrying in 300ms flatfs.go:373
02:57:05.935 ERROR     flatfs: too many open files, retrying in 100ms flatfs.go:373
02:57:05.989 ERROR     flatfs: too many open files, retrying in 100ms flatfs.go:373
02:57:06.089 ERROR     flatfs: too many open files, retrying in 200ms flatfs.go:373
02:57:06.290 ERROR     flatfs: too many open files, retrying in 300ms flatfs.go:373
02:57:08.506 ERROR     flatfs: too many open files, retrying in 100ms flatfs.go:373
02:57:08.506 ERROR     flatfs: too many open files, retrying in 400ms flatfs.go:373
02:57:08.906 ERROR     flatfs: too many open files, retrying in 500ms flatfs.go:373
02:57:09.711 ERROR     flatfs: too many open files, retrying in 100ms flatfs.go:373
02:57:09.732 ERROR     flatfs: too many open files, retrying in 100ms flatfs.go:373
02:57:09.811 ERROR     flatfs: too many open files, retrying in 200ms flatfs.go:373
02:57:09.833 ERROR     flatfs: too many open files, retrying in 200ms flatfs.go:373
02:57:09.892 ERROR     flatfs: too many open files, retrying in 100ms flatfs.go:373
02:57:10.430 ERROR     flatfs: too many open files, retrying in 100ms flatfs.go:373
02:57:10.622 ERROR     flatfs: too many open files, retrying in 100ms flatfs.go:373
02:57:10.727 ERROR     flatfs: too many open files, retrying in 200ms flatfs.go:373
02:57:10.822 ERROR     flatfs: too many open files, retrying in 100ms flatfs.go:373
02:57:11.029 ERROR     flatfs: too many open files, retrying in 100ms flatfs.go:373
02:57:11.130 ERROR     flatfs: too many open files, retrying in 200ms flatfs.go:373
02:57:11.330 ERROR     flatfs: too many open files, retrying in 300ms flatfs.go:373
02:57:11.585 ERROR     flatfs: too many open files, retrying in 100ms flatfs.go:373
02:57:11.630 ERROR     flatfs: too many open files, retrying in 400ms flatfs.go:373
02:57:11.686 ERROR     flatfs: too many open files, retrying in 200ms flatfs.go:373
02:57:11.764 ERROR     flatfs: too many open files, retrying in 100ms flatfs.go:373
02:57:11.864 ERROR     flatfs: too many open files, retrying in 200ms flatfs.go:373
02:57:11.894 ERROR     flatfs: too many open files, retrying in 300ms flatfs.go:373
02:57:11.942 ERROR     flatfs: too many open files, retrying in 100ms flatfs.go:373
02:57:12.031 ERROR     flatfs: too many open files, retrying in 500ms flatfs.go:373
02:57:12.043 ERROR     flatfs: too many open files, retrying in 200ms flatfs.go:373
02:57:12.064 ERROR     flatfs: too many open files, retrying in 300ms flatfs.go:373
02:57:12.127 ERROR     flatfs: too many open files, retrying in 100ms flatfs.go:373
02:57:12.274 ERROR     flatfs: too many open files, retrying in 300ms flatfs.go:373
02:57:12.324 ERROR     flatfs: too many open files, retrying in 100ms flatfs.go:373
02:57:12.365 ERROR     flatfs: too many open files, retrying in 400ms flatfs.go:373
02:57:12.424 ERROR     flatfs: too many open files, retrying in 200ms flatfs.go:373
02:57:12.531 ERROR     flatfs: too many open files, retrying in 600ms flatfs.go:373
02:57:12.575 ERROR     flatfs: too many open files, retrying in 400ms flatfs.go:373
02:57:12.625 ERROR     flatfs: too many open files, retrying in 300ms flatfs.go:373
02:57:12.699 ERROR     flatfs: too many open files, retrying in 100ms flatfs.go:373
02:57:12.770 ERROR     flatfs: too many open files, retrying in 500ms flatfs.go:373
02:57:12.802 ERROR     flatfs: too many open files, retrying in 200ms flatfs.go:373
02:57:12.925 ERROR     flatfs: too many open files, retrying in 400ms flatfs.go:373
02:57:13.161 ERROR       mdns: mdns lookup error:  failed to bind to any unicast udp port mdns.go:139
02:57:13.271 ERROR     flatfs: too many open files, retrying in 600ms flatfs.go:373
02:57:13.325 ERROR     flatfs: too many open files, retrying in 500ms flatfs.go:373
02:57:13.332 ERROR     flatfs: too many open files, retrying in 100ms flatfs.go:373
02:57:13.433 ERROR     flatfs: too many open files, retrying in 200ms flatfs.go:373
02:57:13.633 ERROR     flatfs: too many open files, retrying in 300ms flatfs.go:373
02:57:13.828 ERROR     flatfs: too many open files, retrying in 600ms flatfs.go:373
02:57:13.933 ERROR     flatfs: too many open files, retrying in 400ms flatfs.go:373
02:57:14.087 ERROR     flatfs: too many open files, retrying in 100ms flatfs.go:373
02:57:14.334 ERROR     flatfs: too many open files, retrying in 500ms flatfs.go:373
02:57:14.629 ERROR     flatfs: too many open files, retrying in 100ms flatfs.go:373
02:57:14.730 ERROR     flatfs: too many open files, retrying in 200ms flatfs.go:373
02:57:14.839 ERROR     flatfs: too many open files, retrying in 600ms flatfs.go:373
02:57:14.930 ERROR     flatfs: too many open files, retrying in 300ms flatfs.go:373
02:57:14.933 ERROR     flatfs: too many open files, retrying in 100ms flatfs.go:373
02:57:15.034 ERROR     flatfs: too many open files, retrying in 200ms flatfs.go:373
02:57:15.114 ERROR     flatfs: too many open files, retrying in 100ms flatfs.go:373
02:57:15.281 ERROR     flatfs: too many open files, retrying in 300ms flatfs.go:373
02:57:15.290 ERROR     flatfs: too many open files, retrying in 100ms flatfs.go:373
02:57:15.294 ERROR     flatfs: too many open files, retrying in 100ms flatfs.go:373
02:57:15.391 ERROR     flatfs: too many open files, retrying in 200ms flatfs.go:373
02:57:15.394 ERROR     flatfs: too many open files, retrying in 200ms flatfs.go:373
02:57:15.473 ERROR     flatfs: too many open files, retrying in 100ms flatfs.go:373

**Comment by anorth** [comment]
I think we'll replace fetching params with generating them for the next release.
