### ISSUE TITLE
[bug]`client propose-storage-deal` always get Error

### ISSUE THREAD

**Issue by deaswang** [filecoin-project/go-filecoin#3296]
**Describe the bug**
`go-filecoin client propose-storage-deal --allow-duplicates --repodir=~/.filecoin2 <miner> <data> <ask> <duration>` always get `Error: error creating payment: context deadline exceeded`

**To Reproduce**
1. Start two node, one as miner, another as client.
2. import data into the client node.
3. Propose a storage deal by client node `go-filecoin client propose-storage-deal --allow-duplicates --repodir=~/.filecoin2 <miner> <data> <ask> <duration>` duration is less than miner Expiry.
4. Always get the response `Error: error creating payment: context deadline exceeded`

**Expected behavior**
it will automatically be accepted and return Status: accepted. 

**Version information**
- Go: go1.12.7
- Rust: 1.36.0
- Cargo: 1.36.0
- Commit: 0.4.6

**Comment by OdysLam** [comment]
I am having this issue as well, currently running devnet 0.4.6
