### ISSUE TITLE
[bug] Repeatedly panic when verify seal - 0.4.6

### ISSUE THREAD

**Issue by merced** [filecoin-project/go-filecoin#3306]
Please see details as below. restart go-filecoin will recover to normal, panic again after running for a while.

thread '<unnamed>' panicked at 'assertion failed: step != 0', src/libcore/iter/adapters/mod.rs:412:9
stack backtrace:
   0:           0xea4b8b - backtrace::backtrace::libunwind::trace::h5bc0bbbec4785b9a
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/libunwind.rs:88
   1:           0xea4b8b - backtrace::backtrace::trace_unsynchronized::hf4cf55203265c51b
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/mod.rs:66
   2:           0xea4b8b - std::sys_common::backtrace::_print::h7f21be6b8a753a13
                               at src/libstd/sys_common/backtrace.rs:47
   3:           0xea4b8b - std::sys_common::backtrace::print::hbd10ca8c5a66607b
                               at src/libstd/sys_common/backtrace.rs:36
   4:           0xea4b8b - std::panicking::default_hook::{{closure}}::h1fbeb43ccddede95
                               at src/libstd/panicking.rs:200
   5:           0xea4866 - std::panicking::default_hook::hb56e8fead4dc563f
                               at src/libstd/panicking.rs:214
   6:           0xea52fd - std::panicking::rust_panic_with_hook::h34de78ee1c6d2416
                               at src/libstd/panicking.rs:477
   7:           0xea4e82 - std::panicking::continue_panic_fmt::hd2fe7034954bd46f
                                at src/libstd/panicking.rs:214
   6:           0xea52fd - std::panicking::rust_panic_with_hook::h34de78ee1c6d2416
                               at src/libstd/panicking.rs:477
   7:           0xea4e82 - std::panicking::continue_panic_fmt::hd2fe7034954bd46f
                               at src/libstd/panicking.rs:384
   8:           0xea4d66 - rust_begin_unwind
                               at src/libstd/panicking.rs:311
   9:           0xecd8ad - core::panicking::panic_fmt::h2a1c3e0b75609829
                               at src/libcore/panicking.rs:85
  10:           0xecd7ec - core::panicking::panic::h84748aa3e150058d
                               at src/libcore/panicking.rs:49
  11:           0xff7313 - filecoin_proofs_ffi::helpers::into_proof_vecs::h9bebb4ea04e87865
  12:           0xff6ae6 - filecoin_proofs_ffi::helpers::try_into_porep_proof_bytes::h3f00a944b51e5e2e
  13:           0xfe7369 - verify_seal
  14:           0xe0af81 - _cgo_f88249eab97c_Cfunc_sector_builder_ffi_verify_seal
                               at /tmp/go-build/cgo-gcc-prolog:473
  15:           0x534b70 - runtime.asmcgocall
                               at /usr/local/go/src/runtime/asm_amd64.s:635
fatal runtime error: failed to initiate panic, error 5
SIGABRT: abort
PC=0x7f74771f6e97 m=16 sigcode=18446744073709551610

**Comment by anorth** [comment]
Could you please share more information about your system, as requested in the bug template?

**Comment by iMiamasJohano** [comment]
i got the same proble

**Comment by travisperson** [comment]
I tried to gather this information async by starting a new node and having it sync the chain. I was hoping this would be a rather consistent failure and we'd see it panic while verifying a sector at a particular block height. However, I wasn't able to get this to occur. I'll dig into the logs we have an see if I can pick out the block that may of triggered this.

**Comment by embedSky** [comment]
I am runing at staging-0.4.7  version:62110fcdaabaeffa0c8491af07ee52b9f5faaae2
I also occur it
OS info
```
Operating System: Ubuntu 18.04.2 LTS
            Kernel: Linux 4.15.0-58-generic
      Architecture: x86-64
 

```
