### ISSUE TITLE
[bug] determined miner actor address - preLaunch mining attack

### ISSUE THREAD

**Issue by steven004** [filecoin-project/go-filecoin#3308]
**Describe the bug**
In the current implementation (as of 0.4.6), the miner actor address creation depends on the creator address and its message nonce. See [the code here](https://github.com/filecoin-project/go-filecoin/blob/master/vm/context.go#L162). 
Since an owner (wallet) address could be generated or imported, and the nonce itself could be anticipated, one could use a specific address and send createStorageMiner message at the specific nonce time to create a determined miner actor address. 

The problem of a determined miner actor address is: one could prepare storage power before network launch, because the sector proofs only depend on content of data, miner actor address, sectorID, parameters. Yes, this is pre-launch mining attack. 

**Expected behavior**
A miner actor address should not be determined, even other parameters are the same. That means, a verifiable randomness should be introduced for a miner address creation process.

**Version information**
go-filecoin use-devnet 0.4.6

**Additional context**
See some discussion [here](https://app.slack.com/client/TEHTVS1L6/CEHHJNJS3/thread/CEHHJNJS3-1566902398.098900)

**Comment by anorth** [comment]
@whyrusleeping @sternhenri could you comment on whether this is as it sounds? It probably needs to be addressed at the spec level.

**Comment by whyrusleeping** [comment]
You can precompute your miner address, but you can't precompute the chain randomness that is an input into sealing and PoSt.

This is probably a bug in the current go-filecoin if seals do not take in chain randomness, but as far as I know this is handled by the seal construction

**Comment by steven004** [comment]
@whyrusleeping , No, the current sealing process does not take any chain randomness. As I mentioned, only content of data ingested into a sector, minerAddress, sectorID and parameters are used, I believe.

**Comment by anorth** [comment]
Ok. @dignifiedquire @porcuquine we probably need this in the proofs FFI. Is this already part of the upcoming Rational PoSt implementation?

**Comment by porcuquine** [comment]
@laser — what's the status of this? I remember we discussed this in London and that @sternhenri gave some input. My assumption then was that this would be facilitated by API changes related to PoSt. The issue is here: https://github.com/filecoin-project/specs/issues/56

**Comment by sternhenri** [comment]
It’s stuck on me specing right now. Can prioriti: if blocking.

**Comment by dignifiedquire** [comment]
This is not part of the upcoming api changes, as the spec is not clearly defined on this. We should be able to include it __iff__ we have a spec and it is clear how to implement.

**Comment by anorth** [comment]
Obsolete (sealing now includes unpredictable chain randomness)
