### ISSUE TITLE
Message Syntax/Semantics Validation in fetcher

### ISSUE THREAD

**Issue by hannahhoward** [filecoin-project/go-filecoin#3312]
### Description

This is a place holder issue for defining what we want to validate about message / message receipt syntax and semantics. As part of #3232 we're defining an interface for doing syntax validation. This issue is to discuss what should be validated about the syntax, and if a semantic validator should also be build

### Acceptance criteria

TBD -- this is for discussion

### Where to begin

This issue needs further definition before it's actionable so the first place is to define what should be validated

**Comment by anorth** [comment]
This question should be answered in the spec before we can write much useful code. I've filed https://github.com/filecoin-project/specs/issues/464

**Comment by anorth** [comment]
There is no longer any message semantic validation (until execution), but we still need syntax validation.

**Comment by anorth** [comment]
Just a thought, maybe graphsync shouldn't do message sytax validation, b/c if it does then the messages won't be available to block syntax validation.
