### ISSUE TITLE
[bug]  PoSt proof is not working properly - 0.4.6

### ISSUE THREAD

**Issue by diwufeiwen** [filecoin-project/go-filecoin#3315]
Describe the bug
(1)When the new block height enters the certification period (start,end], it does not start PoSt. After restarting the service, the PoSt will start..
(2) After the end of a PoSt certificate, the next proof period (start,end] will not change.
(3) After the end of a PoSt certificate, the miner power does not increase.

To Reproduce
submitPoSt start:start-1691,end-2691,postInProcess:2691,newBh-2079,inputs:10...
generate_post_dynamic end...
Submit PoSt Success,ProvingPeriodEnd=2513
submitPoSt gap:start-1691,end-2691,inputs:10......

Version information
Release: 0.4.6

**Comment by anorth** [comment]
I saw this failed message, possibly related.

@diwufeiwen can you provide the addresses of the miner actor and worker with which you are experiencing this problem?

```
15:57:19.617  INFO consensus.: ApplyMessage failed: failed to verify PoSt: LEN(proofs) must == CEIL(LEN(comm_rs)/POST_SECTORS_COUNT): 193, 218 SignedMessage cid=[bafy2bzacecjhyz354nxrc4ls6ainxonxda5etfvjc355zdcyi77lnpuay6q64]: {
  "meteredMessage": {
    "message": {
      "to": "t2usk2yzfu23uq2wyuc3w6ov233nxyhkysju2suba",
      "from": "t174be76nirx7ozwxccgnlvqhiibk3vot4d5dd5ky",
      "nonce": "2020",
      "value": "0",
      "method": "submitPoSt",
...
```

**Comment by diwufeiwen** [comment]
@anorth 
miner : t2hy7kxaarkrxcuxm4ga7gly3up2jixszec6za34i
peer ID : QmNj5EFPK7XVmDr1fkF1tCLMTZWfoj1rCDxcb8hvfezm7S
