### ISSUE TITLE
PeerTracker uses hello protocol as heartbeat-like service

### ISSUE THREAD

**Issue by frrist** [filecoin-project/go-filecoin#3319]
### Description
This issue proposes a partial solution to #2674 until a full design is agreed upon.
___

We have opted to disable the block pubsub topic until a node has synced its chain to a fully caught-up state. Due to this decision we must rely on the messages we receive from the hello protocol to know the current state of the network. Since there is no guarantee that these messages will continue to arrive as the network grows we need a way to trigger nodes to send a hello message upon our request. 

Ways to accomplish this without changing the bits of the protocol message:
1. Bounce our libp2p connection with a peer (i.e. disconnect & connect), this works because of the [notify interface](https://github.com/filecoin-project/go-filecoin/blob/master/protocol/hello/hello.go#L174).
2. Ensure we have sent the same number of hello messages to a peer as we have received from them.

Both of these methods are an abuse of the hello protocol. I would argue that 2. is the lesser of the two and the one we should implement. 

The PeerTracker tracker currently tracks peers a node has received a hello message from via a hello protocol callback. The tracker should be extended to periodically issue hello messages to its peers to keep its state up to date. We can then compare the best head the tracker has with our own to determine if we are in a caught up state.

### Acceptance criteria
- The PeerTracker is capable of sending a hello message to some peer.
- The PeerTracker ensures it has sent the same number of hello messages it has received from each peer.
- The PeerTracker has a method that returns the highest head it knows about.

### Risks + pitfalls
- Avoid entering a hello loop

**Comment by anorth** [comment]
This sounds good. Optionally, the set of peers that a repeated hello message is sent to could be limited to a configured trusted set (i.e. those nodes already specified in the config file).

**Comment by anorth** [comment]
On more reflection (and current devnet woes) I think the re-hello *should* be limited to trusted peer set for now. We should set the trust flag directly from membership in that set.

**Comment by frrist** [comment]
addressed via #3327
