### ISSUE TITLE
First time running go-filecoin daemon, errors?

### ISSUE THREAD

**Issue by birdmanscn** [filecoin-project/go-filecoin#3324]
### Description
First time running go-filecoin daemon. It's been running over 24 hrs. Not sure whether it's running successfully or not, it shows a lot of WARNI.

And I tried to move forward as instructed, but gave me error when running go-filecoin in another terminal like this:

~/filecoin$ go-filecoin swarm peers
go-filecoin: command not found
~/filecoin$ go-filecoin ping <QmUV4cCb4a1JNyWiCY4uEyV5Fmr7gbZWpmnH3ptvsHLT5j>
bash: syntax error near unexpected token `newline'

Thank you very much!

**Comment by birdmanscn** [comment]
add path and solved

**Comment by renjun868** [comment]
what do you mean add path? I have the same problem please help
