### ISSUE TITLE
The node structure should contain the clock interface

### ISSUE THREAD

**Issue by frrist** [filecoin-project/go-filecoin#3337]
### Description
The node structure should be modified to contain the [clock interface](https://github.com/filecoin-project/go-filecoin/blob/989cb180995fe637d31bef6100c4d33be5a90877/clock/clock.go#L9). When starting a real filecoin node the value may contain the [`SystemClock`](https://github.com/filecoin-project/go-filecoin/blob/989cb180995fe637d31bef6100c4d33be5a90877/clock/clock.go#L17), when running a node in process the value may contain the [`FakeClock`](https://github.com/filecoin-project/go-filecoin/blob/master/testhelpers/clock.go#L15), or any other yet-to-come interface implementation. This will provide more control over how the node behaves wrt time during in process testing.

### Acceptance criteria
- Node structure contains a clock interface.
- Filecoin nodes started normally us the SystemClock.

### Related
This does not invalidate https://github.com/filecoin-project/go-filecoin/issues/2961 since some things are on both the node and porcelain (e.g. wallet).

The need for this surfaced during work for #3330 which will need to perform some [polling on the peer trackers](https://github.com/filecoin-project/go-filecoin/pull/3330/files#diff-380e79adccbaf1276bf6c91cc551cd7fR614) head in order to determine chain syncing state.

**Comment by anorth** [comment]
Excellent idea

**Comment by frrist** [comment]
Of the clock implementations that exists in go, [github.com/jonboulle/clockwork](https://github.com/jonboulle/clockwork) appears to be the most popular.  Would you be open to wrapping it with our SystemClock and FakeClock implementation?
