### ISSUE TITLE
Repeated seal-now does not increase power

### ISSUE THREAD

**Issue by travisperson** [filecoin-project/go-filecoin#3344]
**Describe the bug**:

The `mining seal-now` command can only seal a sector once.

```
localnet -miner-count 0 -shell
```

Wait for shell

```
go-filecoin miner create --gas-price 0.0001 --gas-limit 1000 10
go-filecoin mining start
go-filecoin mining seal-now
```

After a little while you can check with `go-filecoin mining status` and see the power increase to `1024`, and the sector set increase by one. After this, any call to `go-filecoin mining seal-now` does not result in a new sector.

**Expected behavior**:

Each call to `go-filecoin mining seal-now` should result in a power increase of the miner.

**Diagnostic information:**

- Filecoin Version: 0.4.6 (83becde01402803454b43ea75c77364d13e28564 base commit)
- Filecoin Inspect Output:
```

Version:	73a96fd7cfd883fe907f0f6ecb4d67dbafdd57ba

Runtime
OS:           	linux
Arch:         	amd64
Version:      	go1.12.1
Compiler:     	gc
NumProc:      	8
GoMaxProcs:   	8
NumGoRoutines:	125
NumCGoCalls:  	620

Disk
Free:  	8092106752
Total: 	8092106752
FSType:	16914836

Memory
Swap:   	0
Virtual:	15415152000

Environment
FilAPI: 	
FilPath:	/tmp/localnet469245147/1/repo
GoPath: 	/home/travis
```

**Comment by acruikshank** [comment]
@travisperson The behavior you are seeing is actually expected. After the first seal-now, the miner has no committed sectors. Adding the first committed sector triggers the start of a new proving period. This causes the miner to submit a PoSt and gain power. Every sector committed after that will be tracked by the miner, but won't enter its proving set and won't give it power until the start of the next proving period.

The proving period is currently fixed at 1,000 blocks, which should be around 8 hours. After this you should see an increase in power for all the sectors you have committed. So, to test whether add-piecce/seal-now work for more than one sector using power, you need to wait for a proving period to end.

We lack the tools on the command like to easily confirm that seal-now is doing what it is supposed to. The easiest way to confirm it is to check the number of committedSectors the miner possesses. This would involve adding another method to the actor and a command to query it. We really should just expose the query interface as a plumbing command for these types of use cases.

**Comment by travisperson** [comment]
Ah right. So unfortunately we currently don't have a good way to show the failure at the moment.

**Comment by anorth** [comment]
Note that the functionality also changed slightly in #3263 such that `seal-now` won't implicitly open a new sector unless a piece is added to it. This just makes the opacity problem even more pressing, though.

**Comment by anorth** [comment]
@travisperson I think we can either close this, or rename and repurpose to be about exposing sector and seal information.
