### ISSUE TITLE
Should TipSet methods return errors?

### ISSUE THREAD

**Issue by frrist** [filecoin-project/go-filecoin#3346]
### Description
The methods on [TipSet](https://github.com/filecoin-project/go-filecoin/blob/master/types/tipset.go) can be broken up into 3 categories, those that return a value, return a value and an error, return a value or panic. 
```go
type TipSet struct {
	// This slice is wrapped in a struct to enforce immutability.
	blocks []*Block
	// Key is computed at construction and cached.
	key TipSetKey
}
```
```go
  // return value
	Defined() bool
	Equals(ts2 TipSet) bool
	Key() TipSetKey
	Len() int
	String() string
	ToSlice() []*Block
  // return value and error
	Height() (uint64, error)
	MinTicket() (Ticket, error)
	MinTimestamp() (Uint64, error)
	ParentWeight() (uint64, error)
	Parents() (TipSetKey, error)
  // return value or panic
	At(i int) *Block
```
All methods that can return an error return the same error type: `errUndefTipSet`. This error is returned when the TipSet a method is called on does not contain any blocks. The At method will return a block or panic if the TipSet is undefined.

The handling of these error cases increases the verbosity of code working with TipSets. I believe the intention of these errors is to prevent panics when operating on undefined TipSets. Since not all method follow this pattern, such as the At method, we are left with some inconsistencies when working with TipSet. I would like to discuss ways of improving code that operates over TipSets.

A few ideas that come to mind:
#### TipSet becomes an interface:
This will ensure a TipSet can only to be instantiated through its constructor. The constructor method will then handle the cases for invalid TipSet creation by returning an error. 
```go
type TipSet interface {
	At(i int) *Block
	Defined() bool
	Equals(ts2 TipSet) bool
	Height() (uint64, error)
	Key() TipSetKey
	Len() int
	MinTicket() (Ticket, error)
	MinTimestamp() (Uint64, error)
	ParentWeight() (uint64, error)
	Parents() (TipSetKey, error)
	String() string
	ToSlice() []*Block
}

func NewTipSet(blocks ...*Block) (TipSet, error) {
  return tipSet{...}
}

type tipSet struct {
  // This slice is wrapped in a struct to enforce 
  blocks []*
  // Key is computed at construction and 
  key TipSetKey
}
```

#### Don't return errors
Stop returning errors all together (implying panic), if a developer is unsure if a TipSet is defined they may check with the `Defined` method. Code reviewers must be vigilant of any code defining a TipSet like `ts := types.TipSet{}`.

#### Return errors from all methods
All methods that can potentially panic instead return an error. This would mean just modify the `At` method.

#### Change nothing, this is what we want.
Typing `if err != nil {...}` has cathartic properties.

### Acceptance criteria
- We reach a consensus on whether or not the TipSet code should be modified.

**Comment by ZenGround0** [comment]
Woohoo for modifying `At` and keeping everything else the same.

**Comment by anorth** [comment]
The almost-exclusive use of `At` is for iteration in a for loop until `ts.Len()`. Adding an error value and check here will be redundant and verbose (as it would be for a slice indexing op).

An alternative to `At` may to write an iterator object – see the `TipSetKeyIterator` (`TipSetKey` doesn't have `At`). It's still possible to misuse an iterator, by invoking `Value()` after `Complete()` is true. But for similar reasons, returning an error from `Value()` is unpalateable and almost always a complete waste. You might consider that an iterator is less liable to unexpected misuse than `At` though?

**Comment by frrist** [comment]
I didn't mean to make `At` the focus of this, I like (love) that it doesn't return an error. I think using the `Len` or `Defined` methods to ensure a TipSet is valid before calling `At` is fine. 

Ideally we should be creating all TipSets via their constructor, meaning the only way we get an invalid TipSet is by creating one without a constructor or ignoring an error on a method that returns a TipSet and an Error e.g. `FindCommonAncestor`. Both of these things _should_ be caught in code review.

I'd like to focus on ways of making TipSet operations less verbose, a few ideas:

1. Calculating values at time of construction, so basically what we do with Blocks.
This would entail modifying the TipSet struct to contain fields for `Height`, `Parents`, `ParentWeight`, `MinTimestamp`. Methods would just return those values. `MinTicket` would still error since it has some special cases. 

2. Make it impossible to construct an UndefTipSet.
The interface approach described above would make this much harder to do.

Honestly, if we just modified `Height` not to return an error I would be much happier.

**Comment by anorth** [comment]
> Make it impossible to construct an UndefTipSet

We would then hav `nil` instead in places where a tipset is passed but not always available. These are not many, but do exist. Checking for nil is no better, and the error message less informative.

Pre-calculation doesn't answer the question of what height an undefined tipset is...

FYI I sometimes use `At(0).Height` if I know I have a non-empty tipset, but it may well bite me one day when dependant code changes. If we add an error return as @ZenGround0 suggests then this shortcut will become "safe" too.

**Comment by frrist** [comment]
Per an out of band conversation regarding this: The TipSet code will remain unchanged. If there are areas of code where the handling of errors from TipSets is overly verbose a wrapper like [this one](https://gist.github.com/hannahhoward/417d4560d2779635c36f209b79c1681d) may be created and used instead.
