### ISSUE TITLE
Large int slice DOS vulnerability 

### ISSUE THREAD

**Issue by steven004** [filecoin-project/go-filecoin#3349]
**Describe the bug**:
This is a follow-up of the discussion in #3131 . 

In the current PoSt implementation, provingSet and other integer set are represented by a RLE+ format data, which could introduce huge int set via in a short message. This could harm the network before the operation-based gas consuming implementation.  

**Diagnostic information:**
- Filecoin Version: go-filecoin 0.4

**Comment by anorth** [comment]
This has moved to https://github.com/filecoin-project/go-bitfield. I believe that it was addressed in that new code (via `max` parameters). @Kubuxu @whyrusleeping please re-open over there if that's not the case.
