### ISSUE TITLE
Support proposing storage deal for large file

### ISSUE THREAD

**Issue by ridewindx** [filecoin-project/go-filecoin#3351]
## Description

Currently only 254MB piece is supported in storage deal proposal. It would be great that large file can be imported and splitted into small pieces through some dag service, and output all its CIDs.

## Acceptance criteria

- Large file (e.g., 10GB) can be proposed into several storage deals all at once.

**Comment by anorth** [comment]
The current limitation is an artefact of the underlying sector sizes.
- Those sector sizes will be much bigger by the time of mainnet.
- Go-filecoin will not implement "nice to use" client features. The scope and variation of such work is unbounded, and should be built *on top of* go-filecoin (and other implementations)
