### ISSUE TITLE
where is the proofs, which described in wiki page.

### ISSUE THREAD

**Issue by shapengw** [filecoin-project/go-filecoin#3352]
In your wiki page, which described as below :

"[Download the parameters for your sector size (256Mib)](https://github.com/filecoin-project/go-filecoin/wiki/Mining-Filecoin)"

```shell
proofs/bin/paramfetch -j proofs/misc/parameters.json -z 1024,268435456
```

but, where is the proofs/bin?
and, where is the proofs/misc/parameters.json?

**Comment by OdysLam** [comment]
The default method is (I think) to follow the get started walkthrough, it says to simply run ./paramfetch for default settings.

**Comment by travisperson** [comment]
The Mining Filecoin wiki page is written from the perspective of building from source. If you can find more information about how to do that in the project README. You can also download binaries from the github release page which will include the `go-filecoin` and `paramfetch` binaries.

**Comment by swanduron** [comment]
> The Mining Filecoin wiki page is written from the perspective of building from source. If you can find more information about how to do that in the project README. You can also download binaries from the github release page which will include the `go-filecoin` and `paramfetch` binaries.

Hello expert, I have searched all files under GIT master branch and there is no parameters.json file included in the repo. Actually, there is no any json file in this branch.

Could you confirm that step 0 is correct?

`proofs/bin/paramfetch -j proofs/misc/parameters.json -z 1024,268435456`

**Comment by travisperson** [comment]
```
git clone https://github.com/filecoin-project/go-filecoin.git
cd go-filecoin
./scripts/install-rust-fil-proofs.sh
./proofs/bin/paramfetch -j proofs/misc/parameters.json -z 1024,268435456
```

**Comment by shapengw** [comment]
> git clone https://github.com/filecoin-project/go-filecoin.git
> cd go-filecoin
> ./scripts/install-rust-fil-proofs.sh
> ./proofs/bin/paramfetch -j proofs/misc/parameters.json -z 1024,268435456


At the 3rd step,  got below error(I have tried several times, any purge or clean work needed):

```shell
root@skylon:~/gopath/src/github.com/filecoin-project/go-filecoin# ./scripts/install-rust-fil-proofs.sh 
acquiring release @ 037d5fb8f2fad474
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5739  100  5739    0     0   3510      0  0:00:01  0:00:01 --:--:--  3507

gzip: stdin: unexpected end of file
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
root@skylon:~/gopath/src/github.com/filecoin-project/go-filecoin# 
```

at this moment, proofs/bin like below:

```shell
root@skylon:~/gopath/src/github.com/filecoin-project/go-filecoin# ll proofs/bin/
total 8
drwxr-xr-x 2 root root 4096 Sep  6 09:50 .
drwxr-xr-x 8 root root 4096 Sep  6 09:50 ..
-rw-r--r-- 1 root root    0 Sep  6 09:50 .keep
root@skylon:~/gopath/src/github.com/filecoin-project/go-filecoin# 
```

**Comment by IPFS-grandhelmsman** [comment]
> ```shell
> root@skylon:~/gopath/src/github.com/filecoin-project/go-filecoin# ./scripts/install-rust-fil-proofs.sh 
> acquiring release @ 037d5fb8f2fad474
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100  5739  100  5739    0     0   3510      0  0:00:01  0:00:01 --:--:--  3507
> 
> gzip: stdin: unexpected end of file
> tar: Unexpected EOF in archive
> tar: Unexpected EOF in archive
> tar: Error is not recoverable: exiting now
> root@skylon:~/gopath/src/github.com/filecoin-project/go-filecoin# 
> ```
It has been interrupted when downloading the gzip file, you need to remove /tmp/*.tar.gz or reboot the system.
