### ISSUE TITLE
[bug] index out of range when generating new block  to get ancestors

### ISSUE THREAD

**Issue by diwufeiwen** [filecoin-project/go-filecoin#3359]
Describe the bug
panic: runtime error: index out of range

goroutine 42961 [running]:
github.com/filecoin-project/go-filecoin/chain.GetRecentAncestors(0x1c37ac0, 0xc00381a630, 0xc009566af8, 0x1, 0x1, 0xc0253489a0, 0x1, 0x1, 0x1c1b0a0, 0xc00011cea0, ...)
  /root/go/src/github.com/filecoin-project/go-filecoin/chain/get_ancestors.go:61 +0x813
github.com/filecoin-project/go-filecoin/node.(*Node).getAncestors(0xc00000c1e0, 0x1c37ac0, 0xc00381a630, 0xc009566af8, 0x1, 0x1, 0xc0253489a0, 0x1, 0x1, 0xc012b2c4d0, ...)

Release
staging-0.4.7:

**Comment by anorth** [comment]
This sounds like #3027 again. FYI @deaswang @ZenGround0

**Comment by deaswang** [comment]
#3250 should fix it. 
https://github.com/filecoin-project/go-filecoin/blob/ffba133e59e787c7c0d08462f4f4c3911d1177ef/chain/get_ancestors.go#L57-L61
provingPeriodAncestors maybe empty slice.
