### ISSUE TITLE
8G memory and 30G Swap fatal error: runtime: out of memory

### ISSUE THREAD

**Issue by 3684993** [filecoin-project/go-filecoin#3367]
**Describe the bug**:
fatal error: runtime: out of memory

**Expected behavior**:
  Min hardware for storage mining

**Diagnostic information:**
OS: Ubuntu 18.04.2 LTS / 8 GB Memory +8 GB Swap / 3.8 TB Disk /
free -m
                    total        used        free      shared  buff/cache   available
Mem:           7872         263        5710           0        1898        7425
Swap:          7812          42        7770
....
.....
free -g
              -total        used        free      shared  buff/cache   available
Mem:              7           7           0           0           0           0
Swap:            30          30           0

follow the wiki :https://github.com/filecoin-project/go-filecoin/wiki/Getting-Started

- Filecoin Version: https://github.com/filecoin-project/go-filecoin/releases/tag/0.4.6
- Filecoin Inspect Output: 

**Screenshots:**
 go-filecoin daemon

....
....
Swarm listening on: /ip4/127.0.0.1/tcp/6000
Swarm listening on: /ip4/192.168.6.214/tcp/6000
00:57:38.073  INFO chain.stor: start loading chain at tipset: { bafy2bzacec72lgoulyucgvdzmuhfjw7nvnnmozj4nrb22bb4izmaantajt7lw }, **height: 20220** store.go:135
00:57:38.074  INFO chain.stor: load tipset: { bafy2bzacec72lgoulyucgvdzmuhfjw7nvnnmozj4nrb22bb4izmaantajt7lw }, height: 20220 store.go:153
00:58:12.684  INFO chain.stor: load tipset: { bafy2bzacea2slx267jf3vtze7ivmfd4dlmldoyinrc5u3oao2lifpjo2pbqvu }, height: 18198 store.go:153
00:59:04.625  INFO chain.stor: load tipset: { bafy2bzacebcd5mb2gzzs2sha7j6dfci6bt2gvdirkziujozpirsoafqcltkkq }, height: 16176 store.go:153
00:59:39.313  INFO chain.stor: load tipset: { bafy2bzacednnjmqhxgzsbp4bon6wqqp6hxb5jd3iqesq574tb2mbjw4wmfwjc }, height: 14154 store.go:153
01:06:14.427  INFO chain.stor: load tipset: { bafy2bzacecuqozqdw77iydn3vwfxkmdb7con6rl5xm2w2t2f3p5ybttr7fgdg }, height: 2022 store.go:153
01:07:22.221  INFO chain.stor: load tipset: { bafy2bzacecevx2g2fs2lcxknmein52cm2gqocfg7rc2u2dotsyo5r6osgdyy4 }, height: 0 store.go:153
01:07:22.286  INFO chain.stor: finished loading 20220 tipsets from { bafy2bzacec72lgoulyucgvdzmuhfjw7nvnnmozj4nrb22bb4izmaantajt7lw } store.go:179
01:07:33.519  INFO peer-track: Tracking {peer=QmZRnwmCjyNHgeNDiyT8mXRtGhP6uSzgHtrozc42crmVbg height=20307 head={ bafy2bzacebfbs2nlfceveoes5tpu6n3qzm2onuzzyodpljl2wdx63s5e2cc5a }}, new=true, count=1 peer_tracker.go:40
01:07:33.519  INFO net.graphs: fetching initial tipset { bafy2bzacebfbs2nlfceveoes5tpu6n3qzm2onuzzyodpljl2wdx63s5e2cc5a } from peer QmZRnwmCjyNHgeNDiyT8mXRtGhP6uSzgHtrozc42crmVbg graphsync_fetcher.go:117
01:07:34.019  INFO peer-track: Tracking {peer=QmZRnwmCjyNHgeNDiyT8mXRtGhP6uSzgHtrozc42crmVbg height=20307 head={ bafy2bzacebfbs2nlfceveoes5tpu6n3qzm2onuzzyodpljl2wdx63s5e2cc5a }}, new=false, count=1 peer_tracker.go:40
.....
.....
01:32:25.099  INFO peer-track: Dropping peer QmQZY6XBg753XW39RMCQS3Pa4tYFBvEeU35xaWHHFsP19p peer_tracker.go:67
**fatal error: runtime: out of memory**

runtime stack:
runtime.throw(0x180ba3f, 0x16)
	/usr/local/go/src/runtime/panic.go:617 +0x72
runtime.sysMap(0xc360000000, 0x4000000, 0x27d8878)
	/usr/local/go/src/runtime/mem_linux.go:170 +0xc7
....
....

**Comment by huangchundi** [comment]
Me too. What should I do?

**Comment by 3684993** [comment]
> Me too. What should I do?

Make more than 30G Swap , I used 100G swap and work fine.

**Comment by travisperson** [comment]
I don't believe you should be seeing that much memory use at all. You might want to try running the `paramcache` from the 0.4.6 release to make sure you have parameters on your system.

**Comment by 3684993** [comment]
> I don't believe you should be seeing that much memory use at all. You might want to try running the `paramcache` from the 0.4.6 release to make sure you have parameters on your system.

No,I have parameters on my system. and work fine now. 
Thanks.

**ipfs@filecoin:~$ free -m**
                     total        used        free      shared  buff/cache   available
Mem:           7872        5574         145           1        2151        6096
Swap:        102399        1569      100830
**ipfs@filecoin:~$ ls /var/tmp/filecoin-proof-parameters**
v11-vdf-post-6142c5095dcab8adf8698aaea24eac78035e3fefe6503b3e2f80758e4c948639.params
v11-vdf-post-6142c5095dcab8adf8698aaea24eac78035e3fefe6503b3e2f80758e4c948639.vk
v11-vdf-post-71ca99ebb6212e45b2affa16eb6e1f671c37986e84ee8b9edbf924ab45b5fdfe.params
v11-vdf-post-71ca99ebb6212e45b2affa16eb6e1f671c37986e84ee8b9edbf924ab45b5fdfe.vk
v11-zigzag-proof-of-replication-5efcf852a15bd74808bc65d6f2df146de817baea96c96e3b752e6a3349957644.params
v11-zigzag-proof-of-replication-5efcf852a15bd74808bc65d6f2df146de817baea96c96e3b752e6a3349957644.vk
v11-zigzag-proof-of-replication-a09b5cf44f640589b1b02cf823fa28269850342bcefa4878189b9b5c9ec4d2bb.params
v11-zigzag-proof-of-replication-a09b5cf44f640589b1b02cf823fa28269850342bcefa4878189b9b5c9ec4d2bb.vk
