### ISSUE TITLE
Stop ignoring heads from disconnected peers

### ISSUE THREAD

**Issue by anorth** [filecoin-project/go-filecoin#3368]
### Description
#3362 introduced a change to ignore blocks received over pubsub that originate from peers a node is not directly connected to.

A node will be connected to only a small subset of peers. Most new block messages will thus originate from peers to which the node is not connected. The Hello protocol will not be connecting to all the peers and this appears to me to just be ignoring valid blocks.

### Acceptance criteria
- Blocks received over pubsub are immediately considered for validation (without re-introducing the timeout-related problems that prompted the change).

FYI @ZenGround0

**Comment by ZenGround0** [comment]
This makes sense.  My bad for missing this.

With this perspective in mind I'll think of the right way to avoid blocking too long while syncing.

**Comment by ZenGround0** [comment]
After thinking this through my approach is to remove the `from` peer.id entirely from syncing.  We will fetch from the peers in our peer tracker only.  This prevents us from talking to strange peer ids that we may never be able to connect to as the original fix required to avoid long network timeouts.  It also addresses the concerns raised in this issue by giving nodes the opportunity to fetch data from nodes that we are not connected to.
