### ISSUE TITLE
Fetching timeout update

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/go-filecoin#3371]
### Description
Graphsync requests for 64 blocks should have a longer timeout than requests for 1 block.  We should scale timeout based on the graphsync fetcher's `recursionDepth` parameter.

Furthermore we need to keep this timeout as small as is reasonable without losing data.  Currently timeouts of ~ 2 block times blocks the node from making progress and effectively partitions the network causing forking.

### Acceptance criteria
- Measurements for estimating good defaults for a fetching a number of blocks.  Should probably do this across big geographic distances to get a more realistic idea
- Make fetching timeouts a function of recursionDepth

### Risks + pitfalls
- May be hard to measure
- If we push timeouts too low it may negatively interfere with syncing performance

### Where to begin
- Talk to @frrist and @anorth about measurement setup (they've done something like this before).
- net/graphsync_fetcher.go

**Comment by anorth** [comment]
We could implement a progress timeout rather than completion timeout, since there's a handy callback available.
