### ISSUE TITLE
Release 0.5

### ISSUE THREAD

**Issue by anorth** [filecoin-project/go-filecoin#3377]
The go-filecoin team is planning for the next release.

Label: 0.5.x
When: Week of 23 September 2019

This release will include all development work since the 0.4 series. The key new feature is a mechanism for protocol upgrades, and lifting of the code-CID-match interop check, allowing us to ship new code into a running network.

Also features integration of a new proof construction, Rational PoSt (though fault handling is not yet implemented), plus numerous improvements to stability since the somewhat-rocky 0.4 release.

As for the prior release, we'll use an extended testing period on the staging devnet (in between nightly and user). Community members with testing experience are welcome to participate as well.

Tentative dates, subject to change:

13 Sep: deadline for major changes, cut to staging devnet
14-19 Sep: manual and automated testing from team and community. Redeploy to staging devnet whenever needed.
Week of 23 Sep: target date for 0.5 release
Release notes to be published will outline the changes in more detail.

As we approach the release cut, the GitHub milestone [go-filecoin 0.5](https://github.com/filecoin-project/go-filecoin/milestone/26) will tag issues and PRs we intend to include.

We’ll announce here and in #fil-dev and #_fil-lobby channels with more details once known.

FYI @filecoin-project/go-filecoin-committers

**Comment by anorth** [comment]
Release 0.5.0 was released to staging but chain progress halted after block 7047 as all miners were slashed and lost power. They were slashed because PoSt verification failed (although some earlier PoSts verified successfully).

Debugging is ongoing in Slack channel []()

- [Node logs from chain validation](https://gist.github.com/anorth/d652a2a75253e41409b6fb403881fb22)
- [Message execution log](https://gist.github.com/anorth/78cbc3a4f29812b2a8c6d26b2ab64ccf)
- [Unit test reproducing the failing validations](https://github.com/filecoin-project/go-filecoin/pull/3428)

**Comment by anorth** [comment]
Release 0.5.3 fixed these issues and has been stable on our staging devnet for a while. We welcome more miners engaging with this network to test it ahead of planned release to the user devnet next week.

**Comment by steven004** [comment]
There are near 100 miners joined the staging-0.5.3 testing, and now about 10 online. Do we plan to run 0.5.3 on the user-devnet, or there will be another one with some fixes?

**Comment by anorth** [comment]
We plan to run 0.5.4 on the user devnet, tomorrow. This is the same as 0.5.3 with some trivial patches.

It is not unusual that most miners are offline, especially on a staging network.

**Comment by anorth** [comment]
Release 0.5.6 was deployed to the user devnet a few hours ago and looks stable. Unlike previous releases, you can generally expect code built from `master` to be able to connect to this network.
