### ISSUE TITLE
Initial node error occurs

### ISSUE THREAD

**Issue by bob2325168** [filecoin-project/go-filecoin#3383]
- Filecoin Version: <0.4.6>

**when initializing filecoin node，it occurs error:**

root@usertest:/home/user/filecoin# ./go-filecoin init --genesisfile=./fixtures/test/genesis.car --devnet-user
initializing filecoin node at /root/.filecoin
21:33:00.107  INFO     badger: All 0 tables opened in 0s
 logger.go:46
21:33:00.117  INFO     badger: All 0 tables opened in 0s
 logger.go:46
21:33:00.125  INFO     badger: All 0 tables opened in 0s
 logger.go:46
21:33:00.133  INFO     badger: All 0 tables opened in 0s
 logger.go:46
Error: Could not Init Node: unmarshal error: stream contains key "tickets", but there's no such field in structs of type types.Block

**Comment by ZenGround0** [comment]
Hey @bob2325168 you are using a newer version of `go-filecoin` than the binary version on 0.4.6 to connect to the user devnet.  There was a protocol breaking change (block header format changed) and so you see this error.  If you want to join user-devnet use the 0.4.6 binary.  

Related note: gatekeeping behavior like is going away with  the 0.5 release!
