### ISSUE TITLE
Include signature in deal query response

### ISSUE THREAD

**Issue by anorth** [filecoin-project/go-filecoin#3388]
### Description
The deal structures were reworked a bit when implementing signing (#3222), with the signature extracted to a wrapper. The CLI only returns the inner structure so the signature has been lost from output. 

### Acceptance criteria
- The deal CLI returns a `SignedResponse` instead of a `Response`.

**Comment by hazmatzo** [comment]
Let me know if you need payload information since I've spun it up on my machine recently.

**Comment by anorth** [comment]
Closed by #3389
