### ISSUE TITLE
Flaky test: TestDealWithSameDataAndDifferentMiners

### ISSUE THREAD

**Issue by acruikshank** [filecoin-project/go-filecoin#3395]
### Description

`TestDealWithSameDataAndDifferentMiners` occasionally fails in CI. This is an older command test that makes use of mining start. It should be converted to a FAST test and use the new techniques for deterministic mining (i.e. `CtxMineNext` and `CtxMineNext`).

**Comment by frrist** [comment]
closing in favor of: https://github.com/filecoin-project/go-filecoin/issues/3392
