### ISSUE TITLE
Stop slashing bootstrap miner

### ISSUE THREAD

**Issue by acruikshank** [filecoin-project/go-filecoin#3436]
### Description

The bootstrap miner does not submit PoSts. After the end of two proving periods, the bootstrap miner is susceptible to slashing (and will slash itself if it happens to win the right block). 

This is sort of ok, because it's role is to get the network off the ground and other miners should quickly take over. If, for whatever reason, the rest of the network loses all storage power (or fails to generate any storage power in 2 proving periods), the network is dead and there is no way to recover. Allowing the bootstrap miner to submit PoSts provides a fallback mechanism.

### Acceptance criteria

1. Bootstrap miner survives multiple proving periods

### Risks + pitfallst

Once the bootstrap miner starts submitting posts, it will need to pay gas charges to have these PoSts put on chain. The bootstrap miner reap some rewards for mining early on, but those rewards should decline rapidly as its relative mining power decreases. It's not clear the bootstrap miner can mine indefinitely.

The bootstrap miner does not actually have any storage, so it cannot actually prove storage. It will need to bypass proof creation and submit an empty proof (the bootstrap miner's actor bypasses verification so this is ok).

### Alternatives

Add miner actor logic to error if a slash is directed toward the bootstrap miner. The slashing logic should avoid sending slashes in that case.

**Comment by anorth** [comment]
After #3439, I don't think we need this to prevent a network halting. Since I don't expect the spec to recognize bootstrap miners in this way, I think we can close this.

**Comment by acruikshank** [comment]
#3439 reduces the chance the network will flicker out, but it doesn't eliminate it. Currently the bootstrap miner is guaranteed to get slashed after two proving periods so long as one other node has power on the network. If our other nodes (we need a name for these other than bootstrap) get slashed, and the miner that makes the last slash goes offline, then the network goes into an unrecoverable state.

This is mostly a concern for staging and other small networks. If we're OK needing to reset the network in this situation, this bug should be closed.

**Comment by anorth** [comment]
I don't think we can justify diverging from the spec for this.
