### ISSUE TITLE
Could not Init Node

### ISSUE THREAD

**Issue by nickboot** [filecoin-project/go-filecoin#3452]
# go-filecoin init --devnet-user --genesisfile=https://genesis.user.kittyhawk.wtf/genesis.car
initializing filecoin node at /root/.filecoin
22:22:00.724  INFO     badger: All 0 tables opened in 0s
 logger.go:46
22:22:00.732  INFO     badger: All 0 tables opened in 0s
 logger.go:46
22:22:00.740  INFO     badger: All 0 tables opened in 0s
 logger.go:46
22:22:00.748  INFO     badger: All 0 tables opened in 0s
 logger.go:46
Error: Could not Init Node: unmarshal error: stream contains key "nonce", but there's no such field in structs of type types.Block

# go-filecoin version (0.5.2)
commit: 73f72d731bdfb9ee0345727fed3a54036606c048

**Comment by xueqingping** [comment]
理论上:  run ./paramcache  first,  and  then  you can init node well,  bug  we can not get the parameters of V12  in china only if 爬墙

**Comment by anorth** [comment]
The 0.5.2 candidate is not compatible with the user devnet. Use the latest 0.4.x tag for the user devnet. Or you perhaps intended to connect to the staging network, currently running 0.5.2 (but soon to change).

**Comment by xueqingping** [comment]
go-filecoin init --devnet-staging  --genesisfile=https://genesis.user.kittyhawk.wtf/genesis.car
initializing filecoin node at /home/t1/.filecoin
14:37:21.506  INFO     badger: All 0 tables opened in 0s
 logger.go:46
14:37:21.640  INFO     badger: All 0 tables opened in 0s
 logger.go:46
14:37:21.739  INFO     badger: All 0 tables opened in 0s
 logger.go:46
14:37:21.839  INFO     badger: All 0 tables opened in 0s
 logger.go:46
Error: Could not Init Node: unmarshal error: stream contains key "nonce", but there's no such field in structs of type types.Block

**Comment by walkerxin** [comment]
Initializing the 0.5.3 has the same error whether use '--devnet-user' or '--devnet-staging'
Error: Could not Init Node: unmarshal error: stream contains key "nonce", but there's no such field in structs of type types.Block
