### ISSUE TITLE
Error: Could not Init Node: unmarshal error: stream contains key "nonce", but there's no such field in structs of type types.Block

### ISSUE THREAD

**Issue by lwwhome** [filecoin-project/go-filecoin#3456]
**Describe the bug**:
**When I run the 0.5.3 error as bellow：**
go-filecoin init --devnet-user --genesisfile=https://genesis.user.kittyhawk.wtf/genesis.car
initializing filecoin node at /home/xw/.filecoin
16:41:44.070  INFO     badger: All 0 tables opened in 0s
 logger.go:46
16:41:44.171  INFO     badger: All 0 tables opened in 0s
 logger.go:46
16:41:44.263  INFO     badger: All 0 tables opened in 0s
 logger.go:46
16:41:44.363  INFO     badger: All 0 tables opened in 0s
 logger.go:46
Error: Could not Init Node: unmarshal error: stream contains key "nonce", but there's no such field in structs of type types.Block

**Expected behavior**:

**Diagnostic information:**

- Filecoin Version: staging-devnet-0.5.3
- Filecoin Inspect Output: 
- Initialization Command:

**Comment by anorth** [comment]
The user devnet is running 0.4.6.

If you intend to connect to the staging devnet, please replace `user` with `staging` in your init command (two places).
