### ISSUE TITLE
Replace VMContext ancestors with interface to chain

### ISSUE THREAD

**Issue by acruikshank** [filecoin-project/go-filecoin#3457]
#### Problem

Actors need access to previous chain state in order to derive randomness from the chain. Our current solution to this is to pull some number of tipsets out of the chain, and put them in memory in the `VMContext` to supply data to the context's `SampleChainRandomness` function. 

Since our one use case for this is `SubmitPoSt` and submit PoSt needs to be able to verify late PoSts from the previous proving period, we always need to cache `proving period + proving window` tipsets (minus null blocks). This is currently set to 450. If there are no late PoSts, the most we will need to look back is the proving window (150).

Since our message calling logic doesn't not know whether or not `SampleChainRandomness` will be called, we need to generate this cache for every block we process. Since every message in a tipset is at the same height, we only need to generate the tipset cache once per tipset, but we throw it away and recalculate it each time after that. 

Generating the tipset cache would be way too expensive for query messages or preview messages. Consequently, submitPoSt cannot currently be previewed. This is a big gap in the previewing system. It would be nice to be able to query whether or not a PoSt is valid. We might have other needs for querying chain randomness in the future.

Finally, since we only provide an interface for chain randomness, keeping the entire tipset in memory is wasteful. We should only cache what we need to compute the randomness.

#### Proposal

We should replace the ancestors slice we pass to all the messaging logic with an interface to the chain. This interface should be to a cache that is persistent in memory. It should be able to pull chain state when it needs to, but maintain a memory efficient cache for chain randomness. This cache may be updated on heaviest tipset, or it may pull from the chain whenever randomness is requested at a higher block height (reorgs will still need to be accounted for).

**Comment by anorth** [comment]
👍 on the problem description.

It's not clear what "interface to the chain" looks like.
- One possibility is a fairly direct interface that talks in terms of blocks and tipsets etc, exposing the data structures directly. 
- Another is to expose very tight methods that return narrow pieces of data pre-processed for use by actors, e.g. `SampleTicket(height) []byte`.

Of these, my initial preference is for the latter. It exposes the minimum surface area, removes expensive logic from actors, gives implementation flexibility and will be easiest to fake out for testing.

**Comment by acruikshank** [comment]
Agreed that the interface should expose tight method. That may result in better optimizations (e.g. initially a cache would only need to store heights and tickets (and maybe tipSet keys).

**Comment by anorth** [comment]
See also #3025

**Comment by ZenGround0** [comment]
> Of these, my initial preference is for the latter

@anorth I agree.  See the ticket iterator from https://github.com/filecoin-project/go-filecoin/pull/3437.  This seems like roughly the interface we want.

**Comment by anorth** [comment]
FYI @icorderi . I think the new spec gives more guidance here than it used to, with the runtime having a `Randomness(e block.ChainEpoch, offset UInt) Randomness` method.

**Comment by anorth** [comment]
Closed by #3810
