### ISSUE TITLE
Can't create miner using 0.5.3 version

### ISSUE THREAD

**Issue by SmarterEric** [filecoin-project/go-filecoin#3466]
$ ./go-filecoin miner create --sectorsize=268435456 --from=t1rnsyuwalisvwtzlesb524yuoas3e4oocwaz5hga --peerid=QmZSntoMknUB915MSoDAyCoCE49zZqc1FYBRqmWeQ2qLi2 --gas-price=0.001 --gas-limit=1000 --preview=false 10

Error: Could not create miner. Please consult the documentation to setup your wallet and genesis block correctly: no actor at address t1rnsyuwalisvwtzlesb524yuoas3e4oocwaz5hga: no actor at address t1rnsyuwalisvwtzlesb524yuoas3e4oocwaz5hga: actor not found

I am not sure the command was correct or not? but the old one "go-filecoin miner create 10 100 --gas-price=0 --gas-limit=1000 --peerid QmZSntoMknUB915MSoDAyCoCE49zZqc1FYBRqmWeQ2qLi2 | jq -r '.ID'` " can not useful. 

And can you tell me how to reslove my problem.

**Comment by anorth** [comment]
The message means there is no actor (account) at the specified `from` address `t1rnsyuwalisvwtzlesb524yuoas3e4oocwaz5hga`. Confirm that there is an actor there, with funds.
