### ISSUE TITLE
0.5.3 version：can‘t compile 

### ISSUE THREAD

**Issue by ElonJelinek** [filecoin-project/go-filecoin#3475]
**Describe the bug**:

```
FILECOIN_USE_PRECOMPILED_RUST_PROOFS=true go run ./build deps
pkg-config --version
0.29.2
Installing dependencies...
go mod download
………………
………………
warning: couldn't execute `llvm-config --prefix` (error: No such file or directory (os error 2))
warning: set the LLVM_CONFIG_PATH environment variable to a valid `llvm-config` executable

error: Could not compile `sector-builder-ffi`.

To learn more, run the command again with --verbose.
make: *** [.install-rust-fil-sector-builder] Error 101
Command './scripts/install-go-sectorbuilder.sh' failed: exit status 2
```

After I installed LLVM, I still got the same error

```
tar: Error exit delayed from previous errors.
make: *** [.install-rust-fil-sector-builder] Error 1
Command './scripts/install-go-sectorbuilder.sh' failed: exit status 2
```

**Comment by frrist** [comment]
@ElonJelinek if you haven't, please see instruction here: https://docs.filecoin.io/go-filecoin-tutorial/Getting-Started.html#install-filecoin-and-its-dependencies

Please share the entire output of `FILECOIN_USE_PRECOMPILED_RUST_PROOFS=true go run ./build deps`, the above appears to be truncated.

**Comment by ElonJelinek** [comment]
> **Describe the bug**:
> 
> ```
> FILECOIN_USE_PRECOMPILED_RUST_PROOFS=true go run ./build deps
> pkg-config --version
> 0.29.2
> Installing dependencies...
> go mod download
> ………………
> ………………
> warning: couldn't execute `llvm-config --prefix` (error: No such file or directory (os error 2))
> warning: set the LLVM_CONFIG_PATH environment variable to a valid `llvm-config` executable
> 
> error: Could not compile `sector-builder-ffi`.
> 
> To learn more, run the command again with --verbose.
> make: *** [.install-rust-fil-sector-builder] Error 101
> Command './scripts/install-go-sectorbuilder.sh' failed: exit status 2
> ```
> 
> After I installed LLVM, I still got the same error
> 
> ```
> tar: Error exit delayed from previous errors.
> make: *** [.install-rust-fil-sector-builder] Error 1
> Command './scripts/install-go-sectorbuilder.sh' failed: exit status 2
> ```
