### ISSUE TITLE
0.5.3: panicked at 'assertion failed: step != 0', src/libcore/iter/adapters/mod.rs:412:9

### ISSUE THREAD

**Issue by steven004** [filecoin-project/go-filecoin#3476]
**Describe the bug**:
go-filecoin daemon crashed when trying to connect to a peer, via AutoNAT. 
(This is a guess from the log, see diagnostic information below)

**Expected behavior**:
no panic, just move on to find another peer for communication

**Diagnostic information:**
```
14:42:53.662  INFO    autonat: Discovered AutoNAT peer Qmd6xrWYHsxivfakYRy6MszTpuAiEoFbgE1LWw4EvwBpp4 notify.go:34
14:42:54.858  INFO    autonat: Discovered AutoNAT peer Qmd6xrWYHsxivfakYRy6MszTpuAiEoFbgE1LWw4EvwBpp4 notify.go:34
14:42:56.332  INFO    autonat: Discovered AutoNAT peer Qmd6xrWYHsxivfakYRy6MszTpuAiEoFbgE1LWw4EvwBpp4 notify.go:34
14:42:57.042  INFO peer-track: Tracking {peer=QmY3ZWR7VkgjL21dwPt3ALXPSrN42qcNoWVnZivJbN4mVf height=7962 head={ bafy2bzacecos4ist6byzak2gtil57m3gakxu3guaezuyftqj6dl5lsyyqstme }}, new=true, count=19 trusted=false peer_tracker.go:80
14:42:57.501 WARNI net/identi: error reading identify message:  short buffer id.go:190
14:42:57.532  INFO    autonat: Discovered AutoNAT peer Qmd6xrWYHsxivfakYRy6MszTpuAiEoFbgE1LWw4EvwBpp4 notify.go:34
thread '<unnamed>' panicked at 'assertion failed: step != 0', src/libcore/iter/adapters/mod.rs:412:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
fatal runtime error: failed to initiate panic, error 5
SIGABRT: abort
PC=0x7fff7f68b23e m=26 sigcode=0
```

More information, see: [The detailed log](https://github.com/filecoin-project/go-filecoin/files/3639290/crashlog-20190921.log)

- Filecoin Version: staging-devnet-0.5.3

**Comment by anorth** [comment]
Since this panic happened in Rust code, it's most likely a bug in filecoin-project/rust-fil-proofs. The prior log messages are probably unrelated. Could you please open the issue there instead?

**Comment by steven004** [comment]
submitted [an issue #892](https://github.com/filecoin-project/rust-fil-proofs/issues/892) in rust-fil-proofs.
