### ISSUE TITLE
Node improperly send "commitSector" messages for all sealed sectors after node is started

### ISSUE THREAD

**Issue by ridewindx** [filecoin-project/go-filecoin#3479]
**Describe the bug**:

After node mining is started, node will receive sealing results of all sectors and send "commitSector" messages for all successfully sealed sectors. But some of them may have been committed prior to this restart. They may lead to failed message sending:
```
node: failed to send commitSector message from ... to ... for sector with id ...
```

What's more, they will increase the miner owner's nonce too much, which results in those sealed but uncommitted sectors missing the committing forever:
```
Sep 23 02:53:15 gucloud go-filecoin[1252]: 02:53:15.144 ERROR       node: failed to send commitSector message from t1f6b35na4wodfalsgzdb2icw35r3dcndomltzvoq to t24uwrmws66ja4u7btolidhb2rul7tkvfhiwpbqvq for sector with id 181: failed to add message to message pool: validation error adding message to pool: message nonce (1245) is too much greater than actor nonce (755) node.go:648
Sep 23 02:53:15 gucloud go-filecoin[1252]: 02:53:15.151 ERROR       node: failed to send commitSector message from t1f6b35na4wodfalsgzdb2icw35r3dcndomltzvoq to t24uwrmws66ja4u7btolidhb2rul7tkvfhiwpbqvq for sector with id 81: failed to add message to message pool: validation error adding message to pool: message nonce (1246) is too much greater than actor nonce (755) node.go:648
Sep 23 02:53:15 gucloud go-filecoin[1252]: 02:53:15.158 ERROR       node: failed to send commitSector message from t1f6b35na4wodfalsgzdb2icw35r3dcndomltzvoq to t24uwrmws66ja4u7btolidhb2rul7tkvfhiwpbqvq for sector with id 230: failed to add message to message pool: validation error adding message to pool: message nonce (1247) is too much greater than actor nonce (755) node.go:648
```

**Expected behavior**:

When node mining starts, node should check which sealed sector has been committed to miner actor, and skip these "commitSector" messages of them.

**Diagnostic information:**

Nothing.

- Filecoin Version: `staging-devnet-0.5.3`

**Comment by anorth** [comment]
Thanks, I see all those messages too.

**Comment by anorth** [comment]
@laser are you aware of this behaviour in the sectorbuilder? It might not be there, just checking in case it's a known issue.

**Comment by laser** [comment]
@anorth 

> @laser are you aware of this behaviour in the sectorbuilder?

I was not aware of this bug, but I am now. Thank you. I just eyeballed the software and this bug has been around for some time. I will fix it ASAP.

**Comment by laser** [comment]
Note: The bug is in rust-fil-sector-builder, not go-filecoin.

**Comment by laser** [comment]
@anorth - I would be happy to submit a patch to go-filecoin that would stop the redundant commitSector messages (while we wait to upgrade go-filecoin to use a more recent version of go-sectorbuilder).

**Comment by anorth** [comment]
If that's an easy patch, very welcome. If not, it's perhaps not worth too
much as the code will move to the storage miner module.

**Comment by laser** [comment]
@anorth - I have submitted a go-filecoin patch for this issue, viewable [here](https://github.com/filecoin-project/go-filecoin/pull/3620). The source of the bug has been fixed upstream (in rust-fil-sector-builder), but is not available in the version of go-sectorbuilder consumed by go-filecoin.
