### ISSUE TITLE
Allow PoSt to be submitted in batches

### ISSUE THREAD

**Issue by ridewindx** [filecoin-project/go-filecoin#3480]
### Description

Now the PoSt must be submmited aimed at all commited sealed sectors. But with more sectors being sealed and committed, the PoSt calculating of all these sectors will be a very long time computation task. Any interruption of software or hardware when PoSt is in process will waste all the effort which has been made.

So we should consider batching the PoSt. For example, divide all committed sectors into 100 sectors a batch. This will not impact the security of the PoSt specification. And it will greatly reduce the negative effects of sudden PoSt interruption.

### Acceptance criteria

- The PoSt security is persisted.
- The computing resource waste is reduced to a minimum.

### Risks + pitfalls

The attacks to PoSt should be considered carefully. The increased `submitPoSt` messages should not put too much pressure on chain.

### Protocol Changes

The `submitPoSt' implementation in miner actor will be changed to allow batching PoSt.

### Where to begin

The `submitPoSt' implementation in miner actor.

**Comment by ZenGround0** [comment]
Hey @ridewindx thanks for filing, this issue should be reopened in the [specs](https://github.com/filecoin-project/specs) repo.
