### ISSUE TITLE
Use node builder to replace GenNode and associated calls

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/go-filecoin#3484]
### Description
When building nodes for test we should use the new node builder abstraction.

### Acceptance criteria
- All calls to `GenNode` are replaced with using the builder
- Potentially remove the other test builder `MakeNodeWithChainSeed` though that might be reserved for a follow on issue.

### Risks + pitfalls
May have to augment the node builder to handle these cases.

**Comment by anorth** [comment]
Done
