### ISSUE TITLE
golangci-lint -> go-critic dependency problem with Go 1.13

### ISSUE THREAD

**Issue by rvagg** [filecoin-project/go-filecoin#3486]
This appears when building deps, `FILECOIN_USE_PRECOMPILED_RUST_PROOFS=true go run ./build deps`:

> go: github.com/go-critic/go-critic@v0.0.0-20181204210945-ee9bf5809ead: invalid pseudo-version: does not match version-control timestamp (2019-02-10T22:04:43Z)

Same issue on `0.4.6`, `staging-devnet-0.5.3` and `master`.

Fixed with a piece from a similar problem with go-ipfs: https://github.com/ipfs/go-ipfs/pull/6604/, roughly, manually in go.mod:

```diff
-       github.com/go-critic/go-critic v0.0.0-20181204210945-ee9bf5809ead // indirect
+replace github.com/golangci/golangci-lint => github.com/mhutchinson/golangci-lint v1.17.2-0.20190819125825-d18f2136e32b
```

Compiles fine after that.

@Stebalien suggests this, which apparently has made it to go-ipfs as the final version that deals with the problem:

```
    github.com/ultraware/funlen v0.0.2 // indirect
    golang.org/x/tools v0.0.0-20190912185636-87d9f09c5d89 // indirect
    github.com/golangci/golangci-lint v1.18.0
```

although I haven't tried it yet for go-filecoin to confirm.

**Comment by Stebalien** [comment]
Note: I'd recommend _against_ replace directives whenever possible. Downstream projects depending on this project through go modules will _ignore_ replace directives defined in this project.

**Comment by rvagg** [comment]
additional: `github.com/filecoin-project/go-sectorbuilder@v0.0.0-20190801004428-e75bc9b0aaea` uses `github.com/golangci/golangci-lint@v1.17.1` so the issue isn't resolved here without dealing with that too.

**Comment by rvagg** [comment]
Removing go-critic from go.mod and updating golangci-lint to v1.18.0 in go.mod and ./go-sectorbuilder/go.mod does the trick in 0.5.6 got Go 1.13 support. Tests don't all pass though so I suppose there might be more to it.

**Comment by jonasbostoen** [comment]
I was just trying to install go-filecoin on my Ubuntu system to play around with it, but ran into the same error. Last comment by @rvagg did the trick for me too.

**Comment by anorth** [comment]
I think this is obsolete
