### ISSUE TITLE
Upgrade to Go 1.13

### ISSUE THREAD

**Issue by frrist** [filecoin-project/go-filecoin#3488]
### Description
[Go 1.13](https://blog.golang.org/) has been released. The README states that Go >= 1.12.1 is required. This issue serves as a placeholder for updating go-filecoin requirements to Go >= 1.13.0

### Risks + pitfalls
https://github.com/filecoin-project/go-filecoin/issues/3486

**Comment by shannonwells** [comment]
In progress
