### ISSUE TITLE
Versioned Objects

### ISSUE THREAD

**Issue by whyrusleeping** [filecoin-project/go-filecoin#349]
It might be nice to version our messages and blocks. That way any breaking changes we want to make to the format can be easily detected by the client. An easy way to do this with cbor would be to simply add a tag to the whole object. Cbor tags can be as small as a single byte (if the tag is smaller than a certain number) and simply prefix the rest of the object.

This can also be used to identify which object we're dealing with in certain cases (could allow us to tell if a thing is a block or a message).

**Comment by anorth** [comment]
@whyrusleeping what are your thoughts here more than a year later? If no, let's close this issue.
