### ISSUE TITLE
ProtocolUpgradeTable supports a default protocol version for unknown networks

### ISSUE THREAD

**Issue by travisperson** [filecoin-project/go-filecoin#3496]
### Description

We want to support dynamic network names. The primary use case for this is to support changing the nightly network name without requiring the addition of the network to the protocol table.

The ProtocolVersionTableBuilder would support a method which would define the protocol version returned by `VersionAt` of the `ProtocolVersionTableBuilder` when no version information is defined.

This work is in support of #3491.

### Where to begin
https://github.com/filecoin-project/go-filecoin/blob/master/version/protocol_versions.go

@acruikshank @anorth

**Comment by travisperson** [comment]
After looking at the protocol code I'm not sure if this need to be resolved prior to #3491. I don't believe we use the table yet so a missing network should affect anything at the moment. However we will need to resolve this issue before we start to handle any errors returned by `VersionAt`.

**Comment by sivoh** [comment]
I’d prefer if the protocol version table was modified to work off a prefix of the network name. So “nightly.04-10-2019” and “nightly.05-10-2019” would be the same so far as the PVT is concerned. Using a default table could cause problems. Would that solve this problem @travisperson?

**Comment by travisperson** [comment]
@sivoh I really like that idea! @anorth has another use-case for this kind of behavior which I think we can solve with networks named `ephemeral.<random>` and a protocol version entry for the `ephemeral` network with a block height of `0` and whatever protocol version we want to be used for additional adhoc networks for testing.

The exact naming / format we can discuss (don't want to use `test`) but I like the general idea.

@anorth does this seem like a reasonable design? This is also an interesting way to also support testing the protocol upgrade path of a particular network name without having to duplicate upgrade paths for a newly named network.

**Comment by anorth** [comment]
A prefix-based approach is more complicated than a default. It still requires editing the protocol version table every time a new version sequence is wanted and I forsee an empty prefix being desired in order to get that behaviour. But now how is the table evaluated? Is it ordered? Longest-match? Invariant of no sub-prefixes in keys (those questions need to be answered regardless of the empty-prefix possibility)

I don't yet see a concrete use case for the prefix approach that is not answered by the default approach, nor concrete problems that could be caused by the use of a default.

**Comment by travisperson** [comment]
> But now how is the table evaluated? Is it ordered? Longest-match?

It doesn't take it into account. It would work exactly as it is now. A simple way to conceptualize the idea is that before we call `ConfigureProtocolVersions` we are stripping the suffix. So networks `nightly`, `nightly.foo`, `nightly.bar` all result in the same invocation of `ConfigureProtocolVersions` and therefore return the same protocol table.

> It still requires editing the protocol version table every time a new version sequence is wanted and I forsee an empty prefix being desired in order to get that behaviour.

I don't understand the second half this statement. Can you define the behavior? The issue as described above does not permit protocol upgrade on a defaulted network. It forces all unknown networks to be pinned to a single protocol version (not necessarily the latest, just whatever is configured). I believe this was the original behavior we talked about.

> I don't yet see a concrete use case for the prefix approach that is not answered by the default approach

The use-case is that we could have multiple networks running the same protocol table without but with different names.

For example we could define the nightly to actually go through a series of upgrade during it's life span, while still supporting a network reset and not having to update the protocol table every day to support the new network names.

**Comment by acruikshank** [comment]
> But now how is the table evaluated? Is it ordered? Longest-match? Invariant of no sub-prefixes in keys (those questions need to be answered regardless of the empty-prefix possibility)

Sorry, I was unclear on this. The idea would be to take the prefix up some delimiter ('.', '-' or '_'). So there would be no confusion over which version table we would be using and the change to the existing logic would be trivial.

The small thing I don't like about a default is that it makes it really hard to define rules about when an upgrade on the 'default' network should take place, given that it could be any network created  for any reason.

The big thing I don't like is the (admittedly unlikely) possibility that a slight misconfiguration of the network name or the PVT could produce behavior that is entirely correct up until the point where the desired network and the default network differ. This would make for a big bump in the middle of the night.

**Comment by acruikshank** [comment]
#3512 implements the prefix proposal for clarity in this discussion.

**Comment by anorth** [comment]
Thanks. I did interpret prefix to mean simple string prefix. I see now that the proposal is for structured network names, with the first component defining the upgrade path.

In summary, sounds ok if you both want it. Go for it.

> The use-case is that we could have multiple networks running the same protocol table but with different names. For example we could ...

As a general rule I'd rather not add complexity until we have a *concrete* need rather than hypothetical, but in this case, and for the reasons @acruikshank cited above, let's do it.
