### ISSUE TITLE
(release 0.5.6 daemon connect failed) error reading identify message:  stream reset

### ISSUE THREAD

**Issue by walkerxin** [filecoin-project/go-filecoin#3499]
**Describe the bug**:
when I run "go-filecoin daemon",  it has a warning.
![daemon warning](https://user-images.githubusercontent.com/44486634/65586642-107ac000-dfb7-11e9-9c74-4ee686700250.png)

When I check connectivity and try to test connection to a peer，it's none and has an error(**Error: stream reset**) like this.
```
> go-filecoin swarm peers
> go-filecoin ping QmZGDLdQLUTi7uYTNavKwCd7SBc5KMfxzWxAyvqRQvwuiV
Error: stream reset
```
- Filecoin Version: 0.5.6

**Comment by travisperson** [comment]
Those error reading identify message are pretty common. I'm unsure of the exact issue but my first guess is it has something to do with the fact that we close libp2p connections during the hello protocol if it fails. The hello protocol currently the libp2p notify system and is kicked off on the connection event, so it probably runs at the same time as the `net/identify` protocol.

Could you provide the output of `go-filecoin version` (this is the actual git commit), and what command you used to initialize your node along with any additional configuration you may have made?

**Comment by walkerxin** [comment]
The key is that I can't ping other peers and see my node in devnet network.
```
> go-filecoin version
commit: aa08e59065d50968683aaff401d0dd07c26d52f0
# my node initialization command
> go-filecoin init --devnet-staging --genesisfile=https://genesis.user.kittyhawk.wtf/genesis.car
```

**Comment by travisperson** [comment]
It looks like you initialized your node to bootstrap to the staging network, but initialize with the user network genesis. The `QmZGDLdQLUTi7uYTNavKwCd7SBc5KMfxzWxAyvqRQvwuiV` peer is a bootstrap peer, so you are probably trying to ping a peer with the staging network genesis and the hello protocol is shutting the connection down.

```diff
- go-filecoin init --devnet-staging --genesisfile=https://genesis.user.kittyhawk.wtf/genesis.car
+ go-filecoin init --devnet-user --genesisfile=https://genesis.user.kittyhawk.wtf/genesis.car
```

Should fix your issue let me know if you continue to have issues though.

**Comment by walkerxin** [comment]
Thanks, It goes well. 
P.S. Using '--devnet-staging' is because of an error('Error: Could not Init Node: unmarshal error: stream contains key "nonce", but there's no such field in structs of type types.Block') when initialize go-filecoin 0.5.3.

**Comment by frrist** [comment]
@walkerxin feel free to close this issue if its been address.
