### ISSUE TITLE
ERROR node: setup mining failed

### ISSUE THREAD

**Issue by chenxiaolin0105** [filecoin-project/go-filecoin#3501]
![TIM图片20190925221449](https://user-images.githubusercontent.com/50695407/65609185-ef7b9480-dfe1-11e9-9fb5-509d545394eb.png)

22:06:23.970 ERROR       node: setup mining failed: failed to initialize sector builder: failed to get sector size for miner w/address t25dpwwwgrzg2wx2y4pnpnyurt3tm67lijqfbsu3i: query and deserialize failed: 'getSectorSize' query message failed: querymethod returned an error: failed to get To actor: actor not found node.go:219
Error: failed to initialize sector builder: failed to get sector size for miner w/address t25dpwwwgrzg2wx2y4pnpnyurt3tm67lijqfbsu3i: query and deserialize failed: 'getSectorSize' query message failed: querymethod returned an error: failed to get To actor: actor not found

version: 0.5.6
commit: `aa08e59065d50968683aaff401d0dd07c26d52f0`

How to solve this error?

**Comment by travisperson** [comment]
The actor `t25dpwwwgrzg2wx2y4pnpnyurt3tm67lijqfbsu3i` does not exist on the `alpha2` network. It does look like you synced the `alpha2` chain though as the height 0 tipset is correct.

Could you provide the steps you took from `go-filecoin init` forward that resulted in this issue?

**Comment by chenxiaolin0105** [comment]
This node is indeed completed synchronously, creating a miner and setting up a storage order, which has been running for about 8 hours. Another node has been storing to this node. The storage process has been stuck for more than 40 minutes, and then this error is reported.

```
Error: Post http://127.0.0.1:3453/api/client/propose-storage-deal?arg=t25dpwwwgrzg2wx2y4pnpnyurt3tm67lijqfbsu3i&arg=QmZkxnvyzqgWybgWCE2RjCEHsm3BWkvozvnCxpHsbAeJm2&arg=0&arg=28800&encoding=jso
n&stream-channels=true: EOF
```

**Comment by travisperson** [comment]
Thanks for reporting this issue, we believe we found the problem, an issue has been opened to track the work: #3508
