### ISSUE TITLE
@zenground0 -> maintainer proposal

### ISSUE THREAD

**Issue by anorth** [filecoin-project/go-filecoin#3505]
I nominate @ZenGround0 as a maintainer for go-filecoin.

@ZenGround0 is one of the longest-standing contributors to the project, familiar with its mission, goals, and constraints. A major contribution highlight is the expected consensus protocol implementation, along with various supporting pieces such as the block header structures and leader elections.

@ZenGround0 has a broad understanding of Filecoin system thanks to long tenure, and knows when further advice or knowledge is needed.

@ZenGround0 delivers some of the most thorough and thoughtful code reviews on the project, enabling us all to write better code.

@ZenGround0 has consistently modelled sound judgement, trustworthiness, civility and helpfulness.

Acceptance of this nomination requires unanimous approval of @whyrusleeping and @acruikshank. Please add your comments to this issue.

**Comment by laser** [comment]
I support this nomination, for reasons enumerated by @anorth above.

**Comment by dignifiedquire** [comment]
I support the nomination

**Comment by acruikshank** [comment]
I think this is overdue. I’m strongly in support.

**Comment by ognots** [comment]
Strongly in support

**Comment by iMiamasJohano** [comment]
Although I know that I have no rights,
I have to say:Strongly in support!

**Comment by mishmosh** [comment]
I support this nomination.

**Comment by whyrusleeping** [comment]
Sounds good to me, let's do it!
