### ISSUE TITLE
The go-filecoin process drops off automatically.

### ISSUE THREAD

**Issue by a8159236** [filecoin-project/go-filecoin#3507]
Yesterday, I installed version 0.5.6 (two machines) and everything worked well (memory usage is high). After creating the miner, I used one node to transfer a file to another node and successfully sealed it, but the dashboard has not been updated. In addition, when I looked at it the next day, I found that the go-filecoin process ended automatically. Daemon can't start up, and it's wrong. What's the reason?

01:45:56.614 ERROR       node: setup mining failed: failed to initialize sector builder: failed to get sector size for miner w/address t2rbkcir42j2ywlfyo25ecspqdj6k5y7es7xmkima: query and deserialize failed: 'getSectorSize' query message failed: querymethod returned an error: failed to get To actor: actor not found node.go:219
Error: failed to initialize sector builder: failed to get sector size for miner w/address t2rbkcir42j2ywlfyo25ecspqdj6k5y7es7xmkima: query and deserialize failed: 'getSectorSize' query message failed: querymethod returned an error: failed to get To actor: actor not found

**Comment by travisperson** [comment]
Do you have the logs stored of the `go-filecoin daemon` process? There might be some useful information in the last 1000 log lines (or whatever you can provide, full log would be amazing).

My guess is that your miner actor was reorged out of the chain. There is another issue very similar to this (https://github.com/filecoin-project/go-filecoin/issues/3501). Generally messages removed during a reorg should be added back into the message pool. However, there might be an underlying issue that resulted in this message being dropped complete.

**Comment by travisperson** [comment]
I think we found the problem for why your miner disappeared from the network (#3508), this probably also could of resulted in the node crashing as the miner actor would of disappeared.
