### ISSUE TITLE
failed to get To actor: actor not found 

### ISSUE THREAD

**Issue by wyblyf** [filecoin-project/go-filecoin#3517]
**Describe the bug**:
After ran the miner for about 5 hours,  and failed to check his status:

![image](https://user-images.githubusercontent.com/6084318/65753198-11d7f400-e141-11e9-8498-e1d3b0406389.png)

the log showed the following error:
15:40:42.014 ERROR       node: could not determine if actor created for bootstrapping: query method failed: querymethod returned an error: failed to get To actor: actor not found node.go:432
15:40:42.015 ERROR       node: could not get worker address: querymethod returned an error: failed to get To actor: actor not found node.go:437
![image](https://user-images.githubusercontent.com/6084318/65752644-ca9d3380-e13f-11e9-8e05-b1b7b7e9ddd6.png)

**Expected behavior**:
Miners run normally
**Diagnostic information:**

- Filecoin Version: 0.5.6
- Filecoin Inspect Output: 
- Initialization Command: 
go-filecoin init --devnet-user --genesisfile=https://genesis.user.kittyhawk.wtf/genesis.car

**Comment by steven004** [comment]
Try to remove the miner address in the config.json and recreate it.

**Comment by wyblyf** [comment]
Same as #3507 , recreate miner is ok. Thanks @steven004
