### ISSUE TITLE
My node cannot synchronize the latest block,Error message in log

### ISSUE THREAD

**Issue by muronglaowang** [filecoin-project/go-filecoin#3518]
08:44:30.639 ERROR       node: error in handler github.com/filecoin-project/go-filecoin/node.(*Node).processMessage-fm for topic /fil/msgs/alpha2: validation error adding message to pool: message pool contains message with same actor and nonce but different cid node.go:828
08:44:30.816 ERROR       node: error in handler github.com/filecoin-project/go-filecoin/node.(*Node).processMessage-fm for topic /fil/msgs/alpha2: validation error adding message to pool: message pool contains message with same actor and nonce but different cid node.go:828
08:44:30.955  INFO       node: error in handler github.com/filecoin-project/go-filecoin/node.(*Node).processMessage-fm for topic /fil/msgs/alpha2: validation error adding message to pool: message nonce (7546) is too much greater than actor nonce (7393) node.go:826
08:44:31.025 ERROR       node: error in handler github.com/filecoin-project/go-filecoin/node.(*Node).processMessage-fm for topic /fil/msgs/alpha2: validation error adding message to pool: message pool contains message with same actor and nonce but different cid node.go:828

**Comment by walkerxin** [comment]
This is one of errors when my node is syncing.  Is it never mind? Do you finish the synchronize? How long did it take?
