### ISSUE TITLE
Why is the account balance cleared 0? Is it a bug?

### ISSUE THREAD

**Issue by huangchundi** [filecoin-project/go-filecoin#3519]
Today, the balance of my account was inexplicably cleared, and the orders created by the miners disappeared. Why?

Thank you
Version number：0.5.6

**Comment by immartian** [comment]
Same issue here. 
I got 1000 earlier from the faucet but suddenly back to 0. The dilemma is there's no explorer can check the account history.

**Comment by eshon** [comment]
I believe this was related to the fork attack that occurred after Alphanet devnet launch of go-filecoin constantly reorganizing the chain. Please re-open if you see it again in the future.
