### ISSUE TITLE
error sending proposal: could not establish connection with peer,Peer does not support protocol

### ISSUE THREAD

**Issue by wyblyf** [filecoin-project/go-filecoin#3520]
**Describe the bug**:
create miner:
![image](https://user-images.githubusercontent.com/6084318/65779544-88451800-e17a-11e9-9d7e-e2e47e68789d.png)

Use aother machine to place an order, prompting the following error:
![image](https://user-images.githubusercontent.com/6084318/65779481-677cc280-e17a-11e9-9e20-202d898bccf1.png)

**Expected behavior**:
order success
**Diagnostic information:**

- Filecoin Version: 0.5.6
- Filecoin Inspect Output: 
- Initialization Command: 
go-filecoin init --devnet-user --genesisfile=https://genesis.user.kittyhawk.wtf/genesis.car

**Comment by merced** [comment]
Did you do "go-filecoin mining start" in you mining node?

**Comment by wyblyf** [comment]
@merced Thanks. It's my problem
