### ISSUE TITLE
My node was previously synchronized to the latest height, But it was not the latest height an hour ago and the log output is as follows

### ISSUE THREAD

**Issue by muronglaowang** [filecoin-project/go-filecoin#3521]
**01:07:42.425 WARNI net/identi: error reading identify message:  short buffer id.go:190
01:07:42.566 WARNI net/identi: error reading identify message:  short buffer id.go:190
01:07:43.056 WARNI net/identi: error reading identify message:  short buffer id.go:190
01:07:44.027 WARNI net/identi: error reading identify message:  short buffer id.go:190
01:07:44.646 WARNI net/identi: error reading identify message:  short buffer id.go:190
01:07:45.000 WARNI net/identi: error reading identify message:  short buffer id.go:190
01:07:45.778 WARNI net/identi: error reading identify message:  short buffer id.go:190
01:07:46.711 WARNI net/identi: error reading identify message:  short buffer id.go:190
01:07:47.338 WARNI net/identi: error reading identify message:  short buffer id.go:190
01:07:47.522 WARNI net/identi: error reading identify message:  short buffer id.go:190
01:07:47.968 WARNI net/identi: error reading identify message:  short buffer id.go:190
01:07:48.084 WARNI net/identi: error reading identify message:  short buffer id.go:190
01:07:48.094 WARNI net/identi: error reading identify message:  short buffer id.go:190
01:07:48.516 WARNI net/identi: error reading identify message:  short buffer id.go:190
01:07:49.010 WARNI net/identi: error reading identify message:  short buffer id.go:190
01:07:49.986 WARNI net/identi: error reading identify message:  short buffer id.go:190
01:07:50.295 WARNI net/identi: error reading identify message:  short buffer id.go:190
01:07:50.869 WARNI net/identi: error reading identify message:  short buffer id.go:190
01:07:51.097 WARNI net/identi: error reading identify message:  short buffer id.go:190
01:07:51.168 WARNI net/identi: error reading identify message:  short buffer id.go:190**

**I think the block is first synchronized to the latest height，Should always be at the latest height**:

**Diagnostic information:**
tail  -f  nohup.out

- Filecoin Version: <0.5.6-->
- Filecoin Inspect Output: 

![image](https://user-images.githubusercontent.com/41764545/65809556-f4eb0180-e1d0-11e9-8b0d-e3db249eb6e2.png)

**Comment by huaxiaone** [comment]
咋回事

**Comment by OdysLam** [comment]
+1
The node stops at random height and starts producing these errors.

Any ideas?

**Comment by deltazxm** [comment]
+1,I have encountered this problem many times.Sometimes restarting the node can be solved temporarily
