### ISSUE TITLE
Problem of compilation

### ISSUE THREAD

**Issue by Archie1978** [filecoin-project/go-filecoin#3522]
go get github.com/filecoin-project/go-filecoin
# github.com/ipfs/go-car
/home/root/workspace/go/src/github.com/ipfs/go-car/car.go:50:13: undefined: merkledag.EnumerateChildren
# github.com/ipfs/go-graphsync/ipldbridge
/home/root/workspace/go/src/github.com/ipfs/go-graphsync/ipldbridge/ipld_impl.go:18:24: undefined: traversal.TraversalConfig
/home/root/workspace/go/src/github.com/ipfs/go-graphsync/ipldbridge/ipldbridge.go:50:26: undefined: traversal.TraversalProgress
/home/root/workspace/go/src/github.com/ipfs/go-graphsync/ipldbridge/ipldbridge.go:53:24: undefined: traversal.TraversalReason
# github.com/filecoin-project/go-sectorbuilder
/home/root/workspace/go/src/github.com/filecoin-project/go-sectorbuilder/bindings.go:154:3: cannot use _cgo4 (type *[31]_Ctype_uchar) as type unsafe.Pointer in argument to _Cfunc_sector_builder_ffi_verify_seal
/home/root/workspace/go/src/github.com/filecoin-project/go-sectorbuilder/bindings.go:277:3: cannot use _cgo3 (type *[31]_Ctype_uchar) as type unsafe.Pointer in argument to _Cfunc_sector_builder_ffi_init_sector_builder

OS: 4.4.0-145-generic #171-Ubuntu SMP Tue Mar 26 12:43:40 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
CPU: Intel(R) Atom(TM) CPU D525   @ 1.80GHz
GO verions 1.13.1

How I compile go-filecoin ?

**Comment by travisperson** [comment]
What steps did you take when trying to build go-filecoin?
