### ISSUE TITLE
multiple blocks by one miner in one round

### ISSUE THREAD

**Issue by steven004** [filecoin-project/go-filecoin#3523]
**Describe the bug**:
One miner generates multiple blocks in one round to add more weight. The picture below shows the details
![image](https://user-images.githubusercontent.com/10411723/65882101-085fbd80-e3c7-11e9-8dec-454b825a40f9.png)

**Expected behavior**:
Multiple blocks generated by one miner in one round should be punished as per the spec. All of the miner's pledge collateral and all of their power is irrevocably slashed. This miner can never again produce blocks, even if they attempt to repost their collateral.

**Diagnostic information:**
- Filecoin Version: user-devnet-0.5.6

**Comment by travisperson** [comment]
Spec links

 - [faults#consensus-faults](https://github.com/filecoin-project/specs/blob/94a3cbbc6c1b3f848957730f5fff860ec8db1907/faults.md#consensus-faults)
- [expected-consensus#slashing](https://github.com/filecoin-project/specs/blob/94a3cbbc6c1b3f848957730f5fff860ec8db1907/expected-consensus.md#slashing)

**Comment by ZenGround0** [comment]
This is an expected consequence of go-filecoin not yet slashing consensus faults.  @travisperson's links spec the upcoming resolutions.

**Comment by ZenGround0** [comment]
I'll leave open and link #887 here.
