### ISSUE TITLE
Blocks were slashed!Can't be mined?What happened~

### ISSUE THREAD

**Issue by yaephin** [filecoin-project/go-filecoin#3524]
About an hour ago ,the height of the best tipset header was about _14000+_,but now when I figure out the head of the chain,the height of it is  _10701_ ,and the timestamp of it is _1569732979_ about one day and a half ago .What's more amazing,there are no more blocks being mined.So,what happened?

Previously,the chain was controled by one miner(_t2i25wumjfavhy47xtl6hdfzmy2yvq5tc5hgyee2i_),blocks were mined continuely  all by it,[referring to issue #3523](https://github.com/filecoin-project/go-filecoin/issues/3523) I can't find out why?Could anybody favour me some instructions?THANKS!

Here is the stopped head,using request api(_/show/block/$HEADCID_):
![Screenshot from 2019-09-30 22-49-09](https://user-images.githubusercontent.com/26021404/65890051-dead9300-e3d4-11e9-9b22-8387d3edf309.png)

- Filecoin Version: user-devnet-0.5.6

**Comment by ZenGround0** [comment]
Looks like #3502.  We are aware of this and have a fix in the works but a project wide meeting this week has slowed us from shipping the fix.  We want to get something out this week but it might have to wait until next week.

**Comment by huaxiaone** [comment]
fork attack
