### ISSUE TITLE
Segfault in miner actor SubmitPoSt while generating block

### ISSUE THREAD

**Issue by coder-lb** [filecoin-project/go-filecoin#3525]
**Describe the bug**:

The filecoin daemon crashes because of nil pointer deference.

**Diagnostic information:**

Here is the log:

18:19:36.881  INFO     mining: [TIMER] DefaultWorker.Generate baseTipset: { bafy2bzacedupc6xucqlpqn7fcbudpajlzi5nzxsxwd5grenjwtknusggjddiw } - elapsed time: 2.764s block_generate.go:26
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x98559f]

goroutine 38955419 [running]:
github.com/filecoin-project/go-filecoin/types.(*BlockHeight).Add(0x0, 0xc030fa7528, 0x15)
        /go/src/github.com/filecoin-project/go-filecoin/types/block_height.go:108 +0x4f
github.com/filecoin-project/go-filecoin/actor/builtin/miner.(*Actor).SubmitPoSt.func1(0x1ae2be0, 0xc051e98300, 0x1638860, 0xc02433c480)
        /go/src/github.com/filecoin-project/go-filecoin/actor/builtin/miner/miner.go:874 +0x106
github.com/filecoin-project/go-filecoin/actor.WithState(0x1ae2be0, 0xc051e98300, 0x1638860, 0xc02433c480, 0xc04381c680, 0xc04381c6f8, 0xa, 0xc013f77b60, 0x1787501)
        /go/src/github.com/filecoin-project/go-filecoin/actor/storage.go:50 +0x87
github.com/filecoin-project/go-filecoin/actor/builtin/miner.(*Actor).SubmitPoSt(0xc0001ac778, 0x1ae2be0, 0xc051e98300, 0xc011745500, 0xc0, 0xc0, 0x0, 0x1ae4560, 0xc02cce8990, 0x1ae4560, ...)
        /go/src/github.com/filecoin-project/go-filecoin/actor/builtin/miner/miner.go:867 +0x2c1
reflect.Value.call(0xc024086900, 0xc030fa74c8, 0x13, 0x182c96d, 0x4, 0xc0008df080, 0x5, 0x8, 0x8, 0xc0008df080, ...)
        /usr/local/go/src/reflect/value.go:447 +0x461
reflect.Value.Call(0xc024086900, 0xc030fa74c8, 0x13, 0xc0008df080, 0x5, 0x8, 0x4, 0x8, 0x3)
        /usr/local/go/src/reflect/value.go:308 +0xa4
github.com/filecoin-project/go-filecoin/actor.MakeTypedExport.func2(0x1ae2be0, 0xc051e98300, 0xc29accc476, 0xa, 0xc001610690, 0x1, 0x0, 0x60)
        /go/src/github.com/filecoin-project/go-filecoin/actor/export.go:94 +0x487
github.com/filecoin-project/go-filecoin/vm.send(0x1ad4040, 0xc01bcabf50, 0x19a03a0, 0xc051e98300, 0x1ac5bc0, 0xc031b37c40, 0xc009d04960, 0xc0295b42b8, 0xc09309e000, 0xbf)
        /go/src/github.com/filecoin-project/go-filecoin/vm/vm.go:54 +0x1d2
github.com/filecoin-project/go-filecoin/vm.Send(...)
        /go/src/github.com/filecoin-project/go-filecoin/vm/vm.go:21
github.com/filecoin-project/go-filecoin/consensus.(*DefaultProcessor).attemptApplyMessage(0xc035e5f980, 0x1ad4040, 0xc01bcabf50, 0xc036a312e0, 0x1ac5bc0, 0xc031b37c40, 0xc069279550, 0xc0295b42b8, 0xc009d04960, 0xc09309e000, ...)
        /go/src/github.com/filecoin-project/go-filecoin/consensus/processor.go:512 +0x7c4
github.com/filecoin-project/go-filecoin/consensus.(*DefaultProcessor).ApplyMessage(0xc035e5f980, 0x1ad4040, 0xc01bcabf50, 0x1adaec0, 0xc105af4ca0, 0x1ac5bc0, 0xc031b37c40, 0xc069279550, 0xc024e79100, 0x15, ...)
        /go/src/github.com/filecoin-project/go-filecoin/consensus/processor.go:307 +0x538
github.com/filecoin-project/go-filecoin/consensus.(*DefaultProcessor).ApplyMessagesAndPayRewards(0xc035e5f980, 0x1ad4040, 0xc00142c720, 0x1adaec0, 0xc105af4ca0, 0x1ac5bc0, 0xc031b37c40, 0xc0262b4000, 0x18c, 0x200, ...)
        /go/src/github.com/filecoin-project/go-filecoin/consensus/processor.go:562 +0x22a
github.com/filecoin-project/go-filecoin/mining.(*DefaultWorker).Generate(0xc061b00e00, 0x1ad4040, 0xc00142c720, 0xc024541cc0, 0x1, 0x1, 0xc02376cd40, 0x1, 0x1, 0xc019b36ab0, ...)
        /go/src/github.com/filecoin-project/go-filecoin/mining/block_generate.go:60 +0x58e
github.com/filecoin-project/go-filecoin/mining.(*DefaultWorker).Mine(0xc061b00e00, 0x1ad4040, 0xc00142c720, 0xc024541cc0, 0x1, 0x1, 0xc02376cd40, 0x1, 0x1, 0xc000fccb40, ...)
        /go/src/github.com/filecoin-project/go-filecoin/mining/worker.go:252 +0x1645
github.com/filecoin-project/go-filecoin/mining.(*timingScheduler).Start.func1(0xc0369452c0, 0x1ad3f80, 0xc036daab00, 0xc036da9b60, 0xc02bbda780)
        /go/src/github.com/filecoin-project/go-filecoin/mining/scheduler.go:126 +0x356
created by github.com/filecoin-project/go-filecoin/mining.(*timingScheduler).Start
        /go/src/github.com/filecoin-project/go-filecoin/mining/scheduler.go:95 +0x11b

- Filecoin Version: 0.5.6
- Filecoin Inspect Output: 

Version:        aa08e59065d50968683aaff401d0dd07c26d52f0

Runtime
OS:             linux
Arch:           amd64
Version:        go1.12.1
Compiler:       gc
NumProc:        24
GoMaxProcs:     24
NumGoRoutines:  1810
NumCGoCalls:    34140

Disk
Free:   1941979353088
Total:  1841970475008
FSType: 61267

Memory
Swap:           0
Virtual:        18862268000

**Comment by anorth** [comment]
This is very likely stale, as all the offending code has been replaced
