### ISSUE TITLE
Why my miner storage power only 268.4 MB?

### ISSUE THREAD

**Issue by SmarterEric** [filecoin-project/go-filecoin#3534]
I have stored many pieces data which was 256MB, and some of them have been reached 'complete' status, but the miner power was always 268.4 MB, never increased up, also the Filecoin Network stats only show 268.4 MB. I don't konw why some other miners can increase their power, like 'FILPool', which Proven Storage was 2.3TB.

I store many pieces 256MB data using this command:
、、、
cd $HOME/filecoin

PIECE_1_PATH=$(mktemp)
dd if=/dev/urandom of="${PIECE_1_PATH}" bs=$((1024*1024)) count=254
PIECE_1_CID=$(./go-filecoin client import < ${PIECE_1_PATH})
echo $PIECE_1_CID
./go-filecoin client propose-storage-deal t2n6mbpnld7b3sn7t2gagi6yxw2btbzo5zcqu5ara $PIECE_1_CID 0 2880
、、、

I tried store a data which size was 400MB, but it will returned a Error when I stored it into filecoin.
、、、
~/filecoin/./go-filecoin client import write.mp4 ~/filecoin/./go-filecoin client propose-storage-deal t2n6mbpnld7b3sn7t2gagi6yxw2btbzo5zcqu5ara QmXYzArFLEJmA8amuRdj42czXLiXU297KwduDmS7QB3raJ 000 20160
Error: piece is 502902764 bytes but sector size is 266338304 bytes
[japan@VM_0_16_centos ~]$
、、、

Pls give me a method how to increase up my miner storage power over 268.4 MB, thanks.

**Comment by huaxiaone** [comment]
secret
you should find out the answer by yourself

**Comment by SmarterEric** [comment]
> secret
> you should find out the answer by yourself

it's a big headache for me. I really need help, pls.

**Comment by eshon** [comment]
@SmarterEric:

> I have stored many pieces data which was 256MB, and some of them have been reached 'complete' status, but the miner power was always 268.4 MB, never increased up, also the Filecoin Network stats only show 268.4 MB. 

Is this still true? Proving your storage can take a while, your Miner has to be successfully posting proofs of storage to the network in order to earn Power. If you don't have Power, perhaps your Proofs of Storage are failing and you should check your logs for errors.

I tried store a data which size was 400MB, but it will returned a Error when I stored it into filecoin.
```
~/filecoin/./go-filecoin client import write.mp4 ~/filecoin/./go-filecoin client propose-storage-deal t2n6mbpnld7b3sn7t2gagi6yxw2btbzo5zcqu5ara QmXYzArFLEJmA8amuRdj42czXLiXU297KwduDmS7QB3raJ 000 20160
Error: piece is 502902764 bytes but sector size is 266338304 bytes
[japan@VM_0_16_centos ~]$
```
Above you're trying to store a piece which is too big for the sector size so this won't work. You need to make sure your piece is smaller than the sector size. 

This is a protocol-level requirement, in the future app developers can create better tools to help clients find storage that will match their data size.

**Comment by a8159236** [comment]
@eshon How to view the running log of filecoin? Is it stored in a file?

**Comment by a8159236** [comment]
And how to check that each transaction is correctly posted on the network?

**Comment by SmarterEric** [comment]
> @SmarterEric:
> 
> > I have stored many pieces data which was 256MB, and some of them have been reached 'complete' status, but the miner power was always 268.4 MB, never increased up, also the Filecoin Network stats only show 268.4 MB.
> 
> Is this still true? Proving your storage can take a while, your Miner has to be successfully posting proofs of storage to the network in order to earn Power. If you don't have Power, perhaps your Proofs of Storage are failing and you should check your logs for errors.
> 
> > I tried store a data which size was 400MB, but it will returned a Error when I stored it into filecoin.
> 
> ```
> ~/filecoin/./go-filecoin client import write.mp4 ~/filecoin/./go-filecoin client propose-storage-deal t2n6mbpnld7b3sn7t2gagi6yxw2btbzo5zcqu5ara QmXYzArFLEJmA8amuRdj42czXLiXU297KwduDmS7QB3raJ 000 20160
> Error: piece is 502902764 bytes but sector size is 266338304 bytes
> [japan@VM_0_16_centos ~]$
> ```
> 
> Above you're trying to store a piece which is too big for the sector size so this won't work. You need to make sure your piece is smaller than the sector size.
> 
> This is a protocol-level requirement, in the future app developers can create better tools to help clients find storage that will match their data size.

hi, before I use this command './go-filecoin client propose-storage-deal' , only show 268.4 MB power no matter how many pieces(268.4 MB) I stored.
Now, I adjusted the command adding  --allow-duplicates, like this  './go-filecoin client propose-storage-deal --allow-duplicates', and stored over 100 pieces, some of them staged, or completed, or rejected, or staging. 
![image](https://user-images.githubusercontent.com/38749449/66533682-666a6e80-eb46-11e9-8ef8-3218bf910126.png)
![image](https://user-images.githubusercontent.com/38749449/66533703-797d3e80-eb46-11e9-87b0-8f979153f8c2.png)

Also, the miner has sealed many pieces, 
![image](https://user-images.githubusercontent.com/38749449/66533787-b812f900-eb46-11e9-8af9-196f05edbc31.png)
But, why the power of the miner is still 0, and the Filecoin Network stats show 0.

**Comment by ElecRoastChicken** [comment]
fork attack happens on user devnet, peopel r working on it, wait for new version update, just have some patience and wait
