### ISSUE TITLE
Can not get mock FIL

### ISSUE THREAD

**Issue by yangjian102621** [filecoin-project/go-filecoin#3535]
The  User Devnet faucet([http://user.kittyhawk.wtf:9797](http://user.kittyhawk.wtf:9797)) service didn't work, we can not get FIL from it.

![image](https://user-images.githubusercontent.com/4746061/66389251-8725ad80-e9fa-11e9-8d52-ef8db3c880b8.png)

**Comment by AlexNiny** [comment]
I also encountered this problem. I could not apply within a certain period of time.But it is ok to apply again after half an hour, do not know why

**Comment by yangjian102621** [comment]
It's works again.
