### ISSUE TITLE
Rust depends build error.

### ISSUE THREAD

**Issue by gguoss** [filecoin-project/go-filecoin#3541]
**Describe the bug**:
Rust depends(sector-builder) build error.

**Expected behavior**:
error: failed to run custom build command for `sector-builder-ffi v0.5.2 (/Users/gavin/work/go/src/github.com/filecoin-project/go-filecoin/go-sectorbuilder/rust-fil-sector-builder/sector-builder-ffi)`

Caused by:
  process didn't exit successfully: `/Users/gavin/work/go/src/github.com/filecoin-project/go-filecoin/go-sectorbuilder/rust-fil-sector-builder/target/release/build/sector-builder-ffi-a032bdb3cf7afe60/build-script-build` (exit code: 1)
--- stdout
cargo:rerun-if-changed=src/

--- stderr
/Users/gavin/work/go/src/github.com/filecoin-project/go-filecoin/go-sectorbuilder/rust-fil-sector-builder/target/release/build/sector-builder-ffi-42f3cc1e0e436e95/out/include/sector_builder_ffi.h:16:10: fatal error: 'stdlib.h' file not found
/Users/gavin/work/go/src/github.com/filecoin-project/go-filecoin/go-sectorbuilder/rust-fil-sector-builder/target/release/build/sector-builder-ffi-42f3cc1e0e436e95/out/include/sector_builder_ffi.h:16:10: fatal error: 'stdlib.h' file not found, err: true
unable to generate bindings: ()

warning: build failed, waiting for other jobs to finish...
error[E0308]: mismatched types
  --> /Users/gavin/.cargo/git/checkouts/rust-fil-proofs-ffi-a7c885c6f6fc026a/4281e21/src/api.rs:41:17
   |
41 |                 prover_id,
   |                 ^^^^^^^^^ expected struct `storage_proofs::sector::SectorId`, found &[u8; 31]
   |
   = note: expected type `storage_proofs::sector::SectorId`
              found type `&[u8; 31]`

error[E0061]: this function takes 9 parameters but 7 parameters were supplied
  --> sector-builder/src/helpers/retrieve_piece.rs:69:30
   |
69 |       let num_bytes_unsealed = get_unsealed_range(
   |  ______________________________^
70 | |         (*sector_store).proofs_config().porep_config(),
71 | |         sector_store
72 | |             .manager()
...  |
80 | |         piece.num_bytes,
81 | |     )?;
   | |_____^ expected 9 parameters

error[E0061]: this function takes 7 parameters but 6 parameters were supplied
  --> sector-builder/src/helpers/seal.rs:42:9
   |
42 |       } = seal_internal(
   |  _________^
43 | |         (*sector_store).proofs_config().porep_config(),
44 | |         staged_sector_path,
45 | |         sealed_sector_path.clone(),
...  |
53 | |             .as_slice(),
54 | |     )?;
   | |_____^ expected 7 parameters

error[E0026]: struct `filecoin_proofs::api::SealOutput` does not have a field named `comm_r_star`
  --> sector-builder/src/helpers/seal.rs:38:9
   |
38 |         comm_r_star,
   |         ^^^^^^^^^^^ struct `filecoin_proofs::api::SealOutput` does not have this field

error[E0027]: pattern does not mention field `p_aux`
  --> sector-builder/src/helpers/seal.rs:35:9
   |
35 |       let SealOutput {
   |  _________^
36 | |         comm_r,
37 | |         comm_d,
38 | |         comm_r_star,
...  |
41 | |         piece_inclusion_proofs,
42 | |     } = seal_internal(
   | |_____^ missing field `p_aux`

error[E0308]: mismatched types
  --> /Users/gavin/.cargo/git/checkouts/rust-fil-proofs-ffi-a7c885c6f6fc026a/4281e21/src/api.rs:42:17
   |
42 |                 SectorId::from(sector_id),
   |                 ^^^^^^^^^^^^^^^^^^^^^^^^^ expected array of 32 elements, found struct `storage_proofs::sector::SectorId`
   |
   = note: expected type `[u8; 32]`
              found type `storage_proofs::sector::SectorId`

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0308`.
error: Could not compile `filecoin-proofs-ffi`.
warning: build failed, waiting for other jobs to finish...
error[E0061]: this function takes 3 parameters but 2 parameters were supplied
   --> sector-builder/src/scheduler.rs:193:21
    |
193 |                     PrivateReplicaInfo::new_faulty(path_str, sector.comm_r)
    |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected 3 parameters

error[E0061]: this function takes 3 parameters but 2 parameters were supplied
   --> sector-builder/src/scheduler.rs:195:21
    |
195 |                     PrivateReplicaInfo::new(path_str, sector.comm_r)
    |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected 3 parameters

error: aborting due to 6 previous errors

Some errors have detailed explanations: E0026, E0027, E0061.
For more information about an error, try `rustc --explain E0026`.
error: Could not compile `sector-builder`.

**Diagnostic information:**

- Filecoin Version: 0.5.7
- Filecoin Inspect Output: 
- Initialization Command: FILECOIN_USE_PRECOMPILED_RUST_PROOFS=true go run ./build deps

**Comment by git1234567outlookcom** [comment]
I also encountered this error, how to deal with it.
