### ISSUE TITLE
Breaking compatibility with 0.5 devnet (alphanet)

### ISSUE THREAD

**Issue by anorth** [filecoin-project/go-filecoin#3544]
The October 2019 [spec](https://filecoin-project.github.io/specs/) introduces some dramatic changes to how filecoin works, including:
- asks no longer on chain
- deals on chain
- a cron actor, automated arbitration, automated payments, no piece inclusion proofs
- re-defined storage miner, market and power actors
- updated tipset validation rules
- modified "surprise" rational PoSt construction
- no VDFs
- and much much more

These large changes put continued compatibility with the alphanet in conflict with development velocity. Regrettably, we will thus break the `master` branch's compatibility with the alphanet much sooner than anticipated. Code on the `0.5` release branch is expected to remain compatible, but we won't be porting these new features to that branch or performing further protocol upgrades.

@filecoin-project/go-filecoin-committers

**Comment by yaohcn** [comment]
In this case, can the test network go online on time?

**Comment by anorth** [comment]
We're launching a sequence of new devnets as we iterate towards testnet phase 2.
