### ISSUE TITLE
Nodes cannot connect to the test network

### ISSUE THREAD

**Issue by Lhehe** [filecoin-project/go-filecoin#3548]
Today, I found that the synchronization height of my node has remained unchanged, and go-filecoin has been running.
And after I tried to reinitialize the node, I didn't display my node information and synchronization on the https://stats.kittyhawk.wtf/?

**Comment by walkerxin** [comment]
Me too. Can't see my nodes in stats page whether version 0.5.6 or 0.5.7

**Comment by eshon** [comment]
From anorth:

> The network is locked up after malicious activity, the recent protocol upgrade was unable to repair it sufficiently. I'm sorry this is very frustrating for us all - we'll do something to provide a working developer network soon.

There will likely be an alternative Devnet you can try out in a couple days.
