### ISSUE TITLE
Hundreds of blocks in one tipset, how and why?!

### ISSUE THREAD

**Issue by WindMark-fengzhihen** [filecoin-project/go-filecoin#3551]
The following picture is captured just now from [the chain explorer](http://user.kittyhawk.wtf:8000/) 

<img width="1666" alt="微信图片_20191014093355" src="https://user-images.githubusercontent.com/56462271/66725545-c96d4580-ee65-11e9-9d81-0bb927926aae.png">

**Comment by anorth** [comment]
Because the go-filecoin implementation is not yet complete and does not
penalise this behaviour. It's specced though, and will be penalised
eventually.
