### ISSUE TITLE
Get chain syncing to spec

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/go-filecoin#3567]
### Description
This is a stub issue tracking updates in the design of the filecoin chain syncing subsystem in light of recent updates to the spec.  I'm writing a design doc [here](https://docs.google.com/document/d/1-meMo2rxaXVcLezpj5yDf-fOvBxE6j1Cw7p-rIwWpy8/edit?usp=sharing) and spiking code changes at #3565 

### Acceptance criteria
We can rapidly implement the spec requirements for chain syncing.

### Risks + pitfalls
Lots of new details coming from the spec require us to quickly make significant changes.  This design change is going to be complex.  The syncing spec is about 60% there.  There are a lot of unspecified details, particularly in the CHAIN_CATCHUP phase.  There are also serious disagreements about key parts of the protocol (what does block pubsub message contain is on top of the list).  This design is attempting to see the forest through the trees and set us up for success regardless of where we come out on this issues.

### Where to begin
If you haven't already, catch up on the spec changes: https://github.com/filecoin-project/specs/pull/568.  Read the design doc once I ping you here.  Then take a look at the WIP spike PR.  Both places are good for comments.

**Comment by anorth** [comment]
@ZenGround0 done?
