### ISSUE TITLE
Deterministic BLS keys for test

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/go-filecoin#3570]
### Description
@anorth points out [here](https://github.com/filecoin-project/go-filecoin/pull/3562/commits/acf5d48622639551ccd5fd01ff73500e7f97243d#r335735673) that deterministic bls keys are necessary for a certain amount of testing stability.

In order to achieve this we ideally would have `GeneratePrivateKeyFromSeed` method on the bls sigs [interface](https://github.com/filecoin-project/go-bls-sigs/blob/master/bls.go#L96).  This does not exist, we'd need to PR it into bls sigs or request help from rust proofs people.

A hack around this is to simply run private key generation in advance and store the private keys in a testing fixture.

### Acceptance criteria
One of the two solutions for deterministic bls keys.

### Where to begin
Probably start with the hack for simplicity, keeping private key strings stored in constant strings in the types testing package.

**Comment by ZenGround0** [comment]
FYI https://github.com/filecoin-project/bls-signatures/pull/17
thanks @vmx

**Comment by anorth** [comment]
Closing for #3871. When we next upgrade go-ffi, we'll get the method we need.
