### ISSUE TITLE
Align bootstrap with spec

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/go-filecoin#3582]
### Description
Currently we do two things out of line with the chain bootstrapping as currently specified
1) We start syncing from our bootstrap peers immediately after chain loading.  Instead we should block until a security condition is present.  The spec is unclear about the precise security condition because we haven't converged on the exact condition, but for now we can use something trivial like "has a single peer" to get the logic into the node.
2) We don't register for gossipsub until after our first chain sync from a bootstrapping peer via hello.  We should register immediately and bootstrap off of peers discovered through gossipsub.

### Acceptance criterian
Wait to start syncing until after a security condition is met (use something trivial for now)
Immediate subscription to gossipsub (we should get bootstrap for free through hello)

### Risks + pitfalls
Because we don't know the exact condition we likely won't get dependencies correct this time around.

### Where to begin
Prelim idea: use a latch to gatekeep dispatcher Start.  Open the latch upon security conditions being met.  Also remove pubsub latch gatekeeping.

**Comment by anorth** [comment]
@ZenGround0 anything more to do here?

**Comment by ZenGround0** [comment]
We can close this out.  To my understanding the above description is either done or out of date. Further bootstrap work falls under implementation specific hardening / nice-to-have features for operators and we can open a new issue for that during painnet hardening or user driven development.
