### ISSUE TITLE
failed to send funds

### ISSUE THREAD

**Issue by leesangcheol** [filecoin-project/go-filecoin#3604]
http://user.kittyhawk.wtf:9797 => submit => failed to send funds
Didn't this bug solve?
Help me.

**Comment by leesangcheol** [comment]
![이미지 2019-10-30 001](https://user-images.githubusercontent.com/5343181/67819887-6bde2780-fafa-11e9-9db8-de5ca418b4b3.png)
![이미지 2019-10-30 002](https://user-images.githubusercontent.com/5343181/67819903-700a4500-fafa-11e9-962b-f076ac07e05d.png)

**Comment by auqf** [comment]
why?? I'm wating on the line
