### ISSUE TITLE
Initialize go-filecoin with chain and state from CAR file.

### ISSUE THREAD

**Issue by frrist** [filecoin-project/go-filecoin#3606]
### Description
Go-filecoin can be initialized from a CAR file containing a genesis block, and when #3595 (Related issue: #3554) lands it will support initialization from a CAR file containing a pre-existing chain. As a next step, go-filecoin could support initialization with a CAR file that contains a chain and state for each transition. Doing so could allow a somewhat lengthy chain processing step to be skipped if the file comes from a trusted source.

### Acceptance criteria 
- go-filecoin init accepts a car file containing chain state transitions for initialization.

**Comment by anorth** [comment]
@frrist done?

**Comment by frrist** [comment]
Yes, thought this closed when #3595 went in.
