### ISSUE TITLE
Refund to client if miner offline?

### ISSUE THREAD

**Issue by linas** [filecoin-project/go-filecoin#3628]
**Describe the bug**:
I struck a storage deal `bafy2bzaceabmiiy5w4su6f33ovmywmye642kfckebnshy5xmxiymhm75tmckm` to store a 25MByte file for 5 days. The peer then disappeared a few hours later.
```
go-filecoin client query-storage-deal bafy2bzaceabmiiy5w4su6f33ovmywmye642kfckebnshy5xmxiymhm75tmckm
Error: error querying deal: failed to establish connection with the peer: routing: not found
```
16 hours later, the peer is still gone; I cannot get my data back:
```
/go-filecoin retrieval-client retrieve-piece t2r2pppr3ulrcwu6mgcw2pp7s5h7bstb5ktjhcxei QmYpajXBhW3SFj1CjxM9hMHeFwhvGBLM6odPPRnFUQx396
Error: failed to create stream to retrieval miner: routing: not found
```
I paid good money for storage; the miner did not honor the deal, I want my money back!

**Expected behavior**:
Money back... or at least a clearer understanding of the deal status: a cli tool to understand the status of the deal, when the miner I made the deal with has disappeared.  e.g. since the original deal called for 5 days of storage, then do I have to wait for 5 days? What if I made a 5-day deal, but want my data sooner than that? What if the miner was online for 4 days, disappeared on the 5th day, do I get 100% of my money back, or is it pro-rated? After all, a 100% data loss is catastrophic for me ... I don't want to pay just because the guy almost made it to the finish-line, but then broke down...  I don't care if the data was available for 4 days, I didn't need it then, I only need it on the 5th day...

**Diagnostic information:**

- Filecoin Version: `commit: db01e3c8d82d397268d4c334d3f8d8d0e8f74441`

- Filecoin Inspect Output: 
```
Version:	db01e3c8d82d397268d4c334d3f8d8d0e8f74441

Runtime
OS:           	linux
Arch:         	amd64
Version:      	go1.12.9
Compiler:     	gc
NumProc:      	24
GoMaxProcs:   	24
NumGoRoutines:	1127
NumCGoCalls:  	1255538

Disk
Free:  	3723243851776
Total: 	3450512195584
FSType:	61267

Memory
Swap:   	0
Virtual:	24568712000

Environment
FilAPI: 	
FilPath:	
GoPath: 	

Config
{
	"api": {
		"address": "/ip4/127.0.0.1/tcp/3453",
		"accessControlAllowOrigin": [
			"http://localhost:8080",
			"https://localhost:8080",
			"http://127.0.0.1:8080",
			"https://127.0.0.1:8080"
		],
		"accessControlAllowCredentials": false,
		"accessControlAllowMethods": [
			"GET",
			"POST",
			"PUT"
		]
	},
	"bootstrap": {
		"addresses": [
			"/dns4/user.kittyhawk.wtf/tcp/9000/ipfs/Qmd6xrWYHsxivfakYRy6MszTpuAiEoFbgE1LWw4EvwBpp4",
			"/dns4/user.kittyhawk.wtf/tcp/9001/ipfs/QmXq6XEYeEmUzBFuuKbVEGgxEpVD4xbSkG2Rhek6zkFMp4",
			"/dns4/user.kittyhawk.wtf/tcp/9002/ipfs/QmXhxqTKzBKHA5FcMuiKZv8YaMPwpbKGXHRVZcFB2DX9XY",
			"/dns4/user.kittyhawk.wtf/tcp/9003/ipfs/QmZGDLdQLUTi7uYTNavKwCd7SBc5KMfxzWxAyvqRQvwuiV",
			"/dns4/user.kittyhawk.wtf/tcp/9004/ipfs/QmZRnwmCjyNHgeNDiyT8mXRtGhP6uSzgHtrozc42crmVbg"
		],
		"minPeerThreshold": 1,
		"period": "10s"
	},
	"datastore": {
		"type": "badgerds",
		"path": "badger"
	},
	"heartbeat": {
		"beatTarget": "/dns4/backend-stats.kittyhawk.wtf/tcp/8080/ipfs/QmUWmZnpZb6xFryNDeNU7KcJ1Af5oHy7fB9npU67sseEjR",
		"beatPeriod": "3s",
		"reconnectPeriod": "10s",
		"nickname": "slopalicious"
	},
	"mining": {
		"minerAddress": "t2j3fdycaxvt7yszn224xyvb7pjumn5o225cswoei",
		"autoSealIntervalSeconds": 120,
		"storagePrice": "0.00000000000000011"
	},
	"mpool": {
		"maxPoolSize": 10000,
		"maxNonceGap": "100"
	},
	"observability": {
		"metrics": {
			"prometheusEnabled": false,
			"reportInterval": "5s",
			"prometheusEndpoint": "/ip4/0.0.0.0/tcp/9400"
		},
		"tracing": {
			"jaegerTracingEnabled": false,
			"probabilitySampler": 1,
			"jaegerEndpoint": "http://localhost:14268/api/traces"
		}
	},
	"sectorbase": {
		"rootdir": ""
	},
	"swarm": {
		"address": "/ip4/0.0.0.0/tcp/6000"
	},
	"wallet": {
		"defaultAddress": "t14dh5wp2ab5xdm4kwe7qe4log5ah3etmnkodskoi"
	}
}
```
- Initialization Command: 
```
go-filecoin init --devnet-user --genesisfile=https://genesis.user.kittyhawk.wtf/genesis.car
```

I'm definitely online:
```
/go-filecoin swarm peers |wc
     60      60    5163
```
The client I made the deal with is still listed in the ask list: 
```
./go-filecoin client list-asks |grep t2r2pp
t2r2pppr3ulrcwu6mgcw2pp7s5h7bstb5ktjhcxei 000 0.0000000000000001 29130
```
although clearly this ask is a zombie, as the miner cannot be reached.

**Comment by linas** [comment]
Hmm.  I thought I had lost 300 coins on this failed deal, but I just now discovered the coins were lost in a different way (I lost 340 coins on a ` failed to dial : all dials failed` error message. Please see https://discuss.filecoin.io/t/paying-gas-for-non-deals/583/4 for details.

**Comment by anorth** [comment]
In the current implementation, the client must explicitly recover funds by cancelling the payment channel.

However, the spec now automates deal monitoring and payment transfers on-chain, so that funds will be automatically paid or recovered. So we're not planning to improve this UX before switching to the new way.

Thanks for the detailed report.
