### ISSUE TITLE
propose-storage-deal | failed to read response: EOF

### ISSUE THREAD

**Issue by ndq880815** [filecoin-project/go-filecoin#3629]
**Describe the bug**:
I tried to propose a storage deal, but the response may return the below error content:
> Error: error sending proposal: failed to read response: EOF

Sometimes it could also be stuck for long time without any response. 
Any ideas how to solve or investigate such cases?

**Expected behavior**:
The best case may tell where is going wrong, and possibly timeout hint.

**Diagnostic information:**

`go-filecoin client propose-storage-deal t26s7sfodnvgbwucgrltjvnormym56a46f4hh7v2a QmaBZsihQpG41zCeSrsAKGp5hJ23DJX25gnGVC1WBovLgN 0 3000`

- Filecoin Version:  db01e3c8d82d397268d4c334d3f8d8d0e8f74441
- Filecoin Inspect Output: 

> Version:        db01e3c8d82d397268d4c334d3f8d8d0e8f74441
> 
> Runtime
> OS:             linux
> Arch:           amd64
> Version:        go1.12.1
> Compiler:       gc
> NumProc:        24
> GoMaxProcs:     24
> NumGoRoutines:  634
> NumCGoCalls:    2933564
> 
> Disk
> Free:   42326118400
> Total:  42326118400
> FSType: 1481003842
> 
> Memory
> Swap:           0
> Virtual:        23287604000
> 
> Environment
> FilAPI:         
> FilPath:        
> GoPath:         
> 
> Config
> {
>         "api": {
>                 "address": "/ip4/127.0.0.1/tcp/3453",
>                 "accessControlAllowOrigin": [
>                         "http://localhost:8080",
>                         "https://localhost:8080",
>                         "http://127.0.0.1:8080",
>                         "https://127.0.0.1:8080"
>                 ],
>                 "accessControlAllowCredentials": false,
>                 "accessControlAllowMethods": [
>                         "GET",
>                         "POST",
>                         "PUT"
>                 ]
>         },
>         "bootstrap": {
>                 "addresses": [
>                         "/dns4/user.kittyhawk.wtf/tcp/9000/ipfs/Qmd6xrWYHsxivfakYRy6MszTpuAiEoFbgE1LWw4EvwBpp4",
>                         "/dns4/user.kittyhawk.wtf/tcp/9001/ipfs/QmXq6XEYeEmUzBFuuKbVEGgxEpVD4xbSkG2Rhek6zkFMp4",
>                         "/dns4/user.kittyhawk.wtf/tcp/9002/ipfs/QmXhxqTKzBKHA5FcMuiKZv8YaMPwpbKGXHRVZcFB2DX9XY",
>                         "/dns4/user.kittyhawk.wtf/tcp/9003/ipfs/QmZGDLdQLUTi7uYTNavKwCd7SBc5KMfxzWxAyvqRQvwuiV",
>                         "/dns4/user.kittyhawk.wtf/tcp/9004/ipfs/QmZRnwmCjyNHgeNDiyT8mXRtGhP6uSzgHtrozc42crmVbg"
>                 ],
>                 "minPeerThreshold": 1,
>                 "period": "10s"
>         },
>         "datastore": {
>                 "type": "badgerds",
>                 "path": "badger"
>         },
>         "heartbeat": {
>                 "beatTarget": "/dns4/backend-stats.kittyhawk.wtf/tcp/8080/ipfs/QmUWmZnpZb6xFryNDeNU7KcJ1Af5oHy7fB9npU67sseEjR",
>                 "beatPeriod": "3s",
>                 "reconnectPeriod": "10s",
>                 "nickname": "Sherry"
>         },
>         "mining": {
>                 "minerAddress": "t2pvoi3egpbhb5hqnlc5jvh6mgd2emlvgvxm2g3ga",
>                 "autoSealIntervalSeconds": 120,
>                 "storagePrice": "0.0000000000001"
>         },
>         "mpool": {
>                 "maxPoolSize": 10000,
>                 "maxNonceGap": "100"
>         },
>         "observability": {
>                 "metrics": {
>                         "prometheusEnabled": false,
>                         "reportInterval": "5s",
>                         "prometheusEndpoint": "/ip4/0.0.0.0/tcp/9400"
>                 },
>                 "tracing": {
>                         "jaegerTracingEnabled": false,
>                         "probabilitySampler": 1,
>                         "jaegerEndpoint": "http://localhost:14268/api/traces"
>                 }
>         },
>         "sectorbase": {
>                 "rootdir": ""
>         },
>         "swarm": {
>                 "address": "/ip4/0.0.0.0/tcp/6000"
>         },
>         "wallet": {
>                 "defaultAddress": "t15egcthfbp2pirpexueoytonl7v5ez6kw7ymuq5a"
>         }
> }
> 

- Initialization Command:  `go-filecoin init --devnet-user --genesisfile=https://genesis.user.kittyhawk.wtf/genesis.car`

**Comment by anorth** [comment]
Now the domain of the storage market module
