### ISSUE TITLE
Mining Once / syncing race

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/go-filecoin#3638]
### Description
Integrations tests frequently assume that after a call to mining once the chain head is guaranteed to be updated.  This used to be true because the `addNewBlockFunc` used to synchronously call the syncing system.  Since the dispatcher change landed this function does not block on the syncing call and so we've been dealing with races since then.

One reasonable way forward is to build out a `chain wait` that would operate like a simple message wait and block until a certain block header is in the chain history / new head channel.

### Acceptance criteria
Remove race condition on head being set after mining.  Likely with a new chain / block waiter.

### Where to begin
Look at message waiter, introduce new chain waiting command.  Identify tests that assume mining once guarantees the new head is set.  This last part can either be done up front or lazily as test failures present themselves.

**Comment by anorth** [comment]
If it's at all possible to get a synchronous call path through the dispatcher, I'd much prefer that.

**Comment by ZenGround0** [comment]
> If it's at all possible to get a synchronous call path through the dispatcher, I'd much prefer that.

Let's do it

**Comment by anorth** [comment]
@ZenGround0 done?

**Comment by ZenGround0** [comment]
Yes!
