### ISSUE TITLE
HTTP API Documentation??

### ISSUE THREAD

**Issue by bonedaddy** [filecoin-project/go-filecoin#3654]
Is there a link to the API code? I'm primarily looking for the API model definitions, API call definitions, etc...

**Comment by anorth** [comment]
If you're referring to the API exposed by the cmd-kit based CLI mechanism, no.

The WIP REST API is documented at https://github.com/filecoin-project/filecoin-http-api, but I don't expect it to be completed and integrated until a couple of months.
