### ISSUE TITLE
go-filecoin get chain status exception 

### ISSUE THREAD

**Issue by marco-storswift** [filecoin-project/go-filecoin#3660]
**Describe the bug**:
[root@storswift205 log]$filecoin chain status
{"FetchingHead":[{"/":"bafy2bzaceddgrtn7qha67fd5h7tfylfrmqosglpskmznp2k7rudmq5usbdjgi"}],"FetchingHeight":17599,
"SyncingComplete":true,"SyncingFetchComplete":true,"SyncingHead":[{"/":"bafy2bzacebvphwrhtolyjfq6utirfpwmpmeu2ory57srvleuzlf3ela6a7un2"}],
"SyncingHeight":30563,"SyncingStarted":1573722553,"SyncingTrusted":true,"ValidatedHead":[{"/":"bafy2bzaceca2u55ilozapsef4gxek3guxqwlou2emanosuklhxusu2gndlo6w"}],
"ValidatedHeadHeight":17598}
[root@storswift205 log]$filecoin chain status
{"FetchingHead":[{"/":"bafy2bzacebhe3r7iabd3dt4k4dj74edocfvgr7d6gaiuhhxgnjivswmr4tofu"}],"FetchingHeight":17602,
"SyncingComplete":true,"SyncingFetchComplete":true,"SyncingHead":[{"/":"bafy2bzacebhe3r7iabd3dt4k4dj74edocfvgr7d6gaiuhhxgnjivswmr4tofu"}],
"SyncingHeight":17602,"SyncingStarted":1573722578,"SyncingTrusted":true,"ValidatedHead":[{"/":"bafy2bzaceca2u55ilozapsef4gxek3guxqwlou2emanosuklhxusu2gndlo6w"}],
"ValidatedHeadHeight":17598}
[root@storswift205 log]$filecoin chain status
{"FetchingHead":[{"/":"bafy2bzacebhe3r7iabd3dt4k4dj74edocfvgr7d6gaiuhhxgnjivswmr4tofu"}],"FetchingHeight":17602,
"SyncingComplete":true,"SyncingFetchComplete":true,"SyncingHead":[{"/":"bafy2bzacebhe3r7iabd3dt4k4dj74edocfvgr7d6gaiuhhxgnjivswmr4tofu"}],
"SyncingHeight":17602,"SyncingStarted":1573722578,"SyncingTrusted":true,"ValidatedHead":[{"/":"bafy2bzaceca2u55ilozapsef4gxek3guxqwlou2emanosuklhxusu2gndlo6w"}],
"ValidatedHeadHeight":17598}

**Expected behavior**:
SyncingHeight":30563,"SyncingStarted":1573722553,"SyncingTrusted":true,"ValidatedHead": in console outpur

**Diagnostic information:**

- Filecoin Version: <0.5.8>
- Filecoin Inspect Output: <SyncingHeight":30563,"SyncingStarted":1573722553,"SyncingTrusted":true,"ValidatedHead">
- Initialization Command: <filecoin chain status >

**Comment by anorth** [comment]
Closing bugs on 0.5 since so much has changed. Please open a new one if you can replicate on master.
