### ISSUE TITLE
How can expand its storage space for sectorbase?

### ISSUE THREAD

**Issue by johnsonno1** [filecoin-project/go-filecoin#3663]
My miner has an 8TB hard disk; the original setting of config.json is "sectorbase":{
"rootdir": "/home/filecoin_sector" },
I've bought a new 8TB hard disk now. How can I expand its storage space for sectorbase?

For example1, change config.json to "sectorbase":{
"rootdir": "/home/filecoin_sector", "rootdir": "/mnt/sdb/filecoin_sector" }, ?????
For example2, reuse #go-filecoin init -- sectordir=??????

Or is there a better way? Thank you!!

**Comment by lvusyy** [comment]
lvm is a good choice

**Comment by anorth** [comment]
This is now a problem for the go-storage-miner
