### ISSUE TITLE
install & test fail

### ISSUE THREAD

**Issue by rosenjiang** [filecoin-project/go-filecoin#3667]
following install instruction, when run "go run ./build test", encounter error:

pls give me some hints, thx.

--- FAIL: TestRepoAPIFile (11.89s)
    --- FAIL: TestRepoAPIFile/SetAPI_fails_if_unable_to_create_API_file (1.48s)
        fsrepo_test.go:389: 
                Error Trace:    fsrepo_test.go:389
                                                        fsrepo_test.go:436
                                                        fsrepo_test.go:382
                Error:          An error is expected but got nil.
                Test:           TestRepoAPIFile/SetAPI_fails_if_unable_to_create_API_file

**Comment by rosenjiang** [comment]
use this Getting Started:
https://docs.filecoin.io/go-filecoin-tutorial/Getting-Started.html

**Comment by lintaojlu** [comment]
I have a similar problem，how did you solve it？
