### ISSUE TITLE
Genesis construction technical debt

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/go-filecoin#3701]
### Description
We have two nearly equivalent ways of constructing genesis state / block.  We could reduce the surface area of code we need to fiddle with by removing most of the consensus / genesis logic to operate over a gengen config transformed into genesis state / block by the gengen library.

Genesis state setup isn't even close to being stable (i.e. the spec's mandate to have a *genesis chain* rather than a block which is going to require lots of code).  It is not too late to save ourselves time.

### Where to begin
functions operating over consensus Config should instead operate over genesis config

slightly different interface between callers of consensus genesis are probably what has kept us in this place for so long.  We need to address that head on and decide how to resolve differences, either by change consensus/genesis callers' guarantees (i.e. test keys instead of test addresses) or change gengen config format (i.e. allow direct address setting instead of enforcing all addresses belong with keys)

**Comment by anorth** [comment]
@ZenGround0 did your recent work resolve this?

**Comment by ZenGround0** [comment]
No, we gave gengen ownership of setupDefaultActors through copy-paste but the consensus function still exists.  The integration test work I'm on now might include this to get our tests back.
