### ISSUE TITLE
Mining worker calls into election post proof endpoint

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/go-filecoin#3703]
### Description
Currently the mining worker sleeps a blocktime.  I'm changing this in timing work to put this wait inside the mining scheduler where it belongs.  In the near future we are going to need to put time bound post proving work inside the mining worker.

### Acceptance criteria
Election post requires integrating calls into post proof generation within the mining worker.  This issue tracks that

**Comment by anorth** [comment]
@ZenGround0 done?
