### ISSUE TITLE
Pause / unpause mining during transition to / from catchup mode

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/go-filecoin#3706]
### Description
Transitioning to catchup mode should pause the mining scheduler.  Transition out of it should unpause.

### Acceptance criteria
These side effects of transitioning are written and tested.

### Risks + pitfalls
It is in scope to ensure that mining start can't begin mining when the node is not in the follow state yet.

### Where to begin
1. Add a channel to the dispatcher that sends out signals on a channel
2. Receive on this channel in a go routine within node.go
3. When mining start is called wire up these channel results to the mining scheduler Pause buttons

**Comment by anorth** [comment]
@ZenGround0 done?
