### ISSUE TITLE
chain state randomness sampling interface

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/go-filecoin#3728]
### Description
Reviewing #3726 has brought into question our `SampleRandomness` function's interface.  It relies on both a height presumably passed in from looking at one view of the chain while also relying on the separate internal view of the chain through the reader's Head function.

A seemingly safer interface against reorg misbehavior would pass in a head key.  It's unclear if there are actually any bugs existing in gfc because of this and that should be investigated.

**Comment by anorth** [comment]
Done
