### ISSUE TITLE
storage miner handles changed worker gracefully

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/go-filecoin#3729]
### Description
As of ##3726 we don't update the storage mining component in response to an updated worker key without bringing the node down and up again.  We should have a graceful way to do this for miner experience.

**Comment by anorth** [comment]
@acruikshank this is a problem for the storage mining module. Do you know if we can call it solved?

**Comment by acruikshank** [comment]
Yes, this is addressed in https://github.com/filecoin-project/go-storage-miner/pull/44.
