### ISSUE TITLE
Filecoin Consensus

### ISSUE THREAD

**Issue by whyrusleeping** [filecoin-project/go-filecoin#380]
Alright, it's about time we start moving our consensus towards being based on a 'power table' as its supposed to be, and also to start implementing expected consensus. This will be a pretty long process, so i'm going to make an attempt here at splitting it up into smaller parts. Before embarking on this process, please read through all the related issues and familiarize yourself with the design docs these work tasks are based off of.

This is an epic, and so I have created several epic issues:
- [Groundwork](https://github.com/filecoin-project/go-filecoin/issues/381)
- [Family Trees](https://github.com/filecoin-project/go-filecoin/issues/382)
- [The Return of the King Part A](https://github.com/filecoin-project/go-filecoin/issues/383)
- [edit] [The Return of the King Part B](https://github.com/filecoin-project/go-filecoin/issues/393)
- [The Phantom Menace](https://github.com/filecoin-project/go-filecoin/issues/384)
- [Awakening](https://github.com/filecoin-project/go-filecoin/issues/385)
- [The Scale of Justice](https://github.com/filecoin-project/go-filecoin/issues/386)
- [Power](https://github.com/filecoin-project/go-filecoin/issues/387)

**Comment by ZenGround0** [comment]
This epic has served its purpose.  Remaining issues tracked here belong in epics for hardening filecoin.
