### ISSUE TITLE
NewActorAddress runtime implementation computes wrong address

### ISSUE THREAD

**Issue by frrist** [filecoin-project/go-filecoin#3826]
The [spec defines](https://filecoin-project.github.io/specs/#vmruntime-implementation) the `NewActorAddress()` method to be implemented as follows:
```go
func (rt *VMContext) NewActorAddress() addr.Address {
	addrBuf := new(bytes.Buffer)

	err := rt._immediateCaller.MarshalCBOR(addrBuf)
	util.Assert(err == nil)
	err = binary.Write(addrBuf, binary.BigEndian, rt._toplevelSenderCallSeqNum)
	util.Assert(err != nil)
	err = binary.Write(addrBuf, binary.BigEndian, rt._internalCallSeqNum)
	util.Assert(err != nil)

	newAddr, err := addr.NewActorAddress(addrBuf.Bytes())
	util.Assert(err == nil)
	return newAddr
}
```

The current implementation incorrectly marshals creatorAddress as bytes instead of the expected CBOR and the omits `internalCallSeqNum` in the calculation:
https://github.com/filecoin-project/go-filecoin/blob/bfa563adeed5aa1daded4518850ecdb7b824f9ac/internal/pkg/vm/internal/vmcontext/runtime_adapter.go#L104-L111

https://github.com/filecoin-project/go-filecoin/blob/593634357fd67221ee9a8f3d39a5b77b4b2a0a6d/internal/pkg/vm/internal/vmcontext/invocation_context.go#L440-L452

**Comment by anorth** [comment]
We don't have an internalCallSeqNum. Could you please check what Lotus does? The spec may not be exactly what we want here.

**Comment by frrist** [comment]
Lotus currently has a TODO to expose the internalCallSeqNum on the VM, for now they use `uint64(0)`: https://github.com/filecoin-project/lotus/blob/testnet/3/chain/vm/spec_shim.go#L156

**Comment by anorth** [comment]
@whyrusleeping has also raised that this should use (a) the top-level sender's address rather than the caller, and (b) the pubkey address, which is reorg-proof, rather than the ID address.

**Comment by anorth** [comment]
See https://github.com/filecoin-project/specs/pull/895

**Comment by anorth** [comment]
https://github.com/filecoin-project/specs/issues/894
