### ISSUE TITLE
reson: when i build go-filecoin daemon,Error: failed to get key from keystore: no key by the given name was found;what mean is it?what should i do?

### ISSUE THREAD

**Issue by dongsheng1994** [filecoin-project/go-filecoin#3849]
**Describe the bug**:

**Expected behavior**:

**Diagnostic information:**

- Filecoin Version: 
- Filecoin Inspect Output: 
- Initialization Command:

**Comment by anorth** [comment]
Please provide more information. is this on master or a branch? Please provide reproduction steps.

**Comment by anorth** [comment]
Closing as idle. Please re-open with more information is available.
