### ISSUE TITLE
Miner penalty calculations and deductions

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/go-filecoin#3873]
### Description
According to the spec we need to deduct miners for including certain types of invalid messages.  I need to sync up with @anorth to understand this aspect of the protocol better and implement the correct thing.  cc @acruikshank who has the question: does inclusion of a syntactically invalid message lead to a miner penalty?  Do any message invalidation conditions lead to a block being dropped from a tipset?

### Acceptance criteria

consensus penaltyChecker is renamed properly and either used by the penalty checking code or moved completely out of the consensus validation package and absorbed into a mining message selection.

### Where to begin
sync with @anorth

**Comment by anorth** [comment]
I don't think we have any work to do here: it's already implemented in the VM.

This behaviour is [documented in the spec](https://filecoin-project.github.io/specs/#message-validity-and-failure).

> does inclusion of a syntactically invalid message lead to a miner penalty
It can, yes

> Do any message invalidation conditions lead to a block being dropped from a tipset
Not after syntax and signature validation.
