### ISSUE TITLE
Interop Block pubsub message

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/go-filecoin#3882]
### Description
I misread lotus code a few weeks back: it turns out the data sent over the gossipsub block topic is not a raw block header but a header with message cids.  I haven't found a good spec description 😶 but this is what it should look like:
```golang
type BlockPubSubData struct { 
  _ struct{} `cbor:",toarray"`
  Header block.Block
  BLSMsgCids []e.Cid
  SecpMsgCids []e.Cid
}
```
The cid ordering must be the same as the amt ordering (i.e. how our message store holds them).  I've gone through the trouble of writing in terms of encoding types and struct directives so this can be copy-pasted into a file.

We need to 
1) accept pubsub data assuming this format.  Introduce a new type, unmarshal into it, extract the header for sending to syncing system
2) create messages in this format: either pass cid lists along with new header in return value of mining worker OR read message arrays from message store in the block pubsub message sender (slight preference for this)

### Acceptance criteria
Block message interops with lotus

### Risks + pitfalls
This issue doesn't track making use or sense of these messages on receipt.  That's feature work I consider out of scope until optimizing for security and speed in painnet

### Where to begin
1) new type -> net validator unmarshal into it -> throw away message cids
2) choose your approach then make modifications to mining system and or pubsub message send in node/block.go

**Comment by anorth** [comment]
I plan to pass the messages in the mining output. I think this will be generally more useful for other testing and validation work too, and more efficient than re-reading from store.
