### ISSUE TITLE
DRAND -- Power table and sector set read with lookback parameter

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/go-filecoin#3976]
### Description
The sector set used to mine and validate election (soon to be winning) post and the miner and total power calculations must be read with respect to a past stateroot, not the parent.

In light of other upcoming DRAND changes and future refactors this will involve adding a chain state accessor to consensus and mining modules.  We then need to extract a method from the sampler and make it public so that we can access the lookback block for computing the power table.

**Comment by anorth** [comment]
@ZenGround0 done?
