### ISSUE TITLE
TestMinerCreateIntegration has intermittent failures

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/go-filecoin#4003]
### Description
This has been observed on latest master.  At least two separate failure behaviors have been observed: (1) the client is unable to sync any blocks from the miner and so is unable to wait for the miner create message on the chain (2) the miner is able to sync the chain from the miner but the test still times out.

### Acceptance criteria
Reproduce (should happen ~1/10 times) and debug.

### Where to begin
In the case where the chain won't sync on the client the error traces back to the miner propagating every new block to the client which then fails to sync the chain due to a graphysnc fetcher error: `failure fetching or validating headers: fetching tipset: Unable to find any untried peers`

Debugging the underlying graphsync issue by logging the graphsync error code would be a great start.

**Comment by anorth** [comment]
I believe fixed by #4064
