### ISSUE TITLE
Reinstate chain validation

### ISSUE THREAD

**Issue by acruikshank** [filecoin-project/go-filecoin#4009]
### Description

The chain validation package is out of date with new changes to specs-actors to the point where it will not compile. We need those changes now, so we've had to temporarily disable chain-validation tests. These tests need to be reintegrated once new chain-validation is available.

### Acceptance criteria

1. Code in vmcontext/testing.go and vmcontext/validation_test.go is uncommented.
2. The tests are updated to reflect new behavior of specs-actors.
3. The tests pass.

**Comment by anorth** [comment]
Ack. FYI @frrist when you come round to this.

**Comment by frrist** [comment]
In the process of updating chain-validation to specs-actors v1.0.0 now. I'll make some noise here and on comms when I have it ready.
