### ISSUE TITLE
Update power calculations to use raw byte and quality adjusted power

### ISSUE THREAD

**Issue by acruikshank** [filecoin-project/go-filecoin#4011]
### Description

Protocol changes have made the way we calculate power more complicated. We used to just have network and miner power, but now we have raw byte and quality adjusted power for both them miners and the network. 

### Acceptance criteria

1. Update power table calculations to support the new protocol.
2. Update IsWinner functionality to support the new protocol.

**Comment by anorth** [comment]
I've done much of this in #4027. Still remaining:
- remove dodgy power table logic that counts sectors by dividing power by size
- compute QA power properly from deals in gengen
