### ISSUE TITLE
Don't load entire sector metadata when sampling few

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/go-filecoin#4018]
### Description
During winning post creation and validation (and likely other places) we rely on the entire sector set being passed around.  We predict this will be a scalability bottleneck and need to adjust our design to accommodate this.  

### Acceptance criteria
State viewer must allow selective reading of sector info.  Constructs wrapping state view need to be updated to support selective sector loading.  The election machine type bundling election methods needs to be adjusted to either (1) expose the challenge generate ffi call to mining and validation, or (2) take ownership of state viewing and subsume power table operations.

### Risks + pitfalls
Currently we have messy over complex chain state access management among mining (worker), validation (expected) and the election machine.  However this might be a great opportunity to simplify.

**Comment by anorth** [comment]
I'm going in the direction of (2) above. The power table view isn't doing much any more and we should probably just remove it.
