### ISSUE TITLE
block header arrays should not serialize as cbor null

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/go-filecoin#4058]
### Description
This comes from agreement with lotus after debugging genesis file serialization issues.

This applies to both drand entry and post proof fields at genesis and the drand entries field during mining.  
### Acceptance criteria
Concretely we should always pass in 0 val slices instead of nil when filling in headers.

**Comment by anorth** [comment]
#4061 fixed up the concrete call sites. @ZenGround0 did you want to add or change anything else to prevent recurrence?

**Comment by ZenGround0** [comment]
This is good for now.  Can't think of better solutions easy enough in reach in the current state.
