### ISSUE TITLE
Configure patching specs actors SupportedProofTypes

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/go-filecoin#4101]
### Description
We need to be able to add a line to node configs which allow them to add proof types within the specs actors `SupportedProofTypes` map.  This way we can configure devnets to include the needed interop value of 512 MiB sector sizes and allow functional tests to use the checked in 2KiB preseals.

### Acceptance criteria
Config option for supported proof type.  Functional / Integration tests that work with 2KiB sectors thanks to patching

**Comment by anorth** [comment]
See https://github.com/filecoin-project/specs-actors/pull/363/files/217948049d2bf4c7a0ef660836d0ee9574911aa2#diff-2ecd9908929bba03f96f2c075d8d7ac5

Maybe we can do it like this: https://github.com/filecoin-project/go-filecoin/pull/4084

**Comment by ZenGround0** [comment]
@anorth -- yes #4084 is exactly what I'm going for.
