### ISSUE TITLE
Create separate store for nodes in test NodeBuilder

### ISSUE THREAD

**Issue by shannonwells** [filecoin-project/go-filecoin#4138]
### Description
When writing retrieval CLI tests, it was discovered that the test nodes are sharing storage.  This prevents adequate testing since the client first checks local storage before querying the specified peer;  in the tests, even though the miner node only is seemingly importing the test data, the client retrieves the data "locally", never communicating with the miner at all. 

This means that  in order to verify that data is retrieved from a peer, the code in the command line where local storage is checked must be commented out. 

This is likely to also create false positives or other problems with storage market integration/CLI tests.

### Acceptance criteria
Separate stores for each test node should be created always.  An integration test should be able to show it works.

**Comment by anorth** [comment]
Rather than a config option, nodes should always have separate stores. This sounds like an oversight in the initial test.NodeBuilder.

**Comment by shannonwells** [comment]
> Rather than a config option, nodes should always have separate stores. This sounds like an oversight in the initial test.NodeBuilder.

I edited the Issue description.

**Comment by shannonwells** [comment]
Closing in favor of #4157 which is the real issue
