### ISSUE TITLE
Nonce error in transaction body

### ISSUE THREAD

**Issue by Wangmmx** [filecoin-project/go-filecoin#4176]
I connected the node to get the nonce by using `MpoolGetNonce` to construct the transaction, then put it in the transaction body, and then signed and sent `MpoolPush`. It was successful without any error, but I found that it has never been on the chain. 

The nonce I saw from the browser was 3, and the nonce I got from the node was 8. I specified a nonce of 3 to send the transaction again and successful on chain. This means that the nonce I read from the node has no reference value at all.

 I changed the account to perform the same operation. When the gasLimit is very low, this problem will also occur. In fact, the transaction failed, but the nonce is still increasing, so that the subsequent transaction nonce is wrong.

Address: t1n64o5qeotaiawfwydw3doibwba3dsnki3syz5ba
You can see that address's nonce is 3 at 
https://filscan.io/#/address/detail?address=t1n64o5qeotaiawfwydw3doibwba3dsnki3syz5ba

Connected the node, it was 8

**Comment by anorth** [comment]
Please file this issue in https://github.com/filecoin-project/lotus
