### ISSUE TITLE
Various address Protocols cannot transfer to each other :ProtocolNotSupported("BLS")

### ISSUE THREAD

**Issue by Wangmmx** [filecoin-project/go-filecoin#4196]
When I use the secp256k1 format address to transfer funds to the bls format address, an error will be reported.
Is it that the two formats are not officially supported for mutual transfer? Or does the provided signature tool(filecoin-signing-tools) do not support it? I used the signer-npm in node.js.

If it is not supported, what should I do for offline signing?looking forward to your reply!

**Comment by anorth** [comment]
There's no protocol restriction on transfer between formats. It may be a problem with the signing tools, but you'll have to ask in that repo.

**Comment by Wangmmx** [comment]
Thanks for your reply, I will ask in that repo later
