### ISSUE TITLE
Help review and get DHT pipelining merged (go-libp2p-kad-dht)

### ISSUE THREAD

**Issue by laser** [filecoin-project/go-filecoin#433]
Split out from @whyrusleeping 's original [catch-all issue](https://app.zenhub.com/workspace/o/filecoin-project/go-filecoin/issues/351).

### Description

vyzo's _DHT Request Pipelining_ story appears to be code-complete, but requires additional tests in order for @whyrusleeping to [feel good](https://github.com/libp2p/go-libp2p-kad-dht/pull/92#issuecomment-387373843) about merging it:

> @vyzo what would make me feel better about merging this, is having a test that tests delayed responses. We could do this by using a datastore with delays (https://github.com/ipfs/go-datastore/blob/master/delayed/delayed.go) and asserting that the requests in aggregate took below a certain amount of time.

**Comment by phritz** [comment]
@ZenGround0 assigning over to you as the person with the relationship on the gfc side

**Comment by anacrolix** [comment]
I'm actively working on this now. I'm hoping to get it wrapped up soon.

**Comment by raulk** [comment]
Update: @anacrolix has been working on an alternative [pool-based approach](https://github.com/libp2p/go-libp2p-kad-dht/pull/285) to achieve the same effect (enable parallel requests to the same peer). Our tests show no worthwhile improvement under the 99th percentile, under test loads. See discussion in the linked issue for more details.

We should validate these results with more realistic loads (e.g. within an IPFS node or a DHT booster).
