### ISSUE TITLE
Update Address Format Spec

### ISSUE THREAD

**Issue by dignifiedquire** [filecoin-project/go-filecoin#440]
Based on the discussions in Lisbon, we are close to an address format that we are happy with.

Things left to do

- generate more test vectors
- resolve the issue around ID prefixes
- update https://github.com/filecoin-project/specs/pull/19 & get it merged

Notes: https://docs.google.com/document/d/105B3TMwtqK4K_Pw5sXeJ4p5Lpp2cNeoOMiLr8qd5DmE/edit#heading=h.1x7mge1w4yrh

**Comment by ZenGround0** [comment]
In light of https://github.com/filecoin-project/go-filecoin/pull/2186 I believe this is out of date.
