### ISSUE TITLE
Epic: API Refactor

### ISSUE THREAD

**Issue by dignifiedquire** [filecoin-project/go-filecoin#444]
In order to have a consistent interface exposed to the world, which is controlled through the spec and reduces boilerplate code as much as possible we want to move to an architecture depicted below:

```
                                                    ┌────────────────────────────────────────────────┐
                                                    │                   Other Node                   │
                                                    │                                                │
                                                    │                                                │
┌─────────┐┌─────────┐┌─────────┐┌───────────────┐  ├─────────┐  ┌─────────┐  ┌─────────┐  ┌─────────┤
│ Webpage ││   CLI   ││  Other  ││ Same Program  │  │ pubsub  │  │ bitswap │  │   fil   │  │switch / │
│         ││         ││ Program ││               │  │         │  │         │  │protocol │  │  swarm  │
└─────────┘└─────────┘└─────────┘└───────────────┘  └─────────┴──┴─────────┴──┴─────────┴──┴─────────┘


┌─────────┐┌─────────┐┌─────────┐┌───────────────┐  ┌─────────┐  ┌─────────┐  ┌─────────┐  ┌─────────┐
│ backend ││ backend ││ backend ││               │  │ pubsub  │  │ bitswap │  │   fil   │  │switch / │
│  HTTP   ││ Sockets ││  other  ││               │  │         │  │         │  │protocol │  │  swarm  │
└─────────┘└─────────┘└─────────┘│  lib import   │  └─────────┘  └─────────┘  └─────────┘  └─────────┘
┌───────────────────────────────┐│               │  ┌────────────────────────────────────────────────┐
│       Commands Lib API        ││               │  │               Protocol Handlers                │
│          (commands/)          ││               │  │               (libp2p protocols)               │
└───────────────────────────────┘└───────────────┘  └────────────────────────────────────────────────┘
┌────────────────────────────────────────────────┐  ┌────────────────────────────────────────────────┐
│                Programmatic API                │  │                  Protocol API                  │
│                 (node/node.go)                 │  │             (protocol/protocol.go)             │
└────────────────────────────────────────────────┘  └────────────────────────────────────────────────┘
┌────────────────────────────────────────────────┐  ┌────────────────────────────────────────────────┐
│          API function implementations          │  │       Protocol function implementations        │
│                 (node/impl.go)                 │  │               (protocol/impl.go)               │
└────────────────────────────────────────────────┘  └────────────────────────────────────────────────┘
┌────────────────────────────────────────────────────────────────────────────────────────────────────┐
│                                                                                                    │
│                                               system                                               │
│                                            (core/node/)                                            │
│                                                                                                    │
└────────────────────────────────────────────────────────────────────────────────────────────────────┘
```

The first set of steps to get there are listed out below:

## 1. Move `node/*` into `core/node/*`
  - This is just so we are free to use the `node/` space in the later steps
## 2. Create `node/node.go` and `node/impl.go`
  - `node.go` contains the interface definitions (this will move out of this repo later, so needs to be self contained)
  - `impl.go` contains the implementation for filecoin
  - Fill the interface in the style you can see in `C1`, and content wise this should be a direct map of all commands in `commands`.
## 3. Create `protocol/protocol.go` and `protocol/impl.go`
  - `protocol.go` contains the interface definitions (this will move out of this repo later, so needs to be self contained)
  - `impl.go` contains the implementation for filecoin
  - Interface style the same as in `C1`. Content is the functionality necessarry to supply the individual libp2p protocol handlers.
## 4. Codegen - Copy & Paste
   - Move `node/node.go`  and `protocol/protocol.go` into `go-filecoin/specs/interface/`
   - Vendor the specs repo using a git submodule
   - Setup a simple go generate task that simply copies the interface definitions in the locations as before, but with a header that they have been auto generated.
## 5. Codegen - Commands
  - This needs more design work, but the idea is that based on our interface definitions + the comments, we can generate all the glue code that remains in `commands/`

### C1
```go
type FilecoinNode interface {
	// Interact with actors.
	Actor() ActorAPI
}

type ActorAPI interface {
  // Returns a list of all actors on the chain.
  Ls() []*ActorView
}
```

## Open Questions

- should we merge the two different `node`s, or should they stay independent?
- is `node` the right name for the thing?
- does the proposed file structure make sense, or is there a better one?

**Comment by phritz** [comment]
#1469 has supplanted this issue
