### ISSUE TITLE
Pick a default encoding for filecoin data

### ISSUE THREAD

**Issue by frrist** [filecoin-project/go-filecoin#478]
### Description
We use [`go-multibase`](https://github.com/multiformats/go-multibase) to handle encoding and decoding data. We need to decide on a default encoding for reading values into filecoin (such as the cli command `wallet sign`), and emitting values from filecoin (such as [vouchers](https://github.com/filecoin-project/go-filecoin/pull/463/files#diff-a20fb479d940c4983fda01ab3fc52444R237) and [signatures](https://github.com/filecoin-project/go-filecoin/pull/473/files#diff-0bf3fc72ac3512f4ff27945c4a8bd3fdR188)).

These are the choices we have:
https://github.com/multiformats/go-multibase/blob/master/multibase.go#L15-L38

### Acceptance criteria
Decide on encoding for:
- **data** (binary)
- **pubkey** (a public key)
- **sig** (a signature)
- **vouchers** (payment channels)
- **dealID**'s (querying)
- .....feel free to add more as we identify them.....

#### Code:
- https://github.com/filecoin-project/go-filecoin/blob/master/commands/client.go#L204
- https://github.com/filecoin-project/go-filecoin/pull/463/files#diff-a20fb479d940c4983fda01ab3fc52444R237
- https://github.com/filecoin-project/go-filecoin/pull/473/files#diff-0bf3fc72ac3512f4ff27945c4a8bd3fdR152

#### Previous Discussion:
- https://github.com/filecoin-project/go-filecoin/pull/209#discussion_r177230178

**Comment by anorth** [comment]
I think this issue is obsolete. A new HTTP API that we are planning will answer most of these questions.
