### ISSUE TITLE
Fix `mine-once` to work with tests more reliably post-EC

### ISSUE THREAD

**Issue by aboodman** [filecoin-project/go-filecoin#504]
https://github.com/filecoin-project/go-filecoin/pull/482 introduced some wonkiness in the payment channel tests. We should fix this, as it could cause flaky tests. See: https://github.com/filecoin-project/go-filecoin/pull/482/files#r191029004

**Comment by anorth** [comment]
This issue seems stale and I'm not aware of any flakiness related to mineOnce at present. Please re-open if I'm wrong.
