### ISSUE TITLE
Design Init actor

### ISSUE THREAD

**Issue by aboodman** [filecoin-project/go-filecoin#509]
# Problem

By testnet (or at very latest) mainnet, we are going to need to be able to spawn new instances of actors from the cli or other clients.

One concrete example: we are going to want to support multisig, because this is very important functionality in most blockchains. Multisig is typically implemented via a smart contract that goes like this:

- The contract is funded and multiple signers and a signing policy is initiated
- One signer proposes a transfer
- M of N must approve the transfer, then it happens

This implies that (a) we are going to need a built-in native multisig actor, but more importantly, (b) users are going to need to be able to instantiate this actor from outside an existing actor.

We don't currently have any way to support this. Our current actors that are non-singletons are instantiated via custom code. We don't have any message a user could submit to cause an actor to get created.

# Proposal

Produce a relatively fully-fleshed out design for the init actor that covers the requirement above, and also:

- Whether our current core actors can also be instantiated via this same mechanism. Presumably the genesis block would contain messages requesting the instantiation of the core actors. This would be nice from an elegance and simplicity point of view, but it brings up other questions:
  - It'd be nice if our built-in actors continue to have hard-coded recognizable addresses as they do now (just for debuggability)
  - We'd have to think about what it might mean for multiple instances of our built-in actors to get created, and whether we want to allow that
- Can this be done without privileged APIs. We don't want to have any concept of privileged actors if we can avoid it.
- How will user-supplied actors be submitted in the future (e.g., with custom code)
- How will actors (both built-in and user-supplied) be updated

**Comment by ZenGround0** [comment]
cc @phritz @whyrusleeping @acruikshank can this get closed out?

**Comment by acruikshank** [comment]
I'm in favor of closing this. Nothing in the near term requires actor creation outside of the mechanisms we already have in place (with the possible exception of PaymentChannelActors which can probably be created by the PaymentBroker actor). Keeping more speculative issues in the queue just sows confusion.

**Comment by whyrusleeping** [comment]
We could wait until https://github.com/filecoin-project/specs/pull/169 gets in, but i'm not against closing this and replacing it with an 'implement this spec change' PR
