### ISSUE TITLE
miner actor indexes slice by an int64

### ISSUE THREAD

**Issue by phritz** [filecoin-project/go-filecoin#521]
As part of looking into https://github.com/filecoin-project/go-filecoin/issues/340 I noticed that the miner actor indexes a slice using an int64 https://github.com/filecoin-project/go-filecoin/blob/master/actor/builtin/miner/miner.go#L219. My understanding is that this is going to fail on 32-bit platforms as soon as the value is greater than int max. For example https://play.golang.org/p/lzNI3tQyMA7. 

See also discussion in #340

**Comment by ZenGround0** [comment]
@phritz @acruikshank cool to close?
