### ISSUE TITLE
As a User I can configure how & when a daemon takes config snapshots

### ISSUE THREAD

**Issue by frrist** [filecoin-project/go-filecoin#530]
### Description
Currently the filecoin daemon creates a config snapshot every time a configuration setting is modified via the `go-filecoin config set` command. A user should have:
- ability to enable and disable config snapshotting 
- ability to set an expiration on snapshots
- ability to set a limit on number of snapshots

#### Where to start
`ReplaceConfig` method triggers a snapshot 
https://github.com/filecoin-project/go-filecoin/pull/528#discussion_r194132826

**Comment by byoulten** [comment]
Hey @frrist - i am new to filecoin and am looking to learn and contribute, so i thought this would be a good place to start given its tagged as a good first issue and is low priority. Feel free to tell me if I am way off on my interpretation of the spec, but i just have a few questions about the implementation for this.

1) i had planned on adding the config values for "snapshotEnabled, snapshotExpiration, snapshotLimit", but there doesn't seem to be a relevant config struct that would intuitively encompass these values. do you think it should be in a new one ie **go-filecoin config set snapshots.snapshotEnabled**??

2) For the implementation of the snapshot expiration, did you envision this to be done using a worker process, or for the snapshot list to be curated each time a new snapshot is taken (step 1 - delete all expired snapshots then step 2 - save new snapshot). 

3) Do you think that a "snapshot" function would be useful to snapshot the config at any given moment WITHOUT requiring a change. I had a look but I can't seem to find that functionality in there, and I think it would be relatively easy to implement given the decoupled SnapshotConfig method.

Again, if I'm not on the right track let me know as this is a learning process for me.

Thanks in advance.

Ben

**Comment by frrist** [comment]
Hey Ben - sorry it has taken so long to reply, I have been taking some time off. 

I am no longer certain that configuration snapshot-ing is a feature that a _go-filecoin_ node should support. Part of me thinks it would be more appropriate to create a separate dev-tool for this purpose. I would be curious to hear the opinions of others wrt this (cc @anorth & @travisperson).

That said, given that go-filecoin already has a minimal snapshot implementation, I would feel comfortable moving forward with this. The proposal you have provided looks solid -- thank you for writing this up before proceeding ❤️. You are definitely on the right track! 

> The snapshot list to be curated each time a new snapshot is taken (step 1 - delete all expired snapshots then step 2 - save new snapshot).

I prefer this route given that this may become a separate tool down the road. 

> Do you think that a "snapshot" function would be useful to snapshot the config at any given moment WITHOUT requiring a change. 

I think there should be a method that accepts a config and creates a snapshot of it. This method should not care about the contents of the value it's handed. (So yes)

Feel free to PR the changes described here and add me as a reviewer. If you have any urgent questions I am reachable here and on the public filecoin slack.

**Comment by anorth** [comment]
Thanks @byoulten and @frrist, I concur that config snapshotting is probably not something we should work on right now. It could easily be performed externally, rather than built-in.

@byoulten welcome! Please let me know if you need help choosing another issue to get started with (I see you on our project Slack).
