### ISSUE TITLE
Remember bad blocks

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/go-filecoin#555]
### Description
From @whyrusleeping's CR of EC Pt 5:
> Caching bad block Cids is critical, and we need to do this

The chain manager should stop validating right away if its hit a block that is known to be invalid.

### Where to begin
Chain manager datastructure and validateBlock function.  Look at knownGoodBlocks for inspiration.

**Comment by frrist** [comment]
@ZenGround0 I see we have a cache bad tipsets here
https://github.com/filecoin-project/go-filecoin/blob/239bfc9367f9c2b42ec307c15ddbfe1393e01468/chain/default_syncer.go#L108-L109
and use it here
https://github.com/filecoin-project/go-filecoin/blob/239bfc9367f9c2b42ec307c15ddbfe1393e01468/chain/default_syncer.go#L454-L459

Does this satisfy this issue?
