### ISSUE TITLE
there's a funky smell and it's coming from command output encoding 

### ISSUE THREAD

**Issue by phritz** [filecoin-project/go-filecoin#599]
OK I'm sorry / not sorry to have to hand this off as I go on vacation. As part of https://github.com/filecoin-project/go-filecoin/issues/587 which you can see in https://github.com/filecoin-project/go-filecoin/pull/598 I uncovered some funky smells in our output encoding. See in particular https://github.com/filecoin-project/go-filecoin/pull/598/files#diff-e77b7ad9d6713425351aae9703d0d36bR16

First, take note of https://github.com/filecoin-project/go-filecoin/issues/266 which is almost certainly related to these problems. The issues specifically are:

1. Block.Miner doesn't make it through the nutty series of encodings in dag_daemon_test. The only reason this test passes is that the genesis block doesn't have a miner address set. Anyway, this call returns an error that is presently ignored, if you capture and assert no error on it you can see it: https://github.com/filecoin-project/go-filecoin/blob/master/commands/dag_daemon_test.go#L45

2. This test also embodies the following pattern. It gets a block two ways and then checks that they are equal. It gets the block first via `Block => json => Block`: it calls chain ls which json encodes and outputs a block from memory. Then it dag gets the cid from that block which results in `Block => IPLD node => CBOR => IPLD node => json => IPLD node => Block`. Walking you through that: the block gets turned into an ipld node which is written as cbor in the block store (`Block => IPLD node => CBOR`) and then dag get CBOR decodes it into an IPLD node and json encodes it and outputs it (`Block => IPLD node => CBOR => IPLD node => json`). Then the test json decodes back to the ipld node (`Block => IPLD node => CBOR => IPLD node => json => IPLD node`) and then decodes the ipld node as a block (bringing us all the way to `Block => IPLD node => CBOR => IPLD node => json => IPLD node => Block`). There was an issue with this test when implemented Uint64 so I wanted to write a test in block_test that specifically checked whether the block survived this sequence of transformations. I wrote the test, but it fails with the same error as above. However! The dag_daemon_test which does the should-be-logically-identical transformation passes. So, that's mystery number 2, possibly related to mystery 1.

3. I mentioned we json encode Uint64's to strings. We *have* to do this because of the way that dag_daemon_test's (old, outdated) cbor implementation works: https://github.com/ipfs/go-ipld-cbor/blob/master/node.go#L82. It uses json for a reason I don't understand, it was probably expedient. The ipld node contains bytes for Uint64's so unless we define custom json marshaling it will fail because without custom Uint64 marshaling it expects that Uint64's are marshaled as numbers (not bytes). It's a bummer to have to json encode Uint64's to a string (the LEB128 bytes are base64-encoded and js-quoted) because that makes the json output of Uint64's in commands opaque. Ick. 

4. I'd like to understand what we're shooting for output encoding wise. The sensible thing to me and i think(?) what we have been shooting for in general is to have exactly two types of output encoding for commands. 
  * human-readable output. This is a json encoding of the model object (eg, Block), meant for consumption by humans, *and should never be read by machines* because of that
  * machine-readable output. This should be something close to if not identical to the storage format, so call it raw CBOR. (I'm not sure why we json-encode it? seems like that's a transport concern).

Is that right? If so we need a pass over the code to make sure it is what we're doing.

OK, whew, popping back up. I think the place to start is with https://github.com/filecoin-project/go-filecoin/issues/266, now that it is clear that things are not well in this area of the code. Note that everything that is not dag_daemon_test uses this fork of go-ipld-cbor: https://github.com/filecoin-project/go-ipld-cbor. Once dag_daemon_test has been moved to use QmRiRJhn427YVuufBEHofLreKWNw7P7BWNq86Sb9kzqdbd like the rest of the codebase then tackling 1 and 2 above makes sense. Then once they are fixed or understood it would be amazing to look at 3, whether we can json marshal to a number (sees like we should since the new version of go-ipld-cbor uses refmt and not some hacky series of json marshals).

cc @whyrusleeping @laser @aboodman 

Edit: clarified 2 based on feedback from @travisperson in https://github.com/filecoin-project/go-filecoin/pull/598#pullrequestreview-131829176

**Comment by anorth** [comment]
I hope that this issue becomes redundant with well-defined encoding in #3098 and the CLI using that API directly.
