### ISSUE TITLE
reconciling fileccoin/ipfs go-ipld-cbor incompatibility

### ISSUE THREAD

**Issue by phritz** [filecoin-project/go-filecoin#643]
Dumping state for why, this work is still in progress.

As part of https://github.com/filecoin-project/go-filecoin/issues/599 we made a [small change](https://github.com/ipfs/go-cid/pull/55) to go-cid and released a new version (0.7.22), with the aim of  propagating the change through to go-filecoin. Since ~everything depends on go-cid, @stebalien updated a huge number of ipfs repos dependent on go-cid to the new version and released them. What remains is to update go-filecoin's dependencies to those newly released packages. 

However! go-filecoin and ipfs use different versions of go-ipld-cbor. ipfs uses [1.2.13]( https://github.com/ipfs/go-ipfs/blob/master/package.json#L206) which is built from https://github.com/ipfs/go-ipld-cbor and filecoin uses [1.4.1](https://github.com/filecoin-project/go-filecoin/blob/master/package.json#L14) which is built from a fork that lives at https://github.com/filecoin-project/go-ipld-cbor (the fork came from the [refmt branch](https://github.com/ipfs/go-ipld-cbor/tree/refmt) in the original repo). 

We have basically two options: 
1. Update ipfs to use the new go-cid-based dependencies, release it (for filecoin), and then have filecoin depend on this new version. https://github.com/ipfs/go-ipfs/pull/5243 is a WIP that updates ipfs to use the new dependencies. In order to bring it over the finish line we need to resolve the issue that ipfs and filecoin depend on incompatible versions of go-ipld-cbor: either ipfs needs to use the refmt-based fork or filecoin needs to go back to the non-refmt-based version. Not sure what would need to happen to take the new deps but make ipfs master stay dependent on 1.2.13 while moving a branch for filecoin to 1.4.5 (there's a PR out for this release) -- that's maybe the next step to investigate here.

2. Update the ipfs branch that go-filecoin depends on (release-0.4.15-rc1) to use the new go-cid-based dependencies. I started on this in https://github.com/ipfs/go-ipfs/pull/5244, i think i almost have all the deps updated but is revealing a lot of code incompatibilities: the release branch is months older than master against which the deps were presumably tested. This PR also moves ipfs from 1.2.12 to 1.4.5 (https://github.com/filecoin-project/go-ipld-cbor/pull/4 -- not merged yet bc i wanted to have a better handle on what's going on here), I'm guessing we'll need to do some fixups.

Based on how painful 2 is looking and the fact that filecoin shouldn't depend on too-stale code, I think we want to do 1. 

ps Something I haven't looked at yet is how filecoin works right now given that it depends on a version of ipfs that uses a different go-ipld-cbor version than it. I'm just dumping state so why can take a look.

**Comment by whyrusleeping** [comment]
In my most recent update, i used mainline go-ipld-cbor instead of our fork.

**Comment by phritz** [comment]
sweeeet
