### ISSUE TITLE
depend on libp2p2 dependencies via go-libp2p, don't depend on them directly

### ISSUE THREAD

**Issue by phritz** [filecoin-project/go-filecoin#664]
go-filecoin has as number of direct dependencies on parts of libp2p (eg, go-libp2p-peer) and we also depend directly on libp2p. This means that (A) we can have version conflicts where we depend on sub-deps of libp2p that are at a different version than the sub-deps depended on by the version of libp2p that we depend on and (B) we have strictly more direct deps than is necessary. We should just depend on go-libp2p for these things. 

I think what needs to happen here is:
1. for each dependency in common between libp2p and go-filecoin, remove that dependency from go-filecoin's package.json
1. verify that this works by `gx-go rewrite --undo && gx-go rewrite` so we can see it picking up the right deps from libp2p
1. commit that change
1. update go-filecoin to the newest version of go-libp2p and go-floodsub, which should address https://github.com/filecoin-project/go-filecoin/issues/643#issuecomment-407090982 (cc @dignifiedquire )

This is vaguely related to #599 in that it surfaced in #643.

**Comment by ZenGround0** [comment]
Coming back to this we need to start using gx correctly, incorporating gx-go rewrites into build process for this to start working.  The need for this has become clear during latest libp2p update attempt.

**Comment by phritz** [comment]
this doesn't feel like a priority to fix, i can't imagine us prioritizing it any time soon unless there is real pain, going to close. feel free to reopen if you disagree.
