### ISSUE TITLE
Ensure uniqueness of sector commitments

### ISSUE THREAD

**Issue by whyrusleeping** [filecoin-project/go-filecoin#764]
Since we're moving away from tying lists of deals to sectors, When miners 'commit' to a sector, we need to ensure thats not a sector that they have already used. This could be just making sure that the datastructure we hold sector commitments in is a set/map thingy.

**Comment by anorth** [comment]
`SectorCommitments` is a SectorSet, which is currently a map but will be replaced by an AMT.
