### ISSUE TITLE
Unhelpful error when sending from account with no funds

### ISSUE THREAD

**Issue by whyrusleeping** [filecoin-project/go-filecoin#803]
When attempting to send a message from an account that doesnt yet have any funds, I get a weird error: `couldn't get next nonce: actor not found`. This error makes sense to me, since I know what the problem is.

We should either: 

- Assume that a non-existent account should use a nonce of zero, or
- Return an error saying that the given account doesnt exist or doesnt have funds, or something actionable.

**Comment by deaswang** [comment]
Test on 0.3.2.
This issue need NOT to fix. 
When you new address by `go-filecoin address new`. The address is not recorded in the Node. so when you send message from the address by `go-filecoin message send`, you will get `Error: no actor at address <address>: no actor at address <address>: actor not found`. 
After fund some value to the address and spend all the value, so the balance is 0, then `go-filecoin message send` will get `Error: invalid message: balance insufficient to cover transfer+gas`, this error msg should be fine.

**Comment by frrist** [comment]
Nice, thanks for verifying this @deaswang.
