### ISSUE TITLE
Switch to gossipsub

### ISSUE THREAD

**Issue by dignifiedquire** [filecoin-project/go-filecoin#804]

**Comment by anorth** [comment]
@dignifiedquire this old issue predates many of the current contributors' tenure. Could you add some more detail so we can understand the motivation and what's needed?

**Comment by dignifiedquire** [comment]
There are two different implementations of pubsub in libp2p land, one the older one is called floodsub and a newer one called gossipsub. Gossipsub is an improvement over floodsub, but was just being finished when the work on go-filecoin started. This is about switching to it, to get the new benefits. 

More details on gossipsub can be found here: 
- https://github.com/libp2p/specs/tree/master/pubsub/gossipsub
- https://github.com/libp2p/go-libp2p-pubsub/blob/master/gossipsub.go

**Comment by anorth** [comment]
This is blocked on GossipSub exposing some needed functionality (@zenground0 has the details)
