### ISSUE TITLE
move parameters of the system to into config (eg, params.foo)

### ISSUE THREAD

**Issue by phritz** [filecoin-project/go-filecoin#884]
The task here is to 
1. Move parameters of the system that we probably want to control via config / command line options from the code to config. Any parameter that we might want to set to do an experiment, to run a cluster locally, that might differ between local and in the cloud, etc. we should make config options. And:
2. Ensure that they are nice and discoverable in the config, with default values that work well for local development. 

I don't know how many of these things there are. Some like block time are already config options. Others like mining delay are not. Your task is to scan the code to find these things. Might be helpful to scan https://docs.google.com/document/d/1p_MNXRnaTHNXTecE5KEyvtG60HxDMbW8X9pJ5r253cQ/edit for an idea of what we think of as parameters.

**Comment by anorth** [comment]
We would like to take a digest of the network parameters to use as a sanity check when a node joins the network. The network parameters are distinct from other node configuration, which may differ between interoperating nodes.

It probably makes sense for all of them to go into config, but clearly defining the difference between these two types would be very helpful.

**Comment by acruikshank** [comment]
Some thoughts: 

We can divide our parameters into 3 categories:

1. True protocol parameters. These are in the spec and a Filecoin node must use this parameter to be compliant. Block time is an example. These parameters should be hard coded and require a network fork to change.
2. Semi-protocol parameters. These are parameters that have a "good citizen" range. Node operators can tune the parameters within that range for better performance or better feedback or whatever. Tuning parameters outside that range will cause interoperability issues. Auto-seal interval is an example. A miner might tune their interval to tune the trade off between paid storage and storage power. If the interval is too high, clients will wait too long for storage and cancel payments. 
3. Non-protocol parameters. These are pure optimizations or plain config that don't affect interoperability at all. This includes things like database settings, api port, etc.

There are a lot of parameters around payments that storage clients and storage miners must agree upon (currently all hard coded) that might fall in this category or might go in the first category.  

We might want to implement validation to make sure parameters in the second category don't go out of range. We could also enforce this when two nodes connect through some protocol (but not with a hash).

CC @anorth

**Comment by anorth** [comment]
Ok, for true protocol parameters I'm not convinced they *must* be
hardcoded, but I can see some value in doing so. We will need multiple sets
of them though, e.g. for different networks.

If we put them in code, lets pull them out to a single struct which may be
exported via API and hashed for handshaking. The title of this issue should
change in that case.

**Comment by anorth** [comment]
@acruikshank this issue is quite old and our ideas have changed multiple times. With reference to the protocol versioning you are thinking about, is this issue still worth keeping open? I think we can probably replace it with something better scoped later.

**Comment by acruikshank** [comment]
Agreed. It’s still a good idea. But it’s vague and falls pretty low on our
list of priorities.
