### ISSUE TITLE
Consensus Slashing

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/go-filecoin#887]
### Description

At the highest level we need two things 
1. Detection of a slashing event
2. Communication to the network that the event has taken place.

For 1 we should rely on a simple check function kept in the consensus component which is called on each block after each block is validated but before it is put in the chain store during the main syncing loop.  We can start with a simple map from height to mining address kept in the chain store to look for double posters.

For 2 we need 
a) MUST helpers to construct a slashing message given the witness block.
b) MUST some way to send this message to the message pool from within the syncer (syncer won't be able to call the node AddMessage function).  If we have a proper notification system, great, let's use that.  If not we can hack together a solution using channels.
c) MUST new functionality in the VM to process these messages.  This should be pretty similar to the reward message in that the VM is going to need to be called into by a trusted function only reachable by a certain consensus path.
d) SHOULD some way to prioritize this message.  The message pool is accessed randomly by the miner right now.  If we want slashing to work we should guarantee that a miner doesn't sit on a slashing message. In alpha we can probably assume message pools never hold more than a block's worth of messages so my impression is we leave this for production.  Perhaps the best solution to this particular problem is sorting messages by expected profit somehow so that miner can get the best return on txs.  If we do our job right calculating the slashing reward then slashing messages should always end up near the top of this ordering.

e) ONE DAY would be cool to have a little "snitch-mining" functionality you can run from the CLI so clients who aren't interested in storage mining can run nodes that exclusively snitch on double posters for profit.  Maybe even have everyone run this by default when running a light client?

**Comment by anorth** [comment]
Closing this in favour of #2938, #2946.

The existing storage fault slashing demonstrates a good architectural pattern. I don't think this monitoring should be done within the syncer, but as a separate consumer of block pubsub messages.
