### ISSUE TITLE
implement late penalty penalization for alpha

### ISSUE THREAD

**Issue by phritz** [filecoin-project/go-filecoin#891]
High level design is here: https://github.com/filecoin-project/specs/pull/103 but a low level design / implementation plan is probably required. 

This work has to follow implementation of https://github.com/filecoin-project/go-filecoin/issues/890.

**Comment by ZenGround0** [comment]
I believe this points to a modified link as spec issues changed during open sourcing and renaming.

**Comment by phritz** [comment]
indeed, and this issue subsumed by the 'implement slashing' items on our prioritization list
