### ISSUE TITLE
Scalabe ask, bid, paymentchannel ls commands

### ISSUE THREAD

**Issue by phritz** [filecoin-project/go-filecoin#896]
@acruikshank pointed out elsewhere:

> All these list commands do full tree traversals. They're not going to scale, and aren't even very usable. Something like them will be necessary for the deal making process to work. 
>
> A more usable solution is to pass a predicate to the traversal and then post apply a sort, but that will still be a full traversal. Better solution would be to implement indexes somehow.

I'm saying this is out of scope for alpha, but we should get to it pretty quickly afterwards.

**Comment by anorth** [comment]
Ancient history
