### ISSUE TITLE
Proliferation of datastores in the FC node

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/go-filecoin#940]
### Description
The node has organically attracted a bunch of different *stores (cborstore, blockstores, datastores).  It seems like they can be condensed if we want to design for fewer stores.  Even if we don't this issue serves as an explanation of the current state of the node's storage.

Note, a few of these only show up after PR #851 lands.

### Where to begin
<img width="828" alt="screen shot 2018-09-20 at 9 16 53 am" src="https://user-images.githubusercontent.com/5515260/45821279-c6ca0c00-bcb6-11e8-9e62-596d8e89cec1.png">

<img width="826" alt="screen shot 2018-09-20 at 9 17 13 am" src="https://user-images.githubusercontent.com/5515260/45821310-dcd7cc80-bcb6-11e8-8f5b-76d13b43f3ef.png">
<img width="827" alt="screen shot 2018-09-20 at 9 17 27 am" src="https://user-images.githubusercontent.com/5515260/45821315-df3a2680-bcb6-11e8-9069-bbe2b59b1df7.png">

**Comment by anorth** [comment]
@ZenGround0 things have become a bit more sane here. Shall we close this issue?
