### ISSUE TITLE
Fix CGO linker issues when building on Windows

### ISSUE THREAD

**Issue by laser** [filecoin-project/go-filecoin#955]
### Description

Dominic [called out a linking issue](https://github.com/filecoin-project/go-filecoin/issues/935#issuecomment-423306812) which he experienced when building go-filecoin on Windows. We should fix this.

### Acceptance criteria

- [ ] go-filecoin should build w/out error on Windows

**Comment by aschmahmann** [comment]
@laser has this issue been resolved and can it be closed?

**Comment by djdv** [comment]
@aschmahmann 
There seems to be some new issues with building on Windows.
https://github.com/filecoin-project/go-filecoin/issues/935#issuecomment-466465168

**Comment by anorth** [comment]
See #2258
