### ISSUE TITLE
Decide the fate of TestNodeMining

### ISSUE THREAD

**Issue by dignifiedquire** [filecoin-project/go-filecoin#975]
In https://github.com/filecoin-project/go-filecoin/pull/894/commits/3f49b8a7b0f00b592dbbfc5ce92dbdd5cfd2aacb I disabled `TestNodeMining` because it relies on so much internal state being faked and manually set up that it just became a liability to keep fixing it. 

We should either delete it, or rewrite it such that it properly tests things, without continually needing to be fixed.

**Comment by phritz** [comment]
this test was taken out back and shot, and nobody noticed. good riddance.
